Kong/kong

- kong/db/schema/entities/ca_certificates.lua
* localize some functions
* replace `string.gmatch` to `string.find`
* `to_hex()` will never return `nil`, we should check `x509:digest()`
> refactor(db/schema): optimize ca cert validation

- CHANGELOG.md
- kong/pdk/request.lua
- kong/plugins/request-termination/handler.lua
- spec/03-plugins/14-request-termination/02-access_spec.lua
- t/01-pdk/04-request/21-get_uri_captures.t
request terminator 'echo' option would not return the uri-captures. And when  it did, the array part was not returned as an array.
> fix(request-terminator): add the missing captures in the echo

- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
The `certificates` admin API is used directly in this test block without truncating the tables, if the same sni name is created in another spec file, then collision will occur.
[FTI-4846](https://konghq.atlassian.net/browse/FTI-4846)
[FTI-4846]: https://konghq.atlassian.net/browse/FTI-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(test): prevent potential sni names collision across different test files

- kong/db/schema/init.lua
- spec/01-unit/01-db/01-schema/01-schema_spec.lua
When a schema shorthand type check validation failed in a nested record, the error was not handled correctly, producing failures in setting the configuration that were hard to idenfity due to the missing error.
KAG-851
> fix(schema): nested record shorthand type check

- .github/matrix-commitly.yml
- .github/workflows/release.yml
- build/tests/03-http2-admin-api.sh
- build/tests/util.sh
This PR adds a simple smoke test to check if the HTTP/2 listening port can respond with valid response data.
KAG-854
> chore(tests): add http2 smoke test

- build/kong_bindings.bzl
- build/openresty/wasmx/wasmx_repositories.bzl
- kong/templates/nginx.lua
- spec/fixtures/custom_nginx.template
Set the needed vars to build on macos.
Will not work when using V8 and ARM at the same time.
> fix(build): build wasmx support on macos

- CHANGELOG.md
#10463 missed the change log entry.
> docs(changelog): bumped lua-resty-openssl to 0.8.18

- build/tests/01-base.sh
string to be tested was `built with OpenSSL 1.1.0 (compatible; BoringSSL) (running with BoringSSL)` not including the git sha
> fix(tests): use openssl API version instead of BoringSSL git sha in tests

- CHANGELOG.md
- build/dockerfiles/entrypoint.sh
This change adds a clean-up step to remove all sockets that a previous Kong run may have left in $PREFIX directory.
Dangling unix sockets have been a pain point in recent Kong versions and was dealt in traditional Kong in https://github.com/Kong/kong/pull/9254, but the kong script is not called when starting Kong inside a container, so a similar change to `dockerfiles/entrypoint.sh` was added here.
FTI-4525
> fix(dockerfiles): clean up dangling sockets

- kong/pdk/service/response.lua
Relates to Kong/docs.konghq.com#5147
* [Minor correction of return value description of kong.service.response.get_body]
Fix Kong/docs.konghq.com#5147
> Fix return value description of get_body

- .github/workflows/label-schema.yml
Allow failure for the schema-change-labels job.
This will make the job fail silently on fork PRs, since they are unable to access the secret that is required to complete this workflow.
Please feel free to propose better alternatives.
> chore(workflows): allow errors in schema-change-labels job

- .github/stale.yml
With this change, all PRs and issues are subject to automatic timeout after 28 days of inactivity.
KAG-875
> Summary: chore(*): reconfigure automatic closing of issues and PRs

- CHANGELOG.md
- kong-3.2.1-0.rockspec
bump resty-openssl to 0.8.20
add missing change log entry for resty-timer-ng 0.2.4
> chore(deps): bump resty-openssl to 0.8.20

- CHANGELOG.md
- kong/clustering/compat/removed_fields.lua
- kong/plugins/proxy-cache/handler.lua
- kong/plugins/proxy-cache/schema.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
The proxy-cache plugin uri input is taken straight from `ngx.var.request` and when incoming requests are randomized with lowercase and uppercase letters, all requests are handled as new ones.
The issue with this is that the proxy-cache sees then as unique requests, even if the backend request response is exactly the same and the cache-key should therefore be possible to set to lowercase that upstream servers are not receiving unnecessary requests.
Example of requests being randomized and handled as unique cache entries:
* `/api/greeting/tobias`
* `/api/greeting/Tobias`
* `/api/greeting/tObIaS`
Default of the `ignore_uri_case` is `false` and the cache-key will be based on the actual `ngx.var.request`, but when setting the parameter to `true` instead, it will be lowercased instead.
* …
> feat(proxy-cache): add ignore_uri_case to configuring cache-key uri to be handled as lowercase

- spec/02-integration/03-db/20-ttl-cleanup_spec.lua
This should reduce the time consuming on ttl test and reduce flakiness.
KAG-921
> chore(tests): fix ttl cleanup flakiness

- .devcontainer/devcontainer.json
- scripts/test-upgrade-path.sh
Follow up of https://github.com/Kong/kong/pull/10442.
This should fix the failing Upgrade Tests.
Also open to suggestions to let `make dev` works both in a bazel built venv and in a released docker container
> fix(*): move previous `dev` targets to `dev-legacy`

- CHANGELOG.md
- build/dockerfiles/entrypoint.sh
FTI-4525
(cherry picked from commit a6fe3703e7e564aa0634f36d0f6d60ad395e2a03)
This change adds a clean-up step to remove all sockets that a previous Kong run may have left in `$PREFIX` directory.
Dangling unix sockets have been a pain point in recent Kong versions and was dealt in traditional Kong in #9254, but the kong script is not called when starting Kong inside a container, so a similar change to `dockerfiles/entrypoint.sh` was added here.
FTI-4525
> fix(dockerfiles): clean up dangling sockets on startup (#10468)

- Makefile
To preserve the previous behaviour.
This is a regression from https://github.com/Kong/kong/pull/10442 and https://github.com/Kong/kong/pull/10490.
Fixes https://github.com/Kong/kong-plugin/actions/runs/4421446482/jobs/7765323653
The previous dependency was:
```makefile
install:
@luarocks make OPENSSL_DIR=$(OPENSSL_DIR) CRYPTO_DIR=$(OPENSSL_DIR) YAML_DIR=$(YAML_DIR)
remove:
-@luarocks remove kong
dependencies: bin/grpcurl
@for rock in $(DEV_ROCKS) ; do \
if luarocks list --porcelain $$rock | grep -q "installed" ; then \
echo $$rock already installed, skipping ; \
else \
echo $$rock not found, installing via luarocks... ; \
luarocks install $$rock OPENSSL_DIR=$(OPENSSL_DIR) CRYPTO_DIR=$(OPENSSL_DIR) || exit 1; \
fi \
done;
dev: remove install dependencies
```
> fix(makefile): remove `remove` target dependency to `dependencies` target

- spec/02-integration/03-db/20-ttl-cleanup_spec.lua
It seems that sometimes the estimated time calculation will be 0 which violates the original expression so that the test may fail. Since we're only testing the fact that cleanup running, the time format is not what we care about.
```
kong_1   | 2023/03/16 07:22:41 [debug] 9263#0: *449 [lua] connector.lua:373: cleaning up expired rows from table 'cluster_events' took 0.026 seconds
kong_1   | 2023/03/16 07:22:41 [debug] 9263#0: *449 [lua] connector.lua:373: cleaning up expired rows from table 'clustering_data_planes' took 0.002 seconds
kong_1   | 2023/03/16 07:22:41 [debug] 9263#0: *449 [lua] connector.lua:373: cleaning up expired rows from table 'acme_storage' took 0.001 seconds
kong_1   | 2023/03/16 07:22:41 [debug] 9263#0: *449 [lua] connector.lua:373: cleaning up expired rows from table …
```
> tests(*): fix db ttl cleanup flaky test

- DEVELOPER.md
- build/BUILD.bazel
- build/build_system.bzl
- build/templates/venv-commons
- build/templates/venv.fish
- build/templates/venv.sh
This PR adds official support of Fish shell to venv; and add PS1 prompt to bash/zsh/fish.
Also we starts to move shell scripts into template to make it `shellcheck`-able.
- feat(build): support fish, add PS1, move venv scripts to template
Pretty demo:
[![asciicast](https://asciinema.org/a/2mc7LG1e5fDFfzc1f5uADf8DB.svg)](https://asciinema.org/a/2mc7LG1e5fDFfzc1f5uADf8DB)
> feat(build): support fish, add PS1, move venv scripts to template

- CHANGELOG.md
- kong/runloop/balancer/healthcheckers.lua
- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
The Kong load balancer has concepts of upstream health, which is managed by the healthchecker, and balancer health, which is affected by the healthchecker but also affected by the balancer "health threshold" setting. This means a _balancer_ can be unhealthy (and return HTTP 503) even when healthchecks for the upstream are disabled.
The endpoint `/upstreams/<upstream>/health?balancer_health=1` is an "advanced mode" for viewing health, which shows the _balancer health_ as opposed to upstream health. (It is hidden behind a query argument to avoid confusion, as for most cases the upstream health is sufficient and the "balancer" terminology referring to a mostly internal Kong object may also be unclear to end-users.) This endpoint, however, only returns the balancer health, when healthchecks …
> feat(balancer): expose balancer_health even when healthchecks are off

- kong/db/schema/typedefs.lua
- kong/runloop/certificate.lua
- spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
Currently, a ssl request with invalid sni will cause an error log as follows:
`2023/03/01 06:56:42 [error] 9398#0: *466 [lua] certificate.lua:51: log(): [ssl] failed to fetch SNI: failed to fetch '1.1.1.1' SNI: [postgres] must not be an IP, context: ssl_certificate_by_lua*, client: 127.0.0.1, server: 0.0.0.0:8443`
This is confusing. Customers may think it's related to db. As it's just an invalid request, change the log to debug level.
Fix [FTI-1716](https://konghq.atlassian.net/browse/FTI-1716)
[FTI-1716]: https://konghq.atlassian.net/browse/FTI-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(runloop): ssl request with invalid sni should not be logged as error

- CHANGELOG.md
- kong/clustering/compat/removed_fields.lua
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/opentelemetry/schema.lua
- spec/03-plugins/37-opentelemetry/05-otelcol_spec.lua
add http_response_header_for_traceid config to add trace_id to the downstream header.
FTI-4655
> feat(otel): add http_response_header_for_traceid config to add trace_id for downstream header

- spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
This PR reduces the flakiness of a certificate PATCH test.
A failure example can be found at https://github.com/Kong/kong/actions/runs/4443688330/jobs/7801199951?pr=10475, it can be found from the result that when comparing two certificates lists, the `updated_at` field is marked as different.
```
...
*[updated_at] = 1679021891 }
...
*[updated_at] = 1679021890 }
```
This could happen if the PATCH action happens in the next second of the creation, which may cause this test result flaky.
> tests(certificates): reduce cert PATCH test flakiness

- CHANGELOG.md
- kong.conf.default
- kong/conf_loader/init.lua
- kong/globalpatches.lua
- kong/pdk/request.lua
- kong/pdk/response.lua
- kong/pdk/service/response.lua
- kong/plugins/proxy-cache/handler.lua
- kong/router/atc.lua
- kong/router/traditional.lua
- kong/runloop/balancer/init.lua
- kong/runloop/plugin_servers/init.lua
- kong/templates/kong_defaults.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
- spec/02-integration/05-proxy/30-max-args_spec.lua
- spec/fixtures/custom_nginx.template
- spec/fixtures/custom_plugins/kong/plugins/max-args/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/max-args/schema.lua
- spec/fixtures/mock_upstream.lua
- spec/fixtures/mock_webserver_tpl.lua
Adds new `kong.conf` configuration settings:
- `lua_max_req_headers` (affects `kong.request.get_headers()` and `ngx.req.get_headers()`, does not affect proxying)
- `lua_max_resp_headers` (affects `kong.response.get_headers()` and `kong.service.response.get_headers()` and `ngx.resp.get_headers()`, does not affect proxying)
- `lua_max_uri_args` (affects `kong.request.get_query()`, `kong.request.get_query_arg()`, `ngx.req.get_uri_args()`, does not affect proxying)
- `lua_max_post_args` (affects `kong.request.get_body()` and `ngx.req.get_post_args()`, does not affect proxying)
And changes Kong to use those defaults.
This PR also contains some style/perf commits. I suggest this to be reviewed `commit-by-commit`.
KAG-715
Fix #10324
> feat(conf): configurable max for request headers, response headers, uri args, post args and decode args for lua

- CHANGELOG.md
- kong-3.2.1-0.rockspec
- kong/init.lua
- kong/pdk/init.lua
- kong/pdk/plugin.lua
- kong/plugins/datadog/handler.lua
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/statsd/log.lua
- kong/runloop/plugin_servers/init.lua
- kong/runloop/plugins_iterator.lua
- spec/02-integration/07-sdk/05-pdk_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/get-plugin-id/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/get-plugin-id/schema.lua
Exposing plugins' UUID as fields `id` of plugin config objects.
- New PDK function `kong.plugin.get_id()`
- plugin.lua 
- new file's entry in rockspec
- Test
- 05-pdk_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/get-plugin-id/*
- Change existing usage of `conf.__key__`
- kong/plugins/*
Implement FTI-4019
> feat(pdk): allow plugin to fetch its id

- CHANGELOG.md
- kong/runloop/handler.lua
- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
We expect the upstream passive unhealthy healthcheck on HTTP status code should only mark the targets as "down" (not reachable or proxiable) using the returned HTTP status code from the target, and it should not be affected by the final HTTP status code set by Kong plugin, which is returned to the client.
So we change the passive health check implementation to use nginx var `upstream_code`, this will not be changed by any plugin.
FTI-4841
Fix #10281
(cherry picked from commit dbe8d947e7d6a6c12f8464fc2f08276be1cd392f)
FTI-4802
> fix(runloop): use upstream status code in passive health check (#10325)

- CHANGELOG.md
- kong-3.2.1-0.rockspec
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
* Fix: check if PSK is available
* Add :getlocalchain() + :getlocalcertificate() to mirror the peer methods (@mwild1)
* Add Pre-Shared Key (PSK) support (@jclab-joseph)
> chore(deps) bump luasec from 1.2.0 to 1.3.1

- CHANGELOG.md
- kong/router/traditional.lua
- spec/02-integration/05-proxy/01-proxy_spec.lua
The same route may have been added multiple times to `routes_by_sources[<ip|port>]` or `routes_by_destination[<ip|port>]` which lead to "invalid order function for sorting" when we tried to sort the routes. There was also sorting issue when multiple routes sorted the same. This fixes the issue.
KAG-918
Fix #10446
Close #10470
> fix(router): traditional router could error with "invalid order function for sorting"

- CHANGELOG.md
- kong/plugins/http-log/schema.lua
- spec/03-plugins/03-http-log/01-log_spec.lua
* adds `application/json; charset=utf-8` option for the `Content-Type` header  in the http-log plugin, for log collectors that require that character set declaration.
Reported in FTI 4931.
> feat(http-log): support charset in content-type header

- kong/conf_loader/init.lua
- kong/db/strategies/postgres/connector.lua
- kong/templates/kong_defaults.lua
- spec/02-integration/03-db/20-ttl-cleanup_spec.lua
This PR tries to reduce the  time usage of TTL cleanup integration test, by adding a configurable option `pg_ttl_cleanup_interval` for adjusting when doing tests.
Fix KAG-921
> tests(postgres): reduce ttl cleanup test time usage

- kong/db/dao/plugins.lua
- spec/01-unit/01-db/01-schema/07-plugins_spec.lua
Summary:
Although adding s small check on plugin load does don't introduce a signification performance impact, but I feel adding a test case running only at CI scope could make the core code more cleaner.
[KAG-754]
[KAG-754]: https://konghq.atlassian.net/browse/KAG-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(plugins): add a test case to ensure every bundled plugin have a protocols field

- CHANGELOG.md
- kong-3.2.1-0.rockspec
The 0.17.0 is not beta anymore as the 0.17.1 was released as non-beta, so lets start pinning the resty.http again.
Documentation is clearer about using same connection for multiple requests via 'request' function by @alexdowad in #282
- fix 100 response with headers by @catbro666
- fix: no trailing \"?\" for empty query table by @StarlightIbuki
@chronolaw made their first contribution
@alexdowad made their first contribution
@catbro666 made their first contribution
@StarlightIbuki made their first contribution
> chore(deps): pin to latest resty-http 0.17.1

- build/luarocks/BUILD.luarocks.bazel
to make it work on distros that BINPRM_BUF_SIZE is 128
KAG-998
> fix(build): force the interpreter instead of relying on shebang

- .github/workflows/release.yml
- DEVELOPER.md
- WORKSPACE
Some distro ship old cmake that bazel doens't like; but we still use system installed make because bazel needs to compile it.
* use managed cmake and system-wide make
KAG-996
> feat(build): use managed cmake and system-wide make

- CHANGELOG.md
- kong/plugins/request-transformer/access.lua
- spec/03-plugins/36-request-transformer/02-access_spec.lua
This is a porting of EE/4816
Make the template environment thread safe by scoping it on the request rather than on the module level.
[KAG-933](https://konghq.atlassian.net/browse/KAG-933)
[KAG-933]: https://konghq.atlassian.net/browse/KAG-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(request-transformer): thread safety

- CHANGELOG.md
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/zipkin/handler.lua
- spec/03-plugins/34-zipkin/zipkin_spec.lua
- spec/03-plugins/37-opentelemetry/05-otelcol_spec.lua
> chore(plugin): convert traceid in http response headers to hex format

- .github/workflows/auto-assignee.yml
I'm working on setting up some automation for better project tracking using Github Projects and that requires the 'Assignees' field to be populated with PR author. This action adds automation for that.
> chore: auto-assign PR author as assignee

- kong/pdk/plugin.lua
I missed the comment for the usage of the `kong.plugin.get_id()`.
> chore(pdk): add comment so docs can be generated

- CHANGELOG.md
- kong/db/errors.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
This only affect `POST /config?flatten_errors=1`.
When nested errors are flattened for the response body, they should be removed from the original error table so that they are not included in the final `fields` error object. Errors that are not flattened should remain.
It could be argued that this is a backwards-incompatible change, but:
1. This is opt-in only via the `flatten_errors` query param.
2. Because `flatten_errors` is a new, yet unreleased feature, there is no defined behavior to be broken.
3. It's arguably a behavioral fix since we are effectively de-duplicating the errors in the response.
4. This makes the response object much, much cleaner.
5. The overall "shape" of the `fields` object has not changed.
> fix(dbless): drain error table when flattening errors

- .github/workflows/autodocs.yml
Update `.github/workflows/autodocs.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=name::$output"
```
**TO-BE**
```yml
echo "name=$output" >> $GITHUB_OUTPUT
```
Resolve #10551
> chore(ci): Replace deprecated command with environment file

- kong/clustering/compat/init.lua
`has_updated` flag in the compat logic isn't set after the config is changed  in https://github.com/Kong/kong/pull/10400
https://github.com/Kong/kong/pull/10400
> fix(clustering): fix the bug in compatible logic

- CHANGELOG.md
- kong.conf.default
- kong/conf_loader/init.lua
- kong/pdk/node.lua
- kong/templates/kong_defaults.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
Kong automatically generates node IDs for each node in a cluster. Node IDs are the only unique identifiers that exist to track a Kong node within a cluster (no assumption is made that hostname is unique across all Kong nodes).
When integrating closely with an orchestrator, a configurable node ID helps the operator to source the ID from the underlying orchestrator like Kubernetes instead of letting Kong generate one.
For most customers, letting Kong generate a Node ID will be sufficient.
* introduce `node_id` configuration parameter
> feat(conf) implement 'node_id' for configurable node ID

- .github/workflows/release.yml
These actions are released and controlled by the company, so we do not need to pin them by hash.
KAG-1073
> chore(actions): use release tag for `scan-docker-image`

- CHANGELOG.md
- kong/plugins/request-transformer/access.lua
- spec/03-plugins/36-request-transformer/02-access_spec.lua
This PR enables support for the following configuration parameters and values in the `request-transformer` plugin:
* untrusted_lua = "on", "off", "sandbox"
* untrusted_lua_sandbox_requires
* untrusted_lua_sandbox_environment
[KAG-168]
[KAG-169]
[KAG-168]: https://konghq.atlassian.net/browse/KAG-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAG-169]: https://konghq.atlassian.net/browse/KAG-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(request-transformer): honor untrusted_lua configuration values

- CHANGELOG.md
- kong/plugins/pre-function/_handler.lua
- spec/03-plugins/33-serverless-functions/02-access_spec.lua
Isolate the kong.cache instance available to the serverless functions
Limit access to kong.configuration fields
[KAG-364]
[KAG-364]: https://konghq.atlassian.net/browse/KAG-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(serverless-functions): isolate sandbox cache

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
- .github/workflows/build_and_test.yml
- CHANGELOG.md
- Makefile
- kong/runloop/handler.lua
- spec/02-integration/05-proxy/27-unbuffered_spec.lua
Turning request/response buffering off for HTTP/2.0 is not possible. There is a check that causes buffering only to be controllable for HTTP/1.1.
This was probably done because of an issue in nginx, which was fixed in version 1.9.14 (http://nginx.org/en/docs/http/ngx_http_v2_module.html):
> Before version 1.9.14, buffering of a client request body could not be disabled regardless of [proxy_request_buffering](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering), [fastcgi_request_buffering](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_request_buffering), [uwsgi_request_buffering](http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_request_buffering), and [scgi_request_buffering](http://nginx.org/en/docs/http/ngx_http_scgi_module.h …
> fix(proxy): fix request buffering for HTTP/2.0

- CHANGELOG.md
- kong/runloop/handler.lua
- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
fix passive health checker in subrequest 
* fix passive health checker in subrequest 
FTI-4841
https://github.com/Kong/kong/pull/10550
> fix(healthchecker): fix passive healthchecker in subrequest

- .github/workflows/release.yml
This provides a basic sanity/smoke test of the output of `kong version` compared to the workflow value of `steps.metadata.outputs.kong-version`.
Notably, this comparison is done using a trailing `$` and using shell-escaped dots (`\.`) to exclude "dot-all" matches (grep's default behaviour).
This is remediation from the 2.8.4.0 release.
Fix #_[KAG-1076]_
[KAG-1076]: https://konghq.atlassian.net/browse/KAG-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KAG-1076] fix(gha): add container version sanity test

- kong/pdk/tracing.lua
- kong/tracing/instrumentation.lua
**This is a recreated PR for a temporary/experimental PR, originally created by @samugi**
Fix the hierarchy of spans incorrectly reported to DataDog with balancer spans appearing always last in the flame graph.
The DataDog tracing plugin was always propagating the root span, which means the receiver of the propagation header will set their parent to the ID of the root span (that represents the root http request) instead of the balancer span, which is the real "caller" of the upstream.
To fix this it's necessary that the balancer span (not the root span) is propagated at the end of the request. This is challenging because the balancer spans are generated after the balancer data is available (after the header propagation already occurred).
This solution expands the tracing PDK interface to …
> fix(instrumentation): span hierarchy

- spec/02-integration/04-admin_api/08-targets_routes_spec.lua
add test cases for healthcheck status reported by Admin API endpoint '/upstream/health'.
The health status of targets with weight 0 reported by Admin API was changed from HEALTHY to HEALTHCHECK_OFF in [#9065](https://github.com/Kong/kong/pull/9065). The test cases added in this PR want to cover those changes.
> test(healthcheck): add test cases for healthcheck status reported by admin api

- spec/02-integration/14-tracing/02-propagation_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/schema.lua
Add tests for https://github.com/Kong/kong/pull/10583
Adds a test to confirm the span hierarchy is propagated correctly. The propagated span id must be that of the balancer span.
This test confirms that the whole flow available through https://github.com/Kong/kong/pull/10583 works:
- the custom plugin uses `tracer.create_span()` to create the balancer span in advance and propagate it
- the span is then correctly picked up in `instrumentation` and linked via `tracer.link_span()`
[KAG-1040](https://konghq.atlassian.net/browse/KAG-1040)
[KAG-1040]: https://konghq.atlassian.net/browse/KAG-1040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(tracing): add propagation integration test

- kong-3.2.1-0.rockspec
- kong/clustering/compat/checkers.lua
- kong/clustering/compat/init.lua
Move compatible config-checking logic into a hash table, making code more readable.
Need special cherry-pick action to EE.
> refactor(clustering/compat): using array to store compatible checker functions

- kong-3.3.0-0.rockspec
- kong/meta.lua
This should have been done in master as part of the release of Kong 3.2.0.
The step is now included in our new release checklist.
- <del>[ ] The Pull Request has tests</del>
- <del>[ ] There's an entry in the CHANGELOG</del>
- <del>[ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE</del>
> chore(release): bump version number to 3.3.0

- spec/02-integration/04-admin_api/12-plugins-conf_spec.lua
This PR adds a test to fetch all the plugins sub-module installed under Luarocks `kong` module and test if it is already in the bundle list, to ensure that we will not forget to add new plugins into the bundle list according to our needs. Plugins that do not need to be bundled have to be added to `not_bundled_plugins` whitelist.
I haven't come up with some better solutions yet so if you're looking at this PR and have a better idea, please let me know, thanks!
* add a test to check all plugin sub-modules installed in Luarocks kong module are in bundle list
[FTI-4599](https://konghq.atlassian.net/browse/FTI-4599)
[FTI-4599]: https://konghq.atlassian.net/browse/FTI-4599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(bundled-plugin): test all plugin sub-modules installed in luarocks kong module are in bundle list

- kong/db/migrations/core/019_320_to_330.lua
Sometimes the migrations may be executed partially. Or the state of database already has some fields in some tables. This PR just wraps adding columns and catches duplicate column per table. This is also similar as we do in other migrations.
> refactor(migrations): makes kong 3.3 migrations more resilient on partial migrations

- spec/02-integration/15-plugins-iterator/01-precedence_spec.lua
- spec/fixtures/factories/plugins.lua
Add precedence tests to ensure plugins are executed in the right order according to their scoping (route, service, consumer)
KAG-1127
> tests(plugins-iterator): precedence tests

- kong/cmd/config.lua
- kong/reports.lua
- kong/runloop/handler.lua
- spec/01-unit/11-reports_spec.lua
- spec/02-integration/02-cmd/11-config_spec.lua
respect the kong.configuration.anonymous_reports when initializing the behavior of send_report.
The default behavior of send_report is initially determined by the configuration. However, it could still be toggled later, this means the caller is responsible for the actual behavior.
FTI-4469
> fix(reports): always honor anonymous report toggle

- build/repositories.bzl
This commit updates the GitHub CLI in the Bazel repository to 2.27.0.
The new version introduces keyring storage for authentication token storage and provides native support for Apple Silicon, among other improvements. Allows users to use the token saved in the keyring instead of having to set the `$GITHUB_TOKEN` environment variable every time.
> chore(deps): bump github cli to 2.27.0

- kong/pdk/tracing.lua
- kong/tracing/propagation.lua
- spec/02-integration/14-tracing/02-propagation_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/tcp-trace-exporter/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
fix an issue where incoming propagation headers with disabled sampling (sampled flag = 0) produced invalid propagation of noop spans and broken traces
This fix:
* ensures propagation is not attempted on noop spans
* ensures no span is sampled when sampling is disabled in the incoming headers
* propagates the correct header when sampling is disabled in the incoming headers
https://konghq.atlassian.net/browse/KAG-1184
https://konghq.atlassian.net/browse/KAG-1176
> fix(tracing/core): sampled flags and propagation

- CHANGELOG.md
- kong/clustering/compat/removed_fields.lua
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/opentelemetry/schema.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
At the moment the opentelemtry plugin sets the `default_header_type` for propigations:
https://github.com/Kong/kong/blob/master/kong/plugins/opentelemetry/handler.lua#L150
However, doesn't allow the modification of `header_type` in the `schema`, so it always defaults to `preserve`. However, based on the function it's calling:
https://github.com/Kong/kong/blob/master/kong/tracing/propagation.lua#L432
> -- If conf_header_type is set to `preserve`, found_header_type is used over default_header_type;
The above means the `default_header_type` is never used. We want the `default_header_type` to be used, and we want to ignore the incoming header type. 
I am not implmenting the ability to modify the `default_header_type` as opentelemetry notes it should default to `w3c` which it currently is: …
> feat(opentelemetry): Allow header_type to be set

- CHANGELOG.md
- kong-3.3.0-0.rockspec
* fix: fix log flooding by @ADD-SP in https://github.com/Kong/lua-resty-timer-ng/pull/14
**Full Changelog**: https://github.com/Kong/lua-resty-timer-ng/compare/0.2.4...0.2.5
[KAG-1131]
[KAG-1131]: https://konghq.atlassian.net/browse/KAG-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(dep): bump `lua-resty-timer-ng` from `0.2.4` to `0.2.5`

- spec/02-integration/04-admin_api/08-targets_routes_spec.lua
`spec/02-integration/04-admin_api/08-targets_routes_spec.lua` test has been flaky for some time. This file uses `ngx.sleep()` instead of `wait_until()` or `assert.eventually()` in several tests. When the host is busy, the `ngx.sleep()` time may be not enough.
This change actually waits for the most flaky request in the file to finish instead of relying on `ngx.sleep()`. A lot more still to be done.
* Change a `ngx.sleep()` call to a `assert.eventually()`.
> tests(integration): reduce targets admin API tests flakiness

- .github/workflows/auto-assignee.yml
Fix the failing tests like in https://github.com/Kong/kong/actions/runs/4717539509/jobs/8366244956
* chore(auto-assignee): exclude PR opened from fork
> chore(auto-assignee): exclude PR opened from fork

- kong/init.lua
- kong/tracing/instrumentation.lua
use nanosecond precision to track balancer span's start and end times
KAG-1112
> fix(tracing): balancer span precision

- kong/globalpatches.lua
- spec/02-integration/14-tracing/01-instrumentations_spec.lua
global patch for http_client spans was missing
this fix adds it and fixes the test to ensure http_client spans are created as expected
KAG-1111
> fix(tracing): http_client span

- kong/pdk/tracing.lua
- kong/tracing/instrumentation.lua
- spec/02-integration/14-tracing/01-instrumentations_spec.lua
- spec/02-integration/14-tracing/02-propagation_spec.lua
High cardinality span names (operation name for Datadog) causes the spans unable to group, and not able to help analysis in the dashboard.
We reorgnize the span names, to handle the cardinality with "resource" field for Datadog. This PR is to modified shared code for both CE and EE involved in this fix
* Add comments to clarify the definition of spans
* Rename spans
Fix FTI-4882
> feat(instrumentation): fix high cardinality span name

- kong/cmd/utils/nginx_signals.lua
This PR fixes a problem that Kong uses the system's nginx binary instead of bazel built binary(which is what we expect to be used) under the venv environment.
The root cause of this issue is that Kong tries to iterate through the path list defined in `nginx_search_paths`, and `/usr/local/openresty/nginx/sbin` and `/opt/openresty/nginx/sbin` always take precedence. 
https://github.com/Kong/kong/blob/22cba2328ac8939493699b22ab7926064bdb0175/kong/cmd/utils/nginx_signals.lua#L28-L32
https://github.com/Kong/kong/blob/22cba2328ac8939493699b22ab7926064bdb0175/kong/cmd/utils/nginx_signals.lua#L99-L116
This PR fixes the problem by putting the `""` path to the front of search paths, so Kong will first try to use the nginx binary according to the current PATH env var, and in the venv environment the …
> fix(utils): fix nginx binary path search sequence under the "venv" environment

- kong/clustering/compat/removed_fields.lua
fix version compatibility for acme. The [original PR](https://github.com/Kong/kong/pull/10562) missed to add the field into removed_fields.lua
[KAG-615](https://konghq.atlassian.net/browse/KAG-615)
[KAG-615]: https://konghq.atlassian.net/browse/KAG-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(clustering): version compatibility for acme

- kong/plugins/statsd/log.lua
There is no `kong.log.error`, but there is `kong.log.err`.
> fix(statsd): call the right log function

- CHANGELOG.md
- kong/plugins/opentelemetry/handler.lua
- spec/01-unit/01-db/01-schema/07-plugins_spec.lua
Plugin versions are the same as the core version for the bundled plugin. OpenTelemetry plugin didn't follow this invariant and now it does.
> fix: change opentelemetry plugin version to match core

- CHANGELOG.md
- spec/03-plugins/37-opentelemetry/06-regression_spec.lua
- spec/helpers.lua
[Improvement of batch queue](https://github.com/Kong/kong/issues/10172) fixed the OTEL reconfigure issue.
This PR adds a test to verify the fix.
* Cherry-pick coroutine-based HTTP mock helper function
* Regression test for the issue
Test of KAG-1061
> test(plugin): test for fix of otel reconfigure issue #KAG-1061

- CONTRIBUTING.md
Add a rule to normalize the localized vars.
> docs(contribute): rules for localized name

- spec/02-integration/03-db/15-connection_pool_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/slow-query/api.lua
The test was flaky due to incorrect waiting assertions, that were not ensuring the connection queues to be filled properly/all the time. This change also removes some duplicate code.
KAG-1215
> tests(connection-pool): address flakiness

- build/templates/venv-commons
chore(dev): prioritize `.lua` over `.ljbc` in `LUA_PATH`
We may edit Lua files in place for debug.
* Place `.lua` in front of `.ljbc` in `LUA_PATH`.
* Support custom pluin `KONG_PLUGIN_PATH`.
Fix #_[FTI-5013]_
[FTI-5013]: https://konghq.atlassian.net/browse/FTI-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(dev): prioritize .lua over .ljbc in LUA_PATH

- kong/init.lua
A local variable was added in https://github.com/Kong/kong/pull/10681, but it is not needed. Removing it
> style(balancer): remove not needed variable

- .github/workflows/release-fail-bot.yml
Only notify on given branches.
Fix KAG-1315
> chore: add branch constrains on Workflow “Package & Release” Notifier

- CHANGELOG.md
- kong/cache/init.lua
Fortunately, the default value of `shm_set_tries` is [3](https://github.com/thibaultcha/lua-resty-mlcache#new), so there is no change in behavior.
> fix(cache): a typo of mlcache option `shm_set_tries`

- kong/clustering/compat/removed_fields.lua
This PR adds the missing new config field `disable_https` in the aws-lambda plugin, to the removed field so that clustering compat can work normally.
Related feature PR: https://github.com/Kong/kong/pull/9799
> fix(clustering): add missing aws-lambda plugin new option in removed fields

- build/templates/venv-commons
#10693 prioritizes `.lua` over `.ljbc` in general, within `venv`. This PR applies the rule to EE plugins as well.
* Add all EE plugins in Kong repo to `LUA_PATH`.
Fix #_[FTI-5013]_
[FTI-5013]: https://konghq.atlassian.net/browse/FTI-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
KAG-1235
> chore(dev): prioritize EE plugins .lua over .ljbc

- build/templates/venv-commons
`for plugin in ./plugins-ee/*/; do`
should be changed to
`for plugin in $(ls plugins-ee); do`
* fix a shell bug
Fix KAG-1235 and FTI-5013
> chore(dev): fix a shell issue

- t/01-pdk/08-response/11-exit.t
Fix spelling in `t/01-pdk/08-response/11-exit.t` fixes the test
> tests: fix spelling `ngx.ctx.rewite` -> `ngx.ctx.rewrite`

- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
This fixes an issue in the queue implementation in EE that made queues fail to work after the first entry was processed.  This was caused by the 'smart' way to isolate the queues in each workspace from those in other workspaces by using __index and __newindex to automatically combine the workspace name into the key used as index into the table of queues.  This approach failed to work when the queue had to be deleted as that happens from the timer context in which no ngx.context is not set.
Fixes KAG-1292
> fix(queues): use explicit workspace in registry key

- kong/tools/queue.lua
Master is red: https://github.com/Kong/kong/actions/runs/4791115533/jobs/8521126234
```
busted 2.1.2 already installed, skipping
busted-htest 1.0.0 already installed, skipping
luacheck 1.1.0 already installed, skipping
lua-llthreads2 0.1.6 already installed, skipping
http 0.4 already installed, skipping
ldoc 1.4.6 already installed, skipping
Checking kong/tools/queue.lua                     2 warnings
kong/tools/queue.lua:64:7: unused variable rawset
kong/tools/queue.lua:65:7: unused variable rawget
Total: 2 warnings / 0 errors in 905 files
make: *** [Makefile:[11](https://github.com/Kong/kong/actions/runs/4791115533/jobs/8521126234#step:8:12)6: lint] Error 1
Error: Process completed with exit code 2.
```
> style(queue): remove unused upvalues

- CHANGELOG.md
- build/openresty/patches/lua-resty-dns-0.22_01-destory_resolver.patch
- kong/resty/dns/client.lua
- spec/02-integration/05-proxy/05-dns_spec.lua
In `resty.dns.client` module when `resolver:new()` is called, a UDP socket is created. In 2.x, the UDP socket is released quickly, while in 3.x, it has to take several seconds to release. If the ttl of dns responses is shorter than the time it waits, the leak will happen. In this PR, a forcible release is added.
FTI-4962
FTI-4962
> fix(resty.dns.client): fix the UDP sockets leak

- kong/runloop/plugins_iterator.lua
- spec/01-unit/28-plugins-iterator/compound_key_spec.lua
- spec/01-unit/28-plugins-iterator/lookup_cfg_spec.lua
- spec/02-integration/15-plugins-iterator/02-correctness_spec.lua
- spec/03-plugins/29-acme/05-redis_storage_spec.lua
This patch set changes how the Plugins Iterator finds suitable plugin configurations for defined precedence rules.
To achieve that, we move from a nested table structure that stores various combinations of `route, service and consumer` to a _flat_ hashmap.
**Before.**
```lua
combos[name].rsc[cfg.route_id] =
combos[name].rsc[cfg.route_id] or {}
combos[name].rsc[cfg.route_id][cfg.service_id] =
combos[name].rsc[cfg.route_id][cfg.service_id] or {}
combos[name].rsc[cfg.route_id][cfg.service_id][cfg.consumer_id] = cfg
combos[name].rc[cfg.route_id] =
combos[name].rc[cfg.route_id] or {}
combos[name].rc[cfg.route_id][cfg.consumer_id] = cfg
-- and so on for all possible combinations
```
**After:**
```lua
-- Build a compound key using the route_id, service_id, and consumer_id
local compound_key = …
```
> refactor(plugins-iterator): refactor precedence matching algoritm

- spec/02-integration/05-proxy/06-ssl_spec.lua
> tests(proxy/ssl): enable ssl tests for flavor traditional_compat

- build/BUILD.bazel
- build/templates/venv-commons
- build/templates/venv.fish
- build/templates/venv.sh
- scripts/dependency_services/common.sh
- scripts/dependency_services/up.fish
- scripts/dependency_services/up.sh
docker compose plugin
This reduces the burden of developer needs to learn fish/zsh/bash syntax to add features to the venv. Now only the skleton is depending on each shell's flavor, the actual logic to set env vars and start docker-compose is always in bash.
Fix KAG-441, KAG-1350
> fix(venv): use shell agnostic script to generate env files and support

- kong.conf.default
Adds docs about `env` vault configuration options.
[KAG-1203](https://konghq.atlassian.net/browse/KAG-1203)
[KAG-1203]: https://konghq.atlassian.net/browse/KAG-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(vault): add env vault configuration options in kong.conf

- spec/helpers/perf/utils.lua
This is the last place where we have `resty.worker.events` since we merged: https://github.com/Kong/kong/pull/10142
> chore(tests): remove mention of resty.worker.events from helpers/perf/utils.lua

- build/templates/venv-commons
Enclose parameter for shell safety.
* enclose parameter for shell safety
Fix FTI-5035
> chore(dev): enclose parameter for shell safety

- kong/plugins/datadog/schema.lua
- kong/plugins/http-log/schema.lua
- kong/plugins/opentelemetry/schema.lua
- kong/plugins/statsd/schema.lua
- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
- spec/03-plugins/01-legacy_queue_parameter_warning_spec.lua
- spec/03-plugins/03-http-log/02-schema_spec.lua
This reverts commit 40008ec9a1ad423acc97912e0290737e1daea867 and improves how deprecation messages are logged.  Instead of creating a log message for every `Queue.enqueue` operation, each message for each queue is now logged only once per minute.  This is supposed to provide good visibility for these messages without flooding the log with duplicates.
KAG-1279
KAG-1340
> fix(queues): log deprecation warnings at runtime

- kong/clustering/compat/checkers.lua
- kong/clustering/compat/init.lua
- spec/01-unit/19-hybrid/03-compat_spec.lua
When running a 3.3 CP, queuing parameters that have been required in prior versions would cause DPs to reject the configuration sent by the CP because those parameters are no longer present.  This compatibility fix makes sure that these parameters are present.  Where possible, the values are determined from the new queue configuration hash, otherwise the previous defaults will be supplied.
KAG-1392
> fix(clustering): support queueing plugins of pre-3.3 DP with 3.3 CP

- spec/02-integration/04-admin_api/22-debug_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
Rerunning the master test results in red today: https://github.com/Kong/kong/actions/runs/4830133642/jobs/8643121705
After digging, the errorlog shows
```
2023/05/01 17:50:00 [error] 71095#0: *2 upstream SSL certificate verify error: (22:certificate chain too long) while SSL handshaking to upstream, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", upstream: "https://172.67.204.7:443/requ
est", host: "mockbin.com"
2023/05/01 17:50:01 [error] 71095#0: *2 upstream SSL certificate verify error: (22:certificate chain too long) while SSL handshaking to upstream, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", upstream: "https://104.21.60.253:443/req
uest", host: "mockbin.com"
2023/05/01 17:50:01 [error] 71095#0: *2 upstream SSL certificate verify error: (22:certificate …
```
> tests(*): fix ssl upstream cert verify depth for mockbin.com

- CHANGELOG.md
- kong/conf_loader/init.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
Fixes Kong error on kong stop when references are not available.
> fix(cmd): do not error when kong is stopping on secret resolving errors

- kong/pdk/vault.lua
Just a small change/fix to use right key in strategies/schema caching.
> chore(vault): use name instead of prefix to cache vault strategies and schemas

- CHANGELOG.md
- kong/plugins/opentelemetry/handler.lua
- spec/01-unit/01-db/01-schema/07-plugins_spec.lua
This reverts commit fabbcdd72867065f450341d742151e20bf80e630.
KAG-1410
> [revert kong/#10646] fix(plugins): change opentelemetry plugin version to match core

- kong/db/strategies/postgres/connector.lua
- spec/02-integration/03-db/01-db_spec.lua
DB performance monitor and analyzers displays stats based on Postgresql "applicaiton_name"
Currently Kong shows up as pgmoon and that may not be intuitive for those kong operators who do not know that Kong is a lua app that depends on the lua pgmoon library.
This PR attempt to give it a better name like applicaiton_name=kong.
* set postgresql applicaiton_name=kong 
> chore: set PostgreSQL application_name=kong

- build/templates/venv.sh
chore(dev): silent error if stop_services does not exist
```
~ $ type stop_services >/dev/null
-bash: type: stop_services: not found
~ $ type stop_services &>/dev/null
~ $ echo $?
1
```
* Redirect stderr to `/dev/null` as well.
Fix FTI-5035
> chore(dev): silent error if stop_services does not exist

- CHANGELOG.md
- kong/router/atc.lua
- kong/router/compat.lua
- spec/01-unit/08-router_spec.lua
When prefix and regex routes were mixed or prefixes of different lengths were specified in one route, traditional_compat assigned the highest priority of all paths to the route for all paths, causing unexpected routing matches that were incompatible with the traditional router.
With this fix, each multi-path route is split into multiple routes with separate priorities.
KAG-727
[KAG-1446](https://konghq.atlassian.net/browse/KAG-1446)
[KAG-1446]: https://konghq.atlassian.net/browse/KAG-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(router): fix incorrectly calculated priorities in traditional_compat

- CHANGELOG.md
- kong/status/ready.lua
- spec/02-integration/09-hybrid_mode/11-status_spec.lua
This PR changes the behavior of the new readiness endpoint for control plane nodes. 
The new endpoint `/status/ready` added in #10610 checks if Kong Gateway is ready for proxying. This check only makes sense in data plane nodes, as control plane nodes don't proxy traffic. But the response could be misleading, control plane nodes failing to connect to the database would return `200 OK`, even if they are not functional.
Note: this PR has no automated tests, [our test suite does not support stopping the database while the tests are running](https://github.com/Kong/kong/blob/3.2.2/spec/02-integration/04-admin_api/02-kong_routes_spec.lua#L261-L264).
* Check for database connection in control plane nodes.
KAG-1437
> fix(status): CP /status/ready return 503 when DB is off

- .ci/luacov-stats-aggregator.lua
- .github/workflows/build_and_coverage.yml
porting of a fix already included in EE [here](https://github.com/Kong/kong-ee/pull/5290)
use luacov.runner to simplify luacov stat file aggregation
KAG-1324
> tests(coverage): simplify aggregation

- kong/plugins/datadog/handler.lua
- kong/plugins/http-log/handler.lua
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/statsd/log.lua
- kong/plugins/zipkin/reporter.lua
- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
- spec/03-plugins/03-http-log/01-log_spec.lua
- spec/03-plugins/03-http-log/02-schema_spec.lua
Log entries written by queue functions included the name of the queue, but not the name and ID of the plugin using the queue.  This would make it difficult to correlate queue log entries written by the queue consumption side to the configuration.  With this change, an explcit log_tag key can be passed to the queue when enqueuing which is shown in all log entries written by the queue.  An explicit log_tag key was chosen over a more specific 'plugin' or 'plugin_id' key as queues are also used by non-plugin functionality in EE.
Fixes KAG-1394
> fix(queues): display plugin name in queue log entries

- spec/02-integration/13-vaults/04-echo_spec.lua
One sticky vault configuration test turned to be flaky, this fixes the test.
> tests(integration): fix flaky vault sticky configuration test

- spec/02-integration/08-status_api/01-core_routes_spec.lua
Previously, CE #10629 has some code refactoring to status api test. However, there are two pitfalls.
1. Some of the refactoring is uncessary.
2. The author is currently unavailable to continue this part of the job
This PR make sure the api status test on CE and EE sync. See EE #5299
* Checkout EE `spec/02-integration/08-status_api/01-core_routes_spec.lua` to CE.
Fix KAG-1475
> refactor(tests): make sure status api test sync on CE and EE

- CHANGELOG.md
We have two `Breaking Changes` sections, the second one is duplicated so remove it.
> docs(changelog): remove duplicated sections

- build/BUILD.bazel
Sister PR https://github.com/Kong/atc-router/pull/61
Make the step slightly more robust.
> fix(build): use seperate target to install atc-router lualib

- CHANGELOG.md
- kong-3.4.0-0.rockspec
- **crypto:** use OPENSSL_free in BoringSSL ([#107](https://github.com/fffonion/lua-resty-openssl/issues/107)) [7830212](https://github.com/fffonion/lua-resty-openssl/commit/78302123ac744f2d0b6de1156e459e9ea72b7edb)
<a name="0.8.21"></a>
- **x509.store:** extend verify to support setting flags ([#104](https://github.com/fffonion/lua-resty-openssl/issues/104)) [fa45b6c](https://github.com/fffonion/lua-resty-openssl/commit/fa45b6ce197dee7e2a55601bd4833f415c6cbaa2)
> chore(deps): bump resty.openssl from 0.8.20 to 0.8.22

- CHANGELOG.md
Fixes changelog to link the right pr.
> docs(changelog): fix resty.openssl 0.8.22 bump link

- spec/helpers.lua
This is a cherry-pick of EE PR. This commit serves a part of doc render fix.
N/A
> docs(tests): fix deprecation warning http_server

- spec/02-integration/13-vaults/04-echo_spec.lua
Disables one test on Cassandra, because it for some reason is flaky.
KAG-1517
> tests(integration): disable vault sticky test on cassandra because of flakiness

- spec/03-plugins/03-http-log/01-log_spec.lua
Remove erroneously configured timeouts
The test was configuring 1ms timeouts in two instances of the `http-log` plugin. This was probably done by mistakenly using in route7 and route8 the same configuration [as route6](https://github.com/Kong/kong/blob/e62ec50531644f32c18ed1399315ef6048958f6b/spec/03-plugins/03-http-log/01-log_spec.lua#L203), which is meant to timeout.
What happened under the hood was that 1ms timeout was enough for the logs to be stored but not always enough for the response to get back, so after the queue retries, more than one entry existed, and [this assertion](https://github.com/Kong/kong/blob/041a0e9cdc7996e5ef4bb96e6c2b0a57a14d74af/spec/03-plugins/03-http-log/01-log_spec.lua#L526) failed.
> tests(http-log): address flakiness

- autodoc/admin-api/data/admin-api.lua
- kong-admin-api.yml
- kong/api/routes/plugins.lua
- spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
The /plugins/schema/:name was marked for removal in 3.0 but for some reason we forgot to do it. Doing it now.
> chore(admin): remove /plugins/schema/:name

- CHANGELOG.md
- kong/plugins/acme/handler.lua
- spec/03-plugins/29-acme/06-hybrid_mode_spec.lua
Currently, there is a technical limitation in hybrid mode, that is, the DP side cannot perform any write database operation. However, when the sanity test is executed and the account identifier information is needed to write to storage, we will skip this operation (after a private discussion with @fffonion) and always return 404 directly with all storages. This will not have any substantial impact on the functionality.
* Fixed sanity test can't work with "kong" storage in Hybrid mode
Fix FTI-4909
> fix(acme): sanity test can work with "kong" storage in Hybrid mode

- scripts/dependency_services/docker-compose-test-services.yml
Now we have disabled the tests for Cassandra (#10832), we should also remove other related things.
> chore(scripts): remove cassandra service

- scripts/dependency_services/common.sh
- scripts/dependency_services/up.fish
- scripts/dependency_services/up.sh
Shell utility 'return' can only be used to return from Shell functions.
* Use `exit` instead of `return` upon error.
Fix FTI-5071
> chore(dev): use 'exit' instead of 'return' upon shell error

- CHANGELOG.md
- kong/plugins/loggly/handler.lua
- kong/plugins/tcp-log/handler.lua
- kong/plugins/udp-log/handler.lua
- kong/reports.lua
For those sockets created inside the schedule of timer-ng, the sockets must be closed explicitly. 
More details, please refer to: #10691 
#10691
> fix(loggly&tcp-log&udp-log&reports): close sockets explicitly when necessary

- .github/labeler.yml
Previous glob did not match `kong/db/schema/metaschema.lua`. The new glob matches all of the previous (since `kong/db/schema/entities/**/*` matches a subset of `kong/db/schema/**/*.lua`), plus the missing `kong/db/schema/metaschema.lua` - since `**` also matches ε.
> fix(ci): add new path to schema change bot

- .github/workflows/build_and_test.yml
- spec/01-unit/19-hybrid/03-compat_spec.lua
- spec/fixtures/blueprints.lua
add a test case that should have been added in #10400 
- #10400
> tests(compatibility): add a test case for config compatibility between dp and cp

- CHANGELOG.md
- kong/runloop/handler.lua
- spec/02-integration/04-admin_api/22-debug_spec.lua
This PR fixes a bug when worker consuming dynamic log level setting event and using a wrong reference for notice logging
```
2023/05/18 14:29:06 [error] 23010#0: *3 [lua] callback.lua:98: do_handlerlist(): worker-events: event callback failed; source=debug, event=log_level, wid=0 error='./kong/runloop/handler.lua:937: bad argument #2 to 'log' (expected table to have __tostring metamethod)
[C]: in function 'log'
./kong/runloop/handler.lua:937: in function <./kong/runloop/handler.lua:925>
...uild/kong-dev/openresty/lualib/resty/events/callback.lua:83: in function 'do_handlerlist'
...uild/kong-dev/openresty/lualib/resty/events/callback.lua:130: in function 'do_event'
.../build/kong-dev/openresty/lualib/resty/events/worker.lua:68: in function …
```
> fix(*): fix worker notice logging when setting dynamic log level

- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
* wait until http test server is unhealthy before continuing the test.
* using some tolerance on the number of requests answered by each proxied test server, we are testing the health check here, not the ring balancer behavior.
* removed some parenthesis from comments to avoid messing up with vim.
> tests(integration): avoid passive health check flakiness

- spec/02-integration/02-cmd/13-signals_spec.lua
This flakiness is caused by the slow I/O. so we need to wait for it.
> test(cmd): fix flaky `can receive USR1` test

- spec/02-integration/04-admin_api/22-debug_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
This PR modifies the integration tests that need real access to mockbin.com, to let them access mocking HTTP server so that we can reduce possible flakiness caused by outer dependencies. 
(Note: if you search for `mockbin.com` or `mockbin.org` in the spec directory there are still some services filling in these domains, but they are not really accessing or depending on the response of the mockbin server, so it's okay)
I'm still using https_server here because http_mock does not support https and we still need https in these cases.
* tests(*): modify tests that need to access mockbin.com from integration test
> tests(*): modify tests that need to access mockbin.com from integration test

- CHANGELOG.md
I revised the changes one by one. Besides trivial changes in punctuation/order:
#10783 (Reports: fix a potential issue that could cause socket leaks. and **loggly & tcp-log & udp-log**: fix a potential issue that could cause socket leaks.) was resolved after code freeze and was not backported to 3.3 - its changelog entry was put in the wrong place
#
> docs(changelog): update changelog for 3.3.0 with the released one

- spec/02-integration/05-proxy/06-ssl_spec.lua
Cherry-picks https://github.com/Kong/kong/pull/10893
Stop using mockbin.com for a couple of tests to reduce external dependencies.
> [cherry-pick release/2.8.x] tests(*): modify tests that need to access mockbin.com from integration test (#10893)

- spec/02-integration/04-admin_api/22-debug_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
Cherry-picks https://github.com/Kong/kong/pull/10893
Stop using mockbin.com for a couple of tests to reduce external dependencies.
> [cherry-pick release/3.1.x] tests(*): modify tests that need to access mockbin.com from integration test (#10893)

- spec/02-integration/04-admin_api/22-debug_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
Cherry-picks https://github.com/Kong/kong/pull/10893
Stop using mockbin.com for a couple of tests to reduce external dependencies.
> [cherry-pick release/3.2.x] tests(*): modify tests that need to access mockbin.com from integration test (#10893)

- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
**Note**: flakiness of this test is addressed by https://github.com/Kong/kong/pull/10877
This PR uses the new helpers.http_mock to replace helpers.http_server and adjusts some timeouts to reduce unnecessary waiting time
**Performance improvement** 
before: [about 58 seconds](https://github.com/Kong/kong/actions/runs/5004201982/jobs/8966490811#step:9:1348)
after: [about 36 seconds](https://github.com/Kong/kong/actions/runs/5006865312/jobs/8972713815?pr=10888#step:9:1336)
[KAG-1590](https://konghq.atlassian.net/browse/KAG-1590)
[KAG-1590]: https://konghq.atlassian.net/browse/KAG-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(opentelemetry): improve performance

- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/helpers.lua
This changeset includes several improvements to our start/stop CLI tests. Some changes are purely stylistic in nature (formatting, variable naming/conventions), but beyond that there are some functional improvements as well:
* Several tests had their own "block until Kong is up and responsive" pattern. This PR adds a single helper function to do just that and refactors all tests to use it.
* The usage of `finally(...)` blocks for cleanup has been reduced. The top-level `after_each()` handler for this test suite closes client connections and stops the default Kong instance, so we don't need `finally(function() helpers.stop_kong() end)` in every single test case.
* Additional assertion error output has been added to the `dangling socket cleanup` tests for debugging
* The …
> tests(cmd): stop/start test improvements

- Makefile
grpcurl v1.8.5 doesn't have a specific asset for osx_arm64, thus we will use the x86_64 asset instead when setup the development with apple silicon chips.
The original Makefile bin/grpcurl will try to download [grpcurl_1.8.5_osx_arm64.tar.gz](https://github.com/fullstorydev/grpcurl/releases/download/v1.8.5/grpcurl_1.8.5_osx_arm64.tar.gz) for apple silicon chips but the asset doesn't exist. The fix will use the x86_64 asset instead.
> fix(makefile): fix grpcurl v1.8.5 osx arm64 asset 404 issue

- build/templates/venv.fish
- build/templates/venv.sh
correct venv automatically
When having multiple venvs, currently user has to do `make dev BUILD_NAME=another-venv` even if they are 
inside the venv.
This PR expoeses the BUILD_NAME env var in venv so that after user acitvate the env, they don't need to explictly
set BUILD_NAME to `make dev` anymore.
- set BUILD_NAME in venv so that `make dev` can pick up correct venv automatically
> chore(venv): set BUILD_NAME in venv so that `make dev` can pick up

- .gitignore
- spec/02-integration/01-helpers/03-http_mock_spec.lua
- spec/02-integration/05-proxy/03-upstream_headers_spec.lua
- spec/fixtures/https_server.lua
- spec/helpers.lua
- spec/helpers/http_mock.lua
- spec/helpers/http_mock/asserts.lua
- spec/helpers/http_mock/clients.lua
- spec/helpers/http_mock/debug_port.lua
- spec/helpers/http_mock/nginx_instance.lua
- spec/helpers/http_mock/template.lua
We have 3 types of implementation for HTTP mocking, each of which has some issues.
This PR introduces a new implementation to unify them with a dedicated Nginx instance.
It allows users to use the same logic as `start_kong` fixture. And it collects requests/responses/errors for later assertions on them.
The collected information is then fetched from a debugging port, and a set of assertion APIs handles the fetching process.
It's also possible to extend this solution to support clients-to-server debugging API, e.g, to send a piece of text as the response body for the next request.
* New HTTP mocking implementations, including:
* Logic to create and manage the Nginx server instance;
* API to create an HTTP client to the server;
* APIs to make assertions on requests, responses, and errors;
* …
> test(*): implement new HTTP mocking

- .github/matrix-full.yml
- CHANGELOG.md
Fareware to alpine.
* Remove alpine from CD pipeline
KAG-983
> chore(cd): remove alpine from CD pipeline

- CHANGELOG.md
The `kong.tools.batch_queue` module was renamed to `kong.tools.queue` as part of a reimplementation of  plugin queues: https://github.com/Kong/kong/pull/10172
The`CHANGELOG.md` incorrectly states that the module has been renamed to `kong.tools.batch`
> docs(changelog): fix name of renamed queue module

- scripts/dependency_services/common.sh
The cassandra container is already removed from https://github.com/Kong/kong/pull/10853
> chore(dependency_services): drop cassandra

- kong/init.lua
- kong/tracing/instrumentation.lua
- spec/fixtures/custom_plugins/kong/plugins/tcp-trace-exporter/handler.lua
Fix a bug (only affecting 3.3+) that will result in resolving flakiness in the following tests:
* opentelemetry exporter #postgres #scoping for service with global works
* tracing propagation spec #postgres spans hierarchy propagates the balancer span
* tracing propagation spec #postgres parsing incoming headers enables sampling when incoming header has sampled enabled
Caused by:
- [This error](https://github.com/Kong/kong/blob/77e4e124532be603075f257ab8173d59d5d336b9/kong/pdk/tracing.lua#L288) that came from [here](https://github.com/Kong/kong/blob/77e4e124532be603075f257ab8173d59d5d336b9/kong/tracing/instrumentation.lua#L135) due to [the approximation](https://github.com/Kong/kong/blob/77e4e124532be603075f257ab8173d59d5d336b9/kong/tracing/instrumentation.lua#LL134C1-L134C1) that …
> fix(tracing): address flakiness and resolve approximation bug

- CHANGELOG.md
- kong/clustering/compat/init.lua
- kong/pdk/node.lua
- kong/plugins/prometheus/exporter.lua
- kong/plugins/statsd/log.lua
- kong/plugins/statsd/schema.lua
- spec/01-unit/19-hybrid/03-compat_spec.lua
- spec/03-plugins/06-statsd/01-log_spec.lua
- spec/03-plugins/26-prometheus/05-metrics_spec.lua
- t/01-pdk/12-node/02-get_memory_stats.t
add lmdb metrics to prometheus and statsd, also extend PDK `kong.node.get_memory_stats()`  lmdb capabilities. 
sister PR : https://github.com/Kong/lua-resty-lmdb/pull/25
FTI-4749
> feat(pdk): add lmdb metrics

- spec/03-plugins/06-statsd/01-log_spec.lua
In some cases, shared memory is used to trigger periodic pushes of metrics. This may let statsd flaky test.
KAG-1589, [KAG-1413]
[KAG-1413]: https://konghq.atlassian.net/browse/KAG-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(statsd): fix statsd grpc flaky test

- spec/02-integration/05-proxy/06-ssl_spec.lua
DNS querying costs a lot of time, here I add an option `mocks_only = true`, 
this will avoid actual dns querying, and reduce the time cost from 1-10s to 10ms.
KAG-1644
> tests(proxy/ssl): add mocks_only to avoid dns querying

- kong/clustering/init.lua
`json_handler` and `child` are bad names, people can not understand their real meaning and functionality.
Actually, they are the same things but act as different roles. 
If you have a better idea please leave comments here, thanks.
- rename `json_handler` and `child` to `instance`
- move `cp:new` to `init_worker()`, this will cause each worker to create the object but not copy from the master, but I think the cost is very small
> style(clustering): rename fields `json_handler` and `child`

- spec/helpers.lua
Deprecate `http_server`. The comments could be ignored so we need to make a more noticeable warning.
KAG-1148
> chore(test): deprecate http_server

- spec/03-plugins/34-zipkin/zipkin_spec.lua
backport of https://github.com/Kong/kong/pull/10907
[KAG-1609](https://konghq.atlassian.net/browse/KAG-1609)
[KAG-1609]: https://konghq.atlassian.net/browse/KAG-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport release/3.2.x] tests(zipkin): addressing flakiness

- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
Add a test that verifies the presence of a capacity warning if a queue is reaching the queue capacity warning threshold.
KAG-1579
> tests(queue): verify that capacity warning is produced

- CHANGELOG.md
- kong/api/routes/config.lua
- kong/clustering/data_plane.lua
- kong/init.lua
I was curious as to why some admin API tests for `/config` were so slow and went digging. Turns out this endpoint was reloading the declarative schema on every request, adding several hundred milliseconds of latency.
This updates the logic in Kong.init() to load the declarative config schema and store it in the kong global at `kong.db.declarative_config`.
```
$ busted spec/02-integration/04-admin_api/15-off_spec.lua --filter concurrency
●
1 success / 0 failures / 0 errors / 0 pending : 42.547819 seconds
```
```
$ busted spec/02-integration/04-admin_api/15-off_spec.lua --filter concurrency
●
1 success / 0 failures / 0 errors / 0 pending : 3.752036 seconds
```
No additional tests are needed because the functionality is already tested:
The following tests exercise the declarative config …
> perf(dbless): load declarative schema during init()

- spec/03-plugins/23-rate-limiting/04-access_spec.lua
- spec/fixtures/redis/docker-entrypoint.sh
The CE plugin `rate-limiting` test units take over 60s for each. This PR tries to improve the performance.
* Test refactor
* Change limit window from `minute` to `second`.
* Reduce limit number from `6` to `1`.
* Safeguard by 10 rounds.
Fix FTI-4988
> tests(rate-limiting): improve flaky test

- spec/02-integration/09-hybrid_mode/11-status_spec.lua
This PR will reduce the waiting time for dp testing.
KAG-1650
* use `nginx_main_worker_processes`
* start cp before dp
> tests(api/status): improve test performance of status/ready

- CHANGELOG.md
- kong/db/errors.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
This is a bugfix backport of #10896.
> fix(dbless): handle unexpected types when flattening errors

- CHANGELOG.md
- kong/api/routes/config.lua
- kong/clustering/data_plane.lua
- kong/init.lua
This is a backport of #10932.
With this change we are no longer reloading the declarative schema for every `POST /config` request (something that has been the case since 3.0, I think).
The schema load operation adds 150-200ms of latency to each request in my local testing:
```
$ wrk -c 1 -t 1 -s wrk.lua --latency -d 60 http://localhost:8001/config
```
<details>
<summary>wrk.lua</summary>
```lua
local cjson = require "cjson"
local conf = {
_transform = false,
_format_version = "3.0",
services = {},
}
for i = 1, 500 do
conf.services[i] = {
name     = "my-service-" .. tostring(i),
protocol = "http",
host     = "127.0.0.1",
port     = 80,
routes   = {
{
name = "my-service-route-" .. tostring(i),
hosts = { "my-service-route-" .. tostring(i) .. ".test" },
paths = { "/" },
}
}
}
end
local body = …
```
> perf(dbless): load declarative schema during init() (#10932) [backport]

- UPGRADE.md
I think 'and' was mistakenly written as 'ad'
> docs(upgrade.md): fix a typo in UPGRADE.md

- scripts/dependency_services/up.fish
Set `$cwd` var correctly when calling `stop_services` or `deactivate`.
* fix(venv): fix cwd var not persist to child process
> fix(venv): fix cwd var not persist to child process

- DEVELOPER.md
Bazel will start the development databases automatically, so it's not needed to start them manually using the compose file in the kong-tests-compose repository. Update the developer doc to remove the associated section.
- [no] There's an entry in the CHANGELOG
- [no] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
Removed the ```Databases``` section from the DEVELOPER.md.
> docs(developer): remove the manual database startup step

- kong/db/init.lua
- kong/db/strategies/connector.lua
As Cassandra is now gone from codebase, we can remove this function too.
> chore(db): remove connector:wait_for_schema_consensus

- build/repositories.bzl
In bazel, files are always read in ISO-8859-1 encoding by using `ctx.read` (https://github.com/bazelbuild/bazel/blob/67446d/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java#LL906C39-L906C39), but the `ctx.file` choose write content to disk in UTF-8 by default
(https://github.com/bazelbuild/bazel/blob/67446d/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java#L813-L817)
This behavior will cause the multi-byte character in UTF-8 files been encoded byte-by-byte in UTF-8 again, corrupting the file content.
Luckily, Bazel provides a `legacy_utf8` (https://bazel.build/rules/lib/builtins/repository_ctx#parameters_5) in `ctx.file` to force the file to be written in ISO-8859-1 encoding, make …
> chore(build): write copyright header in correct encoding

- kong/db/schema/init.lua
This was fixed a long time ago:
https://github.com/lunarmodules/Penlight/commit/967ed9b99f9a99910ac0ade8ab0383834666f2dc
Now removing code that is not needed anymore.
> chore(db): tablex.deepcopy is cycle aware, no need to re-implement copy

- kong/init.lua
- kong/runloop/handler.lua
There are several functions in handler.lua that does (almost) nothing.
This commit removes that unneccessary indirection. Hopefully less need to jump between files to see what is going on.
> chore(runloop): remove unused handler functions

- CHANGELOG.md
- kong/plugins/rate-limiting/policies/init.lua
- spec/03-plugins/23-rate-limiting/02-policies_spec.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
fix rate-limiting accuracy reported on issue: https://github.com/Kong/kong/issues/5311
There is a low impact change to the current code and this implementation has better accuracy on redis policy
it is same fix made in PR https://github.com/Kong/kong/pull/8227, but I remove sliding-window feature. Kong have no plans to add a sliding window to this plugin, Sliding window is an enterprise-only feature at this point
[it removes the race condition problem getting keys on redis. it uses the return of the increment command as the usage counter ensuring atomicity, different from the current one, which allows multiple requests to get the same value of the redis key while the counter increment is done asynchronously]
[it has an even better performance than the current plugin using the redis …
> fix(plugin/rate-limiting): use `redis:eval()` to improve rate-limiting accuracy

- spec/02-integration/11-dbless/01-respawn_spec.lua
This will fix a flaky test in `spec/02-integration/11-dbless/01-respawn_spec.lua`:
https://github.com/Kong/kong/actions/runs/5034879042/jobs/9029977684
---
**NOTE:** I had to rework some of the logic in the `worker respawn rotates pids and deletes the old ones` test in order to make things work with an explicit worker process count. I put that work in a separate commit for ease of review, but it's probably okay to squash them at merge time.
> tests(dbless): wait until respawn is complete to make requests

- .ci/run_tests.sh
Just checking how far this goes. Perhaps errors horribly, but we are we not running all the tests in `t/`?
> tests(ci): enable all tests in t folder, not only the pdk ones

- kong/tools/utils.lua
Just replaces utils.deflate_gzip / utils.inflate_gzip to use `string.buffer`s.
> perf(utils): faster deflate_gzip / inflate_gzip using string.buffer

- spec/02-integration/11-dbless/01-respawn_spec.lua
- spec/helpers.lua
This is a follow-up to work that was done in 9cbbee3c8a / #10982 to correct a couple more lingering issues.
In order to reproduce some of the weirdness that seems to only happen in CI, I set WORKER_PROCS to 64 and re-ran the test suite a whole bunch of time. I found the following:
* not all worker data (pids, memory stats, etc) is guaranteed to be available via the admin API immediately after Kong has started, so test cases that fetch this data at the beginning of the test need to be wrapped with `assert.eventually(...)`.
* the way that the worker pid table is computed in the `/` API endpoint [can result in a sparse array with NULL values](https://github.com/Kong/kong/blob/adf6c4d8b5b62c4084ec219e066e50a788d7beee/kong/api/routes/kong.lua#L73-L86), so we need to filter those items out …
> tests(dbless): harden test against eventual consistency

- kong-3.4.0-0.rockspec
- kong/cache/init.lua
- kong/plugins/pre-function/_handler.lua
- kong/resty/mlcache/init.lua
- kong/resty/mlcache/ipc.lua
- kong/runloop/certificate.lua
- t/05-mlcache/00-ipc.t
- t/05-mlcache/01-new.t
- t/05-mlcache/02-get.t
- t/05-mlcache/03-peek.t
- t/05-mlcache/04-update.t
- t/05-mlcache/05-set.t
- t/05-mlcache/06-delete.t
- t/05-mlcache/07-l1_serializer.t
- t/05-mlcache/08-purge.t
- t/05-mlcache/09-isolation.t
- t/05-mlcache/10-ipc_shm.t
- t/05-mlcache/11-locks_shm.t
- t/05-mlcache/12-resurrect-stale.t
- t/05-mlcache/13-get_bulk.t
- t/05-mlcache/14-bulk-and-res.t
Forking `resty.mlcache` into Kong in preparations on adding functionality and changes to it that are out of the scope for the upstream project. Some of which we may try to contribute to upstream too.
> chore(deps): import resty.mlcache from lua-resty-mlcache

- kong/clustering/data_plane.lua
- kong/clustering/events.lua
- kong/clustering/init.lua
Remove semaphore in DP, replaced by lua-resty-events `post_local()`.
Also, remove `config_exit` and `config_thread`.
These changes make the code more understandable.
*  remove `config_exit` and `config_thread`
* register/unregister the handler for each communication
* add `init_dp` and other APIs in `events.lua`
> refactor(clustering): use local event for reconfigure in dp

- scripts/dependency_services/common.sh
- scripts/dependency_services/up.sh
on OSX the default bash is v3.2 and does not have associative array support that is needed by dependency_services/common.sh. A more recent bash (for eg via Homebrew) can be picked up correctly if supplied in the PATH.
Cherry-pick from EE#5595
> fix(venv): pickup bash from env (#5595)

- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
Backport 9ceaddbde341e08fb7650d45c8e7f3e301f5dfae from #10881.
> tests(integration): avoid passive health check flakiness (#10881)

- CHANGELOG.md
- kong-3.4.0-0.rockspec
- chore(utils): remove dependency for lua_pack
> chore(deps): bump resty.session from 4.0.3 to 4.0.4

- kong/runloop/balancer/balancers.lua
`targets.fetch_targets(upstream)` can not return error, so `    return nil, "failed fetching targets:" .. err` will abort in coroutine.
> fix(balancer): fix balancer error thread abort code

- kong/plugins/prometheus/handler.lua
if `upstream_health_metrics` config true->flase change, in the `handler` code, it is not working.
> fix(prometheus): fix upstream_health_metrics config true->false change not working issues

- kong/clustering/data_plane.lua
Port some core code of #11006, removing the usage of worker events.
> refactor(clustering): clean the code of config thread

- spec/03-plugins/23-rate-limiting/04-access_spec.lua
Explicitly set a timeout for rate-limiting test. By default, the timeout value is 5, and does not match the max try 10.
* explicitly set timeout to 15
Fix #FTI-5126
> tests(rate-limiting): explicitly set timeout to 15

- kong/clustering/data_plane.lua
Introduce `goto continue` to remove the big `if-else` statement.
> style(clustering): clean the code of read_thread

- build/openresty/openssl/openssl.bzl
- spec/03-plugins/29-acme/03-access_spec.lua
Previously, openssl seems to default to -O2 even if used with -d (debug build), this is changed on openssl 3.x.
And no opt level is set when using -d, which is the mode we use on CI.
This PR forces opt level to be set on both debug build (on CI) and release build (for releasing artifacts). So the performance degression on CI could be solved.
* fix(build): explictly set -O3 for OpenSSL
* [fix(tests): revert previous change that increases some timeout when bump openssl to 3.0.8](https://github.com/Kong/kong/commit/b9b80c210fc3283cf7f8c1515b2fc48e5c1747d8)
> fix(build): explictly set -O3 for OpenSSL

- CHANGELOG.md
- kong/plugins/prometheus/exporter.lua
- kong/plugins/prometheus/prometheus.lua
base on https://github.com/Kong/kong/pull/10749#issuecomment-1523111032
In my testing, the most CPU-intensive task for the Prometheus plugin is the part of iterating through all upstream health statuses. This part blocks for around 400ms on every metrics request (with 10k upstreams and 20k targets), which is unacceptable for us.
And I found the most time-consuming points in this function, which are caused by excessive creation of temporary tables leading to excessive GC pressure, as well as some performance losses caused by `table.insert` `string.gsub` due to Luajit NYI. Therefore, the solution to this problem is that
1. try to `yield` in long loop in upstream iteration.
2. fix NYI in `full_metrics_name` function, and reduce `gsub` function call.
In my opinion, this iteration doesn't …
> perf(prometheus): fix upstream health expensive iterate latency spike issue

- spec/03-plugins/23-rate-limiting/04-access_spec.lua
The current test make two sequencial requests. The two response bodies may be overlapped.
The fix reorders the request lines.
* reorder the request lines.
Fix #FTI-5126
> tests(rate-limiting): order two request lines

- CHANGELOG.md
- kong/api/routes/health.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
- spec/02-integration/08-status_api/01-core_routes_spec.lua
Remove the meaningless database status information from the status API when operating in dbless mode or data plane.
Fix [FTI-5034](https://konghq.atlassian.net/browse/FTI-5034)
[FTI-5034]: https://konghq.atlassian.net/browse/FTI-5034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api/status): remove the database status in dbless mode and data-plane

- kong/init.lua
Loading and checking of migration state is necessary only when the node is connected to a database. This is true only for traditional mode nodes and 'control_plane' nodes in hybrid mode. Checking the migration state when there is no database is a wasteful operation.
This patch checks (and loads migration state) only when necessary. Early test report a reduction of 5 MB of RSS per worker on start-up.
N/A
> perf: load migration state only when connected to a database

- CHANGELOG.md
- kong.conf.default
- kong/templates/kong_defaults.lua
The current size of 128MB is too conservative and requires bumping by the user in a lot of cases. Bumping to a more sensible value to avoid this.
KAG-1811
> feat(templates): bump default `lmdb_map_size` to 2GB

- Makefile
Improve `Makefile`.
* When we tear down bazel venv, we should remove downloaded binaries.
Fix #FTI-5139
> chore(dev): remove downloaded binaries after bazel clean

- .github/workflows/perf.yml
- kong/plugins/zipkin/README.md
- scripts/upgrade-tests/test-upgrade-path.sh
`gtest` hides a lot of information. It does not even output the assertion failure message.
The output of tests may help us to fix test failures. So this PR tries to remove all `-o gtest` for busted tests.
> chore(test): default output format for more info

- kong/conf_loader/init.lua
A subset of kong.conf options were truncated. A new audit was performed and additional fields 
were added in.
* remove more sensitive fields from kong.conf
> fix: remove sensitive kong.conf fields

- kong/router/atc.lua
Use `string.buffer` in function `gen_for_field()` to improve the performance.
* Use `string.buffer` in function `gen_for_field()`
* `string.find` then `string.gsub`
> perf(router/atc): generate expressions with string.buffer

- CHANGELOG.md
- kong/plugins/prometheus/prometheus.lua
This a performance improvement of #10949, using `string.buffer` to generate metrics string,
eliminate the cost of huge table.
KAG-1783
* remove `table.new`
* introduce `string.buffer`
* only do `gsub` for string value
> perf(plugin/prometheus): generate metrics string with string.buffer

- build/repositories.bzl
This PR updates the version of GitHub CLI to v2.30.0 - As macOS distributions are no longer distributed as .tar.gz files, this required a bit of adaptation in addition to bumping the version number
> chore(build): bump GitHub cli to v2.30.0

- kong-3.4.0-0.rockspec
- kong/db/migrations/core/000_base.lua
- kong/db/migrations/core/020_330_to_340.lua
- spec/05-migration/db/migrations/core/020_330_to_340_spec.lua
- spec/upgrade_helpers.lua
It looks like we forgot to drop this table in a past, so removing it now in 3.4.0.
> chore(migrations): do not create ttls table anymore and remove it

- kong/router/atc.lua
This PR follows #11045, continue to optimize the string usage by `string.buffer`.
> perf(router/atc): generate headers_key with `string.buffer`

- Makefile
fix bazel clean command called in `build-release` job in makefile to avoid the error
```
ERROR: --expunge :: Unrecognized option: --expunge
```
Fix on makefile 
~- [ ] There's an entry in the CHANGELOG~
~- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
> fix(makefile): fix bazel clean command

- kong/router/compat.lua
Introduce `string.buffer` to replace `table.concat`
> perf(router/compat): using string buffer to generate expressions

- .github/workflows/release.yml
amazonlinux2022 removed perl-App-cpanminus; although we were not building amzlinux for Kong, porting this to reduce conflicts.
> fix(build): port amazonlinux 2022 fixes from EE

- kong/cache/init.lua
- kong/global.lua
Kong cache has huge LRU cache of 500.000 items by default, and we create caches two times, one for core and one for rest. The LRU takes around 15 MB of memory (so 30 MB in total), per worker.
Without this change the:
```
KONG_ROLE=control_plane KONG_CLUSTER_CERT=cluster.crt KONG_CLUSTER_CERT_KEY=cluster.key kong start
```
takes around 65 MB of memory (per worker), after this change, it only takes around 35 MB (per worker). On 8 core machine it would mean about 240 MB reduction in memory usage.
The control plane rarely if ever uses `kong.cache`, and it does not require such big LRU. This commit reduces size of LRU cache on control planes to 1.000 items.
> perf(core): reduce memory usage of control plane worker processes

- kong/tracing/instrumentation.lua
`string.buffer` is faster and efficient than `table.concat`.
> perf(tracing): use string.buffer instead of table.concat

- CHANGELOG.md
- kong/clustering/compat/removed_fields.lua
- kong/plugins/rate-limiting/handler.lua
- kong/plugins/rate-limiting/policies/init.lua
- kong/plugins/rate-limiting/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/23-rate-limiting/02-policies_spec.lua
- spec/03-plugins/23-rate-limiting/04-access_spec.lua
<del>**BLOCKED BY https://github.com/Kong/kong/pull/9764**</del> :white_check_mark:
Adds a new configuration `sync_rate` to the `redis` policy, which synchronizes metrics to redis periodically instead of on every request.
Fix _FT-3464_
Fix #8729
> perf(rate-limiting): sync to redis periodically

- kong/router/atc.lua
- kong/router/compat.lua
In PR #10615, we have grouped regex and plain paths,
so the sort action is unnecessary.
* remove sort action in `compat.lua`
* move table.* in `get_headers_key` block
> refactor(router): remove unnecessary sort of paths and code clean

- CHANGELOG.md
- kong-3.4.0-0.rockspec
- **\*:** fix typos and add error check for new_of/dup_of ([#2](https://github.com/fffonion/lua-resty-openssl/issues/2)) [aa6ad47](https://github.com/fffonion/lua-resty-openssl/commit/aa6ad4707845cca9c46282a1550bb9fee7d48698)
- **tests:** add performance test ([#112](https://github.com/fffonion/lua-resty-openssl/issues/112)) [100b4e4](https://github.com/fffonion/lua-resty-openssl/commit/100b4e43843a597327be6e5356c64b5ce621fa56)
- **x509.store:** add store:check_revocation and add flag to skip check CRL for store:add ([#1](https://github.com/fffonion/lua-resty-openssl/issues/1)) [1a5a4c8](https://github.com/fffonion/lua-resty-openssl/commit/1a5a4c881128ffb65d6eaf47bb3961417ef23f0b)
> chore(deps): bump resty.openssl from 0.8.22 to 0.8.23

- Makefile
Bazelisk v1.17.0 comes with updated dependencies, minor bug fixes and new features:
The Go version...
... supports custom download URLs via the BAZELISK_FORMAT_URL env variable ... now only downloads Bazel when necessary
... can check the hash of downloaded binaries via the BAZELISK_VERIFY_SHA256 env variable ... makes it easier to find out which Bazel change broke your build with the --bisect option ... is more robust in the face of transient GCS download issues
The Python version now properly recognises WORKSPACE.bazel files.
We’d like to thank our amazing contributors @jmmv and @jwnimmer-tri!
> chore(deps): bump bazelisk from 1.16.0 to 1.17.0

- Makefile
* Migrated to lunarmodules org, lowercased repository name, started using 'v' prefix for tags
* Add Dockerfile and publish build to ghcr.io
* Configure repository for use *as* a GitHub Action
* Support CommonMark via cmark-lua processor
* Add `--version` and improve CLI `--help` output
* Add 'new' theme
* Add filetype for xLua's .cs files
* Add options for project icons & favicons
* Distinguish between static/class members in moonscript
* Add support for Lua 5.4
* Add feature to skip adding timestamps to output
* Prettify Lua function names
* Make `@param` tag multiline
* Allow using `@module`, `@script`, `@file`, etc. multiple times in a single source file
* Expand builtin tparam aliases to full type names
* Add `--unsafe_no_sandbox` argument and allow importing Lua modules from config
* …
> chore(deps): bump ldoc from 1.4.6 to 1.5.0

- .ci/luacov-stats-aggregator.lua
- .ci/run_tests.sh
- .github/workflows/build_and_test.yml
- spec/fixtures/default_nginx.template
- spec/helpers.lua
Add test coverage for integration and plugins tests.
Luacov is enabled in these tests via nginx configuration, similarly to the following:
```
init_by_lua_block {
require 'luacov'
jit.off()
-- (rest of the init_by_lua_block)
}    
```
This is done conditionally, in `custom_nginx.template`, when `KONG_TEST_COVERAGE=on`.
In order to make this possible even for tests that currently don't use a custom nginx configuration, a new template `default_nginx.template` was defined, that will be used when when `helpers.start_kong` is called without passing a custom template via `nginx_conf`.
---
Enabling coverage with luacov produces a considerable performance degradation. This has the direct consequence of producing more flakiness and failures. This PR aims to define a workflow that runs integration …
> tests(coverage): add coverage for integration tests

- Makefile
- Update Löve standard to 11.4 — @RunningDroid
- Documentation improvements — @rcloran and @hramrach
- Correct compound operators to not crash on modifying upvalues — @arichard4
- Fix warning 582 (error prone negation) not applying to subexpressions — @appgurueu
> chore(deps): bump luacheck from 1.1.0 to 1.1.1

- t/03-dns-client/02-timer-usage.t
Cherry-picks commit from EE to make tests green on EE side, should be fine here too.
> tests(ci): enable all tests in t folder, not only the pdk ones (EE changes)

- CHANGELOG.md
- kong.conf.default
- kong/templates/kong_defaults.lua
> feat(templates): bump `cluster_max_payload` default to 16MB

- kong/runloop/plugins_iterator.lua
- spec/01-unit/28-plugins-iterator/01-compound_key_spec.lua
- spec/01-unit/28-plugins-iterator/02-lookup_cfg_spec.lua
This patch set changes how the Plugins Iterator finds suitable plugin configurations for defined precedence rules.
To achieve that, we move from a nested table structure that stores various combinations of `route, service and consumer` to a _flat_ hashmap.
**Before.**
```lua
combos[name].rsc[cfg.route_id] =
combos[name].rsc[cfg.route_id] or {}
combos[name].rsc[cfg.route_id][cfg.service_id] =
combos[name].rsc[cfg.route_id][cfg.service_id] or {}
combos[name].rsc[cfg.route_id][cfg.service_id][cfg.consumer_id] = cfg
combos[name].rc[cfg.route_id] =
combos[name].rc[cfg.route_id] or {}
combos[name].rc[cfg.route_id][cfg.consumer_id] = cfg
-- and so on for all possible combinations
```
**After:**
```lua
-- Build a compound key using the route_id, service_id, and consumer_id
local compound_key = …
```
> refactor(core): plugins iterator state-building & lookup algorithm 

- CHANGELOG.md
- kong/plugins/prometheus/api.lua
- kong/plugins/prometheus/exporter.lua
- kong/plugins/prometheus/prometheus.lua
This PR follows #11040, continue to optimize the string usage by string.buffer.
KAG-1852
* use `table.new` for `seen_metrics`
* `buffered_print()` outputs a string, not a table
* change `printable_metric_data` of stream to fit the new `buffered_print()` 
* do not use `ipairs` to iterate array
* other small optimizations
> perf(plugin/prometheus): generate metrics output data with string.buffer

- kong/clustering/compat/removed_fields.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
https://github.com/Kong/kong/pull/9538 was created before `3.3.0` released, so the remove_fields was added for `3.3.0`.
Now we are developing `3.4`, so we need to move that to the correct place.
> fix(clustering): move `remove_fields` of `sync_rate` to the right version

- CHANGELOG.md
- kong/api/api_helpers.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
`parse_params` should not call `normalize_nested_params` for `application/json`. Otherwise, the key-value pair of `custom_fields_by_lua` will be converted into a nested table if the key contains dot character(s), which will cause schema violation when calling `/schemas/plugins/validate`
* Fix an issue where `/schemas/plugins/validate` endpoint fails to validate valid plugin configuration when the key of `custom_fields_by_lua` contains dot character(s).
Fix [FTI-5070](https://konghq.atlassian.net/browse/FTI-5070)
[FTI-5070]: https://konghq.atlassian.net/browse/FTI-5070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): schema violation when validating valid plugin configuration

- spec/02-integration/03-db/07-tags_spec.lua
Re-enabling and fixing some flaky tests disabled before.
[KAG-1318]
[KAG-1318]: https://konghq.atlassian.net/browse/KAG-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(db): re-enable and fix flaky tests in spec/02-integration/03-db/07-tags_spec.lua

- CHANGELOG.md
- build/package/kong.service
Previously, no User clause was present in the systemd unit definition for Kong.  While this still made systemd run kong under the 'root' user id, the HOME environment variable would not be set in the Kong process.  This caused the datafile library to fail with various error conditions.  This really is an EE-only issue at this point, but providing Kong a complete run environment with all standard environment variables is prudent for CE as well.
KAG-1832
> fix(service): explicitly set user in systemd definition

- DEVELOPER.md
Correct the Plugin Development Guide url.
> docs(developer): correct the plugin development guide url

- .github/labeler.yml
Backport https://github.com/Kong/kong/commit/9a95a3282e03116ed54d47cf18aeb9504b312eb2 from https://github.com/Kong/kong/pull/10996.
> [Backport release/3.2.x] chore(labeler): add new schema noteworthy path 

- kong/plugins/prometheus/prometheus.lua
The second param of `ngx.re.gsub()` is a regex pattern, 
so `\\` is actually `\`, which is an invalid regex.
Note: `ngx.re.gsub()` is different from `string.gsub()`!
This PR gives the correct regex to `ngx.re.gsub()`.
> fix(plugin/prometheus): fix an error of ngx.re.gsub

- kong/plugins/prometheus/prometheus.lua
Import some changes from https://github.com/knyar/nginx-lua-prometheus/pull/131.
> perf(plugin/prometheus): remove the usage of `string.gsub` and `ipairs`

- kong/clustering/control_plane.lua
- kong/db/schema/init.lua
On control plane there was a debug log written on every second on every worker that had no connected clients. This will now only log it once per worker, until number of connected clients changes.
The schema validation also had a thing called unvalidated fields that caused huge amounts of logs to be written with large config import / validation. (I didn't count but with my example config I got thousands, perhaps tens of thousands of log lines on same second with exactly same uninformal message `2023/06/26 20:08:36 [debug] 72011#0: *10 [kong] init.lua:1121 ignoring validation on updated_at field`).
> chore(clustering/db): reduce log flooding on clustering and schema validation

- kong/clustering/data_plane.lua
- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
- spec/helpers.lua
With this patch, kong.conf settings of a DP are self-reported to the CP. Sensitive credentials from kong.conf are redacted before they are sent to the CP.
This patch reports the configuration, LuaCP isn't going to do anything with it just yet. This feature is specific to Kong Inc's Konnect offering.
> feat(hybrid): report configuration of DP to the CP

- kong/router/compat.lua
Sni expression should have the same format as others, i.e. `( ... )`.
> style(router/compat): add bracket for sni expression

- CHANGELOG.md
- kong/tracing/instrumentation.lua
- spec/02-integration/14-tracing/01-instrumentations_spec.lua
- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
This PR adds the `http.route` span attribute to the kong request span, adapts existing tests to pass with the new attribute and improves instrumentation tests, by adding checks for all spans and attributes.
[KAG-1719](https://konghq.atlassian.net/browse/KAG-1719)
#8125
[KAG-1719]: https://konghq.atlassian.net/browse/KAG-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tracing(instrumentation): add http.route span attribute

- kong/plugins/prometheus/prometheus.lua
Use `ngx.re.match` to replace `string.match` to get better performance.
> perf(plugin/prometheus): use ngx.re.match to replace string.match

- CHANGELOG.md
- kong/tools/utils.lua
- spec/02-integration/05-proxy/12-error_default_type_spec.lua
- t/01-pdk/08-response/13-error.t
remove kong branding from kong HTML error template
FTI-4560
> fix(proxy): remove kong branding from kong HTML error template

- CHANGELOG.md
- kong/pdk/tracing.lua
- spec/02-integration/14-tracing/02-propagation_spec.lua
- spec/02-integration/14-tracing/03-tracer-pdk_spec.lua
This commit fixes a bug where the sampling rate was applied to individual spans.
Problem: when sampling_rate is < 1 and the root span is not sampled, children (that are sampled) are reported without a parent so traces are split (producing multiple traces with different trace IDs for a single request).
The fix ensures that the sampled flag that is calculated by the sampler for the root span is propagated to all children in the same trace.
KAG-1926
> fix(tracing): ensure sampling rate applies to whole trace

- scripts/upgrade-tests/test-upgrade-path.sh
- spec/02-integration/16-queues/01-shutdown_spec.lua
- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
- spec/05-migration/plugins/http-log/migrations/001_280_to_300_spec.lua
- spec/helpers.lua
- spec/helpers/http_mock/asserts.lua
Replacing uses of `helpers.http_server` with the new implementation of HTTP mocking, which is more stable.
Fix KAG-1148
> test(*): remove http_server

- CHANGELOG.md
- kong/router/compat.lua
- spec/01-unit/08-router_spec.lua
In `traditional_compatible` mode, the router would fail to work if a route with multiple paths but no service would be created.
Fixes KAG-1961
> fix(router): don't fail on route with multiple paths

- .github/matrix-full.yml
- BUILD.bazel
- build/BUILD.bazel
- build/openresty/BUILD.openresty.bazel
- build/openresty/wasmx/wasmx_repositories.bzl
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-18.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
This turns on `ngx_wasm_module` by default, adding it to all of our amd64 builds in the release workflow.
Right now we only build and package with `wasmtime`, because that is what is planned to ship, but there is partial support for wasmer and v8 in here as well, should we decide to make them available in the future.
Additionally, with this change the wasm runtime is now statically linked to `ngx_wasm_module`, so there are fewer shared object files that need to be copied around into our common lib directory at build time.
> chore(ci): add wasm to release builds

- kong/plugins/prometheus/exporter.lua
- kong/plugins/prometheus/prometheus.lua
some small optimizations for prometheus.
> refactor(plugin/prometheus): some small optimizations

- CHANGELOG.md
- kong/router/expressions.lua
- spec/02-integration/05-proxy/19-grpc_proxy_spec.lua
- spec/02-integration/05-proxy/21-grpc_plugins_triggering_spec.lua
- spec/helpers.lua
> fix(router/expressions): mapping protocols in expression

- Makefile
- spec/helpers.lua
Adds a tool `h2client` https://github.com/Kong/h2client for us to easily test http2 requests, possibly also grpc(s) requests.
This removes the requirement of lua-http and possibly lua-curl so that our bump to openssl 3 won't break those libraries.
* chore(dev): install h2client in make dev
* feat(tests): use h2client to replace lua-http in spec.helpers
> feat(tests): use h2client to replace lua-http in spec.helpers

- .github/workflows/build_and_test.yml
- .luacov
- t/pdk.luacov
Icludes untested files (coverage = 0%) in luacov reports
Modifies the coverage report to print files sorted by coverage in the CI workflow
KAG-1914
> tests(coverage): luacov include untested files

- Makefile
Add a new `test-custom` target to the makefile that allows an individual test to be run without entering the venv on the shell.
The `test_spec` variable needs to be set on the command line:
```
make test-custom test_spec=spec/01-unit/02-rockspec_meta_spec.lua
```
This is a convenience change to support a particular developer workflow.
Supersedes https://github.com/Kong/kong-ee/pull/5596
> chore(makefile): add test-custom target to run individual test

- .github/matrix-full.yml
- .github/workflows/release.yml
- scripts/explain_manifest/config.py
- scripts/explain_manifest/fixtures/amazonlinux-2023-amd64.txt
- scripts/explain_manifest/fixtures/el8-amd64.txt
Previously we were releasing rhel8 and amazonlinux2022/3 packages from its previous version of distro,
namely rhel7 and amazonlinux2 packages. Because normally libraries are backward compatible, they will just work.
This is also the approach that pypi's prebuilt images are using.
To be able to correctly verify the package and precisely use matching libraries that doesn't rely on backward
compatibility, we now move those packages to build on its matching docker container. This also matches what
we are already doing in EE.
We also move to package only one RPM package for each matrix to reduce the boilterplate code and size of artifact.
* …
> chore(cd): build RPM packages in container matching the distro

- CHANGELOG.md
- kong/router/compat.lua
- kong/router/expressions.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
- spec/02-integration/05-proxy/19-grpc_proxy_spec.lua
- spec/02-integration/05-proxy/21-grpc_plugins_triggering_spec.lua
KAG-1251
This is a follow up of #11082.
if `route.protocols` has only `https`, we will not add `net.protocol` to expression.
This will give the runloop a chance to check http redirection.
Note:
Now `expressions` does not support `tcp/tls`, so we skip these test cases.
> fix(router/expressions): http redirection can't work with "expressions"

- .gitignore
- Makefile
- spec/02-integration/05-proxy/27-unbuffered_spec.lua
- spec/helpers.lua
As we need to use curl as http clients in tests that use HTTP/2.0, we need to add it to our base images.  This ensures that tests that require curl have it available in all situations (i.e. during migration and upgrade tests, pongo based tests etc.).
This is a revised version of the reversal PR #10599 which switched off the tests for #10595
KAG-1105
> fix(tests): revive HTTP/2.0 tests

- CHANGELOG.md
- kong-3.4.0-0.rockspec
Temporary switch to Kong's fork since 3.4 is close and upstream may not merge our PR in time.
Changes included are in https://github.com/Kong/pgmoon/pull/30.
In the future, the Kong's fork should be unified into one, that re-based on a more recent version of
pgmoon upstream. Almost all of the features we put in our fork has been implemented in a different
way in upstream later.
This change should not be cherry-picked to EE.
chore(deps): use kong's fork of pgmoon that fixes an issue when using SCRAM auth with OpenSSL 3.x
Fix KAG-1936
> chore(deps): use kong's fork of pgmoon that fixes an issue when using SCRAM auth with OpenSSL 3.x

- kong/pdk/tracing.lua
The function should be called with a tracer instead of spans.
Found in #11143
> fix(tracing): incorrect comment and documentation

- kong/router/compat.lua
- kong/router/expressions.lua
`ngx.log` and other `ngx.*` are in cold path, localization of them is unnecessary.
> style(router): need not to localize ngx.* in cold path

- kong/router/compat.lua
- kong/router/utils.lua
- move `is_regex_magic()` into utils
- localize `shallow_copy`
> refactor(router): localize some tool functions

- kong/clustering/utils.lua
- kong/conf_loader/init.lua
- kong/global.lua
- kong/init.lua
- kong/templates/kong_defaults.lua
Data plane's connection to control plane is moved to a privileged agent worker process, including:
- maintaining websocket (wrpc) connection and data transfer
- decompression of received data
- json decoding of the received data
- validation and flattening of received data
- inserting data to lmdb
(so that these won't affect latencies / rps on proxy workers)
This time behind configuration flag, and disabled by default.
See previous attempts:
#9432
#8971
KAG-114
> perf(clustering): optionally use privileged agent for control plane connection

- CHANGELOG.md
- kong/router/compat.lua
- spec/01-unit/08-router_spec.lua
In `traditional_compatible` mode, the router would fail to work if a route with multiple paths but no service would be created.
Backport of https://github.com/Kong/kong/pull/11158
Fixes KAG-1961
> [Backport release/3.3.x] fix(router): don't fail on route with multiple paths

- build/openresty/BUILD.openresty.bazel
Default bazel build output missing some c function debug symbol.
Before this patch:
After this Patch:
> fix(build): add missing debug symbols in the default nginx binary for bazel output

- CHANGELOG.md
- kong/db/schema/others/declarative_config.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
- spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/cache-key-vs-endpoint-key/daos.lua
- spec/fixtures/custom_plugins/kong/plugins/cache-key-vs-endpoint-key/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/cache-key-vs-endpoint-key/migrations/000_base_cache_key_vs_endpoint_key.lua
- spec/fixtures/custom_plugins/kong/plugins/cache-key-vs-endpoint-key/migrations/init.lua
- spec/fixtures/custom_plugins/kong/plugins/cache-key-vs-endpoint-key/schema.lua
DB-less mode wasn't performing proper uniqueness checks on declarative config inputs. This is especially problematic on
primary and endpoint keys. This would cause entities to be silently dropped: in the event of conflicting keys, the last one lexically present in the input file would take precedence.
For other unique fields, when using Hybrid mode you would eventually get a database error as the DB would have the uniqueness constraint set, but for pure DB-less you would get inconsistent data.
* Declarative config now performs proper uniqueness checks against its inputs: previously, it would silently drop entries with conflicting primary/endpoint keys, or accept conflicting unique fields silently.
> fix(dbless): perform uniqueness checks on unique fields

- BUILD.bazel
- build/BUILD.bazel
- build/openresty/BUILD.openresty.bazel
- kong/conf_loader/init.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx.lua
- scripts/explain_manifest/fixtures/ubuntu-18.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
- spec/fixtures/custom_nginx.template
This change makes it possible to build ngx_wasm_module as a dynamic Nginx module.
It adds the new flag `--//:wasmx_module`, which accepts `dynamic` and `static` options. Currently `dynamic` is the default value.
There is a new feature to include the `load_module` directive in `nginx.conf` when dynamic module is in use and `wasm = on`. It will search for the shared object in the path defined by the environment variable `KONG_DYNAMIC_MODULES_PATH`, the nginx build prefix and then in `/usr/local/openresty/nginx/modules` (the default installation path).
* Build scripts changed.
KAG-664
> feat(build): build wasmx as static or dynamic module

- kong/plugins/ip-restriction/handler.lua
Lazy initialization, erase the cost of `string.format` and `ngx.var` in normal cases.
> perf(plugin/ip-restriction): optimize not_allowed msg

- spec/02-integration/01-helpers/03-http_mock_spec.lua
- spec/helpers/http_mock.lua
- spec/helpers/http_mock/asserts.lua
- spec/helpers/http_mock/clients.lua
- spec/helpers/http_mock/debug_port.lua
- spec/helpers/http_mock/nginx_instance.lua
- spec/helpers/http_mock/tapping.lua
- spec/helpers/http_mock/template.lua
- spec/renderdocs.sh
Introduce tapping for testing, especially OIDC's behavior when sending requests to IDP.
bugfix: assert truthy
alias for not_all
more checks
better comment&document
N/A
> chore(http_mock): improvements & tapping

- build/openresty/patches/LuaJIT-2.1-20220411_05_arm64_sigill.patch
This fix removes the blocker to enable JIT on arm64 platform like MacOS M1/M2 chips. And the patch is under up-streaming processing. Once the LuaJIT-2.1-20220411_05_arm64_sigill.patch has been merged in upstream, we can pull the latest upstream and remove this internal maintained patch.
- [NA] The Pull Request has tests
- [NA] There's an entry in the CHANGELOG
- [NA] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
> fix(luajit): fix LuaJIT arm64 SIGILL crash.

- .github/workflows/release.yml
- build/dockerfiles/apk.Dockerfile
- build/dockerfiles/deb.Dockerfile
- build/dockerfiles/rpm.Dockerfile
- build/nfpm/repositories.bzl
- build/openresty/BUILD.openresty.bazel
- build/package/nfpm.yaml
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-18.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
The `tree` type is a new feature of nfpm that we can leverage to improve
the packaging of artifacts.
Use `tree` type in nfpm config so that the directory tree is replicated
in the destination, preserving the symlinks. With the default `file`
type, only symlinks to regular files are preserved, while symlinks to
directories are not.
> chore(build): bump nfpm to v2.31.0 + use tree nfpm type

- Makefile
`make dev` will extract `h2client` to the repo's `bin` directory. However, it will also put the `README.md` over there.
See example here:
```bash
~ $ tar -tf h2client_0.4.0_darwin_arm64.tar.gz
README.md
h2client
```
* remove h2client README.md when building kong
Fix #FTI-5230
> chore(dev): remove h2client README.md when building kong

- .github/workflows/release.yml
Just a typo fix. Found when doing CE2EE merge.
* change amazonlinux-2 2022 to 2023
Fix #FTI-5230
> chore(*): change amazonlinux-2 2022 to 2023

- kong/runloop/wasm.lua
- kong/templates/nginx_kong.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
- spec/fixtures/custom_nginx.template
This integrates Kong's DNS resolver into wasmx. See the [docs](https://github.com/Kong/ngx_wasm_module/blob/main/docs/DIRECTIVES.md#proxy_wasm_lua_resolver) for more info on how this works.
KAG-2084
> feat(wasm): integrate with kong's DNS resolver

- kong/clustering/compat/init.lua
- kong/clustering/control_plane.lua
- kong/clustering/data_plane.lua
- kong/clustering/init.lua
- kong/constants.lua
- spec/01-unit/01-db/01-schema/13-cluster_status_spec.lua
- spec/02-integration/20-wasm/06-clustering_spec.lua
This adds basic cluster compatibility checks for wasm filters. The logic is similar to how plugin checks work today. That is, if a wasm filter is present on the control plane but _not_ on the data plane, config updates will not be sent to the data plane, and the control plane will set a (new) sync status for the data plane accordingly.
This is accomplished by adding a new `filters` attribute to the basic_info payload that is sent by the data plane when initiating a connection to the control plane. The `filters` attribute is a map of strings to objects with a single `name` attribute:
```json
{
"my-filter": {
"name": "my-filter",
},
"my-other-filter": {
"name": "my-other-filter",
}
}
```
Using a map instead of an array was done for convenience of member lookup (since we would probably …
> feat(clustering): add cluster compat logic for wasm

- kong/conf_loader/init.lua
- kong/templates/nginx.lua
- spec/01-unit/04-prefix_handler_spec.lua
- spec/fixtures/custom_nginx.template
This PR introduces Wasm configuration through Kong config properties. The following new directive injections are introduced:
- Wasm global directives: applies to the `wasm {}` block, having global effect over the WebAssembly execution;
- Wasm runtime specific directives -- these apply to specific runtime blocks (`wasmtime {}`, `v8{}` and `wasmer{}`)
- Wasm HTTP directives: applies configurations to Wasm execution within the HTTP subsystem
This PR extends https://github.com/Kong/kong/pull/11000. 
KAG-1071
> feat(wasm): make wasm configurable

- kong/api/routes/filter_chains.lua
Fun fact: even though we're moving code out of the shared function into the callers, we replace four calls by three. :)
> refactor(api): issue response at caller on error getting filters

- kong/init.lua
- spec/02-integration/02-cmd/03-reload_spec.lua
- spec/fixtures/custom_nginx.template
- spec/fixtures/default_nginx.template
The cache for `kconfig.js` won't be refreshed across the reload,
which may cause requests to `kconfig.js` still respond with the
old content when the configuration is changed. Force invalidating the
cache during the worker init procedure could fix it.
> fix(admin-gui): invalidate cache for `kconfig.js` when reload

- kong/clustering/data_plane.lua
- kong/db/schema/others/declarative_config.lua
This seems to happen only during Hybrid mode CP/DP communication. A test that will be merged as part of #11218 covers this code.
> fix(dbless): accept table form in flattened foreign keys

- build/openresty/patches/LuaJIT-2.1-20220411_06_arm64_fix_HREFK.patch
The LuaJIT-2.1-20220411_05_arm64_fix_HREFK.patch is a recent merged PR in LuaJIT https://github.com/LuaJIT/LuaJIT/issues/1026, found in https://github.com/Kong/kong/pull/11191#issuecomment-1629196330. It is good to include it to get better support on ARM64.
Passes verification by the test in https://github.com/LuaJIT/LuaJIT/issues/1026.
Because this patch has not been merged in Openresty LuaJIT yet. To support ARM64 better, it is included in our own patches.
- [NA] The Pull Request has tests
- [NA] There's an entry in the CHANGELOG
- [NA] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
Fix #_[KAG-2063]_
[KAG-2063]: https://konghq.atlassian.net/browse/KAG-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> fix(luajit): Add the LuaJIT ARM64 fix for HREFK patch.

- kong/init.lua
This makes wasm's init_worker error-handling conformant with the rest of the logic in Kong.init_worker().
> fix(wasm): return early on error in init_worker

- kong/conf_loader/init.lua
- spec/01-unit/04-prefix_handler_spec.lua
This addresses some of the outstanding feedback from @thibaultcha on the [Wasm integration PR](https://github.com/Kong/kong/pull/11218).
> fix(wasm/config): correctly map inherited directives

- CHANGELOG.md
- kong/plugins/opentelemetry/schema.lua
- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
*  supports the `endpoint` parameter of the opentelemetry plugin as referenceable.
Fix KAG-2066
> feat(opentelemetry): make endpoint field referenceable

- kong/init.lua
- kong/reports.lua
- kong/templates/nginx_kong_gui_include.lua
- spec/01-unit/11-reports_spec.lua
- spec/02-integration/17-admin_gui/03-reports_spec.lua
- spec/fixtures/custom_nginx.template
- spec/fixtures/default_nginx.template
Add metrics `_admin_gui` and `km_visits` to phone home report.
`_admin_gui` will report the admin_gui_listeners status.
The counter will be increased when kong manager is visited, but will not respond to the static assets request.
This fix KAG-2127
> fix(admin-gui): add basic kong manager statistics to phone home

- .github/workflows/upgrade-tests.yml
- scripts/upgrade-tests/test-upgrade-path.sh
The `bin/kong` used in NEW_CONTAINER is not the latest version. If it gets updated, tests may fail.
> chore(ci): use the new bin/kong in NEW_CONTAINER to fix upgrade tests

- build/nfpm/repositories.bzl
- build/openresty/BUILD.openresty.bazel
This change makes it such that we are no longer unconditionally downloading every wasm runtime when building.
> chore(build): do not download wasm runtime unless requested

- build/dockerfiles/apk.Dockerfile
- build/dockerfiles/deb.Dockerfile
- build/dockerfiles/rpm.Dockerfile
Backport https://github.com/Kong/kong/pull/11176.
Vulnerability scan related.
FTI-5195
> [backport #11176] chore(build): upgrade Docker base image during build (#11176)

- build/openresty/patches/ngx_lua-0.10.21_09-crash-when-buffering-with-invalid-if-match-header.patch
- spec/02-integration/05-proxy/24-buffered_spec.lua
> fix(patches): handle if-match headers correctly

- CHANGELOG.md
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
allowd to reference vaults introduced by [#11127](https://github.com/Kong/kong/pull/11127)
[FTI-4937](https://konghq.atlassian.net/browse/FTI-4937)
[FTI-4937]: https://konghq.atlassian.net/browse/FTI-4937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(cmd): remove the restriction that some configuration fields are not

- build/openresty/patches/lua-cjson-2.1.0.10_02-handle-large-string-correctly.patch
- spec/01-unit/29-lua_cjson_large_str_spec.lua
Patch `lua-cjson` to make it can process a large string correctly.
OpenResty PR: [https://github.com/openresty/lua-cjson/pull/94](https://github.com/openresty/lua-cjson/pull/94)
[KAG-2151]
[KAG-2151]: https://konghq.atlassian.net/browse/KAG-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lua-cjson): handle the large string correctly

- .github/workflows/build.yml
- .github/workflows/release.yml
- bin/kong
- kong/constants.lua
- kong/db/schema/init.lua
- kong/pdk/vault.lua
- kong/runloop/handler.lua
- kong/runloop/plugins_iterator.lua
- kong/templates/nginx_kong.lua
- kong/templates/nginx_kong_stream.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/01-unit/04-prefix_handler_spec.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/02-integration/02-cmd/14-vault_spec.lua
- spec/02-integration/13-vaults/02-env_vault_spec.lua
- spec/fixtures/1.2_custom_nginx.template
- spec/fixtures/custom_nginx.template
- spec/fixtures/custom_plugins/kong/plugins/dummy/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/dummy/schema.lua
- spec/fixtures/custom_vaults/kong/vaults/test/init.lua
- spec/fixtures/default_nginx.template
this also fixes the following issues:
* Previously, the ttl related fields were not actually removed from the vault configuration, causing configurations not to be correctly manipulated before they were sent to older DP versions.
https://konghq.atlassian.net/browse/KAG-2061
* When a secret is deleted from a vault, eventually also evict it from caches and stop using it.
https://konghq.atlassian.net/browse/KAG-2060
* Previously, references that were nested in tables inside of a plugin configuration were never updated with fresh values from vaults.
https://konghq.atlassian.net/browse/KAG-2096
* This fixes a bug that caused global plugins not to pick up new secret values - As they are handled differently from plugins that are attached to services, routes or consumers, they did not have …
> fix(vaults): refactor vault pdk and vault ttl code

- build/nfpm/repositories.bzl
- build/openresty/BUILD.openresty.bazel
This is a backport of #11271, including 265c007e7e4dc8b81508c39a29b1211cf936d21c and 405435e6bc117511a902882da55a06f0fb32eb57
> [backport] chore(build): do not download wasm runtime unless requested

- .github/matrix-full.yml
- BUILD.bazel
- build/BUILD.bazel
- build/kong_bindings.bzl
- build/openresty/BUILD.openresty.bazel
- build/openresty/wasmx/wasmx_repositories.bzl
- scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
After much trial and error, I could not make cross-compilation work by injecting the arch via `kong_bindings.bzl`, so this was the next best/most realistic thing.
The code duplication is pretty blah. Happy to hear recs on how I can cut down on this.
> feat(build): add wasmx to arm64 build matrix

- .github/workflows/build_and_test.yml
In ce9813a7fdf57fa060a841eea59f9dee4f49a41a we updated the cache key in the `build.yml` workflow. This updates the cache key in `build_and_test.yml` to match, which fixes failures due to inconsistent cache key computation:
https://github.com/Kong/kong/actions/runs/5671235895/job/15369071875
> fix(ci): ensure cache key is consistent across workflows

- spec/02-integration/11-dbless/03-config_persistence_spec.lua
Fix two flaky tests.
- [N/A] There's an entry in the CHANGELOG
N/A
_[KAG-2158], [KAG-2077]_
[KAG-2158]: https://konghq.atlassian.net/browse/KAG-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAG-2077]: https://konghq.atlassian.net/browse/KAG-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(dbless): fix flaky test

- .github/actions/build-cache-key/action.yml
- .github/workflows/build.yml
- .github/workflows/build_and_test.yml
- .github/workflows/perf.yml
- .github/workflows/release.yml
This makes build cache key generation reusable across different workflows. The test and release workflows now use the same "recipe" for cache key generation--no more copy/paste.
> chore(ci): re-use cache key from build workflow

- build/openresty/BUILD.openresty.bazel
Before this, non-Linux users would get this error:
```
(11:16:26) INFO: Current date is 2023-07-27
(11:16:26) ERROR: /path/path/path/path/external/openresty/BUILD.bazel:346:15: configurable attribute "configure_options" in @openresty//:openresty doesn't match this configuration. Would a default condition help?
Conditions checked:
@platforms//os:linux
To see a condition's definition, run: bazel query --output=build <condition label>.
This instance of @openresty//:openresty has configuration identifier 77dabcd. To inspect its configuration, run: bazel config 77dabcd.
For more help, see https://bazel.build/docs/configurable-attributes#faq-select-choose-condition.
(11:16:26) ERROR: Analysis of target '//build:venv' failed; build aborted: 
(11:16:26) INFO: Elapsed time: 0.111s
(11:16:26) INFO: …
```
> fix(build): add default condition to platform select()

- kong/reports.lua
- kong/runloop/wasm.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
Tests are based on `spec/02-integration/10-go_plugins/01-reports_spec.lua`.
> feat(reports): add anonymous reports for Wasm filter usage

- CHANGELOG.md
add known issue about some schema fields not accepting references due to incorrectly applied field validation
[KAG-2098](https://konghq.atlassian.net/browse/KAG-2098)
[KAG-2098]: https://konghq.atlassian.net/browse/KAG-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(changelog): add 3.4.0 known issues

- kong/api/routes/plugins.lua
Partially reverts #10846
Even though we have been emitting deprecation warnings when the endpoint
was used, we didn't remove it in 3.0, and doing it now can be a surprise
breaking change for someone. In fact, someone had to update a project
which was relying on that path, that is linked in #10846
This reverts the removal and replaces the deprecation version with 4.0
instead of 3.0. This PR does not revert the changes in our tests to use
the new endpoint instead of the deprecated one.
> revert(api): remove /plugins/schema/:name

- kong/router/compat.lua
Apply the suggestion in https://github.com/Kong/kong/pull/11071#discussion_r1260509329.
KAG-2148
> style(router): rename `buffer_append` to `expression_append`

- kong/router/utils.lua
The code of function `get_upstream_uri_v0()` is too complex,
this PR tries to clean the logic by using early `return`.
KAG-2148
> refactor(router): clean the logic of `get_upstream_uri_v0()`

- kong/conf_loader/init.lua
> fix(admin-gui): make admin_gui_ssl_cert_key sensitive

- .github/labeler.yml
Include `schema-change-noteworthy` label in PRs that change `kong/enterprise_edition/redis/init.lua`.
> chore: add schema-change-noteworthy label to redis schema

- kong/router/compat.lua
In Lua `number` can not support `uint64`, `lshift(1, 60)` has potential risk,
this PR change it to cdata `uint64` to make it safer.
> style(router/compat): always use uint64 in compatible priority

- spec/02-integration/01-helpers/03-http_mock_spec.lua
- spec/helpers/http_mock.lua
- spec/helpers/http_mock/template.lua
This commits has two changes:
- Let http mock support specifying customized init_by_lua_block code
- Fix the global patched assert function behavior to keep it same as the original one.
I'm writing some tests for the EE project and it will be useful if we can specify customized init code to run some code at init phase. 
> tests(*): http mock support specifying customized init_by_lua_block code

- build/templates/venv-commons
Remove EE specific paths from `LUA_PATH`. There is no need to cherry-pick.
* Remove EE specific paths from `LUA_PATH`.
Fix #_[FTI-5274]_
[FTI-5274]: https://konghq.atlassian.net/browse/FTI-5274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(dev): remove EE specific path from LUA_PATH

- .github/matrix-full.yml
- .github/workflows/release.yml
- BUILD.bazel
- WORKSPACE
- build/cross_deps/libxcrypt/BUILD.libxcrypt.bazel
- build/openresty/BUILD.openresty.bazel
- build/platforms/distro/BUILD
- build/toolchain/BUILD
- build/toolchain/managed_toolchain.bzl
- build/toolchain/repositories.bzl
- scripts/explain_manifest/config.py
- scripts/explain_manifest/expect.py
- scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt
- scripts/explain_manifest/fixtures/el9-arm64.txt
- scripts/explain_manifest/suites.py
Enables arm64 build on rpm distros for CE.
https://github.com/Kong/kong-ee/pull/6152
* feat(build): cross compile rpm platforms
* feat(cd): release rhel9 and aws2023 arm64 artifacts
KAG-2184
Replaces #11242
> feat(cd): enable arm64 for rhel-9 and aws-2023

- kong-admin-api.yml
This updates `kong-admin-api.yml` for wasm filter chains.
I'm not sure what is/isn't supposed to go into this file, so I just tried to follow existing patterns.
---
KAG-2243
KAG-1164
> docs(admin-api): add filter chains to OpenAPI spec

- spec/02-integration/20-wasm/06-clustering_spec.lua
This adds an additional test case for CP<->DP comms to cover the case where wasm is enabled on the DP, but the DP is missing one or more filters that are configured on the CP.
> tests(wasm): test clustering behavior with missing filters

- kong/runloop/handler.lua
- spec/02-integration/05-proxy/32-query-params_spec.lua
This PR fixes the issue described in #11325 
Replace query args handling code introduced in [this commit](https://github.com/Kong/kong/pull/7743/commits/9ed1547de5e0657f220c2659f8690f3dcf478041) to what it was prior to it.
Fix #11325
> fix(balancer): query args not forwarded bug

- kong/pdk/request.lua
The documentation for the `kong.request.get_raw_body` function [says that the function will return `nil` + an error message](https://github.com/Kong/kong/blob/65de2c30791538b043e352a7785c6ad37aa3e821/kong/pdk/request.lua#L711-L713) if the body doesn't fit into the NGINX temporary buffer, but this case is not reflected in the Lua doc `treturn` tags. I've completed the description if the first `treturn` tag and added a second one explaining the behavior previously described.
* Compete the description of the first return value showing that it can be `nil` in the case that the body doesn't fit into the NGINX temporary buffer.
* Add missing second return value for the error emitted when the body didn't fit into the NGINX temporary buffer.
> docs(pdk): clarify kong.request.get_raw_body doc

- CHANGELOG.md
- kong/plugins/acme/client.lua
In the last change we added string concatenation the wrong way leading to empty logs. This addresses the problem
> fix(acme): error concatenation

- CHANGELOG.md
- kong/clustering/compat/removed_fields.lua
- kong/plugins/proxy-cache/handler.lua
- kong/plugins/proxy-cache/schema.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
- spec/03-plugins/31-proxy-cache/03-api_spec.lua
- spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua
Update of #7829 
Adding Miss/Hit, Age and cache key to answer shouldn't be the default behavior.
Add option to remove the proxy cache headers from the response.
If the kong debug is set keep the headers
The following headers:
- `X-Cache-Status`
- `X-Cache-Key`
- `Age`
can be now be removed from the answer via the `response_headers` option,
for example to remove all:
```
config = {
[...]
response_headers = {
age = false,
["X-Cache-Status"] = false,
["X-Cache-Key"]  = false
}
```
Default behavior to have all the header set is kept for retro compatibility reason.
Refactor test to remove duplicated lines and use get, post and delete helpers instead of send
> feat(proxy): Allow to remove the proxy cache headers

- kong/db/declarative/import.lua
- kong/init.lua
- kong/runloop/events.lua
When dp received the config data from cp, it will load the data into lmdb cache, then invoke "reconfigure".
The "reconfigure" action will happen in both http and stream subsystem, but the code scatter in different lua modules,
This PR move the logic into one place.
* use `string.buffer` to replace `lua-cjson`
* normalize `ngx.config.prefix()` path
* move logic into `runloop/events.lua`
* remove `kong.log.crit`, using `ngx.log`
> refactor(runloop/events): gather stream config logic

- COPYRIGHT
- scripts/update-copyright
We found some issues on the update-copyright script while releasing 3.4, this is forward-porting those changes to master, as well as the updated copyright info.
> chore(*): update copyright info and script

- kong/runloop/plugin_servers/init.lua
- kong/runloop/plugin_servers/pb_rpc.lua
Ensure that if a pluginserver is restarted all workers invalidate their running instances.
Fixes FTI-5238
This is a cherry-pick from EE - https://github.com/Kong/kong-ee/pull/6207.
> fix(pluginservers): workers invalidate instances

- kong/router/atc.lua
- kong/router/utils.lua
This reverts commit e8173ca30b902202e289e93ab34cf40a907fd3d6.
See: https://github.com/Kong/kong/pull/11273#issuecomment-1670920688
> Revert "perf(router): iterate routes with for loop  (#11111)"

- kong/router/atc.lua
- kong/router/traditional.lua
- kong/router/utils.lua
- spec/01-unit/08-router_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
This PR will replace #11072.
I will add change log entry after 3.4 release.
KAG-2050
KAG-2289
* add new schema field `http.queries.*`
* add `queries_key` for cache
* use param `lua_max_uri_args`
* check unknown field in `select()`
> feat(router): support http queries in expression

- CHANGELOG.md
- kong/runloop/plugin_servers/init.lua
- kong/runloop/plugin_servers/mp_rpc.lua
- kong/runloop/plugin_servers/pb_rpc.lua
- kong/runloop/plugin_servers/process.lua
We used to check if the plugin server socket is ready by trying to connect, which will generate a lot of critical messages which cannot be suppressed due to OpenResty's limitation. As the feature is not really helpful, we decided to revert it.
Revert "fix(pluginserver): error if req come before ready (#9507)"
This reverts commit e7b6963f8c01c11232828d2709de08743708bf56.
Fix KAG-2136
Fix #11084
Fix kong/kong-js-pdk#308
> Fix(language): Critical messages during startup

- CHANGELOG.md
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
before being inserted into lua_ssl_trusted_certificate
Fix https://konghq.atlassian.net/browse/FTI-4883
> fix(conf_loader): cluster_cert/cluster_ca_cert should be base64 decoded

- CHANGELOG.md
- kong/plugins/oauth2/access.lua
- spec/03-plugins/25-oauth2/03-access_spec.lua
With `global_credential=true`, `access_token` can be shared across services, as well as `refresh_token` currently. This means that a `refresh_token` belonging to a service can be used to refresh tokens belonging to another service, which is consider as a bug. In this PR, the scope is taken into account as a new creteria of the request validation. Scopes associated with a token provided in the request will be compared with those configured in the Oauth2 instance hit by that request.
FTI-5173
> fix(oauth2): fix a bug that refresh_token could be shared across instances

- build/luarocks/BUILD.luarocks.bazel
Latest `brew` requires `$HOME` to be set.
* Fix `luarocks` build for macos.
> fix(build): set $HOME for luarocks build in macos

- kong/runloop/balancer/upstreams.lua
When starting e.g. empty Kong this got logged:
```
2023/08/11 08:49:27 [debug] 40426#0: *5 [lua] upstreams.lua:108: empty upstreams dict. Could it be an uncatched database error?
```
It is a way too alarmistic. The most common case for upstreams dict to be empty is that people are not using balancer or that there is just no upstreams specified. E.g. only using routes and services.
> chore(balancer): use less dramatic debug message

- CHANGELOG.md
- bin/busted
- kong/cmd/utils/migrations.lua
- kong/db/strategies/postgres/connector.lua
- spec/02-integration/02-cmd/10-migrations_spec.lua
- spec/02-integration/03-db/01-db_spec.lua
- spec/02-integration/03-db/04-db_cluster_mutex_spec.lua
- spec/03-plugins/28-grpc-gateway/01-proxy_spec.lua
- spec/require.lua
This is the follow-up PR of https://github.com/Kong/kong/pull/11127
Changing the socket type from luasocket to openresty cosocket causes some test fail weirdly. After investigating, it's mainly because the cosocket support yield and setkeepalive. See the comments in tests.
https://konghq.atlassian.net/browse/FTI-4937
> fix(*): drop luasocket in cli

- .github/workflows/release.yml
Forks doesn't have access to secrets, thus docker images won't upload then verify image can't run.
> chore(cd): skip verify image test on fork

- spec/03-plugins/25-oauth2/03-access_spec.lua
In this PR, a flaky test which is caused by a conflict between routes with the same `host` field is fixed by change one of them to a local particular name
> test(oauth2): fix flaky test

- kong/tools/utils.lua
Previously the sleeping was skipped with `utils.yield` only on phases `init` and `init_worker`, and on CLI, but there are a lot more phases in Nginx where the ngx.sleep is not allowed. This changes the `utils.yield` to skip `ngx.sleep`ing on such phases. I checked that there was as many phases where it was allowed as there was phases where it was disallowed, so I ended up with a list of where it is allowed as that is easier to update by just looking: https://github.com/openresty/lua-nginx-module#ngxsleep (+ the preread phase).
> fix(utils): yield to sleep only when the ngx.sleep is available

- CHANGELOG.md
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua
- Stop retrying in dns/client.lua, let the resolver handle this.  This change also makes it possible to disable retries, which previously was not possible
- Be more faithful to the timeouts set by the user.  Previously, the timeout configured was used only for the ultimate request sent to the DNS server, but asynchronous requests allowed longer timeouts which was not transparent.
- When the DNS server fails, stop trying other query types.  Previously, the behavior was such that after an (intermediate) failure to query for one record type (say "SRV"), the client would try the next record type (say "A") and succeed with that.  It would then return the contents of the "A" record even if the "SRV" record pointed to a different address.
- Change domain names used for testing the DNS client …
> fix(dns): fix retry and timeout handling

- CHANGELOG.md
The changes on this diff were merged after 3.4 Code Freeze and where
erroneously put in the 3.4 section. This change moves them to the
correct "Unreleased" version.
This check was done by comparing the changelog present in master with
the one present in branch next/3.4.x, and then individually checking
that the fixes where not present when differences between the changelogs
where found.
> docs(changelog): move unreleased changes to Unreleased

- scripts/build-wasm-test-filters.sh
The output of this script was pretty minimal because the filter build path does not need to be known to run the test suite. This additional output is helpful for local development, as users will now see a message printed to stdout that looks something like this:
```
Success! Test filters are now available at:
/home/michaelm/git/kong/kong/spec/fixtures/proxy_wasm_filters/build
For local development, set KONG_WASM_FILTERS_PATH accordingly:
export KONG_WASM_FILTERS_PATH="/home/michaelm/git/kong/kong/spec/fixtures/proxy_wasm_filters/build"
If testing with docker, make sure to mount the full (non-symlink) path
inside your container:
docker run \
-e KONG_WASM_FILTERS_PATH=/filters \
-v "$(realpath "/home/michaelm/git/kong/kong/spec/fixtures/proxy_wasm_filters/build"):/filters" \
...
```
> chore(scripts): print wasm test filter path to stdout

- scripts/upgrade-tests/test-upgrade-path.sh
Tries to fix upgrade test on master. The upgrade test is using `kong/kong:ubuntu` image tag which currently points at `3.4.0-ubuntu`. Change it to use `master-ubuntu` so that it can use the latest headers/shared libraries in the latest image based on master's commit.
> chore(ci): upgrade test use master-ubuntu tag

- CHANGELOG.md
- kong/plugins/aws-lambda/request-util.lua
- spec/03-plugins/27-aws-lambda/08-sam-integration_spec.lua
- spec/fixtures/aws-lambda.lua
- spec/fixtures/sam-app/hello_world/app.py
This PR adds better type handling and error handling for proxy integration mode. One change comes from #11350 is that if lambda function's response body is `application/json` then it will be automatically decoded by AWS lib. We handle this situation better and make sure it gets tested in our integration test.
* Fix the problem that lambda cannot extract a json encoded proxy integration response
> fix(aws-lambda): add better type and error handling on proxy integration mode

- spec/03-plugins/03-http-log/01-log_spec.lua
Let's clear the log before the test.
* clear the log before the test.
* refactor to fail with more clear messages
**Please remember to remove the issue reference from the commit message. It's added by mistake.**
> chore(test): address flakiness of grpc logs test

- CHANGELOG.md
- kong-3.5.0-0.rockspec
Bumps lua-resty-aws from 1.3.0 to 1.3.1
> 1.3.1 (17-Aug-2023)
> fix: fix v4 signing request should correctly canonicalized query table as well https://github.com/Kong/lua-resty-aws/pull/76
* Bump lua-resty-aws version from 1.3.0 to 1.3.1
> chore(deps): bump lua-resty-aws to 1.3.1

- CHANGELOG.md
- kong-3.5.0-0.rockspec
- fix(dshm/memcached): add a missing return statement as otherwise pool parameters are not respected
(also corrects the OpenSSL bump on changelog)
> chore(deps): bump lua-resty-session from 4.0.4 to 4.0.5

- CHANGELOG.md
- kong/cache/warmup.lua
- kong/plugins/acl/groups.lua
- spec/03-plugins/18-acl/02-access_spec.lua
kong acl plugin will need to get all consumer groups by customer id (because consumer group and acl plugin config some complex connection), these entities can not be warmed up by Kong, The "warm up" mechanism mainly ensures that all entities are loaded into the cache and enables more precise SQL queries (based on cache key definitions) https://github.com/Kong/kong/blob/master/kong/plugins/acl/daos.lua#L8. However, for scenarios where it is necessary to iterate through all entities under a consumer ID, caching is not possible. https://github.com/Kong/kong/blob/master/kong/plugins/acl/groups.lua#L45
So this PR tries a patch warmup mechanism to support `acls` entities config.
FTI-5275
> fix(cache): make acl entities group cache warmup

- CHANGELOG.md
- build/package/nfpm.yaml
- kong-3.5.0-0.rockspec
zlib1g-dev
Requires https://github.com/Kong/lua-ffi-zlib/pull/1
Fix KAG-2241
> chore(deps): bump lua-ffi-zlib to 0.6 and remove zlib dev packages from artifact dependency

- build/build_system.bzl
- build/luarocks/BUILD.bazel
- build/luarocks/BUILD.luarocks.bazel
- build/luarocks/luarocks_repositories.bzl
- build/luarocks/templates/luarocks_exec.sh
- build/luarocks/templates/luarocks_make.sh
- build/luarocks/templates/luarocks_target.sh
- build/repositories.bzl
This PR refactors the luarocks build targets by using the improved `kong_template_file`  and `kong_template_genrule` rules so that we don't need to write shell scripts in multipl escapes and complex templates.
- [na] There's an entry in `CHANGELOG.md`
KAG-2351
EE sister PR https://github.com/Kong/kong-ee/pull/6294
KAG-1387
> refactor(build): use kong_template_* rule for luarocks targets

- CHANGELOG/unreleased/kong/11424.yaml
- kong/pdk/response.lua
- t/01-pdk/08-response/14-get_raw_body.t
ngx.ctx.KONG_BODY_BUFFER is not reset while reading the EOF chunk. When `kong.response.get_raw_body()` is called multiple times, the response body gets repeated.
FTI-5296
> fix(PDK): fix response body repeated when kong.response.get_raw_body() called multiple times

- kong/plugins/proxy-cache/schema.lua
The `description` field was missing from #10445, causing the reference documentation to be incomplete.
> fix(doc): add missing description to proxy-cache schema field

- CHANGELOG.md
- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
When defining a very special edge case configuration having max_batch_size=max_entries, the queue can fail with an assertion error when removing the frontmost element. This happens especially when the callback repeatedly fails (eg. an unavailable backend system receiving data).
What happens:
1. we add max_batch_size elements, all of which "post" resources
2. the batch queue consumes all of those resources in `process_once` by `wait()`ing for them, but gets stuck processing/sending the batch
3. as `process_once` is stuck until `max_retry_time` passed, the function does not run `delete_frontmost_entry()` and thus actually moves the `front` reference
4. when enqueuing the next item, it tries to drop the oldest entry, but triggers the assertion in queue.lua as no resources are left
This …
> fix(queue): add failing test for edge case max_batch_size=max_entries

- CHANGELOG.md
- kong/db/dao/tags.lua
- spec/02-integration/04-admin_api/14-tags_spec.lua
> fix(admin): fix admin api /tags/:tag return empty object instead of an empty array

- CHANGELOG.md
- kong/runloop/handler.lua
- spec/02-integration/14-tracing/01-instrumentations_spec.lua
This PR invokes instrumentation when kong requests are not proxied to the upstream, so that the
relevant span attributes are set on all requests.
* Fix: record `http.status_code` even when request is not proxied.
* Test case.
Fixes #11141
Closes #11152 
KAG-2346
> fix(tracing): record http.status_code when request is not proxied

- CHANGELOG.md
Move entries from `Deprecations` to `Additions` or `Fixes`,
and remove some empty sections.
These change log entries belongs to 3.4, should we back port this PR to 3.4 branch? 
> docs(changelog): move some entries to correct place

- CHANGELOG.md
> docs(changelog): add changelog entries for some PRs

- Makefile
Bazelisk v1.18.0 contains some bug fixes and internal cleanups. Most notably, it uses consistent Bazel paths to avoid spurious rebuilds when downloading the same Bazel binary from a different mirror
> chore(deps): bump bazelisk from 1.17.0 to 1.18.0

- spec/02-integration/04-admin_api/08-targets_routes_spec.lua
- spec/02-integration/06-invalidations/01-cluster_events_spec.lua
Generally, if the API definition does not require data ordering, we should not make assumptions about the ordering. Otherwise, the test could be flaky.
We should always update the time before a time-sensitive test.
sleep implicitly updates time, but we need an accurate start time before sleep.
Thanks to @ADD-SP's help.
Fix KAG-2417
> chore(test): fix flaky tests

- CHANGELOG.md
- kong/init.lua
- spec/02-integration/05-proxy/07-upstream_timeouts_spec.lua
When kong uses `kong_buffered_http` and upstream timeout, the return status code needs to return 504 (which return by `ngx.location.capture`), not 502. 
FTI-5320
> fix(response): fix response status code is not real upstream status when using kong.response function

- kong.conf.default
It's pretty wordy because there's a lot to explain. I'm also not sure what it will look like when rendered for docs.konghq.com, so if anyone has pointers on how to preview the end result, let me know.
> docs(kong.conf): add section for wasm nginx.conf directives

- CHANGELOG.md
- kong.conf.default
- kong/runloop/wasm.lua
Backport of #11407
This was added during local development to work around a bug but is no longer desired and disallows setting the isolation level via kong.conf.
> [Backport release/3.4.x] fix(wasm): remove hardcoded isolation level

- kong/tools/queue.lua
The previous fix (#11376) to enable batching during shutdown failed to check the shutdown flag while waiting for more items to batch.  If the coalescing delay was large enough, this could cause the last batch to be lost.
This bug caused the test spec/02-integration/16-queues/01-shutdown_spec.lua to sporadically fail.  The fix removes the flakiness.
KAG-2449
> fix(queues): shutdown flag needs to be checked while waiting

- build/openresty/BUILD.openresty.bazel
Re-enables `ngx_devel_kit_module`.
This was originally disabled in:
https://github.com/Kong/kong/pull/10315
NDK is needed for `set_by_lua`, which is the reason we re-enable it, even when Kong doesn't use it, and can only be used through Nginx configuration injections or custom Kong Nginx templates.
Fix #11455
[KAG-2458](https://konghq.atlassian.net/browse/KAG-2458)
[KAG-2458]: https://konghq.atlassian.net/browse/KAG-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(dist): re-enable ngx_devel_kit_module

- kong/router/atc.lua
Categorize atc fields to `fields` `header_fields` `query_fields`, 
then we can simplify the logic in `select()`.
> refactor(router): categorize router fields to simplify logic

- build/kong_bindings.bzl
EE https://github.com/Kong/kong-ee/pull/6345
> feat(build): check username and python sanity

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build_and_test.yml
- .github/workflows/changelog.yaml
- CHANGELOG/Makefile
- CHANGELOG/README.md
- CHANGELOG/changelog
- CHANGELOG/changelog-md-template.lua
- CHANGELOG/changelog-template.yaml
- CHANGELOG/schema.json
Maintaining changelogs in a single markdown file in the repo is one of the easy ways to maintain and also keep consistency. Since Kong has multiple release versions, sometimes a bugfix needs to be backported to all the supported versions after it gets merged to the master branch. The backport bot is currently broken because of the git conflict. 
I'm Introducing a new way to maintain Kong's changelog, which makes the changelog item become an individual file. The idea is, you don't get the conflict if you don't edit the same file.
Implementation details:
- `CHANGELOG/changelog` is a Lua script that currently provides `preview`, and `release` commands. It only requires Penlight and lyaml libraries.
- Using the template engine(provided by Penglight) which is similar to how Kong renders the …
> chore(changelog): new way to maintain the changelog

- .github/workflows/release-and-tests-fail-bot.yml
Github doesn't treat the author of commit as actor to scheduled workflow run, so sending slack message doesn't make sense.
> chore(cd): skip send slack message for daily build failure

- kong.conf.default
The description of ssl_ciphers was confusing if you were using DHE ciphers because you'd also have to use another parameter. This fixes the description.
This is a cherry-pick of Kong/kong-ee#6035
* `kong.conf.default` update
> docs(kong.conf.default): ssl_ciphers description (#6035)

- scripts/dependency_services/common.sh
macOS ships bash 3.x by default
> fix(dependency_services): support bash 3.x

- .github/workflows/changelog.yaml
Summary:
Add path filter for changelog workflow to skip the workflow when PR does not touch specific paths.
> chore(ci): add filter for changelog workflow

- kong/db/declarative/import.lua
Early return for `load_into_cache()`
> style(db/declarative): simplify the logic of `load_into_cache`

- README.md
This change includes Kong's open-source management Web UI (Kong Manager) in the getting started section. Minor rewording to make the text concise and easier to understand.
> docs(readme) include Kong manager and decK

- CHANGELOG/unreleased/kong/11468.yaml
- kong/plugins/opentelemetry/handler.lua
- kong/runloop/handler.lua
- kong/tracing/instrumentation.lua
- kong/tracing/propagation.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
Fix an issue where the parent span was set incorrectly when the balancer instrumentation was disabled (the parent span ID was set to a temporary balancer span that was never reported).
https://konghq.atlassian.net/browse/KAG-2281
closes https://github.com/Kong/kong/issues/11294
> fix(tracing/propagation): set parent span correctly

- CHANGELOG.md
- CHANGELOG/unreleased/kong/11464.yaml
- kong/db/dao/init.lua
- kong/db/declarative/export.lua
- kong/db/schema/others/declarative_config.lua
- kong/db/strategies/off/init.lua
- kong/db/strategies/postgres/init.lua
- spec/03-plugins/09-key-auth/04-hybrid_mode_spec.lua
* Previously, in DB-less and Hybrid mode, the ttl/updated_at fields were not copied from the original entities to the flattened entities. As a result, the entities were loaded without the TTL field. 
* Additionally, for loading the TTL field, the "off" DB strategy (lmdb) did not support automatic calculation of the remaining expiration time. 
* copy the ttl field from original entities to flatten entities
* transform the absolute ttl value to relative within the new function each_for_export(), then declarative config exports its configuration using `for ... in each_for_export` instead of  `for ... in each()`
* add DAO:each_for_export() based on DAO:each() to export the entity with the absolute ttl
* add the `options.export` field to enable this feature in pg:page()
* add extra pg SQL …
> fix(db/declarative): fix TTL not working in DB-less and Hybrid mode

- DEVELOPER.md
Add a section for setting up hybrid mode dev environment.
Add a step for setting `GITHUB_TOKEN` to the section of `Build and Install from source`.
[KAG-2027](https://konghq.atlassian.net/browse/KAG-2027)
[KAG-2027]: https://konghq.atlassian.net/browse/KAG-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(DEVELOPER.md): add how to set up hybrid mode

- CHANGELOG/unreleased/kong/11518.yaml
- kong-3.5.0-0.rockspec
bugfixes:
- **pkey:** clear error stack when verification fails ([#121](https://github.com/fffonion/lua-resty-openssl/issues/121)) [6e58b28](https://github.com/fffonion/lua-resty-openssl/commit/6e58b28c3d42560631e0c8351befa1434b6fc542)
- **ssl:** support ngx_lua 10025 [abaa66e](https://github.com/fffonion/lua-resty-openssl/commit/abaa66ee07ce734580fd29ec6032157c998f6346)
Fix [FTI-5324](https://konghq.atlassian.net/browse/FTI-5324)
[FTI-5324]: https://konghq.atlassian.net/browse/FTI-5324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): bump resty.openssl from 0.8.23 to 0.8.25

- spec/02-integration/06-invalidations/01-cluster_events_spec.lua
- spec/03-plugins/25-oauth2/04-invalidations_spec.lua
This PR contains 2 flaky test fixes. **PLEASE DO NOT SQUASH WHEN MERGING.**
Those flaky tests are found when trying to introduce FIPS tests.
[chore(tests): update time for time sensitive tests](https://github.com/Kong/kong/commit/fd345517f7c43dcf54b83735839118016f460fbd)
[chore(tests): wait_until for flaky test](https://github.com/Kong/kong/commit/a1c4f781a72dd41d3642cb58728798b9ad7158d8)
> tests(*): yet another compilation of flakiness fixes

- CHANGELOG/unreleased/kong/luajit_ldp_stp_fusion.yaml
- build/openresty/patches/LuaJIT-2.1-20230410_05_ldp_stp_fusion.patch
upstream
https://github.com/LuaJIT/LuaJIT/commit/b8c6ccd50c61b7a2df5123ddc5a85ac7d089542b
> chore(patches): apply the LuaJIT ARM64 LDP/STP fusion fix from LuaJIT

- .github/actions/build-cache-key/action.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
This updates the `build-cache-key` action to accept additional paths to use when generating the cache key. The impetus for this change is to allow removal of `kong/**` from the default cache key so that it can be used selectively.
See also: https://github.com/Kong/kong/pull/11299#discussion_r1278828078
cc @fffonion lemme know what you think of this approach!
> chore(ci): support additional paths in the build cache key

- kong/db/declarative/import.lua
- spec/01-unit/01-db/10-declarative_spec.lua
Since we have implemented the sha256 feature in lua-resty-lmdb(https://github.com/Kong/lua-resty-lmdb/pull/27),
should we remove this call in Kong?
> refactor(db/declarative): remove sha256 in `unique_field_key`

- kong/runloop/balancer/round_robin.lua
Did some style clean for the code of round-robin algo.
> refactor(runloop/balancer): clean the code of round robin algo

- CHANGELOG/unreleased/kong/11553.yaml
- kong-3.5.0-0.rockspec
* Fix: place EAI_OVERFLOW inside macro, unbreak build on <10.7 (Sergey Fedorov)
* Fix: Expand workaround for zero errno to OpenSSL 3.0.x (Kim Alvefur)
* Fix: reset block timeout at send or receive (MartinDahlberg)
> chore(deps): bump luasec from 1.3.1 to 1.3.2

- CHANGELOG/unreleased/kong/11578.yaml
- build/BUILD.bazel
> luarocks-admin and lapis are removed from the docker images by the bazel build system, but they are needed by the container smoke tests, so they need to be brought back.
* [Restore lapis & luarocks-admin bins]
Fix #_[KAG-911]_
[KAG-911]: https://konghq.atlassian.net/browse/KAG-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KAG-911] fix(bazel): don't rm lapis/luarocks-admin bins

- CHANGELOG/unreleased/kong/11538.yaml
- kong/router/expressions.lua
- spec/01-unit/08-router_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
KAG-2561
See: https://github.com/Kong/kubernetes-ingress-controller/pull/4574#issuecomment-1695701737
~~Blocked by #11550~~
> fix(router): fix tls_passthrough in expression flavor

- CHANGELOG/unreleased/kong/11480.yaml
- kong/db/strategies/postgres/connector.lua
- spec/02-integration/03-db/01-db_spec.lua
Currently, we do set/keep socket keepalive after every Postgres SQL query, based on keepalive timeout configured or `lua_socket_keepalive_timeout`(default 60s). 
This could go wrong under some cases, when a query encounters read timeout when trying to receive data from a database with high load, the query ends on Kong's side but the query result may be sent back after timeout happens, and the result data will be lingering inside the socket buffer, and the socket itself get reused for subsequent query, then the subsequent query might get the uncorrect result from the previous query. 
The PR checks the query result's err string, and if `timeout` happens, it'll try to close the socket actively so that the subsequent query will establish new clean ones.
~~- [ ] There is a user-facing docs PR …
> fix(postgres): close socket actively when timeout happens during query

- CHANGELOG/unreleased/kong/11480.yaml
- kong/db/strategies/postgres/connector.lua
- spec/02-integration/03-db/01-db_spec.lua
Backport https://github.com/Kong/kong/commit/d2da4dbb372db3687f1dfae33ba422c384b61024 from https://github.com/Kong/kong/pull/11480.
> [Backport release/2.8.x] fix(postgres): close socket actively when timeout happens during query

- kong/pdk/vault.lua
Backports the fix from EE:
https://github.com/Kong/kong-ee/pull/6444/commits/50eaa56a6f4f7c9e4a8c8336579f005b462a1b46
Fixes issue where Vault references may be dropped from rotation in case a too small value was configured in `config.resurrect_ttl` OR `config.neg_ttl`.
This is fixed by setting a constant value of:
```
local SECRETS_CACHE_MIN_TTL = ROTATION_INTERVAL * 2
```
(the rotation interval is by default 60 seconds).
> [backport] fix(vault): vault references may be dropped from rotation

- kong/plugins/jwt/jwt_parser.lua
`lua-resty-core` provides two functions `base64.encode_base64url()` and `base64.decode_base64url()`,
Which have the same effect as our Lua functions.
* use `base64.encode_base64url` and `base64.decode_base64url`
* optimize table insert
> refactor(plugins/jwt): use encode_base64url in resty.core

- kong/plugins/grpc-web/deco.lua
- kong/plugins/grpc-web/handler.lua
`string.buffer` is better than `table.concat`, we have already done the same thing in other place.
* use `string.buffer` to replace `table.concat`
* use localized `ngx.var` and `ngx.encode_base64`
> refactor(plugins/grpc-web): use string buffer to concat strings

- CHANGELOG/unreleased/kong/11502.yaml
- kong-3.5.0-0.rockspec
- kong/runloop/balancer/init.lua
- kong/runloop/handler.lua
- kong/runloop/upstream_ssl.lua
- kong/templates/nginx_kong.lua
- spec/02-integration/05-proxy/18-upstream_tls_spec.lua
If a plugin has response() handler, in `Kong.response` it will emits a subrequest by calling `ngx.location.capture("/kong_buffered_http", options)`. `ngx.location.capture` will create a new nginx request, so the overwritten ssl info (client key & cert etc.) get lost in the new nginx request.
To fix this, those ssl info need to be re-set in the new request context. We choose to do this in the early rewrite phase of the new request before `Kong.balancer()` getting executed.
The normal flow is as below:
```
Kong.access.before            Kong.access.after             Kong.balancer(first try)    Kong.balancer(retry)
v                             v                                     |                 v
balancer_prepare              balancer.execute(try_count=0)                | …
```
> fix(runloop): upstream ssl failure when plugins use response handler

- build/openresty/repositories.bzl
- [na] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
https://github.com/Kong/kong-ee/pull/6534
> chore(build): add openresty tarball mirror

- DEVELOPER.md
When setting up Kong `DEVELOPER.md` points to Github Documentation to generate a Github Access Token in order to download some essential repos. However it does not explicitly state what permissions the token should grant.
* `DEVELOPER.md`: Mention that no additional permission are needed when setting up Kong 
N/A
> docs(DEVELOPER): clarify permission for Github Access Token

- kong/init.lua
- kong/tools/utils.lua
We have introduced a wrapper function `get_updated_now_ms()` in #10355,
so I think that we can do the same thing for `now()` and `start_time()`.
> refactor(core): wrapper of now_ms and start_time_ms

- spec/02-integration/16-queues/01-shutdown_spec.lua
konghq.com:80 no longer responds with 301 to POST requests, but as we're not interested in the specific status code anyway, remove it from the expected string.  We only need to make sure that an attempt was made to contact the log server (konghq.com).
(EE PR: https://github.com/Kong/kong-ee/pull/6579)
KAG-2612
> fix(test): don't expect specific status code in queue shutdown test

- .github/workflows/label-community-pr.yml
When a pull request against the Kong/kong repository is opened, it should be automatically labeled with `author/community` if the account opening the PR is not a member of the Kong organization.
But because of the author's permissions, it is not allowed to add labels to the PR. So try to use `schedule` instead of `pull_request` to implement this requirement.
KAG-2562
> chore(ci): automatically label community PRs with author/community

- CHANGELOG/unreleased/kong/11613.yaml
- kong-3.5.0-0.rockspec
- fix: lazily initialize structures to avoid c-boundary errors on require [87](https://github.com/Kong/lua-resty-aws/pull/87)
- fix: remove more module-level uses of config.global [83](https://github.com/Kong/lua-resty-aws/pull/83)
- fix: don't invoke region detection code on the module toplevel and advise against trying to. [81](https://github.com/Kong/lua-resty-aws/pull/81)
> chore(deps): bump resty.aws from 1.3.2 to 1.3.5

- kong/db/dao/plugins.lua
- kong/init.lua
- kong/plugins/aws-lambda/handler.lua
Lazily initializes AWS library on a first use, to remove startup delay caused by AWS metadata discovery.
^ this PR does not need any of those, this is on top of unreleased feature.
> fix(aws-lambda): lazily initialize aws library

- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- COMMUNITY_PLEDGE.md
- CONTRIBUTING.md
- README.md
- add community pledge
- update support channel information and social links
> chore(docs): update contributor wording and support channel info

- CHANGELOG/unreleased/kong/10570.yaml
- kong/plugins/response-ratelimiting/policies/init.lua
Adds support for secret rotation for redis credentials in response-ratelimiting plugin.
> feat(response-ratelimiting): add support for secret rotation with redis connection

- kong/plugins/grpc-gateway/deco.lua
Same as #11562, use `string.buffer` to replace `table.concat`
> refactor(plugins/grpc-gateway): use string buffer to concat strings

- kong/runloop/upstream_ssl.lua
Only some style clean for #11502, applying early return.
> style(runloop): style clean for upstream_ssl

- .github/workflows/label-community-pr.yml
This PR adjusts the token being use for community PR identification.
- [na] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
Fix #_[KAG-2562]_
[KAG-2562]: https://konghq.atlassian.net/browse/KAG-2562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(gha): non-default token for PRs ID

- CHANGELOG/unreleased/kong/11566.yaml
Reword changelog of #11566 to be more user-facing
> docs(changelog): reword changelog message

- spec/helpers.lua
Filter out debug log lines as they are not usually useful for 500 errors.
- [na] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
> chore(helpers): do not display debug log when test errors with status code 500

- build/openresty/BUILD.openresty.bazel
- scripts/explain_manifest/config.py
- scripts/explain_manifest/fixtures/alpine-amd64.txt
- scripts/explain_manifest/fixtures/alpine-arm64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt
- scripts/explain_manifest/fixtures/debian-10-amd64.txt
- scripts/explain_manifest/fixtures/debian-11-amd64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/el8-amd64.txt
- scripts/explain_manifest/fixtures/el9-amd64.txt
- scripts/explain_manifest/fixtures/el9-arm64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
- scripts/explain_manifest/suites.py
Fix an issue that resty.signal fails to find librestysignal.so and fails to parse certain LUA_CPATH.
- [na] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
fix(build):add openresty/lualib into rpath
From https://github.com/Kong/kong/pull/11382
> fix(build):add openresty/lualib into rpath

- kong/concurrency.lua
- kong/tools/utils.lua
- spec/02-integration/13-vaults/03-mock_spec.lua
Vault's `try` function now uses `with_coroutine_mutex` concurrency control, but it may be triggered in phases(for example, init phase during config dereference)that does not support `semaphore:wait`, so problem occurs.
> fix(vault): vault try should avoid using semaphore in non-yieldable phases

- spec/02-integration/16-queues/01-shutdown_spec.lua
Instead of testing whether a certain server responded, test whether the provided name could not be resolved by the DNS client.  This is closer to what the test actually tries to verify anyway
KAG-2615
> fix(test): change test to not depend on server to be present

- scripts/upgrade-tests/test-upgrade-path.sh
It seems that `docker pull` started to print to stdout in a recent base image upgrade.  This PR redirects its stdout to `/dev/null` so that the migration tests pass again.
> fix(upgrade-tests): redirect stdout of docker pull in upgrade tests

- CHANGELOG/unreleased/kong/11639.yaml
- build/openresty/patches/LuaJIT-2.1-20230410_07_ldp_stp_unaligned.patch
- A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
> chore(patches): apply the LuaJIT ARM64 LDP/STP fix for unaligned accesses.

- CHANGELOG/unreleased/kong/11638.yaml
- build/openresty/patches/LuaJIT-2.1-20230410_06_arm64_reg_alloc_fix.patch
-  A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
Fix #_[KAG-2473]_
[KAG-2473]: https://konghq.atlassian.net/browse/KAG-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(patches): fix incorrect LuaJIT register allocation for IR_*LOAD on ARM64

- CHANGELOG/unreleased/kong/11532.yaml
- kong-3.5.0-0.rockspec
- kong/clustering/compat/removed_fields.lua
- kong/plugins/acme/schema.lua
- spec/03-plugins/29-acme/05-redis_storage_spec.lua
SRE has started seeing entries in the Redis slowlog related to retrieving keys for `kong_acme:renew_config`.  lua-resty-acme was recently changed to use Redis `scan` instead of `keys` for performance reasons. See the lua-resty-acme PR for more details https://github.com/fffonion/lua-resty-acme/pull/106.
This PR exposes a new configuration field for Redis storage that controls how many keys are returned in a `scan` call and bumps lua-resty-acme to 0.12.0.
@fffonion
> feat(acme): add scan_count to redis storage schema

- scripts/upgrade-tests/test-upgrade-path.sh
This seems to have creeped into all branches and is needed for the upgrade tests to pass.
> fix(upgrade-tests): redirect stdout of docker pull in upgrade tests (#11643)

- spec/02-integration/03-db/18-keys_spec.lua
- spec/02-integration/03-db/19-key-sets_spec.lua
- spec/02-integration/04-admin_api/21-admin-api-keys_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/dummy/schema.lua
Summary
Removes license headers as they must not be in kong-oss.
Closes: https://github.com/Kong/kong/issues/11661
Fix: https://konghq.atlassian.net/browse/KAG-2666
> chore(tests): remove unwanted license headers

- CHANGELOG/unreleased/kong/11468.yaml
- CHANGELOG/unreleased/kong/11484.yaml
- kong/init.lua
- kong/pdk/tracing.lua
- kong/plugins/opentelemetry/handler.lua
- kong/runloop/handler.lua
- kong/tracing/instrumentation.lua
- kong/tracing/propagation.lua
- spec/02-integration/14-tracing/02-propagation_spec.lua
- spec/02-integration/14-tracing/03-tracer-pdk_spec.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
backport of: 
- https://github.com/Kong/kong/pull/11484
- https://github.com/Kong/kong/pull/11135
- https://github.com/Kong/kong/pull/11468
* increased precision of the request (kong) span to nanoseconds
KAG-2336
Fix #11294 (secondary issue reported in the comments)
> [backport to release/3.3.x] fix(tracing): time precision, sampling rate, span hierarchy (#11484)

- changelog/unreleased/kong/11627.yaml
- changelog/unreleased/kong/per_reqeuest_deubgging.yml
- kong-3.5.0-0.rockspec
- kong/conf_loader/init.lua
- kong/constants.lua
- kong/dynamic_hook/init.lua
- kong/dynamic_hook/wrap_function_gen.lua
- kong/global.lua
- kong/globalpatches.lua
- kong/hooks.lua
- kong/init.lua
- kong/resty/dns/client.lua
- kong/runloop/handler.lua
- kong/templates/kong_defaults.lua
- kong/timing/context.lua
- kong/timing/hooks/dns.lua
- kong/timing/hooks/http.lua
- kong/timing/hooks/init.lua
- kong/timing/hooks/redis.lua
- kong/timing/hooks/socket.lua
- kong/timing/init.lua
- kong/tools/utils.lua
- spec/02-integration/21-request-debug/01-request-debug_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/muti-external-http-calls/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/muti-external-http-calls/schema.lua
A mechanism for observing the time consumed by each component (not all) of the given request.
[KAG-1902]
[KAG-1902]: https://konghq.atlassian.net/browse/KAG-1902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tracing): per request debugging

- kong/clustering/compat/checkers.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
Address compatibility for older DPs for the opentelemetry and zipkin configuration option: `header_type` and for zipkin's `default_heder_type`
KAG-2705
> fix(hybrid): opentelemetry and zipkin header_type

- kong/clustering/compat/checkers.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
backport of https://github.com/Kong/kong/pull/11686
address compatibility for older DPs for the opentelemetry and zipkin configuration option: `header_type` and for zipkin's `default_heder_type`
- [] The Pull Request has backports to all the versions it needs to cover
KAG-2705
> [backport #11686 to release/3.4.x] fix(hybrid): opentelemetry and zipkin header_type

- spec/02-integration/21-request-debug/01-request-debug_spec.lua
This includes several changes designed to make the request-debug test suite faster and less memory-intensive.
This test suite is occasionally triggering the OOMKiller in our Enterprise CI runs, and this changeset aims to stop the bleeding.
* de-dupe DB initialization calls (`helpers.get_db_utils()`)
* truncate `error.log` before running tests
* search `error.log` line-by-line instead of all at once
* ensure proxy client connections are closed in all branches
KAG-2710
> tests(request-debug): improve integration tests

- .github/workflows/community-stale.yml
We decided to close old tickets for the repo. This workflow will automatically label PRs/issues as stale for 14 days of inactivity, and close after another 7 days.
> chore(ci): automatically stale and close issue/pr

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> doc(CONTRIBUTING): mention changelog

- kong/runloop/handler.lua
In PR #11627 we introduced a new function `get_updated_monotonic_ms()` in `tools.utils`,
so we can replace the same implementation in `runloop.handler`.
> refactor(runloop): use utils.get_updated_monotonic_ms()

- kong-3.4.2-0.rockspec
- kong/meta.lua
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/debian-10-amd64.txt
- scripts/explain_manifest/fixtures/debian-11-amd64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/el8-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
Two noticeable changes:
* Bumps the version numbers of rockspec and meta after release of 3.4.1
* Backports https://github.com/Kong/kong/pull/11465 (with modifications) to the 3.4.x branch in order to avoid errors in the manifest checks - example  https://github.com/Kong/kong/actions/runs/6391958890/job/17349006720
> chore(release): bump version numbers to 3.4.2

- build/kong_bindings.bzl
- changelog/unreleased/kong/fix_patch_order.yml
When openresty patch applying order matters, some patch applying fails. Fix it by sorting.
There are 2 patches in the Openresty LuaJIT patches directory that have dependency:
1. LuaJIT-2.1-20230410_03_arm64_sigill.patch
2. LuaJIT-2.1-20230410_07_ldp_stp_unaligned.patch
2 depends on 1. And the current bazel build applying the patch in a non-deterministic order and sometime, it can run to build error if 2 is applied first. Fix it by sorting the patch.
Fix #_[KAG-2712]_
[KAG-2712]: https://konghq.atlassian.net/browse/KAG-2712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(build): fix the building failure when applying patches

- kong/timing/init.lua
- spec/02-integration/21-request-debug/01-request-debug_spec.lua
Using `request_id` instead of `debug_id` for the output of the per request debugging feature.
- [N/A] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
Fix #_[KAG-2696]_
[KAG-2696]: https://konghq.atlassian.net/browse/KAG-2696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(request-debugging): use `request_id` instead of `debug_id`

- kong/cmd/utils/prefix_handler.lua
- kong/templates/nginx_kong.lua
- spec/01-unit/04-prefix_handler_spec.lua
Kong can't start once we set `proxy_access_log` to `off` as `access_log off kong_log_format` is invalid in Nginx.
_[KAG-2730]_
[KAG-2730]: https://konghq.atlassian.net/browse/KAG-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(template): fix failure of starting if `proxy_access_log` is `off`

- spec/fixtures/https_server.lua
- spec/fixtures/mock_webserver_tpl.lua
- spec/helpers.lua
Migrate the changes related to helpers from [6734](https://github.com/Kong/kong-ee/pull/6734) to ce.
* `wait_for_all_config_update` support pass custom headers
* `https_server support disable` listen ipv6
> tests(helpers): wait_for_all_config_update support pass custom headers and https_server support disable listen ipv6

- changelog/unreleased/kong/11727.yml
- kong/api/routes/kong.lua
- kong/vaults/env/schema.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
Adding a new endpoint for named vaults. 
`/schemas/vaults/:name`
Vaults are very similar to plugins in terms of internal structure and we do provide such an endpoint for plugins already (`/schemas/plugins/:name`). This endpoint allows us to query a schema of a specific vault, which wasn't possible before.
@Guaris @fabianrbz  This might be of interest to you.
Fix https://konghq.atlassian.net/browse/KAG-2535
> feat(core): add `/schemas/vaults/:name` endpoint

- changelog/unreleased/kong/wasm-filter-json-config.yml
- kong/db/schema/entities/filter_chains.lua
- kong/db/schema/init.lua
- kong/db/schema/metaschema.lua
- kong/runloop/wasm.lua
- spec/02-integration/20-wasm/01-admin-api_spec.lua
- spec/02-integration/20-wasm/02-db_spec.lua
- spec/02-integration/20-wasm/09-filter-meta_spec.lua
This change combines the `config` and `json_config` fields for Wasm filters.
Before, JSON configuration lived in the `json_config` attribute, and `config` could only hold strings:
```lua
{
filters = {
{
name = "my-filter-with-string-config",
config = "a=1 b=2",
},
{
name = "my-filter-with-json-config",
json_config = {
a = 1,
b = 2,
}
},
}
}
```
Now, both string and JSON configurations live in `config`:
```lua
{
filters = {
{
name = "my-filter-with-string-config",
config = "a=1 b=2",
},
{
name = "my-filter-with-json-config",
config = {
a = 1,
b = 2,
}
},
}
}
```
The `json_config` field/attribute was [introduced recently](https://github.com/Kong/kong/pull/11568) and is unreleased, so this change does not break any existing API. 
Note: filters may _only_ use JSON in `config` if they have …
> feat(wasm): combine config and json_config fields

- kong/api/routes/kong.lua
- kong/db/schema/entities/filter_chains.lua
- kong/db/schema/json.lua
- kong/runloop/wasm.lua
- spec/02-integration/20-wasm/09-filter-meta_spec.lua
This exposes JSON schemas for Wasm filters via a new API endpoint. For filters without a user-supplied schema, the default schema is returned.
For better interoperability with other systems, we also ensure that each schema has the proper draft 4 `$schema` attribute.
KAG-2719
> feat(wasm): add /schemas/filters/:name API endpoint

- build/openresty/patches/nginx-1.21.4_09-http2-rapid-reset-ddos-attack-cve-2023-44487.patch
- changelog/unreleased/kong/fix-cve-2023-44487.yml
fix(patches): apply Nginx patch for detecting HTTP/2 stream reset attacks early (CVE-2023-44487)
From nginx/nginx@6ceef19
---------
Patch was acquired from here:
https://mailman.nginx.org/pipermail/nginx-devel/2023-October/S36Q5HBXR7CAIMPLLPRSSSYR4PCMWILK.html
It was slightly modified to apply cleanly on our nginx-1.21.4 (just small offset differences),
See: https://www.cve.org/CVERecord?id=CVE-2023-44487
SIR-435
> fix(patches): apply Nginx patch for detecting HTTP/2 stream reset attacks early (CVE-2023-44487)

- kong/clustering/compat/checkers.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
** REBASE and MERGE **
This reverts commit ad916d29571ef66868d15755e91e471a73d0048a.
Revert commits to prepare for the 3.4.2 http2 CVE patch.
> chore(*): Revert for http2 CVE patch

- kong/dynamic_hook/init.lua
- kong/dynamic_hook/wrap_function_gen.lua
- kong/init.lua
- kong/resty/dns/client.lua
- kong/runloop/handler.lua
- kong/templates/nginx_kong.lua
- kong/timing/init.lua
Improve the performance of the request debugging feature.
* reduce the number of calls of `ngx.ctx`
* cache some functions at the module level
* delete debug request headers only when debug headers exist.
* reduce the number of calls of `req_dyn_hook.runhooks()`.
_[KAG-2738]_
[KAG-2738]: https://konghq.atlassian.net/browse/KAG-2738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> perf(request-debugging): improve performance

- .github/workflows/build_and_test.yml
The test suite build&test should ignore lowercase changelog directory.
> chore(ci): build&test should ignore lowercase changelog directory

- kong/plugins/rate-limiting/policies/init.lua
The [request-aware-table](https://github.com/Kong/kong/pull/11017/) was incorrectly used in this plugin, these tables are expected to be shared across requests and should not be limited to a single request.
This PR just reverts the usage of the request-aware-table from the rate-limiting plugin.
> fix(rate-limiting): revert request-aware-table usage

- kong/tools/request_aware_table.lua
This is a simple code clean for #11017.
> refactor(tools): use `or` to simplify table_new()

- kong/concurrency.lua
- kong/tools/utils.lua
- spec/02-integration/13-vaults/03-mock_spec.lua
Cherry-pick of commit 066ceb3 to 3.4.x branch
> [backport] fix(vault): vault try should avoid using semaphore in non-yieldable phases

- spec/02-integration/11-dbless/01-respawn_spec.lua
- spec/02-integration/11-dbless/02-workers_spec.lua
- spec/02-integration/11-dbless/03-config_persistence_spec.lua
We should use the latest format version for tests, i.e. `3.0`
> tests(dbless): update format_version to `3.0`

- spec/03-plugins/23-rate-limiting/04-access_spec.lua
We should not use `with_max_retries` for the `expire counter` tests as the default `step` is `0.05` (too small to across a window).
_[KAG-2667]_
[KAG-2667]: https://konghq.atlassian.net/browse/KAG-2667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(rate-limiting): fix a flaky test

- .github/workflows/changelog-requirement.yml
Sometimes changelog are not needed and instead, existing ones are being updated instead. The action should not be so strict and forces every PR to add new file into the changelog directory.
> chore(actions): correctly check for changelog updates

- kong/pdk/response.lua
The check of `ngx.headers_sent` appears two times, I think that it is unnecessary.
I also think that we could create a new wrapper function for the checking of `ngx.headers_sent` ( will do it in another PR).
> refactor(pdk): remove duplicated code in set_status()

- kong/runloop/events.lua
We are using `string.buffer` now, no json any more.
> style(runloop): fix incorrect error log message

- .ci/run_tests.sh
- kong/db/schema/entities/filter_chains.lua
- spec/02-integration/20-wasm/01-admin-api_spec.lua
- spec/02-integration/20-wasm/03-runtime_spec.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
- spec/02-integration/20-wasm/05-cache-invalidation_spec.lua
- spec/02-integration/20-wasm/06-clustering_spec.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
- spec/02-integration/20-wasm/08-declarative_spec.lua
- spec/02-integration/20-wasm/09-filter-meta_spec.lua
- spec/fixtures/admin_api.lua
- spec/fixtures/blueprints.lua
- spec/fixtures/dc_blueprints.lua
This PR started as an effort to add more test coverage and culminated in a bugfix with filter chain validation in hybrid mode.
Filters that have an associated JSON schema may accept typed configuration, whereas filters with no schema must have their configuration JSON-encoded:
```json
{
"name": "my-filter-chain",
"filters": [
{
"name": "my-typed-filter",
"config": {
"a": 1,
"b": 2
}
},
{
"name": "my-non-typed-filter",
"config": "{ \"a\": 1, \"b\": 2 }"
}
]
}
```
Filter JSON schemas are defined in `{{filter}}.meta.json` files. These files are not currently required to be present on data-plane nodes, which means the data-plane won't always know which filters have JSON configurations and which ones have string configurations.
This can result in an error when a typed/JSON filter config is …
> fix(wasm): permit json-typed filter configuration on data plane nodes

- kong/clustering/compat/checkers.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
add back #11687
This reverts commit 0b47e243e0b19ad193b280ae25f349b105c9c74f.
> Revert "Revert "fix(hybrid): opentelemetry and zipkin header_type

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- kong.conf.default
Add descriptions to `kong.conf.default`.
> docs(request-debugging): add docs to `kong.conf.default`

- changelog/unreleased/kong/plugin-configure-phase.yml
- kong/init.lua
- kong/plugins/acme/client.lua
- kong/plugins/acme/handler.lua
- kong/plugins/prometheus/exporter.lua
- kong/plugins/prometheus/handler.lua
- kong/runloop/handler.lua
- kong/runloop/plugins_iterator.lua
- spec/02-integration/05-proxy/21-grpc_plugins_triggering_spec.lua
- spec/02-integration/05-proxy/28-stream_plugins_triggering_spec.lua
- spec/02-integration/07-sdk/02-log_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/logger-last/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/logger/handler.lua
Adds a new handler that plugins can implement:
```lua
-- configs will be `nil` if there is no active configs for the plugin
function Plugin:configure(configs)
end
```
See the change in `acme` and `prometheus` plugins.
KAG-2672
KAG-2678
KAG-2679
> feat(runloop): plugin:configure(configs) handler

- kong/clustering/utils.lua
this patch aligns code with EE and is mostly for test scenarios where `kong.configuration.dedicated_config_processing` can be non-boolean
> fix(core): comparison against boolean

- kong-3.5.0-0.rockspec
- scripts/explain_manifest/fixtures/alpine-amd64.txt
- scripts/explain_manifest/fixtures/alpine-arm64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt
- scripts/explain_manifest/fixtures/debian-10-amd64.txt
- scripts/explain_manifest/fixtures/debian-11-amd64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/el8-amd64.txt
- scripts/explain_manifest/fixtures/el9-amd64.txt
- scripts/explain_manifest/fixtures/el9-arm64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
This new package revision removes lua-cjson as a dependency, and therefore the cjson.so entry is also removed from our manifests.
A changelog entry is not needed, as this dependency was first added during the 3.5 release cycle.
KAG-2757
> chore(deps): pin lua-resty-ljsonschema to 1.1.6-2

- kong/runloop/handler.lua
- kong/templates/nginx_kong.lua
If we utilize the nginx original directive `proxy_set_header X-Kong-Request-Id $kong_request_id` instead of lua source code `set_header(Kong-Request-Id ,request_id)`, we can enhance the QPS by ~2% in the testing scenario where no plugins are used and pure http proxying is deployed.
And there are no `set_header` calls within the core path. All the headers that are added to the upstream are currently configured using the proxy_set_header directive.
* Reuse old test cases. The functionality hasn't been modified
* This PR replaces the lua api call of `set_header` with `proxy_set_header`.
KAG-2814
> perf(request-id): use proxy_set_header instead of lua api set_header

- .github/workflows/upgrade-tests.yml
Previously, the upgrade tests were in a standalone workflow and used an incorrect container image as the upgrade target version. With this PR, the tests are integrated into the main build/test workflow and make use of the same container image as pongo, which is built from the PR's branch.
Adapted from https://github.com/Kong/kong-ee/pull/6853 - In EE, we already build a docker image for testing with Pongo, so it made sense to piggy-back the upgrade testing onto that.  In CE, we don't have that, so the image is built specifically for the upgrade test.
KAG-2804
> tests(ci): integrate upgrade tests into `build_and_test.yml`

- kong/plugins/ldap-auth/access.lua
* use the `ngx.re.find` and `ngx.re.match` functions for more robust and efficient string matching operations.
* adds error handling and logging for potential errors during authentication header parsing and credential decoding.
* tweak the handling position for the case where `proxy_authorization_value` does not exist.
Fix [FTI-5329](https://konghq.atlassian.net/browse/FTI-5329)
[FTI-5329]: https://konghq.atlassian.net/browse/FTI-5329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(plugins/ldap-auth): optimize the process of parsing and handling authentication headers

- kong/pdk/response.lua
As we did in other PRs, `string.buffer` is better than `table.concat`.
I also change the logic of `ngx.ctx.KONG_BODY_BUFFER`, Please verify it is correct.
> refactor(pdk): get_raw_body with string.buffer

- changelog/3.5.0/kong-manager/config_card_format.yml
- changelog/3.5.0/kong-manager/fix_port_info.yml
- changelog/3.5.0/kong-manager/fix_proxdy_cache.yml
- changelog/3.5.0/kong-manager/fix_proxy_cache.yml
- changelog/3.5.0/kong-manager/plugin_field_descriptions.yml
- changelog/3.5.0/kong-manager/plugin_protocol.yml
- changelog/3.5.0/kong-manager/target_list_actions.yml
This PR adds Kong Manager Open Source 3.5 changelog.
> chore(*): add changlog for Kong Manager 3.5

- kong/clustering/init.lua
Since we introduced wasm, the name `plugins_list` is a old name, not suitable for present logic, we should use ` basic_info` to avoid misunderstanding.
> refactor(clustering): use the correct param name `basic_info` for init_worker()

- kong/clustering/utils.lua
Simplify the params of `parse_proxy_url()`.
> refactor(clustering): simplify `parse_proxy_url()`

- changelog/unreleased/kong/aws_lambda_service_cache.yml
- kong/plugins/aws-lambda/handler.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/fixtures/custom_vaults/kong/vaults/random/init.lua
- spec/fixtures/custom_vaults/kong/vaults/random/schema.lua
Cache the aws lambda service by composing a cache key using the service related fields, so that service object can be reused between plugins and vault refresh can take effect when key/secret is rotated
* aws lambda service cache by service related fields
Fix KAG-2832
> fix(aws-lambda): aws lambda service cache by service related fields

- build/dockerfiles/apk.Dockerfile
- build/dockerfiles/deb.Dockerfile
- build/dockerfiles/rpm.Dockerfile
Behaviour change from https://github.com/Kong/kong/pull/11594
Fix KAG-2855
Fix #11776
> fix(build): correctly set manifest for multiarch images

- kong-3.6.0-0.rockspec
- kong/meta.lua
Bump the version to 3.6.0 in the master branch as part of the 3.5 feature freeze.
> chore(release): bump version to 3.6.0 as part of the 3.5 Feature Freeze

- changelog/unreleased/kong/aws_lambda_service_cache.yml
- kong/plugins/aws-lambda/handler.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/fixtures/custom_vaults/kong/vaults/random/init.lua
- spec/fixtures/custom_vaults/kong/vaults/random/schema.lua
Backport from https://github.com/Kong/kong/pull/11805
Cache the aws lambda service by composing a cache key using the service related fields, so that service object can be reused between plugins and vault refresh can take effect when key/secret is rotated
* fix(aws-lambda): aws lambda service cache by service related fields
* tests(aws-lambda): add test for checking service cache refresh when vault rotates
* style(*): lint
Fix KAG-2832
> [Backport release/3.5.x] fix(aws-lambda): aws lambda service cache by service related fields (#11805)

- kong-3.6.0-0.rockspec
- kong/pdk/request.lua
- kong/router/atc.lua
- kong/router/compat.lua
- kong/tools/string.lua
- kong/tools/utils.lua
`resty.core.utils.str_replace_char()`  is a better way to replace `-` to `_`.
In the future `string.lua` will gather more functions to simplify `tools.utils.lua`.
See: #10443
> perf(router): use `resty.core.utils.str_replace_char()` for dashes

- kong/templates/nginx_kong.lua
Just uses more correct `#admin_listeners > 0` in templates. I think `admin_listen` may be `"off"` which is kinda against of the reason why this statement is there in template in a first place.
> chore(conf): gui #admin_listen > 0 -> #admin_listeners > 0

- changelog/unreleased/kong/vault-init-warmup.yml
- kong/pdk/vault.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
Fixes issue where this was logged to logs:
```
2023/10/18 13:53:33 [warn] 8714#0: [kong] vault.lua:861 error updating secret reference {vault://env/PG_USER}: could not find cached value
```
That happened for example when starting Kong with this command:
```
KONG_LOG_LEVEL=warn PG_USER=kong KONG_PG_USER={vault://env/PG_USER} ./bin/kong start
```
It auto-corrected itself, which was good in this case. This commit makes it more robust, and does not warn anymore as caches are properly warmed.
> fix(vault): properly warmups the cache on init

- changelog/unreleased/kong/fix-error-message-print.yml
- kong/plugins/aws-lambda/handler.lua
Before the fix, error message is:
[kong] init.lua:405 [aws-lambda] table: 0x04183d70, client:127.0.0.1...
After:
[kong] init.lua:405 [aws-lambda] Function not found: arn:aws:lambda:us-east-1:xxx:function:test-lambda-2, client: 127.0.0.1...
Fix #_[KAG-2844]_
[KAG-2844]: https://konghq.atlassian.net/browse/KAG-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(core): print error message correctly when lambda plugin fails.

- changelog/unreleased/kong/fix-opentelemetry-parent-id.yml
- kong/plugins/opentelemetry/handler.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
Note: the bug was introduced by https://github.com/Kong/kong/pull/11468 where the parent_id was incorrectly [updated on the balancer span](https://github.com/Kong/kong/pull/11468/files#diff-56740d64d3f92488a0cc8c0a5fd35904c2769d3b0b21770d66520c0c2f049ee3L120-R127) instead of the root span. This PR reverts that part.
When the `balancer` instrumentation was enabled, the parent span was set incorrectly on traces, this fix addresses the problem by setting the parent span correctly on the root (`kong`) span when there is an incoming tracing header.
KAG-2811
FTI-5485
> fix(tracing): set parent span correctly

- kong/pdk/vault.lua
> chore(vault): fix docstring of get_cache_value_and_ttl

- kong/pdk/service/response.lua
- kong/pdk/vault.lua
It is a sister PR of #11721, optimize the code of pdk.
> refactor(pdk): use `resty.core.utils.str_replace_char` instead of `gsub`

- .github/workflows/changelog-requirement.yml
`>` evaluates multiline string into a single line thus makes `exit 1` becoming an argument for `echo`.
https://github.com/Kong/kong-ee/pull/6942
> fix(ci): correctly exit 1 when changelog not found

- changelog/unreleased/kong/fix-opentelemetry-parent-id.yml
- kong/plugins/opentelemetry/handler.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
Backport of https://github.com/Kong/kong/pull/11786
Note: the bug was introduced by https://github.com/Kong/kong/pull/11468 where the parent_id was incorrectly [updated on the balancer span](https://github.com/Kong/kong/pull/11468/files#diff-56740d64d3f92488a0cc8c0a5fd35904c2769d3b0b21770d66520c0c2f049ee3L120-R127) instead of the root span. This PR reverts that part.
When the `balancer` instrumentation was enabled, the parent span was set incorrectly on traces, this fix addresses the problem by setting the parent span correctly on the root (`kong`) span when there is an incoming tracing header.
KAG-2811
FTI-5485
> [backport to release/3.4.x] fix(tracing): set parent span correctly (#11786)

- kong/tools/request_aware_table.lua
- kong/tracing/request_id.lua
There are some duplicated code in `tracing.request_id` and `request_aware_table`,
use `request_id.get()` to get clean code.
> refactor(tools): simplify the logic of request_aware_table

- changelog/unreleased/kong/lapis_version_bump.yml
- kong-3.6.0-0.rockspec
Bump kong-lapis from 1.14.0.2 to 1.14.0.3, to remove duplicate dependency of pgmoon
[kong-lapis v1.14.0.3](https://github.com/Kong/lapis/releases/tag/v1.14.0.3) changelog:
- Change pgmoon dependency to kong-pgmoon
KAG-1695
> chore(deps): bump kong-lapis from 1.14.0.2 to 1.14.0.3

- changelog/unreleased/kong/vault-declarative.yml
- kong/init.lua
- kong/pdk/vault.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/fixtures/custom_vaults/kong/vaults/mocksocket/init.lua
- spec/fixtures/custom_vaults/kong/vaults/mocksocket/schema.lua
Warmup cache on `init` where we have Lua `coroutines` available so that it won't happen on `init_worker` where we don't have them (and cannot use e.g. lua-resty-http).
See KAG-2620 and FTI-5080.
> fix(vault): make it possible to use vault references in declarative config

- .github/workflows/upgrade-tests.yml
- changelog/unreleased/kong/fix-tcp-log-sslhandshake.yml
- kong/plugins/tcp-log/handler.lua
FIX: [Repeated sslhandshake in [tcp-log] plugin](https://github.com/Kong/kong/issues/11052)
- [ √] The Pull Request has tests
change the code in  tcp-log/handler.lua
Fix #[_[11052]_](https://github.com/Kong/kong/issues/11052)
> fix(plugin/tcp-log):repeated sslhandshake in [tcp-log] plugin

- changelog/unreleased/kong/vault-resurrect.yml
- kong/pdk/vault.lua
- spec/02-integration/13-vaults/07-resurrect_spec.lua
- spec/fixtures/custom_vaults/kong/vaults/test/schema.lua
The vault is rotating secrets on every minute which updates the shared dictionary cache with new values, both negative and positive results. This commit changes the Negative results handling on LRU. Previously the LRU was cleared for negative results, and we just used to cache for config.ttl amount of time. This commit changes it so that LRU values are deleted, and we cache things config.ttl + config.resurrect_ttl amount of time in lru cache too.
It was reported by @Hayk-S on KAG-2833.
> fix(vault): resurrect positive results in lru cache for ttl + resurrect ttl

- kong/init.lua
- kong/resty/dns/client.lua
- kong/runloop/handler.lua
- kong/timing/init.lua
The debugging data for the request is created by combining various contexts through a sequence of push, pop, and set_property operations.
In most cases, certain operations should not be executed within a specific context when employing the phase filter. However, it's important to note that the phase filter should not control the set_property operation for the root context.
The phase filter is currently exclusive to the EE version, but we need to address it in the CE version to maintain synchronization with the EE code.
The `set_root_context_prop `is for setting the `request_id `and `workspace_id`, it should not be affected by the phase filter. The phase filter is a EE only feature, but we should fix it in CE first.
And rename `is_timing_enabled` to `has_timing` to make the var name is the …
> fix(request-debugging): fix can't set root properties when enable the phase filter

- changelog/unreleased/kong/dedicated_config_processing.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/kong_tests.conf
This patch exists only to simplify the switch-back to the old default
EDIT: Decided to change the default value to OFF on the 26 Oct Block and Tackle meeting.
> chore: disable `dedicated_config_processing by default

- kong/tools/table.lua
`is_lapis_array()` and `is_array_lapis()` have the same implementation code,
this PR removed the duplicated code.
> refactor(tools): merge the implementation of `is_lapis_array`

- kong-3.6.0-0.rockspec
- kong/tools/utils.lua
- kong/tools/yield.lua
This PR is one of serial refactor PRs, the goal is to clean the huge utils.lua.
> refactor(tools): separate yield functions from utils

- changelog/unreleased/kong/fix_dns_enable_dns_no_sync.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
This is a temporary fix for the DNS resolution blocking issue. If the issue is resolved, remember to revert this option to `off`.
Fix FTI-5348
> fix(dns): set default `dns_no_sync` to `on`

- changelog/unreleased/kong/deps_bump_lua_resty_healthcheck.yml
- kong-3.6.0-0.rockspec
This bumps lua-resty-healthcheck to 3.0.0
* bump lua-resty-healthcheck to 3.0.0
KAG-2704
> chore(deps): bump lua-resty-healthcheck to 3.0.0

- spec/03-plugins/35-azure-functions/01-access_spec.lua
Temporarily disable the tests that use mockbin.org or mockbin.com as these two websites are shutdown.
KAG-2912
> tests(azure-functions): temporarily disable tests that use mockbin

- kong-3.6.0-0.rockspec
- kong/tools/gzip.lua
- kong/tools/utils.lua
separate gzip functions from tools.utils
> refactor(tools): separate gzip functions from tools.utils

- changelog/unreleased/kong/dedicated_config_processing.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/kong_tests.conf
This reverts commit 6bccc872cbb3a8bb52389a4e7b18a06b59e05ac0.
Based on the performance benchmark results, we decided to enable `dedicated_config_processing` by default.
> chore(conf): enable `dedicated_config_processing` by default

- spec/03-plugins/35-azure-functions/01-access_spec.lua
This PR fixes the azure plugin test failure due to mockbin.org sunset.
FTI-5523
> tests(*): fix azure plugin test due to mockbin sunset

- build/openresty/patches/LuaJIT-2.1-20230410_06_arm64_reg_alloc_fix.patch
Before:
```
patching file bundle/LuaJIT-2.1-20230410/src/lj_asm_arm64.h
Hunk #1 succeeded at 1133 (offset 26 lines).
Hunk #2 succeeded at 1142 (offset 26 lines).
```
After:
```
patching file bundle/LuaJIT-2.1-20230410/src/lj_asm_arm64.h
```
> chore(patches): make arm64 reg allow patches apply cleanly

- kong/plugins/acl/schema.lua
The ACL plugin is missing descriptions for its configuration parameters, resulting in empty doc fields: https://docs.konghq.com/hub/kong-inc/acl/configuration/#config
Adding descriptions from the [previous version](https://docs.konghq.com/hub/kong-inc/acl/3.3.x/configuration/#config), when they were written manually.
- [ N/A ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ N/A ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - can't do this until we update the schema.
Not applicable.
> fix(acl): Add missing descriptions to plugin schema

- kong/router/atc.lua
- kong/router/compat.lua
- spec/01-unit/08-router_spec.lua
In latest atc-router library we introduced raw string feature, now we need not to escape string.
See: https://github.com/Kong/atc-router/pull/22
KAG-2952
> refactor(router): use rust style raw string in expression

- kong/runloop/wasm.lua
We already use `string.buffer` in many fields successfully, especially for replacing `string.concat`.
* introduce `string.buffer`
* remove useless `clear_tab` `concat`
> refactor(runloop/wasm): optimize hash_chain_entity with string.buffer

- changelog/unreleased/reconfiguration-completion-detection.yml
- kong/clustering/config_helper.lua
- kong/clustering/control_plane.lua
- kong/clustering/data_plane.lua
- kong/db/declarative/import.lua
- kong/db/strategies/postgres/connector.lua
- kong/db/strategies/postgres/init.lua
- kong/global.lua
- kong/runloop/handler.lua
- spec/02-integration/04-admin_api/24-reconfiguration-completion_spec.lua
This change adds a new response header X-Kong-Transaction-Id to the Admin API.  It contains the (ever incrementing) PostgreSQL transaction ID of the change that was made.  The value can then be put into the X-If-Kong-Transaction-Id variable in a request to the proxy path.  The request will be rejected with a 503 error if the proxy path has not been reconfigured yet with this or a later transaction id.
The mechanism is useful in testing, when changes are made through the Admin API and the effects on the proxy path are then to be verified. Rather than waiting for a static period or retrying the proxy path request until the expected result is received, the proxy path client specifies the last transaction ID received from the Admin API in the X-If-Kong-Transaction-Id header and retries the …
> feat(testing): add reconfiguration completion detection mechanism

- kong/db/schema/metaschema.lua
This pull request introduces a new field attribute called `examples` in the metaschema. The `examples` attribute is designed to provide example values for fields in schemas. `examples` is an array so you can specify multiple example values for a single field. 
Adding examples would like this:
`kong/db/schema/typedefs.lua`
```
typedefs.certificate = Schema.define {
type = "string",
custom_validator = validate_certificate,
description = "A string representing a certificate.",
examples = {
"-----BEGIN CERTIFICATE-----\nYourCertificateDataHere\n-----END CERTIFICATE-----",
"-----BEGIN CERTIFICATE-----\nAnotherCertificateDataHere\n-----END CERTIFICATE-----"
}
}
```
and
```
typedefs.auto_timestamp_s = Schema.define {
type = "integer",
timestamp = true,
auto = true,
description = "An integer …
```
> feat(db): add `examples` to metaschema fields

- kong/tools/string.lua
Cache the result of lower(unit) in `bytes_to_str()`, avoiding duplicated calcuation.
> refactor(tools): cache lower(unit) for `bytes_to_str()`

- kong/tools/utils.lua
`str:find("x", 1, true)` is better than normal `str:find("x")`
> style(tools): optimize calls of string.find

- changelog/unreleased/kong/cookie-name-validator.yml
- kong/db/schema/entities/upstreams.lua
- kong/db/schema/typedefs.lua
- kong/tools/utils.lua
- spec/01-unit/05-utils_spec.lua
- spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
We have a too strong limitation on the character used in cookie names. For example "." should be allowed.
We choose not to do the same to the header because we rely on Nginx's API to handle headers, which has more strict restrictions on the characters.
Fix #11860
> fix(core): definition of cookie name validate

- kong/pdk/log.lua
Use `string.buffer` to optimize string operation.
Here I simply replace table.insert and table.concat, but not sure the `serializers[n]`'s effect, so just keep them.
> refactor(pdk): serialize log msg with string.buffer

- changelog/unreleased/kong/rate-limiting-fix-redis-sync-rate.yml
- kong/plugins/rate-limiting/policies/init.lua
- spec/03-plugins/23-rate-limiting/02-policies_spec.lua
When the periodic sync to redis feature is turned on, using the `sync_rate` configuration option, keys are incremented by 2 instead of 1 for requests that arrive after the `sync_rate` interval has expired.
This happens because after each sync, the key is loaded from redis using `incr` (see: https://github.com/Kong/kong/pull/10559) however the next call to `increment` also adds 1 to the counter, so the key is incremented twice every time it's loaded from redis. In other words there can be 2 increments for the same request: [here](https://github.com/Kong/kong/blob/f59e36b554b6071a9213deea6947eb804dd7a6f6/kong/plugins/rate-limiting/policies/init.lua#L325) and then [here](https://github.com/Kong/kong/blob/f59e36b554b6071a9213deea6947eb804dd7a6f6/kong/plugins/rate-limiting/policies/init.lua#L29 …
> fix(rate-limiting): counters accuracy with redis policy & sync_rate

- kong/runloop/plugin_servers/init.lua
- kong/runloop/plugin_servers/pb_rpc.lua
- kong/runloop/plugins_iterator.lua
Cherry-pick fixes https://github.com/Kong/kong-ee/pull/6417.
KAG-2859.
> refactor(pluginserver): reset instance triggers invalidation

- kong/db/strategies/postgres/connector.lua
The PR https://github.com/Kong/kong/pull/11480 introduced a bug that calls `store_connection` without passing `self`. This fixes that.
> fix(db): pg store connection called without self

- kong/plugins/acl/schema.lua
Accidentally added schema descriptions to the nested `elements` field instead of the field itself, so the description is being applied to the wrong thing. Fixing that.
> fix(acl-plugin): Move schema descriptions into the right field

- kong/plugins/opentelemetry/schema.lua
The OpenTelemetry plugin is missing descriptions for its configuration parameters, resulting in empty doc fields: https://docs.konghq.com/hub/kong-inc/opentelemetry/configuration/#config
* `resource_attributes` and `header_type`:  Adding descriptions from the [previous version](https://docs.konghq.com/hub/kong-inc/acl/3.3.x/configuration/#config), when they were written manually.
* `http_response_header_for_traceid`: Description from https://github.com/Kong/kong/pull/10379.
- [ N/A ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - can't do this until we update the schema.
N/A
N/A, reported in docs slack channel.
> fix(opentelemetry): Add missing descriptions to schema

- kong/pdk/service/request.lua
Use `string.buffer` to replace slow `table.concat`.
> refactor(pdk): output content with string.buffer

- kong.conf.default
The `mem_cache_size` parameter in kong.conf mentions that it controls the size of two caches, but doesn't say what the names of the caches are.
According to our [changelog](https://github.com/Kong/kong/blob/master/CHANGELOG-OLD.md#core-32), these two in-memory caches are `kong_core_cache` and `kong_cache`.
Resolves doc ticket https://konghq.atlassian.net/browse/DOCU-1878.
N/A
N/A
> docs(kong.conf): Add names of referenced caches to mem_cache_size parameter

- spec/02-integration/05-proxy/05-dns_spec.lua
just make sure dns resolve can run normally in the stream subsystem
Fix #11896
> tests(dns): add a test case to cover dns resolution in stream subsystem

- changelog/unreleased/kong/clustering-empty-data-plane-hash-fix.yml
- kong/clustering/control_plane.lua
- kong/clustering/data_plane.lua
- spec/02-integration/20-wasm/06-clustering_spec.lua
The previous logic defaulted the config_hash to nil when it was detected to be an empty string. This can cause update_sync_status() to fail, because config_hash is a required attribute:
> 2023/11/03 17:13:30 [debug] 4052224#0: *150 [lua] connector.lua:560: execute(): SQL query throw error: ERROR: null value in column "config_hash" of relation "clustering_data_planes" violates not-null constraint
> Failing row contains (4fb29006-8db1-48bb-b68c-34b582e1d91a, soup, 127.0.0.1, 2023-11-04 00:13:30+00, null, 2023-11-18 00:13:30.799+00, 3.6.0, filter_set_incompatible, 2023-11-04 00:13:30+00, {})., close connection
> 2023/11/03 17:13:30 [notice] 4052224#0: *150 [lua] init.lua:275: upsert(): ERROR: null value in column "config_hash" of relation "clustering_data_planes" violates not-null constraint …
> fix(clustering): ensure data plane config hash is never nil

- changelog/unreleased/kong/expression_http_headers_sensitive.yml
- kong/router/atc.lua
- kong/router/compat.lua
- spec/01-unit/08-router_spec.lua
> fix(router): http headers sensitive for expressions and insensitive for traditional_compatible

- changelog/unreleased/kong/subsystems_do_not_share_router_schemas.yml
- kong/db/schema/entities/routes.lua
- kong/router/atc.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
We do not need the function `has_paths()`, which is only useful for http subsystem, and now we support expressions in both http and stream subsystem.
KAG-2961
> refactor(router): http/stream subsystem does not share schema

- changelog/unreleased/kong/pdk-response-send-remove-transfer-encoding.yml
- kong/pdk/response.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/fixtures/aws-lambda.lua
- t/01-pdk/08-response/11-exit.t
This PR is a follow-up fix for https://github.com/Kong/kong/pull/8698 to ignore the transfer encoding header set by the user.
The line removed in this PR seems to be conflict with the original fix and makes the original fix meaningless, so removed this line to get the expected behavior.
We have related bug reports that when using the AWS-Lambda plugin in proxy_integration mode if the lamdba function returns an arbitrary transfer-encoding header, the response sent by Kong will both contain content-length and transfer-encoding, which is an unexpected result.
Fix FTI-5028
> fix(pdk): response send function should ignore transfer-encoding correctly

- changelog/unreleased/kong/bump-resty-openssl-1.0.1.yml
- kong-3.6.0-0.rockspec
<a name="1.0.1"></a>
- **jwk:** return error if exporting private key from public key ([#128](https://github.com/fffonion/lua-resty-openssl/issues/128)) [3a1bc27](https://github.com/fffonion/lua-resty-openssl/commit/3a1bc273e2a3f41faa7eb68f2939fd1fc25cdecb)
<a name="1.0.0"></a>
- **\*:** remove unused cdefs [84abc0a](https://github.com/fffonion/lua-resty-openssl/commit/84abc0ab99b3d649c7fe4575cf13867cf96a94ef)
- **\*:** BREAKING: drop OpenSSL 1.0.2, 1.1.0 and BoringSSL support [99b493e](https://github.com/fffonion/lua-resty-openssl/commit/99b493e671886e68c07b1b9c9472075c22ce38e9)
- **fips:** add get_fips_version_text [935227b](https://github.com/fffonion/lua-resty-openssl/commit/935227b348ba4416f2f4d671dd94f7910cbf9e61)
<a name="0.8.26"></a>
- **version:** add support for all 3.x versions …
> chore(deps): bump resty-openssl from 0.8.25 to 1.0.1

- changelog/unreleased/kong/bump-lpeg-1.1.0.yml
- kong-3.6.0-0.rockspec
+ accumulator capture
+ UTF-8 ranges
+ Larger limit for number of rules in a grammar
+ Larger limit for number of captures in a match
+ bug fixes
+ other small improvements
> chore(deps): bump lpeg from 1.0.2 to 1.1.0

- changelog/unreleased/kong/bump-lua-messagepack-0.5.3.yml
- kong-3.6.0-0.rockspec
- support Lua 5.4
- testsuite with TestAssertion
- minor refactors
> chore(deps): bump lua-messagepack from 0.5.2 to 0.5.3

- spec/helpers/http_mock.lua
Simplify the most common use of http mock to simply get request/response/whole transaction.
> tests(*): improve http mock

- kong-3.6.0-0.rockspec
- kong/tools/system.lua
- kong/tools/utils.lua
> refactor(tools): separate system-related functions from tools.utils

- kong-3.5.1-0.rockspec
- kong/meta.lua
> chore(version): bump versions to 3.5.1

- .github/workflows/backport.yml
* now contains all the commits of a PR, not only the last one
* now copies labels on the backport PRs
* now copies milestones on the backport PRS
* now copies requested reviewers to the backport PRS
The action instructions for manually merging were mostly wrong and rarely worked.
Now they are more descriptive and isolated (using worktrees)
Fix https://konghq.atlassian.net/browse/KAG-2652
> chore: improve backporting process

- kong/router/atc.lua
`get_headers_key()` and `get_queries_key` have almost the same implementation,
this PR introduce a new function `get_headers_or_queries_key()` and simplify these two functions.
> refactor(router): simplify the functions of cache calculation

- spec/02-integration/01-helpers/03-http_mock_spec.lua
- spec/03-plugins/35-azure-functions/01-access_spec.lua
- spec/fixtures/proxy_wasm_filters/build
- spec/helpers/http_mock.lua
- spec/helpers/http_mock/asserts.lua
- spec/helpers/http_mock/clients.lua
- spec/helpers/http_mock/debug_port.lua
- spec/helpers/http_mock/nginx_instance.lua
- spec/helpers/http_mock/tapping.lua
- spec/helpers/http_mock/template.lua
https://github.com/Kong/kong/pull/11587 accidentally adds a symlink that is currently in master's gitignore into 3.3 branch. This PR removes the useless symlink.
> [release/3.3.x] chore(*): remove useless wasm build file from 3.3.x

- kong/db/dao/plugins.lua
- kong/tools/utils.lua
> refactor(tools): move sort_by_handler_priority to DAO

- kong/pdk/node.lua
- kong/tools/utils.lua
`gethostname` is only used by pdk, it should not be in utils.
> refactor(pdk): move ffi.cdef gethostname from tools into pdk

- .github/workflows/backport.yml
Automated backport to `release/3.4.x`, triggered by a label in https://github.com/Kong/kong/pull/11924.
> [backport -> release/3.4.x] chore: improve backporting process

- .github/workflows/backport.yml
Automated backport to `release/3.3.x`, triggered by a label in https://github.com/Kong/kong/pull/11924.
> [backport -> release/3.3.x] chore: improve backporting process

- build/openresty/patches/LuaJIT-2.1-20230410_08_ldoc_error_fix.patch
- changelog/unreleased/kong/fix-ldoc-intermittent-fail.yml
ldoc intermittently fails caused by an error in LuaJIT. Refer details in [KAG-1761].
Fix #_[KAG-1761]_
[KAG-1761]: https://konghq.atlassian.net/browse/KAG-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(patches): fix ldoc intermittent fail caused by LuaJIT

- Makefile
- Add Korean localization — @marocchino
- Add --exclude-name-file and --log-success options — @hanshuebner (When combined can automate re-running only failed tests)
- Add --name option to easily run single tests — @hanshuebner
- Remove unused luafilesystem dependency — @dundargoc
- Correct installation and example documentation — @C3pa and @alerque
- Use escape sequences to output UTF-8 characters in more environments — @Commandcracker
- Output more standard tracing notation in gtest handler — @Tieske
- Fix casting to string before encoding errors in JSON — @svermeulen
- Correct TAP handler to not error on no test files — @notomo
~- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog …
> chore(deps): bump busted from 2.1.2 to 2.2.0

- changelog/unreleased/reconfiguration-completion-detection.yml
- kong/init.lua
- kong/runloop/handler.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
- spec/02-integration/04-admin_api/24-reconfiguration-completion_spec.lua
Rename header so that it is clearly indicating its purpose.
> fix(*): rename Kong-Transaction-Id header to Kong-Test-Transaction-Id

- kong/pdk/init.lua
Since Kong 3.0 (#8874), we have already removed "kong.singletons", this comment is outdated.
> style(pdk): remove outdated comments of kong.singletons

- changelog/unreleased/kong/inject-nginx-directives-location.yml
- kong.conf.default
- kong/conf_loader/init.lua
- kong/templates/nginx_kong.lua
- spec/01-unit/04-prefix_handler_spec.lua
The injection of Nginx directives [is currently supported](https://docs.konghq.com/gateway/latest/reference/nginx-directives/#injecting-individual-nginx-directives) in the `http` and `server` contexts, but not in the `location` context.
To inject Nginx directives into the `location` context, it is required to create and maintain a custom Nginx template, as detailed in [this document](https://docs.konghq.com/gateway/latest/reference/nginx-directives/#custom-nginx-templates).
The goal is to enable injection of Nginx location directives into the Kong Gateway’s proxy block, following the same pattern used for `http` and `server` contexts, without the need of a custom Nginx template.
This would streamline the process and maintain consistency across different Kong Gateway’s proxy contexts.
* …
> feat(conf): inject nginx directives into kong's proxy location block

- .github/workflows/update-ngx-wasm-module.yml
This adds a faux-dependabot GitHub workflow for updating `Kong/ngx_wasm_module`. It will run once per week.
The goal of this is to keep master updated to the head of `Kong/ngx_wasm_module`'s main branch during the release cycle so that the Wasm and Gateway teams can check the integration status as updates come down the pipeline. When the release cycle comes to a close, we'll manually pin the dependency to a specific tag/release rather than HEAD.
Here is an example PR created by this workflow:
https://github.com/Kong/kong/pull/11982
KAG-2512
> chore(ci): add ngx_wasm_module bump workflow

- kong/router/utils.lua
There is a tight loop when building Router phone home statistics that can introduce latency spikes on worker 0. This commit adds yield to that loop.
KAG-3062
~- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)~
~- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
> perf(router): cooperatively yield when building statistics of routes

- kong/clustering/compat/init.lua
- kong/clustering/control_plane.lua
- kong/clustering/data_plane.lua
- kong/tools/utils.lua
- spec/01-unit/05-utils_spec.lua
- spec/01-unit/19-hybrid/03-compat_spec.lua
- spec/helpers.lua
`utils.lua` includes many small modules, after some refactor PRs, it's time to use them directly.
This PR remove gzip functions from `utils.lua`, now we should use `require("kong.tools.gzip")`.
Do you think it is reasonable?
KAG-3060
> refactor(tools): remove gzip module reference in utils.lua

- kong/pdk/service/response.lua
`get_headers` does not work as it looks like. We should document the behavior.
Addressing KAG-2602, fix #11546
> chore(pdk): doc a known issue of get_headers()

- changelog/unreleased/kong/tracing-dns-query-patch.yml
- kong/globalpatches.lua
- kong/tracing/instrumentation.lua
- spec/02-integration/14-tracing/01-instrumentations_spec.lua
The dns query lazy patch was only effective for cosockets, not for the upstream dns queries, because the patch happened too late when the `toip` function had already been cached in some modules (i.e. balancer)
This change moves the patch to `globalpatches.lua` so that dns spans are correctly generated both for cosocket and upstream dns queries.
* moved dns query patch away from instrumentation, into globalpatches
KAG-3057
> fix(tracing): patch dns query function earlier

- changelog/unreleased/kong/fix_dns_instrument_error_handling.yml
- kong/tracing/instrumentation.lua
- spec/02-integration/14-tracing/01-instrumentations_spec.lua
**PLEASE MERGE AFTER** https://github.com/Kong/kong/pull/11996
The patching function assumes the query never fails and that's not true.
Fix FTI-5544
> fix(tracing): error when DNS query fails

- spec/03-plugins/09-key-auth/02-access_spec.lua
mockbin.com redirects to insomnia official site and could trigger a security policy, which makes tests flaky.
This causes https://github.com/Kong/kong-ee/actions/runs/6872097650/job/18690096578?pr=7124
KAG-3091
> chore(tests): deprecate uses of mockbin.com

- .github/workflows/backport.yml
In https://github.com/Kong/kong/pull/11924 we removed the `labeled` from the `pull_request_target` section. This prevents us from triggering backports of pull requests in hindsight by adding a label. This patch adds it back.
> chore: trigger backport on label addition

- kong-3.6.0-0.rockspec
- kong/db/schema/topological_sort.lua
- kong/db/strategies/postgres/connector.lua
- kong/db/utils.lua
- kong/tools/utils.lua
- spec/01-unit/05-utils_spec.lua
`topological_sort` is moved to `kong/db/utils.lua` because it is only used in the db.
KAG-2959
> refactor(tools): move topological_sort from tools.utils to db.utils

- changelog/unreleased/kong/fix-upstream-uri-azure-function-plugin.yml
- kong/plugins/azure-functions/handler.lua
- spec/03-plugins/35-azure-functions/01-access_spec.lua
> fix(plugin/azure-function): clear upstream uri and request uri inject plugin logic

- kong/router/utils.lua
It is a small improvement of #12008，moving some declarations into `do end` block.
> refactor(router): move some declarations into local scope

- changelog/unreleased/kong/fix_dns_blocking.yml
- changelog/unreleased/kong/fix_dns_retry_and_timeout_handling.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua
- t/03-dns-client/01-phases.t
- t/03-dns-client/02-timer-usage.t
backport https://github.com/Kong/kong/pull/11900 and https://github.com/Kong/kong/pull/11386 to 3.4.x
1. fix(dns): eliminate asynchronous timer in `syncQuery()` to prevent deadlock risk (#11900)
```
* Revert "fix(conf): set default value of `dns_no_sync` to `on` (#11869)"
This reverts commit 3be2513a60b9f5f0a89631ff17c202e6113981c0.
* fix(dns): introduce the synchronous query in syncQuery() to prevent hang risk
Originally the first request to `syncQuery()` will trigger an asynchronous timer
event, which added the risk of thread pool hanging.
With this patch, cold synchronously DNS query will always happen in the current
thread if current phase supports yielding.
```
2. fix(dns): fix retry and timeout handling (#11386)
```
- Stop retrying in dns/client.lua, let the resolver handle this. …
```
> [backport -> release/3.4.x] fix(dns): Eliminate asynchronous timer in syncQuery() to prevent hang

- changelog/unreleased/kong/rl-shared-sync-timer.yml
- kong/plugins/rate-limiting/policies/init.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
All rate-limiting plugin instance syncs with the same plugin config, that is the very first config got hit by a request, and they all sync with the same rate. Even a config update won't change the DB to be synced.
The timer will sync not just the same instance's counters but all counters in the same DB. This is a compromise given the emergency and we prefer simplicity over correctness for this behavior.
* The counter table is split with DB;
* Timers are created when a request hits;
* The sync_rate is guaranteed with limited running timers and timer delay
* Cover the case in the integration test by "`with_sync_rate`"
Fix KAG-2904
> fix(plugin): RL instances sync to the same DB at same rate

- kong/conf_loader/init.lua
- kong/tools/utils.lua
Move function `validate_labels` from `kong/tools/utils.lua` to `kong/conf_loader/init.lua`.
KAG-3094
> refactor(tools): move function validate_labels from tools.utils to conf_loader

- .github/workflows/release.yml
Fix #11776
If tag is created after the release workflow_dispatch is finished, it may overwrite existing ubuntu docker image.
> chore(cd): remove trigger of tags to avoid it overwriting release

- .ci/run_tests.sh
- .github/workflows/build_and_test.yml
- spec/busted-log-failed.lua
Keep track of failing busted tests and skip re-running those that succeeded.  This is to reduce the time it takes to deal with flaky tests.
KAG-2982
> feat(ci): only re-run failed tests

- changelog/unreleased/kong/bump-lapis-1.16.0.1.yml
- kong-3.6.0-0.rockspec
- lapis.validate.types — Add types.params_map validation type, the params compatible variant of types.map_of
- model:update will now only assign the update object to the model instnance if the update completes successfully
- model:update support the returns option to control the RETURNING clause of the generated query
- model:update when timestamps are enabled, the generated updated_at value is assigned to the model instance
- lapis.validate.types — Fix bug where types.params_shape would not return the state object
- model:update will avoid storing db.raw values on passed as update object to the model instance if the update does not complmete successfully
- Model:include_in can now use computed keys to dynamically calculate a foreign key value by applying a function to each passed in …
> chore(deps): bump kong-lapis from 1.14.0.3 to 1.16.0.1

- .github/workflows/cherry-picks.yml
Introduces a GitHub Action to our workflows, designed to automate the cherry-picking process for transferring commits to another repository, specifically 'kong-ee'. This action is triggered by a configurable label (`cherry-pick kong-ee`) when a pull request is merged.
Additionally, it automatically requests a review from the individual who merged the original pull request.
The action can be found here: https://github.com/jschmid1/cross-repo-cherrypick-action
Fix: https://konghq.atlassian.net/browse/KAG-2980
> chore: improve cherry-picking process

- kong/plugins/jwt/jwt_parser.lua
As other PRs did, string.buffer can replace table.concat to get more performance.
Reference: https://github.com/Kong/kong/pull/11304#issuecomment-1671212708
> perf(plugins/jwt): use string.buffer to replace table.concat

- kong/plugins/oauth2/access.lua
Use build-in functions of`tools.sha256`  to simplify code.
KAG-3156
> refactor(plugins/oauth2): use build-in functions to replace sha256

- changelog/unreleased/kong/serviceless-routes-still-trigger-datalog-plugin.yml
- kong/plugins/datadog/handler.lua
- spec/03-plugins/08-datadog/01-log_spec.lua
fix a bug that datadog plugin is not triggered for serviceless routes.
In this PR, the datadog plugin can be triggered even if the serviceless routes are hit, and the value of tag `name` for the metric data is set to an empty string which is still a valid tag for datadog.
FTI-5576
> plugin(datadog): fix a bug that datalog plugin is not triggered for serviceless routes

- .github/workflows/release.yml
The token seems to be changed/expired and no longer working. Allow the step to fail to unblock the workflow.
> hotfix(cd): skip comment on commit step

- changelog/unreleased/kong/perf-tracing-from-timers.yml
- kong/pdk/tracing.lua
- spec/01-unit/26-tracing/01-tracer_pdk_spec.lua
- spec/03-plugins/37-opentelemetry/01-otlp_spec.lua
Before this change timers would generate spans, which means [DB](https://github.com/Kong/kong/blob/0485a76276da23064c593326178c6b04fb6ee117/kong/tracing/instrumentation.lua#L39) and [DNS](https://github.com/Kong/kong/blob/0485a76276da23064c593326178c6b04fb6ee117/kong/tracing/instrumentation.lua#L281) spans in recurring timers would be continuously generated and garbage-collected.
This commit checks the exact ngx phase and runs it against a whitelist of allowed phases to ensure the `timer` phase does not generate spans.
[KAG-3169](https://konghq.atlassian.net/browse/KAG-3169)
[KAG-3169]: https://konghq.atlassian.net/browse/KAG-3169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> perf(tracing): avoid unnecessary creations and garbage-collections of spans (from timers)

- changelog/unreleased/kong/bump-resty-openssl-1.0.1.yml
- changelog/unreleased/kong/bump-resty-openssl-1.0.2.yml
- kong-3.6.0-0.rockspec
changelog:
[1.0.2](https://github.com/fffonion/lua-resty-openssl/compare/1.0.1...1.0.2) - 2023-11-21
bug fixes
jwk: fix EC key dump parameters (https://github.com/fffonion/lua-resty-openssl/issues/131) [c659347](https://github.com/fffonion/lua-resty-openssl/commit/c659347b356acfcb808ce659ae3094ba7fb2b9f1)
* chore(deps): bump lua-resty-openssl to 1.0.2
> chore(deps): bump lua-resty-openssl to 1.0.2

- .github/workflows/backport.yml
REBASE MERGE if needed.
This PR reverts the backport bot related changes
Fix KAG-3198
> Revert new backport bot

- .github/workflows/cherry-picks.yml
That is caused by an nice bootloop. The action is triggered by a comment in the PR that contains “/cherry-pick”. When the action fails it prints the branch to the screen(by adding a comment). The branch name by default contains a “/cherry-pick” substring, which starts the action again. 
Fixing by using `startsWith` instead of `contains`.
Fix https://konghq.atlassian.net/browse/KAG-3197
> fix(cherry-picks): prevent comment flood in case of errors

- kong/clustering/tls.lua
> chore: revise the comment of the tls.validate_client_cert

- .github/workflows/label-check.yml
- changelog/unreleased/kong/fix_dns_blocking.yml
- changelog/unreleased/kong/fix_dns_retry_and_timeout_handling.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua
- t/03-dns-client/01-phases.t
- t/03-dns-client/02-timer-usage.t
backport https://github.com/Kong/kong/pull/11900 and https://github.com/Kong/kong/pull/11386 to 2.8.x
backport some commits about `pr/do not merge` label to 2.8.x
1. fix(dns): eliminate asynchronous timer in `syncQuery()` to prevent deadlock risk (#11900)
```
* Revert "fix(conf): set default value of `dns_no_sync` to `on` (#11869)"
This reverts commit 3be2513a60b9f5f0a89631ff17c202e6113981c0.
* fix(dns): introduce the synchronous query in syncQuery() to prevent hang risk
Originally the first request to `syncQuery()` will trigger an asynchronous timer
event, which added the risk of thread pool hanging.
With this patch, cold synchronously DNS query will always happen in the current
thread if current phase supports yielding.
```
2. fix(dns): fix retry and timeout handling (#11386)
```
- Stop …
```
> [backport -> release/2.8.x] fix(dns): Eliminate asynchronous timer in syncQuery() to prevent hang

- changelog/unreleased/kong/bump-atc-router-1.3.1.yml
- changelog/unreleased/kong/bump_atc_router.yml
Change the change log message to the normal form as usual.
> docs(changelog): tune the message of atc-router version bump

- kong/router/init.lua
- spec/01-unit/08-router_spec.lua
Kong gateway only use one flavor when it starts, we need not to load all router modules at once.
This will reduce the usage of memory to a degree.
KAG-3135
> refactor(router): only load configured flavor module

- changelog/unreleased/kong/add-gateway-edition-to-root-endpoint-admin-api.yml
- kong/api/routes/kong.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
this commit is the follow-up change to the PR https://github.com/Kong/kong/pull/12045, since the the edition info is still useful to the kong manager, we choose to introduce the gateway edition information in the response of the `/` endpoint.
Fix FTI-5557
> feat(admin-api): add gateway edition info to the endpoint `/`

- changelog/unreleased/kong/respect-custom-proxy_access_log.yml
- kong/cmd/utils/prefix_handler.lua
- kong/templates/nginx_kong.lua
- spec/01-unit/04-prefix_handler_spec.lua
Kong now has a fixed access log format `kong_log_format` that prevents customization. Introduced by #11663.
Resolves #12061.
If the `proxy_access_log` has a log format specified, then replace `kong_log_format` with the custom value.
* replace `kong_log_format` with custom value set by end users.
* update tests to be more robust.
Fix #_[FTI-5580]_
[FTI-5580]: https://konghq.atlassian.net/browse/FTI-5580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(core): respect custom proxy_access_log

- kong-3.6.0-0.rockspec
- kong/plugins/opentelemetry/handler.lua
- kong/tracing/instrumentation.lua
- kong/tracing/propagation.lua
- kong/tracing/tracing_context.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
Add a Tracing Context module for managing request-scoped tracing-related information. This provides an interface with `ngx.ctx.TRACING_CONTEXT` for plugins and core to read/update tracing information through.
This commit adds support to read/write:
* Trace ID (raw and all formats)
* Unlinked spans
Follow up will probably include:
* Extracted/Injecjted tracing headers information
[KAG-3125](https://konghq.atlassian.net/browse/KAG-3125)
[KAG-3125]: https://konghq.atlassian.net/browse/KAG-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(tracing): add tracing context

- kong/admin_gui/init.lua
simplify code with table.concat
> refactor(admin_gui): simplify code with table.concat

- .github/workflows/backport-fail-bot.yml
- .github/workflows/release-and-tests-fail-bot.yml
Based on https://github.com/Kong/github-slack-mapping. It is already verified by https://github.com/Kong/kong/pull/12009.
Once merged, cherry-pick to EE to fix EE notification. Only diff is `runs-on: ${{ vars.RUNS_ON }}`.
- [n/a] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
* fix workflow webhook notification based on <https://github.com/Kong/github-slack-mapping>.
Fix #_[FTI-5564]_
[FTI-5564]: https://konghq.atlassian.net/browse/FTI-5564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> chore(ci): fix workflow webhook notification

- .github/workflows/release.yml
KAG-3251
use github.event.pull_request.head.sha instead of github.sha on a PR, as github.sha on PR is the merged commit (temporary commit).
also correctly set the KONG_VERSION env var.
> fix(cd): use correct sha for PR based docker build

- changelog/unreleased/kong/fix_dns_blocking.yml
- changelog/unreleased/kong/fix_dns_retry_and_timeout_handling.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua
- t/03-dns-client/01-phases.t
- t/03-dns-client/02-timer-usage.t
backport https://github.com/Kong/kong/pull/11900 and https://github.com/Kong/kong/pull/11386 to 3.2.x
> [backport -> release/3.2.x] fix(dns): Eliminate asynchronous timer in syncQuery() to prevent hang

- Makefile
- build/templates/venv-commons
- scripts/update-copyright
- Removes luaossl
- Adds EXPAT_DIR env var
- Adds update-copyright in makefile
Replaces #11947
Sister PR https://github.com/Kong/kong-ee/pull/7279
> fix(scripts): fix update-copyright in venv and remove unused repos

- .github/workflows/backport-fail-bot.yml
- .github/workflows/release-and-tests-fail-bot.yml
Miss https://github.com/Kong/kong/pull/12060
- [n/a] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
* bump actions/github-script from 6 to 7
Fix #_[FTI-5564]_
[FTI-5564]: https://konghq.atlassian.net/browse/FTI-5564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): bump actions/github-script from 6 to 7

- CHANGELOG/unreleased/kong/fix_dns_blocking.yml
- changelog/unreleased/kong/fix_dns_retry_and_timeout_handling.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua
- t/03-dns-client/01-phases.t
- t/03-dns-client/02-timer-usage.t
backport https://github.com/Kong/kong/pull/11900 and https://github.com/Kong/kong/pull/11386 to 3.3.x
> [backport -> release/3.3.x] fix(dns): Eliminate asynchronous timer in syncQuery() to prevent hang

- changelog/unreleased/kong/error_handler_494.yml
- kong/error_handlers.lua
- kong/templates/nginx_kong.lua
- spec/02-integration/05-proxy/13-error_handlers_spec.lua
fix the bug that error handler can't recognize status code 494.
There is a dedicated response body for 494 defined in error_handler. However, based on the current configuration for `error_page` in nginx-kong.conf, 494 will not be treated correctly wihout reserving it by the `=response` option in `error_page` directive. In this PR, a `error_page` configuration is added for 494 separately, so that it can be recognized in error handler, and it will be replaced with 400 finally.
FTI-5374
> fix_error_handler_494

- spec/03-plugins/15-response-transformer/01-header_transformer_spec.lua
Fix error in 01-header_transformer_spec caused by newly required constants in kong.pdk.response
> Add ngx globals to 01-header_transformer_spec setup

- .github/PULL_REQUEST_TEMPLATE.md
We enforce a `changelog` being present now. This section is superfluous now.
> chore: remove changelog from PR template

- changelog/unreleased/kong/vault-declarative.yml
- kong/init.lua
- kong/pdk/vault.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/fixtures/custom_vaults/kong/vaults/mocksocket/init.lua
- spec/fixtures/custom_vaults/kong/vaults/mocksocket/schema.lua
Cherry-picks: https://github.com/Kong/kong/pull/11843
KAG-2620
[FTI-5080](https://konghq.atlassian.net/browse/FTI-5080)
[FTI-5080]: https://konghq.atlassian.net/browse/FTI-5080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport -> release/3.4.x] fix(vault): make it possible to use vault references in declarative config (#11843)

- t/05-mlcache/02-get.t
- t/05-mlcache/03-peek.t
- t/05-mlcache/15-renew.t
Some mlcache tests were disabled because of flakiness. This commit re-enables them (hopefully this time without flakiness).
[KAG-2480](https://konghq.atlassian.net/browse/KAG-2480)
[KAG-2985](https://konghq.atlassian.net/browse/KAG-2985)
[KAG-2480]: https://konghq.atlassian.net/browse/KAG-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAG-2985]: https://konghq.atlassian.net/browse/KAG-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tests): re-enable disabled mlcache tests

- changelog/unreleased/kong/feat-add-cipher-to-the-intermediate.yml
- kong/conf_loader/constants.lua
- spec/01-unit/03-conf_loader_spec.lua
Mozilla TLS recommendations added `DHE-RSA-CHACHA20-POLY1305` cipher to intermediate in their version 5.7, see: https://wiki.mozilla.org/Security/Server_Side_TLS
KAG-3257
- ~[ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
> feat(conf): add DHE-RSA-CHACHA20-POLY1305 cipher to the intermediate configuration

- spec/02-integration/21-request-debug/01-request-debug_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/muti-external-http-calls/handler.lua
1. Increase the tolerance for upstream latency in the `upstream_span` tests, given that the timing on CI can be more variable.
2. Use `pcall` when calling `resty.http.request_uri` to prevent potential HTTP 500 errors.
_[KAG-3279]_
[KAG-3279]: https://konghq.atlassian.net/browse/KAG-3279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(request-debugging): fix flaky tests

- kong/pdk/tracing.lua
- spec/01-unit/26-tracing/01-tracer_pdk_spec.lua
An error log was printed whenever a nil attribute was set for a span. This implies every variable has to be nil-checked before it can be assigned to some span attribute. In general it feels more natural to expect that passing `nil` is accepted without producing any error log or warning.
* passing a nil value to `span:set_attribute` is a NOOP if the attribute does not already exist, else it means unsetting that attribute (just like before). Now both of these are applied silently, without printing an error.
> fix(tracing): don't print error when passing nil to span:set_attribute

- .github/workflows/backport.yml
Automated backport to release/3.2.x, triggered by a label in https://github.com/Kong/kong/pull/11924.
> [backport -> release/3.2.x] chore: improve backporting process

- .github/workflows/cherry-picks.yml
This should now correctly identify if the PR was merged using either "Squash and merge" or "Rebase and merge" and act accordingly.
Fix https://konghq.atlassian.net/browse/KAG-3198
> chore: bump cherry-pick action to 1.1.0

- .github/workflows/backport.yml
This now correctly detects the available merge strategies and adapts it's behavior accordingly.
Rebase -> Use commits from the PR
Squash -> Use the newly created, squashed commit
(Merge commit -> We don't use that in our repository.)
Fix https://konghq.atlassian.net/browse/KAG-3198
> chore: re-introduce improved backport action

- changelog/unreleased/kong/fix-cli-shdict-set-api.yml
- kong/globalpatches.lua
This commit introduces support for the exptime parameter in SharedDict:set() to align its functionality with that of the original ngx.shared.DICT.set(). And it refines the logic of SharedDict:add() by using SharedDict:set().
fix KAG-3303
> fix(globalpatches): support exptime in SharedDict:set() api

- kong/db/schema/json.lua
- kong/plugins/hmac-auth/access.lua
- kong/plugins/ldap-auth/access.lua
- kong/plugins/proxy-cache/cache_key.lua
- kong/runloop/wasm.lua
- kong/tools/utils.lua
- spec/03-plugins/20-ldap-auth/01-access_spec.lua
- spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua
Now we have separated sha256 module ,  It's time to remove the reference of `utils.lua`.
KAG-3226
> refactor(tools): remove reference of sha256 from utils

- spec/03-plugins/17-ip-restriction/02-access_spec.lua
Refactor ip-restriction test cases to address flakiness; `helpers.wait_for_invalidation` would hit a different worker than the subsequent proxy request, leading to flakiness in tests. Instead of issuing two requests, one for the Admin and another for the Proxy, wait until the proxy request returns the expected result. 
Fix KAG-3207.
> tests(plugins): refactor tests to address flakiness

- .github/workflows/release.yml
- scripts/release-kong.sh
(cherry picked from commit 851ebcf5e65d6ba12aa5026a453e10f978f95ceb)
This is the sister PRs:
- https://github.com/Kong/release-scripts/pull/108 &
- https://github.com/Kong/kong-ee/pull/7356
It will allow the `version` input to the `release.yml` workflow to be passed as a Cloudsmith tag when uploading packages (assuming it meets the criteria). This will in turn allow us to keep better track of special packages in Cloudsmith, like the recent `rc` packages.
An existing example of such a tag is the `fips` tag: https://cloudsmith.io/~kong/packages/?q=tag%3Afips
For this to work, the input must contain: `rc`,`alpha`,`beta`, or `nightly`
And cannot contain characters outside of: `a-zA-Z0-9._,`
So an input like "3.0.0.0-rc.3" will work, but an input like "3.0.0.0-gamma.5", "9.9.9.isa%is%cool", or …
> feat(gha): pass version as cloudsmith tags

- kong/resty/dns/client.lua
1. luacheck could be passed now, so we do not need to suppress its warnings.
2. `sock:connect(targetIp, targetPort, sock_opts)` could correctly deal with the nil value of `sock_opts` now.
fix KAG-3329
> style(dns): minor code style clean

- build/tests/01-base.sh
- spec/helpers/ssl.lua
Just removes some boring ssl related stuff. We don't use boring ssl anymore.
> chore(tests): remove boring ssl related tests

- spec/02-integration/02-cmd/09-prepare_spec.lua
- spec/02-integration/02-cmd/10-migrations_spec.lua
- spec/02-integration/02-cmd/11-config_spec.lua
- spec/02-integration/02-cmd/15-utils_spec.lua
- spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
- spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
- spec/02-integration/17-admin_gui/01-admin-gui-path_spec.lua
- spec/02-integration/17-admin_gui/03-reports_spec.lua
- spec/03-plugins/03-http-log/01-log_spec.lua
- spec/03-plugins/23-rate-limiting/04-access_spec.lua
- spec/03-plugins/26-prometheus/02-access_spec.lua
- spec/03-plugins/26-prometheus/04-status_api_spec.lua
- spec/03-plugins/27-aws-lambda/06-request-util_spec.lua
- spec/03-plugins/37-opentelemetry/05-otelcol_spec.lua
- spec/04-perf/01-rps/06-core_entities_crud_spec.lua
- spec/04-perf/01-rps/07-upstream_lock_regression_spec.lua
- spec/04-perf/02-flamegraph/01-simple_spec.lua
- spec/04-perf/02-flamegraph/05-prometheus.lua
- spec/04-perf/02-flamegraph/07-upstream_lock_regression_spec.lua
- spec/fixtures/https_server.lua
- spec/helpers.lua
- spec/helpers/http_mock/nginx_instance.lua
- spec/helpers/perf/charts.lua
- spec/helpers/perf/utils.lua
Due to the use of `pl.utils.execute` and `os.execute`, the execution time on both Lua code and the shell commands it launches exceeded the timeout set for the TCP connection. And as it is unable to return from Nginx C event code, it is unable to handle TCP I/O events properly. This resulted in abnormal data reception for some TCP connections.
So, except for one `pl.utils.executeex`, all occurrences of `os.execute`, `pl.utils.execute`, and `pl.utils.executeex` have been replaced with `shell.run`.
By switching to `shell.run`, the current Lua will be suspended, waiting for the command to complete, allowing Nginx's I/O events to be handled properly
KAG-3157
> fix(tests): execute all shell commands using resty.shell

- changelog/unreleased/kong/fix-declarative-config-flattened-data-loss.yml
- kong/db/errors.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
fix error data loss caused by weakly typed of function in declarative_config_flattened function
FTI-5584
> fix(dbless): fix error data loss caused by weakly typed of function  in declarative_config_flattened function

- kong/plugins/oauth2/secret.lua
- spec/03-plugins/25-oauth2/05-kdf_spec.lua
https://konghq.atlassian.net/browse/KAG-3313
> fix(oauth2): use new style KDF API to work better with FIPS mode

- kong/globalpatches.lua
For testing and CLI scenarios, we will not add timer to avoid exhausting timer resources.
1. It checks the expiration of an item when referring it instead of using timer.
2. The API `set()` returns the item now, which will be used in the API `SharedDict:incr()`.
3. It introduces a new internal API `get(data, key)` to check and retrieve non-expired items.
4. It fixes the returned ttl value to align with the `ngx.shared.DICT:ttl()` API of lua-nginx-module.
Fix KAG-3398
> fix(globalpatches): remove timer from SharedDict APIs

- .github/workflows/build_and_test.yml
- .github/workflows/update-test-runtime-statistics.yml
This commit pins Kong to the v1 release of the gateway-test-scheduler and gh-storage action.
> chore(ci): pin CI to test scheduler release v1

- .github/matrix-commitly.yml
- .github/matrix-full.yml
- build/dockerfiles/deb.Dockerfile
- changelog/unreleased/kong/debian-12-support.yml
- scripts/explain_manifest/config.py
- scripts/explain_manifest/fixtures/debian-12-amd64.txt
Build deb packages for Debian 12.
KAG-3015
> feat(cd): build debian 12 packages

- changelog/unreleased/kong/optimize_keepalive_parameters.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
Bumped default values of `nginx_http_keepalive_requests` and `upstream_keepalive_max_requests` to `10000`.
Fix KAG-3360
> perf(proxy): use more reasonable keepalive default value for Nginx tuning

- kong/globalpatches.lua
1. It implements the `get_stale` API.
2. It completes the `set` API with support for the `flags` parameter.
3. It abstracts the `is_stale` function for reuse.
4. It does not delete expired data during referring operations.
Fix KAG-3398
> fix(globalpatches): imeplement SharedDict:get_stale API

- changelog/unreleased/kong/tracing-sampling-rate-scope.yml
- kong/clustering/compat/removed_fields.lua
- kong/pdk/tracing.lua
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/opentelemetry/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/trace-propagator/handler.lua
Sampling rate can now be configured by plugin (OTel) instead of it just being a global setting
If not configured, the global setting still applies.
This also fixes a small bug where, in the edge case of opentelemetry being used for propagation only (instrumentations disabled), the `sampled` flag was incorrectly set to `true` although no span was sampled for that request.
Includes tests to cover more configuration scenarios (esp. different sampling rates) and verify propagation is done correctly.
* new configuration field for Opentelemetry: `config.sampling_rate` that allows setting sampling_rate "by plugin" instead of globally.
[KAG-3126](https://konghq.atlassian.net/browse/KAG-3126)
[KAG-3126]: https://konghq.atlassian.net/browse/KAG-3126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
> feat(opentelemetry): sampling rate configuration option

- changelog/unreleased/kong/postremove.yml
apply comment form: https://github.com/Kong/kong-ee/pull/7622#discussion_r1431765321
> chore: apply changlog comment for post remove

- kong/pdk/response.lua
- kong/pdk/service/request.lua
fix missing doc for https://github.com/Kong/kong/pull/12164
> docs(pdk): fix missing doc for set_header related pdk #12164

- changelog/unreleased/kong/default_status_port.yml.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
We now by default enable status port.
KAG-3359
> chore(core): enable status_listen by default

- .github/workflows/build_and_test.yml
- .github/workflows/update-test-runtime-statistics.yml
This is required for security compliance. Dependabot should take care of bumping in the future.
> chore(actions): pin `gateway-test-scheduler` with hash

- changelog/unreleased/kong/bump-lua-resty-healthcheck-1.5.4.yml
- changelog/unreleased/kong/bump_lua_resty_healthcheck.yml
- kong-2.8.4-0.rockspec
bump lua-resty-healthcheck to 1.5.4
https://github.com/Kong/lua-resty-healthcheck/tree/release/1.5.x#154-22-dec-2023
https://github.com/Kong/lua-resty-healthcheck/pull/147
FTI-5478
> bump: bump lua-resty-healthcheck to 1.5.4

- changelog/unreleased/kong/bump-resty-openssl-1.0.2.yml
- changelog/unreleased/kong/bump-resty-openssl.yml
- kong-3.6.0-0.rockspec
<a name="1.2.0"></a>
- **compat:** works better with plain luajit [d23b34a](https://github.com/fffonion/lua-resty-openssl/commit/d23b34ae8b3349342d5f82d90dbfe76696dd2ca4)
- **bn:** add from_mpi, to_mpi and set API [073c943](https://github.com/fffonion/lua-resty-openssl/commit/073c943bf74cce7bd6ce90ee97dfc9b753af3cf2)
- **cipher:** add set_buffer_size API [3d0a51c](https://github.com/fffonion/lua-resty-openssl/commit/3d0a51ccab0c2dd46f9eb8088fa2f767eff02a61)
- **mac:** add reset API [40fdbbb](https://github.com/fffonion/lua-resty-openssl/commit/40fdbbbddc078c01ea40b8ec8b21257d0e3fefa6)
- **openssl:** list functions can now optionally drop provider name [b36ccba](https://github.com/fffonion/lua-resty-openssl/commit/b36ccba3fce9a1b51a0bc8c23d5e9843e99a2052)
- **cipher:** improve performance …
> chore(deps): bump lua-resty-openssl to 1.2.0

- kong/router/atc.lua
- kong/router/fields.lua
- spec/02-integration/01-helpers/01-helpers_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
- spec/02-integration/05-proxy/03-upstream_headers_spec.lua
- spec/02-integration/05-proxy/14-server_tokens_spec.lua
- spec/03-plugins/07-loggly/01-log_spec.lua
- spec/03-plugins/25-oauth2/04-invalidations_spec.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
It is a succeeding of #12127.
- add `paths = { "/" }` in routes to enable calculation cache for path 
- add `perserve_host` logic for stream
KAG-3032
> fix(router): add preserve_host logic in stream subsystem

- changelog/unreleased/kong/atc_reuse_context.yml
> docs(changelog): fix a typo in #11258

- changelog/unreleased/kong/fix_req_transformer_case_sensitive.yml
- kong/plugins/request-transformer/access.lua
- spec/03-plugins/36-request-transformer/02-access_spec.lua
Request-transformer used to ignore cases when renaming header. This PR makes it case-sensitive when renaming headers.
Fix KAG-2599 #11579
> fix(plugin): request transformer to preserve header cases

- kong/plugins/hmac-auth/access.lua
- kong/plugins/jwt/jwt_parser.lua
- spec/03-plugins/19-hmac-auth/03-access_spec.lua
- spec/03-plugins/19-hmac-auth/04-invalidations_spec.lua
Replace all usage of `resty.openssl.hmac` (which binds `HMAC_*` low level APIs) with `resty.openssl.mac` in Kong.
KAG-3445
> refactor(plugins): replace usage or resty.openssl.hmac with resty.openssl.mac

- .github/workflows/openresty-patches-companion.yml
This PR adds a workflow that opens a companion PR (the link being displayed as mentioning current PR) when developer
opens a PR that modifies openresty patches.
The companion PR (like https://github.com/Kong/openresty-patches-review/pull/6) automatically creates and updates
_in-place_ when the PR at kong or kong-ee updates, and displays only the diffs for patches files to help reviewer
understand the changes better.
> feat(ci): trigger a workflow for reviewing patches

- changelog/unreleased/kong/fix_req_transformer_case_sensitive.yml
- kong/plugins/request-transformer/access.lua
- spec/03-plugins/36-request-transformer/02-access_spec.lua
This reverts commit 30154217e03d7b77675716e0728609b19518dc73.
As it did not pass the test
> Revert "fix(request-transformer): respect letter case of rename headers' new names (#12244)"

- spec/03-plugins/23-rate-limiting/02-policies_spec.lua
Clear expired key in shared dict. Otherwise, we got negative value.
```bash
~ $ resty --http-conf 'lua_shared_dict jim 1m;' -e 'local shm = ngx.shared.jim; shm:set("age", 17, 1); local v = shm:get("age"); print(v); ngx.sleep(1.001); print(shm:ttl("age"))'
17
-0.032
```
Fix #_[FTI-5674]_
[FTI-5674]: https://konghq.atlassian.net/browse/FTI-5674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(rate-limiting): clear expired key in shared dict

- .github/workflows/openresty-patches-companion.yml
Forks doesn't have access to secrets and public forks doesn't have `write` scope for the automatic tokens.
> fix(ci): skip the openresty patches workflow if it's a fork

- spec/02-integration/02-cmd/12-hybrid_spec.lua
Several of these tests contained the following assertion after generating a certificate with the `kong hybrid gen_cert` command:
```lua
assert(crt:get_not_before() >= ngx.time())
```
This produces failures every now and again when the clock has advanced _just_ enough for `ngx.time()` to return `crt:get_not_before() + 1`. To fix this, we record the time _before_ generating the cert and validate against the stored timestamp.
KAG-3464
> test(cmd): record ngx.time() before generating a cert

- .github/workflows/upgrade-tests.yml
- kong-3.3.2-0.rockspec
- kong/meta.lua
Bumping version number to 3.3.2 as part of the post-release steps for 3.3.1
This is a simple bump to the meta info on the 3.3 branch. It was stuck unmerged for months because the upgrade tests where failing. I have taken the executive decision of neutering the upgrade tests in the 3.3 branch. It is extremely unlikely that someone will want to upgrade to 3.3 in particular, given that 3.4 is LTS.
* Bump version number to 3.3.2
* Deactivate upgrade tests
> release: 3.3.2

- spec/02-integration/06-invalidations/01-cluster_events_spec.lua
Timers doe not always trigger precisely on time.
I ran the test on local env 3000 times, in 3 batches and it does not reproduce.
Then I ran it on CI looping 1000 times for each run. It failed the 2nd time on the first 2 tries and succeeded 1000 times on the 3rd try.
Timers do not always trigger at the exact precise time thus the flaky. I added a 0.5s extra delay to the sleep call and tried 3 times. It succeeded every time after the change.
Fix KAG-3224
> chore(tests): fix flaky due to too close time for a timer

- spec/helpers/http_mock.lua
- spec/helpers/http_mock/template.lua
Cheery-picking the change from https://github.com/Kong/kong-ee/pull/7627/
> feat(tests): improve http_mock

- kong/globalpatches.lua
This is necessary because EE has changed `package.path` in this closure, and if we continue leave that in the top-level scope of this file, EE's e2e test will report the following error:
```
/usr/local/share/lua/5.1/kong/constants.lua:8: in main chunk
[C]: in function 'require'
/usr/local/share/lua/5.1/kong/globalpatches.lua:8: in main chunk
[C]: in function 'require'
/usr/local/bin/kong:6: in function 'file_gen'
init_worker_by_lua(nginx.conf:118):46: in function <init_worker_by_lua(nginx.conf:118):44>
init_worker_by_lua(nginx.conf:118):53: in function <init_worker_by_lua(nginx.conf:118):51>
```
- NA The Pull Request has tests
- NA A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if …
> chore(globalpatches): moved `require kong.constants` to the closure

- changelog/unreleased/kong/default_status_port.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
- spec/02-integration/08-status_api/04-config_spec.lua
- spec/fixtures/default_status_listen.conf
- spec/kong_tests.conf
Redoing https://github.com/Kong/kong/pull/12254
KAG-3359
> feat(core): enable status api by default

- changelog/unreleased/kong/standardize-redis-conifguration-response-rl.yml
- kong-3.6.0-0.rockspec
- kong/clustering/compat/checkers.lua
- kong/plugins/response-ratelimiting/clustering/compat/redis_translation.lua
- kong/plugins/response-ratelimiting/migrations/001_350_to_360.lua
- kong/plugins/response-ratelimiting/migrations/init.lua
- kong/plugins/response-ratelimiting/policies/init.lua
- kong/plugins/response-ratelimiting/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
- spec/03-plugins/24-response-rate-limiting/01-schema_spec.lua
- spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
- spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
- spec/05-migration/plugins/response-ratelimiting/migrations/001_350_to_360_spec.lua
Response-RateLimiting right now has new config structure that reuses common redis connection configuration.
Many plugins differ in the way Redis is configured. The goal of this PR is to introduce a standard Redis config schema that could be shared across plugins.
This is the last in the chains of PRs that standardize Redis configuration. 
1. ACME: https://github.com/Kong/kong/pull/12300
2. RateLimiting: https://github.com/Kong/kong/pull/12301 
3. Response-RateLimiting: (this PR)
KAG-3388
> chore(response-rl): standarize redis configuration

- kong/router/atc.lua
- spec/01-unit/08-router_spec.lua
- spec/02-integration/01-helpers/01-helpers_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
- spec/02-integration/05-proxy/03-upstream_headers_spec.lua
- spec/02-integration/05-proxy/14-server_tokens_spec.lua
- spec/03-plugins/03-http-log/01-log_spec.lua
- spec/03-plugins/07-loggly/01-log_spec.lua
- spec/03-plugins/13-cors/01-access_spec.lua
- spec/03-plugins/25-oauth2/04-invalidations_spec.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
> fix(router): always calculate `match_t.upstream_uri` to avoid wrong cache

- kong/tools/cjson.lua
Simplify the implementation of #12019.
> style(tools): simplify the implementation of tools.cjson

- kong/router/atc.lua
- kong/tools/request_aware_table.lua
The value of `is_not_debug_mode` depends on `kong.configuration.log_level`,
which may be unavailable when the module is required.
This PR sets the value of `is_not_debug_mode` in the first call of `new()`.
> refactor(tools): rework `is_not_debug_mode` flag of  request aware table

- .github/labeler.yml
This sets up automation for the new `core/wasm` label.
> chore(ci): add labeler config for core/wasm

- kong/db/schema/init.lua
- kong/plugins/acme/schema.lua
- kong/plugins/acme/storage/config_adapters/redis.lua
- kong/plugins/rate-limiting/policies/init.lua
- kong/plugins/rate-limiting/schema.lua
- kong/plugins/response-ratelimiting/policies/init.lua
- kong/plugins/response-ratelimiting/schema.lua
- spec/03-plugins/23-rate-limiting/01-schema_spec.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
- spec/03-plugins/24-response-rate-limiting/01-schema_spec.lua
- spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
- spec/03-plugins/29-acme/05-redis_storage_spec.lua
ACME, RateLimiting and Response-RateLimiting now use the same redis configuration structure. The olds fields were left in place to maintain backwards compatibility. When resolving the configuration we looked into new fields and if they were empty then fallback to legacy fields. Unfortunately the new fields have their defaults as well which get written into db - so at the time of plugin resolution we'd have to implement complex logic to figure out if the new value came from user or from defualt.
This approach removes the olds fields and uses shorthands to maintain backwards compatibility.
KAG-3388
> fix(plugins): fix competing redis configs

- kong/clustering/data_plane.lua
This branch of logic was mistakenly removed in
0f95ffc0943da16e0588ae35b6054bb54a1fac51 / #12282.
No changelog entry is required because the defect fixed by this PR has never been released.
> fix(clustering): restore immediate ping behavior on config update

- changelog/unreleased/kong/declarative_config_fix.yml
- kong/db/declarative/import.lua
- kong/db/schema/init.lua
- kong/db/strategies/off/init.lua
- spec/01-unit/01-db/11-declarative_lmdb_spec.lua
- spec/02-integration/20-wasm/09-filter-meta_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/preserve-nulls/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/preserve-nulls/schema.lua
Current declarative config uncondtionally removes nulls before loading into LMDB, which would reset relavant config fields to their default values.
If their default values are `nil` and the code fails to dectect it, Kong will error! For example, config update may not be applied to core entities or plugins.
This PR removes nulls only if relevant schemas have transformations defined, and restore those nulls after transformation. Therefore, when loaded, entities preserve their nulls.
This fix does not prevent other components removing nulls accidentally. So please always check both `nil` and `null` for code robustness.
This PR will skip transformations if there is not transformation defitions. As most schemas do not have transformations, this would greatly improve performance.
Addtionally, …
> fix(core): remove and restore nulls before and after transformations

- build/openresty/patches/ngx_lua-0.10.25_01-dyn_upstream_keepalive.patch
- changelog/unreleased/kong/balancer_respect_max_retries.yml
- spec/02-integration/05-proxy/10-balancer/08-retries_spec.lua
In the balancer phase, when obtaining a connection from the upstream connection pool, the `cached` attribute of the peer connection is set to 1(`pc->cached = 1;`), indicating that the connection is obtained from the cache.
If an error occurs during the use of this connection, such as "upstream prematurely closed connection" the system will increase the `tries` attribute of the peer connection by executing `u->peer.tries++`.
`tries` represents the maximum number of attempts to connect to an upstream server. It is equal to the normal 1 attempt + `retries` (default value is 5) = 6.
The occurrence of `u->peer.tries++` is unexpected and it results in the actual retry count exceeding 6 in worst cases.
This PR restores tries by callbacks to the balancer when `u->peer.tries++` is unexpectedly …
> fix(balancer): respect max retries

- kong.conf.default
It seems that proxy_protocol is another value that can be added to the status_listen property, however it was unlisted earlier. Adding it here so customers know status_listen can utilize the proxy protocol. This stems from a support case.
Support case 00040675.
> docs(kong.conf.default): add proxy_protocol to status_listen property

- changelog/unreleased/kong/fix_malloc_assertion_error.yml
- spec/01-unit/11-reports_spec.lua
- spec/fixtures/template_inject/nginx_kong_test_tcp_echo_server_custom_inject_stream.lua
- spec/helpers.lua
Due to many OpenSSL objects are not thread-safe (https://www.openssl.org/docs/faq.html) and it causes intermittent crash when those objects are used in thread based tcp server. Replace it with process based tcp server resolves this error.
This change only replaces the thread tcp server usage in 11-reports_spec.lua file to keep the scope small.
Before this fix, crash like "malloc_consolidate(): unaligned fastbin chunk detected." happens when running spec/01-unit/11-reports_spec.lua about 200 times.
After this fix, there is no crash after running the same test suites more than 5000 times.
Fix #_[KAG-3241]_
[KAG-3241]: https://konghq.atlassian.net/browse/KAG-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(tests): fix malloc assertion error by replacing thread tcp server.

- build/openresty/patches/ngx_lua-0.10.25_01-dyn_upstream_keepalive.patch
- changelog/unreleased/kong/balancer_respect_max_retries.yml
- spec/02-integration/05-proxy/10-balancer/08-retries_spec.lua
this is a backport form https://github.com/Kong/kong/pull/12346
> [backport -> release/3.4.x] fix(balancer): respect max retries (#12346)

- build/openresty/patches/ngx_lua-0.10.25_01-dyn_upstream_keepalive.patch
- changelog/unreleased/kong/balancer_respect_max_retries.yml
- spec/02-integration/05-proxy/10-balancer/08-retries_spec.lua
this is a backport form https://github.com/Kong/kong/pull/12346
> [backport -> release/3.5.x] fix(balancer): respect max retries (#12346)

- changelog/unreleased/kong/basic_www_authenticate.yml
- kong/plugins/basic-auth/access.lua
- kong/plugins/basic-auth/schema.lua
- spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua
- spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
- spec/03-plugins/10-basic-auth/03-access_spec.lua
- spec/03-plugins/10-basic-auth/05-declarative_spec.lua
When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Basic auth was missing this header on some responses. Previously it only returned this header when `Authorization` or `Proxy-Authorization` was missing but the RFC states that it should return it for every 401 response. This PR also adds a possibility to configure a parameter - realm (defaults to `service`).
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11820
- https://github.com/Kong/kong/pull/11833
- add `WWW-Authenticate` header to all …
> fix(basic-auth): add missing www-authenticate headers

- build/README.md
- build/kong_bindings.bzl
- build/openresty/wasmx/wasmx_repositories.bzl
- changelog/unreleased/kong/fix-wasm-module-branch.yml
To improve the development and testing experience of the integration between Kong and Wasmx, the `NGX_WASM_MODULE_BRANCH` environment variable should be used to overwrite the `ngx_wasm_module` branch/commit in the `.requirements` file, as it is documented in `build/README.md`. But this variable was being ignored by the build system.
KAG-3396
> fix(build): use NGX_WASM_MODULE_BRANCH environment variable

- .github/labeler.yml
- changelog/unreleased/kong/add-ai-prompt-decorator-plugin.yml
- kong-3.6.0-0.rockspec
- kong/constants.lua
- kong/plugins/ai-prompt-decorator/handler.lua
- kong/plugins/ai-prompt-decorator/schema.lua
- spec/01-unit/12-plugins_order_spec.lua
- spec/03-plugins/41-ai-prompt-decorator/00-config_spec.lua
- spec/03-plugins/41-ai-prompt-decorator/01-unit_spec.lua
- spec/03-plugins/41-ai-prompt-decorator/02-integration_spec.lua
This commit offers another plugin that extends the functionality of "AI Proxy" in #12207.
It adds an array of "llm/v1/chat" messages to either the **front** or **end** of a caller's chat history.
This allows for complex prompt-engineering on behalf of the caller.
This reason for its development, is that many of our users would like to set up specific prompt history, words, phrases, or otherwise more tightly control how an AI / LLM model is used, if being called via Kong, and this applies especially with the `AI Proxy` plugin that will simplify this process.
> feat(plugins): ai-prompt-decorator-plugin

- build/openresty/patches/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch
- changelog/unreleased/kong/balancer_respect_max_retries.yml
- spec/02-integration/05-proxy/10-balancer/08-retries_spec.lua
this is a backport form https://github.com/Kong/kong/pull/12346
> [backport -> release/3.3.x] fix(balancer): respect max retries (#12346)

- build/openresty/patches/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch
- changelog/unreleased/kong/balancer_respect_max_retries.yml
- spec/02-integration/05-proxy/10-balancer/08-retries_spec.lua
this is a backport form https://github.com/Kong/kong/pull/12346
> [backport -> release/3.2.x] fix(balancer): respect max retries (#12346)

- build/openresty/patches/ngx_lua-0.10.20_02-dyn_upstream_keepalive.patch
- changelog/unreleased/kong/balancer_respect_max_retries.yml
- spec/02-integration/05-proxy/10-balancer/08-retries_spec.lua
this is a backport form #12346
> [backport -> release/2.8.x] fix(balancer): respect max retries (#12346)

- kong/db/schema/entities/routes.lua
- kong/router/fields.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
- spec/01-unit/08-router_spec.lua
[KAG-3604]
[KAG-3604]: https://konghq.atlassian.net/browse/KAG-3604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(router/atc): support field `http.path.segments.len`

- spec/01-unit/08-router_spec.lua
Tests for #12283.
[KAG-3351]
[KAG-3351]: https://konghq.atlassian.net/browse/KAG-3351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(router): ensure uri is normalized when using segments

- kong/pdk/request.lua
- kong/plugins/oauth2/access.lua
- kong/runloop/handler.lua
- kong/tools/http.lua
- t/01-pdk/04-request/13-get_header.t
It is a fixing PR for #12327.
KAG-3570
> fix(pdk): get the first http header value after bumping to OpenResty 1.25.3.1

- .github/labeler.yml
- changelog/unreleased/kong/add-ai-prompt-template-plugin.yml
- kong-3.6.0-0.rockspec
- kong/constants.lua
- kong/plugins/ai-prompt-template/handler.lua
- kong/plugins/ai-prompt-template/schema.lua
- kong/plugins/ai-prompt-template/templater.lua
- spec/01-unit/12-plugins_order_spec.lua
- spec/03-plugins/43-ai-prompt-template/01-unit_spec.lua
- spec/03-plugins/43-ai-prompt-template/02-integration_spec.lua
This plugin adds the ability to provide tuned AI prompts to users, who only need to fill in the blanks with variable placeholders (in moustache format: `{{variable}}` )
**It is to be used in conjunction with `ai-proxy` plugin, as with other AI Family plugins.**
[AI-Proxy plugin](https://github.com/Kong/kong/pull/12207)
This allows prompt tuning to be started, or performed, by the experience LLM users in an organisation, and then consumed by anyone.
When activated, it looks for template references in the following forms:
**Chat:**
```json
{
"messages": "{template://developer-chat}",
"properties": {
"language": "python",
"program": "flask web server"
}
}
```
**Prompt:**
```json
{
"prompt": "{template://developer-prompt}",
"properties": {
"language": "python",
"program": "flask web server"
} …
```
> feat(plugins): ai-prompt-template plugin

- .github/workflows/build.yml
- .github/workflows/build_and_test.yml
- .github/workflows/perf.yml
The v4 version causes issues in EE, so we decided to stay on v3 for now.
Reverts 9cf81aba64
> chore(ci): revert upload/download-artifact version bump to v4

- kong/plugins/acme/schema.lua
- kong/plugins/rate-limiting/schema.lua
- kong/plugins/response-ratelimiting/schema.lua
Shorthand fields even though are transient still use validation. For a string field if it's minimum length is not defined then the default is 1 to disallow empty strings.
However for some of the fields underneath shorthand fields we wanted to allow empty strings therefore we need to add this `len_min=0` to those string fields that can be empty.
KAG-3388
> fix(plugins): add len_min=0 for string fields

- .github/labeler.yml
- changelog/unreleased/kong/add-ai-prompt-guard-plugin.yml
- kong-3.6.0-0.rockspec
- kong/constants.lua
- kong/plugins/ai-prompt-guard/handler.lua
- kong/plugins/ai-prompt-guard/schema.lua
- spec/01-unit/12-plugins_order_spec.lua
- spec/03-plugins/42-ai-prompt-guard/00_config_spec.lua
- spec/03-plugins/42-ai-prompt-guard/01_unit_spec.lua
- spec/03-plugins/42-ai-prompt-guard/02-integration_spec.lua
This commit offers another plugin that extends the functionality of "AI Proxy" in #12207.
It compares the user's `llm/v1/chat` or `llm/v1/completions` request against a series of regular expressions, in two config arrays:
- Allow
- Deny
If the request matches **any** regex pattern in deny, the caller is 400'd.
If any **allow** is specified, by the request matches none of them, the caller is also 400'd.
Engineering design document is available for this feature, but it is quite simple. Comprehensive tests supplied.
This reason for its development, is that many of our users would like to block specific prompts, words, phrases, or otherwise more tightly control how an AI / LLM model is used, if being called via Kong, and this applies especially with the `AI Proxy` plugin that will simplify …
> feat(plugins): ai-prompt-guard-plugin

- .github/labeler.yml
- changelog/unreleased/kong/add-ai-prompt-guard-plugin.yml
- kong-3.6.0-0.rockspec
- kong/constants.lua
- kong/plugins/ai-prompt-guard/handler.lua
- kong/plugins/ai-prompt-guard/schema.lua
- spec/01-unit/12-plugins_order_spec.lua
- spec/03-plugins/42-ai-prompt-guard/00_config_spec.lua
- spec/03-plugins/42-ai-prompt-guard/01_unit_spec.lua
- spec/03-plugins/42-ai-prompt-guard/02-integration_spec.lua
Automated backport to `release/3.6.x`, triggered by a label in #12341.
This commit offers another plugin that extends the functionality of "AI Proxy" in #12207.
It compares the user's `llm/v1/chat` or `llm/v1/completions` request against a series of regular expressions, in two config arrays:
- Allow
- Deny
If the request matches **any** regex pattern in deny, the caller is 400'd.
If any **allow** is specified, by the request matches none of them, the caller is also 400'd.
Engineering design document is available for this feature, but it is quite simple. Comprehensive tests supplied.
This reason for its development, is that many of our users would like to block specific prompts, words, phrases, or otherwise more tightly control how an AI / LLM model is used, if being called via Kong, and …
> [backport -> release/3.6.x] feat(plugins): ai-prompt-guard-plugin #12337 

- changelog/unreleased/kong/bump-lua-resty-aws-1.3.6.yml
- kong-3.6.0-0.rockspec
- fix: validator failure for some field types
> chore(deps): bump lua-resty-aws from 1.3.5 to 1.3.6

- Makefile
- Support NO_COLOR environment variable — @ligurio
- Update SILE builtin with more allowed variables — @alerque
> chore(deps): bump luacheck from 1.1.1 to 1.1.2 (dev dep)

- .github/matrix-full.yml
- .requirements
- BUILD.bazel
- build/openresty/BUILD.openresty.bazel
- build/openresty/brotli/brotli_repositories.bzl
- build/openresty/repositories.bzl
- changelog/unreleased/kong/bump_ngx_brotli.yml
- scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/el9-arm64.txt
1. bump `ngx_brotli` version to master branch https://github.com/google/ngx_brotli
2. disable `ngx_brotli` feature in rhel7 rhel9-arm64 and amazonlinux-2023-arm64 regarding to toolchain error.
FTI-5706
> bump(deps): bump ngx_brotli version to master branch

- kong/plugins/acme/schema.lua
- kong/tools/redis/schema.lua
- spec/01-unit/30-standardized_redis_config_spec.lua
- spec/02-integration/02-cmd/11-config_spec.lua
- spec/03-plugins/29-acme/04-schema_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/redis-dummy/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/redis-dummy/schema.lua
The default port should be 6379. This was how `rate-limiting` and `response-ratelimiting` worked before Redis config standardization. The bug was introduced because `acme` Redis configuration was used as reference which did not have default for Redis port.
KAG-3618
> fix(redis): add default port for standardized Redis config

- changelog/unreleased/kong/wasm-attach.yml
- kong/runloop/wasm.lua
`kong.runloop.wasm.attach()` may be called more than once when filters utilize the `dispatch_http_call` proxy-wasm SDK function. Previously this was assumed to be false, which can yield errors like this one:
> 2024-01-22 16:39:16 2024/01/22 22:39:16 [crit] 2464#0: *340 [lua] wasm.lua:790: attach(): failed attaching service(6bc44ccb-30c9-5f3d-acfa-017fa1b2ef82) filter chain to request: previous plan already attached, client: 172.17.0.1, server: kong, request: "GET /anything HTTP/1.1", host: "localhost:8000", request_id: "112ec236dcf487391a579a6f6f63fc0b"
This adds a `ngx.ctx` check and avoids calling `proxy_wasm.attach()` in this case.
Unfortunately it is incredibly non-trivial to add a test case for this at the moment, but the behavior change/correctness has been validated by hand. …
> fix(wasm): do not call attach() on re-entrancy

- changelog/unreleased/kong/enhance_admin_api_auth_error_response.yml
- kong/plugins/basic-auth/access.lua
- kong/plugins/key-auth/handler.lua
- kong/plugins/ldap-auth/access.lua
- spec/02-integration/02-cmd/03-reload_spec.lua
- spec/03-plugins/09-key-auth/02-access_spec.lua
- spec/03-plugins/10-basic-auth/03-access_spec.lua
- spec/03-plugins/10-basic-auth/05-declarative_spec.lua
- spec/03-plugins/20-ldap-auth/01-access_spec.lua
Unifying error responses when admin authentication via Admin/Portal API is failed. 
Cherry-picks: https://github.com/Kong/kong-ee/pull/6552
Fix SEC-912 / KAG-1672
> fix(plugins): consistent error responses upon Admin API auth failures

- kong/router/fields.lua
Just a small refactor of code to use static functions.
> perf(router): use static functions for callbacks
