- build/openresty/pcre/BUILD.pcre.bazel
PCRE2 requires JIT support to be explicitly enabled during build. From https://pcre.org/current/doc/html/pcre2jit.html:
"JIT support is an optional feature of PCRE2. The "configure" option --enable-jit (or equivalent CMake option) must be set when PCRE2 is built if you want to use JIT."
Without the flag in this commit, Kong logs display several entries containing failures in `pcre2_jit_compile`, such as
```
2024/01/30 16:25:20 [info] 747309#0: pcre2_jit_compile() failed: -45 in "^\s*HTTP/1\.1\s+", ignored
```
> hotfix(deps): enable JIT support for pcre2

- build/openresty/patches/ngx_lua-0.10.26_01-dyn_upstream_keepalive.patch
address comments of https://github.com/Kong/kong/pull/12346
> fix(balancer): ensure the `notify` callback is invoked only if defined when handling cached connection errors

- changelog/unreleased/kong/otel-increase-queue-max-batch-size.yml
- kong/plugins/opentelemetry/schema.lua
The max batch size for Opentelemetry was set to the default value: 1 the value actually refers to the number of spans in a batch, so we are increasing the default value to 200 which corresponds to what the default value used to be with the "old" queue implementation.
https://konghq.atlassian.net/browse/KAG-3173
> perf(opentelemetry): increase queue max batch size

- kong/plugins/ai-proxy/handler.lua
Logic error - with non-200 responses from the LLM, I was double-gzip'ing the response messages (if there was `content-encoding: gzip` header present).
This is a quick fix for it before 3.6.0 release, and this whole response phase can be refactored during the tech preview phase.
Bug discovery during field testing.
> fix(ai-proxy): do not double-gzip responses when status is not 200

- changelog/unreleased/kong/fix_privileged_agent_id_1.yml
- kong/api/routes/kong.lua
- kong/clustering/control_plane.lua
- kong/plugins/acme/handler.lua
- kong/plugins/statsd/log.lua
- kong/runloop/handler.lua
- kong/runloop/log_level.lua
- kong/runloop/plugin_servers/pb_rpc.lua
- spec/02-integration/20-wasm/05-cache-invalidation_spec.lua
By default, `ngx.worker.id()` returns `nil` for the privileged agent. Now Fall back to -1 as the worker ID of privileged agent worker to avoid error. Keep consistent with code like https://github.com/Kong/kong/blob/0ff50d5237d16b7f3535d57e9ef63dfd603ac62a/kong/globalpatches.lua#L427
Fix #_[FTI-5707]_
[FTI-5707]: https://konghq.atlassian.net/browse/FTI-5707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(core): set worker ID of privileged agent to -1

- README.md
Adding highlights for then upcoming AI Gateway capabilities in the `README.md`.
> docs(readme/features): adding AI gateway highlights

- Makefile
bump h2client version to v0.4.4 due to http2 test case failed.
> bump: bump h2client version to v0.4.4

- changelog/unreleased/kong/otel-increase-queue-max-batch-size.yml
- kong/plugins/opentelemetry/schema.lua
backport of https://github.com/Kong/kong/pull/12488
The max batch size for Opentelemetry was set to the default value: 1 the value actually refers to the number of spans in a batch, so we are increasing the default value to 200 which corresponds to what the default value used to be with the "old" queue implementation.
KAG-3173
> [backport -> release/3.3.x] perf(opentelemetry): increase max batch size (#12488)

- CHANGELOG/unreleased/kong/11515.yaml
- CHANGELOG/unreleased/kong/optimize_keepalive_parameters.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
- spec/01-unit/04-prefix_handler_spec.lua
backport https://github.com/Kong/kong/pull/12223
also backport this PR: https://github.com/Kong/kong-ee/pull/6507
Bumped default values of `nginx_http_keepalive_requests` and `upstream_keepalive_max_requests` to `10000`.
Fix KAG-3360
> [backport -> release/2.8.x] perf(proxy): use more reasonable keepalive default value for Nginx tuning

- kong/db/dao/init.lua
- kong/db/dao/plugins.lua
- kong/db/schema/init.lua
- kong/db/schema/metaschema.lua
- kong/plugins/acme/schema.lua
- kong/plugins/rate-limiting/schema.lua
- kong/plugins/response-ratelimiting/schema.lua
- kong/tools/table.lua
- spec/01-unit/05-utils_spec.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
- spec/03-plugins/23-rate-limiting/06-shorthand_fields_spec.lua
- spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
- spec/03-plugins/24-response-rate-limiting/06-shorthand_fields_spec.lua
- spec/03-plugins/29-acme/05-redis_storage_spec.lua
- spec/03-plugins/29-acme/07-shorthand_fields_spec.lua
Shorthand fields are stripped out of response but we're using them when we want to rename some of the fields. This commit adds an option `expand_shortfields` as well as some some options to `shorthand_fields` schema that would allow us to include them back in the schema while using the latest data
KAG-3677
> fix(dao): allow shorthand fields to be in response

- kong/db/dao/init.lua
- kong/db/dao/plugins.lua
- kong/db/schema/init.lua
- spec/02-integration/03-db/14-dao_spec.lua
- spec/03-plugins/23-rate-limiting/06-shorthand_fields_spec.lua
- spec/03-plugins/24-response-rate-limiting/06-shorthand_fields_spec.lua
This commits adds shorthand expansions for `select_by_` / `update_by_` etc. methods
KAG-3686
> fix(dao): add missing shorthand fields expansions

- kong-3.6.1-0.rockspec
- kong/meta.lua
> chore(release): update version to 3.6.1 as part of the GA release

- .github/workflows/cherry-picks.yml
Applies an `incomplete-cherry-pick` label to the original PR if a cherry-pick fails to be created.
Fix: [konghq.atlassian.net/browse/KAG-3590](https://konghq.atlassian.net/browse/KAG-3590)
> chore: apply label on failed cherry-pick

- .github/workflows/backport.yml
Applies an incomplete-backport label to the original PR if at least one backport fails to be created.
Fix: https://konghq.atlassian.net/browse/KAG-3590
> chore: apply label on failed backport

- changelog/unreleased/kong/fix-vault-workspaces.yml
- kong/pdk/vault.lua
In FTI-5762 it was reported that there is a problem with secret rotation when vaults are stored inside a workspace. This commit will fix it by passing `workspace = null` aka making a call a global call which will not then use the possibly incorrect workspace (default) to find vault entity (the vault config). The vault entity prefix is unique across workspaces.
Fix FTI-5762
> fix(vault): use global query when finding a vault by prefix

- kong/conf_loader/parse.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
The #12420 by @Water-Melon forgot to add `grpc_ssl_conf_command`. This commit adds that.
[KAG-3259](https://konghq.atlassian.net/browse/KAG-3259)
[KAG-3259]: https://konghq.atlassian.net/browse/KAG-3259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(conf): enable grpc_ssl_conf_command too

- spec/02-integration/07-sdk/03-cluster_spec.lua
- spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua
- spec/03-plugins/38-ai-proxy/04-cohere_integration_spec.lua
- spec/03-plugins/38-ai-proxy/05-azure_integration_spec.lua
- spec/03-plugins/38-ai-proxy/06-mistral_integration_spec.lua
- spec/03-plugins/38-ai-proxy/07-llama2_integration_spec.lua
- spec/03-plugins/38-ai-proxy/08-encoding_integration_spec.lua
- spec/03-plugins/39-ai-request-transformer/01-transformer_spec.lua
- spec/03-plugins/39-ai-request-transformer/02-integration_spec.lua
- spec/03-plugins/40-ai-response-transformer/01-transformer_spec.lua
- spec/03-plugins/40-ai-response-transformer/02-integration_spec.lua
The [dynamic test scheduler](https://github.com/Kong/kong/pull/12286) exposed some issues by disrupting the order of the tests, some of which did not initialize the database or wrote incompatible data to the database, causing the Gateway instance to fail to start and causing the following test to fail.
* `spec/03-plugins/39-ai-request-transformer/01-transformer_spec.lua`
* `spec/03-plugins/40-ai-response-transformer/01-transformer_spec.lua`
These two test sets start a Gateway instance to launch a mocking server, which can be replaced by the `spec.helpers.http_mock`.
* `spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua`
Since the test sequence is disrupted and the port release is not real-time, this may cause the port to be occupied to the point where the test fails.
- [N/A] The …
> tests: fix flakiness

- changelog/unreleased/kong/optimize_keepalive_parameters.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
Bumped default values of `nginx_http_keepalive_requests` and `upstream_keepalive_max_requests` to `10000`.
backport https://github.com/Kong/kong/pull/12223
Fix [KAG-3360](https://konghq.atlassian.net/browse/KAG-3360)
[KAG-3360]: https://konghq.atlassian.net/browse/KAG-3360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport -> release/3.5.x] perf(proxy): use higher default keepalive request value for Nginx tuning (#12223)

- changelog/unreleased/kong/fix-vault-init-worker.yml
- kong/db/schema/init.lua
- kong/pdk/vault.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
It was reported on KAG-2907 that existing LMDB database with secrets can lead to an error when resolving secrets on init worker:
```
resty/http.lua:74: API disabled in the context of init_worker_by_lua*
[C]: in function 'co_create'
```
This fixes the issue by postponing the resolving to a timer.
https://konghq.atlassian.net/browse/KAG-2907
> fix(vault): postpone vault reference resolving on init_worker

- changelog/unreleased/kong/plugin_server_restart.yml
- kong/runloop/plugin_servers/mp_rpc.lua
- kong/runloop/plugin_servers/pb_rpc.lua
The bug was introduced when refactoring/cherry-picking. We missed the `mp_rpc.lua`. The PR also syncs the changes made to EE branches.
**DO NOT CHEERY-PICK THIS TO EE**.
Fix #12364
Fix KAG-3765
> fix(core): fix an issue where Kong do not handle properly when Python and Javascript plugin server crashes

- kong/conf_loader/parse.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
#12548 
The #12420 by @Water-Melon forgot to add `grpc_ssl_conf_command`. This commit adds that.
Signed-off-by: Aapo Talvensaari <aapo.talvensaari@gmail.com>
(cherry picked from commit 84cb1be01d8e9a241e8a2b3afd6d55bb184e605b)
> [backport -> release/3.6.x] chore(conf): enable grpc_ssl_conf_command too (#12548)

- kong/conf_loader/init.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
#12548 
The #12420 by @Water-Melon forgot to add `grpc_ssl_conf_command`. This commit adds that.
Signed-off-by: Aapo Talvensaari <aapo.talvensaari@gmail.com>
(cherry picked from commit 84cb1be01d8e9a241e8a2b3afd6d55bb184e605b)
> [backport -> release/3.4.x] Backport 12548 to release/3.4.x

- kong/conf_loader/init.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
#12548 
The #12420 by @Water-Melon forgot to add `grpc_ssl_conf_command`. This commit adds that.
Signed-off-by: Aapo Talvensaari <aapo.talvensaari@gmail.com>
(cherry picked from commit 84cb1be01d8e9a241e8a2b3afd6d55bb184e605b)
> [backport -> release/3.5.x] Backport 12548 to release/3.5.x

- spec/02-integration/13-vaults/06-refresh-secrets_spec.lua
- spec/03-plugins/39-reconfiguration-completion/01-access_spec.lua
- spec/03-plugins/39-reconfiguration-completion/02-helper_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/reconfiguration-completion/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/reconfiguration-completion/schema.lua
- spec/helpers.lua
Unlike the previous implementation, this one does not require changes
to Kong and its proxy path.  It works based on the assumption that the
order of admin API changes is preserved.  The admin API client marks
the end of the changes that it needs to see propagated to the data
plane(s) by changing the configuration of this plugin, setting a
particular configuration version number.  On the proxy path, a header
X-Kong-Configuration-Version is sent with that version number.  The
plugin's access handler verifies that the version number configured in
the plugin (on the dataplane) matches the version number requested by
the client.  If the version numbers do not match, a 503 error is
generated, which causes the client to retry.
The plugin is available only to busted tests.  It needs to be …
> feat(test): add reconfiguration completion detection plugin

- spec/02-integration/01-helpers/04-redis_helper_spec.lua
- spec/03-plugins/23-rate-limiting/04-access_spec.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
- spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
- spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
- spec/helpers/redis_helper.lua
In tests there was a lot of code duplication related to redis connection, user adding, removing and db flushing. This commits extracts all of this code to redis_helper
KAG-2130
> chore(tests): remove redis code duplication in specs

- changelog/unreleased/kong/decrease-cocurrency-limit-of-timer-ng.yml
- kong/globalpatches.lua
Too high concurrency setting might make Kong throws error at the runtime.
_[KAG-3779], [FTI-5780]_
[KAG-3779]: https://konghq.atlassian.net/browse/KAG-3779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FTI-5780]: https://konghq.atlassian.net/browse/FTI-5780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(timer-ng): decrease the minimum/maximum threads

- changelog/unreleased/kong/set_grpc_tls_seclevel.yml
Update changelog for gRPC TLS seclevel change. The original PR is #12548.
Set security level of gRPC's TLS to `0` when `ssl_cipher_suite` is set to `old`.
KAG-3259
> chore(changelog): update changelog for gRPC TLS seclevel change

- changelog/unreleased/kong/set_grpc_tls_seclevel.yml
> [backport -> release/3.4.x] Backport 12613 to release 3.4.x

- changelog/unreleased/kong/set_grpc_tls_seclevel.yml
> [backport -> release/3.5.x] Backport 12613 to release 3.5.x

- changelog/unreleased/kong/set_grpc_tls_seclevel.yml
> [backport -> release/3.6.x] Backport 12613 to release 3.6.x

- changelog/unreleased/kong/fix_api_405_vaults_validate_endpoint.yml
- kong/api/routes/kong.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
This fixes an issue where calling the endpoint `POST /schemas/vaults/validate`
was conflicting with the endpoint `/schemas/vaults/:name` which only
has GET implemented, hence resulting in a 405.
By explicting defining a new endpoint `/schemas/vaults/validate`, Lapis
framework should take care of always choosing it over `/schemas/vaults/:name`.
Fix KAG-3699
> fix(api): avoid returning 405 on /schemas/vaults/:name

- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
- spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
There were a lot of checks for redis version being at least 6.0.0 It's been 4 years since redis 6.0.0 release and we don't test against lower versions anymore (as far as I checked) so these `if`s are no longer needed.
I highly recommend viewing the diff with _Hide whitespace_ setting turned on.
KAG-2130
> chore(tests): remove redis >= v6 checks in tests

- kong/router/fields.lua
This PR changes `assert` to `error` and moves it into the function `get_field_accessor()`, 
which is a non-hot path,
so we will remove this cost when finding the func in hash table. 
KAG-3634
> refactor(router/atc): move assert to unlikely path

- changelog/unreleased/kong/fix-missing-router-section-of-request-debugging.yml
- kong/timing/init.lua
- spec/02-integration/21-request-debug/01-request-debug_spec.lua
<del>## Blocked by https://github.com/Kong/kong/pull/12580</del>
We have already added calls of the hook to measure the time consumed by the router.
https://github.com/Kong/kong/blob/f7e6eeefe006af11129d1b0e39a1c06449a53d42/kong/runloop/handler.lua#L1152-L1162
But forgot to setup the hook function, this PR setups the hook function for the router.
And also fix some tests that might cause flakiness.
_[KAG-3438]_
[KAG-3438]: https://konghq.atlassian.net/browse/KAG-3438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(request-debugging): add missing `router` section of the timing output

- kong/db/schema/entities/routes.lua
`validate_route()` only works with `traditional_compatible` and `expressions` routes
> refactor(db/schema): do not generate validator of router expression for non-traditional flavors

- changelog/unreleased/kong/fix-default-value-of-upstream-keepalive-max-requests.yml
- kong.conf.default
This commit fixes the discrepancy between the default value `1000` of upstream_keepalive_max_requests in the Kong.conf comments and the actual value `10000` in kong/templates/kong_defaults.lua.
> fix(kong.conf.default): fix the default value of `upstream_keepalive_max_requests`

- kong/router/atc.lua
- kong/router/compat.lua
As #12467 did, remove some tail return NYI to be more JIT-friendly.
KAG-3634
> refactor(router/atc): remove tail calls to avoid NYIs

- kong/router/atc.lua
KAG-3634
* move atc-router related modules into `do end` block
* some wrapper functions for atc objects created.
> refactor(router/atc): simplify the code of atc router schema

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
- changelog/unreleased/kong/per_reqeuest_deubgging.yml
- kong-3.4.3-0.rockspec
- kong.conf.default
- kong/conf_loader/init.lua
- kong/constants.lua
- kong/dynamic_hook/init.lua
- kong/dynamic_hook/wrap_function_gen.lua
- kong/global.lua
- kong/globalpatches.lua
- kong/hooks.lua
- kong/init.lua
- kong/resty/dns/client.lua
- kong/runloop/handler.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
- kong/timing/context.lua
- kong/timing/hooks/dns.lua
- kong/timing/hooks/http.lua
- kong/timing/hooks/init.lua
- kong/timing/hooks/redis.lua
- kong/timing/hooks/socket.lua
- kong/timing/init.lua
- kong/tools/utils.lua
- spec/02-integration/21-request-debug/01-request-debug_spec.lua
- spec/fixtures/custom_nginx.template
- spec/fixtures/custom_plugins/kong/plugins/muti-external-http-calls/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/muti-external-http-calls/schema.lua
Backports:
* https://github.com/Kong/kong/pull/11627
* https://github.com/Kong/kong/pull/11674
* https://github.com/Kong/kong/pull/11722
* https://github.com/Kong/kong/pull/11779
* https://github.com/Kong/kong/pull/11808
* https://github.com/Kong/kong/pull/11892
_[KAG-3440]_
[KAG-3440]: https://konghq.atlassian.net/browse/KAG-3440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Backport release/3.4.x] feat: request debugging 

- kong/router/fields.lua
KAG-3634
* alignment clean
* remove check of http prefix in `visit_for_context()`
> style(router/atc): simplify the code of atc fields

- .github/workflows/commitlint.yml
Enforce commit message format.
Docs: https://github.com/ahmadnassri/action-commit-lint?tab=readme-ov-file#built-in-configs
Feel free to add new commits testing the linter.
> chore(ci): add commit linter workflow

- kong/runloop/wasm.lua
The overall goal of this PR is to make the Wasm subsystem a better citizen of Kong.
The original code used the `kong.tools.dns` module to attempt* to instantiate its own DNS client:
https://github.com/Kong/kong/blob/b7d50b01f4c69cbf7bbad5329f6d9947de61045b/kong/runloop/wasm.lua#L838-L839
This has not caused any problems that we are aware of, but it's not the correct behavior and could potentially lead to problems further down the line with the DNS client rewrite looming.
Reusing the global `kong.dns` object necessitates moving this initialization code to the `init_worker` phase to work around some order-of-operations challenges (`wasm.init()` needs to run _before_ core entity schemas are loaded, which is also before `kong.dns` is initialized).
Additionally, I have added some checks around …
> chore(wasm): reuse kong.dns object for DNS bridge

- scripts/build-wasm-test-filters.sh
when build kong with 
```make dev BUILD_NAME=35xx```
the last step throw an error:
```
./scripts/build-wasm-test-filters.sh
cargo not found, installing rust toolchain
ERROR: bazel install root not found (/Users/xxxx/Workspace/kong-ee/bazel-bin/build/kong-dev/wasm-cargo-target)
You must run bazel before running this script.
make: *** [wasm-test-filters] Error 1
```
> fix(build): ensure `$BUILD_NAME` is used during the building of WASM test filters

- kong/router/fields.lua
Move the `FIELDS_FUNCS` searching into function `get_field_accessor()`,
this will make code easy to understand.
KAG-3634
> refactor(router/atc): simplify searching for field accessor function

- build/package/kong.logrotate
- build/package/nfpm.yaml
- changelog/unreleased/kong/fix-file-permission-of-logrotate.yml
- scripts/explain_manifest/explain.py
- scripts/explain_manifest/suites.py
origin file permission of kong.logrotate is 664, but the correct file permission is 644, this PR update.
```
bazel build --verbose_failures --config release :kong_deb
cd bazel-bin/pkg
dpkg-deb -R kong.amd64.deb kong-deb/ 
ls -al kong-deb/etc/kong/kong.logrotate
-rw-r--r-- 1  kong-deb/etc/kong/kong.logrotate
```
Fix: https://konghq.atlassian.net/browse/FTI-5756
> fix: update file permission of kong.logrotate

- build/package/nfpm.yaml
- changelog/unreleased/kong/fix-file-permission-of-logrotate.yml
- scripts/explain_manifest/explain.py
- scripts/explain_manifest/suites.py
origin PR: #12629
---------
origin file permission of kong.logrotate is 664, but the correct file permission is 644
Fix: https://konghq.atlassian.net/browse/FTI-5756
> [backport -> release/3.6.x] chore(cd): update file permission of kong.logrotate

- build/package/nfpm.yaml
- changelog/unreleased/kong/fix-file-permission-of-logrotate.yml
- scripts/explain_manifest/explain.py
- scripts/explain_manifest/suites.py
origin PR: #12629
---------
origin file permission of kong.logrotate is 664, but the correct file permission is 644
Fix: https://konghq.atlassian.net/browse/FTI-5756
> [backport -> release/3.5.x] chore(cd): update file permission of kong.logrotate

- changelog/unreleased/kong/cluster_events_invalidation_channel_deprecation.yml
- changelog/unreleased/kong/separate_kong_cache_invalidation_cluster_event_channel.yml
- kong/cache/init.lua
- kong/global.lua
- spec/fixtures/custom_plugins/kong/plugins/invalidations/handler.lua
Currently, the kong_db_cache and kong_core_db_cache use the same invalidations channel named "invalidations" in the cluster event hook. In a traditional cluster(in which multiple Kong nodes use the same database and communicate with each other through cluster events), whenever an invalidation happens on a node A, any other single node X in the cluster will call `invalidate_local` on both kong_db_cache and kong_core_db_cache although the entity usually exists in only one cache, thus generates useless worker events. Not sure if this is an intentional design.
The PR tries to separate every kong.cache instance to use its own invalidations channel to avoid generating useless "invalidations" worker events in a traditional cluster.
- [na] There is a user-facing docs PR against …
> fix(cache): mlcache invalidation use separate cluster event channels to avoid useless invalidation

- build/openresty/patches/ngx_lua-0.10.26_03-regex-memory-corruption.patch
- build/openresty/patches/ngx_stream_lua-0.0.14_02-remove-useless-pcre-config.patch
- build/openresty/patches/ngx_stream_lua-0.0.14_03-regex-memory-corruption.patch
Adds couple of patches that were recently merged to upstream project.
This should finally fix test issues with PCRE2 on EE master.
The EE commit can be already found here:
https://github.com/Kong/kong-ee/pull/7961
[KAG-3614](https://konghq.atlassian.net/browse/KAG-3614)
[KAG-3614]: https://konghq.atlassian.net/browse/KAG-3614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(patches): fix pcre2 regex memory corruption issues

- build/package/nfpm.yaml
- changelog/unreleased/kong/fix-file-permission-of-logrotate.yml
- scripts/explain_manifest/explain.py
- scripts/explain_manifest/suites.py
origin PR: https://github.com/Kong/kong/pull/12629
---------
origin file permission of kong.logrotate is 664, but the correct file permission is 644
Fix: https://konghq.atlassian.net/browse/FTI-5756
---------
> [backport -> release/3.4.x] chore(cd): update file permission of kong.logrotate

- .github/workflows/build_and_test.yml
replace PAT with github_token
background: when I opened this PR PAT had expired and it was making some tests fail on CI. It has since been rotated and things are green again now. 
We can still merge this and use github_token for this workflow instead to avoid this problem in the future.
> fix(ci): build and test use github token

- kong-3.7.0-0.rockspec
- kong/router/atc.lua
- kong/router/compat.lua
- kong/router/expressions.lua
- kong/router/transform.lua
- kong/router/utils.lua
- spec/01-unit/08-router_spec.lua
Move expression generation code out from `atc.lua` and `compat.lua` for future change.
Some small tunings:
* use `lshift_uint64()` when generating stream priority https://github.com/Kong/kong/pull/12650/commits/d5f656b3df15a5ea7cf52eb9c363f23fd47306e7
* use `expression_append()` in `gen_for_field()`
* a new function `is_stream_route()` to check stream route https://github.com/Kong/kong/pull/12650/commits/03abcc20361833909a3ab85b8c7a6cdb1961d3b5 https://github.com/Kong/kong/pull/12650/commits/d927a9aab50a469b26e69ef64ed69b634fcf5122
* move `parse_ip_addr()` out from utils.lua https://github.com/Kong/kong/pull/12650/commits/4b2dffdb76f01ba156dfa6511d72d24efea096bc
KAG-3804
> refactor(router/atc): separate expression transform code in atc-router

- kong/pdk/init.lua
This is a parallel PR for the docs submission made here: https://github.com/Kong/docs.konghq.com/pull/6333
The submission updates the example for checking the `kong.version_num` as the current docs show no major version.
Since the PDK reference docs are generated from the source code, we need to have the PDK code updated as well.
> docs(pdk): add major version to version num example

- kong/plugins/prometheus/schema.lua
I believe a number of Prometheus plugin configs are described incorrectly.
The description for **status_code_metrics**, **latency_metrics**, **bandwidth_metrics**, and **upstream_health_metrics**
_"A boolean value that determines if status code metrics should be collected"_
> docs(prometheus): fix the description of some metrics

- .github/workflows/release.yml
The `${{ secrets.GHA_COMMENT_TOKEN }}` needs to be manually rotated, replacing it by `${{ secrets.GITHUB_TOKEN }}`, which is generated by each run of the workflow, so we don't need to rotate tokens anymore.
* [Permissions required for creating a comment on a commit](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents)
* [How to set the permissions of the `${{ secrets.GITHUB_TOKEN }}`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)
* [Github rest API to create a commit on a commit](https://docs.github.com/en/rest/commits/comments?apiVersion=2022-11-28#create-a-commit-comment
)
- [N/A] A changelog file has been …
> chore(CI): fix the workflow that comments the docker image on the commit

- changelog/unreleased/kong/11464.yml
- changelog/unreleased/kong/11566.yml
- changelog/unreleased/kong/11613.yml
- changelog/unreleased/kong/acl_cache_warmup.yml
- changelog/unreleased/kong/rate-limiting-fix-redis-sync-rate.yml
- changelog/unreleased/kong/response_status_code.yml
- changelog/unreleased/kong/rl-shared-sync-timer.yml
- kong-3.4.3-0.rockspec
- kong/cache/warmup.lua
- kong/db/dao/init.lua
- kong/db/declarative/export.lua
- kong/db/schema/others/declarative_config.lua
- kong/db/strategies/off/init.lua
- kong/db/strategies/postgres/connector.lua
- kong/db/strategies/postgres/init.lua
- kong/init.lua
- kong/pdk/log.lua
- kong/plugins/acl/groups.lua
- kong/plugins/rate-limiting/policies/init.lua
- spec/01-unit/10-log_serializer_spec.lua
- spec/02-integration/05-proxy/07-upstream_timeouts_spec.lua
- spec/02-integration/07-sdk/02-log_spec.lua
- spec/03-plugins/09-key-auth/04-hybrid_mode_spec.lua
- spec/03-plugins/18-acl/02-access_spec.lua
- spec/03-plugins/23-rate-limiting/02-policies_spec.lua
- spec/03-plugins/23-rate-limiting/05-integration_spec.lua
This PR cherry-picks some of the important fixes to `release/3.4.x` so that we can get alignment between `release/3.4.x` and `next/3.4.x.x`
Contains the following PRs:
https://github.com/Kong/kong/pull/11613
https://github.com/Kong/kong/pull/11566
https://github.com/Kong/kong/pull/11859
https://github.com/Kong/kong/pull/12003
https://github.com/Kong/kong/pull/11926
https://github.com/Kong/kong/pull/11464
https://github.com/Kong/kong/pull/11414
https://github.com/Kong/kong/pull/11437
> [cherry release/3.4.x] cherry-picking important fixes to 34x

- .github/workflows/cherry-picks.yml
Bump cherry pick bot to https://github.com/jschmid1/cross-repo-cherrypick-action/releases/tag/v1.2.0
Major additions are:
* The bot now correctly sets the output & failure when encountering issues.
* In addition to requesting a review from the individual who merged the original PR, but also copies over all reviewers that were assigned to it.
Fix: https://konghq.atlassian.net/browse/KAG-4016
> chore: bump cherry-pick action to v1.2.0

- spec/02-integration/02-cmd/03-reload_spec.lua
- spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
- spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
- spec/02-integration/04-admin_api/09-routes_routes_spec.lua
- spec/02-integration/04-admin_api/10-services_routes_spec.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
- spec/02-integration/04-admin_api/17-foreign-entity_spec.lua
- spec/02-integration/04-admin_api/18-worker-events.lua
- spec/02-integration/04-admin_api/19-vaults_spec.lua
- spec/02-integration/04-admin_api/21-truncated_arguments_spec.lua
- spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
- spec/02-integration/05-proxy/09-websockets_spec.lua
- spec/02-integration/05-proxy/11-handler_spec.lua
- spec/02-integration/05-proxy/13-error_handlers_spec.lua
- spec/02-integration/05-proxy/25-upstream_keepalive_spec.lua
- spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
- spec/02-integration/11-dbless/01-respawn_spec.lua
- spec/02-integration/11-dbless/02-workers_spec.lua
- spec/03-plugins/19-hmac-auth/04-invalidations_spec.lua
- spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua
- spec/03-plugins/23-rate-limiting/03-api_spec.lua
- spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
- spec/03-plugins/31-proxy-cache/03-api_spec.lua
- spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua
chore(test): remove prefix directory when stop_kong called (#12691)
If the prefix is not cleaned up when stop_kong is called, it could impact subsequent tests, especially when later tests start Kong by a shell command, the Kong instance might be started up with the default `servroot` prefix.
KAG-3808
(cherry picked from commit 3dd5bdb78ee9aa4b4f602ec241a4b52b1b0ae353)
> [backport -> release/2.8.x] Backport 12691 to release/2.8.x

- spec/02-integration/02-cmd/03-reload_spec.lua
- spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
- spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
- spec/02-integration/04-admin_api/09-routes_routes_spec.lua
- spec/02-integration/04-admin_api/10-services_routes_spec.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
- spec/02-integration/04-admin_api/17-foreign-entity_spec.lua
- spec/02-integration/04-admin_api/19-vaults_spec.lua
- spec/02-integration/04-admin_api/21-admin-api-keys_spec.lua
- spec/02-integration/04-admin_api/21-truncated_arguments_spec.lua
- spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
- spec/02-integration/05-proxy/09-websockets_spec.lua
- spec/02-integration/05-proxy/11-handler_spec.lua
- spec/02-integration/05-proxy/13-error_handlers_spec.lua
- spec/02-integration/05-proxy/25-upstream_keepalive_spec.lua
- spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
- spec/02-integration/11-dbless/01-respawn_spec.lua
- spec/02-integration/11-dbless/02-workers_spec.lua
- spec/02-integration/11-dbless/03-config_persistence_spec.lua
- spec/03-plugins/01-legacy_queue_parameter_warning_spec.lua
- spec/03-plugins/19-hmac-auth/04-invalidations_spec.lua
- spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua
- spec/03-plugins/23-rate-limiting/03-api_spec.lua
- spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
- spec/03-plugins/29-acme/05-redis_storage_spec.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
- spec/03-plugins/31-proxy-cache/03-api_spec.lua
- spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua
- spec/05-migration/plugins/opentelemetry/migrations/001_331_to_332_spec.lua
chore(test): remove prefix directory when stop_kong called (#12691)
If the prefix is not cleaned up when stop_kong is called, it could impact subsequent tests, especially when later tests start Kong by a shell command, the Kong instance might be started up with the default `servroot` prefix.
KAG-3808
(cherry picked from commit 3dd5bdb78ee9aa4b4f602ec241a4b52b1b0ae353)
> [backport -> release/3.3.x] Backport 12691 to release/3.3.x

- .github/workflows/release.yml
Backport https://github.com/Kong/kong/pull/12693
_[KAG-4021]_
[KAG-4021]: https://konghq.atlassian.net/browse/KAG-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport release/3.4.x] chore(CI): fix the workflow that comments the docker image on the commit

- .github/workflows/release.yml
Backport https://github.com/Kong/kong/pull/12693
_[KAG-4021]_
[KAG-4021]: https://konghq.atlassian.net/browse/KAG-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport release/3.3.x] chore(CI): fix the workflow that comments the docker image on the commit

- .github/workflows/release.yml
Backport https://github.com/Kong/kong/pull/12693
_[KAG-4021]_
[KAG-4021]: https://konghq.atlassian.net/browse/KAG-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport release/2.8.x] chore(CI): fix the workflow that comments the docker image on the commit

- changelog/unreleased/kong/fix-snis-tls-passthrough-in-trad-compat.yml
- kong/db/schema/entities/routes.lua
- kong/router/transform.lua
- spec/01-unit/08-router_spec.lua
KAG-3922
FTI-5781 was fixed in #12650, this PR add the test cases and changelog.
> refactor(db/schema): ensure to validate possible routes fields

- changelog/unreleased/kong/plugin-schema-deprecation-record.yml
- kong/db/schema/init.lua
- kong/db/schema/metaschema.lua
- kong/plugins/acme/schema.lua
- kong/plugins/datadog/schema.lua
- kong/plugins/http-log/schema.lua
- kong/plugins/opentelemetry/schema.lua
- kong/plugins/rate-limiting/schema.lua
- kong/plugins/response-ratelimiting/schema.lua
- kong/plugins/statsd/schema.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/dummy/schema.lua
Add a deprecation record field attribute to identify fields that are deprecated. The attribute requires the `message` and `removal_in_version` fields to be configured, which are used to generate a warning when the deprecated field is configured (uses `kong.deprecation`). The optional `old_default` field can be used to determine whether the warning should be logged (in case the field was configured to a value other than the old default).
This PR adds the deprecation attribute to two kind of fields:
1. regular plugin fields that have been deprecated and that were not yet removed from the schema, i.e. the old queue parameters in datadog, opentelemetry, http-log, statsd
2. shorthand fields, for fields that have been removed from the plugin's schema and that only exist as shorthands, i.e. …
> feat(schema): add deprecation field attribute

- changelog/unreleased/kong/fix-jwt-plugin-check.yml
- kong/plugins/jwt/jwt_parser.lua
The plugin might fail due to invalid public keys. The sanity checks are in place for all algorithms except ES384 and ES512. In addition the usage of pkey:verify function has been harmonized across the different algorithms.
Martin Kölbel <martin.koelbel@mercedes-benz.com> on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
> fix(jwt-plugin): Add missing pkey sanity check for ES384 and ES512

- build/openresty/patches/ngx_lua-0.10.26_03-regex-memory-corruption.patch
- build/openresty/patches/ngx_stream_lua-0.0.14_03-regex-memory-corruption.patch
This adds two commits from @zhongweiy as found here: https://github.com/openresty/lua-nginx-module/pull/2291 https://github.com/openresty/stream-lua-nginx-module/pull/341
They are cleanups to original patch.
KAG-3614
> chore(patches): cleanup the pcre2 regex patch

- changelog/unreleased/kong/fix-external-plugin-instance.yml
- kong/runloop/plugin_servers/init.lua
This fixes an issue where an external plugin -- Go, JS, or Python -- would fail to apply a config via a PATCH request to the admin API.
KAG-3949
> fix(pluginserver): ensure a change to plugin config takes effect

- changelog/unreleased/kong/pluginsocket-proto-wrong-type.yml
- kong/include/kong/pluginsocket.proto
Fix the return type for the `.Service.SetUpstream` external plugin PDK method.
Fixes issue https://github.com/Kong/go-pdk/issues/114.
Sister PR: https://github.com/Kong/go-pdk/pull/191
Fixes issue https://github.com/Kong/go-pdk/issues/114.
> fix(pluginsocket.proto): type for `set_upstream`

- changelog/unreleased/kong/fix-router-rebuing-flag.yml
- kong/router/atc.lua
- spec/01-unit/08-router_spec.lua
The variable `rebuilding` is a flag to prevent duplicate router building action,
if any error occurs it should be set to `false`,
or else the router will never be rebuilt again.
KAG-3857
> fix(router/atc): reset rebuilding flag if route has no id

- changelog/unreleased/kong/speed_up_router.yml
- kong/router/fields.lua
```
---- TRACE 1772 start fields.lua:457
0001  UGET     4   0      ; FIELDS_FUNCS       (fields.lua:458)
0002  TGETV    4   4   1       (fields.lua:458)
0003  IST          4       (fields.lua:458)
0004  JMP      5 => 0009
0005  UGET     4   1      ; get_field_accessor       (fields.lua:459)
0006  TGETS    6   0   0  ; "funcs"       (fields.lua:459)
0007  MOV      7   1       (fields.lua:459)
0008  CALL     4   2   3       (fields.lua:459)
0000  . FUNCF    9          ; fields.lua:266
0001  . TGETV    2   0   1       (fields.lua:267)
0002  . ISF          2       (fields.lua:268)
0003  . JMP      3 => 0005
0004  . UCLO     0 => 0055       (fields.lua:269)
---- TRACE 1772 abort fields.lua:269 -- NYI: bytecode 50
```
Generating a field accessor in place in the `get_field_accessor()` is not JIT …
> perf(router): remove NYI to be more JIT-friendly

- changelog/unreleased/kong/log-serializer-receive-latency.yml
- kong/pdk/log.lua
- spec/01-unit/10-log_serializer_spec.lua
This adds receive time to the latencies object, as reported in `ctx.KONG_RECEIVE_TIME`:
https://github.com/Kong/kong/blob/15a3797ba0c6124cb73d20a9037fc7aee9e86bbe/kong/init.lua#L1685-L1692
KAG-3798
> feat(log-serializer): add `latencies.receive` property to log-serializer

- kong/templates/nginx_kong.lua
The following ngx vars were added by https://github.com/Kong/kong/pull/11722 for performance:
``` plain
lua_kong_load_var_index $http_x_kong_request_debug;
lua_kong_load_var_index $http_x_kong_request_debug_token;
lua_kong_load_var_index $http_x_kong_request_debug_log;
```
And the lua-kong-nginx-module index these by default now: https://github.com/Kong/lua-kong-nginx-module/releases/tag/0.9.0, and we have already bumped it by https://github.com/Kong/kong/pull/12752, so we can remove these explicit indexing now.
- [N/A] There is a user-facing docs PR …
> refactor(template): eliminate manual indexing on certain Nginx variables due to inherent default indexing

- changelog/unreleased/kong/bump-lua-resty-timer-ng.yml
- kong-3.7.0-0.rockspec
* perf: remove NYIs to be more JIT-friendly by @ADD-SP in https://github.com/Kong/lua-resty-timer-ng/pull/25
* chore(rockspec): release 0.2.7-1 by @ADD-SP in https://github.com/Kong/lua-resty-timer-ng/pull/26
**Full Changelog**: https://github.com/Kong/lua-resty-timer-ng/compare/0.2.6...0.2.7
_[KAG-3653]_
[KAG-3653]: https://konghq.atlassian.net/browse/KAG-3653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): bump lua-resty-timer-ng from 0.2.6 to 0.2.7

- kong/plugins/grpc-web/deco.lua
- scripts/explain_manifest/expect.py
> style(plugins/grpc-web): fix some typos

- changelog/unreleased/kong/key_auth_www_authenticate.yml
- kong/plugins/key-auth/handler.lua
- kong/plugins/key-auth/schema.lua
- spec/01-unit/01-db/01-schema/07-plugins_spec.lua
- spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
- spec/03-plugins/09-key-auth/02-access_spec.lua
- spec/03-plugins/10-basic-auth/03-access_spec.lua
When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Key auth was missing this header on some responses. This PR also adds a possibility to configure an optional parameter - realm (defaults to `null`).
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11820
- https://github.com/Kong/kong/pull/11833
- add `WWW-Authenticate` header to all key-auth 401 response
- Fix #7772
- KAG-321
> fix(key-auth): add missing www-authenticate headers

- changelog/Makefile
docs(release): simplify changelog automation.
Cherry-pick https://github.com/Kong/kong-ee/pull/8586. Verified by https://github.com/Kong/kong/pull/12763.
Fix #_[FTI-5842]_
[FTI-5842]: https://konghq.atlassian.net/browse/FTI-5842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(release): simplify changelog automation

- changelog/unreleased/kong/fix-upstream-status-unset.yml
- kong/runloop/handler.lua
- spec/02-integration/05-proxy/15-upstream-status-header_spec.lua
Fix a bug that `X-Kong-Upstream-Status` header is not set when the response is provided by the `proxy-cache` plugin.
FTI-5827
> fix(core): X-Kong-Upstream-Status header is not set

- changelog/unreleased/kong/force-no_sync-noip.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
This change adds new `individual_toip()` public function to the DNS client. 
This function bypasses the `noSynchronisation = false` option, forcing individual resolve of the hostnames. It avoids race-conditions when multiple calls to the `access()` phase handler happen in the context of the same request.
KAG-3795
> feat(dns): function to force no sync toip()

- changelog/unreleased/kong/feat-wasm-general-shm-kv.yml
- kong.conf.default
- kong/conf_loader/constants.lua
- kong/templates/nginx.lua
- spec/01-unit/04-prefix_handler_spec.lua
- spec/fixtures/custom_nginx.template
WasmX supports using non-namespaced entries in proxy-wasm `get_shared_data` and `set_shared_data`. For this, one needs to define a no-namespaced shm_kv using the `shm_kv * <size>` directive. This commit adds `nginx_wasm_main_shm_kv` as a supported option alongside the existing `nginx_wasm_main_shm_kv_<namespace>` entries, for definition of the non-namespaced `shm_kv`.
> feat(wasm): support directive for general shm_kv entry

- changelog/unreleased/kong/feat-increase-ai-anthropic-regex-expression-length.yml
- kong/plugins/ai-prompt-guard/schema.lua
- spec/03-plugins/42-ai-prompt-guard/00_config_spec.lua
increase the maximum length of regex expression to 500 for both allow and deny parameter
FTI-5767
> feat(ai-prompt-guard): increase the maximum length of regex expression

- kong/router/transform.lua
Closure may cause unnecessary NYIs, removing them will improve performance.
KAG-4138
> refactor(router/atc): remove closure to avoid NYIs

- kong/plugins/basic-auth/schema.lua
During the review of: https://github.com/Kong/kong/pull/11794 (see comment: https://github.com/Kong/kong/pull/11794#pullrequestreview-1932771723) it was pointed out that the description for realm field was misleading. This PR corrects basic-auth description.
[KAG-3635](https://konghq.atlassian.net/browse/KAG-3635)
[KAG-3635]: https://konghq.atlassian.net/browse/KAG-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(plugins/basic-auth): correct realm field description

- changelog/unreleased/kong/fix-acme-renewal-bug.yml
- kong/plugins/acme/api.lua
- kong/plugins/acme/handler.lua
- spec/03-plugins/29-acme/01-client_spec.lua
Fix ACME renewal bug.
Using `client.renew_certificate` directly as the callback function in `ngx_timer_at` causes the parameter value to not be the plugin's config.
KAG-4008
Fix #12442
> fix(plugins/acme): fix certificate renew failure issue

- kong/tools/module.lua
- simplfy xpcall
- simplify if-else
> style(tools/module): improve code style for readability

- kong/db/schema/typedefs.lua
- use localized `gsub`
- use `xxx:find()`
> style(db/schema): improve readability of string operations

- kong/clustering/compat/removed_fields.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
added compatibility with older data planes for the new tracing headers propagation configuration options
KAG-4139
> fix(plugins): compatibility with older data planes

- kong/plugins/ai-prompt-template/handler.lua
> style(plugins/ai-prompt-template): improve code style for readability

- kong/db/schema/init.lua
- kong/tools/table.lua
- remove outdated comment
- remove the usage of `kong.tools.utils`
> style(tools/table): clean the comments and improve usage

- changelog/unreleased/kong/speed_up_internal_hooking_mechanism.yml
- kong/hooks.lua
* Invoking a function using varargs (...) is NYI.
EE PR: kong/kong-ee#8046
_[KAG-3653]_
[KAG-3653]: https://konghq.atlassian.net/browse/KAG-3653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> perf(hook): remove NYIs to be more JIT-friendly

- kong/reports.lua
- kong/tools/utils.lua
- spec/01-unit/05-utils_spec.lua
This is one of refactor `kong.tools` tasks.
KAG-3137
> refactor(tools/system): move system module out of tools.utils

- .github/workflows/release.yml
- scripts/release-kong.sh
As we have passed the 6 months deprecation period (2023 Dec), artifact release to pulp should be stopped
to allow full removal of Pulp.
[KAG-4120](https://konghq.atlassian.net/browse/KAG-4120)
[KAG-4120]: https://konghq.atlassian.net/browse/KAG-4120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(cd): stop uploading to pulp

- .github/workflows/cherry-picks.yml
Kong-ee uses different names for long-lived branches (they are not prefixed by `release` like in Kong CE).
This means that any pr targetting any branch other than master will get "confused" (since it will not find the branch it expects in EE) and throw an error.
Since our CE backport action copies the labels from the original PR, this means that all the backports are also labeled for cherrypicking. Which is not
our desired workflow: in general we want a change to be cherry-picked from kong-CE/master to kong-EE/master, and then backported to any kong-EE long-lived
branches if necessary.
This change makes the cherry-pick action ignore any PRs not targetting master to avoid these issues.
> chore(ci): cherry-pick only PRs targetting master

- changelog/unreleased/kong/log-serializer-kong-latency.yml
- kong/pdk/log.lua
- spec/01-unit/10-log_serializer_spec.lua
This removes receive time (`latencies.receive` or `ctx.KONG_RECEIVE_TIME`) from `latencies.kong` within the log serializer.
Kongers: see JIRA ticket for more context.
KAG-3798
> fix(log-serializer): do not add receive time to `latencies.kong`

- .github/workflows/label-schema.yml
Currently, a Slack notification is sent to `#gateway-schema-change-feed` for every commit in a PR that has the label `schema-change-noteworthy`.
From the Koko side, we're only interested in the change as a whole (PR level). This change aims to reduce the duplicate messages and make it easier to keep track of gateway schema changes. 
> ci: remove `synchronize` trigger for label-schema

- bin/busted
This PR makes bin/busted able to trust system certificate store for the convenience of some unit testing.
This is a partial cherry-picking from EE PR, although currently we don't have any OSS test that relies on this change, I created this cherry-picking PR just for keeping consistency between the two repos.
> chore(test): busted script support system trusted certificate store

- kong/plugins/aws-lambda/schema.lua
This PR adds a detailed description for the `function_name` format of the aws-lambda plugin.
> docs(aws-lambda): add name format description for aws lambda plugin

- changelog/unreleased/kong/speed_up_internal_hooking_mechanism.yml
Make the changelog created by https://github.com/Kong/kong/pull/12784 more customer-friendly.
_[KAG-3653]_
[KAG-3653]: https://konghq.atlassian.net/browse/KAG-3653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(changelog): make the changelog of performance optimization more customer-friendly

- DEVELOPER.md
Fix links to busted and luacheck in DEVELOPER.md
> docs: fix links to busted and luacheck in DEVELOPER.md

- changelog/unreleased/kong/bump-lua-protobuf.yml
- kong-3.7.0-0.rockspec
v0.5.1 includes a fix for a segfault we have faced recently - as described in detail here: https://github.com/starwing/lua-protobuf/issues/261.
> chore(deps): bump lua-protobuf to v0.5.1

- spec/02-integration/02-cmd/02-start_stop_spec.lua
I've been seeing intermittent failures of these tests such as this one:
https://github.com/Kong/kong/actions/runs/8561323431/job/23462317673?pr=12829
```
FAIL spec/02-integration/02-cmd/02-start_stop_spec.lua:935: kong start/stop #off errors dbless does not fail fatally when referencing secrets doesn't work in declarative configuration using vault entities
spec/02-integration/02-cmd/02-start_stop_spec.lua:976: Expected file at:
(string) '/home/runner/work/kong/kong/servroot/logs/error.log'
To match:
(string) ' {vault://mock/session-secret-unknown-again}'
```
The log file assertion in question did not account for eventual consistency (zero timeout):
```lua
assert.logfile().has.line(" {vault://mock/session-secret-unknown-again}", true, 0)
```
I removed the 0 so that the assertion uses the …
> tests(vaults): fix log file assertion

- changelog/unreleased/kong/tracing-pdk-short-trace-ids.yml
- kong/pdk/tracing.lua
- spec/01-unit/26-tracing/01-tracer_pdk_spec.lua
- spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
This is a forward port of `kong-ee/pull/8767` the actual fix is not needed because already covered by the new propagation module.
This commit ports the updates to the pdk (no longer throw error on too short id) and tests.
[KAG-4218](https://konghq.atlassian.net/browse/KAG-4218)
[KAG-4218]: https://konghq.atlassian.net/browse/KAG-4218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tracing): do not error on too short trace id + tests

- changelog/unreleased/kong/fix-ctx-host-port.yml
- kong/pdk/log.lua
- kong/router/fields.lua
- kong/router/traditional.lua
- kong/runloop/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests-response/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests/handler.lua
It turns out that `ngx.ctx.host_port` may be a `string` in some cases, which leads to bugs elsewhere where it may be expected to be a number. This adds `tonumber` call to ensure that it is a number.
This bug affects for example `PDK` function `kong.request.get_forwarded_port()`.
https://konghq.atlassian.net/browse/KAG-4158
> fix(core): ensure ngx.ctx.host_port is a number (and not a string)

- changelog/unreleased/kong/analytics-for-anthropic.yml
- kong/llm/drivers/anthropic.lua
- kong/llm/init.lua
- spec/03-plugins/38-ai-proxy/00-config_spec.lua
- spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua
- spec/fixtures/ai-proxy/anthropic/llm-v1-chat/responses/good.json
- spec/fixtures/ai-proxy/unit/real-responses/anthropic/llm-v1-chat.json
fix a bug that the analystics is not included in the response of the `chat` route_type of anthropic
FTI-5769
> fix(ai-proxy): add analytics for `chat` route_type of anthropic

- changelog/unreleased/kong/feat-ai-proxy-add-streaming.yml
- kong/llm/drivers/anthropic.lua
- kong/llm/drivers/azure.lua
- kong/llm/drivers/cohere.lua
- kong/llm/drivers/llama2.lua
- kong/llm/drivers/mistral.lua
- kong/llm/drivers/openai.lua
- kong/llm/drivers/shared.lua
- kong/llm/init.lua
- kong/plugins/ai-proxy/handler.lua
- spec/03-plugins/38-ai-proxy/01-unit_spec.lua
- spec/03-plugins/38-ai-proxy/09-streaming_integration_spec.lua
- spec/fixtures/ai-proxy/cohere/llm-v1-chat/requests/good-stream.json
- spec/fixtures/ai-proxy/llama2/ollama/chat-stream.json
- spec/fixtures/ai-proxy/openai/llm-v1-chat/requests/good-stream.json
- spec/fixtures/ai-proxy/openai/llm-v1-chat/requests/good.json
- spec/fixtures/ai-proxy/openai/llm-v1-chat/requests/good_own_model.json
- spec/fixtures/ai-proxy/unit/expected-requests/azure/llm-v1-chat.json
- spec/fixtures/ai-proxy/unit/expected-requests/azure/llm-v1-completions.json
- spec/fixtures/ai-proxy/unit/expected-requests/mistral/openai/llm-v1-chat.json
- spec/fixtures/ai-proxy/unit/expected-requests/openai/llm-v1-chat.json
- spec/fixtures/ai-proxy/unit/expected-requests/openai/llm-v1-completions.json
- spec/fixtures/ai-proxy/unit/real-stream-frames/cohere/llm-v1-chat.txt
- spec/fixtures/ai-proxy/unit/real-stream-frames/cohere/llm-v1-completions.txt
- spec/fixtures/ai-proxy/unit/real-stream-frames/openai/llm-v1-chat.txt
- spec/fixtures/ai-proxy/unit/real-stream-frames/openai/llm-v1-completions.txt
Adds "streaming" support to AI Proxy plugin.
Streaming is a mode where a client can specify `"stream": true` in their request, and the LLM server will stream each piece piece of the response text (usually token-by-token) as a server-sent event.
We need to capture each (batch of) event(s) in order to translate them back into our inference format, so that all providers are compatible with the same framework that our users will create on their side.
Where "streaming=false" requests proxy directly to the LLM, and look like this:
the new streaming framework captures each event, and sends the chunk back to the client, like this:
and then it **exits early**. Docs will describe the limitations of this (no response transformer, etc).
It will also count/estimate tokens for LLM services that have …
> feat(ai-proxy): add streaming support and transformers

- kong/llm/init.lua
- kong/plugins/acme/client.lua
- kong/plugins/grpc-gateway/deco.lua
- kong/plugins/jwt/handler.lua
- kong/plugins/oauth2/access.lua
- kong/plugins/proxy-cache/handler.lua
- kong/runloop/plugin_servers/mp_rpc.lua
- kong/runloop/plugin_servers/pb_rpc.lua
This commit ensures that `ngx.re` uses (in critical (proxy path) code paths mostly) are both JITted and JIT-cached.
I have not had time to run some perf tests for this, so feel free to hold on merging until I have time to do so.
> perf(*): `ngx.re` uses are jitted and cached

- changelog/unreleased/kong/update-ai-proxy-telemetry.yml
- kong/llm/drivers/shared.lua
- kong/plugins/ai-proxy/handler.lua
- kong/plugins/ai-request-transformer/handler.lua
- kong/plugins/ai-response-transformer/handler.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
This will allow to add a provide layer in the analytics in case several plugins are used 
Current model is:
```json
"ai": {
"meta": {
"response_model": "mistral-tiny",
"provider_name": "mistral",
"request_model": "mistral-tiny"
},
"usage": {
"prompt_tokens": 259,
"completion_tokens": 274,
"total_tokens": 533
}
}
```
New model if using several plugins:
```json
"ai": {
"mistral": {
"request_total_tokens": 648,
"number_of_instances": 1,
"instances": [
{
"meta": {
"request_model": "mistral-tiny",
"plugin_id": "1c783122-0223-4a03-9f1d-c71d2baab01e",
"response_model": "mistral-tiny",
"provider_name": "mistral"
},
"usage": {
"prompt_token": 392,
"total_tokens": 648,
"completion_token": 256
}
}
],
"request_prompt_tokens": 392,
"request_completion_tokens": 256
},
"azure": {
"request_total_tokens": …
```
> change ai analytics

- changelog/unreleased/kong/bump-penlight.yml
- kong-3.7.0-0.rockspec
- spec/03-plugins/36-request-transformer/02-access_spec.lua
Changelog:
> 1.14.0 (2024-Apr-15)
fix(path): make path.expanduser more sturdy https://github.com/lunarmodules/Penlight/pull/469
feat(func): extend compose to support N functions https://github.com/lunarmodules/Penlight/pull/448
fix(utils) nil values in utils.choose(cond, val1, val2) https://github.com/lunarmodules/Penlight/pull/447
fix(template) using % as an escape character caused the expression to not be recognized https://github.com/lunarmodules/Penlight/pull/452
enhance(template): Preserve line numbers https://github.com/lunarmodules/Penlight/pull/468
fix(pretty) integers for Lua 5.4 https://github.com/lunarmodules/Penlight/pull/456
Fix #_[issue …
> chore(deps): bump penlight to 1.14.0

- changelog/unreleased/kong/fix-ctx-host-port.yml
- kong/pdk/log.lua
- kong/router/fields.lua
- kong/router/traditional.lua
- kong/runloop/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests-response/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests/handler.lua
Manual fix backport.
https://konghq.atlassian.net/browse/KAG-4158
> [backport -> release/3.4.x] fix(core): ensure ngx.ctx.host_port is a number (and not a string)

- changelog/unreleased/kong/fix-ctx-host-port.yml
- kong/pdk/log.lua
- kong/router/fields.lua
- kong/router/traditional.lua
- kong/runloop/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests-response/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests/handler.lua
Manual fix backport.
https://github.com/Kong/kong/pull/12806
https://konghq.atlassian.net/browse/KAG-4158
> [backport -> release/3.5.x] fix(core): ensure ngx.ctx.host_port is a number (and not a string)

- changelog/unreleased/kong/fix-ctx-host-port.yml
- kong/pdk/log.lua
- kong/router/fields.lua
- kong/router/traditional.lua
- kong/runloop/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests-response/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/ctx-tests/handler.lua
Manual fix backport of https://github.com/Kong/kong/pull/12806
https://konghq.atlassian.net/browse/KAG-4158
> [backport -> release/3.6.x] fix(core): ensure ngx.ctx.host_port is a number (and not a string)

- changelog/unreleased/kong/flavor-expressions-supports-traditional-fields.yml
- kong/db/schema/entities/routes.lua
- kong/db/schema/entities/routes_subschemas.lua
- kong/router/atc.lua
- kong/router/compat.lua
- kong/router/expressions.lua
- kong/router/transform.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
- spec/01-unit/08-router_spec.lua
- spec/02-integration/05-proxy/01-proxy_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
- spec/02-integration/05-proxy/10-balancer/06-stream_spec.lua
- spec/02-integration/05-proxy/18-upstream_tls_spec.lua
- spec/02-integration/05-proxy/19-grpc_proxy_spec.lua
- spec/02-integration/05-proxy/21-grpc_plugins_triggering_spec.lua
- spec/02-integration/05-proxy/23-context_spec.lua
- spec/02-integration/05-proxy/26-udp_spec.lua
- spec/02-integration/05-proxy/28-stream_plugins_triggering_spec.lua
- spec/02-integration/05-proxy/31-stream_tls_spec.lua
* now `expressions` flavor supports `methods` `hosts` `paths` `headers` `snis` and other fields
* now `expressions` flavor is a superset of `traditional_compatible`
NOTICE:
We will have additional work on `routes.lua ` and `routes_subschemas.lua` when cherry pick.
Fix: KAG-3805 KAG-3807
> feat(db/schema): add traditional fields to expressions flavor

- spec/01-unit/08-router_spec.lua
> tests(router): use router.transform.get_expression

- .requirements
- build/build_system.bzl
- build/openresty/atc_router/atc_router_repositories.bzl
- build/openresty/brotli/brotli_repositories.bzl
- build/openresty/repositories.bzl
- build/openresty/wasmx/wasmx_repositories.bzl
- build/repositories.bzl
Now we are able to use like 
```
LUA_KONG_NGINX_MODULE=../lua-kong-nginx-module
```
to support local development
KAG-4280
> feat(build): allow use local path to replace git repositories

- changelog/unreleased/kong/fix-hybrid-dp-certificate-with-vault-not-refresh.yml
- kong/pdk/vault.lua
- kong/runloop/certificate.lua
- spec/02-integration/05-proxy/18-upstream_tls_spec.lua
- spec/02-integration/13-vaults/05-ttl_spec.lua
This PR fixes a problem that a certificate entity with cert/keys stored in a vault-referenced type cannot be refreshed even if the vault reference secret value has been updated both in L1/L2 vault PDK.
The root cause of this problem is that in a dp node running hybrid mode, kong cache interfaces force the cache TTL to be infinite(and it also does not respect cache TTL configured in `kong.conf`), thus the certificate object cannot be updated unless a new configuration is received and cache `purge` being called.
The PR fixes the problem by caching the vault reference fields `$ref` and call `kong.vault.update` every time in `get_certificate`, and l1 serializer will keep the value serialized inside the certificate object.
This PR contains a test case that tests a certificate entity with a …
> fix(certificate): hybrid dp cannot refresh certificate entity with vault reference

- changelog/unreleased/kong/fix_balancer_healthecker_unexpected_panic.yml
- kong/runloop/balancer/healthcheckers.lua
fix balancer stop_healthchecks function unexpected table nil panic
https://github.com/Kong/kong/blob/master/kong/runloop/balancer/healthcheckers.lua#L421
Fix https://github.com/Kong/kong/issues/12811
> fix(core): fix balancer stop_healthchecks function table nil panic bug

- .github/workflows/cherry-picks.yml
The cherry-pick action failed to add a label when the action itself failed. [As seen for example here 
](https://github.com/Kong/kong/actions/runs/8700023067/job/23859557374)
This can be resolved by adding [proper permissions ](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)to the job like we did in the backports job. Most notably the `pull-requests` permission which:
> Work with pull requests. For example, pull-requests: write permits an action to add a label to a pull request. For more information, see "[Permissions required for GitHub Apps](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests)."
Fix: https://konghq.atlassian.net/browse/KAG-4288
> chore(ci): add permissions to cherry-pick job

- changelog/unreleased/kong/bump-lua-resty-aws.yml
- kong-3.7.0-0.rockspec
Changelog:
> fix: aws configuration cannot be loaded due to pl.path cannot resolve the path started with ~ https://github.com/Kong/lua-resty-aws/pull/94
fix: fix the bug of missing boolean type with a value of false in the generated request body https://github.com/Kong/lua-resty-aws/pull/100
security: remove the documentation entry that contains a sample access key from AWS SDK. This avoids false postive vulnerability report. https://github.com/Kong/lua-resty-aws/pull/102
feat: container credential provider now supports using auth token defined in AWS_CONTAINER_AUTHORIZATION_TOKEN and AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE. https://github.com/Kong/lua-resty-aws/pull/107
fix: operations without inputs (eg, some S3 ones) would cause errors to be thrown …
> chore(deps): bump lua-resty-aws to 1.4.1

- spec/02-integration/13-vaults/05-ttl_spec.lua
- spec/02-integration/13-vaults/07-resurrect_spec.lua
Due to the inclusion of the following statement in the test code:
```lua
helpers.test_conf.loaded_plugins = {
dummy = true,
}
```
This statement directly causes the `load_subsystems` function in `kong/db/migrations/state.lua` to only obtain the subsystems `core` and `enterprise`, which in turn causes most plugins to not undergo migration in `helpers.get_db_utils`. This ultimately leads to the issue when checking the migration of each plugin during `start_kong`.
KAG-4240
> fix(tests): fix the flakiness caused by incomplete migration in the Vault tests

- build/BUILD.bazel
- build/openresty/BUILD.openresty.bazel
- build/openresty/repositories.bzl
- build/openresty/wasmx/filters/BUILD.bazel
- build/openresty/wasmx/filters/repositories.bzl
- build/openresty/wasmx/filters/variables.bzl
The changes in this PR cause the defined wasm filters to be downloaded from github and packaged with Kong.
Fix #_[KAG-4210]_
[KAG-4210]: https://konghq.atlassian.net/browse/KAG-4210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KAG-4210] Incorporate wasm filters into bazel build

- kong/llm/drivers/anthropic.lua
- spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua
- spec/fixtures/ai-proxy/anthropic/llm-v1-chat/responses/malformed_usage_response.json
- spec/fixtures/ai-proxy/anthropic/llm-v1-chat/responses/no_usage_response.json
There is a bit difference in the usage data between ai providers, and considering the variability of it, this PR attempts to improve the robustness during the process of transforming the usage data when: 
1. no usage data provided in the upstream response;
2. some possible changes in structure of usage data in the future;
In #12781 , it is arbitrarily believed that the usage data is always included and the data struct won't change. This may be a potential issue throwing an error. Therefore, this PR is a follow-up one to prevent from it.
> fix(AI-Proxy): improve the robustness of anthropic's statistics

- .github/workflows/release.yml
KAG-4155
actions/cache@v4 breaks on old distros like centos7 and amazonlinux2
> chore(cd): degrade actions/cache from v4 to v3

- kong/clustering/compat/checkers.lua
- kong/clustering/compat/init.lua
- kong/clustering/control_plane.lua
- spec/01-unit/19-hybrid/03-compat_spec.lua
~~Blocked by #12667.~~
KAG-3806
> feat(clustering): add compatible checkers for mixed mode routes

- changelog/unreleased/kong/fix-dbless-duplicate-target-error.yml
- kong/db/errors.lua
- kong/db/schema/others/declarative_config.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
This makes a change to the shape/structure of dbless errors. Before this change, an upstream with duplicate targets would yield a response like this:
```json
{
"code": 14,
"fields": {
"targets": [
null,
"uniqueness violation: 'targets' entity with primary key set to '48322e4a-b3b0-591b-8ed6-fd95a6d75019' already declared"
]
},
"message": "declarative config is invalid: {targets={[2]=\"uniqueness violation: 'targets' entity with primary key set to '48322e4a-b3b0-591b-8ed6-fd95a6d75019' already declared\"}}",
"name": "invalid declarative configuration"
}
```
This is bad because the error-flattening code cannot associate this error with the input. The linkage between the upstream->target from the input has been lost.
After this change, the errors are nested under the parent upstream:
```json …
```
> fix(dbless): nest duplicate entity primary key errors for children

- changelog/unreleased/kong/fix-wasm-disable-pwm-lua-resolver.yml
- kong/conf_loader/init.lua
- spec/01-unit/04-prefix_handler_spec.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
We need to disable this for the time being, as coroutine scheduling issues in the Wasm/Lua bridge are addressed in ngx_wasmx_module.
* https://github.com/Kong/ngx_wasm_module/issues/524
> fix(wasm): disable Lua DNS resolver for proxy-wasm

- changelog/unreleased/kong/bump-lua-resty-http-0.17.2.yml
- kong-3.7.0-0.rockspec
Backports the lua-resty-http bump from EE to CE:
https://github.com/Kong/kong-ee/pull/8424
> chore(deps): bump lua-resty-http to 0.17.2

- .requirements
- build/libexpat/repositories.bzl
- changelog/unreleased/kong/bump-libexpat.yml
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt
- scripts/explain_manifest/fixtures/debian-10-amd64.txt
- scripts/explain_manifest/fixtures/debian-11-amd64.txt
- scripts/explain_manifest/fixtures/debian-12-amd64.txt
- scripts/explain_manifest/fixtures/el7-amd64.txt
- scripts/explain_manifest/fixtures/el8-amd64.txt
- scripts/explain_manifest/fixtures/el9-amd64.txt
- scripts/explain_manifest/fixtures/el9-arm64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
```
Release 2.6.0 Tue February 6 2024
Security fixes:
#789 #814  CVE-2023-52425 -- Fix quadratic runtime issues with big tokens
that can cause denial of service, in partial where
dealing with compressed XML input.  Applications
that parsed a document in one go -- a single call to
functions XML_Parse or XML_ParseBuffer -- were not affected.
The smaller the chunks/buffers you use for parsing
previously, the bigger the problem prior to the fix.
Backporters should be careful to no omit parts of
pull request #789 and to include earlier pull request #771,
in order to not break the fix.
#777  CVE-2023-52426 -- Fix billion laughs attacks for users
compiling *without* XML_DTD defined (which is not common).
Users with XML_DTD defined have been protected since
Expat >=2.4.0 (and that was …
```
> chore(deps): bump libexpat from 2.5.0 to 2.6.2

- changelog/unreleased/kong/bump-lua-resty-acme.yml
- kong-3.7.0-0.rockspec
- **autossl:** log the errors on the list certificates request ([#110](https://github.com/fffonion/lua-resty-acme/issues/110)) [6c9760f](https://github.com/fffonion/lua-resty-acme/commit/6c9760f21d38fccd7971a70019afc5fe1fc6f1be)
- **autossl:** add option to delete none whitelisted domains in certificate renewal ([#112](https://github.com/fffonion/lua-resty-acme/issues/112)) [1bbf39c](https://github.com/fffonion/lua-resty-acme/commit/1bbf39c84de90a54a3f61b3ee2e331e613eb5e7a)
KAG-4330
> chore(deps): bump resty.acme from 0.12.0 to 0.13.0

- changelog/unreleased/kong/update-ai-proxy-telemetry.yml
- kong/llm/drivers/shared.lua
- kong/plugins/ai-request-transformer/handler.lua
- kong/plugins/ai-response-transformer/handler.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/03-plugins/39-ai-request-transformer/02-integration_spec.lua
- spec/03-plugins/40-ai-response-transformer/02-integration_spec.lua
This PR is a fixed of https://github.com/Kong/kong/pull/12583
We need to refactor as many observability providers do not simplify ingest array. Here is a new nested format:
Current model is:
```json
"ai": {
"mistral": {
"request_total_tokens": 648,
"number_of_instances": 1,
"instances": [
{
"meta": {
"request_model": "mistral-tiny",
"plugin_id": "1c783122-0223-4a03-9f1d-c71d2baab01e",
"response_model": "mistral-tiny",
"provider_name": "mistral"
},
"usage": {
"prompt_token": 392,
"total_tokens": 648,
"completion_token": 256
}
}
],
"request_prompt_tokens": 392,
"request_completion_tokens": 256
},
"azure": {
"request_total_tokens": 145,
"number_of_instances": 1,
"instances": [
{
"meta": {
"request_model": "gpt-35-turbo",
"plugin_id": "5df193be-47a3-4f1b-8c37-37e31af0568b",
"response_model": …
```
> fix analytics with new format

- kong/resty/dns/client.lua
The `force_no_sync` option was missing in the recursive calls to `execute_toip()`.
Skipping the changelog entry on this PR, as it is a fix for a feature not yet released.
KAG-3795
> fix(dns): keep the force no sync option on recursive toip calls

- build/openresty/patches/lua-cjson-2.1.0.13_01-error-on-t_end.patch
- changelog/unreleased/kong/fix-cjson-t-end.yml
middle
https://github.com/Kong/lua-cjson/pull/1
KAG-4275
> fix(cjson): port cjson fix that throws error when T_END found in the

- kong/router/transform.lua
- spec/01-unit/08-router_spec.lua
The original `split_routes_and_services_by_path()` will create a new table to contains all routes even if no splitting.
To erase this overhead, now `split_routes_and_services_by_path()` will insert the cloned routes directly into the passed in table.
KAG-4138
> refactor(router/atc): do not create new table in `split_routes_and_services_by_path()`

- changelog/unreleased/kong/wasm-bundled-filters.yml
- kong.conf.default
- kong/conf_loader/constants.lua
- kong/conf_loader/init.lua
- kong/constants.lua
- kong/templates/kong_defaults.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/20-wasm/06-clustering_spec.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
- spec/02-integration/20-wasm/08-declarative_spec.lua
An upcoming Kong release will ship with at least one bundled Wasm filter.
Previously there was no concept of "bundled" filters: all filters must be provided by the user in the `wasm_filters_path` directory.
This introduces a new `wasm_filters` kong.conf property. It is a comma-delimited array that functions quite similarly to the `plugins` property with the addition of a special `user` value:
```
wasm_filters = off
wasm_filters = bundled
wasm_filters = user
wasm_filters = bundled, user
wasm_filters = some_bundled_filter, some_user_supplied_filter
```
In the case of a collision between bundled and user filters, the conf loader will prefer the user filter and log a warning.
KAG-4211
> feat(wasm): support bundled filters

- changelog/unreleased/kong/feat-add-workspace-label-to-prometheus.yml
- kong/pdk/log.lua
- kong/plugins/prometheus/exporter.lua
- spec/03-plugins/26-prometheus/02-access_spec.lua
- spec/03-plugins/26-prometheus/03-custom-serve_spec.lua
- spec/03-plugins/26-prometheus/04-status_api_spec.lua
- spec/03-plugins/26-prometheus/05-metrics_spec.lua
add workspace label to the real-time metrics.
FTI-5573
> feat(prometheus): add workspace label to the real time metrics

- .github/workflows/changelog-requirement.yml
> chore(deps): bump tj-actions/changed-files to 44.0.0

- .bazelrc
- build/BUILD.bazel
- build/openresty/snappy/BUILD.bazel
> fix(build): fix snappy shared library build on macOS

- .github/labeler.yml
- changelog/unreleased/kong/plugins-add-standard-webhooks.yml
- kong-3.7.0-0.rockspec
- kong/constants.lua
- kong/plugins/standard-webhooks/handler.lua
- kong/plugins/standard-webhooks/internal.lua
- kong/plugins/standard-webhooks/schema.lua
- spec/01-unit/12-plugins_order_spec.lua
- spec/03-plugins/44-standard-webhooks/01-unit_spec.lua
- spec/03-plugins/44-standard-webhooks/02-integration_spec.lua
This PR adds the plugin for validating payloads using the [standard-webhooks](https://github.com/standard-webhooks/standard-webhooks) specification.
> feat(plugins): standard-webhooks

- kong/clustering/rpc/concentrator.lua
- spec/02-integration/18-hybrid_rpc/04-concentrator_spec.lua
- spec/fixtures/template_inject/nginx_kong_test_custom_inject_http.lua
review address and adds tests for concentrator. This fixes error like:
```
concentrator.lua:237: [rpc] concentrator event loop error: wait_for_notification error: receive_message: failed to get type: timeout, reconnecting in 8 seconds, context: ngx.timer
```
Note: the `reuseport` change for testing fixture is needed in order to run two CP at the same time in our testing suite.
[KAG-623]
[KAG-623]: https://konghq.atlassian.net/browse/KAG-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(clustering/rpc): fix incorrect `is_timeout()` call introduced during

- changelog/unreleased/kong/add-ai-data-report.yml
- kong/init.lua
- kong/reports.lua
- spec/02-integration/22-ai_plugins/01-reports_spec.lua
This PR will add new AI analytics into the PING anonymous report
> feat(ai): improve analytics report

- build/openresty/patches/ngx_lua-0.10.26_04-head-request-smuggling.patch
- build/openresty/patches/ngx_lua-0.10.26_05-setkeepalive-data-integrity.patch
- build/openresty/patches/ngx_lua-0.10.26_06-ngx-arg-connection-close.patch
- build/openresty/patches/ngx_stream_lua-0.0.14_04-setkeepalive-data-integrity.patch
- build/openresty/patches/ngx_stream_lua-0.0.14_05-ssl-context.patch
- https://github.com/openresty/lua-nginx-module/commit/e5248aa8203d3e0075822a577c1cdd19f5f1f831
- https://github.com/openresty/lua-nginx-module/commit/e2067ddd2b2897d3c6fa6f91ce4e8169fe8c97c6
- https://github.com/openresty/lua-nginx-module/commit/6c00bd4765ec5f7bf090a2c6424d11845fc4ab72
- https://github.com/openresty/stream-lua-nginx-module/commit/cb82db3574f42fd3f22f98c51f5183e975eaa766
- https://github.com/openresty/stream-lua-nginx-module/commit/bea8a0c0de94cede71554f53818ac0267d675d63 (this may not be necessary as we are not having the nginx 1.25.5 as of now, but doesn't hurt either)
KAG-4379
> chore(patches): add patches from upstream openresty

- DEVELOPER.md
- changelog/unreleased/kong/feat-emmy-debugger.yml
- kong-3.7.0-0.rockspec
- kong/init.lua
- kong/tools/emmy_debugger.lua
The change provides a hook in the init_worker phase to start the EmmyLua debugger.  The debugger is enabled by setting the `KONG_EMMY_DEBUGGER` to the absolute pathname of the EmmyLuaDebugger shared library (e.g. /usr/local/bin/emmy_core.dylib).  The host and port that the debugger interface listens on can be defined by setting the `KONG_EMMY_DEBUGGER_HOST` and `KONG_EMMY_DEBUGGER_PORT` environment variables, respectively.
If the environment variable `KONG_EMMY_DEBUGGER_WAIT` is set, the debugger hook waits for the IDE to connect at the beginning of the worker startup process to allow debugging of startup issues.
Kong should be started with`KONG_NGINX_WORKER_PROCESSES` set to 1 to enable only one worker process.  Debugging multiple worker processes is not supported.
This feature is based …
> feat: add EmmyLuaDebugger hook

- changelog/unreleased/kong/feat-hybrid-sync-mixed-route-policy.yml
> docs(changelog): add changelog entry for #12814

- changelog/unreleased/kong/feat-emmy-debugger.yml
- kong/tools/emmy_debugger.lua
Add a warning to point out that the EmmyLua debugger integration is not supported at this point.
KAG-4404
> fix(emmy-lua-debugger): add support status warning for feature

- Makefile
When running tests, this target allows one to show the logs of the running tests. Simply by open another terminal and doing `make test-logs`.
> chore(makefile): add target 'test-logs' to show test logs

- changelog/unreleased/kong/fix-grpc-gateway-json-decode-bug.yml
- kong/plugins/grpc-gateway/deco.lua
- kong/plugins/grpc-gateway/handler.lua
- spec/03-plugins/28-grpc-gateway/01-proxy_spec.lua
> fix(plugins/grpc-gateway):handle json decode error safely(#10028)

- changelog/unreleased/kong/cp-dp-rpc.yml
- changelog/unreleased/kong/dynamic-log-level-rpc.yml
- kong/conf_loader/init.lua
- kong/templates/kong_defaults.lua
- spec/01-unit/04-prefix_handler_spec.lua
- spec/02-integration/18-hybrid_rpc/01-rpc_spec.lua
- spec/02-integration/18-hybrid_rpc/02-log-level_spec.lua
- spec/02-integration/18-hybrid_rpc/04-concentrator_spec.lua
The new hybrid RPC still requires some additional changes before it is ready for GA. This disables cluster RPC and does not allow it to be re-enabled. This feature will be enabled in a future release.
Fix: KAG-4407
> fix(rpc): disable cluster_rpc for 3.7

- changelog/unreleased/kong/fix-migrations-for-redis-plugins-acme.yml
- changelog/unreleased/kong/fix-migrations-for-redis-plugins-response-rl.yml
- changelog/unreleased/kong/fix-migrations-for-redis-plugins-rl.yml
- kong/plugins/acme/migrations/003_350_to_360.lua
- kong/plugins/rate-limiting/migrations/006_350_to_360.lua
- kong/plugins/response-ratelimiting/migrations/001_350_to_360.lua
- spec/05-migration/plugins/acme/migrations/003_350_to_360_spec.lua
"UP" phase should only contain non-destructive operations. "TEARDOWN" (or "FINISH") phase should be used to change/delete data.
KAG-4419
https://github.com/Kong/kong/issues/12978
> fix(migrations): split redis migrations into up and teardown

- .github/workflows/label-schema.yml
Update rtBot to overwrite its message with the PR title, which is currently in the footer, and update the footer with the PR link. The existing message does not provide a clear understanding of the schema-related changes. This change will allow us to open the schema files directly from the message footer.
> chore(workflows): label-schema to overwrite slack message with pr title and footer as pr link

- kong/plugins/acme/migrations/003_350_to_360.lua
- kong/plugins/rate-limiting/migrations/006_350_to_360.lua
- kong/plugins/response-ratelimiting/migrations/001_350_to_360.lua
The migrations should be reentrant. This migration was working well on it's own but it tried to pull data from "old" columns. However if a user runs `kong migrations finish` and then `kong migrations up -f` it would have tried to pull data from nonexisting columns overwriting it's current data. Therefore we need those COALESCE statements so that if the "old" data is not there then it tries to read it from the "new" columns.
[KAG-4419](https://konghq.atlassian.net/browse/KAG-4419)
[KAG-4419]: https://konghq.atlassian.net/browse/KAG-4419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(migration): make redis schema migrations reentrant

- kong/plugins/ai-prompt-template/handler.lua
- kong/plugins/ai-prompt-template/templater.lua
- spec/03-plugins/43-ai-prompt-template/01-unit_spec.lua
- spec/03-plugins/43-ai-prompt-template/02-integration_spec.lua
the changelog is omitted, can go with the same entry as #12907
> fix(plugin): cleanup and fix error handling

- kong/llm/drivers/llama2.lua
- kong/llm/drivers/mistral.lua
Fixes "Unexpected error" when using self-hosted Llama2 or Mistral models. Path parsing was incomplete, resulting in Kong trying to `gsub` a nil table reference.
https://github.com/Kong/kong/issues/12869
> fix(ai-proxy): internal server error on path parse failure

- kong/clustering/compat/removed_fields.lua
Add azure fields to removed_fields.lua to address CP/DP version compatibility issue reported at https://konghq.atlassian.net/browse/KAG-4356
Fix https://konghq.atlassian.net/browse/KAG-4356
> fix(ai-proxy): removed compat fields pre-3.7

- kong-3.8.0-0.rockspec
- kong/meta.lua
Bump version to 3.8 as part of the feature freeze.
KAG-4455
> chore(release): bump version to 3.8 as part of the feature freeze

- spec/busted-ci-helper.lua
require 'socket.unix' was causing a different socket module to be loaded
If 'socket.unix' was loaded before the `socket` module, it resulted in a different socket implementation to be used, which resulted in failures when trying to access nil fields of the socket object.
KAG-4472
> fix(ci): require correct `socket` module

- changelog/unreleased/kong/fix-dns-ignore-records-with-non-matching-types.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/01-unit/21-dns-client/03-client_cache_spec.lua
Originally, Kong dns client will store records with non-matching domain/type when parsing answers. For instance, if Kong queried a domain with A type, and received CNAME+A records, Kong would store the CNAME record in its cache. Consequently, this would lead to subsequent queries for CNAME records, which is unnecessary behavior for a DNS client.
This fix will remove records with non-matching types, such as CNAME records from the answers of an A query.
Fix KAG-4446, FTI-5834
> fix(dns): ignore records with non-matching types when parsing answers

- kong/router/transform.lua
Just a slightly tighter code and reusing table.
This was originally proposed at #12901 for inclusion in #12875.
> refactor(router/atc): cleanup split routes and services

- changelog/unreleased/kong/fix-aws-lambda-gateway-compat-version-field.yml
- kong/plugins/aws-lambda/request-util.lua
- spec/03-plugins/27-aws-lambda/05-aws-serializer_spec.lua
This PR adds a missing `version` field into the `aws-lambda` plugin's `awsgateway_compatible` payload.
The `awsgateway_compatible` field provides a way to send a wrapped request body which is compatible with the format of AWS API gateway's proxy integration. The format of the payload is described here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format
Some framework/projects that used to build Lambda function may check the `version` field sent by API gateway, so that they can apply different extracting logic according to different versions of payload. For example the logic in `mangum` looks like: https://github.com/jordaneremieff/mangum/blob/6086c268f32571c01f18e20875430db14a0570bc/mangum …
> fix(aws-lambda): add missing version field into aws gateway compatible payload

- changelog/unreleased/kong/bump-lua-resty-healthcheck.yml
- kong-3.8.0-0.rockspec
Bumps `lua-resty-healthcheck` to 3.0.2.
Changelogs:
> What's Changed
fix(*): avoid creating multiple timers to run the same active check
https://github.com/Kong/lua-resty-healthcheck/pull/157
FTI-5847
> chore(deps): bump lua-resty-healthcheck to 3.0.2

- build/BUILD.bazel
ported from https://github.com/Kong/kong-ee/pull/8843
> fix(build): remove the original websocket library from openresty

- changelog/unreleased/kong/fix-base64-cluster-cert.yml
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
Backporting https://github.com/Kong/kong/pull/11385
(cherry picked from commit 07475c431246bf9ec02181a3086b98e8c478e176)
Fix https://konghq.atlassian.net/browse/FTI-5953
> [backport -> release/3.4.x] fix(conf_loader): cluster_cert/cluster_ca_cert to support base64 encoded values (#11385)

- kong/conf_loader/init.lua
A very small code clean, should be easy to review.
> style(conf_loader): use localized `lower()` properly

- spec/03-plugins/17-ip-restriction/02-access_spec.lua
DO NOT CHERRY-PICK THIS PR TO EE! A corresponding PR is intentionally manually created: https://github.com/Kong/kong-ee/pull/9162
Fix KAG-4523
> tests(plugin): a more reliable way to wait for config update

- changelog/unreleased/kong/feat-dont-allow-priority-with-others.yml
- kong/db/schema/entities/routes.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
Notice: `regex_priority` and `priority` have the default value `0`, so we think `0` is equivalent  to "not set".
KAG-4411
> feat(db/schema): do not allow setting priority with traditional route in mixed mode

- spec/02-integration/03-db/08-declarative_spec.lua
> tests(db/declarative): bootstrap correctly to avoid corrupted table

- kong/clustering/compat/checkers.lua
some logic in checkers is made redundant by the fact [the same fields exist in removed_fields](https://github.com/Kong/kong/blob/d112f3c09bf049fe4614dc5f38e45cba5adce0f7/kong/clustering/compat/removed_fields.lua#L128-L137). This commit removes the redundant logic
KAG-4457
> chore(clustering): cleanup redundant checkers

- changelog/unreleased/kong/cleanup_ai.yml
- changelog/unreleased/kong/log-serializer-kong-latency.yml
Improve two changelog entries.
KAG-4422
> docs(changelog): apply suggestions

- spec/01-unit/21-dns-client/02-client_spec.lua
The original test cases calls `toip` with the default option: `order=LAST,SRV,A,CNAME`,  resulting in 3 queries (SRV, SRV-dereference(CNAME), A) each time we call toip, but it actually expects single query each time.
Fix KAG-4520
> tests(dns): fix the flakiness of the individual_toip test case

- changelog/unreleased/kong/fix-request-transformer-uri-replace.yml
- kong/router/atc.lua
- spec/01-unit/08-router_spec.lua
- spec/03-plugins/36-request-transformer/02-access_spec.lua
URI captures are not usable if the first capture is an empty string.
Fix #13014, KAG-4474
> fix(router/atc): uri replace didn't works well if contains the optional group

- kong/dynamic_hook/init.lua
- kong/init.lua
- kong/resty/dns/client.lua
- kong/runloop/handler.lua
Please review commit-by-commit. This PR did some style cleaning, fixed some bugs, and removed unused features.
_[KAG-4590]_
[KAG-4590]: https://konghq.atlassian.net/browse/KAG-4590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> dynamic_hook: cumulative changes

- DEVELOPER.md
- bin/busted
- kong/tools/emmy_debugger.lua
Support debugging of busted tests with EmmyLua.  Debugging busted tests is controlled by a separate set of environment variables to not interfere with debugging Kong Gateway itself.  This PR also enables debugging multiple workers and adds more documentation.
KAG-4584
> feat(emmy-lua-debugger): support busted & multi worker debugging + docs

- kong/router/transform.lua
Small code clean with early return and some comments.
KAG-4138
> style(router/atc): simplify sni transform code

- kong/dynamic_hook/README.md
- kong/dynamic_hook/init.lua
Adds a readme for the dynamic hooks core feature and reference docs in the code
[KAG-4552](https://konghq.atlassian.net/browse/KAG-4552)
[KAG-4552]: https://konghq.atlassian.net/browse/KAG-4552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(dynamic-hooks): add dynamic hooks documentation

- changelog/unreleased/kong/fix-age-header.yml
- kong-3.8.0-0.rockspec
- kong/clustering/compat/checkers.lua
- kong/plugins/proxy-cache/clustering/compat/response_headers_translation.lua
- kong/plugins/proxy-cache/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
The age parameter on the schema was in lower case which caused the header Age to appear only when the kong debug option was enabled. This commit changes the schema parameter from age to Age.
Fix #12787
> fix(proxy-cache): changes age param

- spec/01-unit/19-hybrid/03-compat_spec.lua
KAG-4440
This is a follow up of #13008.
> tests(hybrid): reset schema for correct bootstrap

- kong-3.7.1-0.rockspec
- kong/meta.lua
> chore(release): update version to 3.7.1 as part of the GA release

- kong/tools/uri.lua
We already have localized `table_new`, use it directly.
> style(tools/uri): use `table.new` correctly

- kong/runloop/balancer/init.lua
- spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua
Before this PR we use `ngx.req.get_headers()` to get all possible header values as identifier,
but since nginx 1.23.0 or OpenResty  1.25.3.1 `ngx.var` can get a combined value for all header values 
with identical name (joined by comma), so I think that we could simplify these code. 
KAG-4572
> refactor(balancer): get headers as hash identifier by ngx.var

- .requirements
The comments were wrong about versions used for brotli and ngx_brotli.
> chore(.requirements): fix comments on brotli

- kong/pdk/client/tls.lua
Access to `tls  table was missing
> docs(pdk): fix a typo in kong.client.tls comment

- changelog/unreleased/kong/bump-lua-resty-acme.yml
- kong-3.8.0-0.rockspec
- ***:** provide better robustness when waiting for DNS propagation [3ce2614](https://github.com/fffonion/lua-resty-acme/commit/3ce261462ff91deda67bd541fcd35ad924169a36)
- ***:** cleanup API for dns-01 challenge [a1b43f1](https://github.com/fffonion/lua-resty-acme/commit/a1b43f1a7980ee4f88a3cfe3ab7b1bd5a46471be)
- ***:** support dns-01 challenge [67a5711](https://github.com/fffonion/lua-resty-acme/commit/67a5711d6e1bd0f36735fd4ffcf53141bb73a0f6)
- **autossl:** support create wildcard cert in SAN [8ed36c3](https://github.com/fffonion/lua-resty-acme/commit/8ed36c3a959a759356c608a4f385a5dcc3f887df)
- **dns-01:** add dnspod-intl provider [0c12f89](https://github.com/fffonion/lua-resty-acme/commit/0c12f89f3d54f1f935fd12a0a148a7aa136dd482)
- **dns-01:** add cloudflare and dynv6 DNS provider …
> chore(deps): bump resty.acme from 0.13.0 to 0.14.0

- changelog/unreleased/kong/bump-lua-resty-openssl.yml
- kong-3.8.0-0.rockspec
- **ec:** add missing cdef for EC_POINT_free [2093e88](https://github.com/fffonion/lua-resty-openssl/commit/2093e8814ccfbe830ba594a71f05870cac208e9c)
- **pkey:** allow pkey.new to compose from parameters [91a30f6](https://github.com/fffonion/lua-resty-openssl/commit/91a30f6988e3fc696363ce1445b49a3f6ee8f35e)
- **pkey:** add pkey:verify_raw [0016308](https://github.com/fffonion/lua-resty-openssl/commit/0016308c9e3a2ccfdfe674ede64e462060f7b13b)
KAG-4615
KAG-4620
> chore(deps): bump resty.openssl from 1.3.1 to 1.4.0

- changelog/unreleased/host_header.yml
- kong/runloop/balancer/init.lua
- spec/02-integration/05-proxy/03-upstream_headers_spec.lua
fix a bug that the `host_header` can not be set correctly as Host header in requests to upstream when retries happen 
FTI-5987
> fix(core/balancer): fix a bug that the `host_header` not set correctly

- changelog/unreleased/kong/feat-response-transformer-json-rename.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/response-transformer/body_transformer.lua
- kong/plugins/response-transformer/header_transformer.lua
- kong/plugins/response-transformer/schema.lua
- spec/01-unit/01-db/01-schema/07-plugins_spec.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/15-response-transformer/01-header_transformer_spec.lua
- spec/03-plugins/15-response-transformer/02-body_transformer_spec.lua
- spec/03-plugins/15-response-transformer/03-api_spec.lua
reopened: https://github.com/Kong/kong/pull/12888 (by: [zhongweikang](https://github.com/zhongweikang), closed by mistake)
> feat(plugin/response-transformer): added support for json_body rename 

- .github/labeler.yml
Ensure that schema changes for AI plugins are tagged with `schema-change-noteworthy` so that the notification is sent to `#gateway-schema-change-feed` Slack channel.
> ci: label `schema-change-noteworthy` for AI plugin PR

- changelog/unreleased/kong/fix-http-log-host-header.yml
- kong/plugins/http-log/handler.lua
- spec/03-plugins/03-http-log/01-log_spec.lua
Add port to host header when non-default port is used.The log server receives requests with a host header that does not include the port number
Fix #13067
> fix(http-log): add port information to the host header

- changelog/unreleased/kong/improve-prometheus-error-logging.yml
- kong/plugins/prometheus/prometheus.lua
Currently, the Prometheus plugin will log the following error if we have encountered an inconsistent label count while debugging:
```
[error]... inconsistent labels count, expected 6, got 5
```
It's hard to identify which metric is going wrong, and it will be helpful if we can bring the metric name as well:
```
[error]... metric 'bandwidth_bytes' has the inconsistent labels count, expected 6, got 5
```
> fix(prometheus): improve logging when having the inconsistent labels count

- kong/db/schema/entities/routes.lua
- kong/router/compat.lua
- kong/router/expressions.lua
- kong/router/transform.lua
Simplify the code, moving some logic into `transform.lua`.
KAG-4138
> refactor(router/atc): unify expression validation function in schema

- Makefile
- The Go version now supports BAZELISK_NOJDK
- It's now easier to use Bazelisk programmatically
- Bazelisk will retry more connection errors
- A display bug in the download progress bar has been fixed
KAG-4615
KAG-4624
> chore(deps): bump bazelisk from 1.19.0 to 1.20.0

- Makefile
- Add builtin standards support for minetest — @BuckarooBanzay and @appgurueu
- Memoize results to addresses speed refression from new feature in v0.26 — @tomlau10
KAG-4615
KAG-4621
> chore(deps): bump luacheck from 1.1.2 to 1.2.0

- changelog/unreleased/kong/feat-aws-lambda-decode-empty-array.yml
- kong-3.8.0-0.rockspec
- kong/clustering/compat/removed_fields.lua
- kong/plugins/aws-lambda/handler.lua
- kong/plugins/aws-lambda/request-util.lua
- kong/plugins/aws-lambda/schema.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/fixtures/aws-lambda.lua
This PR adds a new configuration field `empty_arrays_mode` to control the behaviour that whether Kong will transform an empty array `[]`(returned by Lambda function) into an empty object `{}` when enabled aws-lambda plugin in the response.
**Essentially** this PR is just a small bugfix for not previously enabling `decode_array_with_array_mt` when decoding Lambda function's response. However, enabling `decode_array_with_array_mt` may bring unexpected behaviour changes on the user side(since the wrong behaviour itself has existed for long), so we decided to add a new field to keep backward compatibility, and remove this field in the next major version to let the correct behaviour(keep empty arrrays as is) to become the default behaviour in the next major version.
FTI-5937
> feat(aws-lambda): add new configuration field `empty_arrays_mode` to control empty array decoding behavior

- build/repositories.bzl
See: https://github.com/cli/cli/releases
KAG-4615
KAG-4618
> chore(deps): bump github-cli from 2.30.0 to 2.50.0

- .github/workflows/release.yml
- Stop generating the latest-ubuntu image on non-default branches.
- Rerunning the old commit action on the default branch will not generate latest-ubuntu.
KAG-4374
> chore(ci): generate the Docker tag latest-ubuntu only for the latest commit on the default branch

- kong/api/api_helpers.lua
- kong/db/schema/typedefs.lua
- kong/error_handlers.lua
- kong/pdk/response.lua
- kong/plugins/response-transformer/schema.lua
- kong/tracing/propagation/schema.lua
- spec/01-unit/05-utils_spec.lua
> refactor(tools/http): update references from `kong.tools.utils` to `kong.tools.http`

- kong/plugins/file-log/handler.lua
- kong/tools/utils.lua
- spec/helpers.lua
- spec/helpers/http_mock/nginx_instance.lua
This is a follow up of #13156, clean some references of `tools.utils`.
KAG-3136
> refactor(tools): update references of `tools.utils` to correct module

- spec/helpers.lua
> tests(helpers): specify a larger buffer to avoid read stalling issues caused by insufficient buffer size

- bin/kong
- changelog/unreleased/kong/fix-cmd-error-log.yml
- spec/02-integration/02-cmd/16-verbose_spec.lua
- spec/helpers.lua
This PR fixes a problem that running `kong` CLI command will not print some of the debug level error logs. Those error logs may be triggered by `ngx.log` before the actual `kong.cmd` module gets called. 
The issue in this PR was discovered when debugging FTI-5995, but it is not related to the ticket's problem at all.
> fix(cmd): fix kong cli not printing some debug level error log

- kong/conf_loader/init.lua
The "jo" option could optimize the execution of regex.
> style(conf_loader): add "jo" option for ngx.re.sub

- spec/02-integration/02-cmd/16-verbose_spec.lua
Fixed the CI failure when cherry-picking https://github.com/Kong/kong-ee/pull/9382
When `meta._VERSION` contains `-`, it will be regarded as magic character which is not expected.
This PR fixes the test to let it use plain matches. Note that CE does not have this issue because CE's `meta._VERSION` does not contain magic character
> tests(cmd): match kong version in cmd verbose test should use plain match

- kong/pdk/log.lua
* Some micro optimization for performance.
* Add a hidden flag for `kong.log.serialize()` to skip fetching req/resp headers.
This PR is the pre-requirement of https://github.com/Kong/kong-ee/pull/9084.
_[KAG-4271]_
[KAG-4271]: https://konghq.atlassian.net/browse/KAG-4271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PDK: Cumulative changes

- build/nfpm/repositories.bzl
See: https://github.com/goreleaser/nfpm/releases
KAG-4615
KAG-4617
> chore(deps): bump nfpm from 2.31.0 to 2.37.1

- changelog/unreleased/kong/fix-ai-proxy-shared-state.yml
- kong-3.8.0-0.rockspec
- kong/llm/init.lua
- kong/llm/schemas/init.lua
- kong/plugins/ai-proxy/handler.lua
- kong/plugins/ai-request-transformer/handler.lua
- kong/plugins/ai-response-transformer/handler.lua
- spec/03-plugins/39-ai-request-transformer/01-transformer_spec.lua
- spec/03-plugins/40-ai-response-transformer/01-transformer_spec.lua
- spec/03-plugins/40-ai-response-transformer/02-integration_spec.lua
The object initializer (new) would set properties on class instead of on the instance. Also cleans up some code.
I have added comments on the actual bug, everything else is cosmetic/cleanup. Please review with whitespace changes disabled in the github UI.
Internal ticket: AG-44
> fix(ai-proxy): prevent shared state

- .github/workflows/release.yml
> chore(ci): use github.sha in push event to get latest commit SHA from default branch

- kong/tools/http.lua
- spec/01-unit/05-utils_spec.lua
- t/01-pdk/05-client/08-get_protocol.t
We used to call `ngx.req.get_headers()` to get all possible header values,
but since nginx 1.23.0 or OpenResty 1.25.3.1 `ngx.var` can get a combined value for all header values
with identical name (joined by comma), so I think that we could simplify these code.
There is one concern:
If header `X-Forwarded-Proto` has a comma separated value like `http, https`, 
This PR will think it is a multiple header request and report an error `Only one X-Forwarded-Proto header allowed`.
But I think that it is an unlikely case in the real world.
KAG-4673
> refactor(tools/http): simplify check_https() with ngx.var

- kong-3.8.0-0.rockspec
- kong/conf_loader/init.lua
- kong/conf_loader/sys.lua
This refactor will make the code of conf loader easier to maintain.
KAG-4638
> refactor(conf_loader): separate system functions from conf loader

- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
Generating entries is expensive in some cases,
so we'd better have a way to observe the state of the Queue.
So we are able to skip generating if the Queue is already or will be full.
This is the pre-requirement of https://github.com/Kong/kong-ee/pull/9273.
_[KAG-4270]_
[KAG-4270]: https://konghq.atlassian.net/browse/KAG-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(queue): implement functions `Quque.is_full` & `Queue.can_enqueue`

- kong/tools/emmy_debugger.lua
We prefer vararg-style calls for ngx.log.
KAG-4673
See:https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#strings
> style(tools/emmy_debugger): prefer vararg-style for ngx.log

- changelog/unreleased/kong/fix-realm-compat-changes-basic-auth.yml
- kong/clustering/compat/removed_fields.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
Manual backport of https://github.com/Kong/kong/pull/13042 to `release/3.6.x` due to the fact that the original PR fixed basic-auth and key-auth but key-auth changes were introduced in newer (3.7) version.
Basic-auth and key-auth added new field "realm" but it was not added to "removed_fields" which breaks backwards compat between new CPs and old DPs. Adding realm to removed fields fixes the issue.
KAG-4516
> [backport -> release/3.6.x] fix(plugins): add realm to removed fields

- .github/workflows/deck-integration.yml
- spec/06-third-party/01-deck/01-deck-integration_spec.lua
These tests are meant to catch changes in Kong that result in incompatibilities with decK.
The approach used here is to configure all the bundled plugins in Kong and a few other entities and confirm that deck dump + sync executes without errors.
This new workflow "continues-on-error" instead of producing failures on CI: changes in gateway schemas might have to be merged despite making decK fail, the purpose of this is to notify about such incompatibilities. When those failures are detected, the workflow posts a review in the PR requesting changes, and a link to the failing run.
~The review is then dismissed if new changes are pushed to the PR that make the workflow pass.~ <-- not anymore: branch protection rules prevent this
[KAG-4236](https://konghq.atlassian.net/browse/KAG-4236) …
> tests(deck): add deck integration tests

- .github/workflows/build_and_test.yml
- spec/helpers.lua
> tests(ci): copy and upload failed test logs

- CHANGELOG.md
Assemble changelog entries into a central place CHANGELOG.md.
KAG-4666
> docs(changelog): assemble changelog entries into a central place

- kong/tools/string.lua
With simple microbenchmark:
```lua
ngx.update_time()
local s = ngx.now()
for i = 1, 100000 do
local a = strip("           \t \ndogestr   \f\t\r ")
end
ngx.update_time()
local e = ngx.now()
print("took: ", (e * 1000) - (s * 1000), " ms")
```
I get these results:
Current: `took: 57 ms`
PR: `took: 7 ms`
KAG-4684
> refactor(tools/string): speed up strip (whitespace)

- kong/pdk/log.lua
- t/01-pdk/02-log/05-set_serialize_value.t
Just some miscellaneous optimizations to log serializer:
- avoid unnecessary table creation and modification
- move variable creation closer to usage
- do not use tail calls
- remove EMPTY_TAB
- faster split by dot implementation
KAG-4728
> refactor(pdk/log): optimize log serialize

- kong/conf_loader/parse.lua
> style(conf_loader): minor code style clean

- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
Treating the non-existing queue instance has enough capacity for enqueueing (fixup https://github.com/Kong/kong/pull/13164)
_[KAG-4270]_
[KAG-4270]: https://konghq.atlassian.net/browse/KAG-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  fix(queue): function `Queue.can_enqueue` should handle non-existing queue instance correctly

- changelog/unreleased/kong/ldap_www_authenticate.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/ldap-auth/access.lua
- kong/plugins/ldap-auth/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/20-ldap-auth/01-access_spec.lua
When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Ldap auth was missing this header on some responses.
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11833
- add `WWW-Authenticate` header to all ldap 401 response
- Fix #7772
- KAG-321
> fix(ldap): add missing www-authenticate headers

- kong-3.8.0-0.rockspec
- kong/pdk/private/rate_limiting.lua
- kong/plugins/rate-limiting/handler.lua
- kong/plugins/response-ratelimiting/header_filter.lua
Currently, all rate-limiting-like plugins process their own response headers individually, we should unify this process by a private PDK function.
This PR is also for _[KAG-4679]_.
_[KAG-4679]_
[KAG-4679]: https://konghq.atlassian.net/browse/KAG-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAG-4679]: https://konghq.atlassian.net/browse/KAG-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
> feat(pdk): implement private PDK functions to process rate_limiting response headers

- .github/matrix-commitly.yml
- .github/matrix-full.yml
Github runner's "ubuntu-latest" will be bumped to ubuntu 24.04, thus build outside of docker results in artifacts targeting 24.04.
> chore(cd): build ubuntu jammy artifacts in docker

- build/openresty/BUILD.openresty.bazel
> chore(build): use wasmx_dynamic_mod to mark dynamic module as created

- changelog/unreleased/kong/hmac_www_authenticate.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/hmac-auth/access.lua
- kong/plugins/hmac-auth/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/19-hmac-auth/03-access_spec.lua
When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. HMAC auth was missing this header.
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11820
- https://github.com/Kong/kong/pull/11833
- add `WWW-Authenticate` header to hmac 401 response
- Fix #7772
- KAG-321
> fix(hmac): add missing www-authenticate headers

- kong/pdk/private/rate_limiting.lua
- kong/plugins/rate-limiting/handler.lua
- kong/plugins/response-ratelimiting/access.lua
- kong/plugins/response-ratelimiting/header_filter.lua
- t/01-pdk/16-rl-ctx.t
The rate-limiting-related headers have no fixed format, different plugins have different formats.
The goal of this private PDK is only to retrieve the RL context in a central place, so it should be enough.
[KAG-4679](https://konghq.atlassian.net/browse/KAG-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[KAG-4679]: https://konghq.atlassian.net/browse/KAG-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> refactor(pdk): simplify private RL pdk

- changelog/unreleased/kong/fix-propagation-remove-redundant-warnings.yml
- kong/tracing/propagation/init.lua
The propagation module logs some redundant warning messages that [are already printed](https://github.com/Kong/kong/blob/master/kong/plugins/opentelemetry/schema.lua#L75), when necessary, during schema validation, with logic that also checks the "old default" value. This commit removes the unnecessary messages.
KAG-4744
> fix(propagation): remove redundant warning messages

- .github/workflows/update-ngx-wasm-module.yml
Use the proper wording when auto-writing the changelog.
KAG-4671
> style(workflows): proper changelog wording

- kong/db/schema/init.lua
Just a small refactor on schema process auto fields, to move some vault reference resolving code outside of the already big process auto fields function.
KAG-4742
> refactor(schema): move some repetitive vault resolving code to local functions

- kong/pdk/private/rate_limiting.lua
- t/01-pdk/16-rl-ctx.t
The function `assert` doesn't show the caller of the PDK function when failed to validate incoming arguments. Invoking function `error` when unable to validate an argument can get a better error message.
_[KAG-4679]_
[KAG-4679]: https://konghq.atlassian.net/browse/KAG-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(pdk): show more friendly error msg when passing invalid arguments

- changelog/unreleased/kong/oauth2_www_authenticate.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/oauth2/access.lua
- kong/plugins/oauth2/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/25-oauth2/03-access_spec.lua
When kong returns `401 Unauthorized` response it should return `WWW-Authenticate` header with proper challenge. Oauth2 was missing this header on some responses.
- https://github.com/Kong/kong/pull/11791
- https://github.com/Kong/kong/pull/11794
- https://github.com/Kong/kong/pull/11795
- https://github.com/Kong/kong/pull/11820
- add `WWW-Authenticate` header to all oauth2 401 response
- Fix #7772
- KAG-321
> fix(oauth2): add missing www-authenticate headers

- kong/runloop/wasm.lua
This function can trigger a segfault if it is jit-compiled due to the semantics of making an FFI call to a C land function which in turn calls back into a Lua land function.
Fixes a condition introduced in https://github.com/Kong/kong/pull/13222.
No changelog entry required--the bug fixed by this change has not been released anywhere.
KAG-4671
> fix(wasm): disable jit for set_host_properties_handlers()

- changelog/unreleased/kong/ai-proxy-azure-streaming copy.yml
- changelog/unreleased/kong/ai-proxy-azure-streaming.yml
- changelog/unreleased/kong/ai-proxy-fix-model-parameter.yml
- changelog/unreleased/kong/ai-proxy-fix-nil-response-token-count.yml
- changelog/unreleased/kong/ai-proxy-fix-sending-own-model.yml
- changelog/unreleased/kong/ai-proxy-fix-tuning-parameter-precedence.yml
- changelog/unreleased/kong/ai-proxy-proper-model-assignment.yml
- kong/llm/drivers/anthropic.lua
- kong/llm/drivers/cohere.lua
- kong/llm/drivers/openai.lua
- kong/llm/drivers/shared.lua
- kong/plugins/ai-proxy/handler.lua
- spec/03-plugins/38-ai-proxy/01-unit_spec.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/03-plugins/38-ai-proxy/09-streaming_integration_spec.lua
Minor fix rollup from RC2, for function calling fixes and other broken AI config checks.
[KAG-4596](https://konghq.atlassian.net/browse/KAG-4596)
[KAG-4596]: https://konghq.atlassian.net/browse/KAG-4596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ai-proxy): Fix Cohere breaks with model parameter in body; Fix OpenAI token counting for function requests; Fix user sending own-model parameter

- changelog/unreleased/kong/traditional_router_header_validation.yml
- kong/db/schema/entities/routes.lua
- kong/db/schema/typedefs.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
> fix(core): Regex header values in traditional router are now validated

- spec/02-integration/06-invalidations/01-cluster_events_spec.lua
For the test scenario of broadcasting an event with a delay (`broadcast(..., ..., delay)`), we need to apply wait_until to stabilize the test. Note that https://github.com/Kong/kong/pull/12696 has fixed a similar issue, however, another one remains unresolved.
Fix KAG-4764
> tests(cluster_events): fix flaky due to too close time for a delay timer

- build/openresty/patches/LuaJIT-2.1-20231117_03_Revert_Detect_SSE4.2_support_dynamically.patch
- build/openresty/patches/LuaJIT-2.1-20231117_04_Revert_bugfix_fixed_compatibility_regression_with_Mi.patch
- build/openresty/patches/LuaJIT-2.1-20231117_05_Revert_Adjust_SSE4.1_str_hash_to_replace_hash_sparse.patch
- changelog/unreleased/fix_hash.yml
This change reverts some hash optimizations in LuaJIT
Fix KAG-4646
> perf(LuaJIT): revert optimization for hash

- CHANGELOG.md
> docs(changelog): assemble changelog entries into a central place 

- scripts/explain_manifest/main.py
cherry-pick from kong/kong-ee#9042
This PR doesn't need to be cherry-picked.
KAG-4775
> fix(ci): replace "cpio" rpm extraction

- .github/workflows/release.yml
Disable package upload to Pulp.
KAG-4776
> chore(ci): disable package upload to Pulp

- kong-2.8.5-0.rockspec
- kong/meta.lua
> chore(release): update version to 2.8.5

- changelog/unreleased/kong/fix-dns-ignore-records-with-non-matching-types.yml
- kong/resty/dns/client.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/01-unit/21-dns-client/03-client_cache_spec.lua
This reverts commit 40f43c9008eec553240255d919ae99aa3c8d7fb3.
The original change could cause issues with DNS responses containing additional section. Reverting it while the issue gets addressed.
FTI-6038
KAG-4446
FTI-5834
> Revert "fix(dns): ignore records with RR types differs from that of the query when parsing answers (#13002)"

- changelog/unreleased/kong/revert-dns-behavior.yml
Add changelog to reverted PR.
FTI-6039
> docs(changelog): documented dns client behavior revert

- build/package/nfpm.yaml
- changelog/unreleased/kong/add_zlib1g-dev.yml
Added missing zlib1g-dev dependency.
KAG-4786
> fix(package): add missing zlib1g-dev dependency

- .github/workflows/release.yml
Skip uploading centos packages to cloudsmith as cloudsmith doesn't support centos. Users should use rhel packages instead.
KAG-4786
> chore(ci): skip uploading centos packages to cloudsmith

- CHANGELOG.md
assemble 2.8.5 changelog into CHANGELOG.md
KAG-4786
> docs(changelog): assemble 2.8.5 changelog into CHANGELOG.md

- changelog/unreleased/kong/fix-ai-plugin-no-consumer.yml
- kong/plugins/ai-prompt-template/schema.lua
- kong/plugins/ai-proxy/schema.lua
- kong/plugins/ai-response-transformer/schema.lua
> fix(ai-plugins): remove no_consumer and no_service restriction on AI plugins

- kong/router/fields.lua
`ngx.var` is a relatively expensive operation in OpenResty, 
this PR tries to cache the result of `ngx.var` when we process TLS requests.
> refactor(router/atc): cache `ngx.var` result in stream routing

- kong/pdk/log.lua
Using varags-style for `string.buffer:put()` will make the code easy to read.
> style(pdk/log): simplify buffer:put with vararg-style

- changelog/unreleased/kong/fix-tracing-sampling-rate.yml
- kong/pdk/tracing.lua
- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
Kong generates a temporary trace ID when spans are created, this trace ID can be overwritten if tracing headers are passed in the request. Before this change, the global sampling rate from kong.conf was applied to the temporary trace ID, which was only valid for traces created by Kong, and not in distributed tracing scenarios.
This commit ensures the sampling decision always happens during the OTel plugin's access phase so that it is taken after headers have been read, when the trace id is final, to ensure Kong's sampling decision matches that of other tracing systems and therefore guarantee that traces are not broken when sampling rates are set to the same values.
[KAG-4785](https://konghq.atlassian.net/browse/KAG-4785)
[KAG-4785]: …
> fix(tracing): ensure sampling decisions apply to correct trace ID

- changelog/unreleased/kong/fix-acme-misleading-deprecation-logs.yml
- changelog/unreleased/kong/fix-response-rl-misleading-deprecation-logs.yml
- changelog/unreleased/kong/fix-rl-misleading-deprecation-logs.yml
- kong/db/schema/init.lua
- spec/02-integration/09-hybrid_mode/13-deprecations_spec.lua
- spec/03-plugins/23-rate-limiting/07-hybrid_mode_spec.lua
When running kong in hybrid mode with ACME plugin the configuration for the plugin is being pushed from CP to DP. When introducing shorthand field expansion to Admin API responses the deprecated fields (defined as shorthand fields) were also pushed from CP to DP which resulted in DP receiving config with both new fields and also old fields. It resulted with DP reporting in logs that ACME plugin is being configured with deprecated fields.
This PR disables the deprecation logs in DPs. The reasoning behind that is that those deprecation logs are not actionable on DP side and should be actually changed on CP if they were indeed configured improperly.
KAG-4515
> fix(redis): remove unnecessary redis config deprecation warnings in hybrid mode

- kong/db/schema/init.lua
After merging: https://github.com/Kong/kong/pull/13069 it was revealed in some tests that `kong` global might not have been initialized yet. This PR checks first if kong global is defined as it's done in a few other places in this module. It's just to make sure unit test work.
[KAG-4515](https://konghq.atlassian.net/browse/KAG-4515)
[KAG-4515]: https://konghq.atlassian.net/browse/KAG-4515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(core): should_warn checks if kong global has been defined

- kong.conf.default
The non-ASCII double quote will display as garbage if the locale of the terminal is not correctly set, which is something that can happen with Docker in some cases.
> chore(docs): replace non-ASCII quote in kong.conf.default with normal double quote

- kong-2.8.6-0.rockspec
- kong/meta.lua
Bump version to 2.8.6 as part of the 2.8.5 release.
KAG-4786
> chore(release): bump version to 2.8.6

- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/01-unit/21-dns-client/03-client_cache_spec.lua
The test suits hook the query function and uses a shared variable to change the hook. This causes conflicts when test A has an aysnc query still running, and B swaps the hook function, so the function will be called more than expected times.
Fix KAG-4519
> tests(dns): flakiness due to hook conflict

- kong/plugins/opentelemetry/handler.lua
Update `opentelemetry` plugin version to match Kong Gateway version.
> fix: update otel version to match Kong Gateway version

- kong/clustering/rpc/utils.lua
Using lru_cache to improve the performance of `pares_method_name()`.
KAG-4441
> refactor(clustering/rpc): cache the result of parse_method_name()

- changelog/unreleased/kong/fix-request-size-limiting-with-chunked-transfer-encoding-and-no-content-length.yml
- kong/plugins/request-size-limiting/handler.lua
- spec/03-plugins/12-request-size-limiting/01-access_spec.lua
Firstly enable request-size-limiting plugin with below config
```
plugins:
- config:
allowed_payload_size: 512
require_content_length: false
size_unit: kilobytes
enabled: true
name: request-size-limiting
```
When client send request without content-length and request body chunked with Transfer-Encoding,
then kong.request.get_raw_body() become nil, and request-size-limiting plugin do not work anymore and return 200 directly.
Below curl command could trigger the error:
```
dd if=/dev/urandom of=1m.dat bs=1m count=1
curl -v --data-binary @1m.dat http://kong:8000/test -H "Content-Length:" -H "Transfer-Encoding: chunked"
```
This PR will check the file size when the request body buffered to a temporary file.
Then request-size-limiting plugin still able to get the request body size and work as …
> fix(plugins/request-size-limiting): Check the file size when the request body buffered to a temporary file

- changelog/unreleased/kong/fix-rpc-err-msg-checking.yml
- kong/clustering/rpc/json_rpc_v2.lua
- kong/clustering/rpc/socket.lua
minor code style improvement.
KAG-4441
> fix(clustering/rpc): more strict parameter checking when generating a RPC error

- changelog/unreleased/kong/ttl_expires.yml
- kong/db/dao/init.lua
- kong/db/strategies/postgres/init.lua
- spec/02-integration/03-db/14-dao_spec.lua
Before running the TTL cleanup in the background timer. it can't delete or select an entity after the TTL expires.
The context of this PR has been written in KAG-4833.
KM-111, [KAG-4833](https://konghq.atlassian.net/browse/KAG-4833)
[KAG-4833]: https://konghq.atlassian.net/browse/KAG-4833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(dao): add ability to select and delete expired entities

- changelog/unreleased/kong/traditional_router_header_validation.yml
- kong/db/schema/entities/routes.lua
- kong/db/schema/typedefs.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
Reverts Kong/kong#12365
It fails KIC nightly
Fix https://konghq.atlassian.net/browse/KAG-4788
> Revert "fix(core): Regex header values in traditional router are now validated"

- .github/matrix-full.yml
remove RHEL 7 and Debian 10.
KAG-4847
> chore(cd): remove EOL distros

- changelog/unreleased/kong/pdk-telemetry-log.yml
- kong-3.8.0-0.rockspec
- kong/globalpatches.lua
- kong/observability/logs.lua
- kong/pdk/init.lua
- kong/pdk/log.lua
- kong/pdk/telemetry.lua
- spec/01-unit/26-observability/05-logs_spec.lua
- spec/01-unit/26-observability/06-telemetry-pdk_spec.lua
- spec/02-integration/14-observability/06-telemetry-pdk_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/pdk-logger/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/pdk-logger/schema.lua
This PR:
* introduces the `kong.telemetry` pdk module
* adds the `kong.telemetry.log` function to allow generating log entries meant to be reported via the OpenTelemetry plugin
KAG-4848
> feat(pdk): telemetry log

- kong.conf.default
The kong.conf.default doc requires a lot of formatting changes to fix on the docs website. This PR contains those changes .
Corresponding EE PR https://github.com/Kong/kong-ee/pull/9473 
This CE one needs to be merged first and then I will update on EE. 
- [x ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - https://github.com/Kong/docs.konghq.com/pull/7490
https://konghq.atlassian.net/jira/software/c/projects/DOCU/boards/58?selectedIssue=DOCU-829
https://konghq.atlassian.net/browse/DOCU-3896
> Clean up kong.conf.default for better output to doc site

- .github/workflows/release.yml
- build/dockerfiles/deb.Dockerfile
- build/dockerfiles/rpm.Dockerfile
This updates our release workflow to use docker's build-time [bind mount](https://docs.docker.com/reference/dockerfile/#run---mounttypebind) support to supply the package file(s) instead of copying into the image.
The idea behind this is that mounting the package removes a large `COPY` layer and reduces the image size.
The directory that is mounted is checksum-ed by docker as part of the build context, so build cache is automatically invalidated when the package file changes.
```
$ docker image ls kong/kong-gateway-dev:master \
> --format 'table {{.Repository}}\t{{.Tag}}\t{{.Size}}'
REPOSITORY              TAG       SIZE
kong/kong-gateway-dev   master    538MB
```
```
$ docker image history kong/kong-gateway-dev:master \
> --format 'table {{.CreatedAt}}\t{{.CreatedBy}}\t{{.Size}}'
CREATED …
```
> chore(ci): mount package directory at image build time

- changelog/unreleased/kong/admin-api-map-brackets-syntax.yml
- kong-3.8.0-0.rockspec
- kong/api/arguments.lua
- kong/api/arguments_decoder.lua
- spec/01-unit/01-db/03-arguments_spec.lua
This commit adds support for configuring maps using brackets syntax to
enclose the key:
```
http -f post :8001/plugins/                       \
name=opentelemetry                                \
config.endpoint=http://test.test/                 \
config.resource_attributes[service.name]=kong-dev
```
KAG-4827
> feat(admin_api): support map brackets syntax

- build/openresty/BUILD.openresty.bazel
Had issues with `bazel build //build:kong` due to ngx_brotli. Re-run with `--//:brotli=false` and ngx_brotli is still being downloaded, which caused another issue with recursive cloning. This now truly disable ngx_brotli when asked, assuming user has a good reason to.
~- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)~
~- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
~Fix #_[issue number]_~
> chore(build): do not download ngx_brotli with '--//:brotli=false'

- changelog/unreleased/kong/fix-sni-cache-invalidate.yml
- kong/runloop/events.lua
- spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
Both `data.entity` and `data.old_entity` should be invalidated when a sni is updated. A non-existent sni may also have been cached.
https://konghq.atlassian.net/browse/FTI-6009
> fix(runloop): the sni cache isn't invalidated when a sni is updated

- build/package/nfpm.yaml
> chore(cd): make the RPM package relocatable

- changelog/unreleased/kong/ai-plugin-read-file.yml
- changelog/unreleased/kong/pdk-read-file.yml
- kong/clustering/compat/removed_fields.lua
- kong/pdk/request.lua
- kong/plugins/ai-prompt-decorator/handler.lua
- kong/plugins/ai-prompt-decorator/schema.lua
- kong/plugins/ai-prompt-guard/handler.lua
- kong/plugins/ai-prompt-guard/schema.lua
- kong/plugins/ai-prompt-template/handler.lua
- kong/plugins/ai-prompt-template/schema.lua
- kong/plugins/ai-proxy/handler.lua
- kong/plugins/ai-proxy/schema.lua
- kong/plugins/ai-request-transformer/handler.lua
- kong/plugins/ai-request-transformer/schema.lua
- kong/plugins/ai-response-transformer/handler.lua
- kong/plugins/ai-response-transformer/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- t/01-pdk/04-request/15-get_raw_body.t
- t/01-pdk/04-request/16-get_body.t
- [feat(plugins): enable ai plugins to read request body from buffered file](https://github.com/Kong/kong/commit/f2eb35eeb0991f5e9a2fd63f8ede5fb9d4b03f49)
- [feat(pdk): add argument to allow request body read from disk](https://github.com/Kong/kong/commit/2771163eacc01276fdcc6f6f8159313b578c4052)
AG-39
#13211
> feat(plugins): enable ai plugins to read request body from buffered file

- kong/cluster_events/init.lua
- kong/concurrency.lua
- kong/db/declarative/import.lua
Several places in the gateway need a node-level lock, some of them used slightly different implementations. This refactor brings consistency in the ways we do node-level locking by using the same implementation (concurrency.with_worker_mutex) everywhere.
Note: in order to maintain the logic of `declarative.import` unaltered, the `concurrency.with_worker_mutex` function has been slightly modified to return an additional value `ttl` in case of timeout error, so that `retry_after` could be implemented as before.
KAG-2337
> refactor(concurrency): consistent node-level locks

- kong/cluster_events/init.lua
- kong/concurrency.lua
- kong/db/declarative/import.lua
Reverts Kong/kong#13055
The original PR is producing errors in the log like:
```
[lua] init.lua:364: [cluster_events] timeout, context: ngx.timer
```
reverting to investigate further.
> Revert "refactor(concurrency): consistent node-level locks"

- changelog/unreleased/kong/feat-via.yml
- kong/plugins/aws-lambda/handler.lua
- kong/plugins/azure-functions/handler.lua
- kong/runloop/handler.lua
- kong/templates/nginx_kong.lua
- spec/02-integration/05-proxy/09-websockets_spec.lua
- spec/02-integration/05-proxy/14-server_tokens_spec.lua
- spec/02-integration/05-proxy/30-max-args_spec.lua
- spec/02-integration/05-proxy/35-via_spec.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/03-plugins/35-azure-functions/01-access_spec.lua
- spec/helpers.lua
According to [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-5.7.1) and [RFC9110](https://datatracker.ietf.org/doc/html/rfc9110#name-via) gateway MUST append protocol, version and host (or pseudonym) information when forwarding HTTP messages from clients to upstreams. Currently, Kong just ignores this part.
And optionally append the information when forwarding messages in the reverse direction, depending on the `headers` configuration. Currently, Kong blindly overrides the response `Via` header with server token.
This PR do the following works:
1. Append inbound info like `1.1 kong/3.8.0`, and outbound info like `1.1 kong/3.8.0`.
2. Supports gRPC and gRPCs protocols, like inbound `2 kong/3.8.0` and outbound `2 kong/3.8.0`.
3. When the upstream does not include the `Server` …
> feat(core): support inbound and outbound Via header

- changelog/unreleased/kong/fix-reports-uninitialized-variable-in-400.yml
- kong/reports.lua
- kong/templates/nginx_kong.lua
- spec/02-integration/05-proxy/22-reports_spec.lua
When Kong receives abnormal traffic, it will trigger 400 responses without initializing any Nginx variable, So it will trigger `report.lua`  error, which is unnecessary.
eg: send HTTP traffic to HTTPS port, Nginx will finalize the current request by 400 response in the TLS handshake, So it will never call any openresty HTTP processing phase, it also does not initialize any Nginx variable.
Fix https://github.com/Kong/kong/issues/13197
https://konghq.atlassian.net/browse/FTI-6025
> fix(core): reduce uninitialized variable message when nginx return 400

- kong/observability/logs.lua
When the log buffer was full, a log message was logged for every dropped log entry. This was causing a lot of noise.
This commit changes the behavior to only log a single message (per worker) when the log buffer is full. Another message is logged when the buffer resumes accepting new log entries.
[KAG-4924](https://konghq.atlassian.net/browse/KAG-4924)
[KAG-4924]: https://konghq.atlassian.net/browse/KAG-4924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(observability): log a single warning when buffer is full until it recovers

- build/BUILD.bazel
- changelog/unreleased/kong/cp-luarocks-admin-to-bin.yml
- scripts/explain_manifest/docker_image_filelist.txt
- scripts/explain_manifest/suites.py
Port of https://github.com/Kong/kong-ee/pull/9671 to ensure that `luarocks-admin` is present in CE packages/docker images:
```bash
$ podman run --user=root --privileged --rm -it kong/kong:master bash -c 'find /usr/local -name luarocks-admin'
/usr/local/lib/luarocks/rocks-5.1/luarocks/3.11.1-1/bin/luarocks-admin
```
Fix #_[KAG-911]_
[KAG-911]: https://konghq.atlassian.net/browse/KAG-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(bazel): cp luarocks-admin to bin

- changelog/unreleased/kong/feat-ai-prompt-guard-all-roles.yml
- changelog/unreleased/kong/fix-ai-prompt-guard-order.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/ai-prompt-guard/handler.lua
- kong/plugins/ai-prompt-guard/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/42-ai-prompt-guard/00-config_spec.lua
- spec/03-plugins/42-ai-prompt-guard/01-unit_spec.lua
This PR also fixes an issue when allow_all_conversation_history
is set to false, the first user request is selected instead of the last
one.
Unit tests are refactored to so that it's cleaner and has wider coverage.
AG-58
> feat(ai-promp-guard) add config option to prompt guard for scanning "system" and "assistant" messages

- changelog/unreleased/kong/feat-aws-lambda-configurable-sts-endpoint.yml
- kong/clustering/compat/checkers.lua
- kong/plugins/aws-lambda/handler.lua
- kong/plugins/aws-lambda/schema.lua
This is a cherry-pick of part of the https://github.com/Kong/kong-ee/pull/9654. Please REBASE MERGE to keep consistency between commits.
EE part PR already has ut/integration test for the STS service, and it seems meaningless to add another integration test for the lambda plugin, so skipped the test on this PR.
KAG-4599
> feat(aws-lambda): add configurable sts endpoint url for aws-lambda plugin

- CHANGELOG.md
Forward the 2.8.5 changelog changes to release/2.8.x.
> docs(changelog): assemble 2.8.5 changelog into CHANGELOG.md (#13289)

- changelog/unreleased/kong/fix-aws-lambda-empty-array-mutli-value.yml
- kong/plugins/aws-lambda/handler.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/fixtures/aws-lambda.lua
This PR fixes a bug that introduced by #13084, that when `is_proxy_integration` mode is set to true with `empty_arrays_mode` set to `legacy`, and lambda function returns `multiValueHeader` that contains a `Content-Type` with single value array, the plugin cannot work correctly.
The `multiValueHeaders` field in the proxy integration response can be an array even if the header has only one value. I've tested AWS API gateway and the Kong gateway before #13084 and confirmed that both would work fine with `Content-Type` single value array inside the mutliValueHeader response field.
The reason of #13084 brings in this issue is that before #13084 we did not have any logic about reading `Content-Type` so no problem existed. The single value array will goes into `kong.response.exit` and normalized …
> fix(aws-lambda): fix an incompatibility with multi value header in proxy integration and legacy empty arrays mode

- changelog/unreleased/kong/pdk-log-error.yml
- kong/pdk/log.lua
- spec/01-unit/10-log_serializer_spec.lua
As titled, this PR is to fix the bug reported by FTI-6096
Fix #_[FTI-6096]_
[FTI-6096]: https://konghq.atlassian.net/browse/FTI-6096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(pdk.log): fix a bug that pdk.log.serialize() does not properly handle JSON nulls

- build/package/nfpm.yaml
- changelog/unreleased/kong/fix-type-of-logrotate.yml
…
Fix [FTI-6079](https://konghq.atlassian.net/browse/FTI-6079)
[FTI-6079]: https://konghq.atlassian.net/browse/FTI-6079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(build): set type of kong.logrotate as config|noreplace avoid overwriting during the upgrade

- changelog/unreleased/kong/yield-in-gzip.yml
- kong/tools/gzip.lua
KAG-4878
Still in discussion, but I checked the source of [ffi-zlib](https://github.com/hamishforbes/lua-ffi-zlib/blob/master/lib/ffi-zlib.lua) and believe it can yield safely.
> perf(tools): yield when gzip or gunzip

- changelog/unreleased/kong/bump-lua-resty-openssl.yml
- kong-3.8.0-0.rockspec
Fix several issue under high memory pressure.
Full changelog: https://github.com/fffonion/lua-resty-openssl/compare/1.4.0...1.5.0
> chore(deps): bump lua-resty-openssl to 1.5.0

- kong/dns/README.md
- kong/dns/utils.lua
- spec/01-unit/30-new-dns-client/01-utils_spec.lua
Merge ready since #12305 was cherry-picked successfully.
KAG-5001
* two blank lines between blocks
* optimize table.insert
* family should compare to `domain`, not `name`.
> style(dns): style and typo fixes

- .github/workflows/release.yml
Due to ${{ github.event.inputs.default_branch }} being empty, causing an exception when fetching the SHA, so hardcode the branch name.
KAG-4992
> chore(ci): fix image release issue by hard-coding branch

- kong/plugins/aws-lambda/handler.lua
`tools.time` provides many time utilities, we should not re-invent wheels.
> refactor(plugins/aws-lambda): simplify code with tools.time utility

- changelog/unreleased/kong/proxy-cache-fix-age-header.yml
- kong/plugins/proxy-cache/handler.lua
- spec/03-plugins/31-proxy-cache/02-access_spec.lua
The `age` header should be added by default or when explicitly configured.
Fix #12787
> fix(proxy-cache): correctly add age header on cache hit

- kong/dns/utils.lua
Merge ready since #12305 was cherry-picked successfully.
Try to improve #12305.
KAG-5001
> refactor(dns): simplify the code of new dns utils

- kong/clustering/compat/checkers.lua
- kong/clustering/compat/removed_fields.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
The last Gemini PR (https://github.com/Kong/kong/pull/12948) broke cluster compat of <3.8 with the new 3.8 control plane.
KAG-5020
> fix(ai-proxy): gemini: broke cluster compat in last commit

- changelog/unreleased/kong/fix-wasm-enable-pwm-lua-resolver.yml
- kong/conf_loader/init.lua
- spec/01-unit/04-prefix_handler_spec.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
This was previously disabled in 9a5d48bfca (#12825) due to shortcomings of the underlying ngx_wasm_module Lua execution model, which has since been fixed and merged into master (19ee6a9dd66ad2275209b29406303a88f59eb3b6).
[KAG-4671](https://konghq.atlassian.net/browse/KAG-4671)
Replace #13363 (can't re-open this PR after force-pushing the branch)
[KAG-4671]: https://konghq.atlassian.net/browse/KAG-4671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(wasm): re-enable Lua DNS resolver for proxy-wasm

- changelog/unreleased/kong/fix-otel-migrations-exception.yml
- kong/plugins/opentelemetry/migrations/001_331_to_332.lua
- spec/05-migration/plugins/opentelemetry/migrations/001_331_to_332_spec.lua
The migration job try to reset `config.queue.max_batch_size` of opentelemetry plugin. However the `config.queue` field has only been introduced since 3.3. 
This means that if users are upgrading from a version below 3.3 to 3.7, they will encounter `kong migrations finish` terminates unsuccessfully with the error:
```
kong@943321e5c877:/$ kong migrations finish
migrating opentelemetry on database 'kong'...
Error: [PostgreSQL error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:174: [PostgreSQL error] failed to run migration '001_331_to_332' teardown: ./opentelemetry/migrations/001_331_to_332.lua:14: attempt to index field 'queue' (a nil value)
./opentelemetry/migrations/001_331_to_332.lua:14: in function 'fixup_fn' …
```
> fix(opentelemetry): migration exception when upgrading from below version 3.3 to 3.7

- changelog/unreleased/kong/fix-ai-metrics-prometheus-compat.yml
- kong/clustering/compat/removed_fields.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
Fix compat prometheus ai metrics
https://konghq.atlassian.net/browse/KAG-4934
> fix(clustering): fix compat for prometheus ai metrics config fields

- CHANGELOG-OLD.md
Add 2.8.2-2.8.5 changelog entries to the CHANGELOG-OLD.md.
KAG-4790
> docs(changelog): add 2.8.2-2.8.5 changelog entries

- changelog/unreleased/kong/certificates_schema_validate.yml
- kong/db/dao/certificates.lua
- kong/db/schema/entities/certificates.lua
- kong/db/schema/metaschema.lua
- kong/db/strategies/postgres/init.lua
- spec/02-integration/04-admin_api/02-kong_routes_spec.lua
- spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
the endpoint  POST `/schemas/certificates/validate` with entity data:
>{
"cert":"<input valid cert>",
"key":"<input valid key>",
"snis":["a","b","c"]
}
It throws an error.
>{
"code": 2,
"name": "schema violation",
"fields": {
"snis": "unknown field"
},
"message": "schema violation (snis: unknown field)"
}
Currently, the endpoint POST `/certificates` can batch-create sni entities with `snis`. But the `snis` is not part of the certificate schema. so we need to remove it from the request body.
KM-223
> fix(certificates): validate the certificates schema failed if `snis` was in the request body

- changelog/unreleased/kong/feat-parse-ngx-size.yml
- kong/tools/string.lua
- spec/01-unit/05-utils_spec.lua
It is the cherry-pick of kong/kong-ee#9472.
KAG-4698
> feat(tools): add a function to parse Nginx size strings

- kong/clustering/utils.lua
In #13421 we introduced lua-resty-simdjson, but the behavior of encoding has some differences with cjson, this PR disabled simdjson encoding temporarily. 
KAG-5061
Related PR: https://github.com/Kong/lua-resty-simdjson/pull/38
> fix(clustering): still encoding with cjson

- changelog/unreleased/kong/feat-pdk-unlimited-body-size.yml
- kong/pdk/request.lua
- t/01-pdk/04-request/15-get_raw_body.t
It is the cherry-pick of kong/kong-ee#9472.
KAG-4698
> feat(pdk): add zero value to support unlimited body size

- scripts/explain_manifest/config.py
- scripts/explain_manifest/suites.py
Just simply skip the `libsimdjson.so` check.
KAG-5070
> chore(ci): fix the verify manifest error on AWS Linux 2

- changelog/unreleased/kong/acl-always-use-authenticated-groups.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/acl/handler.lua
- kong/plugins/acl/schema.lua
- spec/02-integration/03-db/08-declarative_spec.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/18-acl/02-access_spec.lua
Currently, authenticated groups will only be used when there is no consumer or the consumer is anonymous. When there is an authenticated consumer, there is no way to use authenticated groups, only the groups associated with the consumer will be used.
This PR adds a config `always_use_authenticated_groups` to support using authenticated groups even when an authenticated consumer exists. If enabled, it will first try to use authenticated groups and will fallback to use the groups associated with the consumer if authenticated groups don't exist, which is consistent with the logic in the anonymous consumer case.
https://konghq.atlassian.net/browse/FTI-5945
> feat(acl): added a config `always_use_authenticated_groups` to support using authenticated groups even when an authenticated consumer exists.

- build/dockerfiles/entrypoint.sh
- changelog/unreleased/kong/move-sockets-to-subdir.yml
- kong/clustering/utils.lua
- kong/cmd/start.lua
- kong/cmd/utils/prefix_handler.lua
- kong/conf_loader/init.lua
- kong/constants.lua
- kong/global.lua
- kong/init.lua
- kong/runloop/events.lua
- kong/runloop/handler.lua
- kong/templates/nginx.lua
- kong/templates/nginx_kong.lua
- kong/templates/nginx_kong_stream.lua
- kong/tools/stream_api.lua
- spec/01-unit/01-db/11-declarative_lmdb_spec.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/02-integration/03-db/14-dao_spec.lua
- spec/02-integration/05-proxy/01-proxy_spec.lua
- spec/02-integration/12-stream_api/01-stream_api_endpoint_spec.lua
- spec/fixtures/template_inject/nginx_kong_test_custom_inject_stream.lua
- spec/helpers.lua
This moves all internal unix sockets managed by Kong from `{{prefix}}` into a subdirectory at `{{prefix}}/sockets`. The conf loader makes this available via the new `socket_path` field, which is intended as a step towards relocating this path _outside_ of the prefix tree in a later release.
KAG-4947
> fix(core): relocate unix sockets to a subdirectory

- changelog/unreleased/kong/fix-correlation-id-config-generator.yml
- kong/plugins/correlation-id/schema.lua
- spec/03-plugins/11-correlation-id/02-schema_spec.lua
Some fields in the request body to admin api occasionally are specified as `json.null`.
In this PR, we add `required=true` to the schema of the field so that it can be auto-completed with the default when construction if it is `null` in database. It will become a mandatory field in KM.
FTI-6134
> fix(correlation-id): auto-complete config.generator when constructing if it is `null` in database

- DEVELOPER.md
* Added two new ways to do authentication with GitHub.
* Explained how to get the Rust build system authenticated by GitHub.
> docs(DEVELOPER.md): explain how to get the Rust build system authenticated by GitHub

- changelog/unreleased/kong/refactor_dns_client.yml
- kong.conf.default
- kong/conf_loader/constants.lua
- kong/conf_loader/parse.lua
- kong/dns/client.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
- kong/tools/dns.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/02-cmd/11-config_spec.lua
- spec/02-integration/04-admin_api/11-reports_spec.lua
- spec/02-integration/05-proxy/22-reports_spec.lua
- spec/02-integration/10-go_plugins/01-reports_spec.lua
- spec/02-integration/17-admin_gui/03-reports_spec.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
- spec/02-integration/22-ai_plugins/01-reports_spec.lua
- spec/fixtures/default_status_listen.conf
- spec/kong_tests.conf
The new DNS implementation requires introducing a new set of directives because some directives (`resolver_xxx`) behave differently between the old and new libraries. Without clear differentiation, users might be confused by the inconsistent behavior of these directives in the new library.
Fix KAG-4994
> feat(dns): support resolver_* directives for new dns client

- kong/llm/schemas/init.lua
- spec/03-plugins/38-ai-proxy/00-config_spec.lua
> chore(llm): remove llm model schema auth required

- changelog/unreleased/kong/refactor_dns_client.yml
- kong-3.8.0-0.rockspec
- kong/api/routes/dns.lua
- kong/status/init.lua
- spec/02-integration/08-status_api/05-dns_client_spec.lua
The dns statistics API should be added into status_listen port, otherwise we'll not get the DNS statistics from admin_listen port in DP.
Fix KAG-5115
> fix(dns): added /status/dns API to status_listen port

- changelog/unreleased/kong/make_rpm_relocatable.yml
- changelog/unreleased/kong/remove_eol_debian_rhel.yml
Add changelogs for
- [KAG-4847](https://konghq.atlassian.net/browse/KAG-4847) (https://github.com/Kong/kong/pull/13340)
- [FTI-6054](https://konghq.atlassian.net/browse/FTI-6054) (https://github.com/Kong/kong/pull/13351)
- [KAG-4549](https://konghq.atlassian.net/browse/KAG-4549) (https://github.com/Kong/kong/pull/13052)
KAG-5122
[KAG-4847]: https://konghq.atlassian.net/browse/KAG-4847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FTI-6054]: https://konghq.atlassian.net/browse/FTI-6054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAG-4549]: https://konghq.atlassian.net/browse/KAG-4549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(changelog): add missing changelogs

- changelog/unreleased/kong/ai-proxy-mistral-ai.yml
- kong/clustering/compat/checkers.lua
- kong/llm/drivers/anthropic.lua
- kong/llm/drivers/cohere.lua
- kong/llm/drivers/mistral.lua
- kong/llm/drivers/openai.lua
- kong/llm/drivers/shared.lua
- kong/llm/schemas/init.lua
- spec/03-plugins/38-ai-proxy/00-config_spec.lua
> feat(ai-proxy): allow to use mistral.ai cloud service by omitting

- DEVELOPER.md
> docs(DEVELOPER.md): fix the guide of authentication

- .github/labeler.yml
> chore(ci): add llm schemas to schema-change-noteworthy labeler

- changelog/unreleased/fix-deprecate-shorthands-precedence.yml
- kong/api/routes/plugins.lua
- kong/db/dao/plugins.lua
- kong/db/schema/init.lua
- spec/01-unit/01-db/01-schema/01-schema_spec.lua
The shorthand fields e.g. as used in (the url is a shorthand) take precedence:
```
http PUT :8001/services/test url=http://test.org/ port=2345
```
That means that `port=2345` will be overwritten by http default port of `80` that is implicit in shorthand field `url`.
This is how it has been for a long long time.
In PR https://github.com/Kong/kong/pull/12686 we added `deprecation` field to shorthand fields definition.
Some of our automatic migrations without database migrations magic use this functionality, but the precedence there does not good:
```
http -f PUT :8001/plugins/x name=x config.new=test config.old=should_be_ignored
```
In above the `config.old` is a shorthand field with a deprecation property. Thus it should not overwrite the `config.new`, but in current code base it does. …
> fix(schema): deprecated shorthand fields precedence 

- spec/01-unit/05-utils_spec.lua
From https://github.com/Kong/kong-ee/pull/9910
> tests(tools): add tests against `kong.tools.http.parse_directive_header()`

- changelog/unreleased/kong/fix-clustering-forward-proxy-authentication.yml
- kong.conf.default
- kong/clustering/utils.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/09-hybrid_mode/10-forward-proxy_spec.lua
Hybrid mode connections not working if the forward proxy password contains special character(`#`). Even after the `proxy_server` is url encoded, it still doesn't work and reports a "407 Proxy Authentication Required" error.
This fix tries to address this issue. But, keep in mind that even with this fix, `proxy_server` still needs to be url-encoded.
Fix FTI-6145
> fix(clustering): hybrid mode should accept special characters used in forward proxy password

- .github/workflows/build_and_test.yml
- spec/03-plugins/03-http-log/05-old-plugin-compatibility_spec.lua
- spec/helpers.lua
Cherry-picking https://github.com/Kong/kong-ee/pull/9077.
Test the old version plugin against the latest core code. We only focus on whether there is any runtime error in the happy path. Because logic changes from version to version, it is not feasible to test the behavior of the plugin.
This test is not guaranteed to capture all interface changes, because it may not be able to cover all the dependent interfaces, and even if the interface is covered, it can't detect interface semantic changes or internal logic changes. These kinds of things still rely on the tests of the interfaces themselves to cover.
https://konghq.atlassian.net/browse/FTI-5923
> [cherry-pick master] tests(plugins): add old version plugin compatibility test (#9077)

- kong/clustering/compat/init.lua
- kong/conf_loader/constants.lua
- kong/hooks.lua
- kong/llm/init.lua
- kong/llm/proxy/handler.lua
- kong/plugins/acl/groups.lua
- kong/plugins/acl/handler.lua
- kong/plugins/oauth2/access.lua
- kong/plugins/proxy-cache/cache_key.lua
- kong/plugins/proxy-cache/handler.lua
- kong/plugins/rate-limiting/handler.lua
- kong/plugins/rate-limiting/policies/init.lua
- kong/plugins/request-transformer/access.lua
- kong/plugins/response-ratelimiting/access.lua
- kong/resty/dns/client.lua
- kong/router/traditional.lua
- kong/runloop/balancer/init.lua
- kong/runloop/balancer/least_connections.lua
- kong/runloop/balancer/targets.lua
- kong/tools/http.lua
- kong/tools/table.lua
Inspired by #13491.
This PR did not replace all so called `EMPTY` tables, only which are obviously readonly.
KAG-5140
> feat(tools): add readonly `tools.table.EMPTY` for common usage

- changelog/unreleased/kong/fix-service-tls-verify.yml
- kong/db/schema/entities/services.lua
- kong/runloop/upstream_ssl.lua
- spec/02-integration/05-proxy/18-upstream_tls_spec.lua
Should also set_upstream_ssl_verify when `tls_verify` is false, because the global level config `proxy_ssl_verify` may be `on`.
Fix https://konghq.atlassian.net/browse/FTI-6095
> fix(runloop): Fixed an issue where setting `tls_verify` to `false` didn't override the global level config `proxy_ssl_verify`

- changelog/unreleased/kong/ai-proxy-add-allow-override-opt.yml
- kong/clustering/compat/removed_fields.lua
- kong/llm/drivers/anthropic.lua
- kong/llm/drivers/azure.lua
- kong/llm/drivers/cohere.lua
- kong/llm/drivers/llama2.lua
- kong/llm/drivers/mistral.lua
- kong/llm/drivers/openai.lua
- kong/llm/drivers/shared.lua
- kong/llm/schemas/init.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/38-ai-proxy/00-config_spec.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua
- spec/03-plugins/38-ai-proxy/04-cohere_integration_spec.lua
- spec/03-plugins/38-ai-proxy/05-azure_integration_spec.lua
- spec/03-plugins/38-ai-proxy/06-mistral_integration_spec.lua
- spec/03-plugins/38-ai-proxy/07-llama2_integration_spec.lua
Add `allow_override` option to allow overriding the upstream model auth parameter or header from the caller's request.
/AG-92
> feat(llm): add auth.allow_override option for llm auth functionality

- spec/01-unit/05-utils_spec.lua
> tests(tools): add parse_directive_header and calculate_resource_ttl function unit test

- changelog/unreleased/kong/req-trans-rename.yml
- kong/plugins/request-transformer/access.lua
- spec/03-plugins/36-request-transformer/02-access_spec.lua
This plugin removes the target parameter when renaming from the same parameter.
Fix KAG-4915
Also see https://github.com/Kong/kong/pull/9442
> fix(plugins): Request-Transformer rename behavior

- kong.conf.default
- kong/api/routes/dns.lua
- kong/api/routes/kong.lua
- kong/conf_loader/constants.lua
- kong/resty/dns/client.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong.lua
- kong/tools/dns.lua
- spec/01-unit/09-balancer/01-generic_spec.lua
- spec/01-unit/09-balancer/02-least_connections_spec.lua
- spec/01-unit/09-balancer/03-consistent_hashing_spec.lua
- spec/01-unit/09-balancer/04-round_robin_spec.lua
- spec/01-unit/09-balancer/05-worker_consistency_spec.lua
- spec/01-unit/09-balancer/06-latency_spec.lua
- spec/01-unit/21-dns-client/02-client_spec.lua
- spec/01-unit/21-dns-client/03-client_cache_spec.lua
- spec/01-unit/30-new-dns-client/04-client_ipc_spec.lua
- spec/02-integration/08-status_api/05-dns_client_spec.lua
- spec/helpers/dns.lua
1. The option `legacy_dns_client` in method is counterintuitive, so we need to change it to `new_dns_client`.
2. Enable both original DNS client and new DNS client in balancer test cases.
Fix KAG-5176
> fix(dns): change dns client switch to `new_dns_client`

- changelog/unreleased/kong/ai-proxy-cloud-identity-transformer-plugins.yml
- kong/llm/drivers/bedrock.lua
- kong/llm/drivers/gemini.lua
- kong/llm/drivers/shared.lua
- kong/llm/init.lua
- kong/llm/proxy/handler.lua
- kong/plugins/ai-request-transformer/handler.lua
- kong/plugins/ai-response-transformer/handler.lua
- Fixed a bug where cloud identity authentication was not used in `ai-request-transformer` and `ai-response-transformer` plugins.
- Re-factor "cloud SDK auth" function to be shared across many AI plugins.
AG-94
> fix(plugins): ai proxy cloud identity transformers

- changelog/unreleased/kong/fix-multi-modal.yml
- kong/llm/drivers/bedrock.lua
- kong/llm/drivers/shared.lua
- spec/03-plugins/38-ai-proxy/01-unit_spec.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/fixtures/ai-proxy/openai/llm-v1-chat/requests/good_multi_modal.json
For multi modal inputs (openai or bedrock), the input format is changed from:
```
messages=[
{
"role": "user",
"content": "What's an apple?
}
]
```
to
```
messages=[
{
"role": "user",
"content": [
{"type": "text", "text": "What's in this image?"},
{
"type": "image_url",
"image_url": {
"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
},
},
],
}
]
```
AG-61
> fix(llm): check multi modal input with provider and fix cost calculation

- changelog/unreleased/kong/bump-lua-resty-openssl.yml
- kong-3.8.0-0.rockspec
- chore(kdf): fix the outlen type to be size_t
KAG-5095
> chore(deps): bump lua-resty-openssl to 1.5.1

- changelog/unreleased/kong/fix-dns-initialization.yml
- kong/globalpatches.lua
- kong/init.lua
- kong/runloop/balancer/targets.lua
- kong/timing/hooks/dns.lua
There are muliple duplcated dns initialization which is unnecessary, This PR aims to improve the logic of dns initialization which as less as possible.  
Fix KAG-5059
> refactor(dns): remove unnecessary DNS client initialization

- changelog/unreleased/kong/bump-lua-resty-acme.yml
- kong-3.8.0-0.rockspec
- **tests:** use tlsv1.2 in dual cert test [415be3f](https://github.com/fffonion/lua-resty-acme/commit/415be3fe2a5bfcc3cd6aac5ab8a736f0a672475c)
- **tests:** uses v3 protocol for etcd [c3928b5](https://github.com/fffonion/lua-resty-acme/commit/c3928b5e92dd66e9a22d497935a878b59cb26b36)
- **etcd:** etcd storage to use v3 protocol [a3353b3](https://github.com/fffonion/lua-resty-acme/commit/a3353b3b26b4cb0c17e98dd36f829a0db18e4ef7)
- **redis:** add support for username/password auth ([#121](https://github.com/fffonion/lua-resty-acme/issues/121)) [186ab23](https://github.com/fffonion/lua-resty-acme/commit/186ab2367c66725b6a38a8f81743328e9a4455e3)
KAG-5189
> chore(deps): bump lua-resty-acme to 0.15.0

- kong/clustering/compat/checkers.lua
redis.password should work and redis.auth is just a shorthand left for backwards compatiblity reasons.
> fix(checkers): remove log warning of acme redis password

- .github/workflows/release.yml
The SCA tool (grype) invoked as part scan-images job downloads the vulnerability DB on each run. This is leading to issues dues to Grype CDN failures sporadically:
Long running jobs failing due to timeout (job resource wastage) when the job is stuck / hung up
Interim solutions to address from multiple fronts:
- Fixes [#140](https://github.com/Kong/public-shared-actions/issues/140)
- Add job timeout for scan job to achieve early graceful job failure
- Ability to bypass  scan-images using the `vars.DISABLE_SCA_SCAN` in the repository variable of emergency when enforcement / fail_build is `true`. Only Github Admin / Repo Admin access can perform this.
- Bump the `scan-actions` version to use GH cache as part of `[2.4.0](https://github.com/Kong/public-shared-actions/releases/tag/v2.4.0)`
Long …
> chore(ci): graceful scan-images job execution during grype cdn failures

- changelog/unreleased/kong/refactor_dns_client.yml
- kong.conf.default
- kong/templates/kong_defaults.lua
For the ongoing 3.8 release, we need to disable the new DNS client by default to avoid breaking the original DNS client's behavior.
Dont merge it until 3.8 RC2, 3.8 RC1 still enables the new DNS client for testing.
Fix KAG-5174
> fix(dns): disable new dns client by default

- kong/llm/proxy/handler.lua
Regression from https://github.com/Kong/kong/pull/13155
> fix(ai-proxy): disable gzip for SSE streams

- changelog/unreleased/kong/fix-db-read-only.yml
- kong/db/strategies/postgres/plugins.lua
- kong/db/strategies/postgres/services.lua
- kong/db/strategies/postgres/tags.lua
- kong/plugins/response-ratelimiting/policies/cluster.lua
@jeremyjpj0916 mentions in discussion thread:
https://github.com/Kong/kong/discussions/13513
That Kong may work unexpectedly or require write node for general operation.
I did quick search and found couple of  missing places where we don't give "read" as a parameter for readonly operations. This may not fix all the issues that we have for how resilient Kong nodes are for write node being offline, but at least it is obvious to fix these at first.
[KAG-5196](https://konghq.atlassian.net/browse/KAG-5196)
[KAG-5196]: https://konghq.atlassian.net/browse/KAG-5196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(db): pass "read" on read-only database operations

- changelog/unreleased/kong/fix-vault-secret-rotation-log-level.yml
- kong/pdk/vault.lua
This PR lowers the log level for secret rotation errors to `notice`.
Feels more like a "chore" to me but it changed the Lua code, thus the "fix"
FTI-5775
> fix(*): lower the secret rotation error log level

- spec/details/constants.lua
- spec/helpers.lua
KAG-5233
It is one of serial refactors of helpers.lua
> tests(helpers): split constants into a standalone file

- .github/workflows/release.yml
This should fix the issue where the scan job doesn't report any vulnerabilities due to caching issues of grype db which results in staleness.
[
](url)
> fix empty cve results due to grype db cache staleness

- .github/workflows/build_and_test.yml
When a new minor version is just bumped, the tag x.x.0 doesn't exist yet. So we fallback to use the starting point of the previous branch instead of the tag x.x.0 of the previous branch.
https://konghq.atlassian.net/browse/FTI-5923
> chore(ci): fallback to use the starting point of the previous branch for old plugin compatibility test if the first release tag doesn't exist yet

- spec/03-plugins/40-ai-response-transformer/02-integration_spec.lua
The way this latency is measured in the code is not granular enough to guarantee that it will always produce a non-zero result, so the assertion is changed from `>` to `>=`.
KAG-5251
> tests(ai-plugins): fix flaky latency assertion

- kong-3.9.0-0.rockspec
- kong/meta.lua
Bump the kong master version to 3.9 as part of the 3.8 feature freeze work.
KAG-5216
> chore(release): bump version to 3.9 as part of the feature freeze

- spec/01-unit/01-db/01-schema/01-schema_spec.lua
Gladly we found an issue where merge conflict in EE was wrongly resolved (by me, @bungle, most likely) before we released.
Thanks to @nowNick for finding it out.
Here is the missing tests that hopefully helps us in a future to spot it better.
> tests(db): add shorthands precedence test when using complex records

- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/03-plugins/39-ai-request-transformer/02-integration_spec.lua
Applies the same fix as 58c580f420 (#13558) to similar tests.
[KAG-5251](https://konghq.atlassian.net/browse/KAG-5251)
[KAG-5251]: https://konghq.atlassian.net/browse/KAG-5251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(ai-plugins): fix flaky latency assertion (part 2)

- .github/workflows/build_and_test.yml
https://konghq.atlassian.net/browse/FTI-5923
> chore(ci): fix build_and_test metadata

- changelog/unreleased/kong/shorten-socket-names.yml
- kong/clustering/utils.lua
- kong/conf_loader/constants.lua
- kong/conf_loader/init.lua
- kong/constants.lua
- kong/global.lua
- kong/runloop/events.lua
- kong/runloop/handler.lua
- kong/templates/nginx.lua
- kong/templates/nginx_kong.lua
- kong/templates/nginx_kong_stream.lua
- kong/tools/stream_api.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/02-integration/05-proxy/01-proxy_spec.lua
- spec/02-integration/12-stream_api/01-stream_api_endpoint_spec.lua
- spec/fixtures/template_inject/nginx_kong_test_custom_inject_stream.lua
- spec/helpers.lua
Unix domain sockets have a hard length limit of around 108 characters. When Kong is configured in a deeply nested directory structure, this can cause Kong to fail to start. Reducing the file name length will help alleviate this issue.
Fix: KAG-5136
> fix(core): rename unix sockets to shorter names to avoid exceeding socket name limit

- build/package/nfpm.yaml
> chore(cd): update rpm prefix and add resty symlink

- changelog/unreleased/kong/make_rpm_relocatable.yml
> chore(changelog): update the changelog regarding the RPM prefix

- changelog/unreleased/kong/ai-proxy-add-deep-copy-lib.yml
- kong/llm/proxy/handler.lua
This is a backport of #13566 so that it lands in 3.8 CE
Fix [konghq.atlassian.net/browse/AG-111](https://konghq.atlassian.net/browse/AG-111)
> fix(ai): caching use deep copy for request table

- changelog/unreleased/kong/fix-for-null-aware-shorthand.yml
- kong/db/schema/init.lua
- kong/tools/table.lua
- spec/01-unit/01-db/01-schema/01-schema_spec.lua
When both new field and shorthand fields are used but the new field contains null value and the old field contains some other specific value this change allows for that specific value to overwrite the new null value. If a user wants to set explicit null they have to send request without the old value.
KAG-5287
> fix(core): make deprecated shorthand fields take precedence when new value is null

- changelog/unreleased/kong/reject-config-on-deprecated-fields-mismatch.yml
- kong/db/schema/init.lua
- kong/db/schema/metaschema.lua
- kong/plugins/acme/schema.lua
- kong/plugins/rate-limiting/schema.lua
- kong/plugins/response-ratelimiting/schema.lua
- spec/01-unit/01-db/01-schema/01-schema_spec.lua
This PR adds a validation to deprecated fields that checks the case in which both new field and old field were defined; when that happens their values must match.
It introduces a new structure to deprecation definition by adding `replaced_with` information. This way field validation can verify if the `replaced_with` field has the same value as the old deprecated field. By default the comparison is done via translation through simple path but there might be instances where translation from old to new is more complicated and then the translation function should be provided in `translation` field.
The plan is to remove `translate_backwards` field in the future in favor of `replaced_with`.
KAG-5262
> fix(*): reject config if both deprecated and new field defined and their values mismatch

- .github/workflows/pr-diff.yml
add an action to enable executing the `/prdiff <other-pr-url>` command, to get the diff between the current PR's changes and the other PR's (effectively this outputs the diff of the PRs' diffs, using: https://github.com/samugi/gh-compr).
This gives a quick overview of the differences between two PRs and is meant to facilitate the process of reviewing cherry-picks.
KAG-4999
> feat(ci): pr diff

- changelog/unreleased/kong/fix-return-values-mistaken-in-rate-limiting-plugin.yml
- kong/plugins/rate-limiting/policies/init.lua
> fix(rate-limiting-plugin): fix a bug where the return values from `get_redis_connection()` are mistaken

- kong/llm/proxy/handler.lua
- kong/observability/logs.lua
The module `tools.utils` is deprecated, we should not use it anymore.
> style(tools): should not use `tools.utils` module

- spec/details/module.lua
- spec/helpers.lua
It is one of the serial refactors of helpers.lua
This function (`reload_module`) may be used by test cases outside.
KAG-5243
> tests(helper): separate module reload function

- spec/details/grpc.lua
- spec/helpers.lua
It is one of the serial refactors of helpers.lua
KAG-5242
> tests(helpers): separate grpc test functions

- changelog/unreleased/kong/fix-vault-cache-workspace-id.yml
- kong/db/dao/vaults.lua
- spec/02-integration/13-vaults/01-vault_spec.lua
This PR modifies the `cache_key` function of the vault entity to always generate a cache key without workspace id.
Vault entity is workspace-able, but our secret rotation timer always run without workspace settings(thus the default workspace is being used), so during secret rotation, the code https://github.com/Kong/kong/blob/4e38b965b922f57febe8652fb96b7d74aeab591a/kong/pdk/vault.lua#L620-L621 will generate a duplicate vault cache with default workspace id for each non-default workspace vault entity, and those cache will never be refreshed. The result of this issue is that when you update a vault entity's configuration inside a non-default workspace, it will never take effect in the secret rotation.
Since the prefix of vault entity is unique across workspaces, it should be safe to only …
> fix(vault): let vault entity cache key not containing workspace id

- kong/clustering/services/sync/hooks.lua
- kong/clustering/services/sync/strategies/postgres.lua
- kong/db/dao/init.lua
> feat(dao): support diff transaction

- changelog/unreleased/kong/fix-aws-lambda-multi-value-header-null.yml
- kong/plugins/aws-lambda/request-util.lua
- spec/03-plugins/27-aws-lambda/99-access_spec.lua
- spec/fixtures/aws-lambda.lua
A small PR for adding a null handling code for the `multiValueHeaders` field. Also contains a small refactor to put `isBase64Encode` check into the validate function to keep consistency with other fields
FTI-6168
> fix(aws-lambda): add null handling for multiValueHeaders

- changelog/unreleased/kong/fix-ai-semantic-cache-model.yml
- kong/llm/drivers/shared.lua
- kong/llm/proxy/handler.lua
- kong/llm/state.lua
- kong/plugins/ai-request-transformer/handler.lua
- kong/plugins/ai-response-transformer/handler.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
Sets request model name consistently across AI plugins.
> fix(ai): llm model moved to share state to guarantee consistency

- changelog/unreleased/kong/feat-pdk-clear-query-arg.yml
- changelog/unreleased/kong/fix-key-auth-retain-query-order.yml
- kong/pdk/service/request.lua
- kong/plugins/key-auth/handler.lua
- spec/03-plugins/09-key-auth/02-access_spec.lua
- t/01-pdk/06-service-request/00-phase_checks.t
- t/01-pdk/06-service-request/14-clear_query_arg.t
Adds `kong.service.request.clear_query_arg` to PDK. It also contains a second commit that fixes `key-auth` to retain order of query string arguments when hiding the credentials.
[KAG-5238](https://konghq.atlassian.net/browse/KAG-5238)
Fix #12758 reported by @battlebyte 
[KAG-5238]: https://konghq.atlassian.net/browse/KAG-5238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(pdk): add kong.service.request.clear_query_arg

- .github/matrix-commitly.yml
- .github/matrix-full.yml
- .github/workflows/release.yml
- build/README.md
- build/cross_deps/README.md
- build/cross_deps/libxcrypt/001-4.4.27-enable-hash-all.patch
- build/cross_deps/libxcrypt/repositories.bzl
- changelog/unreleased/kong/add-noble-numbat.yml
- scripts/explain_manifest/config.py
- scripts/explain_manifest/fixtures/ubuntu-24.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-24.04-arm64.txt
- scripts/explain_manifest/suites.py
- scripts/release-kong.sh
This PR introduces the next LTS version of Ubuntu, and makes it the default Ubuntu version used for building PRs, the `-ubuntu` tagged docker images, etc. Notably, this PR does NOT change any `runs-on` statements for github actions. A later PR will need to address that.
Had to make some changes to get the build rolling on 24.04:
- a `libxcrypt` patch that fixes some logic in their build scripts that wasn't adapted for modern perl
- parameterize the `GID` and `UID` in the docker parts of the explain_manifest script (`ubuntu` is already UID 1000 in Noble Numbat)
- add [`libsimdjson_ffi.so`](https://github.com/Kong/lua-resty-simdjson/blob/7e6466ce91b2bc763b45701a4f055e94b1e8143b/Makefile#L33-L34) and [`libada.so`](https://github.com/ada-url/ada) to the new explain_manifest fixtures
- add a …
> feat: Add Ubuntu 24.04 to build matrix

- spec/details/asserts.lua
- spec/details/conf.lua
- spec/details/constants.lua
- spec/details/db.lua
- spec/details/shell.lua
- spec/helpers.lua
KAG-5322
- The original `dcdp` and `PLUGINS_LIST` now turn to functions, since they are initialized in `get_db_utils()`.
- Add a param `extra_fields` for the function `validate_plugin_config_schema()` to be compatible with EE
-  move `conf` out of `shell` module
> tests(helpers): separate db functions

- .github/workflows/release.yml
According to the [bazelbuild/setup-bazelisk](https://github.com/bazelbuild/setup-bazelisk) README, the action is superseded by the [bazel-contrib/setup-bazel](https://github.com/bazel-contrib/setup-bazel). Please check if we need to migrate to the new action. One of the possible motivation of this migration is that node.js 16 is deprecated soon from github runners.
KAG-5221
> chore(ci): migrate bazelbuild/setup-bazelisk to bazel-contrib/setup-bazel

- spec/details/cmd.lua
- spec/details/pid.lua
- spec/details/server.lua
- spec/helpers.lua
KAG-5244
Move echo server related functions since they are using `cmd.stop_kong()`
> tests(helpers): separate cmd&pid functions

- kong/db/dao/targets.lua
`kong.db.targets:upsert` was not handling errors with `kong.db.targets:each_for_upstream` correctly. This fixes it.
> fix(db): targets:upsert to properly handle errors

- build/luarocks/luarocks_repositories.bzl
Luarocks.org can be down, and when it's down our CI fails. This points to the same artifacts in a more reliable location on GitHub.
> chore(ci): point to the more reliable Github distributions for Luarocks

- scripts/explain_manifest/fixtures/ubuntu-24.04-amd64.txt
> fix(ci): verify manifest fails with OpenSSL 3.2.3

- build/dockerfiles/rpm.Dockerfile
- changelog/unreleased/kong/bump-dockerfile-ubi9.yml
This PR updates the Dockerfile used when building RHEL-family docker images so that it uses redhat/ubi9 as its base.
> chore(docker): use ubi8 -> ubi9

- spec/helpers.lua
- spec/internal/db.lua
- spec/internal/misc.lua
> tests(helpers): move some misc funcs

- changelog/unreleased/kong/bump-prometheus-latency-bucket.yml
- kong/plugins/prometheus/exporter.lua
> chore(plugin): bump prometheus KONG_LATENCY_BUCKETS bucket to 6000

- bin/busted
- bin/kong
- kong/init.lua
This reduces memory usage a bit. I don't think we have any use for this anymore.
> chore(*): remove luarocks loader

- kong/pdk/vault.lua
> fix(pdk/vault): handle crud events for dbless

- .github/workflows/release.yml
> chore(ci): pin bazel-contrib/setup-bazel to e403ad507104847c3539436f64a9e9eecc73eeec

- build/toolchain/repositories.bzl
- scripts/explain_manifest/fixtures/ubuntu-24.04-arm64.txt
Do not set `cherry-pick` label.
It will be cherry-picked in https://github.com/Kong/kong-ee/pull/10226.
KAG-5335
> chore(ci): bump cross build toolchain from 0.8.0 to 0.8.2

- changelog/unreleased/kong/feat-api-yaml-media-type.yml
- kong/api/api_helpers.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
The https://datatracker.ietf.org/doc/html/rfc9512 specifies the official media-type to YAML as `application/yaml`. We had support for `text/yaml` (which is kept for backward compatibility), but this commit adds support for `application/yaml` as well.
KAG-5474
> feat(api): support official media-type of yaml in /config endpoint

- spec/02-integration/05-proxy/01-proxy_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
- spec/02-integration/05-proxy/06-ssl_spec.lua
- spec/02-integration/05-proxy/10-balancer/06-stream_spec.lua
- spec/02-integration/05-proxy/18-upstream_tls_spec.lua
- spec/02-integration/05-proxy/19-grpc_proxy_spec.lua
- spec/02-integration/05-proxy/21-grpc_plugins_triggering_spec.lua
- spec/02-integration/05-proxy/23-context_spec.lua
- spec/02-integration/05-proxy/26-udp_spec.lua
- spec/02-integration/05-proxy/28-stream_plugins_triggering_spec.lua
- spec/internal/misc.lua
- spec/internal/module.lua
- spec/internal/sys.lua
KAG-5423
Separate `setenv/unsetenv` from misc to sys, then they will not depend on `intenal.constants`.
> tests(router): remove duplicated `reload_router()`

- kong/clustering/control_plane.lua
Currently controlplane logs at ERROR level when dataplane closes the connection. This commit lowers the log level to `DEBUG` in this common case.
KAG-5476
> chore(clustering): adjust control plane log level when client closes the connection

- .github/matrix-commitly.yml
- .github/matrix-full.yml
- .github/workflows/release.yml
- scripts/explain_manifest/expect.py
- scripts/explain_manifest/explain.py
- scripts/explain_manifest/requirements.txt
- scripts/explain_manifest/suites.py
Bump lief (0.12.x no longer builds on ubuntu 24.04 host) and return matched groups
From https://github.com/Kong/kong/pull/13626
KAG-4672
> chore(explain_manifest): bump lief and return matched groups

- scripts/dependency_services/common.sh
Bash 3 is the default shell on macOS it seems
> fix(venv): fix compatibility on Bash 4.x and sync changes from EE

- scripts/explain_manifest/explain.py
Regression from https://github.com/Kong/kong/pull/13639
> fix(explain_manifest): fix behaviour change or API after version bump

- changelog/create_pr
The tool didn't include the "docs(release)" scope in the changelog PR title previously and sometime it leads to incorrect commit messages when moderators try to use "squash and merge". This change is to add the scope to the PR title.
KAG-5216
> docs(*): update the changelog PR title to include the docs(release) scope

- kong/db/schema/init.lua
- kong/db/schema/metaschema.lua
- kong/plugins/acme/schema.lua
- kong/plugins/rate-limiting/schema.lua
- kong/plugins/response-ratelimiting/schema.lua
We've introduced `replaced_with` when working on `shorthand_fields` when used as deprecation and making sure that incoming request do not contain mismatched data: https://github.com/Kong/kong/pull/13565
This made `translate_backwards` field obsolete as `replaced_with` is just more robust and intuitive. This PR removes that code.
KAG-5298
> refactor(shorthand_fields): remove translate_backwards in favor of replaced_with

- .gitignore
- changelog/unreleased/kong/fix-rl-plugin-resp-hdr.yml
- kong/plugins/rate-limiting/handler.lua
- spec/03-plugins/23-rate-limiting/04-access_spec.lua
Fix #13715, we should not set the response header if `conf.hide_client_headers` is `true`.
#13715, _[KAG-5492]_
[KAG-5492]: https://konghq.atlassian.net/browse/KAG-5492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(rate-limiting): do not set response headers if  `conf.hide_client_headers` is `true`

- BUILD.bazel
- build/BUILD.bazel
- build/cross_deps/libxcrypt/BUILD.libxcrypt.bazel
- build/cross_deps/libyaml/BUILD.libyaml.bazel
- build/cross_deps/libyaml/repositories.bzl
- build/cross_deps/repositories.bzl
- build/cross_deps/zlib/BUILD.zlib.bazel
- build/cross_deps/zlib/repositories.bzl
- build/libexpat/BUILD.libexpat.bazel
- build/libexpat/repositories.bzl
- build/luarocks/BUILD.luarocks.bazel
- build/openresty/BUILD.openresty.bazel
- build/openresty/atc_router/atc_router_repositories.bzl
- build/openresty/brotli/brotli_repositories.bzl
- build/openresty/openssl/openssl.bzl
- build/openresty/pcre/BUILD.pcre.bazel
- build/openresty/repositories.bzl
- build/openresty/simdjson_ffi/simdjson_ffi_repositories.bzl
- build/openresty/wasmx/wasmx_repositories.bzl
- build/repositories.bzl
- build/toolchain/cc_toolchain_config.bzl
Format Bazel files using https://github.com/bazelbuild/buildtools/blob/main/buildifier/README.md.
https://konghq.atlassian.net/browse/KAG-5491
> chore(Bazel): format Bazel files by Bazel Buildifier

- kong/clustering/services/sync/init.lua
- kong/clustering/services/sync/rpc.lua
Try to resolve this comment https://github.com/Kong/kong/pull/13157#discussion_r1791121787 
> fix(incremental): reduce the use of timers

- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
This takes the existing DNS client test and parameterizes it across `new_dns_client = {on, off}`.
KAG-5126
> tests(wasm): add test for new dns client

- kong.conf.default
Add a special note for `kong.conf.default` to mention that request debug is not authenticated with `X-Request-Debug-Token` when requests are originating from loopback.
KAG-5418
> docs(request-debug): Add special note for request debug

- kong/db/dao/workspaces.lua
If we could not get default id from lmdb, it should return nil from select_by_name API rather than returning empty table {}
> fix(incremental sync): fix incorrect return value from Workspace:select_by_name

- changelog/unreleased/kong/feat-request-debguger-finer-resolution-and-total-latency.yml
- kong/timing/context.lua
- spec/02-integration/21-request-debug/01-request-debug_spec.lua
Using `time_ns` to measure the context duration and make `total_time` finer resolution when less than 1ms.
A field called `total_time_without_upsteam` is introduced to represent total latency without upstream.
KAG-4733
FTI-5989
> feat(request-debugging): Finer time resolution and latency in total

- .github/actions/build-wasm-test-filters/action.yml
- .github/workflows/backport.yml
- .github/workflows/build.yml
- .github/workflows/build_and_test.yml
- .github/workflows/cherry-picks.yml
- .github/workflows/deck-integration.yml
- .github/workflows/perf.yml
- .github/workflows/release.yml
> chore(ci): bump Github actions to support node.js 20

- kong/db/dao/workspaces.lua
> fix(incremental): initial default workspace for importing declarative config

- changelog/unreleased/kong/bump-lua-resty-lmdb.yml
Fixed grammar of lua-resty-lmdb bumping changelog entry.
Fix KAG-5568
> doc(changelog): fix grammar in lua-resty-lmdb update

- spec/02-integration/20-wasm/10-wasmtime_spec.lua
> fix(tests): enable incremental sync for wasm cases

- changelog/unreleased/kong/add_multiple_domain_for_gui.yml
- kong.conf.default
- kong/admin_gui/init.lua
- kong/api/api_helpers.lua
- kong/conf_loader/constants.lua
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/01-unit/29-admin_gui/02-admin_gui_template_spec.lua
- spec/02-integration/02-cmd/03-reload_spec.lua
1. By default, set the origin retrieved from the request header or '*'.
2. If the `admin_gui_url` has more than one domain, the origin from the request header must match one of the `admin_gui_url`. Otherwise, It can't access the Admin API via the Kong Manager. 
For example: 
`admin_gui_url=http://example.com,http://km.konghq.com/manager`
These addresses access Kong Manager works well. http://example.com and http://km.konghq.com/manager.
Others can't.
EE's PR is here: https://github.com/Kong/kong-ee/pull/10260
https://github.com/Kong/docs.konghq.com/pull/7976
KM-516
> feat(gui): add a new feature to support multiple domains for KM GUI

- changelog/unreleased/kong/ai-gemini-fix-transformer-plugins.yml
- changelog/unreleased/kong/ai-transformers-bad-error-handling.yml
- kong/llm/drivers/gemini.lua
- kong/llm/init.lua
- spec/03-plugins/39-ai-request-transformer/02-integration_spec.lua
- spec/03-plugins/40-ai-response-transformer/02-integration_spec.lua
- spec/fixtures/ai-proxy/gemini/llm-v1-chat/responses/fails_safety.json
This fixes two related issues:
1. 'Gemini' when using a 'Google One' or 'Personal' subscription, was not forming the AI Transformer URL correctly, and resulted in all 404's
2. 'from_format' parser error handling was using the wrong return argument, resulting in `expected #1 got nil` errors to the client
AG-113
> fix: [AG-113] Gemini transformer plugins, incorrect URL and response error parsers

- changelog/unreleased/kong/bump-lua-resty-aws.yml
- kong-3.9.0-0.rockspec
> 1.5.4 (23-Sep-2024)
> fix: fix configure endpoint bug in getRegionPrefix https://github.com/Kong/lua-resty-aws/pull/129
Bump the library to fix a bug inside the underlying region prefix-generating logic. This bug will cause the library to use a wrong generated service endpoint in certain regions.
https://konghq.atlassian.net/browse/FTI-6159
> chore(deps): bump lua-resty-aws to 1.5.4

- CHANGELOG.md
- changelog/3.8.0/3.8.0.md
Fix https://github.com/Kong/kong/issues/13763
_[KAG-5596]_
[KAG-5596]: https://konghq.atlassian.net/browse/KAG-5596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(release): fix PR and Jira links in 3.8.0 changelog

- CHANGELOG.md
- changelog/3.8.0/3.8.0.md
Backport https://github.com/Kong/kong/pull/13767
_[KAG-5596]_
[KAG-5596]: https://konghq.atlassian.net/browse/KAG-5596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Backport -> release/3.8.x] chore(release): fix PR and Jira links in 3.8.0 changelog

- scripts/Dockerfile
- scripts/release-lib.sh
It was not easy to install and figure out all the dependencies for the update-copyright script. This PR aims to install all the required dependencies into a docker image and use it to execute the update-copyright script.
KAG-5297
> chore(release): use docker image to facilitate update-copyright step

- build/package/nfpm.yaml
- changelog/unreleased/kong/fix_service_file.yml
- scripts/explain_manifest/fixtures/alpine-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt
- scripts/explain_manifest/fixtures/amazonlinux-2023-amd64.txt
- scripts/explain_manifest/fixtures/debian-11-amd64.txt
- scripts/explain_manifest/fixtures/el8-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
- scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt
- scripts/explain_manifest/suites.py
This PR fixes an issue where the systemd unit file, `kong.service`, had gone missing from packages produced from the 2.8 branch(es).
Fix #_[KAG-5648]_
[KAG-5648]: https://konghq.atlassian.net/browse/KAG-5648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: Replace missing systemd Unit File (2.8)

- changelog/unreleased/kong/fix-wasm-check-missing-filters.yml
- kong/init.lua
- kong/runloop/wasm.lua
- spec/02-integration/20-wasm/11-missing-filters_spec.lua
This adds a check during `init` that will prevent Kong from starting if any filter chain entities are found in the database using a filter that is not installed. Example:
> Error: ./kong/cmd/start.lua:99: nginx: [error] init_by_lua error: /path/to/kong/init.lua:750: [wasm]: found one or more filter chain entities with filters that are not enabled/installed:
> filter chain: 9e0b56d6-0e8c-469f-bf15-142debdd5d05, filter: #1 (response_transformer)
> filter chain: 9e0b56d6-0e8c-469f-bf15-142debdd5d05, filter: #3 (response_transformer)
Previously, this condition would not be caught until the Wasm state is built during `init_worker`. This change brings Wasm more in line with the behavior of the plugins iterator.
[KAG-2636]
[KAG-2636]: https://konghq.atlassian.net/browse/KAG-2636?atlOrigin=eyJpIjo …
> fix(wasm): add a startup check for missing filters

- build/luarocks/templates/luarocks_exec.sh
Create symbolic links against `.dylib` instead of `.so` on macOS.
Cherry-pick to EE: https://github.com/Kong/kong-ee/pull/10522
_[KAG-5571]_
[KAG-5571]: https://konghq.atlassian.net/browse/KAG-5571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(build): fix exec script of LuaRocks on macOS

- CONTRIBUTING.md
https://github.com/Kong/kong/blob/master/CHANGELOG/README.md does not exist.
Fix the url. Although, should that point at [changelog-template.yaml](https://github.com/Kong/kong/blob/master/changelog/changelog-template.yaml) instead? 
I don't see anything in that readme directly relevant to contributors (who are not going to be generating a changelog themselves). Alternatively, as a new contributor, I'm not sure how to read these instructions and would be happy to update them :).
> Fix: Fix broken link in contributing.md

- changelog/unreleased/kong/bump-lua-resty-ljsonschema.yml
- kong-3.9.0-0.rockspec
Changelog for ljsonschema-1.2.0:
> 1.2.0 (23-Oct-2024)
> fix: properly calculate utf8 sequence lengths instead of byte count (https://github.com/Tieske/lua-resty-ljsonschema/pull/30)
> fix: support null as an option in enum types (https://github.com/Tieske/lua-resty-ljsonschema/pull/26)
> chore: update the test suite to a more recent version; 23.2.0 (https://github.com/Tieske/lua-resty-ljsonschema/pull/27)
> chore: list all disabled tests as pending (to make them visible) (https://github.com/Tieske/lua-resty-ljsonschema/pull/27)
> fix: fix numeric overflow (new case from updated test-suite) (https://github.com/Tieske/lua-resty-ljsonschema/pull/27)
> chore: restructure documentation and more repo-maintenance (https://github.com/Tieske/lua-resty-ljsonschema/pull/25)
FTI-5870, FTI-6171
> chore(deps): bump `lua-resty-ljsonschema` to 1.2.0

- kong/clustering/services/sync/rpc.lua
- kong/clustering/services/sync/strategies/postgres.lua
- kong/db/declarative/export.lua
> fix(clustering): delta version is null

- .github/workflows/release.yml
Updated kong/public-shared-actions to v2.7.3 which will use docker.io registry instead of ghcr to workaround the rate limiting issue we're encountering.
FIXME: the dockerhub trivy image when run as container still attempts to download trivy-db internally from GHCR that seems to be failing. So to unblock our development we have to temporarily disable the cis scan.
KAG-5670
> chore(ci): updated public-shared-actions to v2.7.3

- changelog/unreleased/kong/bump-lua-kong-nginx-module.yml
Fix https://konghq.atlassian.net/browse/FTI-6275
> chore(changelog): update changelog description

- changelog/unreleased/kong/fix-loggly-hostname-notfound.yml
- kong/pdk/node.lua
- kong/plugins/loggly/handler.lua
1. Refactor the PDK's `get_hostname` to use only the `gethostname` system call to retrieve the hostname.
2. Loggly uses the PDK's `get_hostname` to retrieve the hostname.
FTI-6046
> fix(loggly): fix the error caused by the missing /bin/hostname

- kong/clustering/services/sync/rpc.lua
Added comment for why we need to call synchronize the detlas twice.
Fix KAG-5589
> fix(incremental sync): added comment for 2 times do_sync

- spec/02-integration/03-db/08-declarative_spec.lua
- spec/internal/db.lua
We have some tests that polluted schema after run.
This is to guarantee no leftover dirty schema for the follow-up tests which may not tolerate that.
KAG-5040
> tests(db): Always do schema reset in `get_db_utils` 

- changelog/unreleased/kong/fix-parse-nested-parameters.yml
- kong/api/api_helpers.lua
- kong/tools/http.lua
- spec/02-integration/04-admin_api/13-plugin-endpoints_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/admin-api-method/api.lua
When using `curl` to send a form-urlencoded request with nested parameters, such as
```
$ curl -X POST http://localhost:8001/parsed_params \
--data 'items[1]=foo' \
--data 'items[2]=bar'
```
the expected response is `{"items":["foo","bar"]}`, but instead, it returns `{"items":{}}`.
This is actually an EE issue, but I see that there is a risk of this in CE even though it doesn't currently occur. So I initiated that fix on CE.
The cause of the problem is due to the fact that nested parameters are lost when the [decode_args](https://github.com/Kong/kong/blob/1c4b859be73f716b8e6796868cc35a9eee7413ca/kong/api/api_helpers.lua#L303) method is called twice, without this fix.
Fix FTI-6165
> fix(admin-api): nested parameters can be parsed correctly when using form-urlencoded requests

- kong/db/strategies/off/init.lua
> refactor(dbless): clean logic of select_by_field

- kong/db/declarative/import.lua
In this loop of _set_entity_for_txn, the ws_id has been modifed to default ws_id, but the following logic or entity will use this modified ws_id even though they are unreleated to previous modified ws_id.
Fix KAG-5710
> fix(incremental sync): fixed ws_id processing in _set_entity_for_txn

- changelog/unreleased/kong/feat-ai-proxy-disable-h2-alpn.yml
- kong-3.9.0-0.rockspec
- kong/init.lua
- kong/llm/proxy/handler.lua
- kong/pdk/client/tls.lua
- kong/pdk/private/phases.lua
- kong/plugins/ai-proxy/handler.lua
- kong/templates/nginx_kong.lua
- kong/templates/nginx_kong_stream.lua
- kong/tls/plugins/certificate.lua
- kong/tls/plugins/sni_filter.lua
- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/fixtures/1.2_custom_nginx.template
- t/01-pdk/14-client-tls/00-phase_checks.t
This change will disable HTTP/2 ALPN handshake for connections on routes configured with AI-proxy.
The following are the specific changes
- move tls related function `kong/tls/plugins/certificate.lua` and `kong/tls/plugins/sni_filter.lua` from ee to ce repo
- Based on https://github.com/Kong/kong/pull/13709 and https://github.com/Kong/lua-kong-nginx-module/pull/93, we introduce the `disable_http2_alpn` action in the ai-proxy plugin to solve the `ai-proxy` plugin did not work in HTTP2 case. After the current PR is merged,  HTTP/2 ALPN handshakes will be disabled for requests on routes configured with AI-proxy, and all these connections will fall back to the http1.1 protocol.
AG-119
> feat: disable HTTP/2 ALPN handshake for connections on routes configured with AI-proxy.

- kong/init.lua
- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
Let's fix the rest of the tests in another PR.
Fix KAG-5551
> fix(clustering): CP should support both v1 and v2

- kong/clustering/rpc/manager.lua
- kong/clustering/rpc/socket.lua
- kong/clustering/services/sync/hooks.lua
- kong/db/dao/init.lua
- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
The dao hook does not handle `upsert_by` event thus `PUT` method requests are missed and not propagated to DPs.
Fix KAG-5734 and [KAG-5551](https://konghq.atlassian.net/browse/KAG-5551) 
Related ticket: KAG-5723
[KAG-5551]: https://konghq.atlassian.net/browse/KAG-5551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(clustering/rpc): dao hooks of upsert/delete/update_by are missed

- .github/workflows/release.yml
backport of #13793 
Updated kong/public-shared-actions to v2.7.3 which will use docker.io registry instead of ghcr to workaround the rate limiting issue we're encountering.
FIXME: the dockerhub trivy image when run as container still attempts to download trivy-db internally from GHCR that seems to be failing. So to unblock our development we have to temporarily disable the cis scan.
KAG-5670
> chore(ci): updated public-shared-actions to v2.7.3 (#13793)

- spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua
- spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua
- spec/03-plugins/38-ai-proxy/04-cohere_integration_spec.lua
- spec/03-plugins/38-ai-proxy/05-azure_integration_spec.lua
- spec/03-plugins/38-ai-proxy/06-mistral_integration_spec.lua
- spec/03-plugins/38-ai-proxy/07-llama2_integration_spec.lua
- spec/03-plugins/38-ai-proxy/08-encoding_integration_spec.lua
- spec/03-plugins/38-ai-proxy/09-streaming_integration_spec.lua
In https://github.com/Kong/kong/commit/7d71b6b83601b541f6335cd06c09cc8e3d169138, we introduce disable http2 alpn in ai-proxy plugin, now all http2 force protocol test will failed, so do not need http2 test in ai-proxy anymore, because we have been disabled http2.
> test(ai-proxy): fix red test due to other feature break http protocol behavior

- kong/clustering/services/sync/rpc.lua
> refactor(clustering/rpc): code clean of full sync in rpc

- kong/clustering/services/sync/hooks.lua
- kong/clustering/services/sync/rpc.lua
- kong/clustering/services/sync/strategies/postgres.lua
> fix(clustering/rpc): cascade deleting for incremental sync

- kong/clustering/services/sync/rpc.lua
> refactor(clustering/sync): delta.ws_id is not necessary

- kong/db/schema/others/declarative_config.lua
- kong/tools/request_aware_table.lua
For the entity with multiple primary keys, like consumer_group_consumers, the pk_string() function construct incorrect pk string like `table: 0x028a49eda0:table: 0x0289c257b8`. Because it does not extract the internal id value. Here, we fix it with original lmdb logic get_cache_key_value(). Note this method directly gets id field name.
Fix KAG-5732
> fix(dbless): construct right pk string for entity with multiple primary keys

- kong/clustering/rpc/manager.lua
- kong/init.lua
> refactor(clustering/rpc): rework on rpc initial connection

- spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua
> tests(clustering): start/stop when incremental on

- kong/clustering/rpc/manager.lua
> refactor(clustering/rpc): dp does not need concentrator

- kong/plugins/acme/schema.lua
Just a small chore to use our table tools.
> style(acme): just use our table tools to shallow copy instead of tablex

- changelog/unreleased/kong/fix-core-pass-ctx-to-log-init-worker-errors.yml
- kong/init.lua
Just saw this on my local machine when started to kill -9 worker processes on a control plane. So just a tiny fix here. Not sure how easy this is to test, but it is quite an obvious fix and bug. Without this the `log_init_worker_errors` may runtime crash.
> fix(core): always pass `ngx.ctx` to `log_init_worker_errors`

- kong/clustering/control_plane.lua
- kong/clustering/services/sync/rpc.lua
> refactor(clustering): add `no_broadcast_crud_event` for dp status updating

- kong/clustering/services/sync/rpc.lua
With full sync (`wipe = true` in `do_sync()`), if we dont notify other workers with `declarative:reconfigure`, the registered callbacks in other workers will not be called, like updating `kong.default_workerspace`.
Note that when an empty-configured CP and DP start with incremental sync enabled, the DP will rebuild routers, plugins, and the balancer twice. This occurs because the DP currently calls do_sync() twice during a single sync operation. With incremental sync disabled, it rebuilds these components only once.
Fix KAG-5812
> fix(clustering/sync): notify declarative:reconfigure events for full sync

- kong/clustering/services/sync/rpc.lua
> refactor(clustering): dont generate event for full sync

- changelog/unreleased/kong/fix-schema-validation-with-nil-field.yml
- kong/db/schema/init.lua
- spec/01-unit/01-db/01-schema/06-routes_spec.lua
Adjusted schema validation logic to account for `nil` field scenario, ensuring proper handling of fields to prevent errors.
Fix:[FTI-6336](https://konghq.atlassian.net/browse/FTI-6336)
[FTI-6336]: https://konghq.atlassian.net/browse/FTI-6336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(schema): schema validation to handle potential `nil` field case

- kong/init.lua
Clustering initialization needs to be handled when dedicated worker is off
Fix KAG-5807
> fix(sync): full sync not working if dedicated disabled

- Makefile
https://konghq.atlassian.net/browse/FTI-6338
> bump: bump lua-reqwest in Makefile to fix macos build error

- kong/clustering/services/sync/rpc.lua
> fix(sync): prevent unnecessary modifications to kong.default_workspace

- .github/workflows/deck-integration.yml
**note:** do **not** cherry-pick to EE
The checkout step of these tests was using a secret that is not available to PRs opened from forks, which made it fail. This commit removes the token (not needed in CE), which makes the action fall back to the default github token.
> chore(ci): deck integration tests checkout secret

- changelog/unreleased/kong/wasm-filter-plugins.yml
- kong-3.9.0-0.rockspec
- kong/conf_loader/init.lua
- kong/db/dao/plugins.lua
- kong/db/schema/entities/filter_chains.lua
- kong/db/schema/init.lua
- kong/db/schema/json.lua
- kong/db/schema/others/wasm_filter.lua
- kong/db/schema/plugin_loader.lua
- kong/runloop/events.lua
- kong/runloop/plugins_iterator.lua
- kong/runloop/wasm.lua
- kong/runloop/wasm/plugins.lua
- spec/02-integration/20-wasm/09-filter-meta_spec.lua
- spec/02-integration/20-wasm/12-filters-as-plugins_spec.lua
This adds a new interface to wasm filters, allowing users to configure them in the same manner as a plugin entity.
From the admin API/database/plugin entity side of things, inspiration was taken from the implementation of plugin servers, so there are parallels with regards to how filters and their schemas are discovered. Some refactoring was done so that the `filter` Lua schema could be reused between both the `filter_chain` entity and this new plugin schema interface.
This feature works in concert with the existing filter chain model. On the runloop side, we iterate over plugin entities to discover the wasm filters and create proxy-wasm filter chains on-the-fly. When an existing `filter_chain` entity exists for a service/route, we append filters to it. …
> feat(wasm): add wasm plugin interface

- build/templates/venv.fish
I found out that PATH was not returned to its original state on with `deactivate` in fish shell. This fixes it.
> fix(venv): reset PATH to original state on deactivate

- changelog/unreleased/kong/feat-plugin-conf-ws-id.yml
- changelog/unreleased/kong/fix-plugin-conf-ws-id.yml
https://konghq.atlassian.net/browse/FTI-6200
> chore(changelog): update changelog type

- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
- spec/02-integration/19-incrmental_sync/01-sync_spec.lua
Using `worker_state_update_frequency = 1` will reduce the time cost of testing significantly.
KAG-5551
> tests(clustering): rebuild router with small worker_state_update_frequency

- kong/plugins/session/session.lua
This log line in the session plugin does seem like a leftover for debugging purpose.
> refactor(plugins/session): remove seemingly useless log

- changelog/unreleased/kong/deprecate_node_id.yml
- kong/pdk/node.lua
`node_id` in configuration is deprecated in this PR, which means it is not recommended to be specified manually.
A warning message is printed in error log if the `node_id` is recognized in the configuration.
FTI-6221
> fix(core): `node_id` in configuration is deprecated in this PR

- changelog/unreleased/kong/chore-clustering-log-level.yml
- kong/clustering/data_plane.lua
Changed error log level from ERROR to WARN for better clarity and to avoid alarming users unnecessarily when control plane connections break. This adjustment enhances user experience under connection interruptions.
Fix:[FTI-6238](https://konghq.atlassian.net/browse/FTI-6238)
[FTI-6238]: https://konghq.atlassian.net/browse/FTI-6238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(clustering): adjust error log levels for control plane connections

- changelog/unreleased/kong/fix-jwt-plugin-rsa-public-key-b64decoded
- changelog/unreleased/kong/fix-jwt-plugin-rsa-public-key-b64decoded.yml
- kong/plugins/jwt/handler.lua
- spec/03-plugins/16-jwt/03-access_spec.lua
never base64 decode a rsa public key
- ~~[ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~~
Fix #13710
> fix(jwt): remove chances to base64 decode a rsa_public_key

- changelog/unreleased/kong/prometheus-wasmx-metrics.yml
- kong-3.9.0-0.rockspec
- kong/plugins/prometheus/exporter.lua
- kong/plugins/prometheus/wasmx.lua
- kong/runloop/wasm.lua
- spec/02-integration/20-wasm/04-proxy-wasm_spec.lua
- spec/02-integration/20-wasm/09-filter-meta_spec.lua
- spec/03-plugins/26-prometheus/09-wasmx_spec.lua
- spec/fixtures/proxy_wasm_filters/tests/src/filter.rs
- spec/fixtures/proxy_wasm_filters/tests/src/metrics.rs
- spec/fixtures/proxy_wasm_filters/tests/src/test_http.rs
> feat(prometheus): add wasmx metrics

- Makefile
Align ee Makefile change in https://github.com/Kong/kong/blob/master/Makefile
KAG-5513
> chore: install rust toolchain in makefile dev

- kong/clustering/rpc/manager.lua
- kong/init.lua
- spec/02-integration/09-hybrid_mode/14-dp_privileged_agent_spec.lua
> feat(clustering/rpc): meta rpc call handshake

- build/kong_crate/deps.bzl
- crate_locks/atc_router.Cargo.lock
- crate_locks/atc_router.lock
ATC-Router requires rust version >= 1.81.0 so we bump to 1.82.0
> chore(toolchain): bump rust toolchain to 1.82.0

- CHANGELOG.md
Updating the changelog to include 3.8.1 changes.
> docs(changelog): Update changelog for 3.8.1

- .github/workflows/release.yml
- scripts/explain_manifest/main.py
it's recently removed from t he rockylinux:9 baseimage
* fix(explain_manifest): pipe output of rpm2archive
cherry-picked from https://github.com/Kong/kong-ee/pull/10796
> fix(cd): install config-manager for rhel9 (#10796)

- kong/clustering/services/sync/init.lua
- kong/clustering/services/sync/rpc.lua
> fix(clustering/rpc): try sync after rpc is ready

- kong/runloop/handler.lua
The init router creation could be interrupted and we assume it will always be a non-nil value after the `init_worker` phase, which may cause 500 to proxy requests.
Let's create an empty router before creating the initial router.
As the issue occurs at this version I omitted the changelog.
Fix KAG-5815
> fix(core): initialize route to avoid race (500)

- kong/clustering/rpc/manager.lua
- kong/clustering/services/sync/rpc.lua
- spec/02-integration/18-hybrid_rpc/01-rpc_spec.lua
May change after KAG-5369  and #13887
KAG-5772
> fix(clustering): report node version in sync

- kong/clustering/services/sync/init.lua
> refactor(clustering/sync): use CLUSTERING_PING_INTERVAL as sync delay

- .github/workflows/release.yml
- scripts/explain_manifest/main.py
it's recently removed from t he rockylinux:9 baseimage
* fix(explain_manifest): pipe output of rpm2archive
(cherry picked from commit 60d4bad246140dae78b5831c4ff14a1ed55c9364)
> [backport -> release/3.8.x] fix(cd): install config-manager for rhel9 (#10796) (#13926)

- changelog/unreleased/kong/fix-nil-reference-schema-checker.yml
- kong/db/schema/init.lua
- spec/01-unit/01-db/01-schema/01-schema_spec.lua
This fixes a nil reference if a checker referred to an inexistent field.
```
./kong/db/schema/init.lua:1267: attempt to index a nil value
./kong/db/schema/init.lua: in function 'run_entity_check'
./kong/db/schema/init.lua:1384: in function 'run_checks'
./kong/db/schema/init.lua:1400: in function 'run_entity_checks'
./kong/db/schema/init.lua:2101: in function 'validate'
./kong/db/schema/init.lua:957: in function 'validate_field'
./kong/db/schema/init.lua:1187: in function 'validate_fields'
./kong/db/schema/init.lua:2091: in function 'validate_insert'
./kong/db/dao/init.lua:470: in function 'check_insert'
./kong/db/dao/init.lua:1155: in function 'insert_entity'
./kong/api/endpoints.lua:409: in function 'fn'
./kong/api/api_helpers.lua:329: in function …
```
> fix(schema): run check on invalid field

- kong/plugins/acme/schema.lua
Updating the ACME plugin's `config.storage` parameter description to:
* Mention that shm is not supported in hybrid, and kong storage is not supported in Konnect.
* Remove the line about supported backends, as those as listed in the `one_of` field in the schema.
Resolves the last piece of https://konghq.atlassian.net/browse/DOCU-2910. Issue recently came up with a user, see link to slack convo in ticket.
- [ N/ A ] The Pull Request has tests
> docs: describe storage limitations in hybrid and Konnect for ACME plugin

- spec/01-unit/01-db/07-dao/01-plugins_spec.lua
If a plugin version field is greater than 9, the previous match sequence would not catch it. This change tests for `"\d+\.\d+\.\d+"` and not `"[0-9]\.[0-9]\.[0-9]"`,
KAG-5534
> tests(dao): match versions greater than 9

- kong/clustering/services/sync/rpc.lua
When we start up DP, we need to make a meta call to CP first, so the first `do_sync` during the initial sync fails. It reports an ERR error: `rpc.lua:432: unable to create worker mutex and sync: rpc is not ready`. This experience is not ideal.
The initialization of the configuration also fails, and we have to wait for ourselves to wait 30 seconds (`sync_every(30s)`) before the configuration can sync successfully. This means that the DP will be unable to function for a period of time after connecting.
Fix KAG-5922
> fix(sync): extend wait time for RPC layer initialization

- build/openresty/patches/ngx_lua-0.10.26_07-tcpsock-setkeepalive-tls13.patch
- build/openresty/patches/ngx_stream_lua-0.0.14_06-tcpsock-setkeepalive-tls13.patch
- spec/internal/ssl.lua
Fixing the issue where a connection can't be setkeepalive successfully when using TLSv1.3. The issue was originally found in the tcp-log plugin.
- https://github.com/openresty/lua-nginx-module/commit/bf4bdcd5b299fc5680eb7d6fd594d4a49983de21
- https://github.com/openresty/lua-nginx-module/commit/ea09d92adf835e30cab8d79343c7b8266e888128
- https://github.com/openresty/lua-nginx-module/commit/816483d6e66efa1b5a93571932d4e33f336b2d36
- https://github.com/openresty/stream-lua-nginx-module/commit/5954e22fa1e03125df7c0c55aa003c1076e02f7c
- https://github.com/openresty/stream-lua-nginx-module/commit/69f0cd762112a6e0cddb07f2b5192e9a65034a93
- https://github.com/openresty/stream-lua-nginx-module/commit/1e1d93eac29a3d8ffe2183c0470c090ef4da700f
https://konghq.atlassian.net/browse/FTI-6190
> fix(patches): add patches from upstream openresty

- kong/clustering/services/sync/rpc.lua
- kong/constants.lua
It will retry until the version matches
Fix KAG-5857 KAG-5876
> fix(clustering/sync): avoiding long delay caused by race condition

- kong-3.10.0-0.rockspec
- kong/meta.lua
> chore(release): bump version to 3.10 as part of the feature freeze

- changelog/unreleased/kong/fix-nonexisting-anonymous-error-message.yml
- kong/plugins/basic-auth/access.lua
- kong/plugins/hmac-auth/access.lua
- kong/plugins/jwt/handler.lua
- kong/plugins/key-auth/handler.lua
- kong/plugins/ldap-auth/access.lua
- kong/plugins/oauth2/access.lua
- spec/03-plugins/09-key-auth/02-access_spec.lua
- spec/03-plugins/10-basic-auth/03-access_spec.lua
- spec/03-plugins/16-jwt/03-access_spec.lua
- spec/03-plugins/19-hmac-auth/03-access_spec.lua
- spec/03-plugins/20-ldap-auth/01-access_spec.lua
- spec/03-plugins/25-oauth2/03-access_spec.lua
https://konghq.atlassian.net/browse/FTI-5392
> fix(plugins): Improved the error message when an anonymous consumer was configured but did not exist

- kong/clustering/services/sync/rpc.lua
- kong/conf_loader/constants.lua
- kong/templates/kong_defaults.lua
> feat(clustering): full sync threshold should be configureable

- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
Enable all tests of 09-hybrid_mode/01-sync_spec.lua under incremental sync on mode
Fix KAG-5951
> tests(clustering/rpc): enable 09-hybrid_mode/01-sync_spec.lua for incremental sync

- kong/runloop/wasm.lua
- spec/02-integration/20-wasm/12-filters-as-plugins_spec.lua
- spec/fixtures/proxy_wasm_filters/tests/src/test_http.rs
- spec/fixtures/proxy_wasm_filters/tests/src/types.rs
Before this change, execution order of filter plugins was subject to ordering returned by the underling DB implementation of `kong.db.plugins:each()`.
This adds an extra step that sorts all discovered filter plugins by name so that execution order is more consistent.
[KAG-5851](https://konghq.atlassian.net/browse/KAG-5851)
[KAG-5851]: https://konghq.atlassian.net/browse/KAG-5851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(wasm): execute filter plugins in a consistent order

- kong/clustering/services/sync/rpc.lua
> refactor(clustering/sync): clean the logic of sync_once

- spec/02-integration/19-incrmental_sync/01-sync_spec.lua
- spec/02-integration/19-incrmental_sync/02-multiple_dp_nodes_spec.lua
> tests(clustering/sync): test with multiple dp nodes

- kong/llm/plugin/ctx.lua
- kong/llm/plugin/shared-filters/normalize-request.lua
- kong/llm/plugin/shared-filters/serialize-analytics.lua
- kong/plugins/ai-prompt-decorator/filters/decorate-prompt.lua
- spec/03-plugins/41-ai-prompt-decorator/02-integration_spec.lua
>  fix(ai-prompr-decorator): fix unable to modify request 

- kong/clustering/services/sync/rpc.lua
Reverts Kong/kong#13956, it may cause tests flaky.
> Revert "refactor(clustering/sync): clean the logic of sync_once"

- changelog/verify-prs
The PR title helps the release runners a lot when analyzing the `changelog/verify-prs` report to speed up the process. This PR is to add the title in the report and the title and PR URL are concatenated with ` - `.
KAG-5972
> chore(tools): show PR title in the changelog/verify-prs report

- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/02-integration/02-cmd/03-reload_spec.lua
- spec/02-integration/04-admin_api/22-debug_spec.lua
- spec/02-integration/11-dbless/03-config_persistence_spec.lua
- spec/internal/wait.lua
This PR removes an useless `strategy` argument from one the helpers function `reload_kong`, as well as another related function `wait_until_no_common_workers`.
This argument(and the `reload_kong` function itself) was made a helpers function in PR #8670 (see the diff [here](https://github.com/Kong/kong/commit/fe20857b0edd52f6f1f977d28269535e3c976746#diff-5ef8552b54a226fa973a6c33644d117aba05c008e8e60efcc8508629eed713afR2805), which used to be a local helper function inside a test case. The argument `strategy` was only for sleeping a bit more time when the test was running under a Cassandra deployment and there was no other use besides this.
This argument was removed in EE earlier in another PR https://github.com/Kong/kong-ee/pull/3420, in commit …
> tests(*): remove useless strategy arg from reload_kong helper function

- .busted
This adds the `lazy` setting to our `.busted` file. This is the equivalent of adding the `--lazy` flag when running the busted CLI, which essentially causes every `setup()` and `teardown()` invocation to behave like `lazy_setup()` and `lazy_teardown()`.
We have a bunch of test files that are using `setup()`/`teardown()` instead of the `lazy_` variants, and making one small change to the `.busted` file saves us the trouble of updating all of them (including EE).
> what's the difference between `setup()` and `lazy_setup()`?
`setup()` always runs, whereas `lazy_setup()` only runs if at least one test case (`it(...)`) is scheduled to run:
```lua
describe("strict", function()
setup(function()
-- I always run, even if the following test is skipped
print("[strict] doing setup things")
end) …
```
> tests(busted): make all setup() and teardown() calls lazy

- spec/02-integration/20-wasm/06-clustering_spec.lua
- spec/02-integration/20-wasm/08-declarative_spec.lua
- spec/02-integration/20-wasm/10-wasmtime_spec.lua
* fixed a couple logic bugs in usage of `assert.eventually()`
* added missing `#off`, `#postgres`, and `#db` tags that are used for filtering in CI
KAG-5962
> tests(wasm): add missing filter tags

- .github/matrix-full.yml
- scripts/explain_manifest/config.py
- scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
Reverts Kong/kong#13987
Ubuntu 20.04 is not EOL'ed.
> Revert "chore(cd): remove ubuntu-20.04"

- kong/clustering/data_plane.lua
Log ping sends only if the config hash changes and add the hash in the log statement. This enables us to see how long the gateway is running with the same configuration.
> style(clustering): log pings only when the hash changes 

- kong/runloop/handler.lua
> fix(sync): do not introduce router rebuild timer for full sync

- .busted
- kong-3.10.0-0.rockspec
- kong/cmd/init.lua
- kong/cmd/utils/timer.lua
- spec/busted-ci-helper.lua
This takes the same fix that was applied to Kong's CLI framework in 26b2db7b94f3158e4ae1f5a8468b9bde832a19c7 and applies it to busted test runs.
* a7d3e8f963a590545e89f1934c1fc194d122863f - factor out the timer shutdown logic into `kong.cmd.utils.timer.shutdown()`
* c01e93dadd0ff8b16b929e61d21db42a2007ebc7
- hook into busted's `exit` event to call `kong.cmd.utils.timer.shutdown()` at the end of execution
- add `--helper spec/busted-ci-helper.lua` as a default option in `.busted` 
* ff03381af71d211985067db382dfb80af99ee461 - refactor `spec/busted-ci-helper.lua` to keep concerns separated
Test performance. If the timer instance isn't explicitly torn down, it delays the worker process shutdown for ~1s. In CI where each test file is executed via a separate `busted` CLI invocation, this adds …
> tests(*): shutdown timerng instance after test completion

- build/openresty/wasmx/filters/variables.bzl
- changelog/3.9.0/kong/bump-datakit.yml
- changelog/3.9.0/kong/remove-datakit.yml
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
KAG-6021
see also: #14013 (master branch PR)
It seemed silly to include the dependency bump changelog entry for datakit, so I removed `changelog/3.9.0/kong/bump-datakit.yml`.
> chore(wasm): remove bundled datakit filter

- CHANGELOG.md
- changelog/3.9.0/3.9.0.md
Update changelog for the 3.9.0 release.
> docs(changelog): update 3.9.0 changelog

- changelog/unreleased/kong/fix-dbless-consumer-credential-error.yml
- kong/db/schema/others/declarative_config.lua
- spec/02-integration/04-admin_api/15-off_spec.lua
This applies the same fix as b8891eb969a00469afb2a70d8a4a605497c1fc40 (#12797) but to a different code path that checks fields with a unique constraint.
closes #13998
see also:
FTI-6351
FTI-6318
KAG-6032
> fix(dbless): nest unique field errors for child entities

- kong/clustering/services/sync/rpc.lua
[KAG-5944](https://konghq.atlassian.net/browse/KAG-5944)
See https://github.com/Kong/kong/pull/13896 and https://github.com/Kong/kong/pull/13956
[KAG-5944]: https://konghq.atlassian.net/browse/KAG-5944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(clustering/sync): clean the logic of sync_once_impl()

- kong/clustering/rpc/manager.lua
- kong/clustering/utils.lua
- spec/02-integration/09-hybrid_mode/10-forward-proxy_spec.lua
- spec/02-integration/09-hybrid_mode/14-dp_privileged_agent_spec.lua
The original hybrid mode connections like full sync (sync v1) support forward proxy via the option `cluster_use_proxy`. While clustering RPC protocol does not support this, this commit introduces this feature to RPC protocol.
Fix KAG-5555
> fix(clustering/rpc): support `cluster_use_proxy` option for clustering rpc protocol

- build/build_system.bzl
Needed by https://github.com/Kong/kong-ee/pull/11007
> feat(build): allow github_release to download without extract

- kong-3.9.1-0.rockspec
- kong/meta.lua
Done as part as the 3.9.0 release
> release: 3.9.1

- changelog/unreleased/kong/fix-error-flattening-json.yml
- kong/db/errors.lua
- kong/tools/cjson.lua
- spec/01-unit/01-db/01-schema/11-declarative_config/05-error-flattening_spec.lua
You know the deal: you create a list-like table but don't put anything in it, and all the sudden cjson thinks it's an object!
I wonder how many more times I'll fix this in my tenure at Kong :thinking:
Well, this one is fixed. I even added a little helper function for it.
KAG-6032
> fix(db): ensure that flattened_errors is encoded as a JSON array

- kong/clustering/data_plane.lua
- kong/clustering/rpc/manager.lua
- kong/clustering/services/sync/init.lua
- kong/clustering/utils.lua
- kong/init.lua
- spec/02-integration/09-hybrid_mode/15-cp_inert_rpc_sync_spec.lua
> refactor(clustering/rpc): post event when rpc is ready

- changelog/unreleased/kong/perf-lmdb-remove-global-query-key.yml
- kong/db/declarative/import.lua
- kong/db/declarative/init.lua
- kong/db/strategies/off/init.lua
- spec/01-unit/01-db/10-declarative_spec.lua
- spec/01-unit/01-db/11-declarative_lmdb_spec.lua
- spec/02-integration/04-admin_api/14-tags_spec.lua
1. redesign the key format for LMDB
2. remove the key with * workspace
3. search all the workspaces if upper user calls `select()` API without providing the specific workspace id
Fix KAG-5704
> perf(lmdb): remove the key with global workspace id *

- changelog/unreleased/kong/fix-potential-socket-connection-leak.yml
- kong/clustering/rpc/manager.lua
- kong/clustering/utils.lua
For websocket client, we should close socket connection by `websocket.client.close()` when there's error on `websocket.client.connect`, because `connect` failure will leave an occupied socket. We should not rely on GC to release the socket connection.
Fix https://konghq.atlassian.net/browse/KAG-5361
> close socket connection when websocket connect failed to avoid potential leak

- changelog/unreleased/kong/feat-variable-resource-attributes.yml
- kong/plugins/opentelemetry/handler.lua
- kong/plugins/opentelemetry/logs.lua
- kong/plugins/opentelemetry/traces.lua
- kong/plugins/opentelemetry/utils.lua
- spec/03-plugins/37-opentelemetry/02-schema_spec.lua
- spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
- spec/03-plugins/37-opentelemetry/07-utils_spec.lua
This change allows render resource attributes as lua code.
For example,
```
config:
traces_endpoint: "https://otlp-red-saas.instana.io:4318/v1/traces"
resource_attributes:
host.id: "$(headers.host)"
```
`host.id` is `0.0.0.0:9000` or depends on `headers.host` value. 
Fix #12538
> feat(opentelemetry): support variable resource attributes 

- spec/01-unit/09-balancer/03-consistent_hashing_spec.lua
[KAG-5551](https://konghq.atlassian.net/browse/KAG-5551)
[KAG-5551]: https://konghq.atlassian.net/browse/KAG-5551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(tests): assertions in test should use assert.is_true

- bin/busted
- spec/02-integration/01-helpers/05-rpc-mock_spec.lua
- spec/02-integration/18-hybrid_rpc/05-sync-rpc_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-debug/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-debug/schema.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-hello-test/api.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-hello-test/handler.lua
- spec/helpers/rpc_mock/cp.lua
- spec/helpers/rpc_mock/default.lua
- spec/helpers/rpc_mock/dp.lua
- spec/helpers/rpc_mock/readme.md
- spec/helpers/rpc_mock/setup.lua
- spec/internal/misc.lua
RPC needs mock tests
doc: https://github.com/Kong/kong/blob/rpc-mock/spec/helpers/rpc_mock/readme.md
Fix KAG-5551
> tests(clustering/rpc): rpc mock/hook

- kong/runloop/handler.lua
1. From the perspective of more precise searching for services from `select` API, the route here already has a ws_id, so we should directly search for the service under the specific workspace
2. LMDB has removed all the global query keys (see https://github.com/Kong/kong/pull/14028), if we select services without ws_id, it will search it through all the workspace, which has a performance issue.
Fix KAG-6087, KAG-5704
> perf(router): load service with route.ws_id while building routers

- changelog/unreleased/kong/session_store_metadata.yml
- kong-3.10.0-0.rockspec
- kong/plugins/session/daos.lua
- kong/plugins/session/daos/session_metadatas.lua
- kong/plugins/session/migrations/003_330_to_3100.lua
- kong/plugins/session/migrations/init.lua
- kong/plugins/session/schema.lua
- kong/plugins/session/session.lua
- kong/plugins/session/storage/kong.lua
- kong/plugins/session/strategies/postgres/session_metadatas.lua
- spec/03-plugins/30-session/02-kong_storage_adapter_spec.lua
- spec/05-migration/plugins/session/migrations/003_330_to_3100_spec.lua
Engineering brief:
https://docs.google.com/document/d/1r7nSZGOlTVhupoVGQ6Ymqsaw64eGHKSMibko8FgrwAQ/edit?tab=t.0
**### This PR won't bring a break change.**
Add two new configurations`hash_subject`(by default false) and `store_metadata`(by default false). Please ref [here](https://github.com/bungle/lua-resty-session?tab=readme-ov-file#session-configuration).
Add a new table `session_metadatas` to store the session's metadata.
```
CREATE TABLE IF NOT EXISTS session_metadatas(
id            uuid,
session_id    uuid                    REFERENCES "sessions" ("id") ON DELETE CASCADE,
sid           text,
subject       text,
audience      text,
created_at    timestamp WITH TIME ZONE,
PRIMARY KEY (id)
);
```
**Why to do this?**
Please check this PR's ticket.
KM-788
> feat(sessions): store session's meatadata

- CHANGELOG.md
Remove the incorrect merge conflict line from the CHANGELOG.md.
> docs(changelog): remove the incorrect merge conflict line

- changelog/unreleased/kong/fix-potential-socket-connection-leak.yml
The follow up of https://github.com/Kong/kong/pull/14038
Fix https://konghq.atlassian.net/browse/KAG-5361
> docs(changelog): clarify the changelog entry of #14038   

- changelog/unreleased/kong-ee/fix-certificate-reference.yml
- kong/resty/mlcache/init.lua
- spec/02-integration/13-vaults/05-ttl_spec.lua
- t/05-mlcache/07-l1_serializer.t
Manual backport https://github.com/Kong/kong-ee/pull/10984 to CE
When set the cert to an invalid string in the vault, and then correct the string, kong will not start to use the correct certificate even though `kong vault` command shows the correct certiticate being returned.
This is because the initial invalid string has already been cached in the L2 cache by mlcache, and it will not be updated via the L3 cache callback afterward.
When mlcache fails during the execution of the `l1_serializer`, it caches the result retrieved from the L3 cache callback the first time in the L2 cache permanently. This means that subsequent calls to `cache.get()` will never fetch data from the L3 cache but will directly retrieve it from the L2 cache.
To avoid this situation, when the `l1_serializer` fails, …
> fix(certificate): unable to refresh certificate entity with vault reference when initial with an invalid string

- kong/clustering/data_plane.lua
- kong/clustering/services/sync/init.lua
> feat(clustering/rpc): always sync when rpc connected

- kong/clustering/services/sync/init.lua
> fix(clustering/rpc): invoke `notify_new_version` on events `clustering, push_config`

- kong/clustering/data_plane.lua
- kong/clustering/services/sync/init.lua
- kong/clustering/services/sync/rpc.lua
> feat(clustering/rpc): stop ngx.timer.every if no sync.v2

- kong/clustering/rpc/manager.lua
- kong/clustering/services/sync/init.lua
> feat(clustering/rpc): generate rpc disconnected event

- kong/clustering/services/sync/rpc.lua
> fix(clustering/rpc): dont start too many timers for sync

- kong/clustering/compat/removed_fields.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
Add compatibility to this PR. https://github.com/Kong/kong/pull/13990
KM-878
> fix(session): adds a compatablity for session

- .github/workflows/autodocs.yml
- .github/workflows/build_and_test.yml
- .github/workflows/changelog-validation.yml
- .github/workflows/label-schema.yml
- .github/workflows/release.yml
- .github/workflows/update-test-runtime-statistics.yml
> chore(ci): pin third-party GitHub actions to specific commit hashes

- changelog/unreleased/kong/fix-ai-chunking.yml
- kong-3.10.0-0.rockspec
- kong/llm/plugin/base.lua
- kong/llm/plugin/ctx.lua
- kong/llm/plugin/shared-filters/enable-buffering.lua
- kong/llm/plugin/shared-filters/normalize-response-header.lua
- kong/llm/plugin/shared-filters/parse-sse-chunk.lua
- kong/plugins/ai-proxy/handler.lua
- spec/03-plugins/38-ai-proxy/09-streaming_integration_spec.lua
Fixes an issue where "AI streaming responses" were returning all inside a single chunk, instead of being returned chunk-by-chunk to the client.
Also fixes other parsing issues with Bedrock, where the wrong response content-type was used.
FTI-6419
> fix(ai): response stream chunking de-buffering

- changelog/unreleased/kong/fix-socket-path-permissions.yml
- kong/cmd/utils/prefix_handler.lua
When umask is configured to `0027`, the newly created `kong_config.socket_path` directory inherits permissions `750`, which restricts access for worker processes. This commit ensures that the `socket_path` directory is explicitly set to permissions `755` using `chmod 755`, thereby preventing permission-related errors and allowing proper access for all necessary processes.
Fix: [FTI-6298](https://konghq.atlassian.net/browse/FTI-6298)
[FTI-6298]: https://konghq.atlassian.net/browse/FTI-6298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(core): set correct permissions for socket path when umask is set to `0027`

- build/luarocks/BUILD.luarocks.bazel
- build/luarocks/luarocks_repositories.bzl
since lua-messagepack 0.5.2 has been archived, we can only install it directly via rock.
Fix: [FTI-6417](https://konghq.atlassian.net/browse/FTI-6417)
[FTI-6417]: https://konghq.atlassian.net/browse/FTI-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): install lua-messagepack 0.5.2 by rock directly

- .github/actions/build-wasm-test-filters/action.yml
- scripts/build-wasm-test-filters.sh
See https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html and https://github.com/rust-lang/rust/pull/126662/
Note: this only affects filters built/used for integration tests.
> chore(build): rename rust target wasm32-wasi to wasm32-wasip1

- .github/workflows/autodocs.yml
- .github/workflows/build_and_test.yml
- .github/workflows/changelog-validation.yml
- .github/workflows/label-schema.yml
- .github/workflows/release.yml
- .github/workflows/update-test-runtime-statistics.yml
[KAG-6149](https://konghq.atlassian.net/browse/KAG-6149)
(cherry picked from commit 0a440b6eca935cc7c49a29fc13c6e4f04b5adfcc)
[KAG-6149]: https://konghq.atlassian.net/browse/KAG-6149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [backport to release/3.9.x] chore(ci): pin third-party GitHub actions to specific commit hashes (#14115)

- kong/clustering/services/sync/rpc.lua
- kong/clustering/services/sync/strategies/postgres.lua
- kong/db/declarative/import.lua
- spec/02-integration/18-hybrid_rpc/05-sync-rpc_spec.lua
> feat(clustering/rpc): change sync version to string

- changelog/unreleased/kong/fix-consistent-hashing-for-hyphenated-pascal-case-headers.yml
- kong/runloop/balancer/init.lua
- spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua
Consistent hashing was not correctly handling headers with hyphens and PascalCase formatting, resulting in uneven distribution of requests across upstream targets.
Fix: [FTI-6431](https://konghq.atlassian.net/browse/FTI-6431)
[FTI-6431]: https://konghq.atlassian.net/browse/FTI-6431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(balancer): handle hyphenated-Pascal-case headers in consistent hashing

- crate_locks/README.md
> fix(docs): fix a typo in bash commands of crate_locks readme

- kong/clustering/services/sync/rpc.lua
- kong/clustering/services/sync/strategies/postgres.lua
KAG-5894
Clean the code of #14078
> refactor(clustering/rpc): move is_valid_version() to strategies

- kong/runloop/handler.lua
In rare cases, the rebuild timer will interrupt the reconfigure handler because of `router was changed while rebuilding it`, which results in an outdated plugin iterator and balancer.
It is hard to test this rare race condition.
[KAG-6015]
[KAG-6015]: https://konghq.atlassian.net/browse/KAG-6015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(runloop): skip router rebuilding if reconfigure is running

- build/openresty/wasmx/filters/variables.bzl
- changelog/unreleased/kong/remove-datakit.yml
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
* chore(wasm): remove bundled datakit filter
* change log level
(cherry picked from commit f10cd09bc4c5f515c72b2987d441dc1d5a389653)
kong/kong#14013
> [backport to release/3.7.x] chore(wasm): remove bundled datakit filter (#14013)

- build/openresty/wasmx/filters/variables.bzl
- changelog/unreleased/kong/remove-datakit.yml
- kong/conf_loader/init.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/02-integration/20-wasm/07-reports_spec.lua
* chore(wasm): remove bundled datakit filter
* change log level
(cherry picked from commit f10cd09bc4c5f515c72b2987d441dc1d5a389653)
kong/kong#14013
> [backport to release/3.8.x] chore(wasm): remove bundled datakit filter (#14013)

- spec/02-integration/18-hybrid_rpc/07-notification_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-notification-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-notification-test/schema.lua
KAG-6157
Add test cases for https://github.com/Kong/kong/pull/13948
> tests(clustering/rpc): add cases for notifications

- kong/clustering/services/sync/rpc.lua
This bug was found when I tried to fix some failed test cases, so we don't need to write extra tests.
[KAG-6176]
[KAG-6176]: https://konghq.atlassian.net/browse/KAG-6176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(clustering/rpc): record the default workspace after the dropping the lmdb

- spec/03-plugins/11-correlation-id/02-schema_spec.lua
> tests(clustering): enable rpc sync on test

- kong/clustering/rpc/manager.lua
- kong/clustering/rpc/socket.lua
- spec/02-integration/18-hybrid_rpc/06-batch-rpc_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-batch-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-batch-test/schema.lua
> refactor(clustering/rpc): support rpc batching on dp side

- changelog/unreleased/kong/fix-ai-analytics-key.yml
change.
Add the missing changelog introduced during 3.9.
The change is being reverted on 3.9 https://github.com/Kong/kong-ee/pull/11135.
[AG-196](https://konghq.atlassian.net/browse/AG-196)
[AG-196]: https://konghq.atlassian.net/browse/AG-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(changelog): add the missing changelog of AI analytics breaking

- kong/clustering/rpc/manager.lua
> style(clustering/rpc): fix typo of META_V1

- .github/workflows/release.yml
Separate development docker repository from production repository.
KAG-6137
> chore(cd): update prerelease docker repository

- changelog/unreleased/kong/fix-ai-azure-streaming.yml
- kong/llm/drivers/shared.lua
Fixes Azure streaming when "JSON mode" is used (i.e. when inline content safety is enabled).
It broke because the SSE chunk would start with `[` or `'` and be caught by the wrong switch statement in the parser.
[FTI-6419](https://konghq.atlassian.net/browse/FTI-6419)
[FTI-6419]: https://konghq.atlassian.net/browse/FTI-6419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ai): fix Azure streaming with raw JSON transmission mode

- changelog/unreleased/kong/fix-header_cache.yml
- kong/runloop/handler.lua
- spec/03-plugins/28-grpc-gateway/01-proxy_spec.lua
- spec/03-plugins/32-grpc-web/01-proxy_spec.lua
A regression in kong.tools.http.get_header() where the header cache was probably a stale one was causing `grpc-web` or `grpc-gateweay` plugins unable to work.
FTI-6410
> fix(plugins): Fixed the stale header cache that causes a break in `grpc-web` & `grpc-gateway` plugins

- .github/actions/build-wasm-test-filters/action.yml
actions-rs/cargo and actions-rs/toolchain
KAG-6149
> chore(ci): pin 3rd-party actions to specific commit hashes

- spec/02-integration/18-hybrid_rpc/07-notification_spec.lua
- spec/02-integration/18-hybrid_rpc/08-sync_v2_get_delta_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-get-delta-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-get-delta-test/schema.lua
> tests(clustering/rpc): add cases for sync.v2.get_delta

- kong/clustering/rpc/socket.lua
- spec/02-integration/18-hybrid_rpc/02-error_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-error-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-error-test/schema.lua
> tests(clustering/rpc): add cases for rpc error handler

- spec/02-integration/18-hybrid_rpc/06-batch-rpc_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-batch-test/handler.lua
> tests(clustering): clean assertions in batch tests

- spec/03-plugins/11-correlation-id/02-schema_spec.lua
This test is flaky in master:
* https://github.com/Kong/kong/actions/runs/12790828477/job/35657524113
* https://github.com/Kong/kong/actions/runs/12765031186/job/35578409591
[KAG-6207]
[KAG-6207]: https://konghq.atlassian.net/browse/KAG-6207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(correlation-id): fix flaky test

- .github/workflows/label-schema.yml
- .github/workflows/release.yml
Kong/action-slack-notify to v2_node20
Kong/public-shared-actions/security-actions/scan-docker-image to v4.0.1
KAG-6149
> chore(ci): bump action-slack-notify and public-shared-actions

- spec/02-integration/09-hybrid_mode/12-errors_spec.lua
> tests(clustering): errors spec only for sync.v1

- changelog/unreleased/kong/fix-ai-azure-incorrect-path-overriding.yml
- kong/llm/drivers/azure.lua
- kong/llm/drivers/shared.lua
- spec/03-plugins/38-ai-proxy/05-azure_integration_spec.lua
There was a bug found, where the Azure provider stopped parsing 'custom upstream path' overrides since Kong 3.9.0.
Every request would 404 due to incorrect parsing.
I've added a parser / config options test to prevent this from happening again!
FTI-6403
AG-191
> fix(ai): (FTI-6403) Fixed error with Azure path override formatting

- kong/clustering/services/sync/rpc.lua
- spec/02-integration/18-hybrid_rpc/09-notify_new_version_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-notify-new-version-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-notify-new-version-test/schema.lua
> tests(clustering/rpc): add cases for sync.v2.notify_new_version

- kong/clustering/control_plane.lua
- kong/clustering/services/sync/rpc.lua
> refactor(clustering): use tools.table.EMPTY to avoid overhead

- kong/clustering/rpc/concentrator.lua
> feat(clustering/rpc): rpc batching on concentrator

- changelog/unreleased/kong/fix-upstream-keep-alive-pool-name.yml
- kong/init.lua
- spec/02-integration/05-proxy/25-upstream_keepalive_spec.lua
Fix https://konghq.atlassian.net/browse/FTI-6380
> fix(core): add `tls_verify`, `tls_verify_depth`, `ca_certificates` of a service into the upstream keepalive pool name

- changelog/unreleased/kong/bump-libexpat-to-2_6_4.yml
> docs(changelog): add a changelog for bumping libexpat

- changelog/unreleased/kong/bump-libexpat-to-2_6_4.yml
> chore(changelog): update changelog for bumping libexpat

- changelog/unreleased/kong/bump-libexpat-to-2_6_4.yml
KAG-6222
(cherry picked from commit 0add6a509f0c1c6b1bc687d80d82b999ad906647)
> [backport to release/3.9.x] chore(changelog): add a changelog for bumping libexpat (#14207)

- kong/clustering/services/sync/rpc.lua
> feat(clustering/rpc): update dp status after syncing

- kong/clustering/services/sync/rpc.lua
- spec/02-integration/18-hybrid_rpc/09-notify_new_version_spec.lua
KAG-6205
See: https://github.com/Kong/kong/pull/14174#discussion_r1919640857
> fix(clustering/rpc): warning log level for sync retry failing

- kong/clustering/rpc/socket.lua
KAG-5934
In #14040 we changed the timeout from `5` to `0.5`, but that is not necessary and may cause checking queue frequently,
so this PR revert this small change.
> refactor(clustering/rpc): wait 5 seconds for  rpc queue

- kong/clustering/services/sync/rpc.lua
> refactor(clustering/rpc): reshape do_sync

- bin/busted
- kong-3.10.0-0.rockspec
- kong/clustering/services/sync/rpc.lua
- kong/clustering/services/sync/validate.lua
- kong/db/declarative/init.lua
- kong/db/schema/others/declarative_config.lua
- kong/init.lua
- spec/02-integration/09-hybrid_mode/09-node-id-persistence_spec.lua
- spec/02-integration/18-hybrid_rpc/06-validate_deltas_spec.lua
- spec/fixtures/dc_blueprints.lua
- spec/internal/db.lua
1. validate entity schema
* call `kong.db[entity].validate(entity)` over all the entities from deltas
2. validate entity's references (foreign references)
* re-implemented logic: traverse delta -> try to find delta's foreign entity in config & LMDB
* TODO: decouple this logic completely from declarative config logic: https://konghq.atlassian.net/browse/KAG-6231
3. TODO: report error if deleting delta operation could not find its associated entity in LMDB and deltas: https://konghq.atlassian.net/browse/KAG-6238
Fix KAG-5897
> feat(clustering/sync): validate deltas when syncing

- spec/fixtures/custom_plugins/kong/plugins/rpc-notify-new-version-test/handler.lua
The original constructed workspace lack required fields, this commit adds them to bypass DP's delta validation.
Fix [KAG-5897](https://konghq.atlassian.net/browse/KAG-5897)
[KAG-5897]: https://konghq.atlassian.net/browse/KAG-5897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(clustering/rpc): added required field for mocked workspace to byass validation

- build/luarocks/templates/luarocks_make.sh
- build/luarocks/templates/luarocks_target.sh
Fix a typo in the luarocks script which will cause the loss of stderr output.
> chore(ci): fix luarocks script redirect typo

- changelog/unreleased/kong/fix-admin-api-route-path-response-error.yml
- kong/runloop/plugin_servers/process.lua
Problem: There are  some runtime data like `proc` stored in `kong.configuration.pluginservers`, which is cdata type and could not be encoded by cjson. Thus when fetching the admin api "/", the response body encoding of configuration will fail and throws 500 error.
Solution: Separate runtime data from configuration, store runtime info like `proc` inside the plugin servers module, not global configuration.
Fix https://konghq.atlassian.net/browse/KAG-6088
> fix(core): separate plugin server runtime data from kong configuration

- changelog/unreleased/kong/add-cp-connectivity-metric-prometheus.yml
- kong/clustering/data_plane.lua
- kong/plugins/prometheus/exporter.lua
- spec/03-plugins/26-prometheus/04-status_api_spec.lua
Add a new Prometheus gauge metric `control_plane_connected`. Similar to `datastore_reachable` gauge, 0 means the connection is not healthy; 1 means that the connection is healthy. We mark the connection as unhealthy under the following circumstances:
* Failure while establihing a websocket connection
* Failure while sending basic information to controlplane
* Failure while sending ping to controlplane
* Failure while receiving a packet from the websocket connection
This is helpful for users running a signficant number of gateways to be alerted about potential issues any gateway(s) may be facing while talking to the controlplane.
> feat(prometheus): expose controlplane connectivity state as a gauge

- build/openresty/patches/LuaJIT-2.1-20240815_03-revert-reflect-override-of-ljlibd.patch
This is a backport/cherry-pick of one LuaJIT revert commit patch that was already added to EE when bumping OpenResty to 1.27.1.1, as seen here: https://github.com/Kong/kong-ee/pull/11243
Thus no need to cherry-pick this to EE nor any changelog needed.
> chore(patches): backport revert override of ljlibd

- kong/clustering/services/sync/rpc.lua
> fix(clustering/sync): fix default workspace check

- kong/db/schema/entities/key_sets.lua
- kong/db/schema/entities/keys.lua
It's Key Sets in Konnect we should match that standard in description text to avoid confusion. 
https://github.com/Kong/developer.konghq.com/issues/258
> Docs: change key-sets to Key Sets to match Konnect in entity description text

- .github/actions/build-wasm-test-filters/action.yml
* switch to [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) for installing the rust toolchain (actions-rs is dead/unmaintained)
* update `actions/cache/save` v3 -> v4
* clean up some shell glue code
* restrict cache save/restore paths \*
\* The action was previously caching the entire rust toolchain, which used up 60-70MB of our cache quota per cache entry. It's been updated to only cache `*.wasm` files, so now the cache size is <1MB.
KAG-6289
> chore(ci): update build-wasm-test-filters action

- changelog/unreleased/kong/prometheus-upstream-metrics-toggle.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/prometheus/exporter.lua
- kong/plugins/prometheus/schema.lua
- kong/plugins/prometheus/wasmx.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/26-prometheus/09-wasmx_spec.lua
Adds a toggle for wasm metrics export to the prometheus plugin.
KAG-5904
> fix(prometheus): add a toggle switch for wasm metrics export

- spec/02-integration/02-cmd/02-start_stop_spec.lua
- spec/02-integration/05-proxy/02-router_spec.lua
- spec/kong_tests.conf
`nginx_worker_processes` is the standard configuration in our template, and it has an alias `nginx_main_worker_processes`. So, no matter which one we configure, both will work. However, if we set these options at the same time, the one that takes effect will be `nginx_main_worker_processes`.
Since our test suite uses [`nginx_main_worker_processes`](https://github.com/Kong/kong/blob/7a505eaa6870a5b9e7da914a32464635691f1038/spec/kong_tests.conf#L35), that means using `nginx_worker_processes` in the test cases is not working. 
We have a bunch of test files that are using `nginx_worker_processes` instead of the `nginx_main_worker_processes` alias, and making one small change to the kong_test.conf file saves us the trouble of updating all of them (including EE).
> tests(*): make nginx_worker_processes to take effect properly

- kong/clustering/services/sync/validate.lua
- spec/01-unit/19-hybrid/04-validate_deltas_spec.lua
Try to align with sync v1 logic, v1 will ignore required fields error because
```
dc:validate(input)
....
-> field_schema:process_auto_fields(value, "insert")
-> route:validate
```
So when recursively calling the validate() function, it will call process_auto_fields before validating a specific entity inside for sync v1.
Fix KAG-6249
> fix(clustering/sync): insert default values to delta entities before validation

- kong/llm/plugin/shared-filters/normalize-response-header.lua
AG-204
https://github.com/Kong/kong-ee/pull/11255
> fix(llm): fix gzip handling when using multiple AI plugins

- kong/clustering/rpc/socket.lua
KAG-6336
Currently it is a temporary solution, we may work on it later.
> fix(clustering/rpc): add random for timer‘s name

- kong/db/dao/init.lua
> style(daos): rename function parameter to keep consistency

- changelog/unreleased/kong/fix-response-ratelimiting-upstream-headers.yml
- kong/plugins/response-ratelimiting/access.lua
- spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
`response-ratelimiting` plugin should send usage headers to upstream server.
But in Kong 3.8, there are no usage headers such as `X-RateLimit-Remaining-Videos: 10` for upstream requests.
In this change, it coming back usage headers for upstream.
- It seems to be already there are tests for this feature but are there passing? https://github.com/Kong/kong/blob/master/spec/03-plugins/24-response-rate-limiting/04-access_spec.lua#L505
Fix #13682
> fix(response-ratelimiting): fix missing usage headers for upstream

- changelog/unreleased/kong/fix-ai-upstream-url-trailing-empty.yml
- kong/llm/drivers/anthropic.lua
- kong/llm/drivers/azure.lua
- kong/llm/drivers/bedrock.lua
- kong/llm/drivers/cohere.lua
- kong/llm/drivers/gemini.lua
- kong/llm/drivers/openai.lua
>  fix(llm): fix error when upstream_url missing trailing slash

- kong/clustering/services/sync/hooks.lua
> fix(clustering/rpc): do not log disconnected node

- kong/tools/sandbox/require/handler.lua
This PR adds more modules that are allowed within sandboxed handlers (custom plugins).
[KAG-6255](https://konghq.atlassian.net/browse/KAG-6255)
[KAG-6255]: https://konghq.atlassian.net/browse/KAG-6255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(sandbox): allow more sub-modules with sandboxed handlers

- changelog/unreleased/kong/fix-response-ratelimiting-upstream-headers.yml
- spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
- spec/fixtures/1.2_custom_nginx.template
- spec/fixtures/template_inject/nginx_kong_test_custom_inject_http.lua
The response rate limiting plugin's tests spec includes multiple flaky test cases, and it's not even enabled in CI(with the `#flaky` tag) which means some test cases are not correct but not been aware of.
The purpose of this PR is to make the flaky tests stable, and enable them in CI.
Fix https://konghq.atlassian.net/browse/KAG-5447
> chore(tests): stabilize flaky tests of response rate limiting plugin

- kong/clustering/rpc/socket.lua
- kong/clustering/services/sync/rpc.lua
- kong/clustering/services/sync/validate.lua
- kong/constants.lua
- kong/db/errors.lua
- spec/01-unit/19-hybrid/04-validate_deltas_spec.lua
- spec/02-integration/18-hybrid_rpc/10-validate_deltas_spec.lua
1. flatten validation error for sync deltas
2. call RPC notify to API `kong.sync.v2.notify_validation_error` (spec: https://github.com/Kong/openrpc_specfiles/pull/18/)
3. fix bug that CP will crash if DP calls a non-existent RPC notify: KAG-6381
Fix KAG-6351 KAG-5898 KAG-6381
> feat(clustering/sync): flatten and report validation error

- kong/clustering/rpc/manager.lua
KAG-5891
Precondition for [KAG-6178](https://konghq.atlassian.net/browse/KAG-6178)
[KAG-6178]: https://konghq.atlassian.net/browse/KAG-6178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(clustering/rpc): correct rpc disconnected event on dp side

- kong/tools/string.lua
In https://github.com/Kong/kong/pull/13168 I made this already faster, but this time I managed to make it a way faster, main reason being:
- not needing to count length of input
- not needing to use for loop :-)
Leading to potentially better JIT compilation results as well.
The code in my opinion is also easier to read and understand.
I get  `3492 ms` reduced to (with this PR) `149 ms` execution time in microbenchmark.
KAG-6354
> perf(tools/string): a way faster strip function

- bin/busted
- bin/kong
- kong/cache/init.lua
- kong/cluster_events/init.lua
- kong/clustering/control_plane.lua
- kong/clustering/data_plane.lua
- kong/clustering/rpc/manager.lua
- kong/clustering/rpc/socket.lua
- kong/clustering/services/sync/hooks.lua
- kong/clustering/services/sync/rpc.lua
- kong/db/strategies/postgres/connector.lua
- kong/dns/client.lua
- kong/llm/plugin/base.lua
- kong/pdk/log.lua
- kong/tools/queue.lua
- spec/01-unit/27-queue_spec.lua
- spec/02-integration/02-cmd/16-verbose_spec.lua
The recurring timers and other things were causing excessive logging.
KAG-5769
This is a cherry-pick from:
https://github.com/Kong/kong-ee/pull/10652
https://github.com/Kong/kong-ee/pull/11393
Mentioned in #14249, see: https://github.com/Kong/kong/issues/14249#issuecomment-2653622776
> chore(logging): reduce excessive log flooding on debug logs

- changelog/unreleased/kong/fix-pdk-clear-query-arg-space-encoding.yml
- kong/pdk/service/request.lua
- t/01-pdk/06-service-request/14-clear_query_arg.t
The `+` encoding is more correct (in query strings), but it seems to cause some problems with some users. As a short-term solution I propose that we just convert `+` to `%20`. This is more in-lines what Nginx and OpenResty seems to be doing as well.
KAG-6324
Fix FTI-6475
> fix(pdk): make kong.service.request.clear_query_arg encode spaces as %20 instead of +

- spec/02-integration/20-wasm/06-clustering_spec.lua
> tests(clustering/wasm): enable rpc sync tests for wasm partially

- kong/clustering/rpc/socket.lua
- spec/02-integration/18-hybrid_rpc/07-notification_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-notification-test/handler.lua
> tests(clustering/rpc): check not existed method for notification

- changelog/unreleased/kong/feat-cors-skip-return-acao-when-no-origin-in-request.yml
- kong/clustering/compat/removed_fields.lua
- kong/plugins/cors/handler.lua
- kong/plugins/cors/schema.lua
- spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
- spec/03-plugins/13-cors/01-access_spec.lua
> feat(cors): add an option to skip return ACAO  when no origin in request

- kong/clustering/services/sync/init.lua
> refactor(clustering/rpc): rpc sync should start without delay

- .github/workflows/labeler-v2.yml
skip labeler on fork PRs
[KAG-6397](https://konghq.atlassian.net/browse/KAG-6397)
[KAG-6397]: https://konghq.atlassian.net/browse/KAG-6397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci(*): skip labeler on fork PRs

- kong/db/strategies/postgres/init.lua
Precondition of [KAG-6296](https://konghq.atlassian.net/browse/KAG-6296)
[KAG-6296]: https://konghq.atlassian.net/browse/KAG-6296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(db): add missing select statement for export

- kong/clustering/services/sync/validate.lua
- spec/01-unit/19-hybrid/04-validate_deltas_spec.lua
Add support to strict ws_id validation to sync.v2.
Fix KAG-5760
> feat(clustering/sync): add strict validation for delta workspace id

- spec/02-integration/02-cmd/02-start_stop_spec.lua
Cherry-picked from https://github.com/Kong/kong-ee/pull/11446
_[KAG-6433]_
[KAG-6433]: https://konghq.atlassian.net/browse/KAG-6433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(cmd): fix flaky test

- spec/02-integration/07-sdk/03-cluster_spec.lua
- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
- spec/02-integration/09-hybrid_mode/03-pki_spec.lua
- spec/02-integration/09-hybrid_mode/05-ocsp_spec.lua
- spec/02-integration/09-hybrid_mode/08-lazy_export_spec.lua
- spec/02-integration/09-hybrid_mode/10-forward-proxy_spec.lua
- spec/02-integration/09-hybrid_mode/13-deprecations_spec.lua
- spec/03-plugins/09-key-auth/04-hybrid_mode_spec.lua
- spec/03-plugins/11-correlation-id/02-schema_spec.lua
Manually cherry-pick from https://github.com/Kong/kong-ee/pull/11388
Additionally, test from https://github.com/Kong/kong-ee/pull/11418 is cherry-picked as well.
Fix [KAG-6393](https://konghq.atlassian.net/browse/KAG-6393)
[KAG-6393]: https://konghq.atlassian.net/browse/KAG-6393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(clustering/rpc): wait dp full sync ends for rpc sync

- spec/internal/misc.lua
> chore(spec): generate_keys supports EC key

- kong/clustering/services/sync/strategies/postgres.lua
- spec/01-unit/19-hybrid/05-validate-versions_spec.lua
Currently, the `is_valid_version` accepts invalid versions like `v02_xxxxxxxx`, which not only isn't a valid hex number but also has an unexpected string length.
We should validate the version string more strictly.
_[KAG-6452]_
[KAG-6452]: https://konghq.atlassian.net/browse/KAG-6452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(clustering/rpc): validate version string more strictly

- bin/busted
This refactors our busted CLI wrapper to minimize work that does not need to be performed on launch/re-launch.
Instead of unconditionally creating temporary certs on disk and loading the emmylua debugger, these setup tasks are guarded by env var checks.
KAG-6465
> chore(test): don't duplicate work when launching busted

- changelog/unreleased/kong/fix-target-deletion.yml
- kong/runloop/balancer/targets.lua
- spec/02-integration/05-proxy/05-dns_spec.lua
For the deployment that multiple kong instances in traditional mode share the same database, when there are updates in targets via admin API happening on one of the instances, the related targets can not be removed from the DNS query queue via cluster events notification broadcasted by the initial instance.
This issue is that the payload in the cluster event broadcasted from other instances only contains the upstream ID attached to the target. However, the handler that is eventually supposed to consume the payload expects a target entity.
The issue is not caused by an incorrect payload in the cluster event, because the payload of a cluster event is transmitted via the database. Therefore, passing a smaller and simpler payload is a wise choice, whereas a complete target entity obviously …
> fix(targets): targets can't be removed from dns query queue

- changelog/unreleased/kong/admin-gui-csp-header.yml
- kong.conf.default
- kong/cmd/utils/prefix_handler.lua
- kong/conf_loader/constants.lua
- kong/templates/kong_defaults.lua
- kong/templates/nginx_kong_gui_include.lua
- spec/01-unit/03-conf_loader_spec.lua
- spec/01-unit/04-prefix_handler_spec.lua
This pull request adds `Content-Security-Policy` and `Referrer-Policy` headers while serving Admin GUI requests.
Cherry-picking PR in EE was created manually. Please refer to the linked PR.
Since the `Content-Security-Policy` has caused some issues with the Kong Manager before, we introduce a new configuration parameter `admin_gui_csp_header` which defaults to `"off"` to control the availability of this header. Users can opt in manually.
As for the `Referrer-Policy` header, we will serve `'strict-origin-when-cross-origin'` which seems to be the default value today:
> Note: This is the default policy if no policy is specified, or if the provided value is invalid (see spec revision [November 2020](https://github.com/whatwg/fetch/pull/1066)). Previously the default was …
> fix(templates): add missing security headers for Admin GUI

- changelog/unreleased/kong/perf-trace-ID-size-lookup.yml
- kong/observability/tracing/propagation/injectors/_base.lua
Replace table_contains with a more efficient lookup table for trace ID sizes, improving performance of trace ID size lookup.
> perf(tracing): improving performance of trace ID size lookup

- kong/clustering/services/sync/rpc.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-get-delta-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-notify-new-version-test/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/rpc-validation-test/handler.lua
KAG-6504
Related PR: https://github.com/Kong/kong-ee/pull/11373
I think that this PR dose not need to cherry pick to EE.
> refactor(clustering/rpc): rename field `wipe` to `full_sync` and other code clean

- changelog/unreleased/kong/fix-duplicate-content-type.yml
- kong/api/api_helpers.lua
This is the bug reported in issue #14187.
If we send a request like this:
```
POST / HTTP/1.1
Accept: */*
Host: 127.0.0.0
Content-Type: application/x-www-form-urlencoded
Content-Type: application/x-www-form-urlencoded
```
then the `content_type` variable will be a table, whereas if the request is like this:
```
POST / HTTP/1.1
Accept: */*
Host: 127.0.0.0
Content-Type: application/x-www-form-urlencoded; application/json
```
the `content_type` will be a string `application/x-www-form-urlencoded; application/json`.
As described by RFC 7230: https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2
> A sender MUST NOT generate multiple header fields with the same field
name in a message unless either the entire field value for that
header field is defined as a comma-separated list [i.e., …
> fix(admin): fix error caused by duplicate Content-Type

- build/nfpm/repositories.bzl
This reverts commit 8eaeef1200deafa263dcc2f1b5d2e4fd1e09e033.
Version `2.41.2` of nfpm was creating an RPM package incompatible with our signing process/the resigning process of Cloudsmith, as evidenced by [the nightlies failing](https://github.com/Kong/kong/actions/runs/13533594768/job/37821630776) (both here and for EE).
This is a reminder that the PR-based github actions runs don't include our full matrix of platforms we support. So changes like this to the packaging or to platforms other than Ubuntu need to have a full matrix run tested. Or at the very least, nightlies need to be looked at.
- [na] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. …
> Revert "chore(deps): bump nfpm from 2.37.1 to 2.41.2"

- changelog/unreleased/kong/fix-new-dns-client-timeout.yml
- kong/dns/client.lua
- kong/dns/utils.lua
- spec/01-unit/30-new-dns-client/01-utils_spec.lua
- spec/01-unit/30-new-dns-client/02-old_client_spec.lua
Original Kong dns client was treating resolv.conf timeout or RES_OPTIONS timeout as being in milliseconds when the reality per RFC is they are in seconds, so anyone using Kong who custom sets their DNS timeouts via those methods are getting 2ms of DNS time allowed vs 2000ms expected(2 second configured).
See references here:
https://github.com/Kong/kong/issues/14249#issuecomment-2658565525
and
https://github.com/Kong/kong/issues/14249#issuecomment-2658607207
This fix refers to original fix https://github.com/Kong/kong/pull/14313
Co-authored-by: @jeremyjpj0916
Fix KAG-6495
Fix https://github.com/Kong/kong/issues/14249
Fix https://github.com/Kong/kong/issues/14233
> fix(dns): new DNS client did not correctly handle timeout option in resolv.conf

- kong/pdk/response.lua
- t/01-pdk/08-response/02-get_header.t
This PR is an amendment of https://github.com/Kong/kong/pull/13981.
I found that in openresty, they have special handling for some headers like "connection", "transfer-encoding" in `ngx.resp.get_headers` (see https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_headers.c#L521-L538).
However, `ngx.header.HEADER` doesn't include these special handling, which means fetching single header like "connection" may get `nil` but `get_headers()["connection"]` will get a not `nil` value.
So we need to revert the change in the `response.get_header` PDK to avoid this potential issue.
Fix https://konghq.atlassian.net/browse/KAG-5567
> feat(pdk): revert response.get_header change to avoid behavior change

- spec/02-integration/05-proxy/07-upstream_timeouts_spec.lua
Cherry-picked from https://github.com/Kong/kong-ee/pull/11325
_[KAG-6337]_
[KAG-6337]: https://konghq.atlassian.net/browse/KAG-6337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tests(upstream_timeout): enable hybrid and rpc sync tests

- build/openresty/patches/nginx-1.27.1_13-upstream-latency-metrics.patch
this commit patches the ngx_http_upstream_module to add the following variables each containing timestamps with microseconds precision
* upstream_start_timestamp_us: transactions with the upstream server started
* upstream_connect_timestamp_us: connection was established with the upstream server
* upstream_request_timestamp_us: request was sent to the upstream server
* upstream_header_timestamp_us: response headers received from the upstream server
* upstream_response_timestamp_us: response body received from the upstream server
Fix KAG-6234
> feat(nginx): patch - added upstream latency metrics

- .github/workflows/changelog-requirement.yml
Use kong changed-files github actions as the original upstream has been compromised and shut down.
> fix: use kong changed-files action

- kong/clustering/services/sync/rpc.lua
- kong/db/schema/others/declarative_config.lua
cherry-pick to Kong-ce from EE pr: https://github.com/Kong/kong-ee/pull/11547
We need to follow the RPC spec to handle ws_id.
1. set entity/delta ws_id correctly when initially inserting delta to Database
2. correct get detal key logic for coalesing
KAG-6432
---------
> fix(clustering/rpc): process ws_id correctly (#11547)

- .ci/ast-grep/README.md
- .ci/ast-grep/rules/assert-eventually-terminated.yml
- .ci/ast-grep/rules/helpers-outside-of-setup.yml
- .ci/ast-grep/rules/ngx-log-string-concat.yml
- .ci/ast-grep/tests/__snapshots__/assert-eventually-terminated-snapshot.yml
- .ci/ast-grep/tests/__snapshots__/helpers-outside-of-setup-snapshot.yml
- .ci/ast-grep/tests/__snapshots__/ngx-log-string-concat-snapshot.yml
- .ci/ast-grep/tests/assert-eventually-terminated-test.yml
- .ci/ast-grep/tests/helpers-outside-of-setup-test.yml
- .ci/ast-grep/tests/ngx-log-string-concat-test.yml
- .github/workflows/ast-grep.yml
- kong/clustering/rpc/manager.lua
- kong/llm/drivers/gemini.lua
- kong/llm/drivers/huggingface.lua
- kong/resty/dns/client.lua
- kong/resty/mlcache/init.lua
- sgconfig.yml
This is an experiment in using [ast-grep](https://github.com/ast-grep/ast-grep) to craft our own semantic lint rules.
`ast-grep` is a tool for querying source code in a (relatively) language-agnostic manner. It allows us to write lint rules that target patterns that are specific to our codebase and therefore not covered by tools like `luacheck`.
In practice I expect this to be used mostly for lua files, but in theory we could use it to write lints for [all sorts of languages/filetypes](https://ast-grep.github.io/reference/languages.html).
Everything here runs in the new `ast-grep.yml` workflow, which is triggered on a PR event with changes to any `ast-grep`-related files (rules, config, etc) or any `*.lua` source code files.
Errors and warnings behave as expected and create annotations on …
> chore(lint): add ast-grep lint rules and CI workflow

- kong/pdk/tracing.lua
update tracing pdk docs to remove the (currently not supported) admin_api phase.
[KAG-6485](https://konghq.atlassian.net/browse/KAG-6485)
closes https://github.com/Kong/kong/discussions/14288
[KAG-6485]: https://konghq.atlassian.net/browse/KAG-6485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(pdk): tracing

- .github/workflows/release.yml
KAG-6739
(cherry picked from commit b991c85953ebb345230043bc504d5ce4f3c34437)
> chore(ci): fix version pattern for Docker tag generation

- spec/02-integration/04-admin_api/21-admin-api-keys_spec.lua
- spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua
- spec/02-integration/05-proxy/10-balancer/07-latency_spec.lua
- spec/02-integration/08-status_api/05-dns_client_spec.lua
- spec/02-integration/09-hybrid_mode/01-sync_spec.lua
- spec/03-plugins/23-rate-limiting/04-access_spec.lua
- spec/03-plugins/26-prometheus/04-status_api_spec.lua
- spec/03-plugins/39-ai-request-transformer/01-transformer_spec.lua
This is a follow-up to d1a8e41ab7923605510c8ca1ebc6692a65a90bd8 that fixes the remainder of the files with warnings.
```
$ ast-grep scan | wc -l
0
```
> chore(lint): fix remaining helpers-outside-of-setup warnings

- README.md
Previous, the README.md Build & Test status will be red as long as the latest build fails no matter it's from our maintenance branch or a development branch (PR's branch), which is not a good way to show the repository's status. This PR changed it to show the latest commit's workflow run result from master.
> docs(readme): display master latest commit's Build & Test workflow status

- .github/labeler.yml
> ci: add pgvector folder to CI labeler

- changelog/unreleased/kong/fix-jwt-www-authenticate-header-delimiter.yml
- kong/plugins/jwt/handler.lua
- spec/03-plugins/16-jwt/03-access_spec.lua
Fix issue https://github.com/Kong/kong/issues/14429 where authentication plugins were using spaces instead of commas to separate parameters in the WWW-Authenticate header. According to RFC 7235 (HTTP Authentication) ([Section 4.1](https://datatracker.ietf.org/doc/html/rfc7235#section-4.1)), the parameters should be comma-delimited.
-  #14436 
Fix #14429
> fix(jwt):correct  header delimiter to use comma

- .github/workflows/copyright-check.yml
- .github/workflows/license-notice-check.yml
- kong/plugins/ai-prompt-decorator/filters/decorate-prompt.lua
- kong/plugins/ai-prompt-guard/filters/guard-prompt.lua
- kong/plugins/ai-prompt-template/filters/render-prompt-template.lua
- kong/plugins/ai-request-transformer/filters/transform-request.lua
- kong/plugins/ai-response-transformer/filters/transform-response.lua
- kong/tls/plugins/certificate.lua
- kong/tls/plugins/sni_filter.lua
- spec/01-unit/01-db/11-declarative_lmdb_spec.lua
- spec/03-plugins/03-http-log/05-old-plugin-compatibility_spec.lua
- spec/03-plugins/25-oauth2/05-kdf_spec.lua
- spec/fixtures/custom_plugins/kong/plugins/preserve-nulls/handler.lua
- spec/fixtures/custom_plugins/kong/plugins/preserve-nulls/schema.lua
KAG-6949
(cherry picked from commit 8ed78ce1c801064c9cbc6b997df16fe59b3aa16d)
> [backport to release/3.9.x] chore(ci): fix the name of the workflow that checks for copyright (#14450)

- changelog/unreleased/kong/fix-downgrade-routes-plugins-rebuilding-log-level.yml
- kong/runloop/handler.lua
> fix(core): downgrade log level for routes rebuilding (#12340)

- kong/clustering/control_plane.lua
- kong/clustering/rpc/manager.lua
- spec/02-integration/18-hybrid_rpc/04-concentrator_spec.lua
> fix(clustering/rpc): rpc concentrator may not work with sync v1

- kong/reports.lua
- spec/01-unit/11-reports_spec.lua
Report the state of new_dns_client in anonymous reports.
[KAG-7019]
[KAG-7019]: https://konghq.atlassian.net/browse/KAG-7019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(anonymous_reports): report the state of new_dns_client

- build/BUILD.bazel
- build/luarocks/BUILD.luarocks.bazel
- build/luarocks/lua/BUILD.bazel
- build/luarocks/lua/BUILD.lua.bazel
- build/luarocks/lua/lua_repositories.bzl
- build/luarocks/lua/patches/lua-cross.patch
- build/luarocks/luarocks_repositories.bzl
- build/luarocks/templates/luarocks_exec.sh
- build/luarocks/templates/luarocks_target.sh
- build/templates/venv-commons
- scripts/upgrade-tests/luarocks-system-lua
- scripts/upgrade-tests/test-upgrade-path.sh
> fix(ci): use PUC-Rio Lua to invoke luarocks

- scripts/make-release
Update the `scripts/make-release version_bump` script's commit message.
KAG-7109
> chore(scripts): update the version_bump script's commit message

- kong-3.9.2-0.rockspec
- kong/meta.lua
Bump version to 3.9.2 as part of the 3.9.1 patch release.
KAG-7109
> chore(release): bump version to 3.9.2

- .github/workflows/release.yml
#14572 
KAG-7040
(cherry picked from commit 36db98046b05cfe48b14d3ae00a3c5601bd105a8)
> [backport to release/3.9.x] chore(ci): enable dockerhub organization access token (OAT) (#14572)

- build/luarocks/lua/BUILD.lua.bazel
Lua has a default `AR= ar rcu` in its makefile, overriding it with `AR=/usr/bin/ar` will cause the build fail on macOS due to missing required arguments
The `/usr/bin` is in the `PATH` by default on macOS, so it's okay to remove this override to fix the issue
JIRA: KM-1362
> fix(build): use default AR args for the Lua package on macOS

- COPYRIGHT
Forward merge 3.9.1 copyright update.
> docs(COPYRIGHT): update copyright for 3.9.1

- scripts/upgrade-tests/test-upgrade-path.sh
> fix(ci): fix upgrade-test failure caused by renamed rockspec file

- kong/plugins/cors/schema.lua
Added a note to clarify the behavior of the cors plugin when the origins element is absent or empty, as requested [here](https://github.com/Kong/docs.konghq.com/issues/7875).
Fix https://github.com/Kong/docs.konghq.com/issues/7875
> docs(cors): Clarify behavior with no origins specified

- build/luarocks/lua/BUILD.lua.bazel
Lua has a default `AR= ar rcu` in its makefile, overriding it with `AR=/usr/bin/ar` will cause the build fail on macOS due to missing required arguments
The `/usr/bin` is in the `PATH` by default on macOS, so it's okay to remove this override to fix the issue
JIRA: KM-1362
(cherry picked from commit 7c095c07ccd70ed21dcd6914ad5a61d9de002504)
#14648
> fix(build): use default AR args for the Lua package on macOS (#14648)

- DEVELOPER.md
This patch fix a dead link in DEVELOPER.md 
more: 
This test script drop in pr: #12180 and use est_suites.json instead.
but the dev doc seems not follow, the patch follow the change and 
fix the dead link. 
> docs(DEVELOPER): fix a dead link in dev md
