Kong/kong

kong/cli/db.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/factory.lua
kong/dao/cassandra/plugins_configurations.lua
kong/dao/cassandra/ratelimiting_metrics.lua
kong/kong.lua
spec/integration/cli/start_spec.lua
spec/spec_helpers.lua
spec/unit/dao/cassandra_spec.lua

This PR started as an improvement for developing #147, but it's also useful to fix #11. It's a small refactor, to avoid having to call `:prepare` every time a DAO is instantiated.
- The DAO factory does not need to call `:prepare` at startup anymore. Statements will be dynamically prepared if they were not already. This is a step towards fixing #11, and having a more usable DAO
- split cassandra "core collections" and "plugins collections" tests
- `:prepare` is still called in `kong.lua` when Kong starts, as a simple way of checking all statements are valid. `:prepare` might disappear in the future.
- An improvement will be to prepare the Rate Limiting plugin statements so they are prepared **before** being inserted in batch statements. For now, they are batched as plain strings.

[refactor] dao prepare

---

database/migrations/cassandra/2015-01-12-175310_init_schema.lua
database/migrations/cassandra/2015-04-24-154530_plugins.lua
kong/cli/migrations.lua

It's the least we can do to keep the core and the plugins tables
separate before releasing 0.2.0.

Split plugins tables from core tables

---

kong/resolver/access.lua
kong/resolver/handler.lua
spec/integration/proxy/resolver_spec.lua

- 'API not found with host %s' is the new error message, allowing the
user to better understand what is happening
- Minor changes to the resolver plugin: no need to strip the header +
tests

[fix] friendlier 'API not found' error message

---

.travis/setup_cassandra.sh
kong/dao/cassandra/apis.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/basicauth_credentials.lua
kong/dao/cassandra/consumers.lua
kong/dao/cassandra/factory.lua
kong/dao/cassandra/keyauth_credentials.lua
kong/dao/cassandra/plugins_configurations.lua
kong/dao/error.lua

If Cassandra returns an unprepared error, the DAO will re-prepare it and try the query again. This fixes #11, and handles the case where Cassandra would go down, and then up again while Kong is still running.
Other changes:
- docs: base_dao and the factory have been given a better documentation.
- refactor:
- `kong_query` is now the prefered term for _queries elements.
- `params` becomes `args_keys` and `values` `args` for consistance with the driver.
- The `_execute` method was renamed to `_execute_kong_query` and broken into smaller chunks.
- Batch statements now need to use the raw `_execute` method (the new one, not the one renamed to `_execute_kong_query`.
- Cassandra errors now also have the error code.

[feature] support unprepared statement errors. fix #11

---

kong/dao/cassandra/base_dao.lua

DAO sockets now take advantage of the connection pool and if they are
coming from it (meaning they've been used before), they don't set their
keyspace anymore.

fix: reused DAO sockets don't set the keyspace. fix #170

---

kong-0.2.1-1.rockspec
kong/cli/migrations.lua
kong/cli/utils/signal.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/factory.lua
kong/dao/cassandra/migrations.lua
kong/tools/migrations.lua
spec/unit/migrations_spec.lua

The purpose on the factory would be to only gather DAOs rather than also
be responsible for executing queries and migrations like previously.
This is a step towards this, which also removes some duplicated code to
open cassandra sessions and execute queries, since the migrations now
use the BaseDAO

[refactor] separate migrations from the Factory

---

kong/dao/cassandra/apis.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/consumers.lua
kong/dao/cassandra/plugins_configurations.lua
kong/tools/faker.lua
spec/integration/admin_api/admin_api_spec.lua
spec/unit/dao/cassandra_spec.lua

This proposes a way to delete all `plugins_configurations` related to `Consumers` or `APIs` when deleting one of the two later.
`:delete()` is simply overridden to iterate over all related `plugins_configuration` and delete them one by one.
Caveats:
- I am very unhappy with how painful it is to use one DAO inside another
DAO. To avoid what would appear to be a cycling reference I rather opted
for instanciating a new DAO inside of the `delete` method.
- It is painful to perform a paginated query through the base_dao.
- It is even more painful to perform a find_by_keys query as a paginated
query.

[feature] cascade delete of plugins_configurations. fix #107

---

.travis.yml
.travis/setup_dnsmasq.sh
kong.yml
kong/cli/quit.lua
kong/cli/reload.lua
kong/cli/restart.lua
kong/cli/stop.lua
kong/cli/utils/signal.lua
kong/constants.lua
kong/tools/faker.lua
kong/tools/io.lua
spec/integration/proxy/dns_spec.lua
spec/integration/proxy/realip_spec.lua
spec/spec_helpers.lua
spec/unit/statics_spec.lua
spec/unit/tools/faker_spec.lua
spec/unit/tools/io_spec.lua
spec/unit/tools/syslog_spec.lua

This pull request fixes issue #182, #163 and #127.
The nginx [`resolver`](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) property specifies which DNS server nginx will use when resolving addresses.
The problem with the resolver is that by design nginx doesn't follow the system settings including the `/etc/hosts` file. In order to have a proper DNS resolution that respects the system DNS settings a new dependency needs to be introduces: [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html). 
dnsmasq is a DNS server that runs locally, can listen on a port (I decided to use `8053` for Kong), and can provide DNS resolution reading both `/etc/hosts` file and `resolv.conf`. It is the same dependency that we use for the official Kong Dockerfile …

dnsmasq integration

---

kong-0.2.1-1.rockspec
kong/dao/cassandra/apis.lua
kong/dao/cassandra/base_dao.lua
kong/dao/schemas.lua
kong/tools/faker.lua
kong/tools/http_client.lua
kong/tools/io.lua
spec/integration/proxy/realip_spec.lua
spec/ngx_stub.lua
spec/plugins/logging_spec.lua
spec/spec_helpers.lua
spec/unit/schemas_spec.lua
spec/unit/statics_spec.lua
spec/unit/tools/faker_spec.lua
spec/unit/tools/http_client_spec.lua

Following the discussion we had in #167, this PR removes the need for patterns everywhere accross Kong. 
- **This PR does not yet remove the installation of perl nor pcre during the package building or the travis-ci setup.** We will do it if we decide to merge this. For the time being, this PR only shows what would change by using patterns.
- There should be no major performance drawback by using patterns instead of Perl regexps as we are not doing heavy text processing **at all** (at least the core and current plugins). And lua patterns can also be nicer than Perl regexps for some use cases.
- As a side effect, regexes are assumed to disappear entirely once those are removed, and the `regex` field in schemas is not supported anymore. One now needs to use `func` and use Lua patterns. …

[refactor] drop pcre regexes for lua patterns

---

kong/constants.lua
kong/kong.lua
kong/resolver/access.lua
kong/tools/responses.lua
spec/integration/proxy/resolver_spec.lua
spec/unit/tools/responses_spec.lua

Proxying can now be triggered via a `Host` or a `X-Host-Override`
header. Multiple values can be given to each of those headers.
Fix #203

[feature] support for alternate Host header

---

kong/dao/cassandra/plugins_configurations.lua
kong/dao/schemas.lua
kong/plugins/keyauth/schema.lua
kong/plugins/request_transformer/schema.lua
kong/plugins/tcplog/schema.lua
kong/plugins/udplog/schema.lua
spec/unit/schemas_spec.lua

A few tweaks in the schema validator and now sub-schemas get auto-vivified if they have a `default` value in it. `required` and custom `func` checks now happen after it.

[feature] default key_names to "apikey"

---

kong/vendor/ssl.lua
spec/plugins/ssl_spec.lua
spec/spec_helpers.lua

- ssl.lua needs to be installed whenever Kong is installed (imagine if ones purges the rocks tree). It is a dependency when installing OpenResty but also when kong is running.
- removed a reset_db call from one of the tests, and removed the method from the spec_helper (migrations make the tests too slow to afford using it)

[chore] add vendor/ssl.lua and remove reset_db()

---

kong.yml
kong/cli/utils/signal.lua
kong/dao/cassandra/factory.lua
kong/plugins/httplog/log.lua
spec/spec_helpers.lua
spec/unit/statics_spec.lua
spec/unit/tools/timestamp_spec.lua

Disabling the `ipv6` in the resolver to handle connections to ipv6 addresses from Lua. Plus some clean up.

Resolver "ipv6" setting

---

kong/dao/cassandra/apis.lua
kong/dao/schemas.lua
kong/tools/utils.lua
spec/integration/admin_api/admin_api_spec.lua

URL Validation

---

kong/dao/schemas_validation.lua
kong/plugins/keyauth/schema.lua
kong/plugins/request_transformer/access.lua
kong/plugins/request_transformer/schema.lua
spec/unit/schemas_spec.lua

- Useful for lists such as `{"apikey", "key"}`
- Can be aliased to a comma-separated string: `"apikey,key"`
In form-encoded mode (JSON would be a real array), the Admin API accepts the following:
```shell
$ curl --url http://localhost:8001/apis/mockbin/plugins \
-d "name=keyauth" \
-d "value.key_names[1]=apikey" \
-d "value.key_names[2]=key"
```
Or:
```shell
$ curl --url http://localhost:8001/apis/mockbin/plugins \
-d "name=keyauth" \
-d "value.key_names=apikey,key"
```

[feature] new `array` type for schema fields

---

.travis.yml
.travis/setup_cassandra.sh
.travis/setup_kong.sh
versions.sh

it has 0 value if it's not used in both travis and the package build anymore. It should have been removed when changing this.

[chore] versions.sh became useless

---

CHANGELOG.md

Push to this branch to update the changelog for the upcoming 0.3.0

[docs][changelog] add latest changes for 0.3.0

---

kong/resolver/access.lua
spec/integration/proxy/resolver_spec.lua

When the resolver was called with a Host header, it is possible that the
port is included. if so, it will be stripped out so that the required
Host matches with the set `public_dns`.
Fix #307

[fix] Resolver strips port from Host header

---

kong-0.3.2-1.rockspec
kong/api/crud_helpers.lua
kong/cli/utils/signal.lua
kong/dao/cassandra/apis.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/consumers.lua
kong/dao/cassandra/factory.lua
kong/dao/cassandra/migrations.lua
kong/dao/cassandra/plugins_configurations.lua
kong/kong.lua
kong/plugins/base_plugin.lua
kong/plugins/basicauth/daos.lua
kong/plugins/keyauth/daos.lua
kong/plugins/ratelimiting/daos.lua
kong/tools/io.lua
kong/tools/migrations.lua
kong/tools/utils.lua
spec/unit/dao/cassandra_spec.lua
spec/unit/tools/utils_spec.lua

- Plugins can now have their own DAO(s) in a `daos.lua` file. The returned table for this file is a list of all DAOs for this plugin, so a plugin can have multiple DAOs to be future-proof.
- TRUNCATE queries now belong to their respective DAO.
- Migrations DAO is only loaded if explicitly asked. Thus only `kong.tools.migrations` loads it.
- DAOs now have a reference to the Factory: `self._factory`
- DAOs now belong to factory.daos[dao_name] but can be accessed via a shorthand `__index` method: factory[dao_name] for backward compatibility
A lot of work is still needed to have a proper DAO architecture for the plugins architecture:
- Remove tests in the core that rely on some of the plugins. Examples:
- `database_cache_spec` find another way to test that (@thefosk)
- `cassandra_spec` move …

[feature] Plugin DAOs

---

Makefile
spec/unit/tools/io_spec.lua

In Makefile, [ string1 = string2 ] is good compatibility, Such as ubuntu:dash do not support [ string1 == string2 ]

[ string1 = string2 ] is good compatibility

---

kong/dao/schemas_validation.lua
kong/plugins/basicauth/access.lua

Proposed fix for #361
- Fix wrong check in schema validation for sub-values with `default`
- Fix access.lua not throwing an error in case of missing configuration (
which is mandatory for this plugin)

[fix] basicauth not being executed by default

---

kong/api/crud_helpers.lua
kong/dao/cassandra/base_dao.lua
kong/dao/schemas_validation.lua
spec/integration/admin_api/apis_routes_spec.lua

#362 bis. Since plugin_configuration's `value` is stored as plain text in
Cassandra, if one made a PATCH request it could potentially override the
stored value because the DAO treated the field just like any other.
Instead, we need to set each property of a `value` that is not updated
by the PATCH before updating the row.
That behaviour doesn't apply to PUT requests.

[fix/api] Prevent PATCH from overriding plugin's value

---

kong/plugins/log_serializers/alf.lua
spec/integration/admin_api/apis_routes_spec.lua
spec/plugins/analytics/alf_serializer_spec.lua
spec/unit/tools/responses_spec.lua

- ALF serializer has a new test for the environment property
- Update the responses 500 test not calling ngx.log

[fix] ALF Serializer and responses tests

---

kong-0.4.0-1.rockspec
kong/cli/migrations.lua
kong/cli/utils/input.lua
kong/dao/cassandra/migrations.lua
kong/tools/migrations.lua

Handle occasional error where the schema_migrations columnfamily would
be missing thus preventing the migrations to work properly.
We now print a better error for the unaware user and suggest that the
"kong migrations reset" command should be run to fix this.
Fix #250 
```shell
$ kong start
[...]
[INFO] Connecting to the database...
[ERR] Missing mandatory column family "schema_migrations" in configured keyspace. Please consider running "kong migrations reset" to fix this.
$ kong migrations reset
[INFO] Resetting cassandra keyspace "kong"
Are you sure? You will lose your data. [Y/n] idk
Are you sure? You will lose your data. [Y/n] y
[OK] Keyspace successfully reset
$ kong start
[...]
[INFO] Connecting to the database...
[INFO] Database not initialized. Running migrations...
[OK] Migrated …
```

[fix/migrations] handle missing schema_migrations

---

kong/kong.lua
kong/plugins/basicauth/access.lua
kong/plugins/cors/access.lua
kong/plugins/keyauth/access.lua
kong/plugins/request_transformer/access.lua
kong/plugins/response_transformer/header_filter.lua

Instead of passing nil, pass an empty objects to plugins so they don't
have to check if `conf` exists.
Fix #352

[chore] Pass empty configuration to plugins

---

kong/plugins/basicauth/access.lua
kong/plugins/keyauth/access.lua
kong/tools/responses.lua
spec/integration/proxy/database_cache_spec.lua
spec/integration/proxy/resolver_spec.lua
spec/plugins/basicauth/access_spec.lua
spec/plugins/keyauth/access_spec.lua

[fix/auth] reply 401 to missing credentials

---

kong.yml
kong/api/app.lua
spec/unit/statics_spec.lua

Implementing CORS support in the Admin API #298.
This is the simplest way to do it, as I see no way to do it once Lapis has started processing the request.
Thoughts @ajayk @thefosk ?

[feat/admin api] enable CORS support

---

kong/api/app.lua
kong/api/routes/plugins.lua
spec/integration/admin_api/plugins_routes_spec.lua

Implement a suggestion from #309 to expose a plugin's schema in the API.
This allows UI builders to abstract a part of their code.
This adds an endpoint: `/plugins` to retrieve the `enabled_plugins` of
the node and `/plugins/:name/schema` to retrieve the schema.
`/plugins` can be confounded with `/plugins_configurations` but I see no
better name for it now.
Fix #309.

[feat/admin api] endpoint to retrieve a plugin's schema

---

kong/dao/cassandra/base_dao.lua
kong/dao/schemas/apis.lua
kong/dao/schemas/plugins_configurations.lua
kong/dao/schemas_validation.lua
kong/resolver/access.lua
spec/integration/proxy/resolver_spec.lua
spec/unit/dao/cassandra/base_dao_spec.lua
spec/unit/dao/entities_schemas_spec.lua
spec/unit/dao/oauth2/oauth2_entities_spec.lua
spec/unit/schemas_spec.lua

An API's `public_dns` can now contain one '*' at the start or at the end of the string, and on a dot border (same rules as http://nginx.org/en/docs/http/server_names.html#wildcard_names).
If so, it will get special treatment during the lookup and the resolver will try to match any given `Host` header against all wildcard `public_dns`.
We keep things efficient by guaranteeing O(1) lookup for non wildcard `public_dns`. Only wildcard `public_dns` and `paths` will be O(n).
Implements #297.

[feature] implement wildcard subdomains for APIs' public_dns

---

.travis.yml
.travis/setup_cassandra.sh
database/migrations/cassandra/2015-06-09-170921_0.4.0.lua
kong/dao/schemas/plugins_configurations.lua
kong/plugins/ratelimiting/access.lua
kong/plugins/ratelimiting/schema.lua
spec/plugins/ratelimiting/access_spec.lua
spec/plugins/ratelimiting/api_spec.lua
spec/plugins/ratelimiting/schema_spec.lua
spec/unit/dao/cassandra/base_dao_spec.lua
spec/unit/dao/entities_schemas_spec.lua

Closes issue #205 and deprecates #224.
This pull requests enables support for multiple rate-limit periods on the same API.
This PR promotes a new format for setting up the `ratelimiting` plugin, whose value is now `value.{period}={limit}`, for example: 
`value.second=10` instead of the previous one `value.limit=10&value.period=second`.
The plugin will transparently handle the old value format **without requiring** a migration of the data.

Handling multiple rate-limits

---

.luacheckrc
kong-0.4.0-1.rockspec
kong.yml
kong/dao/cassandra/base_dao.lua
kong/dao/schemas_validation.lua
kong/plugins/ip-restriction/access.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/ip-restriction/init_worker.lua
kong/plugins/ip-restriction/schema.lua
kong/vendor/resty-lrucache/lib/resty/lrucache.lua
kong/vendor/resty-lrucache/lib/resty/lrucache/pureffi.lua
spec/plugins/ip-restriction/access_spec.lua
spec/unit/statics_spec.lua

Closes #379. Adds a very basic security plugin, that blocks incoming requests per IP. 
Both individual IPs and ranges in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation) (like `127.0.0.0/24`) can be either whitelisted or blacklisted.
It also fixes a few bugs like:
* `nil` exception in DAO when updating a value that doesn't exist in a schema with a `PATCH` request
* During a `PATCH` update, setting an `array` field to an empty value properly initializes an empty table `{}` instead of `{""}`

[feature] IP Restriction Plugin

---

spec/integration/cli/start_spec.lua

Re enabling the start_spec suite since luassert now has an `error_matches` function.

[test] re-enabling start_spec

---

kong/resolver/access.lua
spec/integration/proxy/api_resolver_spec.lua

This is my first time doing this kind of thing so tell me if you need more detail or whatever!

Fix for stripping paths containing magic characters.

---

Makefile
README.md
kong/dao/cassandra/apis.lua
kong/plugins/log_serializers/alf.lua
kong/plugins/mashape-analytics/buffer.lua
kong/plugins/mashape-analytics/handler.lua
kong/plugins/mashape-analytics/schema.lua
kong/tools/ngx_stub.lua
spec/plugins/mashape-analytics/alf_serializer_spec.lua
spec/plugins/mashape-analytics/buffer_spec.lua
spec/plugins/mashape-analytics/fixtures/requests.lua

Addressing various issues reported in #423
- more descriptive logging in error.log
- clientIPAddress #424
- fix an issue when `log_body` was true but the request had no body (GET
request for example)
- fix an issue when nginx is retrying against upstream after a timeout
and resulting in multiple `upstream_response_time` values
- more robust buffering (payload size and better flushing)
- don't buffer aborted requests (refused by analytics anyways)

[fix/mashape-analytics] ALF serializer and Buffer

---

README.md

* + summary to not get lost
* + roadmap link
* + nicer development instructions
* - remove benchmark taking all the space, put a link to getknog.org/about/benchmark instead
* - redundant "documentation" paragraph

docs(readme) add related git repos and cleanup

---

Makefile
kong-0.4.1-1.rockspec
kong.yml
kong/cli/utils/signal.lua
kong/cli/utils/utils.lua
kong/dao/cassandra/apis.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/consumers.lua
kong/dao/cassandra/factory.lua
kong/dao/cassandra/plugins_configurations.lua
kong/plugins/ratelimiting/daos.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/unit/statics_spec.lua

This PR addresses #373 (Cassandra authentication). Kong can now be used with any authenticated/encrypted Cassandra cluster (ie. instaclustr.com).
In order to do this and as an investment for Cassandra related features to move faster in the future, the Cassandra driver was switched from jbochi/lua-resty-cassandra to a [new one](http://thibaultcha.github.io/lua-cassandra/manual/README.md.html), which supports both binary protocols v2 and v3, as well as authentication and client encryption.
- Cassandra driver (lua-cassandra) now uses binary protocol v3. This in an investment in order to improve the DAO in the future, and use some of the new features provided by the v3 protocol (ie. named values binding).
- Support for authentication …

[feature/dao] cassandra authentication + client encryption

---

Makefile
kong.yml
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/factory.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/integration/dao/cassandra/factory_spec.lua
spec/unit/statics_spec.lua

Since having the `port` option for Cassandra and also providing a way to set ports on a per-node basis, it makes it harder for users to "guess" how to add Cassandra nodes.
This changes the config file to show that `hosts` is an array of `host:port` and can be intuitively modified.
:warning: This is a breaking change since we don't support the `port` option anymore. Will need to be documented properly in `UPDATE.md` even if the steps are very straightforward.

[feature/config] remove port option for better usability

---

kong/plugins/log_serializers/alf.lua
spec/plugins/mashape-analytics/alf_serializer_spec.lua
spec/plugins/mashape-analytics/fixtures/requests.lua

As specified by ALF specs: https://github.com/ahmadnassri/har-validator/blob/8fd21c30edb23a1fed2d50b934d055d1be3dd7c9/lib/schemas/record.json#L12

[hotfix/analytics] alf serializer stringifies records

---

kong/resolver/access.lua
spec/integration/proxy/api_resolver_spec.lua
spec/spec_helpers.lua

- Prevent strip_path from matching multiple times the request_uri. Fix
#442
- Prevent the resolver from wrongfully matching some request_uri with
some paths.

[hotfix/resolver] strip_path fix + better matching

---

kong/api/routes/apis.lua
spec/integration/admin_api/apis_routes_spec.lua

The `/apis/{api}/plugins/{plugin}` route cannot have {name_or_id} to select the plugin, because multiple plugins might be added to an API (if targeting different Consumers).

[fix/api] disabling route path with plugin name

---

kong/plugins/oauth2/access.lua

The password grant did not save the authenticated_userid before (nil). Without this information the resource server will not be able to perform authorization on the user. 
I'm pretty sure the client credential grant should also try and save the authenticated_userid  if provided, but as I'm not lua guy I would let someone else have a look at that part.

Added authenticated_userid to password grant

---

kong/resolver/access.lua
spec/integration/proxy/api_resolver_spec.lua

Use $uri instead of $request_uri to allow path matching even if
querystring parameters are present.
Fix #495

[hotfix/path resolver] not matching if querystring

---

kong/dao/cassandra/apis.lua
kong/dao/cassandra/base_dao.lua
kong/dao/cassandra/consumers.lua
kong/dao/cassandra/factory.lua
kong/plugins/basicauth/daos.lua
kong/plugins/keyauth/daos.lua
kong/plugins/oauth2/access.lua
kong/plugins/oauth2/daos.lua
kong/plugins/oauth2/migrations/cassandra.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/integration/dao/cassandra/cascade_spec.lua
spec/plugins/oauth2/api_spec.lua

This implements a "delete hook" system to trigger cascade deletion of foreign rows in Cassandra. To do so, all foreign columns (representing foreign keys) must now be queryable (which means be indexed by Cassandra).
A "delete hook" is added to a parent DAO if any other DAO has foreign rows to that DAO. Ex: APIs are parents to plugins_credentials, hence the `apis` DAO will have a delete hook on the deletion of a row, to also delete any related `plugins_configurations`.
- Move cascade delete tests to another file, with all use cases of current cascade deletion.
- Add a migration for oauth2 plugin to index the `consumer_id` field.
- Remove obsolete overridden delete methods of apis and consumers DAOs.
This should be a solution to #438 and is an improved implementation of #107.
PS: I don't …

[feat/dao] implement cascade deletion for Cassandra

---

kong/plugins/log_serializers/alf.lua
spec/plugins/mashape-analytics/fixtures/requests.lua

Fix invalid ALFs when the URI contains reserved characters because
`request_uri` returns an unescaped string. `uri` returns the string
untouched but with querystring, which is fine for HAR.
Fix #470

[fix/alf-serializer] invalid 'url' property in ALF

---

kong/tools/utils.lua
spec/unit/tools/utils_spec.lua

Adding more than twice the same key will keep adding values to a list,
instead of creating nested tables.
Also handle object error values.
Fix #509

[fix/utils] add_error list behaviour

---

.travis.yml

2.1.9 has been released, and 2.1.8 is not available to download
anymore...

[chore/travis] bump Cassandra version

---

kong/dao/cassandra/base_dao.lua
kong/tools/migrations.lua

Auto paginated queries that failed preparation used to not throw an
error if the prepare failed. Thus misleading into confusing error
messages as in #532.

[fix] nil call

---

kong-0.5.0-1.rockspec
kong.yml
kong/plugins/hmac-auth/access.lua
kong/plugins/hmac-auth/api.lua
kong/plugins/hmac-auth/daos.lua
kong/plugins/hmac-auth/handler.lua
kong/plugins/hmac-auth/migrations/cassandra.lua
kong/plugins/hmac-auth/schema.lua
kong/tools/faker.lua
spec/plugins/hmac-auth/access_spec.lua
spec/plugins/hmac-auth/api_spec.lua
spec/plugins/hmac-auth/schema_spec.lua
spec/unit/statics_spec.lua

HMAC Plugin

---

kong/plugins/jwt/daos.lua
spec/plugins/jwt/api_spec.lua

Credentials could be migrated from another system, hence both `key` and
`secret` should be possible to manually set. They are still
auto-generated if not specified.

[feat/jwt] accept a manually set `secret`

---

kong/dao/schemas/apis.lua
kong/dao/schemas_validation.lua
kong/tools/ngx_stub.lua
spec/integration/admin_api/apis_routes_spec.lua
spec/integration/cli/start_spec.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/integration/dao/cassandra/cascade_spec.lua
spec/integration/proxy/api_resolver_spec.lua
spec/integration/proxy/database_cache_spec.lua
spec/integration/proxy/dns_resolver_spec.lua
spec/integration/proxy/realip_spec.lua
spec/plugins/acl/access_spec.lua
spec/plugins/basic-auth/access_spec.lua
spec/plugins/cors/access_spec.lua
spec/plugins/hmac-auth/access_spec.lua
spec/plugins/jwt/access_spec.lua
spec/plugins/key-auth/access_spec.lua
spec/plugins/logging_spec.lua
spec/plugins/oauth2/access_spec.lua
spec/plugins/rate-limiting/access_spec.lua
spec/plugins/rate-limiting/api_spec.lua
spec/plugins/request-size-limiting/access_spec.lua
spec/plugins/request-transformer/access_spec.lua
spec/plugins/response-ratelimiting/access_spec.lua
spec/plugins/response-ratelimiting/api_spec.lua
spec/plugins/response-transformer/access_spec.lua
spec/plugins/ssl/access_spec.lua
spec/unit/dao/entities_schemas_spec.lua

- API names cannot contain characters from RFC 3986 reserved characters
list. If such a character is detected, it is a schema error and the
creation/update is refused.
- This also sets an API's name to the given `request_path` if no
`request_dns` is set. The first slash is omitted and subsequent
slashes are replaced with dashes.
- Since spaces are not allowed anymore in API names, fixture APIs must
comply too.
See #547, #489

[feat/schemas] API names forbid reserved URI characters

---

kong/dao/schemas_validation.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/unit/dao/entities_schemas_spec.lua

Fixing null pointer exception on DAO update when config is missing

---

kong.yml

* I was doing some ssl tests and noticed that the nginx default configuration in kong.yml doesn't prevents from POODLE attack. This change adds a config change that protects from this.

Update kong.yml to protect from POODLE ssl attack. 

---

kong/plugins/jwt/access.lua
spec/plugins/jwt/access_spec.lua

[fix/jwt] handle `iss` not being found in jwt credentials

---

.ci/setup_kong.sh
kong/tools/timestamp.lua
spec/plugins/rate-limiting/access_spec.lua
spec/plugins/response-ratelimiting/access_spec.lua

This will fix the occasional test failure in rate-limiting plugins.

Adding wait time before rate-limiting tests

---

UPDATE.md

the git clone URL from the docs returned:
Permission denied (publickey).
since I don't have commit access. I changed that to https://... URL

Changed URL of cloned repo

---

kong/plugins/hmac-auth/access.lua
spec/plugins/hmac-auth/access_spec.lua

Added fix for #600. Now it will send 403 for wrong username instead of 500

hmac GH issues# 600 fix

---

kong/plugins/basic-auth/access.lua
kong/plugins/key-auth/access.lua
spec/plugins/basic-auth/access_spec.lua
spec/plugins/key-auth/access_spec.lua

Adds a new header 'WWW-Authenticate' for 401 responses, the header value typically should include a [challenge](http://stackoverflow.com/questions/17687876/authorization-in-restful-http-api-401-www-authenticate?answertab=votes#tab-top) with some information about the authentication scheme (key-auth) #587

Add 'WWW-Authenticate' header for reponses w/ status code 401 Unauthorized.

---

CHANGELOG.md
CONTRIBUTING.md
README.md

As discussed internally, we decided to change the git flow of Kong. This PR introduces the documentation changes in the development instructions.
- The `master` branch is to hold only production-ready, released code. Release tags are to be created on this branch. **No direct commit** is to be made to this branch.
- The `next` branch is to hold development, unreleased code. **No direct commit** is to be made to it either.
- **New features** are to be introduced through a pull request against the `next` branch. (Ideally the branch is named `feat/xxx`)
- **Bug fixes** must either be proposed in a pull request against the `next` branch, or, depending on the urgency of it, against the `master` branch. If made against the `master` branch, it is considered a hotfix and must be manually merged in …

[docs] document the new gitflow

---

kong/plugins/log-serializers/alf.lua
spec/plugins/mashape-analytics/alf_serializer_spec.lua
spec/plugins/mashape-analytics/fixtures/requests.lua

If a request or response have multiple Content-Type headers, this make
sure the latest one is returned, so mimeType is guaranteed to be a
string, and not an array.
Fix for #584

[fix/alf_serializer] always ensure mimeType is a string

---

spec/plugins/oauth2/access_spec.lua

Some more tests to make sure #535 is fixed.

OAuth 2.0 tests to check for upstream headers

---

kong.yml
kong/cli/utils/signal.lua
kong/dao/cassandra/schema/migrations.lua
kong/tools/config_defaults.lua
kong/tools/config_loader.lua
kong/tools/dao_loader.lua
kong/tools/migrations.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/integration/dao/cassandra/migrations_spec.lua
spec/unit/dao/cassandra/migrations_spec.lua
spec/unit/tools/config_loader_spec.lua

Reopening of #589 against feat/commented-config this time.
Possibility to configure the replication strategy used by the created
keyspace and its options.
Added options:
```yaml
######
######
######
######
```
Implements #543 and #350

[feat/cli] keyspace options in configuration and un-nesting

---

.travis.yml

2.1.11 since 2.1.10 has been removed from the Apache downloads.

[chore/ci] bump cassandra

---

CHANGELOG.md
kong/cli/utils/signal.lua
kong/tools/io.lua

Since IO.file_exists was being called and of course returned false when
called with just `nginx`, the command was never executed, and no chance
was given to the shell to try to find the executable in the $PATH.
Fix #610

[hotfix/path] search nginx executable in $PATH

---

kong/plugins/jwt/api.lua
spec/plugins/jwt/api_spec.lua

Revert "Allow PATCH method on jwt credential endpoint"

---

kong/plugins/oauth2/access.lua

This fixes an edge case when there is a query-string appended to the URL which wasn't previously handled.

Better URL handling for OAuth 2.0

---

kong-0.5.2-1.rockspec
kong/dao/cassandra/base_dao.lua
kong/tools/utils.lua
spec/integration/dao/cassandra/base_dao_spec.lua
spec/plugins/key-auth/daos_spec.lua
spec/plugins/rate-limiting/daos_spec.lua
spec/plugins/response-ratelimiting/daos_spec.lua
spec/unit/tools/faker_spec.lua

This PR replaces https://github.com/Tieske/uuid with https://github.com/Mashape/lua-uuid.
The previous UUID library seemed to produce UUID conflicts that lead to errors like #659. The new library leverages [libuuid](http://linux.die.net/man/3/libuuid) which provides a more solid implementation.
When we decide to merge this PR, we need to update https://github.com/Mashape/kong-distributions to include a dependency to libuuid whenever the operating system doesn't already ship with it.

Replacing the previous uuid library with our lua_uuid

---

kong/resolver/access.lua
spec/integration/proxy/api_resolver_spec.lua

This should fix issue #688. 
@yoanisgil to test this do you need a distribution package? If yes, just tell me your system and I can create it for you.

[hotfix/resolver] avoid URL decoding in URI proxying

---

kong.yml

In the current code we are using the `PATH` environment variable without specifying `env PATH;` in the nginx configuration, required because nginx does not pass along all the system environments unconditionally. This could lead to some problems on certain systems.
**Note**: The environment variable `PATH` will not be used anymore in the next major version. So this hotfix only applies to Kong < 0.6.0.

Added missing "env PATH" statement

---

kong.yml
spec/integration/admin_api/kong_routes_spec.lua

This sets the limit of request bodies to the Admin API to 10MB.
Closes #700.

Properly handling big request bodies in Admin API

---

kong/tools/migrations.lua

Noticed this in a screenshot on #660.

Fixes typo in "Inconsistency" error message

---

kong/core/certificate.lua
kong/dao/cassandra/base_dao.lua
kong/plugins/response-ratelimiting/log.lua

Makes sure that DAO errors are printed with `tostring(err)`. Also fixes the little logging quirk reported in #734.

Properly printing DAO errors

---

spec/plugins/mashape-analytics/fixtures/requests.lua

One fixture body was missing a 'base64_' prefix since #747

fix(specs) correct alf_serializer_spec fixture

---

kong/plugins/oauth2/access.lua
kong/plugins/oauth2/schema.lua
kong/plugins/ssl/access.lua
kong/plugins/ssl/schema.lua
spec/plugins/oauth2/access_spec.lua
spec/plugins/ssl/access_spec.lua

Added the `accept_http_if_already_terminated` to the SSL and OAuth 2.0 plugins to accept HTTP requests with a `X-Forwaded-Proto: https` header when the request was supposed to be sent on HTTPs.
* Makes the SSL and OAuth 2.0 plugins work behind a Load Balancer that already does SSL termination, like the ELB.
* Fixes the previous OAuth 2.0 check which allowed every client to bypass the check by simply sending `X-Forwaded-Proto: https`. Now that check needs to be explicitly enabled only when the server cannot be reached from the outside, and the only point of entry is a Load Balancer that already terminates SSL.

Added "accept_http_if_already_terminated" to SSL and OAuth 2.0

---

kong/plugins/mashape-analytics/handler.lua

JSON bodies need to be present in the text field but not included in
`postData.params`.
This also avoids reading the request body if not configured so in the
plugin.
Sadly there is no unit test for this part of the ALF serializer.
Fix #762

hotfix(alf_serializer) do not include JSON body in params

---

kong/tools/utils.lua
spec/integration/admin_api/apis_routes_spec.lua
spec/integration/admin_api/plugins_routes_spec.lua
spec/unit/tools/utils_spec.lua

Fixes the encoding of boolean parameters in the body of HTTP requests generated by `http_client`.

Fixing body encoding for boolean parameters in http_client

---

.ci/setup_cassandra.sh

seen multiple download failures in CI logs, added 5 retries to fix these

Update CI script cassandra to retry download if it fails

---

.luacheckrc
kong-0.5.4-1.rockspec
kong/plugins/file-log/log.lua

This PR better handles the system constants being used by the file-log plugin, and also introduces better error handling if the file cannot be created/opened.
It also introduces a new dependency, because LuaFFI does not allow to access system constants, and the only solution would be to hard-code them. Problem is the constants values change depending on the system where Kong is being compiled, so the new dependency [`lua_system_constants`](https://github.com/Mashape/lua-system-constants) always makes sure that the constants are correct and not hard-coded with the wrong value.

Better handling of system constants in the file-log plugin

---

.ci/setup_kong.sh
CHANGELOG.md
bin/kong
kong/cli/config.lua
kong/cli/db.lua
kong/cli/migrations.lua
kong/cli/quit.lua
kong/cli/reload.lua
kong/cli/restart.lua
kong/cli/start.lua
kong/cli/stop.lua
kong/cli/version.lua

The dev package was already obsolete, dropped Lua dependency from Kong install script and changed CLI to use the LuaJit engine.

move CLI from Puc Lua to LuaJit, reducing dependencies

---

kong/dao/cassandra/factory.lua
kong/kong.lua
kong/tools/dao_loader.lua
kong/tools/ngx_stub.lua

- Cluster is only spawned when inside if ngx_lua (when starting Kong).
- Ensure LuaSocket is used by the driver by changing the return value of
`ngx_stub.get_phase()` to `init`.
- Ensure lua-cassandra does not output logs when in the `init` phase
(which is the case because of change #2) and inside of the specs.
Which is why `ngx.stub` is a new property.
@shashiranjan84

fix(dao) do not spawn cluster when outside of ngx_lua

---

kong-0.5.4-1.rockspec
kong/plugins/datadog/handler.lua
kong/plugins/datadog/schema.lua
kong/plugins/datadog/statsd_logger.lua
kong/tools/config_defaults.lua
spec/plugins/datadog/log_spec.lua

Compiles metrics like Request count, size, Response status and latency and send it to
Datadog statsd server

[plugin/datadog] Logging to statsd server

---

kong/plugins/request-transformer/access.lua
kong/plugins/request-transformer/schema.lua
spec/plugins/request-transformer/access_spec.lua

Fix for issue #393 for response-transformer motivated fix for this plugin too. New config append/replace added to support adding new value to existing header/querystring and
replcaing  existing header/querystring with new value.

refactor(req-transformer) append, replace of header/querystring

---

CHANGELOG.md
UPGRADE.md

Changelog for `0.5.4..next`. This does not includes changes in the invalidations branch, which should be, with eventually minor modifications:
```patch
diff --git a/CHANGELOG.md b/CHANGELOG.md
index c073a39..8c610fc 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -4,11 +4,25 @@
+- [Serf](https://www.serfdom.io/) is now a Kong dependency. It allows Kong node to communicate between each other opening the way to many features and improvements.
- The configuration file format changed. Some properties were slightly moved, many others are new. For example, the cassandra properties are not nested under `cassandra.properties` anymore, but rather directly under `cassandra`. Since many new properties are available, it is wise to consult the new configuration file while updating yours.
- Drop the …
```

docs(changelog) 0.6.0 changes

---

kong.yml
kong/api/app.lua
kong/api/routes/kong.lua
kong/api/routes/plugins.lua
kong/cli/migrations.lua
kong/constants.lua
kong/kong.lua
kong/tools/config_defaults.lua
kong/tools/config_loader.lua
kong/tools/dao_loader.lua
kong/tools/migrations.lua
spec/integration/cli/start_spec.lua
spec/integration/dao/cassandra/migrations_spec.lua
spec/unit/tools/config_loader_spec.lua

As per description.
When loading the configuration, a new entry is dynamically entered, `configuration.plugins`, which merges the available plugins with the custom plugins added in the conf file.

plugins_available becomes custom_plugins

---

kong/plugins/jwt/access.lua
kong/plugins/jwt/jwt_parser.lua
kong/plugins/jwt/schema.lua
spec/plugins/jwt/access_spec.lua

This patch adds support for a configurable JWT secret key field,
defaulting to 'iss'.

[JWT] support for base64 encoded secrets and arbitrary claim for secret

---

kong.yml
kong/cli/config.lua
kong/core/handler.lua
kong/kong.lua

one exception; `ssl_certificate` is still `certificate` as that is part of the public api for plugins

standardizes naming in kong core modules

---

CHANGELOG.md
kong/dao/cassandra/base_dao.lua
spec/integration/admin_api/apis_routes_spec.lua

The base_dao `update()` method used the old entity table to build the
UPDATE query instead of the one merged with the new parameters. If a
field was previously unset, PATCH would then not set it to the new value
(because the old entity table did not have the field present).
Fix #857

fix(api patch) allow PATCH to set an unset field

---

spec/integration/cli/reload_spec.lua
spec/integration/cli/start_spec.lua

fix cli tests to cleanup db in between tests, preventing data from spilling over to the next test.

fix cli tests

---

Makefile

Fixes the check whether development rocks have been installed.
Currently `make dev` fails checking and reinstalls everything, this fixes it and reinstalls only if not installed already

[fix/chore] Fixes `make dev` to not reinstall rocks already available

---

kong/dao/schemas_validation.lua
kong/plugins/ip-restriction/access.lua
kong/plugins/ip-restriction/init_worker.lua
kong/plugins/ip-restriction/schema.lua
spec/plugins/ip-restriction/access_spec.lua
spec/plugins/ip-restriction/api_spec.lua

Also add checks to make sure #782 does not happen (even if I could not
reproduce).

perf(ip-restriction) cache globals and use table.getn()

---

kong-0.5.4-1.rockspec
kong/plugins/file-log/log.lua

- Caching the oflags and mode arguments of open() avoids the invoke the C
binding on every execution of `log_by_lua`.
- It is more common to create a log file with 644 permissions. This needed
an update of lua-system-constants.

[file-log] perf fix and new file permissions on O_CREAT

---

kong/dao/schemas/apis.lua
spec/integration/admin_api/kong_routes_spec.lua
spec/unit/dao/entities_schemas_spec.lua

- Stronger validation of an API's request_path
- Stronger test suite for API schema validation (and sorted the mess)
- Prevent '/' from being considered a valid request_path
Fix #880

refactor(schema) stronger request_path validation

---

README.md

The badge is pointing to the master branch, which is *currently* failing, but will get back in the green once next is merged.

docs(readme) add CI badge back

---

.ci/run_tests.sh
.ci/setenv_kong.sh
.ci/setup_cassandra.sh
.ci/setup_dnsmasq.sh
.ci/setup_lua.sh
.ci/setup_openresty.sh
.ci/setup_serf.sh
.travis.yml

- unfortunately, the tests are really, really too long with a --repeat 3 setting
- update Luarocks version
- simpler .travis.yml with a .ci/setenv_kong.sh script
- allow caching of multiple versions of OpenResty
- luacov in a dependency of luacov-coveralls, hence not needed
- update setup_lua.sh script with latest Lua versions and improvements
- remove "VERSION" suffix from ENV variables

chore(ci) no more --repeat and setup improvements

---

kong/cli/services/nginx.lua

C* client-to-node CA file was not inserted in nginx.conf since 0.6.0 and the CLI services refactoring. Sadly this is not tested in CI because we do not maintain an SSL cluster for testing.
PS: @mars Here it is!

hotfix(cass) insertion of SSL certificate in nginx.conf for C* cluster

---

kong.yml
kong/cli/services/nginx.lua
spec/unit/dao/cassandra/factory_spec.lua

kong.yml proposed this property as `user` wether the real name of the
property is in fact `username` as seen in the config defaults and the
Cassandra DAO Factory.

fix(config) proper name for C* username auth scheme

---

kong/plugins/http-log/handler.lua
spec/plugins/logging_spec.lua

Removing additional \r\n at the end of the HTTP body

---

kong/plugins/log-serializers/alf.lua
kong/plugins/mashape-analytics/buffer.lua
kong/plugins/mashape-analytics/handler.lua

- If the access phase of the galileo handler is not executed, we are
missing the ngx.ctx.analytics data in the ALF serializer. This fallsback
on an empty ctx.
- 4720b7b renamed the previous 'locks' shm and broke the galileo retry
policy relying on it. To avoid users to modify their nginx config if
they use a custom one, this makes galileo use the already present (and
huge) 'cache' shm.

hotfix(galileo) missing shared dict and skipped access phase fixes

---

kong/plugins/oauth2/api.lua
spec/plugins/oauth2/api_spec.lua

Adds `PUT` support to `/oauth2_tokens/`. Closes #897.

Closes #897

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/schema.lua
spec/plugins/rate-limiting/access_spec.lua

Allow to increase the counter asynchronously. Also closes #912 because if the counter is being increased asynchronously, and the DB is down, the request will fail in the timer and the request can be still be processed.

Supporting async increment for rate-limiting plugin

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/schema.lua
kong/plugins/response-ratelimiting/access.lua
kong/plugins/response-ratelimiting/handler.lua
kong/plugins/response-ratelimiting/header_filter.lua
kong/plugins/response-ratelimiting/schema.lua
spec/plugins/rate-limiting/access_spec.lua
spec/plugins/response-ratelimiting/access_spec.lua

Rate-Limiting and Response Rate-Limiting can continue on DB error

---

kong/plugins/datadog/handler.lua
kong/plugins/datadog/schema.lua
spec/plugins/datadog/log_spec.lua

This commit was reverted for the incoming 0.6.1 release containing hotfixes only.

feature(datadog) Add resp-size metric

---

kong/cli/utils/services.lua

This PR adds the following checks to the Kong startup logic:
* Check if the working directory exists. If it doesn't it tries to create it and set the right permissions
* Checks if the working directory is a real directory, and not a file
* Checks if the working directory has write, read and executable permissions to the user that's currently running Kong (executable permissions required by the Serf even handler).
On a side note `nginx_working_dir` should be renamed in the future to `working_dir` or `kong_working_dir` since it's not specific to nginx anymore.

Working directory checks on startup

---

kong/cli/services/serf.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/ip-restriction/schema.lua
spec/plugins/ip-restriction/access_spec.lua

Fixes the restart bug mentioned in #782, and adds an additional check if the request comes from a unix domain socket.

Fixes a bug in the invalidation event of the IP Restriction plugin

---

kong/dao/cassandra/base_dao.lua
kong/dao/schemas/apis.lua
kong/dao/schemas/consumers.lua
kong/dao/schemas/plugins.lua
kong/plugins/ip-restriction/schema.lua
kong/plugins/ssl/schema.lua
spec/integration/dao/cassandra/events_spec.lua
spec/plugins/logging_spec.lua
spec/plugins/rate-limiting/access_spec.lua
spec/plugins/response-ratelimiting/access_spec.lua

`marshall_event` by default now returns an empty object, and the properties to propagate need to be explicitly returned.
This changed the previous behavior where by default `marshall_event` returned the entire object.

Reducing avg Serf UDP packet sizes

---

kong.yml
kong/cli/services/nginx.lua

This removes the annoying `warn` log in `error.log`.

The user directive is set only if the user is root

---

kong/cli/services/serf.lua

Serf log is stored in the `nginx_working_dir` instead of `/tmp`.

Serf log is stored in the nginx_working_dir

---

kong-0.6.1-0.rockspec
kong.yml
kong/core/error_handlers.lua

Returning JSON responses for common upstream server errors

---

kong-0.6.1-0.rockspec
kong/plugins/log-serializers/runscope.lua
kong/plugins/runscope/handler.lua
kong/plugins/runscope/log.lua
kong/plugins/runscope/schema.lua

Manually applied #863 with minor modifications.

feat(plugins) new Runscope plugin

---

kong/core/plugins_iterator.lua
kong/kong.lua
spec/plugins/rate-limiting/access_spec.lua

Closes #978. 
Also loads the consumer-specific configuration only for those plugins that have `no_consumer = false` in the schema.

Fixing the plugins loader

---

CHANGELOG.md
UPGRADE.md

- 0.7.x changelog (still as "unreleased")
- 0.7.x upgrade path
Note in upgrade path that I feel is appropriate:
> **Note**: We expose the underlying NGINX configuration as a way for Kong
to be as flexible as possible and allow you to bend your NGINX instance
to your needs. We are aware that many of you do not need to customize it
and such changes should not affect you. Plans are to embed the NGINX
configuration in Kong, while still allowing customization for the most
demanding users. [#217](https://github.com/Mashape/kong/pull/217) is the
place to discuss this and share thoughts/needs.

docs(changelog) 0.7.x changelog and upgrade path

---

kong/api/routes/kong.lua

Shows the following stats in the index endpoint `/` of the Kong API, for example:
```json
{
"timers": {
"running": 2,
"pending": 5
}
...
}
```

Showing ngx timers stats in the API

---

kong/plugins/acl/hooks.lua
spec/plugins/acl/access_spec.lua

Adding invalidation event when assigning a new ACL group

---

kong-0.6.1-0.rockspec
kong/api/app.lua
kong/api/routes/apis.lua
kong/api/routes/cluster.lua
kong/api/routes/kong.lua
kong/api/routes/plugins.lua
kong/core/certificate.lua
kong/core/cluster.lua
kong/core/hooks.lua
kong/core/plugins_iterator.lua
kong/core/resolver.lua
kong/kong.lua
kong/plugins/acl/daos.lua
kong/plugins/acl/handler.lua
kong/plugins/basic-auth/access.lua
kong/plugins/basic-auth/daos.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/oauth2/access.lua
kong/plugins/rate-limiting/handler.lua
kong/plugins/response-ratelimiting/access.lua
kong/plugins/response-ratelimiting/log.lua
kong/singletons.lua
spec/unit/core/resolver_spec.lua

*(Second try on this PR.)*
Follow-through from https://github.com/mars/kong/commit/f59c849960930dd2e709197df10d14ef93bfd06c
Replacing globals will not change any functional behavior. It will:
* avoid slow global lookups
* make it easier for devs to see where values come from
The module name `singletons` was chosen to make it easy to find these anywhere in the project; names like `env`, `environment`, `config`, etc. would lead to confusion.

Replace globals with `kong.singletons` module variables.

---

kong/api/routes/cluster.lua
kong/cli/services/serf.lua
kong/cli/utils/services.lua
kong/core/cluster.lua
kong/core/hooks.lua

This change adds the node on start, and not on hook. It provides a better way of dealing with the `nodes` table, and also allows `nginx` to be the last service to start up.
Also tries to address issue #1004.

Adding node on start, and not on hook

---

kong.yml
kong/dao/cassandra/factory.lua
kong/tools/config_defaults.lua
spec/unit/dao/cassandra/factory_spec.lua

Configurable Cassandra consistency level

---

kong-0.7.0-0.rockspec
kong/api/app.lua
kong/api/routes/apis.lua
kong/api/routes/cluster.lua
kong/api/routes/kong.lua
kong/api/routes/plugins.lua
kong/core/certificate.lua
kong/core/cluster.lua
kong/core/hooks.lua
kong/core/plugins_iterator.lua
kong/core/resolver.lua
kong/kong.lua
kong/plugins/acl/daos.lua
kong/plugins/acl/handler.lua
kong/plugins/basic-auth/access.lua
kong/plugins/basic-auth/daos.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/oauth2/access.lua
kong/plugins/rate-limiting/handler.lua
kong/plugins/response-ratelimiting/access.lua
kong/plugins/response-ratelimiting/log.lua
kong/singletons.lua
spec/unit/core/resolver_spec.lua

Reapplying the patch from #982 with squashed commits and against `next`.

refactor: use singleton pattern instead of globals

---

kong/constants.lua

Enables the Runscope plugin in the default installation.

Loading runscope by default

---

kong/cli/utils/services.lua

Properly logs `prepare` errors in the CLI. Closes #1066.

Closes #1066

---

README.md

Url to Kong story is broken in documentation.

Fix url typo in README

---

CHANGELOG.md
kong/plugins/basic-auth/api.lua
kong/plugins/key-auth/api.lua

- `/consumers/:consumer/keyauth` -> `/consumers/:consumer/key-auth`
- `/consumers/:consumer/basicauth` -> `/consumers/:consumer/basic-auth`

Drop long deprecated Admin API routes

---

kong-0.7.0-0.rockspec
spec/unit/rockspec_spec.lua

+ test to ensure most of our Lua modules bear the same name when
installed via Luarocks as when required from './kong'
fix #1079

fix(rockspec) rename runscope.buffer to runscope.log

---

Makefile
kong.yml
kong/dao/migrations/postgres.lua
kong/dao/postgres_db.lua
spec/integration/dao/02-migrations_spec.lua

This PR does two things:
* Auto-creates the PostgreSQL database if it's not existing, with an implementation similar to how the Cassandra DAO does it. The behavior is now 1:1 to how Cassandra works.
* Fixes `make dev` which caused an issue where the `kong_TEST.yml` file would't be created.
It also adds more comments in `kong.yml` in the `postgres` section.

Auto-create Postgres database and fix make dev

---

kong.yml
kong/cli/services/serf.lua
kong/core/cluster.lua
kong/dao/cassandra_db.lua
kong/dao/dao.lua
kong/dao/postgres_db.lua
kong/tools/config_defaults.lua
spec/integration/dao/07-options_spec.lua

Fixes the TTL problem mentioned by @chrisanderton in https://github.com/Mashape/kong/pull/1054.
Also introduces the `ttl_on_failure` property in the configuration file, because `3600` may not be an appropriate value for every environment.
This PR is to be merged in both `next` and `release/0.8.0`.

Fixing TTL in Cassandra

---

kong/core/reports.lua
kong/dao/migrations/postgres.lua
kong/dao/postgres_db.lua
kong/tools/config_defaults.lua
spec/integration/dao/02-migrations_spec.lua

Reverts #1105, because effectively is becoming more complicated to implement this right rather than move the complexity to the final user.
One thing that this PR changes is having a `nullable` password instead of a default `kong` password.
Also closes #1136 (does not apply anymore). We will collect feedback and usage data from our users and see how big of an issue this is, and eventually I will go back at it if it's required.

Reverting back Postgres auto-creation of database

---

kong-0.8.0rc2-0.rockspec
kong/constants.lua
kong/plugins/statsd/handler.lua
kong/plugins/statsd/schema.lua
kong/plugins/statsd/statsd_logger.lua
spec/plugins/statsd/log_spec.lua

Statsd plugin logs metrics like request count, request size, unique users etc to statsd server

plugin/statsd (feature) Statsd logger

---

CHANGELOG.md
kong-0.8.0rc2-0.rockspec
kong.yml
kong/dao/cassandra_db.lua
kong/tools/config_defaults.lua

Clusters with nodes not running on the default `9042` port couldn't be
properly reached by Kong. This bumps the driver (including the fix), and
adds a `port` options to the configuration. Thanks @allisthere2love for
the investigation.
This issue was never encountered before and my guess is because such
clusters added their contact_points including the port (`x.x.x.x:9043`),
and the driver could connect to it, but not to the other nodes, since it
was trying `9042` on those. So it simply considered the other nodes as
DOWN, and thus still worked from an outsider's POV (if one doesn't check the logs and those lags
are not displaying warnings, it seems like nothing is going wrong).
However @allisthere2love had nodes from another C* cluster listening on
`9042`, leading to inconsistencies and …

fix(cassandra) add a 'port' option for clusters

---

kong/tools/utils.lua
spec/unit/02-utils_spec.lua

Addresses an issue mentioned in #1160 (thanks to @asknaskan for the implementation).

Better get_hostname() implementation

---

kong/dao/schemas/apis.lua
kong/dao/schemas/consumers.lua
kong/dao/schemas/nodes.lua
kong/dao/schemas/plugins.lua
kong/dao/schemas_validation.lua
kong/plugins/response-ratelimiting/header_filter.lua
spec/integration/04-admin_api/apis_routes_spec.lua
spec/integration/04-admin_api/consumers_routes_spec.lua
spec/unit/10-schema_validation_spec.lua

Addresses #1166 by properly enforcing required fields when full-updating an entity.

Enforcing required fields on full-updates

---

kong/constants.lua
kong/core/resolver.lua
spec/integration/05-proxy/resolver_spec.lua

Adds `X-Forwarded-Host` and `X-Forwarded-Prefix` to the upstream request headers (depending if the API is being resolved using the `Host` header or the path).
Closes #1150.

Closing #1150

---

kong.yml
kong/tools/config_defaults.lua

`ttl_on_failure` should be at least `60`.

Implementing missing check on ttl_on_failure

---

kong/plugins/loggly/handler.lua
spec/plugins/loggly/log_spec.lua

loggly plugin was failing for 400 and 500 errors. This commit
fix the issue #1183

fix (plugin/loggly) fix for issue 1183

---

kong/core/resolver.lua
kong/dao/schemas/apis.lua
spec/integration/05-proxy/resolver_spec.lua
spec/unit/11-entities_schemas_spec.lua

Supports simple slash in request_path

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/response-ratelimiting/access.lua
kong/plugins/response-ratelimiting/header_filter.lua
kong/plugins/response-ratelimiting/schema.lua
spec/plugins/response-ratelimiting/access_spec.lua

Closes #1096.
This PR does two things:
* Appends usage header to the upstream request, so that the API can determine if a request, bulk or not bulk, can be processed or not. The headers will be in the form of `X-Ratelimit-Remaining-{limit_name}`, like `X-Ratelimit-Remaining-Image`.
* Introduces a `block_on_first_violation` configuration property that blocks processing requests when at least one limit has been reached.

Fixing some use-cases of the response rate limiting plugin

---

kong-0.8.1-0.rockspec
spec/integration/05-proxy/resolver_spec.lua

Fixes some problems introduced by #1227.

Fixing tests

---

kong/plugins/jwt/handler.lua

When migrating from an older version of Kong, the 'algorithm' field is
left empty. Better to include it in the code rather than in the
migration to resolve the issue for users who already migrated.
Fix #1233

hotfix(jwt) default algorithm to 'HS256'

---

kong/dao/postgres_db.lua

Prevent it from exploding into a Lua error, obfuscating the real error. Now returns the DB error.
See issue #1239

Fixed a failed error parsing on Postgres.

---

kong/plugins/response-transformer/handler.lua
kong/plugins/response-transformer/header_transformer.lua
spec/plugins/response-transformer/skip_body_spec.lua

Fix response transformer hang. See issues #1260 and #1207

---

kong/plugins/oauth2/access.lua
kong/plugins/ssl/handler.lua
kong/tools/utils.lua
spec/unit/02-utils_spec.lua

fixes #1246 
Note: test is pending because multiple headers cannot be added in the current test setup

duplicate headers are no longer allowed. 

---

kong/cli/services/serf.lua
kong/core/cluster.lua
kong/tools/cluster.lua

This PR creates a `serf.id` file at startup (only the first time if the file is missing) in the Kong working directory. The value of the file is then used as a `name` in the `nodes` table when starting a Kong node.
Should close #1255 and maybe #1160.
If this is merged, it needs to be back-ported to `refactor/cli`.

Closing #1255

---

kong.conf.default
kong/cmd/utils/serf_signals.lua
kong/templates/kong_defaults.lua

This new format follows PostgreSQL's configuration file and allows for a
cleaner, easier to read and edit configuration file.
- comments were also slightly rewritten and notes have been added.
- mentions of ngx_lua and Serf.
- change default `log_level` to `notice` instead of `error`.

refactor(conf) new format

---

spec/helpers.lua

I found myself repeating a lot of data structure parsing and handling responses and requests (returned from mockbin). So I wrote some assertions and modifiers.
It allows you to do this;
```lua
local res = assert(client:send {
method = "POST",
path = "/request",
query = {
hello = "world",
hello2 = "world2",
},
body = {
["toremoveform"] = "yes",
["nottoremove"] = "yes"
},
headers = {
["Content-Type"] = "application/x-www-form-urlencoded",
host = "test4.com",
custom = "myValue"
}
})
local body_as_text = assert.response(res).has.status(200)
local body_as_table = assert.response(res).has.jsonbody()
local value = assert.response(res).has.header("custom")
assert.equal("myValue", value)
local assert.request(res).has.no.queryparam("hello3")
local param = …
```

feat(helpers) new busted assertions and modifiers

---

kong-0.8.2-0.rockspec
kong/cmd/utils/nginx_signals.lua
kong/cmd/utils/serf_signals.lua

feat(cli) better version information for dependency binaries

---

kong/dao/schemas/apis.lua
spec/01-unit/08-entities_schemas_spec.lua
spec/02-integration/03-admin_api/02-apis_routes_spec.lua

fixes #1300 and i18n hostnames. See https://github.com/Mashape/kong/issues/1205#issuecomment-221386825

accepts hostnames without TLD, and i18n formats (punycode).

---

kong.conf.default
kong/conf_loader.lua
kong/templates/kong_defaults.lua
kong/templates/nginx_kong.lua
spec/01-unit/03-prefix_handler_spec.lua

When specifying a certificate for datastore connections, it can be
required to adjust the verification depth in the certificates chain.
This adds the `lua_ssl_verify_depth` directive when *and only when* a
certificate is configured for Cassandra connections.
Once PostgreSQL SSL connections will be supported, we will handle better
the `lua_ssl_trusted_certificate` directive as well as the verify depth.
* New property: new default + added and documented it in
`kong.conf.default`
* new test
Implements #1395

feat(conf) add 'lua_ssl_verify_depth' property

---

spec/03-plugins/key-auth/01-api_spec.lua

closes #772. Fix was already applied, this adds only the test.

refactor/key-auth: extends test to validate unique random keys

---

kong/plugins/oauth2/access.lua
kong/plugins/oauth2/daos.lua
kong/plugins/oauth2/migrations/cassandra.lua
kong/plugins/oauth2/migrations/postgres.lua
spec/03-plugins/oauth2/03-access_spec.lua

* Authorization codes can only be used once.
* Authorization codes can only be used by the application that created it.
This fix involves a migration of the database to support an additional `credential_id` column in the `oauth2_authorization_codes` table.

fix(oauth2) security fixes

---

kong-0.8.3-0.rockspec
kong.conf.default
kong/cmd/utils/prefix_handler.lua
kong/conf_loader.lua
kong/dao/cassandra_db.lua
kong/dao/postgres_db.lua
kong/templates/kong_defaults.lua
kong/templates/nginx_kong.lua
spec/01-unit/02-conf_loader_spec.lua
spec/01-unit/03-prefix_handler_spec.lua

This bumps pgmoon to v1.5.0 and adds the necessary configuration
settings to allow for SSL connections to PostgreSQL when used as Kong's
backend.
It removes the `cassandra_ssl_trusted_cert` property in favor of
`lua_ssl_trusted_certificate` in the misc section, since this setting is
not stricly related to Cassandra/Postgres connections but any Lua
cosocket one too.
* bump pgmoon to v1.5.0
* add posdtgres and misc default settings for SSL connections
* document postgres/misc settings for SSL connections
* remove `cassandra_ssl_trusted_cert`
* update kong nginx config compilation tests
Implements #1309

feat(postgres) implement SSL connections capability

---

kong-0.9.0rc1-0.rockspec
kong/cmd/utils/nginx_signals.lua
kong/meta.lua
kong/plugins/rate-limiting/migrations/cassandra.lua
kong/plugins/rate-limiting/migrations/postgres.lua
spec/01-unit/01-rockspec_spec.lua

Release `0.9.0rc1` with some fixes along the way.
* Release `0.9.0rc1`.
* OpenResty `1.9.15.1` required.
* Fixed rockspec test.
* Fixed rate-limiting migration.

fix(migrations) + release(0.9.0rc1)

---

.ci/run_tests.sh
.ci/setup_env.sh
.travis.yml
Makefile
kong/cmd/cluster.lua
kong/cmd/utils/serf_signals.lua
kong/serf.lua
kong/templates/kong_defaults.lua
spec/02-integration/00-helpers/00-helpers_spec.lua
spec/02-integration/01-cmd/02-start_stop_spec.lua
spec/02-integration/01-cmd/04-reload_spec.lua
spec/02-integration/01-cmd/07-cluster_spec.lua
spec/02-integration/01-cmd/08-restart_spec.lua
spec/02-integration/03-admin_api/06-cluster_routes_spec.lua
spec/02-integration/04-core/02-hooks_spec.lua
spec/02-integration/06-cluster/01-cluster_spec.lua
spec/03-plugins/005-syslog/01-log_spec.lua
spec/03-plugins/008-datadog/01-log_spec.lua
spec/03-plugins/06-jwt/01-jwt_parser_spec.lua
spec/03-plugins/98-rate-limiting/04-access_spec.lua
spec/03-plugins/99-oauth2/03-access_spec.lua
spec/03-plugins/99-oauth2/04-hooks_spec.lua
spec/helpers.lua

Make Travis-CI complete its builds 🌟 . Still not 100% reliable, occasional errors can happen, but disabling non-deterministic tests, increasing some timeout values to mockbin, improving Serf error reporting etc, helps get a much more stable build.
* 🎆  improve `res_status` assertion: on HTTP 500, we tail the error log files from `servroot` to know what happened server-side
* new `serf_path` property in settings. This allows OpenResty to find the serf executable at runtime if it is not in the `sh` shell's `$PATH`, as it is the case with travis. See `./ci/run_tests.sh` where we run the tests with the `KONG_SERF_PATH` env variable for this purpose
* disable (travis only) some non-deterministic tests or tests too heavy for travis (OAuth2 access+hooks, rate-limiting access)
* disable (travis …

fix(tests) improve tests reliability for Travis-CI builds

---

kong/plugins/statsd/handler.lua
kong/plugins/statsd/schema.lua
spec/03-plugins/006-statsd/01-log_spec.lua

This PR adds upstream_latency as an option for the statsd logging plugin. 
*adds upstream_stream latency as an option for statsd, reading the value from message.latencies.proxy
*adds test for the new value

feat(plugin) Adds upstream_latency as an option to Statsd plugin

---

kong/plugins/key-auth/handler.lua
kong/plugins/key-auth/schema.lua
spec/03-plugins/02-key-auth/02-access_spec.lua

The old implementation was too cumberstone with little added benefit
(since an API key will never be searched in some other place than
querystring or headers anyways). This new one is simpler but also more
efficient because it involves fewer loops and table lookups.
* refactor key-auth access handler (perf + simpler)
* handle duplicated API keys in querystring (HTTP 401)
* add duplicate key in qs test
Fix #1462

refactor(key-auth) perf improvements + handle duplicate key in querystring

---

kong/cmd/utils/dnsmasq_signals.lua
kong/cmd/utils/nginx_signals.lua
kong/cmd/utils/prefix_handler.lua
kong/cmd/utils/serf_signals.lua
kong/meta.lua
spec/01-unit/01-rockspec_meta_spec.lua

Fix startup checks and error messages
* change -v to -V for resty check
* updated error messages for nginx executable
Fix #XXX
Not a listed issue, but fixes the check on the resty executable. The executable is checked using `-v` which always fails, it should be `-V` (capitalized)

fix (startup) fix resty check and improve nginx-check messages

---

CHANGELOG.md
kong/cmd/cluster.lua
kong/cmd/roar.lua
kong/cmd/utils/serf_signals.lua
spec/02-integration/01-cmd/01-cmds_spec.lua
spec/02-integration/01-cmd/04-reload_spec.lua

* re-enable serf error handling in 'leave',
68b79bcc4c4ea6a1ed5ad8d1828719c03a2d52e4 is disabling it at the serf
module level
* update tagline for 'kong roar'
* fix duplicated change in CHANGELOG.md

fix: changelog/kong roar/serf error handling

---

CHANGELOG.md
kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/migrations/cassandra.lua
kong/plugins/rate-limiting/migrations/postgres.lua
kong/plugins/rate-limiting/schema.lua
kong/plugins/response-ratelimiting/access.lua
kong/plugins/response-ratelimiting/migrations/cassandra.lua
kong/plugins/response-ratelimiting/migrations/postgres.lua
kong/plugins/response-ratelimiting/schema.lua
spec/03-plugins/98-rate-limiting/04-access_spec.lua
spec/03-plugins/98-response-rate-limiting/04-access_spec.lua

Renamed configuration property for the Rate-Limiting and Response Rate-Limiting plugins.
* Renamed `cluster_fault_tolerant` to `fault_tolerant`

cluster_fault_tolerant is now fault_tolerant

---

kong/dao/cassandra_db.lua
kong/dao/postgres_db.lua
kong/kong.lua
kong/plugins/correlation-id/handler.lua
kong/tools/utils.lua
spec/01-unit/04-utils_spec.lua
spec/02-integration/02-dao/04-constraints_spec.lua
spec/03-plugins/98-rate-limiting/02-daos_spec.lua
spec/03-plugins/98-response-rate-limiting/02-daos_spec.lua

relax uuid checking to fix failing migrations
- directs all uuid related calls through `tools.utils`
- replaces the tighter uuid validation with the older more permissive one
Fix uuid migration issues for release 0.9, see https://github.com/thibaultcha/lua-resty-jit-uuid/issues/8

fix(core) relax uuid checking to fix failing migrations

---

kong/dao/migrations/cassandra.lua

Fixes a formatting bug in the Cassandra migrations when starting Kong with a `NetworkTopology` and explicit `cassandra_data_centers`.
* Fixing a migration bug in Cassandra when using `NetworkTopology` and `cassandra_data_centers`.
Fix #1513.

fix(cassandra) migrations with NetworkTopology and explicit datacenters

---

kong/api/routes/plugins.lua
spec/02-integration/03-admin_api/04-plugins_routes_spec.lua

The response of `/plugins/enabled` now returns a proper JSON array. This was a bug introduced with v0.9.
* `/plugins/enabled` returns a JSON array like it did in < 0.9 and not a JSON object.

Fixing the response value of /plugins/enabled

---

CHANGELOG.md
UPGRADE.md

Hotfix to the CHANGELOG and UPGRADE documents to mention that Postgres is the new default database.
* Mentioning that PostgreSQL is the default `database` in both `CHANGELOG.md` and `UPGRADE.md`

hotfix(changelog+upgrade) postgres is the default database

---

spec/02-integration/01-cmd/02-start_stop_spec.lua

Adding test to check that both IPs and hostnames are properly supported in the DB settings when starting Kong.

tests(cli) add /etc/hosts resolving test cases for CLI

---

spec/02-integration/02-dao/02-migrations_spec.lua
spec/02-integration/03-admin_api/06-cluster_routes_spec.lua

There should not be an attempt to connect to a non-existing Postgres database because that will only result in an error. This is only supported by Cassandra.

fix(tests) do not try to get migrations from non-existing Postgres DB

---

kong-0.9.0-0.rockspec
kong/core/globalpatches.lua
kong/kong.lua
kong/tools/utils.lua

This replaces #1554, since the improved seeding technique was not an
appropriate fix. To this point, I do not think it is worth investing in such a
complex seeding technique as the root of the issue really was the 
continuous use of `math.randomseed()` by one of Lapis' utilities.
* Disable (or rather, no-op) `math.randomseed()` to prevent
third-party modules from overriding our correct seed (many modules
make a wrong usage of `math.randomseed()` by calling it multiple times
or do not use unique seed for Nginx workers.
* Bump lua-resty-jit-uuid version to include `uuid.seed()` changes
* Shorten the name of some of our cached variables
---
Update:
fix: patch math.randomseed() to prevent invalid calls  …
Patch `math.random` to prevent it from being called by another context
than init_worker, …

fix: no-op math.randomseed() once called by Kong

---

kong/plugins/acl/api.lua
spec/03-plugins/10-acl/01-api_spec.lua

Extends the ACL plugin API.
* Allows to retrieve, update or delete an ACL by group name and not just by ID.
Fix #1525

feat(acl) extended API to query by group name

---

kong/cmd/utils/prefix_handler.lua

* Handles `unlimited` ulimit and assumes a limit of `65536` when tuning nginx.
Fix #1384

fix(cli) handles unlimited ulimit

---

bin/busted
bin/kong
kong-0.9.0-0.rockspec
kong/dao/postgres_db.lua

This fixes a namespace issue where lapis' pgmoon dependency would
override Mashape's pgmoon fork source code and lead to issues as
`pgmoon.socket` would not be used properly.

fix(postgres) use pgmoon-mashape 2.0.0

---

kong/core/error_handlers.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/01-resolver_spec.lua

* Properly return the correct Kong headers on 40x and 50x errors.
Fix #1552 and #1553.

fix(core) returning appropriate headers in error pages

---

kong/plugins/basic-auth/api.lua
kong/plugins/hmac-auth/api.lua
kong/plugins/jwt/api.lua
kong/plugins/key-auth/api.lua
kong/plugins/oauth2/api.lua
spec/03-plugins/01-basic-auth/02-api_spec.lua
spec/03-plugins/02-key-auth/01-api_spec.lua
spec/03-plugins/06-jwt/02-api_spec.lua
spec/03-plugins/06-jwt/03-access_spec.lua
spec/03-plugins/09-hmac-auth/02-api_spec.lua
spec/03-plugins/99-oauth2/02-api_spec.lua

Extends the plugins API to make queries easier. The ACL plugin has been already extended with #1544.
* Extended Basic-Auth API to query credentials by `username`.
* Extended HMAC-Auth API to query credentials by `username`.
* Extended JWT API to query credentials by `key`.
* Extended Key-Auth API to query credentials by `key`.
* Extended OAuth2 API to query credentials by `client_id` and tokens by `access_token`.

feat(plugins) extended plugins API to query by specific relevant field

---

kong/plugins/galileo/alf.lua
spec/03-plugins/05-galileo/01-alf_spec.lua

ALF: Read the request/response body size from the `Content-Length` header
when logging bodies is disabled. Defaults to zero when no other option
is available.
Fix Mashape/galileo-frontend#948

fix(galileo) better req/resp body length support

---

kong/cmd/start.lua
spec/02-integration/01-cmd/02-start_stop_spec.lua
spec/helpers.lua

Stop services on failure to `start`/`restart`. 
- use an xpcall to catch errors and stop all services from there (no
error checking)
- new test for this behavior
Fix #1530

fix(cli) stop all services when Kong cannot start

---

kong/plugins/ldap-auth/access.lua

accidentally merged #1594 in `master` instead of `next`

refactor(plugin) remove usage of `error` as a variable name, as it is a global Lua function

---

kong/core/globalpatches.lua
kong/plugins/galileo/buffer.lua
kong/plugins/http-log/handler.lua
kong/plugins/ldap-auth/access.lua
kong/plugins/rate-limiting/policies.lua
kong/plugins/response-ratelimiting/policies.lua
kong/plugins/runscope/log.lua
kong/plugins/tcp-log/handler.lua

implements global patch to wrap tcp sockets `connect` function into one that resolves using the internal dns client.

patch the global tcp.connect function to use the internal dns resolver

---

kong/cmd/utils/prefix_handler.lua

In the case when `anonymous_reports=on` + `socket.toip` is not 
resolving (ex: no internet connection) Nginx would be started with an 
invalid configuration file because Kong's nginx config template would have an untouched
`${{SYSLOG_REPORTS}}` placeholder left. See `prefix_handker.lua`'s `compile_conf()` function.
This ensures that by default, some of those variables (holding the directive name + value) are at least removed from the template before starting.

fix(conf) fallback for lack of value for var placeholders

---

kong/cmd/init.lua

adds version information to the cli output on log levels `debug` (`--vv` option) and `verbose` (`--v` option)
general information provided in requests for support is usually lacking this information.

fix(cli) include version information in debug and verbose logging

---

kong/cmd/init.lua

the `--trace` is confusing as with support requests people tend to include the output, which contains very little information, where they should have included the `debug` level logging from the `--vv` option.
This drops the `--trace` option, but includes the information generated automatically in both `verbose` (the `--v` option) and `debug` (the `--vv` option)  level loggings.

fix(cli) drop the --trace option as it provides little information.

---

kong/core/globalpatches.lua

fix(globalpatches) randomseed throws error when seeded in wrong context

---

kong/plugins/oauth2/access.lua
spec/03-plugins/99-oauth2/03-access_spec.lua

Removing the word "Kong" from the error message.
* OAuth 2: Removing the word "Kong" from the error message when the `provision_key` is missing or wrong.
Related to #1617.

fix(oauth2) removing Kong from error message

---

.ci/run_tests.sh
.ci/setup_env.sh
.travis.yml

Improve the travis setup environment to have multiple cached versions of our dependencies + fix `luarocks make` step now using the new `OPENSSL_DIR` required environment variable.
* upgraded Travis-CI caching mechanism to support multiple versions
cached
* export `OPENSSL_DIR` variable for `luarocks make` install step
* bump Luarocks version in travis-ci

chore(ci) better Travis-CI setup_env.sh

---

kong/cmd/start.lua
spec/02-integration/01-cmd/02-start_stop_spec.lua

* add a check ensuring Kong (Nginx) is not running even before executing
the prefix_handler, which would maybe have consequences such as
re-generating SSL certs, or running migrations, etc...
* add a test for this behavior
* error now says "Kong is already running" instead of "Nginx is already
running", which is also probably more elegant.

fix(cli) prevent start from stopping already-running Kong

---

kong/cmd/utils/kill.lua

This would occasionally output some ungraceful "no pid file at" error to
`stderr`. Instead, we catch those and now print a proper debug log.

hotfix(cli) prevent executing 'kill' on missing pids

---

kong/api/routes/kong.lua
kong/conf_loader.lua
spec/01-unit/02-conf_loader_spec.lua
spec/02-integration/03-admin_api/01-kong_routes_spec.lua

* new `remove_sensitive()` function clones the configuration and
replaces sensitive settings with a placeholder
* unit test for conf_loader and new tests for the Admin API's `/` route

fix(api) obfuscates sensitive settings from the `/` route

---

bin/busted
bin/kong
kong-0.9.1-0.rockspec
kong/dao/cassandra_db.lua

* ensures proper usage for shm and cosocket fallbacks when outside of
ngx_lua

chore(deps) bump lua-cassandra to 0.5.4

---

kong/plugins/galileo/alf.lua
kong/plugins/galileo/buffer.lua
spec/03-plugins/05-galileo/01-alf_spec.lua

* update the code to fallback on a default value if those sizes are
still unset, rather than doing that in an `else`
* add request/response tests
* correctly log at `DEBUG` level in the buffer
Fix #1656

fix(galileo) default 'body_Size' when 'log_bodies=true' but no body

---

kong/plugins/oauth2/migrations/cassandra.lua

In Cassandra OAuth2 applications can be deleted again by creating a Cassandra index on `oauth2_authorization_codes(credential_id)`.
* Fixed an issue that prevented an OAuth2 credential to be deleted when using Cassandra.
Fix #1654.

fix(oauth2) create Cassandra index on oauth2_authorization_codes

---

kong/core/cluster.lua
kong/dao/dao.lua

* Stops propagating cluster keep-alive requests, reducing intracluster noise

fix(cluster) quiet keepalive events

---

.travis.yml
kong/meta.lua

Add OpenResty `1.11.2.1` to the range of supported versions for Kong.
* 🌠  **support for OpenResty 1.11.2.1**

chore(dep) bump OpenResty support to 1.11.2.1

---

spec/02-integration/02-dao/08-quiet_spec.lua

Complements #1660 by adding tests.

test(cluster) quiet option

---

kong/meta.lua

* Adds support for Serf 0.8
Fixes https://github.com/Mashape/homebrew-kong/issues/35

hotfix(serf) adding support for Serf 0.8

---

kong/conf_loader.lua
spec/01-unit/02-conf_loader_spec.lua

* fix a condition to prevent loading one of the default locations if a
-c flag has been given
* add a function to extend the default path, only used in tests
* new test
Fix #1675

fix(cli) honor -c flag even if config exists at default location

---

kong/conf_loader.lua

changing the order in the DEFAULT_PATHS table
/etc/kong/kong.conf is supposed to be the preferred way.
Fix #1697

fix(cli): changing the order in the DEFAULT_PATHS table

---

bin/busted
bin/kong
kong/core/globalpatches.lua
kong/dao/cassandra_db.lua
kong/kong.lua
spec/01-unit/00-globalpatches_spec.lua

This should be cleaner than relying on a global set in the resty-cli
scripts. This way, we:
- keep all interactions with _G in `kong.core.globalpatches` only
- are accurate as to how to load those patches and potentially support
other options in the future, rather than trying to detect `arg` in
`globalpatches`.

refactor(globalpatches) as a closure with options

---

kong/core/globalpatches.lua

log the issues instead of erroring out to prevent `lua_code_cache=off`
from being aborted when math.randomseed is called from defectuous
modules.
* replace `error(...)` with `ngx.log(ngx.WARN, ...)`
Fix #1716

fix(globalpatches) log seed error instead of erroring out

---

kong/cmd/utils/prefix_handler.lua

In case of admin ip changed from default.
The admin api changes are not being pushed to serf.
As the default ip (127.0.0.1) is hardcoded in the script.
* Set the new admin ip if changed from default.
Fix #1509 
Setting the admin IP if changed from default.
Fix for issue: https://github.com/Mashape/kong/issues/1509

Bug fix: Admin changes are not reflecting in proxy

---

kong/api/routes/kong.lua
kong/cmd/init.lua
kong/core/globalpatches.lua
kong/kong.lua
kong/templates/nginx_kong.lua
kong/tools/utils.lua
spec/02-integration/03-admin_api/01-kong_routes_spec.lua

**Note: this is a hotfix to be manually merged in both master and next**
This changes the seeding technique for LuaJIT's PRNG from using a
combination of `time (s precision) + worker PID` to using OpenSSL's
`RAND_bytes()`.
Reasoning: in modern deployment setups such as application containers
and AWS AMIs (etc...), it is a common practise to deploy from a forked
VM, resulting in high probability of collision for PIDs at a seconds
precision. This could result in duplicated PRNG seeds, which is
ultimately the PRNG used to generate UUIDs in Kong, by the use of
[lua-resty-jit-uuid](https://github.com/thibaultcha/lua-resty-jit-uuid).
Solution: in order to have a higher entropy when seeding LuaJIT's PRNG,
a proposed fix was to use `/dev/urandom`. This implementation however
uses OpenSSL's …

hotfix(globalpatches) use OpenSSL to seed PRNG

---

.travis.yml
kong/dao/postgres_db.lua
kong/meta.lua

* Dropping support for OpenResty 1.9.15.1
* Fixes an error in the auto-clustering event
* Adds a `DEBUG` log when clearing PostgreSQL TTLs

Dropping support for 1.9.15.1

---

kong-0.9.5-0.rockspec
kong/core/balancer.lua
kong/core/globalpatches.lua
kong/tools/dns.lua

updated dependencies after changing the dns library name.

fix(chore) change over to the renamed dns library

---

kong/core/reports.lua

* Fixed reports to send `unique_id` again.

fix(reports) send unique_id again

---

Makefile
kong-0.9.5-0.rockspec
kong/core/globalpatches.lua

The DNS branch enables the usage of cosockets in the CLI because they
can now resolve `/etc/hosts` hostnames. However, they *yield*, which is an
issue since the CLI runs inside a `xpcall` context.
* re-implement the `force_luasocket` patch for pgmoon/lua-cassandra
* re-introduce pgmoon-mashape
* proper punctuation in globalpatches docs
Fix:
```
next ⇒ KONG_DATABASE=cassandra bin/busted spec/02-integration/03-admin_api/02-apis_routes_spec.lua
✱
0 successes / 0 failures / 1 error / 0 pending : 0.010228 seconds
Error → ...lar/ngx_openresty/1.11.2.1/lualib/resty/dns/resolver.lua @ 841
suite spec/02-integration/03-admin_api/02-apis_routes_spec.lua
...lar/ngx_openresty/1.11.2.1/lualib/resty/dns/resolver.lua:841: attempt to yield across C-call boundary
```

fix: bring backcassandra usage post-dns

---

kong/dao/factory.lua
spec/02-integration/02-dao/02-migrations_spec.lua

Clean the shm after the forced failure in this test, so that the next
time we spawn a C* DAO, the shm does not contain misleading
informations about the `127.0.0.1` peer.
* fix some C* DAO tests
* fix DAO migrations error that would add twice the `[db_type error]` prefix to error messages.

tests(dao) fix some C* tests failures

---

kong.conf.default

In kong.conf.default comments, clarify purpose of cluster_listen_rpc parameter.
* kong.conf.default: clarify purpose of cluster_listen_rpc in comments
As a new kong user, I was unsure of the purpose of cluster_listen_rpc from reading the docs. After reading through the code, I'd like to submit this to make that clearer for other new users.
I'd also like to update the paragraph at https://getkong.org/docs/0.9.x/configuration/#clustering-section with the same text; I'm still looking into the best way to do so.
Thank you for taking the time to look at my request.

kong.conf.default: clarify purpose of cluster_listen_rpc

---

kong/core/handler.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/04-websockets_spec.lua

* Proxy support for Websockets.
Fix #218.

feat(proxy) supports websockets

---

kong/cmd/start.lua

The `pcall`s used to stop the services seem to inherit the errorhandler
from the `xpcall` up on the stack. This causes a recursive call if stopping the services
errors for some reason.

hotfix(cli) fix recursive calls to the startup errorhandler

---

kong/plugins/galileo/alf.lua
spec/03-plugins/05-galileo/01-alf_spec.lua

Use a workaround until https://github.com/openresty/lua-cjson/pull/16 is
included in an OpenResty formal release.

hotfix(galileo) proper empty encoding as empty arr

---

kong/plugins/oauth2/migrations/postgres.lua

* Implements a missing migration for `redirect_uri` in OAuth2 credentials
Fix #1737.

hotfix(oauth2) missing migration for postgres

---

kong/conf_loader.lua
spec/01-unit/02-conf_loader_spec.lua
spec/01-unit/03-prefix_handler_spec.lua

Ensure custom_plugins are passed from the config file to the prefix
config file, and hence down to the runtime OpenResty Kong.

hotfix(conf) load custom plugins property

---

kong/plugins/oauth2/access.lua
spec/03-plugins/99-oauth2/03-access_spec.lua

* OAuth 2 plugin now properly parses empty bodies.
Fix #1710 and #1853.

hotfix(oauth2) safely parse body even when empty

---

kong/plugins/oauth2/migrations/postgres.lua

Puts the OAuth2 Postgres migration in the right chronological order.

hotfix(oauth2) fixing postgres migration

---

kong/core/globalpatches.lua

Luassert has been fixed upstream, though unreleased. Now installing from its git repo in case this problem is hit will suffice, until the luassert fix is released.

fix(test) drop the Luassert patch. 

---

kong/core/certificate.lua
spec/02-integration/05-proxy/04-ssl_spec.lua

When Kong starts it auto-generates global SSL certificates to be used on the `proxy_listen_ssl` port. 
0.10.0 introduced a bug where the global certificate was not used anymore if an API doesn't have a specific SSL certificate configured. This PR fixes the bug.

fix(ssl) fallback on global SSL certificate

---

kong/api/crud_helpers.lua
kong/api/routes/consumers.lua
spec/02-integration/03-admin_api/03-consumers_routes_spec.lua

Fix for issue #1968 allowing username with spaces in url
Initial commit with only a test, but oddly the test passes...
on the command line I can reproduce the erroneous behaviour:
```
mashapes-mbp-2:kong thijs$ http post :8001/consumers username="bob pop"
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 16 Jan 2017 13:32:58 GMT
Server: kong/0.10.0rc2
Transfer-Encoding: chunked
{
"created_at": 1484573579000,
"id": "9fbe2f9e-42bb-4e08-87bf-e63e40151227",
"username": "bob pop"
}
mashapes-mbp-2:kong thijs$ http get :8001/consumers/bob%20pop
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 16 Jan 2017 13:33:16 GMT
Server: …
```

fix(test) fetch user by escaped username #1968

---

spec/03-plugins/99-oauth2/03-access_spec.lua
spec/03-plugins/99-oauth2/04-hooks_spec.lua
spec/helpers.lua

Most errors are fixed, but still getting;
```
[----------] Running tests from ./spec/03-plugins/99-oauth2/03-access_spec.lua
2017/01/16 11:09:51 [error] 28023#0: *2 SSL_do_handshake() failed (SSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error), context: ngx.timer
./spec/helpers.lua:225: handshake failed
./spec/helpers.lua:225: in function 'proxy_ssl_client'
./spec/03-plugins/99-oauth2/03-access_spec.lua:204: in function <./spec/03-plugins/99-oauth2/03-access_spec.lua:7>
[----------] 0 tests from ./spec/03-plugins/99-oauth2/03-access_spec.lua (2069.44 ms total)
```
Suspecting this due to the changes in ssl/tls from the new router.
@thibaultcha any hints?

fix(tests) fixed oauth2 tests failing due to merge issues

---

kong/templates/nginx_kong.lua

Not very good with the intimate details of the nginx configuration but the variable was overwritten with a bad value.
Question; are the other two values that are being set to `nil` of any value, or should they be removed to?

fix(test) websockets tests fixed, remnant of router merge

---

kong/dao/schemas_validation.lua
spec/01-unit/07-schema_validation_spec.lua

* validates timestamps to be numbers > 0
Fix #1542

fix(dao) validate timestamps, allow only positive numbers. Fixes #1542

---

kong/dao/migrations/postgres.lua
spec/02-integration/03-admin_api/03-consumers_routes_spec.lua

On postgres the field `custom_id` for `consumers` was supposed to be unique, but this was not enforced. This updates the checks and enforces it.
__NOTE__: if data is not unique before starting Kong with this fix, it will fail the migrations! so duplicates must be removed before upgrading. Hence I do not think it should be backported to the 0.9.x version, but only be applied in 0.10.x

fix(dao) enforce custom_id uniqueness

---

CHANGELOG.md
kong/core/handler.lua
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua
kong/dao/schemas/apis.lua
kong/kong.lua
kong/templates/nginx_kong.lua
spec/01-unit/08-entities_schemas_spec.lua
spec/02-integration/05-proxy/06-upstream_timeouts_spec.lua

This implements timeout options between Kong and the upstream services/APIs. It adds 3 new fields to the API definition: `upstream_connect_timeout`, `upstream_send_timeout`, and `upstream_read_timeout`.
Those fields use a ms precision, and this take an integer value between 1 and 2^31 - 1.
When not specified, the default value is `60000` (60 seconds) for all 3 fields.
* add new fields to APIs for connect/send/read timeouts
* fields are in ms precision, and must be greater than 0

feat(proxy) implement upstream timeouts

---

kong/tools/utils.lua
spec/01-unit/04-utils_spec.lua
spec/02-integration/05-proxy/04-uri_encoding_spec.lua

This is a patch that includes #1998 as well as a new integration test suite to ensure percent-encoding behavior of proxied URLs. The expected behavior is asserted in there as a source of truth.
* fix(utils) remove unescape from encode_args_value
* tests(proxy) assert URI encoding behavior in tests
Fix #1975
Ensure #749 behavior
Ensure #688 behavior
Ensure #1480 behavior
Replaces #1998

fix(proxy) prevent misinterpretation of '%' character in proxied URL encoding

---

kong/cmd/utils/serf_signals.lua

Our distributions put the `serf` executable in a known path at `/usr/local/bin/serf`. Adds this path as a known path (like we do for `resty`) when searching for Serf, if `serf_path` is not specified in the configuration file.
* Look for `serf` in known paths, if `serf_path` is not specified.
Fix #1953

fix(cli) properly look for serf in known paths

---

kong/core/balancer.lua
kong/core/handler.lua
kong/core/router.lua
kong/templates/nginx_kong.lua
spec/01-unit/12-router_spec.lua
spec/02-integration/05-proxy/01-router_spec.lua

If the host header is updated to include the port, then what is the exact desired behaviour?
So if `preserve_host` is set on the api definition, we do not touch the header at all? or do we still inject a default port if it was not in the received host header?
If we don't preserve the header, we could simply insert the upstream host and port.

fix(proxy): host header including port

---

kong/dao/db/cassandra.lua
kong/dao/migrations/cassandra.lua
spec/02-integration/02-dao/05-use_cases_spec.lua

* Pass correct local datacenter name to DCAwareRoundRobin load balancing policy
* Relax accepted names for `cassandra_data_center` config field
Fix #2056

fix(cassandra) correct some settings usage

---

kong/dao/db/cassandra.lua
kong/dao/db/postgres.lua
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua

The previous intent was to rely on a schema's default field to insert
default values for new fields. However, a `full` update means we pass a
complete row to the DAO, and that row might contain older fields. Those
fields come from the row in the DB, but **disappeared** from the schema
definition. Hence, the DAO errors on the update and complains that
fields (such as `strip_request_path`) do not exist anymore, which is
correct, according to the current API schema.
Hence, we prefer not performing full updates, and only pass a subset of
hard-coded entities' fields to `dao:update()`.
* avoid performing full updates with now non-existing fields in 
`dao:update()` from migrations

fix(migrations) avoid performing full updates

---

kong/plugins/oauth2/access.lua
spec/03-plugins/99-oauth2/03-access_spec.lua

We now use `ngx.var.uri` to check if the path segments contains (and not
if they are just *prefixed* with anymore) `/oauth2/token` or `/oauth2/authorize`.

fix(oauth2) now works with new 0.10 router

---

kong.conf.default
kong/cmd/cluster.lua
kong/cmd/utils/serf_signals.lua
kong/serf.lua
kong/templates/kong_defaults.lua
spec/02-integration/01-cmd/07-cluster_spec.lua

Exposes the underlying [`serf keys`](https://www.serf.io/docs/commands/keys.html) in Kong, to:
> perform cluster-wide encryption key operations, such as installing new keys and removing old keys. When used properly, the keys command allows you to achieve non-disruptive encryption key rotation across a Serf cluster.
* Adds a new `cluster_keyring_file` property in the configuration file.
* Exposes `serf keys ..` commands in the `kong cluster keys ..` CLI command to perform cluster-wide encryption key operations:
* `kong cluster keys list`
* `kong cluster keys install <key>`
* `kong cluster keys remove <key>`
* `kong cluster keys use <key>`

feat(cli) exposing underlying serf keys commands

---

kong/plugins/cors/handler.lua
kong/templates/nginx_kong.lua
spec/03-plugins/04-cors/01-access_spec.lua

* Properly follow the CORS specification and return `Access-Control-Allow-Credentials: false` if `Access-Control-Allow-Origin: *`

fix(cors) returning correct Access-Control-Allow-Credentials

---

spec/03-plugins/07-ip-restriction/02-access_spec.lua

Some additional tests on IP Restriction plugin trying to replicate #1995, unsuccessfully. 
Everything seems to be working fine with a `X-Forwarded-For` header.

test(ip-restriction) properly checking "X-Forwarded-For" header

---

kong/dao/migrations/postgres.lua

Signed-off-by: Wei.ZHAO <zhaowei@qiyi.com>

fix(dao): drop `hosts` instead of `headers` in postgresql migration

---

kong/cmd/init.lua

The `prng_seed` is used explicitly for the generation of UUID creation for setting the consumer ids. The consumer identifier is further used as salt value to hash the passwords in the database.
* Hides the PRNG seed from the debug logs.

chore(cli) removing sensitive PRNG seed log

---

CHANGELOG.md
kong/cmd/utils/prefix_handler.lua

* Auto-generates stronger SHA-256 with RSA encryption SSL certificates.

chore(cli) stronger auto-generated SSL certificates

---

CHANGELOG.md
kong/core/handler.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/04-ssl_spec.lua

* Dropping support for unsecure `TLS/1.0` and defaulting `Upgrade` responses to `TLS/1.2`.

chore(ssl) requiring upgrade to more secure TLS/1.2

---

kong-0.10.0rc4-0.rockspec
kong/dao/db/cassandra.lua
kong/dao/factory.lua
kong/dao/migrations/cassandra.lua

Run DDL queries from a single coordinator and only check for the schema consensus at the very end of this process. This allows for faster and more reliable migrations
* bump lua-cassandra to 1.1.1
* implement a "single coordinator" mode in the cassandra DB module
Possible fix #2063

feat(c*) run migrations from a single coordinator

---

kong-0.10.0rc4-0.rockspec

Updates dependency to fix an issue with the balancer.
Before merging:
Fix #2131

fix(balancer): update dependency to fix issue #2131

---

.luacheckrc
Makefile
kong/core/globalpatches.lua

This allows users who would rather use `luacheck .` than the `make lint`
command to do so. It also makes the linting options more obvious.
Note: In the future, re-enable white-spaces warnings.
* use `.luacheckrc` for Luacheck config options
* update Luacheck settings

chore(luacheck) use .luacheckrc + update settings

---

spec/01-unit/01-rockspec_meta_spec.lua

This test ensures that all `kong.*` modules required in all of the Kong
sources are valid Kong modules, declared in the rockspec. This will help
a lot with the file structure revamp.

tests(rock) ensure all required Kong modules are declared

---

kong/plugins/aws-lambda/handler.lua
kong/plugins/oauth2/access.lua
kong/plugins/runscope/handler.lua
kong/utils/public.lua

This call can fail in multiple ways, most notibly when the request body size is greater than client_body_buffer_size. Until a refactored plugin api is in place, we should catch errors (either Lua errors, or a returned error message from ngx).
* fix(plugins) user a sane wrapper around ngx.get_post_args
Fix #1241

fix(plugins) use a sane wrapper around ngx.get_post_args

---

CHANGELOG.md
kong/plugins/hmac-auth/daos.lua
spec/03-plugins/20-hmac-auth/02-api_spec.lua

Since the credential secret is required to compute the signature, create a random secret which will be  displayed back to the user as part of the response body.
* generate a credential secret if none provided
Fix #2143

fix(hmac-auth) generate a credential secret if none provided

---

kong/plugins/oauth2/access.lua
spec/03-plugins/26-oauth2/03-access_spec.lua

Don't try to remove credentials from request bodies when the request is a multipart upload. This prevents a thread abort when trying to index a non-existent table.
* fix(oauth2) dont try to hide credentials in a multipart req body
Fix #1952

fix(oauth2) dont try to hide credentials in a multipart req body

---

CHANGELOG.md
kong-0.10.0-0.rockspec
kong/plugins/cors/handler.lua
kong/plugins/cors/migrations/cassandra.lua
kong/plugins/cors/migrations/postgres.lua
kong/plugins/cors/schema.lua
spec/03-plugins/14-cors/01-access_spec.lua

Updated PR to handle multiple origins in the CORS plugin.
* rename `origin` to `origins`, which allows a list of origins
* provide migrations for this change (missing fro m#1973)
* rebase #1973 on top of the current master and fix tests
* fix #1973 to also handle `*` being configured for `conf.origins` and `Allow-Credentials`
* use the PCRE API from ngx.re
* minor style updates
* minor perf updates
Replace #1774
Replace #1973
Fix #1043

feat(cors) allow for multiple origins

---

kong-0.10.0-0.rockspec

The multipart header whitespace was obligatory, and now is optional
fixes: https://github.com/Mashape/lua-multipart/issues/9

fix(deps): updated lua-multipart to 0.5 for a bugfix

---

kong/templates/nginx_kong.lua

* Also disables `TLS/1.0` on the Admin API

hotfix(admin-api) disable TLS/1.0

---

kong/cmd/utils/serf_signals.lua

generating the error message concatenated a table by omitting a `tostring()` call.
Fix #2217

fix(cli): fixes bad error message on missing serf

---

kong/conf_loader.lua
spec/01-unit/02-conf_loader_spec.lua
spec/fixtures/to-strip.conf

Properties like:
value = a,  b  , c
...used to yield non-trimed values in the resulting array. We now trim such
values when parsing the config file.

fix(conf) strip/trim specified list values

---

kong/core/plugins_iterator.lua
kong/plugins/acl/handler.lua
kong/plugins/basic-auth/access.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/access.lua
kong/plugins/oauth2/access.lua
kong/tools/database_cache.lua
kong/tools/utils.lua
spec/01-unit/04-utils_spec.lua
spec/01-unit/11-database_cache_spec.lua

Main cause is exiting early on error conditions, when the lock has not
yet been released. It occurs both in the `get_or_set` method itself as
well as in the callbacks all over the code base.
Fix #2186

hotfix(cache): removes deadlocks when cache callbacks error

---

spec/02-integration/05-proxy/01-router_spec.lua
spec/fixtures/custom_nginx.template
spec/helpers.lua

We'd rather not depend on any third-party service for testing such a
behavior since `preserve_host` typically creates invalid HTTP requests
to upstream services.
Here we introduce custom Nginx locations that allow us to mimic (and
improve) httpbin.org behavior locally. The long term goal is to
transition all of the tests relying on httpbin.org to such local code,
so this is a step forwards, regardless of the testing framework or Nginx
configuration handling we might have in the future.

tests(proxy) rewrite preserve_hosts suite

---

kong/plugins/ldap-auth/schema.lua

Adds the `no_consumer` flag to the ldap plugin.
Fixes #2235

fix(plugin): adds the 'no-consumer' flag to the ldap plugin schema

---

kong/api/init.lua
spec/02-integration/03-admin_api/01-kong_routes_spec.lua

* Fixes an edge-case when requesting the Admin API with an invalid method

hotfix(admin-api) fixes an edge-case and returns 405 on invalid methods

---

kong.conf.default

the actual defaults had no passwords set for neither Cassandra nor Postgres,
yet the template config file had them both set to `kong`.
fixes #2254

fix(config): align template config file with actual defaults

---

kong/cmd/migrations.lua

**Note: new features are to be opened against next, hotfixes against master.**
Migrations will fail during the upgrade process to 0.10.0 with the following error:
```
Error: 
/usr/local/share/lua/5.1/kong/dao/dao.lua:80: attempt to index field 'TYPES' (a nil value)
/usr/local/share/lua/5.1/kong/dao/dao.lua:80: in function 'event'
/usr/local/share/lua/5.1/kong/dao/dao.lua:302: in function 'update'
/usr/local/share/lua/5.1/kong/dao/migrations/postgres.lua:359: in function 'up'
/usr/local/share/lua/5.1/kong/dao/factory.lua:232: in function 'migrate'
/usr/local/share/lua/5.1/kong/dao/factory.lua:288: in function 'run_migrations'
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: in function 'cmd_exec'
/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function …
```

Fix DAOFactory usage in the migration command

---

kong/tools/database_cache.lua

As the intent is to replace the caching all together, I did not make its size configurable
See code comments on some rough calculations. Configurability can be added if required, feedback welcome

fix(cache): replace in-memory table with an lru-cache to limit memory consumption

---

kong/plugins/aws-lambda/schema.lua

Hello
Lambda plugin is not supported in us-west-2. Is there any specific reason for this limitation.
Will this region be supported in near future.
Thanks
Steps To Reproduce
Create a pi and attach a lambda plugin. In the configuration when i mention us-west-2 i get a error that region is not supported.
Additional Details & Logs
Kong version (0.10.0)
Operating System : Centos

Lambda support for us-west-2 #2257

---

spec/02-integration/05-proxy/01-router_spec.lua

When we don't route an API via its `hosts` property (no Host recorded),
this test ensures that we still forward the incoming request `Host`
header when `preserve_host = true`.

tests(router) ensure preserve_host without hosts matching

---

kong/core/router.lua
spec/01-unit/11-router_spec.lua

We now avoid reading all request headers via `ngx.req.get_headers()` and
use the `ngx.var` API instead. In the future, we'll distinguish Host
fetching and full headers fetching when arbitrary headers matching will
be added to the router.

perf(router) efficient host header reading

---

spec/03-plugins/23-aws-lambda/01-access_spec.lua

The lambda environment needs to warm up, the initial request may be very
slow. This occasionally causes timeouts on the tests, which then fail.

test(lambda): add an initial request to prevent timeouts in testing

---

kong/api/crud_helpers.lua
kong/api/routes/upstreams.lua
spec/02-integration/03-admin_api/09-targets_routes_spec.lua

* Extends the sugar `DELETE` method for upstream targets, allowing them to be deleted by `id` as well.

feat(admin) targets can be deleted by their ID

---

kong/plugins/hmac-auth/access.lua
spec/03-plugins/20-hmac-auth/03-access_spec.lua

We don't need to try to compare against an empty string.
Additionally, remove the needless length comparison. This was bugged
to begin with, but the length comparison is needless, and doing so
removes the constant time factor from this function.

fix(hmac) handle invalid Base64-encoded signatures

---

kong/api/routes/upstreams.lua
spec/02-integration/03-admin_api/09-targets_routes_spec.lua

Previously we defined active upstream targets as any target with
a nonzero weight. This definition was properly implemented, but
caused confusion. As such, we redfine 'active targets' to be the most
recent entry of each nonzero target. This presents a more accurate
picture of the targets currently in use by the balancer.
Fix #2306.

hotfix(upstream) display active targets based on proper definition

---

kong/cmd/utils/kill.lua
spec/02-integration/03-admin_api/06-cluster_routes_spec.lua
spec/02-integration/04-core/02-hooks_spec.lua
spec/03-plugins/09-galileo/ngx.lua
spec/03-plugins/24-rate-limiting/04-access_spec.lua
spec/03-plugins/25-response-rate-limiting/04-access_spec.lua

Right now we suggest compiling OpenResty with `--without-luajit-lua52` (or LuaJIT without `-DLUAJIT_ENABLE_LUA52COMPAT`). All the official OpenResty packages compile LuaJIT with Lua 5.2 compatibility, and we should follow the suit.
Also it looks like some of the tests were using `os.execute("sleep ...")` instead of `ngx.sleep(...)`. This pull-request fixes that as well.

fix(*) replace os.execute calls with Penlight execute / ngx.sleep

---

kong/api/routes/certificates.lua
kong/dao/schemas/ssl_servers_names.lua
spec/02-integration/03-admin_api/07-certificates_routes_spec.lua

Previously, if a duplicate sni was detected as part of the 'snis'
sugar param, we still created the certificate object, as well as
any previously non-existant sni encountered before the conflicting
element. This commit prevents creation of orphan entries by checking
for the existence all posted snis before creating the certificate
and sni objects.
This commit also cleans up the naming schemes for admin API certificate
routes integration tests (no functional change).
Fixes issue #2275, among other behavioral inconsistencies.

fix(sni) stricter detection and handling of duplicate snis

---

kong/conf_loader.lua
kong/templates/nginx.lua
spec/01-unit/02-conf_loader_spec.lua
spec/01-unit/03-prefix_handler_spec.lua
spec/fixtures/custom_nginx.template

The PR #2311 introduced Nginx `user` directive defaults with values `nobody nobody`. While this may work with `root` user, it gives a warning with normal user:
```
2017/04/03 13:23:54 [warn] 8249#0: the "user" directive makes sense only
if the master process runs with super-user privileges,
ignored in /usr/local/kong/nginx.conf:1
```
This patch fixes the #2311 so that we do set the defaults only if `Kong` is started as a `super-user`.

fix(conf) the "user" directive makes sense only if the master process runs with super-user privileges

---

kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua

replaces #2266, this goes against `next`
The default value for anonymous == "", yet the migrations were missing
fixes #2264 but for all auth plugins.

hotfix(migrations): set default for anonymous with auth plugins

---

kong/kong.lua

The `kong.tools.responses` module sends a body with `ngx.say` when
calling `responses.send_HTTP_SERVER_ERROR()`. This produces an error on
top of a previous error, as in:
```
2017/04/03 23:42:00 [error] 11076#0: *29 [lua] kong.lua:239: balancer(): failed to set the current peer (address:'2400:cb00:2048:1:0:0:681c:767' port:80): invalid port while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /status/200?apikey=secret123 HTTP/1.1", host: "acl_test1.com"
2017/04/03 23:42:00 [error] 11076#0: *29 failed to run balancer_by_lua*: ...he/luarocks-2.4.2/share/lua/5.1/kong/tools/responses.lua:127: API disabled in the context of balancer_by_lua*
[C]: in function 'say'
...he/luarocks-2.4.2/share/lua/5.1/kong/tools/responses.lua:127: in function 'balancer' …
```

fix(balancer) do not send body from balancer ctx

---

kong/core/router.lua
spec/01-unit/11-router_spec.lua
spec/02-integration/05-proxy/01-router_spec.lua

The router avoids grabbing the headers if not absolutely necessary (at
least one API configured with a `hosts` rule. This caused an edge-case
and mislead the router into believing the headers were already grabbed,
and returned a `nil` value instead of the request's Host header.
* add a unit test case
* add an integration test case, although more generic
* use the `ngx.var.http_*` API to grab the request's Host

fix(router) ensure preserve_host when no `hosts`

---

kong/core/router.lua
spec/01-unit/11-router_spec.lua

When a request URI is matching (as a prefix) the `uris` of several APIs, but
other properties (say, `hosts`) differ, there was a possibility of
running into an edge-case, and try to match APIs with values of another
API. Doing so would result in a miss, and not return any API.
* fix edge-case
* simpler de-normalization logic when possible.
* simpler matching logic with updated reducer returning all APIs
for a category as well as a minimalistic plain subset.
* use `ngx.re.find` instead of `ngx.re.match` when searching for hosts
wildcard matching when categorizing.
* update variable names for clarifications
* some more comments to detail the logic
Fix #2334

fix(router) handle a matching edge-case with uris

---

CHANGELOG.md
kong/tools/utils.lua
spec/01-unit/04-utils_spec.lua
spec/03-plugins/10-key-auth/01-api_spec.lua

There is no incentive for Kong to not allow a header name containing an
underscore. This reverts the change in behavior introduced in #2142
and 73437ef01d1514492fd645f1e9e04a74776878eb.
The `underscores_in_headers` directive seems to already be enabled.

feat(key-auth) allow underscore in key header name

---

CHANGELOG.md
kong/kong.lua
kong/plugins/log-serializers/basic.lua
spec/01-unit/13-log_serializer_spec.lua

* Logging plugins now also log the authenticated consumer

feat(log) logs the authenticated consumer

---

kong/cmd/utils/prefix_handler.lua
spec/01-unit/03-prefix_handler_spec.lua

If you have this in your custom nginx template:
```nginx
resolver ${{DNS_RESOLVER}} ipv6=off;
```
It will yield an error. This PR fixes the issue by transforming
the `dns_resolver` from `table` to `string` for template usage.
Fix #2319

hotfix(conf) convert custom nginx conf dns_resolver to string

---

CHANGELOG.md
kong/api/crud_helpers.lua
kong/plugins/acl/api.lua
kong/plugins/basic-auth/api.lua
kong/plugins/hmac-auth/api.lua
kong/plugins/jwt/api.lua
kong/plugins/key-auth/api.lua
kong/plugins/oauth2/api.lua
spec/02-integration/03-admin_api/03-consumers_routes_spec.lua

when the name/key/whatever field is formatted as a uuid Kong
would assume that field to be the `id` field. This change will
make it first try the `id` field in that case, and then the
alternative field.
Fixes #2415

fix(api) lookup entities by secondary field as uuid

---

CHANGELOG.md
kong/core/plugins_iterator.lua
spec/02-integration/05-proxy/03-plugins_triggering_spec.lua

Credentials will not always be set, hence the iterator should base
itself on the consumer id set.
fixes #2414

fix(proxy) iterator to act on consumer, not on credential

---

CHANGELOG.md
kong/plugins/http-log/handler.lua
spec/03-plugins/03-http-log/01-log_spec.lua

feat(http-log) Add basic auth header if credentials provided

---

CHANGELOG.md
kong/kong.lua
kong/plugins/log-serializers/basic.lua
spec/01-unit/13-log_serializer_spec.lua

The number of tries will be logged in the basic serializer. If any retries occurred, then failure information will be added as well.

feat(log) add balancer tries and failure information

---

CHANGELOG.md
kong-0.10.1-0.rockspec

Fixes an issue with the dns resolver not properly caching CNAME records.
fixes #2303

chore(deps) updates dns resolver dependency to 0.4.1

---

CHANGELOG.md
kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/schema.lua
kong/plugins/response-ratelimiting/header_filter.lua
kong/plugins/response-ratelimiting/schema.lua
spec/03-plugins/24-rate-limiting/04-access_spec.lua
spec/03-plugins/25-response-rate-limiting/04-access_spec.lua

**Summary**
Add a config option to the rate-limiting and response-ratelimiting plugins to not send the rate-related headers (limit and remaining) normally sent to the client. For publicly exposed APIs, this can be useful for security.
**Full changelog**
- Add boolean config option hide_client_headers
- Add related tests

feat(rate-limiting,response-ratelimiting) optionally hide client headers

---

CHANGELOG.md
kong/plugins/jwt/handler.lua
spec/03-plugins/17-jwt/03-access_spec.lua

On invalid claims the JWT plugin returned `403 forbidden` instead
of the `401 unauthorized`.
fixes #2409

fix(jwt-auth) return 401 unauthorized instead of 403

---

CHANGELOG.md
kong/plugins/file-log/handler.lua
kong/plugins/file-log/schema.lua
spec/03-plugins/04-file-log/01-log_spec.lua

A new boolean property `no_cache_fd` determines whether cache the open descriptor in
memory, or to open and close the file on each invocation. By default this value is false, resulting in no change to default behaviors.
Fix #2325

fix(file-log) add option to not cache fd

---

kong/plugins/hmac-auth/access.lua

This (partially) reverts commit f5010994b9b921d799504a46a0f8d1817d656f5c.
The initial premise upon which this commit was built is incorrect;
Lua's interning of strings always means that EQ operators are constant
time. Given this, we don't need to place additional stress on the Lua
VM by creating unique string objects for each character in the client
header.

perf(hmac) use a simpler comparison for signature validation

---

kong/plugins/cors/handler.lua
spec/03-plugins/14-cors/01-access_spec.lua

Access-Control-Allow-Credentials used to systematically be set to
`false` if ACAC was `*`.
However, `false` is an invalid value for ACAC, which only accepts
`true`, and ACAO cannot be `*` when credentials are desired.
* if credentials are desired, ACAO will be set to the request's Origin
* ACAC never received `false` anymore
* tests from @thefosk in #2243, plus one more to ensure port is
included in ACAO if present in the request's Origin.
Replace #2243

fix(cors) proper handling of the ACAC header

---

kong/templates/nginx_kong.lua

Remove the ACAC header set to `false` in the Admin API.
This raises an interesting concern about the Admin API: we do not allow
requests with credentials to be made to it (since ACAC is not sent with
`true`). This might warrant an update and some testing in the future.

fix(admin) CORS ACAC header cannot receive false

---

kong/dao/schemas/upstreams.lua
spec/02-integration/03-admin_api/08-upstreams_routes_spec.lua

DELETE against upstream objects is currently broken when using cassandra because the schema defines the primary key as `{id, name}` but both postgres and cassandra schemas actually define their PK with `id`. this causes failures because cassandra tries to delete against a non PK column.
* correctly enumerate daos in upstream integration tests
* make Kong and DB schemas consistent
Fix #2358

fix(upstream) proper primary_key in kong schema

---

kong/dao/migrations/postgres.lua
kong/dao/schemas/plugins.lua
spec/02-integration/03-admin_api/02-apis_routes_spec.lua

The compound primary key, coupled with a lack of unique constraint
on id, allows for duplicate plugin UUIDs, breaking expected behavior.
This commit adds a unique constraint in the Kong schema, and directly
to the Postgres table definition via a migration.
* fix(plugins) add unique constraint to id field
Fix #2227

fix(plugins) add unique constraint to id field

---

kong/core/error_handlers.lua
kong/templates/nginx_kong.lua
spec/fixtures/custom_nginx.template

In addition to BAD_REQUEST messages sent by Kong, we should also
handle natively-generated 400 response codes.
* handle native 400 response codes
Fix #1816, #2085

feat(core) handle native 400 response codes

---

kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua
spec/03-plugins/24-rate-limiting/04-access_spec.lua
spec/03-plugins/25-response-rate-limiting/04-access_spec.lua

* Rate Limiting and Response Rate Limiting: properly selects the Redis Database (if not `0`) when retrieving counters if the `config.policy=redis`.

hotfix(rate-limiting) properly use the selected Redis database

---

spec/03-plugins/24-rate-limiting/04-access_spec.lua

* Compare a table against JSON, and not the encoded JSON string.
* Ensure Kong is restarted when adding APIs to it due to the recent router changes in the 0.10 family.

tests(rate-limiting) fix a couple of tests

---

kong/plugins/oauth2/daos.lua
kong/plugins/oauth2/migrations/postgres.lua
spec/03-plugins/26-oauth2/02-api_spec.lua

Remove the unique constraint on client_secret in the oauth2_credentials table. There appears to be no need to hold this constraint; indeed, no other authentication plugins take this approach (apart from JWT, which builds logic around maintaining a unique key).
* remove unique constraint on client_secret
Fix #1972

fix(oauth2) remove unique constraint on client_secret

---

kong/plugins/log-serializers/basic.lua
spec/01-unit/13-log_serializer_spec.lua

if the `ngx.ctx.balancer_address` structure was missing the basic
serializer would fail.
```
2017/05/10 15:33:42 [error] 14766#0: *98833 failed to run log_by_lua*: ...cal/share/lua/5.1/kong/plugins/log-serializers/basic.lua:28: attempt to index local 'addr' (a nil value)
...cal/share/lua/5.1/kong/plugins/log-serializers/basic.lua:28: in function 'serialize'
/usr/local/share/lua/5.1/kong/plugins/file-log/handler.lua:76: in function 'log'
/usr/local/share/lua/5.1/kong.lua:321: in function 'log'
log_by_lua(nginx-kong.conf:109):2: in function <log_by_lua(nginx-kong.conf:109):1> while logging request, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "localhost:8000"
```

fix(serializer) stop failing on missing structure

---

kong/plugins/basic-auth/access.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/access.lua
kong/plugins/oauth2/access.lua

This PR deals with an error caused by the missing migrations file (fixed in https://github.com/Mashape/kong/pull/2313) without implementing the missing migration. 
It prevents returning a `500` error on an invalid credential when `conf.anonymous=nil`.
This can be merged as a hotfix so it can land in a minor release, and reverted back in the next major since https://github.com/Mashape/kong/pull/2313 already takes care of it.
* Fixes a bug that triggered `500` errors when an invalid credential is being sent.

hotfix(auth) handle nil anonymous consumers

---

kong/plugins/cors/handler.lua
spec/03-plugins/14-cors/01-access_spec.lua

This fixes a regression introduced in 0.10.1, where the migration would
set the new `conf.origins` field to an empty table, but the code would
only set `*` if the table was `nil`, and not empty.
We are reluctant to update the migration due to the immutable nature
that they should carry (in order to avoid divergence between users who
already ran them, and users who will run it after this patch), so this
changes the business logic to be more robust instead, which we probably
want anyways.
This regression was documented post-release, in #2517.
* handle empty `config.origins` in the CORS ACAO business logic
* regression test
Relates to #2517

fix(cors) send '*' in ACAO when 'conf.origins' is empty

---

kong/plugins/cors/handler.lua
kong/plugins/cors/schema.lua
spec/03-plugins/14-cors/01-access_spec.lua
spec/03-plugins/14-cors/02-schema_spec.lua

Use the ngx.re API to match configured origins as regular expressions against the client Origin header. In cases where a single origin is configured for the plugin, set the ACAO header based on the plugin configuration if the configuration contains only non-PCRE metacharacters; otherwise, treat the single configured origin as a though multiple origins were configured, by iterating through the array and setting the ACAO header based on the client Origin.
This changeset will be accompanied by a sister PR that includes a migration of existing configured `origins` to escape `.` characters. Because such a migration will target Kong 0.11, and this PR targets Kong 0.10.3, we will commit these as separate PRs.
* Examine the client Origin header against configured `origins` as a full expression
* …

feat(cors) match configured origins as a regular expression

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/policies/cluster.lua
kong/plugins/rate-limiting/policies/init.lua
spec/03-plugins/24-rate-limiting/02-policies_spec.lua
spec/03-plugins/25-response-rate-limiting/02-policies_spec.lua

* Rate-Limiting: performance improvements to only increment the configured limits, and not all of them.
Notes: the same patch will have to be applied to the Response Rate Limiting plugin in a separate PR.

perf(rate-limiting) only increment configured limits

---

kong/plugins/aws-lambda/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/oauth2/access.lua
kong/plugins/runscope/handler.lua
kong/tools/public.lua
spec/03-plugins/10-key-auth/02-access_spec.lua

This commit expands the functionality of the request body reader convenience function to return a table of args for JSON, multipart, and form body requests. It also refactors away several existing duplicate implementations.
* Implement multipart and JSON readers in `kong.tools.public`
* Update tests for key-auth plugin to examine all three content types
* Update oauth2 and lambda plugins to remove duplicate code patterns

refactor(utils) clean up and flesh out body args reader

---

kong/plugins/file-log/handler.lua

write() takes a constant pointer as the source buffer, and open() takes a constant pointer as the filename, which means we can avoid the overhead of casting from a string to a char buffer.
* update write() and open() cdef signatures
* remove `string_to_char` and its callers

perf(file-log) use the proper libc signatures

---

kong/plugins/ip-restriction/handler.lua

Using the binary representation of the address (e.g. via ngx.var.binary_remote_addr) is a more efficient approach, as we no longer need to rely on a small LRU cache to store binary-parsed CIDR and IP objects. To achieve this, we rely on a read-through module-level cache of parsed CIDR objects to call iputils.binip_in_cidrs directly; parsed CIDRs objects by definition are consistent, so we needn't worry about cache invalidation here.
This is still not an optimal approach, as the cache function still builds a new table on each execution. Ideally we would cache the entirety of this function as a single table; the trick here is defining the cache key. The speediest cache key would be a pregenerated string (such as a UUID) associated with the plugin object, but this would require a migration …

perf(ip-restriction) faster iputils checking

---

kong-0.10.2-0.rockspec
kong/dao/db/cassandra.lua

Set LuaSocket's `cafile` option when we are in a context that does not
support cosockets.
Fix #2528
See thibaultcha/lua-cassandra#95

fix(c*) pass lua_trusted_ssl_cert to lua-cassandra

---

kong/plugins/jwt/daos.lua
kong/plugins/jwt/migrations/postgres.lua
spec/03-plugins/17-jwt/02-api_spec.lua

Remove the unique constraint from `jwt_secrets.secret`. This constraint was applied when the plugin was initially introduced; it does not provide any use.
* Remove unique constraint from `jwt_secrets` DAO.
* Remove unique constraint from Postgres schema.
* Add test allowing duplicate secrets.
Fix #1512

fix(jwt) remove unique constraint on secret

---

.travis.yml

This requires cleaning of the Travis cache.

chore(ci) bump OpenSSL to 1.0.2l

---

CONTRIBUTING.md

A more welcoming contributing guide, addressed to both members of the
community (technical or not, seeking for help or to contribute), and new
hires.
This includes an updated code style, an FAQ about which channels to
communicate on, a contributing guide with guidelines for good commit
messages and overall healthy contributions.
This replaces #2253 which became style, and introduces a new, undesired
`CODE_SYLE.md` file.

docs(contributing) revamp with code style

---

kong/api/routes/kong.lua
kong/dao/db/cassandra.lua
kong/dao/db/postgres.lua
spec/02-integration/03-admin_api/01-kong_routes_spec.lua

This is a replacement proposal for #2554. As discussed, the point of this change is to provide a connection test to the database, and not to evaluate its health. Following this logic, this patch is more aligned with the intended goal.
cc @shashiranjan84 @p0pr0ck5 @thefosk

feat(admin) remove DB counters in favor of a connection test

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Following the recent improvements in the CONTRIBUTING.md guidelines, we
can update those templates to:
- better redirect contributors to meaningful resources
- shorter and thus more susceptible to actually be read by contributors
- not use a Markdown syntax which isn't supported in the issue
composition text field

chore(gh) Improve GitHub issue/PR templates

---

kong-0.10.3-0.rockspec
kong/plugins/file-log/handler.lua
kong/tools/utils.lua
spec/01-unit/04-utils_spec.lua
spec/03-plugins/04-file-log/01-log_spec.lua
spec/03-plugins/05-syslog/01-log_spec.lua
spec/03-plugins/17-jwt/02-api_spec.lua

The current implementation of utils.random_string() leverages the LuaJIT math.random() under the hood to generate bytes; this is unsuitable for cases where cryptographically secure random data is needed, such as fallback values for authentication plugin secret values. To correct this, we introduce a wrapper around the kernel CSPRNG (via /dev/urandom) to read random bytes, and wrap utils.random_string around this. We also return these bytes in a modified Base64 encoding (replacing non-alphanumeric characters with random alphanumeric replacements); this serves to increase the size of the keyspace significantly while attempting to maintain some backwards compatibility with previous generated string
parameters (e.g. by generating a string of the same size and a somewhat matching pattern).
The …

feat(utils) generate random strings via CSPRNG

---

CONTRIBUTING.md

Fix typo in code style content for variables defined in uppercase
* Fix typo in CONTRIBUTING.md

docs(contributing) fix typo in code style section

---

kong/plugins/aws-lambda/handler.lua
kong/plugins/aws-lambda/schema.lua
spec/03-plugins/23-aws-lambda/01-access_spec.lua
spec/03-plugins/23-aws-lambda/02-schema_spec.lua
spec/fixtures/custom_nginx.template

This is a feature request for the Kong aws-lambda plugin. The use case is for allowing users to set a custom response code for APIs they've configured. AWS Lambda's Invoke call returns a 20x code regardless of whether an error occurred. This supports configuring a different response code via the API.
Adds a new `unhandled_status` configuration option for the aws-lambda
plugin. If set - when the [`X-Amzn-Function-Error`](http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseSyntax) invoke call response
header is set to `Unhandled` then the numeric value will be used as the
response code for the API.
* Add support to override response code for unhandled exceptions via `unhandled_status`.
* Updated spec for usage without `unhandled_status`.
* Added specs for …

feat(aws-lambda) Add support for setting a custom response code

---

kong-0.10.3-0.rockspec
kong.conf.default
kong/conf_loader.lua
kong/core/balancer.lua
kong/templates/kong_defaults.lua
kong/tools/dns.lua
spec/01-unit/02-conf_loader_spec.lua

implements search and ndots options from in the dns resolver.
additionally makes some more options configurable
Fixes #2201
- Waits for the new dns resolver lib version (0.5) to be released.
- the new `ttl` settings are in `seconds` aligned with existing `ttl` settings (as opposed to `timeout` settings which all are in `milliseconds`)

feat(resolver) implements search and ndots options

---

kong/meta.lua
spec/01-unit/01-rockspec_meta_spec.lua

To enable release suffix that are not necessarily pre-releases, ie `enterprise`.

refactor(meta) pre_release becomes suffix

---

spec/03-plugins/24-rate-limiting/04-access_spec.lua

When errors happen in this test suite, another errors supersedes it
because of the wrong usage of `error()` and its second argument.

tests(rate-limiting) proper usage of error()

---

kong/cmd/utils/prefix_handler.lua

Because Kong automatically (re)creates this file, we should be define a more restrictive permissions set. Note this is related specifically to the Kong environment file, _not_ the kong.conf user-defined config file (control of which is the responsibility of the system administrator).
* Set user read-write, group read, and other none permissions on `.kong_env`
Addresses some concerns in #1806

fix(core) explicitly set kong env as user read only

---

kong/core/handler.lua
kong/core/router.lua
kong/templates/nginx_kong.lua
spec/01-unit/11-router_spec.lua
spec/02-integration/05-proxy/01-router_spec.lua
spec/02-integration/05-proxy/07-uri_encoding_spec.lua
spec/fixtures/custom_nginx.template

Since `ngx.req.set_uri` will make Nginx's proxying escape the upstream URI, we do not use this API anymore. As it was the case prior to Kong 0.10, we go back to inlining an Nginx variable containing the desired, plain URI, and thus ensure Nginx will not unconditionally percent-encode before proxying.
* The router now returns a 4th value: the URI to use for the upstream
call.
* The `proxy_pass` directive now inlines a new `$upstream_uri` variable
which contains a raw string with both the Nginx `$request_uri` and
`$args` variables.
* Update the router value return test
* New test to ensure we proxy the request's querystring
* New regression test to ensure we do not double percent-encode request
URIs.
* simplify URI stripping logic
Fix #2512

fix(router) ensure transparent proxying of URIs

---

kong/plugins/hmac-auth/access.lua
kong/plugins/hmac-auth/schema.lua
spec/03-plugins/20-hmac-auth/03-access_spec.lua

This PR adds additional request body validation along with existing
headers validation. The motivation behind request body validation
is to detect body tampering. But as the validation process requires
to read the whole body in memory, which can affect Kong's
performance, this feature is disabled by default. User can change
the default behavior using config `validate-request-body`.
if config `validate-request-body` is set to `true`, validate request
body along with headers validation. If it is `false`, perform only
headers validation.
* Added new config `validate-request-body` to schema. 
* Logic added to validate `digest` header value. 
* Added tests test `digest` validation logic.
Note: This PR is based of #2419 with some code refactoring.

feat(hmac) Implement request body validation

---

kong/core/handler.lua
kong/plugins/oauth2/access.lua
kong/tools/utils.lua
spec/01-unit/04-utils_spec.lua
spec/02-integration/05-proxy/05-ssl_spec.lua
spec/03-plugins/26-oauth2/03-access_spec.lua

We now only examine the X-Forwarded-Proto header if we have defined the connecting client as a trusted IP.
* `kong.tools.utils.check_https` now accepts a boolean derived from `singletons.ip.trusted` to determine how it should examine `X-Forwarded-Proto`.
* Untrusted clients sending `X-Forwarded-Proto: https` via a plaintext connection are denied with 426 when the selected API has `https_only` set.
* Oauth2 plugin SSL requirements leverage the trusted_ips / X-F-P logic.
* Updated various tests to define 127.0.0.1 as a trusted IP.
Tangentially references #2583.

fix(proxy) check_https respects trusted_ips

---

kong/dao/schemas/apis.lua

Assume a (very mildly) more agressive posture by disabling interpretation of the X-Forwarded-Proto header in HTTPS-only APIs by default when the client sent a plaintext connection. This does not improve any functional posturing in the analysis of plaintext connections, but it does require that operators explicitly set this value (and thus assumedly understand the current implications of such a configuration)
* Set the `http_if_terminated` API schema member to false by default.
Fix #2583

fix(proxy) set http_if_terminated false by default

---

spec/02-integration/05-proxy/01-router_spec.lua
spec/02-integration/05-proxy/07-uri_encoding_spec.lua

httpbin.org generates the "url" portion of the response seemingly from magic (actually, we assume from a combination of the Host/X-Forwarded-Host headers). Router tests that leveraged this response field are updated to examine only the path portion of the resource, as the introduction of X-Forwarded-Host handling, combined with Nginx's internal "host" variable, broke several assumptions about httpbin's response.
The nature of the router strip_uri tests is such that we need to define a separate negative assertion to confirm the strip behavior, as we can no longer rely on the anchoring that the host portion of the "url" field provided (compared with the affected URI encoding tests, which only examine encoding behaviors of unstripped portion of the request line).

tests(router) check only the request line portion of the url

---

spec/02-integration/05-proxy/08-websockets_spec.lua

Since sockb.in appears to be offline, we'll need to find a way to test
WebSocket proxying support differently.
- Use another service
- Spawn our own sockb.in instance on Heroku
- Compile our test Nginx with the stream module for local testing
(ideal)

tests(websocket) set suite to pending

---

kong/api/routes/upstreams.lua

When no active upstreams are present, the 'data' response field should be an empty list, not an object
* Define `data` as a cjson empty_array when no active targets are found.
Fix #2618

fix(admin) fix data format for empty upstreams array

---

spec/02-integration/05-proxy/04-dns_spec.lua

fixes the test that commonly fails in ci to take a bit more time to start the test server.

fix(test) dns-retries test

---

kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua

dict:incr() takes a third param 'init', and always sets the expire time of node entries to 0, so the initial call to dict:add() is useless
* Replace `add` and `incr` calls with a single `incr` with init value.

perf(ratelimiting) reduce the number of shm accesses in increment

---

kong-0.10.3-0.rockspec
kong.conf.default
kong/conf_loader.lua
kong/templates/kong_defaults.lua
kong/tools/dns.lua

updates the dns lib to 0.6.0, adds the new `dns_stale_ttl` option.

chore(deps) Update dns dependency and options

---

kong-0.10.3-0.rockspec
kong.conf.default
kong/conf_loader.lua
kong/templates/kong_defaults.lua
kong/tools/dns.lua
spec/01-unit/002-conf_loader_spec.lua

allows the nameservers to be configured in both `ipv4` and `ipv6` format. And if the `/etc/resolv.conf` file contains `ipv6` nameserver entries, they will be used as well.
Fixes the _"Error: Invalid configuration, no dns servers found"_ error on systems with only `ipv6` nameservers configured.
(this builds on top of PR #2625 )

allow ipv6 nameservers

---

kong-0.10.3-0.rockspec
kong/plugins/statsd/handler.lua
kong/plugins/statsd/migrations/cassandra.lua
kong/plugins/statsd/migrations/postgres.lua
kong/plugins/statsd/schema.lua
kong/plugins/statsd/statsd_logger.lua
spec/03-plugins/06-statsd/01-log_spec.lua
spec/03-plugins/06-statsd/02-schema_spec.lua

- Now each metric supports configurable stat type,
sample rate and customer identifier if applicable.
- Custom prefix for stats's name
- New metrics `upstream_latency`, `kong_latency` and `status_count_per_user`.
- Schema updated to support new metrics
- Schema updated to support `stat_type`, `sample_rate` and `consumer_identifier`
- Added new schema checks and test 
FIX #1533
NOTE: depends on the PR on https://github.com/Mashape/kong/pull/2367

feat(statsd) new metrics and more flexible configuration

---

kong-0.10.3-0.rockspec
kong/plugins/datadog/handler.lua
kong/plugins/datadog/migrations/cassandra.lua
kong/plugins/datadog/migrations/postgres.lua
kong/plugins/datadog/schema.lua
kong/plugins/datadog/statsd_logger.lua
spec/03-plugins/08-datadog/01-log_spec.lua
spec/03-plugins/08-datadog/02-schema_spec.lua

- Now each metric supports configurable stat type,
sample rate and customer identifier if applicable.
- Custom prefix for stats's name
- Custom tags for Datadog.
- New metrics `upstream_latency`, `kong_latency` and `status_count_per_user`.
- Schema updated to support new metrics
- Schema updated to support `stat_type`, `sample_rate`, `consumer_identifier`, and tags
- Added new schema checks and test 
NOTE: depends on the PR on #2367

feat(datadog) new metrics and more flexible configuration

---

kong/dao/migrations/postgres.lua

An attempt to fix #2208.
Creates two indexes on the `ttls` table in Postgres to improve performance on `SELECT` statements.
Effectively we do make a TTL check on every `SELECT` statement on these columns: https://github.com/Mashape/kong/blob/master/kong/dao/db/postgres.lua#L238-L244
This should improve performance by a lot.

perf(postgres) creating indexes on ttls table

---

kong/core/handler.lua
kong/kong.lua

This is mainly to address the Lambda and OpenWhisk plugins not being
able to run if the specified ùpstream_url`'s hostname does not resolve,
hence resulting in an HTTP 500 error.
Ideally, this change should probably be reverted, since some future
plugins might need to know the resolved IP address or the upstream Host
header in their `access` phase.
No tests for now, just running the CI.

fix(proxy) resolve DNS hostnames post-plugins

---

kong/core/handler.lua
kong/kong.lua
kong/plugins/log-serializers/basic.lua

* fix(logging) include `balancer_by_lua` latency in Kong latency

fix(logging) include 'balancer_by_lua' latency in Kong latency

---

kong/core/router.lua
spec/01-unit/11-router_spec.lua

When matching URIs, we iterate over a list of APIs, and not a list of
URIs (for various, performance reasons, although a refactor of the
router is scheduled with some performance improvements later on).
This list of APIs is sorted per URI length. But an API can have more
than one URI. As such, the router can potentially evaluate an API with a
very long URI, and a much shorter one that matches the request URI,
instead of a following API which would be an exact match for that API.
To fix this, we sort our deserialized list of URIs to iterate on in the
select method, and if we do have a match, we conserve the URI that was
matched, to check if it belongs to the right API at API match time.
Fix #2662

fix(router) do not match another API with a longer URI

---

kong/dao/migrations/postgres.lua

This change helps support compatibility with BDR.
Kong performs postgres database migrations on start-up.
Postgres logs an error when postgres.lua calls ALTER TABLE … DEFAULT.
Per the BDR docs, ALTER TABLE ... DEFAULT is not supported by BDR.
However, it can be rewritten into a short sequence that is supported.
This commit replaces the one command with the short sequence.
http://bdr-project.org/docs/0.9/ddl-replication-statements.html
* [Implement restructured postgreSQL commands in kong/dao/migrations/postgres.lua]
Fix  #2671

chore(dao) modify postgres for bdr compatibility

---

kong/plugins/aws-lambda/handler.lua
spec/03-plugins/23-aws-lambda/01-access_spec.lua
spec/fixtures/custom_nginx.template

```
HTTP/1.1 200 OK
Content-Type: application/json
Connection: keep-alive
Content-Length: 444
Connection: keep-alive
x-amzn-RequestId: ...
X-Amzn-Trace-Id: ...
Date: Thu, 06 Jul 2017 16:23:07 GMT
X-Amz-Function-Error: Handled
x-amzn-Remapped-Content-Length: 0
Server: kong/0.10.2
```
Today I noticed that I mistakenly added a `n` to the aws lambda function http header. ☹️ 
This fixes the aws-lambda plugin and specs to use the correct function header name as per the latest documentation at http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseSyntax
> ## Response Syntax
>```
>HTTP/1.1 StatusCode
>X-Amz-Function-Error: FunctionError
>X-Amz-Log-Result: LogResult
>
>Payload
>```
I'll open a separate PR to support updating the status code for Handled errors.
suggested …

fix(aws-lambda) Fix typo in X-Amz-Function-Error header

---

kong/plugins/bot-detection/handler.lua

Bring back the old behavior of caching UA lookups per-worker in the bot detection plugin. This behavior was removed during serf removal. A local table is used to cache lookup results of the UA based on the plugin config; this cache is purged when the plugin is updated.
* Implement per-worker cache of User Agent matches

feat(bot-detection) per-worker cache UA lookups

---

kong/plugins/basic-auth/access.lua

The call to `next` on this plugin checked whether table m was empty.
Since only m[1] is used later on, I changed the check to test whether
m[1] exists.

fix(basic-auth) removes NYI instruction

---

kong/plugins/bot-detection/handler.lua

We don't need to use the match's return value, only whether the match
happened.
This PR is a branch rename of #2689

perf(bot-detection) replace ngx.re.match with find

---

kong-0.10.3-0.rockspec
kong/api/crud_helpers.lua
kong/api/init.lua
kong/api/routes/upstreams.lua
kong/templates/nginx_kong.lua
spec/fixtures/custom_nginx.template

This PR will change Lapis framework dependency to Mashape's temporary fork `kong-lapis`. This is added to support latest versions of OpenResty.
* Change dependency from `lapis` to `kong-lapis` on a `.rockspec`
* Change code dependencies to use `kong-lapis` instead of `lapis`
Fix #2489

chore(deps) change to latest kong fork of lapis to support latest openresty

---

kong/cmd/utils/prefix_handler.lua
kong/templates/nginx_kong.lua
spec/01-unit/003-prefix_handler_spec.lua
spec/02-integration/05-proxy/02-upstream_headers_spec.lua
spec/fixtures/custom_nginx.template

@thefosk added HTTP2 flags to config, and here I decided to follow same pattern and add a new template variable ${{PROXY_PROTOCOL}} to template compilation. It makes the templates a bit easier to read. I also added couple of additional tests (originally didn't want to add this as I felt it was a bit dirty to have that variable with a space in front of the actual value, e.g. " proxy_protocol", but as I saw @thefosk using it for HTTP2, I decided to follow the suit).

refactor(conf) add ${{PROXY_PROTOCOL}} template variable

---

kong/kong.lua
kong/templates/nginx_kong.lua
spec/fixtures/custom_nginx.template

Originally did this for Lapis patch to move Admin API Lua / CORS code out of Kong Nginx templates. But I decided to make other changes to other similar parts of the code, and here it is for a review.

refactor(conf) move excessive lua code out of kong nginx templates

---

kong/cmd/check.lua
kong/cmd/cluster.lua
kong/cmd/compile.lua
kong/cmd/health.lua
kong/cmd/init.lua
kong/cmd/migrations.lua
kong/cmd/quit.lua
kong/cmd/reload.lua
kong/cmd/restart.lua
kong/cmd/start.lua
kong/cmd/stop.lua
kong/cmd/version.lua

Properly align the CLI options with the default ones injected by the CLI main.
Before:
```
$ kong compile --help
[...]
Options:
-c,--conf (optional string) configuration file
--v         verbose
--vv        debug
```
After:
```
$ kong compile --help
[...]
Options:
-c,--conf   (optional string) configuration file
--v         verbose
--vv        debug
```

fix(cli) properly align options in help messages

---

kong/cache.lua
kong/core/router.lua

Because those cache sizes are defined in number of units and not in
memory size, we must draw such an hypothesis as the ones described in
the related comments, and draw a conclusion from it, which is a
theoretical ideal cache size.
* Increase LRU cache size for the router
* Increase LRU cache size for the DB cache

perf(*) increase hard-coded LRU Lua cache sizes

---

kong-0.10.3-0.rockspec

This needs to be done (and released) before this can be merged:
https://github.com/Mashape/kong-lapis/pull/2

chore(deps) change to kong-lapis 1.5.4 that has pgmoon-mashape switched to pgmoon

---

kong/cluster_events/strategies/postgres.lua

properly reports this error:
```
2017/07/18 03:43:34 [error] 105#0: *67 [lua] cluster_events.lua:366: [cluster_events] poll() threw an error: ...hare/lua/5.1/kong/cluster_events/strategies/postgres.lua:102: attempt to get length of local 'res' (a nil value), context: ngx.timer
2017/07/18 03:43:34 [debug] 103#0: *805 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1500349349.017 to: 1500349414.026
2017/07/18 03:43:34 [error] 103#0: *805 [lua] cluster_events.lua:366: [cluster_events] poll() threw an error: ...hare/lua/5.1/kong/cluster_events/strategies/postgres.lua:102: attempt to get length of local 'res' (a nil value), context: ngx.timer
2017/07/18 03:43:39 [debug] 100#0: *870 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1500349349.017 to: …
```

fix(cluster) add missing error handling

---

kong/core/handler.lua
kong/core/router.lua
kong/dao/schemas/apis.lua
spec/01-unit/007-entities_schemas_spec.lua
spec/01-unit/010-router_spec.lua
spec/02-integration/05-proxy/01-router_spec.lua

APIs now accept regex values in their `uris` property. Any such value that does not respect the reserved character set of RFC 3986 is currently considered a regex.
URI regexes can be useful for use-cases like:
- `/users/\d+/profile`
- `/version/\d+/users/\S+`
APIs with `strip_uri = true` will correctly strip off the entire matching regex from the request URI.
We also support named (or numbered) groups captures:
- `/users/(?P<user_id>\d+)/profile`
- `/version/(?P<version>\d+)/users/(?P<user>\S+)`
Those URIs, when matched, will make the router return a new table with both a hash and an array part, to be used at the user's convenience:
```lua
{ "1", "john", version = "1", user = "john" }
```
This value is not used by the core as of yet, and will be in a later contribution, and will get …

feat(router) support for regex URIs

---

kong-0.10.3-0.rockspec
kong/cmd/compile.lua
kong/cmd/init.lua
kong/cmd/prepare.lua
kong/cmd/utils/log.lua
spec/02-integration/02-cmd/10-prepare_spec.lua

* Introduces a new `kong prepare` command that only prepares the prefix.
Documentation at https://github.com/Mashape/getkong.org/commit/c5b332ef0e0484b36ecf807fd812bc66ff7e234a

feat(cli) kong prepare cli command to prepare prefix

---

kong/core/handler.lua
kong/kong.lua

Gets the `ngx.ctx` table once, and passes it on to the handlers, reducing the expensive meta-table magic. This could be extended to the plugins, but omitted that. Considering that part of the new plugin api.

perf(core) get ngx.ctx once and pass along to handlers

---

kong/dao/dao.lua
kong/dao/db/cassandra.lua
kong/dao/db/postgres.lua
kong/dao/schemas_validation.lua
spec/01-unit/006-schema_validation_spec.lua
spec/02-integration/03-dao/03-crud_spec.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua

Better handling of JSON `null` in DAO layer and validations.
Also allows usage of JSON `null` to remove optional parameters using `PATCH` request, e.g. with HTTPie:
```bash
http patch :8001/apis/test hosts:=null uris:=null
```

feat(dao) ngx.null — allows patch requests to remove opt. conf. params

---

kong/api/crud_helpers.lua
kong/api/routes/apis.lua
kong/api/routes/plugins.lua
spec/02-integration/03-admin_api/10-post_processing_spec.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-post-process/api.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-post-process/handler.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-post-process/schema.lua

Adds 3rd parameter to `paginated_set` function, and when given as a function allows post processing of a paginated results.
Usage example:
```lua
crud.paginated_set(self, dao.oic_issuers, function(row)
local configuration = row.configuration
if configuration then
configuration = json.decode(configuration)
if configuration then
row.configuration = configuration
else
configuration = {}
end
end
local keys = row.keys
if keys then
keys = json.decode(keys)
if keys then
row.keys = keys
else
keys = {}
end
end
end)
```

feat(dao) allow post processing with a callback on a crud_helpers

---

CHANGELOG.md
kong/api/crud_helpers.lua
kong/api/routes/apis.lua
kong/api/routes/plugins.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua

* Reverts the main part of #2726
* Needs to be merged before #2714 in order to make its tests pass

fix(admin) disable plugin names in /api/:id/plugins*

---

.ci/setup_env.sh
kong-0.10.3-0.rockspec

Since 1.5.3, Penlight should now provide compatibility for
`pl_utils.executeex` out of the box between Lua 5.1 and 5.2.
This should allow Kong to work on an OpenResty build without the
`--without-luajit-lua52` flag.

chore(*) enable lua52 compat

---

kong/plugins/acl/handler.lua
spec/03-plugins/19-acl/02-access_spec.lua

Sometimes Kong is not the provider of credentials, but a third-party identity provider does that. E.g. with OpenID Connect and LDAP the credentials are stored in 3rd party IdP or directory.
ACL plugin on the other hand did only work with `ngx.ctx.authenticated_credential`, this patch adds a support to `ngx.ctx.authenticated_consumer` as well.

feat(acl) allow acl plugin to use a consumer without credentials

---

kong/api/routes/consumers.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/fixtures/custom_plugins/kong/plugins/rewriter/schema.lua

Adds CRUD routes for plugins scoped by consumers to the admin API:
* `/consumers/:username_or_id/plugins/`
* `/consumers/:username_or_id/plugins/id`
This PR needs #2726 to be merged before it, otherwise the api route tests will fail.
Closes #2336

feat(admin) add /consumers/:id/plugins routes

---

spec/03-plugins/17-jwt/01-jwt_parser_spec.lua

Follow up of 7642f4a601652998802e06aa76c42eca2f0ace2d
Due to the following addition (RS512 support) in master:
4e2e1d7a81748c41e5bd3b55cc4b6f4ae137b727

tests(jwt) proper RS512 fixture for OpenResty 1.11.2.3+

---

spec/02-integration/04-admin_api/08-targets_routes_spec.lua

This test is currently failing too often on CI and slowing down our
release process. It is only disable for Travis CI like so (still runs on
local testing).

tests(admin) disable the flaking targets test on CI

---

kong/dao/migrations/cassandra.lua

Cassandra does not support the `COLUMN IF EXISTS` conditionals like Postgres does.

fix(migration) C* got an OD copy-pasta from Postgres

---

kong/core/plugins_iterator.lua
kong/kong.lua
spec/02-integration/05-proxy/03-plugins_triggering_spec.lua

If a request is authenticated via one of the authentication plugins
(key-auth, basic-auth, jwt, etc...) and if `anonymous_reports` are
enabled, Kong errors out and returns an HTTP 500 error.
This was not detected by our test suite since tests are run with
`anonymous_reports` **disabled**.
Context:
The new runloop introduced in baf69f1f230c77300f3a94be7fc72643caef1e9d
assumes that plugins always have a schema (which is a correct assumption
to make). However, the `anonymous_reports` feature is implemented as such
a plugin for legacy reasons. Furthermore, it is implemented *without* a
schema, which is an oversight from a legacy contribution. As such, once
a request is authenticated, the new runloop evaluates plugins by
considering their `schema.no_consumer` property (if set, then the
runloop …

hotfix(core) handle anon reports in authenticated requests

---

spec/01-unit/004-utils_spec.lua
spec/01-unit/006-schema_validation_spec.lua
spec/01-unit/007-entities_schemas_spec.lua
spec/01-unit/010-router_spec.lua

Replaces httpbin/mockbin with "example" in the unit tests.
This makes it easier to grep for appearances of those two later on, and is also a bit more explicit, since no actual requests to httpbin or mockbin are needed during the unit tests.

tests(core) remove (http|mock)bin from unit tests

---

kong/plugins/datadog/handler.lua
spec/03-plugins/08-datadog/01-log_spec.lua

Fix runtime error when the datadog plugin is global and there is
not a catch all api present
Addresses the runtime error that occurs when datadog is registered as a global plugin and there is not a catch all api. 
Example log: 
`2017/07/06 01:41:53 [error] 101#0: *60797 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/datadog/handler.lua:60: attempt to index field 'api' (a nil value)]`
cc @p0pr0ck5

fix(datadog) skip non-matched apis

---

kong/dao/schemas_validation.lua
spec/01-unit/006-schema_validation_spec.lua

Support using `\,` for representing a `,` character in a comma-separated array, without using it as a separator. This allows one to use commas when entering URIs using the PCRE regex syntax `{n,m}` for `n`-to-`m` repetitions. For example:
```
$ curl localhost:8001/apis -d name=test -d upstream_url=http://httpbin.org -d uris='/foo/\d{1\,3},/bar'
```
Fixes #2780.

fix(dao) allow escaped commas in arrays

---

spec/02-integration/01-helpers/00-helpers_spec.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/02-cmd/04-reload_spec.lua
spec/02-integration/02-cmd/07-restart_spec.lua
spec/02-integration/02-cmd/09-quit_spec.lua
spec/02-integration/04-admin_api/01-kong_routes_spec.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
spec/02-integration/04-admin_api/05-cache_routes_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/04-admin_api/09-post_processing_spec.lua
spec/02-integration/05-proxy/01-router_spec.lua
spec/02-integration/05-proxy/04-dns_spec.lua
spec/02-integration/05-proxy/05-ssl_spec.lua
spec/02-integration/05-proxy/07-uri_encoding_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
spec/03-plugins/10-key-auth/03-invalidations_spec.lua
spec/03-plugins/11-basic-auth/04-invalidations_spec.lua
spec/03-plugins/17-jwt/04-invalidations_spec.lua
spec/03-plugins/19-acl/03-invalidations_spec.lua

This further improves the ability to run tests individually, without
assuming behavior about previous tests having performed migrations
and establishing a proper test schema.
* add `helpers.run_migrations()` where appropriate in various integration tests

tests(*) run helper migrations in individual tests where necessary

---

kong/cmd/health.lua
kong/cmd/restart.lua
kong/cmd/stop.lua

> Opened against `release/0.11` because considered a "hotfix" (last-minute fixing of a non-released bug)
Warning logs issues by the configuration loader module would be logged
twice for `kong health` and `kong restart`. The logged warning with
which this incorrect behavior was noticed is the WARN log for
`db_update_propagation = 0` when using a Cassandra datastore.
This is a matter of a missing `disable`/`enable` in `kong health`. In
`kong restart`, however, we need a way to ensure that warning issued by
the config loading module when `stop.lua` is invoked from another
command are silent, from start to finish. We chose to add an optional
`quiet` argument for simplicity.
Another possible fix would have been to keep track of the number of
`disable()` and `enable()` calls, and make sure that …

hotfix(cli) prevent double logging in health and restart

---

kong/api/crud_helpers.lua
kong/api/routes/apis.lua
kong/api/routes/plugins.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-post-process/api.lua

* Fixes the reports (that were broken with https://github.com/Mashape/kong/commit/cc4ffc30397b0a1291c456f39840d88ba00f7b98).
* Removes plugin configuration from report log.

hotfix(reports) propagate API events and don't send plugins config

---

kong/plugins/oauth2/access.lua

We can use a more performant JITable string find to search for the exposed endpoints, based on the given logic. Doing so avoids the PCRE overhead and saves expression cache space in the VM.
* Use `string_find` instead of `ngx.re.find` for artificial endpoint search

perf(oauth2) remove needless use of regex for artificial endpoints

---

spec/02-integration/05-proxy/11-error_default_type_spec.lua

Workaround the intermittent Travis failures we keep getting,
by increasing the delay in `error_default_type_spec.lua` tests
to 1 second.
These tests are failing because they update the configuration,
run `kong reload`, wait for an arbitrary amount of time, then
run the test. This arbitrary amount of time (currently 0.5s)
is not always enough, so while increasing it is not a real
solution to the problem, at least it can make our Travis tests
pass on these, so that the fail/pass status in the Travis/Github
integration becomes useful again.
See #2803.

tests(proxy) Increase delay to workaround Travis failures

---

kong/core/router.lua
spec/01-unit/010-router_spec.lua

Summary
-------
It was reported in #2825 that `preserve_host` seemed to behave wrongly
upon subsequent call of a same API if that API had no `hosts`.
Since matches APIs are cached, and so are their `upstream_host` values,
I investigated around the LRU cache of our matches in the router. What I
discovered is, considering the following API:
{
"name": "example",
"upstream_url": "http://httpbin.org",
"uris": ["/example"]
}
The router would try to save cycles by *not* reading the
`ngx.var.http_host` variable, since no API is configured to match on a
Host header.
However, the Host is also part of the cache key since the introduction
of the LRU cache in the router. But in the above case, considering the
following two requests:
GET /example HTTP/1.1
Host: domain1.com
GET /example HTTP/1.1
Host: …

fix(router) preserve_host always fetches the request's Host

---

.ci/run_tests.sh
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/03-plugins/05-syslog/01-log_spec.lua
spec/03-plugins/24-rate-limiting/04-access_spec.lua
spec/03-plugins/25-response-rate-limiting/04-access_spec.lua

Rename tests which are disabled due to intermittent failure
from #ci to #flaky, to better identify them.

chore(tests) rename #ci to #flaky

---

spec/02-integration/03-dao/08-ipc_events_spec.lua
spec/02-integration/04-admin_api/01-kong_routes_spec.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/05-proxy/06-upstream_timeouts_spec.lua
spec/02-integration/06-invalidations/01-cluster_events_spec.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua

Mark the desciptions of all Cassandra and PostgreSQL tests
with the appropriate #cassandra and #postgres hashtags,
so they can be enabled/disabled properly via the Busted
command-line.

tests(*) use hashtags to toggle cassandra/postgres

---

kong/core/router.lua
spec/01-unit/010-router_spec.lua

Add a check to `marshall_api` to make sure it returns an error
when it fails to categorize an API.
This moves a test from `pending` to running.

fix(router) enforce api types

---

spec/fixtures/custom_nginx.template
spec/fixtures/mock_upstream.lua

Add an endpoint `/stream/:num` to the mock upstream fixture that streams `num` number of chunked responses.
* Add `/stream/:num` endpont to `spec/fixtures/custom_nginx.template`
* Publicly expose `get_default_json_response` for consumption in mock nginx template

tests(fixtures) add /stream endpoint to mock fixture

---

spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/02-cmd/07-restart_spec.lua

Re-enable tests for `kong stop`/`kong start` and
`kong stop`/`kong restart` which were pending, since
those no longer perform migrations. Also, make sure
they don't depend on affecting a system-wide
installation of Kong.

fix(tests) re-enable (re)start/stop tests

---

kong/dao/schemas/apis.lua
kong/dao/schemas/consumers.lua
kong/dao/schemas/plugins.lua
kong/dao/schemas/ssl_certificates.lua
kong/dao/schemas/ssl_servers_names.lua
kong/dao/schemas/targets.lua
kong/dao/schemas/upstreams.lua
kong/plugins/acl/daos.lua
kong/plugins/basic-auth/daos.lua
kong/plugins/hmac-auth/daos.lua
kong/plugins/jwt/daos.lua
kong/plugins/key-auth/daos.lua
kong/plugins/oauth2/daos.lua

Since the removal of Serf, `marshall_event` is not used anymore by any
schema (invalidations uses `cache_key` or custom invalidation handlers
instead).
This just gets rid of unused code.

chore(*) cleanup un-needed marshall_event handlers on schemas

---

kong/core/balancer.lua

Due to a typo the configured balancer size was not set up,
and the default size of 1000 was always used.
This also fixes some of the (occasionally) failing tests.

fix(balancer) respect the given balancer size

---

kong/plugins/acl/handler.lua

Rewritten logic.
I put some serious lightning into its flux capacitor, it will now take you back to the future any time.
(not to mention we dropped the awesome `utils.table_contains` usage from this one)

perf(acl) rewrite for performance, jit and caching

---

kong/tools/public.lua

Built for #2823 and future programmatic usage of request body
parsing.
New public API `get_body_info()` to retrieve:
- parsed body args (similar to `get_body_args()` (table)
- error code due to potential unknown request MIME type
- raw body (string)
- the request MIME type (as an enum value for programmable usage)
New public API enum values:
- `req_mime_types`: table containing known request MIME types
- `req_body_errors`: table containing enum of req body parsing errors
The previous `get_body_args()` API is left untouched from a user's POV
to preserve backwards compatibility: it still return only one argument
which is the parsed body, or an empty table.
The implementation tries to be efficient and lazily reads the request
body only when necessary.

feat(utils) new get_body_info() public API

---

kong/plugins/aws-lambda/handler.lua
kong/plugins/aws-lambda/schema.lua
spec/03-plugins/23-aws-lambda/01-access_spec.lua
spec/fixtures/custom_nginx.template

**Depends on:** #2822
Reworked version of #2470 from @akh00.
This fixes a few issues with #2470 regarding inconsistent request body parsing, some inconsistent naming for the new schema values and a slightly different approach regarding the forging of the forwarded upstream request body. It also addresses quite a few style and maintainability issues.
New optional configuration properties:
- `forward_request_method`
- `forward_request_uri`
- `forward_request_headers`
- `forward_request_body`
If specified, the request body sent to the invoked Lambda will contain
the desired attributes of the client's request as a JSON payload.
If none of the above values are specified, the upstream body contains a
JSON payload which is merged from the request's body data and its
query string. This is to …

 	feat(aws-lambda) add support for forwarded request method/uri/body

---

spec/02-integration/03-dao/02-migrations_spec.lua

the defined spies were not used, hence the test always succeeded

test(migration) fix an always succeeding test

---

kong/dao/factory.lua
spec/02-integration/03-dao/02-migrations_spec.lua

Migrations are recorded in the datastore and then the order in which
they appear there is relevant for determining if they should run.
Once something goes out-of-sync on every start/restart it will keep
running migrations over and over again.

fix(migrations) stop depending on the order as recorded

---

kong/plugins/key-auth/handler.lua
kong/plugins/key-auth/schema.lua
spec/01-unit/007-entities_schemas_spec.lua
spec/02-integration/03-dao/04-constraints_spec.lua
spec/03-plugins/10-key-auth/02-access_spec.lua

fixes #1292, #1535
replaces #2743 
follow up PR with the migrations: #2752

feat(key-auth) skip authenticating preflight OPTIONS requests

---

kong-0.11.0-0.rockspec
kong/core/balancer.lua
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua
kong/dao/schemas/upstreams.lua
kong/init.lua
spec/01-unit/007-entities_schemas_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

This removes the orderlist property from the balancer entity. Due to a different implementation in the dns library, it is no longer required.
Reason:
Because multiple Kong nodes need the exact same ring-balancer, the orderlist was used to make sure they all used the same random data to set up the balancer.
This has now been replaced by using a separate randomizer in the dns library, which always will be seeded again, and with the same seed. This causes the exact same random set of numbers to be generated. This works because there is no need for uniqueness, there is only need for distribution of the data.

refactor(balancer) drop the orderlist property

---

kong/api/routes/upstreams.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

With the trailing slash the `.../targets/active` endpoint would return a "method not allowed" error
fixes #2840

fix(admin) fix regression of trailing slash in targets uri

---

Makefile

Recent changes in luacheck have caused false positive linting failures; such failures have been covered in Travis due to build cache.

chore(*) pin luacheck to a stable version

---

kong/plugins/bot-detection/handler.lua
spec/03-plugins/22-bot-detection/01-access_spec.lua

Also updates the caching mechanism to a simple weak table.
fixes #2904

fix(bots) allow the plugin to run globally

---

kong/dao/db/cassandra.lua
kong/dao/db/postgres.lua

This fixes a reported issue that Kong would not be able to run
migrations on PostgreSQL with self-signed certificates. The error "self
signed certificate" that Kong raised indicated that the root CA was not
made available to the cosocket in use.
Because the CLI is interpreted by resty-cli, it is too late to set the
resty-cli `lua_ssl_trusted_certificate` directive.
The approach we historically take is to rely on LuaSocket/LuaSec in
Kong's CLI and circumvant this limitation (the root CA file can be
specified at runtime as part of the LuaSocket instantiation options).
Fix #2856

fix(dao) allow self-signed certificates for migrations

---

kong/core/handler.lua
kong/dao/db/postgres.lua
kong/dao/migrations/postgres.lua
spec/02-integration/05-proxy/01-router_spec.lua

APIs are retrieved without an `ORDER BY` clause from the datastore when
building the router. Because of the lack of such a clause in our current
Cassandra schema, we wish to implement sorting by creation date in our
business logic, right before building the router.
However, the PostgreSQL default clause of the APIs `created_at` field
is set to `CURRENT_TIMESTAMP(0)`, which strips ms precision out of the
timestamp. This changes the default timestamp precision to 3 digits so
our sorting attribute (`created_at`) can be meaningful.
This fix is targeting 0.11.1, and as such does not introduce a new
migration to update the default value of `created_at`. This fix will
only have effect for new database schemas.
A second commit will introduce a migration, which, as per our policy,
will be targeted …

fix(postgres) ensure APIs created_at has ms precision

---

spec/02-integration/01-helpers/00-helpers_spec.lua
spec/02-integration/05-proxy/08-websockets_spec.lua
spec/fixtures/custom_nginx.template
spec/helpers.lua

Avoid conflicts with other client connections that may be taking place at the same time (especially frequent in the Travis CI environment).

tests(*) do not launch servers in ephemeral ports

---

kong/dao/migrations/postgres.lua

Follow-up commit to #2924
This migration is targeted for landing in 0.12.0, and will ensure that
newly created APIs will have a `created_at` field with ms precision.

 fix(postgres) migration for APIs created_at default precision

---

kong-0.11.0-0.rockspec
kong/dao/db/cassandra.lua
kong/dao/migrations/helpers.lua
kong/plugins/jwt/handler.lua
kong/plugins/jwt/migrations/cassandra.lua
kong/plugins/jwt/migrations/postgres.lua
kong/plugins/key-auth/handler.lua
kong/plugins/key-auth/migrations/cassandra.lua
kong/plugins/key-auth/migrations/postgres.lua

PR #2744 and #2857 implemented the preflight options (for a minor release). This adds the migrations including defaults (for a major release)

feat(migrations) add preflight defaults for jwt and key-auth

---

kong/init.lua

The field referenced did not exist and failed with an error while
indexing a nil value. This error happened during logging, and hence the
actual underlying error was lost unfortunately.
Note: the `addr` structure is [defined here](https://github.com/Mashape/kong/blob/0.10.3/kong/core/handler.lua#L103-L117) and does not have an `upstream` field.

fix(balancer) log the proper field

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
UPGRADE.md
kong/plugins/galileo/alf.lua
kong/tools/utils.lua
spec/01-unit/006-schema_validation_spec.lua
spec/01-unit/010-router_spec.lua
spec/02-integration/05-proxy/03-plugins_triggering_spec.lua
spec/02-integration/05-proxy/07-uri_encoding_spec.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
spec/03-plugins/16-response-transformer/02-body_transformer_spec.lua

replaced all instances of https://github.com/Mashape with https://github.com/Kong with exception of the rockspec

misc(re-org): migrated from github.com/Mashape to github.com/Kong

---

kong/plugins/ldap-auth/access.lua
kong/plugins/ldap-auth/schema.lua

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#contributing
Ability to use `Authorization: WhaTeVer base64(username:password)` has a authorization header for the ldap-auth plugin.
In particular, when not using the basic-auth plugin, using `Authorization: Basic base64(username:password)` instead of "Authorization: LDAP base64(username:password)` will allow you to use any client (web browser, curl) without having to fool around the headers manually.
* The ldap-auth plugin can now use any `Authorization type` you want, such as `Authorization: LDAP base64(username:password)`, `Authorization: Basic base64(username:password)`, `Authorization: WhaTeVer …

Ability to use "Authorization: WhaTeVer base64(username:password)"

---

kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua

Redis policy for rate-limiting and response rate-limiting plugins uses redis pipelining feature but start and commit multiple pipelines instead of using a single one.
I messed up in a force push on my forked repo, this is same as #2932 
Sorry for the confusion.
* Optimize redis storage policy for rate limiting plugin by using a single pipeline
* Optimize redis storage policy for response rate limiting plugin by using a single pipeline

perf(*-rate-limiting) optimize redis pipelining

---

.editorconfig

chore(conf): add .editorconfig

---

kong/plugins/response-transformer/handler.lua

Concatenate strings in buffer every time body_filter occurs
when receiving response from an upstream can lead strong overhead.
The right way would be to add chunks to a table, and do a concat
when eof occurs.
Programming in Lua - 11.6 – String Buffers:
https://www.lua.org/pil/11.6.html
Discussion in kong mailing list:
https://groups.google.com/forum/#!topic/konglayer/vWU5Y7Qsb_s

perf(response-transformer) accumulate chunks of response using table

---

kong/plugins/hmac-auth/access.lua
spec/03-plugins/20-hmac-auth/03-access_spec.lua

When an invalid hmac-auth header is sent by the client, kong generates an internal server error when enforce_headers are configured. The code did not check whether any headers were actually parsed.
Fix #2951

fixed internal error with invalid hmac-auth authorization header

---

kong/core/balancer.lua
kong/core/handler.lua
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua
kong/dao/schemas/upstreams.lua
spec/01-unit/011-balancer_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

One can define 2 keys to hash on, if the first key returns `nil`, the fallback is used (for example if a header is not present). The options for the keys are:
1. `none`:  do not use a hash, just do (weighted) round-robin. This is the default.
1. `consumer`: use the `consumer_id`, or if not found the `credential_id`. (later is for external auth like `oauth2` or `ldap`)
1. `ip`: use the originating ip address
1. `header`: use the header specified in the additional header option. If there are multiple headers by this name, then all entries are used (concatenated)
The hash value is created from the resulting string-value, and is calculated as a numerical `crc32`.

feat(balancer) implement consistent hashing

---

kong/plugins/log-serializers/basic.lua
spec/01-unit/012-log_serializer_spec.lua

`ngx.var.request_uri` is the original uri and is not updated if the uri is changed using `ngx.set_uri(newUri)`. Instead, `ngx.var.uri` reflects the new uri. Added a new field to reflect the modified uri.
* Use the same name as the Nginx variables in request object of logs
* Rename `request_uri` to `request_url`
* New unit test
Fix #2441

Modify log to add ngx.var.uri in request object

---

kong/core/handler.lua
kong/dao/dao.lua

The `post_local` API of the worker-events library can return `false,
nil` when polling is skipped because we are posting from an event
handler, effectively nullifying the purpose of the first return value of
`post_local`.
My suggestion to lua-resty-worker-events would be to replace the
following line in `post_local`:
return _M.poll()
with a wrapper:
local ok, err = _M.poll()
if err then
return nil, err
end
return true -- the event *was* posted
In the meantime, this commit changes the return values check to rely on
`err ~= nil`, thus avoiding such inadvertent error messages to show up.
Fix #2872

fix(cluster) do not inadvertently log error messages

---

kong/api/crud_helpers.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua

Background
----------
Due to unfortunate legacy design decisions, our HTTP PUT handlers behave
in the following way as of today:
1. if the payload does not have the entity's primary key values,
we attempt an insert()
2. if the payload has primary key values, we attempt an update()
Issue
-----
While acknowledging this isn't the appropriate/desired behavior for a
PUT handler, #2774 has raised the following concern:
> When a PUT payload contains an non-existing primary key (attempt to
create an entity), the endpoint responds HTTP 200 OK, but the entity is
not created, and the response body is empty.
Root cause & resolution
-----------------------
This was due to a mis-usage of the `dao:update()` API.
While this change will **not** allow #2774 to work the way it is
expected of it to work, …

fix(admin) return HTTP 404 on PUT with non-existing PK

---

kong/api/crud_helpers.lua
kong/api/routes/certificates.lua
kong/api/routes/upstreams.lua
kong/plugins/galileo/alf.lua
spec/03-plugins/09-galileo/01-alf_spec.lua

Since https://github.com/openresty/lua-cjson/pull/16 has been merged quite a while back and we use Openresty 1.11.2.4, we can safely remove some workarounds.

chore(*) fix workarounds for lua_cjson empty array handling

---

spec/03-plugins/06-statsd/01-log_spec.lua
spec/03-plugins/08-datadog/01-log_spec.lua

This is a band-aid solution to the remaining class of
ephemeral failures happening in our CI. Most threads that
spawn a UDP server use `helper:udp_server` which does
sleep. A few ones run customized servers, and those were
lacking the sleep.
The most proper solution would be to implement an initialization
handshake (and to refactor the tests touched by this patch to
avoid the repetition that proliferated this bug), but this is
the least-invasive patch to address the problem, submitted in
hopes that it can be applied quickly to address the CI issues.
We will revisit this issue properly when we review the test suite
as a whole in the future. …

tests(plugins) wait for UDP server threads to start

---

CHANGELOG.md

This introduced two new sections to the Kong Changelog to better reflect
the states of our upcoming releases.
A "Planned" section details our long term upcoming releases and their
theme, at a rather high level, without any strict deadline nor
boundaries as to their contents.
A "Scheduled" section shows upcoming, imminent releases for which a date
has already been picked, along with a **non-exhaustive**, detailed
changelog.
We added two of our upcoming releases to these sections:
* Add 0.11.2 to the "Scheduled" section
* Add 0.12.0 to the "Planned" section

docs(changelog) new scheduled/planned sections

---

kong/conf_loader.lua
spec/01-unit/002-conf_loader_spec.lua

Adds a listen address check in `conf_loader.lua` for the `admin_listen_ssl` configuration string to enhance error reporting when a Kong node is misconfigured.

fix(conf-loader) add format check for `admin_listen_ssl` string

---

kong/plugins/jwt/api.lua
spec/03-plugins/17-jwt/02-api_spec.lua

* `/jwts/` to paginate through all jwt credentials
* `/jwts/:jwt_key_or_id/consumer` to retrieve the Consumer
associated with a credential
Similar to #2998 #2955

feat(jwt) add endpoint to list all JWTs

---

kong/plugins/hmac-auth/api.lua
spec/03-plugins/20-hmac-auth/02-api_spec.lua

* `/hmac-auths/` to paginate through all hmac-auth credentials
* `/hmac-auths/:credential_key_or_id/consumer` to retrieve the Consumer
associated with a credential

feat(hmac-auth) add 2 endpoints to interact with hmac-auth credentials

---

kong/plugins/basic-auth/api.lua
spec/03-plugins/11-basic-auth/02-api_spec.lua

Adding endpoints:
- `GET /basic-auth` : lists all the basic-auths present in kong
- `GET /basic-auth/:credential_id/consumer` : retrieve a consumer form a credential ID
* `GET /basic-auth` : lists all the basic-auths present in kong
* `GET /basic-auth/:credential_id/consumer` : retrieve a consumer form a credential ID
* Add related tests
This is similar to #2955 and #2371

feat(basic-auth) add endpoint to list all basic-auths

---

spec/03-plugins/10-key-auth/01-api_spec.lua
spec/03-plugins/11-basic-auth/02-api_spec.lua
spec/03-plugins/17-jwt/02-api_spec.lua
spec/03-plugins/20-hmac-auth/02-api_spec.lua

The recent commits adding endpoints to manipulate the credentials of
authentication plugins had test cases that were flawed when running with
Cassandra.
With Cassandra, the `offset` query argument must be URL-encoded, and the
`offset` parameter in the Admin API response will also be present in the
response for the last page.

hotfix(*) credentials endpoints test suites with Cassandra

---

CHANGELOG.md
kong-0.11.2-0.rockspec
kong/meta.lua

**Formal PR for Kong 0.11.2 - request for reviews!**
* Full list of commits since 0.11.1: https://github.com/Kong/kong/compare/0.11.1...release/0.11.2
* Changelog (formatted): https://github.com/Kong/kong/blob/4b609928da7263819640ea139989a8d34840b7f0/CHANGELOG.md#0112---20171129
* Docs PR: https://github.com/Kong/getkong.org/pull/554
Things to look for:
* Is the changelog complete?
* Changelog typos
* Double checking for the absence of breaking changes in the commits
* If enough time, double checking/testing the new features/fixes
**This officially closes the merging window for 0.11.2 as of today, 2017/11/27.**

release: 0.11.2

---

kong/cmd/quit.lua

The cli QUIT command would even on a forceful exit still print a 'graceful' message.

fix(cli) fix log to forceful shutdown

---

kong/cmd/utils/prefix_handler.lua
kong/tools/utils.lua

Handle a potential vulnerability in how we secured the Kong env file. Previously we chmod'd the file after writing the contents via penlight's wrapper of the Lua io lib, which in turn uses stdio. This allowed for a miniscule window in which the file contents could be read (fopen() creates files with 0666 octal permissions, as modified by the processes's umask).
The new behavior is to leverage the open() libc wrapper directly via FFI, which allows us to create the file with appropriate permissions from the outset.
* Open, write, and close the `.kong_env` file via libc wrappers around open/write/read syscalls (via FFI)

fix(cli) handle race condition in changing env perms

---

CONTRIBUTING.md

This PR proposes dropping the requirement to always align assignments for variables and table constructors. This will reduce `diff` noise caused by a variable change affecting a number of unrelated lines of code around it. This does not imply that judicious use of alignment of semantically-related concepts is now forbidden (we already use it successfully in the codebase for things other than assignments), it's just no longer a style requirement for every single table constructor and group of assignments.

style(contributing) drop assignment alignment rule

---

bin/busted

An alternative approach to solving the issue raised in PR #3066.
Bypass existing `KONG_*` environment variables when running Busted, replacing their values with `KONG_TEST_*` equivalents.

fix(tests) use KONG_TEST_* variables only in tests

---

bin/busted

A regression introduced by 67473d2 and #3075: the underlying `io.popen`
read syscall can easily be interrupted by the `SIGCHLD` signal returned
from the invoked shell (handled by NGINX, underlying the resty-cli)
interpreter.
This issue is discussed in several places:
* openresty/resty-cli#35
* luarocks/luarocks#732
An easy workaround for it is the fix proposed in one of the above
issues, in which we simply call our iterator in protected mode and
ignore the resulting Lua error from the uncaught `EINTR` error.

hotfix(tests) ensure bin/busted works on some platforms

---

kong/core/reports.lua
kong/dao/db/cassandra.lua
kong/dao/db/postgres.lua
kong/init.lua
kong/plugins/rate-limiting/policies/init.lua
spec/01-unit/01-db/02-cassandra_spec.lua
spec/01-unit/01-db/03-postgres_spec.lua
spec/02-integration/03-dao/01-factory_spec.lua

In order to offer better support for the different versions of each
database Kong is compatible with, we need to be able to make decisions
based on field usage data.
This commit adds the Cassandra/PostgreSQL/Redis version as part of the
PING signal, when `anonymous_reports` is enabled. We only retrieve the
first two digits of the version number to avoid high cardinality values
as much as possible, and to stay concise in our UDP packet.
We introduce tests for the version retrieval of both datastores
(PostgreSQL and Cassandra).
Unfortunately, there exist no tests for the reports `ping` signal, and
the `redis_version` retrieval is even more cumbersome to test. Those
have been tested manually for now (yuck).
and …

feat(reports) send database_version and redis_version

---

kong/core/reports.lua
kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua
spec/01-unit/013-reports_spec.lua

* Moved the Redis version tracking so it can be used in
response-ratelimiting, and any other plugin that may use Redis.
* Moved the tracking point from `increment` to `usage` to enable
tracking in scenarios when all clients have already reached their
limit.
* Unit tests for reports Redis tracking.
* We require the `kong.core.reports` module at the module level
regardless of the value of `anonymous_reports`, since it is already
done in the `core/handler.lua` module for now anyway.

feat(reports) abstract redis version tracking

---

kong/core/plugins_iterator.lua

mlcache does not catch errors coming out from a cache callback via the
traditional second return argument (yet). It only catches Lua errors
thrown by `error()`. This fixes a silent failure when such errors
happen in the plugins iterator, causing the HTTP 500 response to not be
sent.
Additionally, we take advantage of mlcache's native miss cache to remove
the need for a nil sentinel when our plugin query is a miss.

fix(plugins-iter) properly catch errors from the cache callback

---

kong/plugins/request-termination/handler.lua
kong/plugins/tcp-log/handler.lua
spec/01-unit/014-plugins_order_spec.lua

Work done in #3079 highlighted that tcp-log executed with a lower priority than request-termination. While this functionally has not presented a significant problem, this commit cleans up the prioritization of these plugins to a more sane definition. This has the added benefit of not requiring the request-termination define its own delayed callback function once #3079 is merged.
* Swap the priority definitions of the `tcp-log` and `request-termination` plugins
* Update the plugins order unit spec to reflect that `tcp-log` is prioritized accordingly

fix(*) invert tcp-log and request-termination priority

---

kong/core/plugins_iterator.lua
kong/init.lua
kong/plugins/acl/handler.lua
kong/plugins/oauth2/access.lua
kong/tools/responses.lua
spec/01-unit/009-responses_spec.lua
spec/02-integration/05-proxy/03-plugins_triggering_spec.lua
spec/fixtures/custom_plugins/kong/plugins/dummy/handler.lua
spec/fixtures/custom_plugins/kong/plugins/dummy/schema.lua

Background context
------------------
Prior to this change, if a plugin short-circuits a request (e.g. auth
plugin with HTTP 401, or rate limiting with HTTP 429) then plugins
running in the NGX_HTTP_LOG_PHASE would not be executed.
Arguably, this is an issue if one wishes to track such requests that are
short-circuited by Kong, i.e. via one of our available log plugins.
The purpose of this patch is to allow other plugins in general to run
after a plugin short-circuited a request in the access phase.
Underlying issue
----------------
Our current plugins' run-loop is implemented in such a way that it both
constructs the list of plugins to execute, and yields to its caller (for
loop) at the same time. Once yielded, a plugin is instantly executed by
the caller (for loop). If the plugin uses …

feat(core) execute subsequent phases upon short-circuited requests

---

kong-0.11.2-0.rockspec
kong/plugins/tcp-log/handler.lua
kong/plugins/tcp-log/migrations/cassandra.lua
kong/plugins/tcp-log/migrations/postgres.lua
kong/plugins/tcp-log/schema.lua
spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua
spec/helpers.lua

Support TLS connections for remote TCP servers in the `tcp-log` plugin.
* Add two new config options to `tcp-log`: `tls`, a boolean indicating whether to perform a TLS handshake against the remote server, and `tls_sni`, and optional string defining the SNI hostname to send in the handshake.
* Attempt to perform a TLS handshake when `tls` is true.
* Add support for TLS connections in the mock `tcp_server` helpers construct.

feat(tcp-log) TLS handshake support for TCP logs

---

Makefile

Detect the default OPENSSL_DIR include path based on the OS. The variable can still be explicitly overridden. This fixes a regression introduced by 54691fb.
This default definition for non-Darwin environments primarily targets Debian-based distros, benefiting the `kong-vagrant` environment.
* Define the `OPENSSL_DIR` default directive accordingly based on OS.

fix(makefile) proper OPENSSL_DIR defaults

---

kong/api/init.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua

Fixes issue when using empty body with supported content-types on POST / PUT / PATCH.
Fix #1182

fix(admin) unsupported media type (415) error reported on issue #1182

---

kong/api/routes/upstreams.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

The endpoints to list active and all Targets associated
with an Upstream have been changed as follows:
* `GET /upstreams/:upstream_name_or_id/targets/` now
lists only the active Targets instead of listing all The targets.
Previously, active targets were available at the endpoint
`/upstreams/:upstream_name_or_id/targets/active`, which is now
removed.
* `GET /upstreams/:upstream_name_or_id/targets/all` endpiont is
introduced, which returns a list of all the Targets (old and current).
Fix #2791 
* Update doc

feat(admin) change behaviour of GET target requests

---

.ci/run_tests.sh
kong-0.11.2-0.rockspec
kong/api/routes/upstreams.lua
kong/constants.lua
kong/core/balancer.lua
kong/core/handler.lua
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua
kong/dao/schemas/upstreams.lua
kong/init.lua
kong/templates/nginx_kong.lua
kong/tools/utils.lua
spec/01-unit/007-entities_schemas_spec.lua
spec/01-unit/011-balancer_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua
spec/fixtures/custom_nginx.template

Adds support for health checks in Kong. 
Health checkers can perform _active health checks_, periodically pinging a configurable upstream URL and checking for the HTTP status code, TCP errors and timeouts, and also _passive health checks_, checking these same signals on ongoing traffic, allowing for _circuit breaker_ functionality.
Major kudos to @Tieske for his work on [lua-resty-dns-client](https://github.com/kong/lua-resty-dns-client) and our joint work on [lua-resty-healthcheck](https://github.com/kong/lua-resty-healthcheck) (on which this is based), and to @thibaultcha for his reviews while this PR was in the making.
* Overhaul of the update flow for ring-balancer objects of upstream entities: instead of checking and updating balancer objects on-demand based on client requests, the …

feat(healthchecks) add active and passive health checks

---

kong/plugins/log-serializers/basic.lua
spec/01-unit/012-log_serializer_spec.lua

Reflecting back on #2445, the chosen names feel very redundant when
accessed from a queryable interface. The same way, `upstream_uri` seems
to have been wrongly added under the `request` scope, where it doesn't
belong.
This solution has the benefit of being less breaking as well. (Only one
field gets renamed).

hotfix(log-serializer) avoid redundant `request.request_*` properties

---

kong-0.11.2-0.rockspec

There are no changes for UUID v4 generation between 0.0.5 and 0.0.7, but
the 0.0.7 bump allows anyone to generate v3/v5 UUIDs.
See: https://github.com/thibaultcha/lua-resty-jit-uuid/compare/0.0.5...0.0.7

chore(deps) bump lua-resty-jit-uuid to 0.0.7

---

.travis.yml

When merging next into master, we will also bump our OpenResty versions.

chore(travis) bump OpenSSL and LuaRocks versions

---

kong/core/reports.lua
spec/01-unit/013-reports_spec.lua

This allows ping keys to be redefined every time send_report is
called.
* Execute the value of `_ping_infos` members as function when defined as a function.

feat(reports) execute defined ping values as functions

---

kong-0.12.0rc1-0.rockspec
kong/dao/schemas/upstreams.lua

To avoid unexpected behaviors for users, this makes the circuit-breaker functionality of passive healthchecks disabled by default. Users need to opt-in by supplying threshold values to enable the cut-off of targets based on analysis of ongoing traffic.
This commit requires functionality introduced in lua-resty-healthcheck 0.3.0 (version bump included in this PR).

hotfix(healthchecks) make circuit-breaker functionality off by default

---

kong/dao/migrations/cassandra.lua
spec/02-integration/03-dao/01-factory_spec.lua

Regression introduced by #3085.
This highlights the dangers of using the DAO in our migrations. While
each migration should be frozen in time and always considered valid given
its parents have previously run, using our DAO in the migrations
introduces a time factor as the DAO undergoes changes over time that
might make previously written migrations suddenly become invalid
(sometimes in worst cases than this, if the schema of entities has
changed).

hotfix(migrations) check major C* version against new field

---

Makefile

when updating dependencies without updating the rock versioning, old versions will not be removed. By explicitly removing the old version this is ensured.
Typical example when installing current `next` on top of `0.12.1`:
```
lua-resty-jit-uuid 0.0.7-1 is now installed in /usr/local (license: MIT)
Checking stability of dependencies in the absence of
lua-resty-jit-uuid 0.0.5-1...
Will not remove lua-resty-jit-uuid 0.0.5-1.
Removing it would break dependencies for:
kong 0.12.1-0
```
after the fix
```
lua-resty-jit-uuid 0.0.7-1 is now installed in /usr/local (license: MIT)
Checking stability of dependencies in the absence of
lua-resty-jit-uuid 0.0.5-1...
Removing lua-resty-jit-uuid 0.0.5-1...
Removal successful.
```

fix(deps) remove Kong before installing on `make dev`

---

spec/01-unit/011-balancer_spec.lua
spec/01-unit/013-reports_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

Remove a few calls that write unneeded debug/log data. This just cleans up the test output.
* Remove a missed `test_log` param from a balancer integration test
* Neuter `ngx.log` in a balancer unit test where `lua-resty-dns-client` wrote a `WARN` level entry
* Update the neutered `ngx.log` in the `reports` unit test to follow the same pattern as implemented here.

chore(tests) remove extraneous stdout/stderr output

---

kong/cache.lua
spec/02-integration/03-dao/10-cache_spec.lua

The callback run inside a `pcall` and the error checking will only deal with the `pcall` failing, not with a `pcall` success and returning `nil + err`.
This is temporary until the mlcache dependency is updated (upstream lib instead of a copy)

fix(cache) soft errors would not be handled properly by the cache

---

kong/core/balancer.lua

Makes sure to log the names and types tried to ease debugging dns problems.

fix(balancer) log the tries upon a dns error

---

kong-0.12.1-0.rockspec

Bump lua-multipart version from 0.5.1 to 0.5.4.
Fix #3024 
Fix #2981
Fix #2851
Fix https://github.com/Kong/lua-multipart/issues/12

chore(deps) bump lua-multipart version from 0.5.1 to 0.5.4

---

kong/core/reports.lua
spec/01-unit/013-reports_spec.lua

Add function to insert custom items in the immutable
portion of the report buffer.

feat(reports) custom immutable items

---

kong/cmd/migrations.lua
spec/02-integration/02-cmd/10-migrations_spec.lua

This -y|--yes flag allows for 'kong migrations' to run
non-interactively, and answer "yes" to all prompt questions, such as
"Are you sure?" from the 'reset' sub-command.

feat(cli) add --yes flag to 'kong migrations'

---

Makefile

Oftentimes, this command will fail because Kong is not installed. We now
avoid having to call make with the -k option as a workaround.
This is a regression introduced by 04f967b.

chore(makefile) ignore luarocks remove failures

---

kong-0.12.1-0.rockspec

This PR addresses https://discuss.konghq.com/t/bumping-to-more-recent-version-of-lua-resty-http/480 by upgrading the version of lua-resty-http to 0.12 (latest available version)
* Well, the only location I found referencing the `lua-rest-http` version is in the `kong-0.12.1-0.rockspec` ... but I don't know if directly updating this file is the right way to do. Pardon me if this is not !
https://discuss.konghq.com/t/bumping-to-more-recent-version-of-lua-resty-http/480

Bumping to lua-resty-http 0.12

---

CHANGELOG.md

This adds the current state of affairs regarding the two upcoming
releases of February/March.
We also remove the unused "Planned" section.

docs(changelog) add 0.12.2 and 0.13.0 releases

---

kong/core/balancer.lua

When a healthchecker is stopped, unregister its callback immediately, instead of waiting for the garbage collector to kick in and automatically reclaim it (as per the behavior of `register_weak`).
This does not modify the logic of health checks, but prevents bogus error messages from appearing in the error logs.
Thanks to @aledbf for the report!

fix(balancer) unregister healthchecker callback immediately

---

kong/core/balancer.lua
kong/core/handler.lua
spec/01-unit/011-balancer_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua
spec/helpers.lua

When upstreams include targets using hostnames instead of IPs, the initialization of balancer objects needs to perform DNS resolution, which involves opening a socket, which is not available in the init_worker phase.
~~This patch delays balancer initialization to the access phase.~~
**Updated**: This patch performs balancer initialization in a timer, which makes initialization asynchronous to worker initialization. For this reason, it adds a locking system to create_balancer to avoid race conditions when requests happen while the balancers are being initialized.
The locking system uses a simplified version of the `resty.lock` logic which does
not use the shm, since balancers are per-worker and we are concerned here only
with intra-worker concurrency control.

fix(balancer) async initialization of balancer objects

---

kong/plugins/statsd/schema.lua

- removed `required` attribute when default provided for fields
- schema update

fix(statsd) remove required attribute when default provided

---

kong/api/routes/kong.lua
kong/cluster_events.lua
kong/init.lua
kong/tools/public.lua
spec/02-integration/04-admin_api/01-kong_routes_spec.lua

Move the unique identifier of the Kong node from the `kong.cluster_events` module into an internal value, accessible via `kong.tools.public.get_node_id()`.
This way, the same unique identifier can be used for different features that need it, such as cluster events and identifying per-node data in health check reporting.

refactor(core) expose API to obtain node_id

---

spec/02-integration/05-proxy/09-balancer_spec.lua

This PR contains two commits that perform separate improvements for the stability of active healthcheck tests in our suite:
* **launch test server before starting active healthchecks** - When launching test `http_server` instances in the balancer tests, do so before enabling active healthchecks, to ensure that we get the expected results (and no failed checks before the server starts).
* **make sure http_server always times out** - Active healthchecks produce a constant flow of requests to the server, causing it to never timeout (in case of failed tests where the number of requests received does not match the list of requests expected). This turns the `timeout` argument into a hard limit for the execution time of the `http_server` itself.

tests(balancer) improve stability of active healthcheck tests

---

kong/core/balancer.lua
spec/01-unit/011-balancer_spec.lua

Adds a pair of functions, `subscribe_to_healthcheck_events` and `unsubscribe_from_healthcheck_events`, which allow tapping into the stream of healthcheck events.
As a bonus, this PR includes two other fixes in separate commits (7da9c6d, which gets rid of bogus error messages, and 2308284 which gets rid of the last references to `orderlist` in the code base).

feat(healthchecks) add subscriber API for tracking healthcheck events 

---

kong/api/routes/upstreams.lua
kong/core/balancer.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

**Note**: This is a work-in-progress.
This adds `/upstreams/:upstream_id/health`, an endpoint to report health of the targets of an upstream.
It returns the same contents of `/upstreams/:upstream_id/targets`, with the addition of a `"health"` field, which may return one of four values:
* `"not in balancer"` - target failed to be inserted into the  load balancer (usually because of DNS resolution error), target is therefore **not** in use by the load balancer
* `"healthchecks disabled"` - healthchecks are disabled, target is in use by the load balancer
* `"healthy"` - healthchecks are enabled, target is considered healthy by healthchecks, target is in use by the load balancer
* `"unhealthy"` - healthchecks are enabled, target is considered unhealthy by healthchecks, target is in **not** in …

feat(healthcheck) adding visibility to target health status

---

kong/api/endpoints.lua
kong/api/routes/routes.lua
kong/api/routes/services.lua
spec/02-integration/04-admin_api/20-routes_routes_spec.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

Adds two new Admin API endpoints:
- `/services/{service}/plugins`
- `/routes/{route}/plugins`
These endpoints support `GET`, `PUT`, and `POST` just like `/apis/{api}/plugins` does.
It is under new-model (routes and services) but uses old model on `/plugins` because plugins are still in old model. It doesn't add `/routes/{route}/plugins/{id}` (unlike `/apis({api}/plugins/{id}` because you can always just use `/plugins/{id}`.

feat(api) add /services/{service}/plugins and /routes/{route}/plugins

---

kong-0.12.1-0.rockspec
kong/core/balancer.lua

Update the dns client to 2.0, to fix several issues. For details see https://github.com/Kong/lua-resty-dns-client/blob/master/README.md#history
closes #3210

chore(dns) update dns client library

---

kong/core/balancer.lua
spec/01-unit/011-balancer_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

This fixes the behavior of the `/upstreams/:id/targets/:target/healthy` and `/upstreams/:id/targets/:target/unhealthy` endpoints when `:target` is of the form `hostname:port` (with a name instead of an IP).
The balancer testsuite is amended to perform all tests with both IPs and hostnames as targets.

fix(balancer) accept hostnames in post_health

---

kong/constants.lua
kong/dao/schemas/plugins.lua
kong/init.lua
spec-old-api/02-integration/04-admin_api/02-apis_routes_spec.lua
spec-old-api/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/23-deprecated_plugin_spec.lua

Currently user can use a plugin which is installed but not enabled, which can be confusing because next time user restart Kong, it will fail as plugin is not enabled.  So this change is to prevent that behavior. Now user would explicitly need to enable the plugin as a custom plugin to use it.
- added additional schema checks to prevent installed plugin to be applied
to an api if it's not enabled.
- added a list of deprecated plugins in Constants.lua
- log warning when using deprecated plugin
- added relevent tests

fix(plugin) checks for deprecated plugins

---

kong/cache.lua
kong/core/handler.lua
kong/mlcache.lua
spec/02-integration/03-dao/10-cache_spec.lua

This fixes a regression introduced in de6390e34c5301aa4c965d52f08e00ab81f91efa and released in 0.12.2 and 0.13.0rc1. It was reported in #3277 and investigated by @hishamhm and myself.
This PR takes a conservative approach at fixing the underlying issues: we introduce 3 commits from less to most disruptive, in an attempt to release a safe 0.12.3 hotfix:
- avoid generated-on-the-fly cache callback closure in the router cache
- use a different caching key for `soft_to_hard_error` wrapping closure that does not prevent the underlying callback from being GC'ed.
- backport an upstream mlcache feature to get rid of the (temporary) `soft_to_hard_error` wrapper workaround altogether (https://github.com/thibaultcha/lua-resty-mlcache/commit/4fdfbb976a9b4cda0f277ffc71294a14481a9c4d)

fix(core) remove a memory leak introduced in the DB caching

---

spec/01-unit/013-reports_spec.lua
spec/03-plugins/06-statsd/01-log_spec.lua
spec/03-plugins/08-datadog/01-log_spec.lua
spec/helpers.lua

This is done in two commits because there is a part that is common on `master` and `next`, and one that is `master`-specific.
* Adds arguments for number of packets and timeout value in helpers.udp_server
* Increases default TCP and UDP timeouts to 360 seconds as a safety net for CI slowness, but no test should be designed to wait for the entire timeout
* Removes all repeated instances of customized UDP servers that only differ in the number of packets received, making their behavior more consistent in the process.
This modifies tests for `statsd` and `datadog` in  `spec/`. Based on PR #3282.

[master] tests(*) improve timeouts and refactor duplication in udp/tcp tests

---

kong/api/init.lua

Not defaulting to Lapis error page when parameter is not a table.
* on_error accept non table parameters

fix(core) on_error accepts strings and numbers

---

kong/plugins/basic-auth/access.lua
spec/03-plugins/11-basic-auth/03-access_spec.lua

Story: I'm trying to migrate our current API to kong, and we have to support basic-auth with empty passwords, thus I opened this pr.
I think this is not a breaking change, and it's based on the `master` branch instead of the `next` branch.
Related to empty password basic auth
- https://svn.reviewboard.kde.org/r/1601/
- https://tools.ietf.org/html/rfc7617 (it didn't mention that password should be not empty)
* Add empty password support for basic-auth

feat(basic-auth-empty-password) allow empty password

---

kong/cmd/utils/prefix_handler.lua
spec/01-unit/003-prefix_handler_spec.lua

Prior to this patch, an error in the Penlight template for custom nginx
configurations would result in `compile_conf()` returning `nil`, which
would result in errors later in the execution path (trying to write a
`nil` value at `<prefix>/nginx-kong.conf` instead of a `string`).
This fix now catches errors returned by `pl_template.substitute`.

fix(cli) catch compilation errors of nginx config templates

---

kong/plugins/aws-lambda/v4.lua
kong/plugins/basic-auth/api.lua
kong/plugins/hmac-auth/api.lua
kong/plugins/jwt/api.lua
kong/plugins/key-auth/api.lua
kong/plugins/oauth2/api.lua
spec/03-plugins/10-key-auth/01-api_spec.lua
spec/03-plugins/11-basic-auth/02-api_spec.lua
spec/03-plugins/17-jwt/02-api_spec.lua
spec/03-plugins/20-hmac-auth/02-api_spec.lua
spec/03-plugins/26-oauth2/02-api_spec.lua

In some plugins (basic-auth, hmac-auth, jwt, key-auth, oauth2) we have path fragments which represent plugin fields that may contain spaces in their definitions. For example, if a username for basic-auth contains a space, for example, then it is reasonable to perform this request:
```
http ":8001/consumers/bob/basic-auth/John Doe/"
```
which, due to URL-encoding, results in a request to
http://localhost:8001/consumers/bob/basic-auth/John%20Doe/ --
we are currently returning 404 for those queries.
This patch performs URL-decoding on those path fragments, using `ngx.unescape_uri`.
It also modifies the test suites for these plugins using values with spaces for the relevant fields, and using the URL-encoded version of these fields when querying the Admin API.
Fixes #3247.

fix(plugins) urldecode path fragments which accept spaces

---

kong/meta.lua

Style fix . change a ternary operation by a simple "or" keeping the same behavior
meta.lua - change a ternary operation by an "or"

style(meta) use 'or' instead of ternary operator

---

kong/dao/schemas/upstreams.lua
spec/01-unit/007-entities_schemas_spec.lua

Check for the upper bound of all `timeout` and `interval` fields in the health check configuration.

fix(schemas) check upper bound on healthcheck time values

---

kong/dao/schemas/upstreams.lua
spec-old-api/01-unit/007-entities_schemas_spec.lua
spec/01-unit/007-entities_schemas_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua

Updates the default balancer size from 100 to 65535 (max size). The original size is to low as the advice is 100 slots for each target. 
This should have been included in #3220 since that implemented the performance (speed and footprint) improvement for the balancer to enable the new size default.
Related #3220

fix(balancer) update default size from 100 to 10000

---

kong-0.13.0rc2-0.rockspec

This update fixes the setting of defaults in `http_statuses` fields.

chore(deps) bump lua-resty-healthcheck to 0.4.0

---

kong/core/balancer.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

In the upstream event handler, `create_balancer` was being called with the object received via the event, which contains "id" and "name" only, and not the entire entity table containing the rest of the upstream fields. This caused it create a healthchecker with an empty configuration (ignoring the user's configuration), which then fell back into the lua-resty-healthcheck defaults.
This fix obtains the proper entity object from the id and passes it to `create_balancer`.
A regression test is included, which spawns two Kong instances and reproduces the error scenario described by @mengskysama.
This commit is against `master`, but can be cherry-picked against `next` with no conflicts.
Fixes #3304.

fix(balancer) use correct upstream object in event handler

---

spec/02-integration/02-cmd/02-start_stop_spec.lua

Since the removal of dnsmasq and serf there are no external dependencies any more.

tests(cli) remove unnecessary test

---

kong/cmd/start.lua
kong/cmd/utils/log.lua
kong/constants.lua
kong/dao/db/cassandra.lua
kong/dao/db/postgres.lua
kong/dao/factory.lua
spec/02-integration/03-dao/01-factory_spec.lua

Add a check to the DAO's `init()` method to ensure the compatibility of the underlying database (PostgreSQL or Cassandra). This check is ran:
1. In the `kong start` command
2. In `init_by_lua`
We support "minimum recommended version", and an _optional_ "oldest deprecated version", which as of today and 0.12.3 are:
PostgreSQL
- current minimum recommended: 9.5
- deprecated: 9.4
Cassandra
- current minimum recommended: 2.2
- deprecated: 2.1
---
When using a deprecated datastore, the CLI shows:
```
$ bin/kong start                 
2018/03/16 17:38:18 [warn] Currently using PostgreSQL 9.4 which is considered deprecated, please use 9.5 or greater
Kong started
```
It is also shown in the nginx logs when starting Kong from `nginx` (e.g. Docker images).
---
When using a version that is below the …

feat: check database version compatibility

---

spec-old-api/02-integration/05-proxy/09-balancer_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua
spec/helpers.lua

* Removes timed dependencies based on `ngx.sleep`: using the new `/health` endpoint, we can poll-wait on health changes and write tests that are timing-independent
* Avoids restarting Kong on every test: instead, this generates unique ids so that each test works on different entities.
Local results show a speed up from ~1min26s down to ~11s. :tada: 
The wrapper `describe` block is left unintented in the `spec-old-api` version to reduce `git diff` and to make the actual changes clearer (otherwise the whole file would be marked as changed). The one in `spec` is the one we will want to keep long-term and that one has been indented properly.
(Eventually we should remove the "postgres, cassandra" iteration from inside the tests anyway and just run one of each database in separate Travis jobs.)

tests(balancer) increase speed and reliability of balancer tests

---

kong/plugins/hmac-auth/access.lua
spec/03-plugins/20-hmac-auth/03-access_spec.lua

`ngx.var.uri` is normalized and so `ngx.var.request_uri` should be
used to get request origional uri with arguments
* signature generator logic now use ngx.var.request_uri to
get original request uri

fix(hmac-auth) use ngx var request_uri instead uri

---

kong/api/routes/plugins.lua

Make `remove_functions` produce a copy instead of modifying the plugin
schema table in-place.
FIxes #3222.

fix(admin) do not corrupt the plugin table when reading the schema

---

kong/constants.lua
kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua
kong/templates/nginx_kong.lua
spec/fixtures/custom_nginx.template

This is part of a series of fixes:
- https://github.com/thibaultcha/lua-resty-mlcache/pull/41
- https://github.com/thibaultcha/lua-resty-mlcache/pull/42
- https://github.com/Kong/kong/pull/3311
- https://github.com/Kong/kong/pull/3341
Context
-------
In the `local` mode of the rate-limiting plugins, storing the
rate-limiting counters in the same shm used by Kong's database cache is
too invasive for the underlying shm, especially when the rate-limiting
plugins are used with a `seconds` precision.
On top of exhausting the database cache slots, this approach also
generates some form of fragmentation in the shm. This is due to the
side-by-side storage of values with sizes of different orders of
magnitude (JSON strings vs. an incremented double) and the LRU eviction
mechanism. When the shm is …

fix(*) use dedicated shm for rate-limiting plugins

---

kong/plugins/ldap-auth/access.lua
kong/plugins/ldap-auth/schema.lua
spec-old-api/03-plugins/21-ldap-auth/01-access_spec.lua
spec/03-plugins/21-ldap-auth/01-access_spec.lua

Changes the way how LDAP cache key in constructed. Previously it didn't share cache with similarly configured LDAP plugins. And more importantly, it was broken when configured as a global plugin (that was reported with #3335)
* Implement cache key based on plugin configuration
Fix #3335

fix(ldap) cache key to work when plugin is configured globally

---

spec/02-integration/03-dao/07-ttl_spec.lua
spec/helpers.lua

* remove explicit uses of `ngx.sleep`, make tests rely on `wait_until` only.
* increase `wait_until` timeouts, to make them more resilient to slowness in CI environment
* lower ttl values in examples to make tests run faster
Update the internal `ngx` clock before calculating the start time of the `wait_until` loop. This also allows moving the `ngx.sleep` of the loop after the `pcall` (without the `ngx.update_time` at the top, some tests would break if `ngx.sleep` was done after the `pcall` as they were implicitly assuming that they ran with an updated clock).

tests(dao) increase speed and reliability of DAO ttl tests

---

kong/api/api_helpers.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

The `url` convenience property was parsed, but defaulted
to port 80, even for 'https' schemes. Updated to 443.
fixes #3357

fix(api) parsing service url default to 443 for https

---

kong/dao/db/cassandra.lua
spec/02-integration/03-dao/03-crud_spec.lua

Correctly serialize string based boolean values for Cassandra.
Filtering on boolean values through API queries would always result in a
list of truthy based results. This is because the value passed to
serialize_arg is of type string. This can be reproduced by issuing a
request against entities with true fields with a query filter of false.

fix(dao) properly serialize string booleans

---

kong-0.13.0-0.rockspec

This worker events release includes a fix in error handling, and improved stacktraces.

chore(deps) bump lua-resty-worker-events to 0.3.2

---

kong/core/reports.lua

This PR changes the level of logs occurs in reports.lua from `ngx.ERR` to `ngx.WARN`.
These errors won't (and shouldn't) stop kong from running, it's better to make them warnings.
* Change the level of logs in reports from ngx.ERR to ngx.WARN.

fix(reports) change log level of reports to ngx.WARN

---

kong/cluster_events.lua

If Kong fails to create a recurring timer when `poll_handler` is called, we now log this to `ngx.CRIT` level.
The reason of doing this is, if a recurring timer ever fails to create or start, any function that relies on this, like health check or cache invalidation, will stop working from then. This is a serious situation and deserves the CRIT level.
* Change log level to ngx.CRIT when recurring timer fails to start.

fix(cluster-events) log recurring timer failed to start to ngx.CRIT

---

kong/core/globalpatches.lua

This PR fixes an typo in `core/globalpatches.lua`.
* Change **ot** to **of**.

chore(core) fix a typo in comments of globalpatches.lua

---

kong/plugins/aws-lambda/handler.lua

This PR fixes a typo in the `aws-lambda` plugin.
* Change the request header `X-Amx-Log-Type` to `X-Amz-Log-Type`.

fix(aws-lambda) fix a typo in request headers

---

kong/dao/db/postgres.lua
kong/dao/factory.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/03-dao/01-factory_spec.lua

This fixes a regression introduced in #3310.
If the database is unreachabel when Kong start, it is our policy that
the error message be prefixed with `[postgres error]` (in the case of
PostgreSQL) to help the user troubleshoot the issue.
Prior to this patch, this behavior was changed in #3310, since it
introduced a call to `init()` in the CLI. Users would see:
```
$ kong start
Error: connection refused
```
Instead of:
```
$ kong start
Error: [postgres error] could not retrieve server_version: connection refused
```

hotfix(dao) ensure 'init()' errors are prefixed with DB name

---

kong/api/arguments.lua
kong/api/endpoints.lua
kong/api/init.lua
kong/api/routes/services.lua
kong/db/dao/init.lua
kong/db/schema/entities/services.lua
kong/db/schema/init.lua
kong/db/schema/metaschema.lua
kong/db/strategies/cassandra/init.lua
kong/db/strategies/postgres/connector.lua
kong/db/strategies/postgres/init.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua
spec/01-unit/000-new-dao/03-arguments_spec.lua
spec/02-integration/04-admin_api/20-routes_routes_spec.lua

This PR enhances our new model autogenerated Admin API in several ways:
1. It has more intelligent type inferring for `application/x-www-form-urlencoded` that takes into account information from schemas
2. It adds support for `endpoint_key` parameter in schemas that can be pointed to any unique field (allows us to e.g. autogenerate `/consumers/<uuid-or-username>`)
3. It adds proper `PUT` support (by `<uuid>` or by `<schema.endpoint_key>` (aka unique)
Fix #3378 
It will also close these when the respective entities are moved to new model:
Fix (or make obsolete) #3183
Fix (or make obsolete) #3168

feat(admin) implement inferring, endpoint key and put support

---

kong/db/strategies/postgres/connector.lua

Postgres strategy (new model) could result error like the below when running multiple subsequent Admin API calls rapidly (or parallel):
```
[error] 27206#0: *3351 lua coroutine: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:294: bad request
```

fix(db) postgres connector keepalive errors on load

---

kong/api_router.lua
spec-old-api/01-unit/010-router_spec.lua

Port of cd8b4df0bfb6e162056f7986502ffbce9b009f28 to the legacy API
router (backwards-compatible router for APIs).
Fix #3435

fix(api-router) support routing requests without Host header for HTTP/1.0

---

kong-0.13.1-0.rockspec

Updates worker-events to 0.3.3 to fix the timeout issue for some events at startup, see #3417.
Fixes #3417

chore(deps) bump lua-resty-worker-events to 0.3.3

---

kong/api/api_helpers.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

Fixes unexpected error on admin api when using invalid `url´ sugar attribute on services endpoints reported by @thefosk.
Fix #3448

fix(admin) empty url sugar attribute, see #3448

---

kong/api/routes/certificates.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua

Previously this method did create an extra certificate, but not the
accompanying SNI included on the URL. See the spec for details.

fix(api) correctly handle sni in PUT /certificates/foo.com

---

spec-old-api/02-integration/05-proxy/09-balancer_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua
spec/helpers.lua

The regression test for issue #3304 was flaky because it launches two
Kong nodes and it waited for the second one to be ready by reading the
logs. This is not a reliable way of determining if a node is
immediately ready to proxy a configured route.
Reversing the order of proxy calls in the test made it fail more
consistently, which helped debugging the issue.
This changes the check to verify if the router has been rebuilt,
using a dummy route for triggering the routing rebuild before the
proper test starts. (Thanks @thibaultcha for the idea!)
The changes are also backported to `spec-old-api/`.
This PR is against `master`, and it's good for pulling into `next` as well.

tests(healthchecks) fix flaky healthcheck test

---

kong-0.13.1-0.rockspec
kong/constants.lua
spec/01-unit/014-plugins_order_spec.lua
spec/01-unit/015-plugins_version_spec.lua

This PR only adds the plugin to the Kong installation. The plugin itself is external, see https://github.com/Kong/kong-plugin-azure-functions
Fixes #2652

Azure Functions plugin

---

kong/dao/migrations/cassandra.lua

ScyllaDB compatibility patch
Added an explicit `DROP INDEX`, because otherwise Scylla refuses to drop `nodes` with the following error:
```
migrating core for keyspace kong
Error: [cassandra error] Error during migration 2017-05-19-173100_remove_nodes_table: [Invalid] Cannot drop table when materialized views still depend on it (kong.{nodes_cluster_listening_address_idx_index})
```

ScyllaDB compatibility: explicitly drop index before dropping table

---

kong/api/routes/upstreams.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

The problem was that when an upstream health update in propagated via cluster events, only the upstream name (and not the id) was being forwarded. This resulted in `post_health` having the correct behavior in the Kong node where the `/healthy` or `/unhealthy` endpoint was used, but the information wasn't propagated to the cluster as advertised.
(The problem doesn't happen at worker level because the healthchecker objects coordinate among themselves.)
This PR changes the `balancer:post_health` cluster events message to include upstream id data.
This PR includes a regression test. Also, replaced hardcoded port numbers with variables in the multi-node tests.

fix(healthchecks) ensure health posted via cluster_events can be read

---

kong-0.13.1-0.rockspec

See https://github.com/Kong/lua-resty-dns-client#history for the changes in version 2.1.0.

chore(deps) bump DNS lib to 2.1.0

---

kong/runloop/balancer.lua
spec/01-unit/011-balancer_spec.lua

This bug was introduced when the loop to find `last_equal_index` was changed from looping the new targets list into looping the old targets list. Looping the old targets list is more efficient, but the logic for checking the index needed to be updated.
Includes a regression test that verifies that adding a target works and does not rebuild the balancer.

fix(balancer) avoid needless rebuild of balancer when adding target

---

kong-0.13.1-0.rockspec
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua
kong/dao/schemas/upstreams.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
kong/tools/utils.lua
spec/01-unit/004-utils_spec.lua
spec/01-unit/011-balancer_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

Add ability to hash on cookie. Per a [discussion on the feature suggestion board](https://discuss.konghq.com/t/support-sticky-sessions-for-websockets/937/9) with @Tieske , this adds a `cookie` option for the `hash_on` feature, which works very similarly to the `header option. The use case for this is to allow load balancing with cookie injection, creating a sticky session for API consumers who all behind the same NAT gateway. Specifically this is useful for websockets.
* Implement cookie source for hashing algorithm
* Upstream config can use `cookie` for `hash_on` and `hash_fallback` value
* Upstream config uses `hash_on_cookie` or `hash_fallback_cookie` for the name of the cookie to use
* Upstream config uses `hash_on_cookie_path` or `hash_fallback_cookie_path` to add the path to the …

Add hash on cookie

---

kong/init.lua
kong/plugins/log-serializers/basic.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
spec/01-unit/011-balancer_spec.lua
spec/01-unit/012-log_serializer_spec.lua

The `ctx` structure for storing balancer data grew over time to store much more than the address. This renaming reflects that. Also made the localized versions match the name (those `addr` locals that contained non-address data did confuse me back then when I started learning about the balancer!).
This also moves `balancer_hash_cookie` added by @PepperTeasdale inside that same structure.
Since at least one plugin did access `ngx.ctx.balancer_address` explicitly, I kept an alias around for backwards compatibility.
Also took the opportunity to tweak the style of the lines touched by this patch to make them fit in 80 characters.

refactor(balancer) rename balancer_address to balancer_data

---

kong-0.13.1-0.rockspec
kong/plugins/acl/groups.lua
kong/plugins/acl/handler.lua

Consumer groups are managed from the acl plugin. This refactor extracts the logic to access and validate the groups into a separate file exposing the functions.
Ideally the whole group feature (including endpoints for managing them) would be extracted from the acl plugin. But with the migration to the new DAO and the plugin SDK coming up I just disentangled the code. Leaving relocation of it up to the new DAO and SDK.
Functionally nothing changed.

[refactor] Extract group related functions from acl plugin

---

spec/helpers.lua

This doesn't look like it should have been necessary, but at least one strange CI failure could have been avoided by this: https://travis-ci.com/Kong/kong-private/jobs/126566137

tests(helpers) try harder to extract the OpenResty version

---

kong/conf_loader.lua
spec/01-unit/002-conf_loader_spec.lua

Nginx requires brackets in IPv6 addresses, but `normalize_ip` does not include them (due to backwards compatibility with its other uses elsewhere in the codebase).
Fixes #3475.

fix(conf) retain IPv6 brackets in proxy_listen and admin_listen

---

kong/plugins/ip-restriction/handler.lua
spec/01-unit/014-plugins_order_spec.lua

Raises the priority of the `ip-restriction` plugin to `3000` so that it runs before other plugins, after Zipkin, just as `bot-detection` does to prevent code execution that is not required. 
See: https://getkong.org/docs/0.13.x/plugin-development/custom-logic/#plugins-execution-order

fix(plugins) raise ip-restriction priority to 3000

---

spec-old-api/kong_tests.conf
spec/kong_tests.conf

Dnsmasq dependency was removed in v0.11.0.
This commit removes a harmless leftover config value from a configuration
file that is used to run Kong during tests.

chore(conf) drop 'dnsmasq' property form test config

---

kong/plugins/aws-lambda/schema.lua

Add us-gov-west-1 to the list of allowed regions to permit AWS Lambda
functions to be invoked from the AWS GovCloud region.
* Add us-gov-west-1 to schema of aws_region config in aws-lambda plugin

feat(aws-lambda) Add AWS Gov Cloud region to plugin schema

---

kong/error_handlers.lua
kong/meta.lua
kong/runloop/handler.lua
kong/tools/responses.lua
spec-old-api/02-integration/04-admin_api/01-kong_routes_spec.lua
spec-old-api/02-integration/05-proxy/12-server_tokens_spec.lua
spec/01-unit/001-rockspec_meta_spec.lua
spec/01-unit/009-responses_spec.lua
spec/02-integration/04-admin_api/01-kong_routes_spec.lua
spec/02-integration/05-proxy/13-server_tokens_spec.lua

Add `kong.meta._SERVER_TOKENS` and change codebase to use that everywhere.

refactor(meta) add meta._SERVER_TOKENS

---

kong-0.13.1-0.rockspec
kong/init.lua
kong/plugins/log-serializers/basic.lua
kong/resty/ctx.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/03-plugins_triggering_spec.lua
spec/02-integration/05-proxy/11-error_default_type_spec.lua
spec/fixtures/custom_nginx.template
spec/fixtures/custom_plugins/kong/plugins/error-handler-log/handler.lua
spec/fixtures/custom_plugins/kong/plugins/error-handler-log/schema.lua
spec/helpers.lua

Context
-------
Before this patch, several scenarios would make Kong/Nginx produce
errors that did not execute plugins:
1. Nginx-produced client errors (HTTP 4xx) on invalid requests per the
Nginx settings (e.g. headers too large, URI too large, etc...)
2. Proxy TCP/HTTP errors on the last balancer try (e.g. connection
refused, connection timeout, read/write timeout, etc...)
3. Any other Nginx-produced server errors (HTTP 5xx), if any
Because plugins are not executed in such cases, logging plugins in
particular do not get a chance to report such errors, leaving Kong
administrator blind when relying on bundled or homegrown logging
plugins. Additionally, other plugins, e.g. transformation, do not get a
chance to run either and could lead to scenarios where those errors
produce headers or …

feat(runloop) execute plugins on Nginx-produced errors

---

kong/init.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/09-balancer_spec.lua

Report both connection timeouts at the `balancer` phase and
upstream timeouts as `timeout` events when using passive healthchecks.
Previously, connection timeouts were being misreported as `tcp_failures`.
Upstream timeouts can now be caught due to recent runloop improvements for
executing plugins on Nginx-produced errors (#3533).
Includes regression tests for both cases.

fix(healthchecks) report timeouts on passive healthchecks

---

kong/templates/nginx_kong.lua

Likely the result of a merge gone wrong, since this value was added in
cbe4a612ee85b395d176ab85b38561a3839db183.

fix(nginx-conf) add missing 'default_type' directive

---

kong/db/schema/init.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/01-schema/03-routes_spec.lua

Thanks to @fffonion for reporting it and to @bungle for the fix!
Includes both a general regression test for the schema library and a regression test specific for the Routes entity.

fix(schema) catch properly when foreign keys are null

---

kong-0.13.1-0.rockspec

Changelog 2.0.2...2.1.0:
https://github.com/thibaultcha/lua-resty-mlcache/compare/2.0.2...2.1.0
Mainly useful to take advantage of the new `shm_locks` option.

chore(deps) bump mlcache to 2.1.0

---

kong/plugins/request-termination/handler.lua
spec/03-plugins/27-request-termination/02-access_spec.lua

Fix `request-termination` delayed response

fix(request-termination) delayed response

---

kong/cache.lua
kong/templates/nginx_kong.lua
spec/fixtures/custom_nginx.template

This commit introduces a new shm, `kong_locks`, to be used by instances
of lua-resty-lock across Kong or its libraries, if possible.
Since #3543 bumped the mlcache dependency, the DB cache is the first
consumer of this shm to store its locks, which helps in limiting the
effects of LRU churning in certain workloads. More components should use
this shm to store their resty-lock instances, especially instead of
relying on the `kong` shm, which is to be considered "immutable".
The chosen size for this shm is 8Mb:
1. In the not too far future, users should be able to customize the size
of _any_ shm via configuration properties. Some additional work on top
of #3530 is needed for this.
2. Such a size allows to store (based on estimations with a test script)
about 65.000 lua-resty-lock items. …

feat(nginx-conf) add a 'kong_locks' shm for resty-lock users

---

kong-0.13.1-0.rockspec

Bump `azure-functions` plugin to `0.1.1`.
Related to this (do not merge before):
https://github.com/Kong/kong-plugin-azure-functions/pull/1

chore(azure-functions) bump to 0.1.1

---

kong-0.14.0rc2-0.rockspec
kong.conf.default
kong/cache.lua
kong/conf_loader.lua
kong/globalpatches.lua
kong/init.lua
kong/runloop/plugins_iterator.lua
kong/templates/kong_defaults.lua

* Bump mlcache to 2.2.0
This new version adds support for `resurrect_ttl`, which resurrects
stale values when the callback fails on soft errors.
https://github.com/thibaultcha/lua-resty-mlcache/blob/master/CHANGELOG.md#220
* add a new 'db_resurrect_ttl' config option
Documentation for its behaviour can be read in the description test
included in kong.conf.default.
* do not throw error from plugin loader
In order for the resurrection of stale cached values to occur when
callback I/O fails (see c932dc6), we have to return soft errors from our
callbacks, and not throw them via error().
Additionally, we rely on the modern behavior of mlcache with regards to
the caching of cache misses - returning `nil` is cached my mlcache.

feat: new 'db_resurrect_ttl' configuration property + resilient cache callbacks 

---

Makefile

Fixes compiler warnings on some newer platforms. Warnings occur on the Vagrant box since it was bumped to the Ubuntu Xenial64 image.
Compiler warnings on some newer platforms resolved. Especially the Kong-Vagrant box.

chore(deps) bump llthreads library, test-only dependency

---

kong-0.14.0rc3-0.rockspec

This version ensures the new request-aware LB policies can be used in
init_by_lua* contexts when using the lua-resty-core module.
Changelog:
https://github.com/thibaultcha/lua-cassandra/blob/master/CHANGELOG.md#131---20180702
Fix #3580

chore(deps) bump lua-cassandra to 1.3.1

---

kong/init.lua
spec/fixtures/custom_plugins/kong/plugins/logger-last/handler.lua
spec/fixtures/custom_plugins/kong/plugins/logger/handler.lua

Nothing guarantees that `plugin.handler._name` is properly set in
plugins if they do not inherit the base_plugin.lua class. This is the
case with the `reports.lua` module, which is built as a plugin but not
inheriting from the base_plugin.lua class.
Since anonymous reports are disabled in all development/CI environments,
this issue was not caught immediately, but an error logs complaining that
arg #2 of the `set_namespaced_log()` function was nil would show up in
the error logs.
Instead, we we `plugin.name` which, as per the `load_plugin()` function,
is guaranteed to be set even when plugins do not inherit from the
base_plugin.lua class.

hotfix(runloop) use proper property to set log namespace

---

kong-0.14.0rc3-0.rockspec

Unpin the patch version (x.y.Z) version numbers of bundled plugins,
so that users can install strictly-bugfix releases using
`luarocks install <plugin-name>`.

chore(rockspec) unpin patch version numbers of plugins

---

kong/db/schema/init.lua
kong/db/schema/metaschema.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua

Includes a regression test in the metaschema testsuite, and a testcase in the
schema testsuite (which demonstrates that the nested records issue was a
metaschema-only problem).
Includes some minor corrections to the metaschema specification, detected
using the metaschema to attempt to validate itself... unfortunately the schema
validator doesn't implement a type system strong enough to fully validate the
metaschema without falling into an infinite loop -- in fact, the schema library isn't strong enough to validate schemas without having the metaschema
"cheat" and perform some of its validation of schemas using the
`check` escape-hatch function to recurse into records, as we see in this
commit. This is by design, because the schema library is meant to be only as complex as necessary for …

fix(schema) fix validation of nested records in metaschema

---

kong/db/schema/metaschema.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua

Adds support for entity schemas for `ttl = true` and `ttl = false` which enables or disables `ttl` support for the entitity.
This is first PR in series of PRs that implement the `ttl` support in new model.

feat(schema) add support for ttl

---

kong/init.lua
kong/plugins/log-serializers/basic.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua

* localizes `kong` global access on `handler`
* removes `regex` for simple `string.sub`
* passes `ngx.ctx` to `plugins iterator`
* passes `ngx.ctx` to `balancer`
* optimizations on `basic` serializer (mainly `ngx.ctx` localization)
* reduces some nesting in `handler`

refactor(runloop) ngx.ctx usage optimizations and other small changes to runloop and related

---

.travis.yml

to reduce the travis queue lets only run travis on master and next branches and all PR merge results

misc(travis) only run travis on master and next branches

---

kong/plugins/ldap-auth/access.lua
kong/plugins/ldap-auth/asn1.lua
spec/03-plugins/21-ldap-auth/01-access_spec.lua
spec/03-plugins/21-ldap-auth/02-invalidations_spec.lua

This PP fixes two issues with plugin:
- One where request added negative cache for incorrect password.
- Second when request results in 500 when very long password being used. Now `%` used instead of `bin.mod` as `bin.mod` does not exist

fix(ldap-auth) remove bin.mod and negative cache

---

Makefile

Git clients on Windows tend to convert line endings to Windows
format, such that Windows editors can be used (is reverted on commit).
This doesn't work if mounting those files from a Unix machine for
development for example (Kong-Vagrant). Lua is agnostic to the format,
but the Unix shell is not. Hence only the scripts in `./kong/bin` are
affected.
This change will have the makefile automatically convert those scripts
back to Unix format. This allows Windows users to work on the Kong code
and custom plugins without other configuration.
Fix https://github.com/Kong/kong-vagrant/issues/84

chore(dev) auto-convert Windows line-endings

---

kong/api/endpoints.lua
kong/api/init.lua
kong/db/dao/init.lua
kong/db/init.lua

`kong.db.errors` module did not receive name of the strategy and `dao:each` didn't handle database errors correctly.

fix(db) kong.db.errors module did not receive name of the strategy

---

spec-old-api/03-plugins/02-udp-log/01-udp-log_spec.lua
spec-old-api/03-plugins/08-datadog/01-log_spec.lua
spec-old-api/03-plugins/10-key-auth/01-api_spec.lua
spec/03-plugins/02-udp-log/01-udp-log_spec.lua

This PR cleans 2 flaky tests.
* join an opened thread to clean test environment
* Allow 1 extra ms more for a test to pass (probably an split ms
issue)
* More verbose logging in case of failure starting Kong

fix(tests) fix flaky tests

---

kong/globalpatches.lua

When connecting to unix domain socket, port parameter should not
be passed to tcpsock:connect or udpsock:connect
* globalpatches of ngx.socket to connect to unix domain socket
Fix #3626

fix(globalpathces) ngx socket connect to unix domain socket

---

.ci/trigger-travis.sh
.travis.yml

Uses a private github repository that builds / releases kong artifacts via travis-ci
- I made / pushed a tag
- The travis deploy stage here ( https://travis-ci.org/Kong/kong/jobs/401935053 ) successfully
- Triggered the kong-distributions build ( https://travis-ci.com/Kong/kong-distributions/builds/78491101 )
- Which I killed because I didn't want it to actually build / publish the artifacts
- Deleted the stray tags

misc(travis) use travis-ci to build / release kong

---

kong/db/schema/init.lua
kong/db/schema/metaschema.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua

This resolves three difficulties that would appear when porting the Plugins entity over to the new DAO: loading the plugin configuration schema dynamically, the fact that this schema depends on a value of the entity row itself, and the fact that the specific plugin type can impose further constraints on values.
The old DAO implemented this by allowing records to have a `schema` field that would be either a table or a function evaluated at validation time, and using an ad-hoc validation that checked for a `no_consumer` field to restrict the value of `consumer_id` to `null`.
The new DAO implements this by allowing an entity (such as Plugins) to declare that it is extensible via **subschemas**:
* a schema may declare that it allows subschemas, tagged by one specific string key of the schema, …

feat(schema) add support for subschemas

---

kong/db/init.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/04-admin_api/20-routes_routes_spec.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

Since recently, we call the new DAO's `assert(db:init_connector())` in
the CLI _before_ instantiating the old DAO (because the latter needs the
former as an attribute).
For Cassandra, this has the effect of retrieving the cluster's topology,
and thus trying to connect to the given contact points. If any error is
encountered, the new DAO does not properly prefix the error with the
`[Cassandra error]` prefix, as the old DAO would do. This goes unnoticed
for the PostgreSQL strategy since the connector initialization is
nopping.
See a related CI failure here:
https://travis-ci.com/Kong/kong-private/jobs/136391637#L1094
We now prefix connector errors (which are always strings). We also include the strategy in the reported error, as it should have always been, but was missing due to the lack of …

fix(cli) prefix Cassandra connector errors in new DAO

---

t/01-pdk/08-response/00-phase_checks.t

This function never generates an OpenResty error.

tests(pdk) fix phase checks for kong.response.get_source

---

.ci/trigger-travis.sh

add rhel:6, rhel:7 and amazonlinux to the trigger-travis job that builds kong

feat(nightly) make rhel:6/7 and amazonlinux nightly as well

---

spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/04-admin_api/20-routes_routes_spec.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

**Note:** `next` is currently broken because tests expect `strategy` to appear but the code doesn't produce it; this is one possible solution: changing the tests. The other one is in an alternative PR, #3671 — one should be merged, the other dropped. :)
About this PR:
Error tables returned by the new DB calls now include the strategy:
https://github.com/Kong/kong/commit/9f5102fbcb05c53fdb0df9d178ab92630384d43b
But the Admin API cleans them up:
https://github.com/Kong/kong/blob/next/kong/api/endpoints.lua#L34-L36
This adjusts the tests to not expect `strategy`.

tests(admin) fix tests assuming the strategy is printed on errors

---

kong/conf_loader.lua
spec/fixtures/deprecated_custom_plugin.conf

Only warn if the plugins listed in `custom_plugins` were not already in `plugins`.

fix(conf) drop custom_plugins warning if already using plugins

---

kong-0.14.0-0.rockspec

This PR bumps lua-resty-healthcheck version to 0.5.0. The 0.5.0 version includes https active checks.
* Bump lua-resty-healthcheck version

Bump lua-resty-healthcheck version

---

kong/globalpatches.lua
spec/02-integration/06-invalidations/01-cluster_events_spec.lua

Prior to this change, the shm retrieved as a result of the very first
`ngx.shared.<shm>` reference would be different than the one retrieved
in subsequent references to `ngx.shared.<shm>`.
This is an issue since the data stored by each of these mock shms is
stored in instances of themselves, therefore several references to
`ngx.shared.<shm>` could hold different data - which is breaking
compared to the real behavior of shms.

fix(globalpatches) properly cache mock ngx.shared dicts

---

kong-0.14.0-0.rockspec
kong/resty/getssl.lua

This allows fetching the `SSL*` object for the current client as a luaossl object

 feat(core) add kong.resty.getssl module 

---

kong/db/init.lua
kong/db/strategies/cassandra/connector.lua
kong/db/strategies/connector.lua
spec/02-integration/000-new-dao/03-db_cluster_mutex_spec.lua

This function can be called to set a cluster-wide lock (via the
underlying DB, currently C* only) to execute some code in a
"cluster-wide mutex".

feat(db) implement the db:cluster_mutex() utility

---

kong/api/endpoints.lua
kong/api/routes/consumers.lua
kong/db/dao/init.lua
kong/db/errors.lua
kong/db/init.lua
kong/db/schema/metaschema.lua
kong/db/strategies/cassandra/init.lua
kong/db/strategies/connector.lua
kong/db/strategies/postgres/connector.lua
kong/db/strategies/postgres/init.lua
kong/init.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua
spec/01-unit/000-new-dao/02-db-errors_spec.lua
spec/02-integration/000-new-dao/02-db_core_entities_spec.lua
spec/02-integration/04-admin_api/20-routes_routes_spec.lua

* Implements TTL support in Cassandra strategy
* Implements TTL support in Postgres strategy
* Implements TTL support in Generic DAO
* Implements TTL support in Admin API Endpoints
* Implements TTL cleanup timer for Postgres strategy
* Renames `kong.db.init_connector` to `kong.db.init`

feat(db) implement ttl support for kong.db and new admin api

---

kong/db/dao/init.lua
kong/runloop/handler.lua

This function can return one of:
1. `true, nil`
2. `nil, err`
3. `false, nil`
Case 3. occurs when the library is already polling, likely in situations
with busy Admin API workloads. Because our return values check were
incorrect, some error logs would appear such as:
```
[error] 32#0: *6883 [lua] handler.lua:218: [events] could not broadcast crud event: nil, client: 10.x.x.x, server: kong, request: "POST /auth/oauth2/token HTTP/1.1"
```

fix(*) properly check worker_events.post_local() ret values

---

kong-0.14.0-0.rockspec

This release fixes an issue encountered in environments with DNS
load-balancing in effect for contact_points provided as hostnames (e.g.
Kubernetes with `contact_points = { "cassandra" }`).
This could result in `no host details for <peer IP>` errors when using
multiple instances of the Cluster module.
Changelog:
https://github.com/thibaultcha/lua-cassandra/blob/master/CHANGELOG.md#132

chore(deps) bump lua-cassandra to 1.3.2

---

kong/plugins/ldap-auth/access.lua
kong/plugins/ldap-auth/ldap.lua
spec-old-api/03-plugins/21-ldap-auth/01-access_spec.lua
spec/03-plugins/21-ldap-auth/01-access_spec.lua
spec/03-plugins/21-ldap-auth/02-invalidations_spec.lua

This change adds password as part of cache key, doing so
we can cache invalid credential without blocking valid credential
*  Update cache key generation logic to use password
*  Update invalidation spec to test changes
*  Minor log refactor

fix(ldap-auth) use username, password for cache key

---

kong/plugins/acl/handler.lua
kong/plugins/acl/schema.lua
spec/03-plugins/19-acl/02-access_spec.lua

As discussed here : https://github.com/Kong/kong/issues/3609
One of my biggest concerns with Kong's ACL functionality as it stands today is including the arbitrarily growing in size list of a consumers entire ACL groups as a header. In our specific implementation of Kong every route gets is own ACL group as the routes existing uuid, so we can then give consumers access to specific routes by adding that uuid to their ACL, I suspect this will be a popular pattern going forward for many users who implement Kong. 
I propose a boolean that will act as a switch and enable/disable sending the consumer groups as a header, as I suspect for plenty of use cases that the arbitrary group info in the header is not necessary and as it grows in size could one day break an otherwise working proxy by …

Optional X-Consumer-Groups ACL Header Improvement

---

kong/plugins/acl/handler.lua

Update to reduce Kong memory pressure when ACL X-Consumer-Groups header has been hidden as suggested by @Tieske . Related to Original PR https://github.com/Kong/kong/pull/3703
* Modify kong/plugins/acl/handler.lua to_be_blocked = nil if conf.hide_groups_header enabled.
Improve memory footprint with ACL plugin.

Optional X-Consumer-Groups ACL Header Improvement, secondary memory footprint enhancement

---

.travis.yml

the travis docs are a little ambiguous :(
travis uses travis-conditional for `if` logic that's applies to builds, stages and jobs but the deploy job `on` conditional has it's own way of working.
Since we're using `if` per the `travis-conditional` library documentation
```
The following known attributes are available:
type (the current event type, known event types are: push, pull_request, api, cron)
```
**References**
https://github.com/travis-ci/travis-conditions
https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

fix(ci) adjust deploy condition per travis docs

---

kong/plugins/hmac-auth/access.lua
spec/03-plugins/20-hmac-auth/03-access_spec.lua

Add deprecation transition for PR #3339 by adding support for older signatures generated from `request-line` without the query_string. This is intended to be a patch on 0.13.1 but may apply to 0.14+ although I haven't tested this. 
* add deprecation hmac-auth transition for pr #3339 
Fix #3672

fix(hmac-auth) add deprecation transition for pr #3339

---

kong/api/endpoints.lua
kong/db/dao/init.lua
kong/db/dao/snis.lua
kong/db/strategies/cassandra/init.lua
kong/db/strategies/postgres/init.lua
kong/runloop/handler.lua
spec/02-integration/000-new-dao/02-db_core_entities_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua

This PR fixes the behavior of Kong `master` by making sure it always iterates over all SNIs.
The source of the problem was that the `:for_*` functions were being used at times as a "select" function, i.e., ignoring the fact that it returns a page at a time and not the full results. My approach was then to begin with a refactor, renaming these functions to `:page_*` (i.e. `routes:page_for_service` etc.), so that this distinction becomes harder to miss in the future. 
Then, I added an iterator variant, `:each_for_*` (the page-for method was renamed aiming to get some symmetry with the each-for) — the implementation of `:each_for_*` reuses the logic of `:each` (which was refactored to be done at the generic-DAO level, because the implementation in both strategies was essentially identical: a …

fix(db) iterate through all SNIs

---

kong/plugins/ldap-auth/migrations/cassandra.lua
kong/plugins/ldap-auth/migrations/postgres.lua

Hard coding header default so that schema can change in later versions of Kong without affecting behavior of migration.

fix(ldap-auth) hardcode ldap header so schema can change

---

.ci/run_tests.sh
.travis.yml

Separate parallelized builds for
```
postgres vs cassandra2.2 vs cassandra3.9 
X
integration vs plugin vs old-integration vs old-plugin
```
result is a build time (wall clock) of ~15-20min depending on cache etc

feat(ci) parallelize travis builds

---

kong/pdk/service.lua
t/01-pdk/06-service-request/01-set_scheme.t
t/01-pdk/06-service-request/09-set_header.t
t/01-pdk/06-service-request/10-add_header.t
t/01-pdk/06-service-request/12-set_headers.t
t/01-pdk/09-service/01-set-upstream.t
t/01-pdk/09-service/02-set-target.t
t/Util.pm

The PDK and PDK tests were still using the old `balancer_address`
structure name (renamed in fe834e7c64767446546dcc6e640f1c66485740d3).

chore(*) rename 'balancer_address' to 'balancer_data'

---

kong-0.14.1-0.rockspec
kong/api/arguments.lua
kong/api/crud_helpers.lua
kong/api/endpoints.lua
kong/api/init.lua
kong/dao/factory.lua
kong/dao/migrations/cassandra.lua
kong/dao/migrations/postgres.lua
kong/db/dao/init.lua
kong/db/errors.lua
kong/db/init.lua
kong/db/schema/entities/apis.lua
kong/db/schema/entity.lua
kong/db/schema/init.lua
kong/db/schema/metaschema.lua
kong/db/schema/typedefs.lua
kong/db/strategies/cassandra/init.lua
kong/db/strategies/postgres/init.lua
kong/runloop/handler.lua
spec-old-api/02-integration/03-dao/09-cache_key_spec.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua
spec/02-integration/03-dao/09-cache_key_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua

This is the first half of the work porting the Plugins core entity to kong.db — Plugins is the last pending core entity using the old DAO; after this, the only core entity using the old DAO will be the deprecated Apis entity, as well as the non-core entities from Plugins, which are on the way to being ported as well.
This PR contains a number of features and fixes needed to port Plugins to `kong.db`, the new DAO infrastructure. This contains all the work that can be merged prior to "flicking the switch" and deleting the entity from `kong.dao` and adding the entity in `kong.db`.
This contains the minimal changes to the test suite to keep tests passing. Tests exercising the new behaviors added will appear in the second PR, in which the Plugins entity is ported over.

Groundwork for porting the Plugins core entity to kong.db

---

kong/db/schema/entity.lua
kong/db/schema/init.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/04-dao.lua

This PR proposes new semantics for handling missing or unset values arriving from the strategies. With this PR, the DAO will apply the default values if a strategy returns a column as `ngx.null` and is marked as `nullable = false` in a schema. We also make records in entities non-nullable by default, so that we always recurse their structure, filling defaults for their fields.
This will allow us to produce default values in newly-added columns without requiring a migration filling the table with default values.

feat(db) make schema set fields to default if missing from DB 

---

kong/api/arguments.lua
spec/01-unit/000-new-dao/03-arguments_spec.lua

Fixes inferring record fields on Admin API when using `application/x-www-form-urlencoded`.
This was originally proposed in
#3710 
And this is one of the series of PRs that were previously implemented in that branch.

fix(admin) inferring of arguments for record types

---

kong/db/dao/certificates.lua
kong/db/dao/consumers.lua
kong/db/dao/init.lua
kong/db/dao/plugins.lua
kong/db/dao/snis.lua
kong/db/dao/targets.lua
kong/db/strategies/cassandra/init.lua
spec/fixtures/blueprints.lua

Refactored `kong.db.dao` to be more consistent with the options table.
This was originally proposed in
#3710 
And this is one of the series of PRs that were previously implemented in that branch.

refactor(db) a more consistent options handling

---

.ci/setup_env.sh

This is a cherry-pick of https://github.com/Kong/kong/commit/4cfd5668b57174b7fbb401cc97bf317d30a70071 off of next to master so OpenResty / OpenSSL avoid the problem described here https://forum.nginx.org/read.php?2,279002 which we are experiencing on master

chore(ci) dynamically link OpenResty against OpenSSL

---

kong/api/arguments.lua
kong/api/init.lua
spec/02-integration/04-admin_api/02-apis_routes_spec.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/04-admin_api/09-post_processing_spec.lua
spec/02-integration/04-admin_api/20-routes_routes_spec.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

This adds `multipart/form-data` support to Admin API. But this is not a 100% solution as there turns our to be edge cases because of Lapis Framework that are not very easy to solve without rather complex changes.
How Lapis Reads the `multipart/form-data`:
1. On OpenResty Lapis uses `lua-resty-upload` to stream read `multipart/form-data` upload.
2. `lua-resty-upload` consumes the request body without writing it back, which means that you cannot read request body in our `arguments` parser.
3. That means that only place we can access `multipart/form-data` params in admin api is through Lapis `self.req.params_post`.
4. Lapis in turn does parsing of `multipart/form-data` to a key/value table. And because of that you cannot send same name in `multipart/form-data` twice, e.g. `paths=/first` and …

feat(admin) add multipart/form-data support to admin api (80% solution)

---

kong/db/strategies/postgres/connector.lua

Fixes unfortunate bug in Postgres `TTL` cleanup  timer where it tried to delete rows from tables that didn't have `ttl=true`.

hotfix(db) postgres ttl cleanup timer

---

kong-0.14.1-0.rockspec

See 0.2.0 changelog:
https://github.com/Kong/kong-plugin-prometheus/blob/master/CHANGELOG.md#020---20180924
Bump and pin Prometheus plugin to 0.2.0
The change is going into the `next` branch since some redundant metrics are being dropped.

chore(deps) bump kong-prometheus-plugin to 0.2

---

kong/tools/public.lua
spec/03-plugins/23-aws-lambda/01-access_spec.lua

Empty tables are decoded as empty json arrays instead of emtpy
objects.

fix(aws-plugin) handle empty json arrays

---

spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua
spec/03-plugins/02-udp-log/01-udp-log_spec.lua

In some cases, there's 1 split ms that makes the test fail.
Allowing for 1 extra ms.

test(tcp-log-plugin) fix flaky test

---

kong/db/dao/plugins.lua

Fixes a small mistake in chained table access.
See #3809.

fix(db) fix crash in legacy schema converter

---

kong/api/endpoints.lua
kong/api/routes/snis.lua
kong/api/routes/targets.lua

This is a minor refactor that adds a utility function `endpoints.not_found` to be used when overriding an auto-generated endpoint to make it return 404 at all times.
This causes no functional change, but makes the specifications a bit more declarative, which makes it easier to inspect for deactivated endpoints.

refactor(api) make deactivated endpoints more declarative

---

kong/runloop/handler.lua

Complementary commit for:
* 11d69be feat(conf) add 'pg_timeout' property
* 85946ba perf(router) wrap router rebuilds in a worker mutex
We now use the configured timeout for PostgreSQL as the timeout to our
router rebuild semaphore. Note that the default value of `60` is
preserved to be friendly to any fork out there that may support other
configuration backends.
See #3794
See #3808

feat(core) use 'pg_timeout' as router rebuild semaphore timeout

---

kong/db/strategies/postgres/connector.lua

This is merely a safe guard, previously we had just:
`WHERE ttl < CURRENT_TIMESTAMP`
on old record cleanups, and  now we have:
`WHERE ttl < CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`
Everywhere else this was already the case. These two places just didn't have that.

fix(db) postgres ttl related where clauses to be more explicit about CURRENT_TIMESTAMP

---

kong-0.14.1-0.rockspec
kong/pdk/init.lua
kong/pdk/node.lua
t/01-pdk/12-node/00-phase_checks.t
t/01-pdk/12-node/01-get_id.t

This new module provides node-level utilities, such as
`kong.node.get_id()`, which is a replacement to the old
`kong.tools.public` module's `get_node_id()` utility.
Reminder: the `kong.tools.public` module is to be stripped away for the
1.0 stable release.
This new implementation **throws** errors instead of returning them, for
two reasons:
1. Simplicity of usage: now that this function is exposed for public
consumption (and already used by plugins such as Zipkin), avoiding for
the need to check for errors simplifies its usage.
2. If such an error occurs, it will be during the initialization of the
master process, and will then properly prevent Kong from starting. At
runtime, no such error should occur since the id is cached, but if they
do, they should be very obvious and provide their …

feat(pdk) add kong.node module with '.get_id()' util

---

kong/plugins/cors/handler.lua
spec/03-plugins/14-cors/01-access_spec.lua

When Access-Control-Allow-Origin is not *, the cors plugins normally
sets Vary=Origin.  In the case where the plugin sets
Access-Control-Allow-Credentials the Vary=Origin is missing.
When that happens, the browser is told to uses its cache even when the
origin is different and then CORS fails by rejecting the non-matching
origin.

fix(cors) set missing vary=origin

---

kong/db/dao/init.lua

Fixes issue that was in some cases, e.g. with `ACLs` leading to `nil` cache key, with requests like:
```
http put :8001/consumers/demo/acls/group
```
Also makes it consistent to always use `entity_to_insert|update|upsert` as it was sometimes using just `entity`(which might be lacking autogenerated `id` for example).

hotfix(db) cache_key was not always calculated correctly

---

kong/db/schema/entities/certificates.lua
kong/db/schema/typedefs.lua
spec/01-unit/000-new-dao/01-schema/03-typedefs_spec.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua

Adds `certificate` and `key` typedefs
Used by the forthcoming service mesh CA entity.
However also useful for validating e.g. certificate entity.

feat(schema) add `certificate` and `key` typedefs

---

kong/db/schema/init.lua
kong/db/schema/metaschema.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua
spec/03-plugins/08-datadog/02-schema_spec.lua

Allows a user function to perform a cross-field check:
```lua
{
fields = {
{ aaa = { type = "string" } },
{ bbb = { type = "string" } },
{ ccc = { type = "number" } },
},
entity_checks = {
{ custom_entity_check = {
field_sources = { "bbb", "ccc" },
fn = function(entity)
assert(entity.aaa == nil)
if entity.bbb == "foo" and entity.ccc == 42 then
return true
end
return nil, "oh no"
end,
} }
}
```
Note that only the fields specifying in `field_sources` are visible
to the `entity` table received by `fn` (this is to allow partial
updates to work properly -- the check is skipped if none of the
fields in `field_sources` is being updated).

feat(schema) introduce custom_entity_check

---

kong/db/schema/init.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua

This is inspired by #3846.
For the generic checkers we had so far, running them on invalid fields and
reporting everything at once was okay, and avoided the "get one error, fix
thing, get another error" experience. But for a custom checker, it's safer to
only run it on valid fields (especially thinking of making things less
error-prone for third-party plugin authors).
The commit is lengthy because the `errors` table is now passed along
and is used to check whether there are recorded errors by the time
entity checkers run; a side effect of this is that the code is now
simpler, and produces fewer intermediate tables.

feat(schema) do not run custom_entity_check if fields are invalid

---

kong/init.lua
spec/02-integration/000-new-dao/01-db_spec.lua

Very tiny patch to replace `db.old_dao:infos` with `db.infos`.

refactor(db) replace db.old_dao:infos() with db.infos

---

.ci/run_tests.sh
.ci/track_failures.sh
.travis.yml

On builds of master with failing tests send the test name as a datapoint to datadog
All tests are output to stdout and to a file via `tee`. From there we `sed` / `grep` to manipulate only the failed tests to something that is formatted appropriately to be sent to datadog. Requires that datadog credentials exist where this is ran (already added to travis-ci)

misc(ci) track failure statistics

---

kong/db/strategies/cassandra/init.lua
spec/02-integration/000-new-dao/02-db_core_entities_spec.lua

The old code would never throw a primary key violation.

fix(db) Fix incorrect check for primary key violations under cassandra

---

kong/init.lua
kong/runloop/certificate.lua
kong/runloop/handler.lua

<s>This PR modifies the certificate phase to use luaossl via the kong.resty.getssl module instead of ngx.ssl
This allows us to use the same certificate management code (newly exposed via `find_certificate`) for both http and stream modes.</s>
This PR now just refactors the runloop/certificate module to use the lru cache built into ml-cache. The code is organised in a way to make a followup PR to add stream support have a minimal diff.

feat(certificate) use lru cache built into ml-cache

---

t/01-pdk/04-request/17-get_path_with_query.t

Related with https://github.com/Kong/kong-plugin-zipkin/pull/24
Explanation:
When kong receives an invalid request, it activates its [internal `kong_error_handler` location](https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L164):
```
error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
error_page 500 502 503 504 /kong_error_handler;
...
location = /kong_error_handler {
internal;
uninitialized_variable_warn off;
content_by_lua_block {
Kong.handle_error()
}
header_filter_by_lua_block {
Kong.header_filter()
}
body_filter_by_lua_block {
Kong.body_filter()
}
log_by_lua_block {
Kong.log()
}
}
```
This code will activate plugins which have header filters, body filters or log phases. On these cases, `ngx.var.request_uri` can indeed be `nil` (on invalid http …

tests(pdk) test for kong.request.get_path_with_query on error requests

---

kong/db/migrations/helpers.lua

Fixes `copy_cassandra_records` to handle `nil` values and use `cassandra.null` instead of calling the cassandra type constructor (`cassandra.uuid(x)`, etc.)
(Does not include a regression test in this PR as this is in the process of being tested in https://github.com/kong/kong-upgrade-tests )

fix(db) handle nils in copy_cassandra_records migration helper

---

kong/db/schema/init.lua
spec/01-unit/000-new-dao/01-schema/02-metaschema_spec.lua

Trying the proposal at https://github.com/Kong/kong/commit/3365902caa785fef3fcdbf723f2547342e336971#r30944834 I ran into an issue where `eq` was not accepted by the metaschema validator (though it seems to be accepted by the normal schema validator?)

fix(db) type 'any' shouldn't cause metaschema validation errors

---

.ci/setup_env.sh

Compiles OpenResty with added `--with-stream_ssl_preread_module`.
This is needed for Service Mesh to be fully functional.

chore(travis) compile with stream_ssl_preread_module

---

UPGRADE.md

There was a simple typo in the file.
* Corrected the typo in UPGRADE.md

docs: fix typo in UPGRADE.md

---

Makefile
kong/globalpatches.lua

After release rc13 the ffi patch was incorporated in Busted, hence
no more need to carry it with Kong itself.
See https://github.com/Olivine-Labs/busted/pull/555

tests(deps) update busted to 2.0rc13 and remove global patch

---

kong/db/schema/typedefs.lua

A typo in a typedef could lead to very cryptic error messages. This adds a metatable which catches accesses to unknown fields, producing an immediate error that is more evident for plugin authors. Since the metatable only hits on invalid accesses which are always plugin development bugs, this metatable adds no runtime overhead.

feat(schema) nicer error message for typedef errors

---

kong.conf.default
kong/conf_loader.lua
spec/01-unit/002-conf_loader_spec.lua

Requires https://github.com/Kong/openresty-patches/pull/10
Related to https://trac.nginx.org/nginx/ticket/287

feat(conf) add support for 'transparent' in listeners

---

kong/init.lua
kong/runloop/handler.lua

This PR is another foundational piece for service mesh.
The default SSL_CTX should be exposed somewhere for other internal modules to use.
I was going to add it to singletons, however that seems to be deprecated soon? I added it to the kong object for now, does anyone have a preference of where it is stored and/or which module creates it? Ideally it should be created somewhere with access to the kong config; and earlier than most other pieces (so that the mesh code or other code can then modify it).
Note: an earlier version of this PR didn't respect `client_ssl_cert_key` and `client_ssl_cert` set in the kong config; surprisingly this didn't make any tests fail!

feat(balancer) use luaossl created SSL_CTX

---

kong/db/schema/init.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
spec/02-integration/04-admin_api/21-services_routes_spec.lua

Fixes some problems with PATCH operations on updates:
* `adjust_field_for_context`: the filling of default values was recursing incorrectly when values are nil on "update" contexts: it should not recurse, and in case the table is not nullable, it should just fail on validation later; fixing this prevents clobbering partial updates with default values.
* `merge_values`: make sure that invalid fields are merged as well, so that it failed validation in the next step when passing a bogus field on input.
For regression testing, this PR adds more tests for failure cases of PATCH operations on plugins.

hotfix(schema) fix propagation of values on updates

---

kong/conf_loader.lua
kong/pdk/init.lua
kong/templates/kong_defaults.lua
spec/01-unit/002-conf_loader_spec.lua
spec/01-unit/003-prefix_handler_spec.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/05-proxy/14-upstream-status-header_spec.lua
spec/02-integration/07-sdk/01-ctx_spec.lua
spec/02-integration/07-sdk/02-log_spec.lua

This commit drops the `custom_plugins` property which was deprecated
since 0.14.0, in favor of `plugins`, which was introduced in
80acbf848e897a469c728395bf255dcbfda4cff3

chore(conf) drop the 'custom_plugins' property

---

kong-0.14.1-0.rockspec

This release makes sure that we favor the `rpc_address` to connect to
the elected contact point. It also adds support for CQL frames with
custom payloads.
Changelog:
https://github.com/thibaultcha/lua-cassandra/blob/master/CHANGELOG.md#133

chore(deps) bump lua-cassandra to 1.3.3

---

.travis.yml

Bumps LuaRocks in the Travis environment to version 3.0.4.

chore(deps) bump LuaRocks to 3.0.4

---

kong/cmd/migrations.lua
kong/db/migrations/core/001_14_to_15.lua
kong/db/schema/entities/plugins.lua
kong/db/schema/init.lua
kong/db/schema/typedefs.lua
kong/plugins/acl/schema.lua
kong/plugins/aws-lambda/schema.lua
kong/plugins/basic-auth/schema.lua
kong/plugins/bot-detection/schema.lua
kong/plugins/correlation-id/schema.lua
kong/plugins/cors/schema.lua
kong/plugins/hmac-auth/schema.lua
kong/plugins/ip-restriction/schema.lua
kong/plugins/jwt/schema.lua
kong/plugins/key-auth/schema.lua
kong/plugins/ldap-auth/schema.lua
kong/plugins/oauth2/schema.lua
kong/plugins/rate-limiting/schema.lua
kong/plugins/request-size-limiting/schema.lua
kong/plugins/request-termination/schema.lua
kong/plugins/request-transformer/schema.lua
kong/plugins/response-ratelimiting/schema.lua
kong/plugins/response-transformer/schema.lua

This PR includes:
* A fix on the schema, found by chance while studying how to best implement the new field
* A new field called `mesh_mode` to tag plugins with `inbound`, `outbound` or `two-way`. Note that `two-way` plugin instances can be individually tagged as `inbound` or `outbound` on creation, but plugins tagged as `inbound` can only have `inbound` instances, and the same goes for `outbound` pluggins.
I have tagged 15 plugins as `two-way` on this PR. There are multiple commits with explanations for my reasons.

Feat/plugins mesh field 1/2

---

kong-1.0.0rc2-0.rockspec

Bumps `luaossl` from  `20180708` to `20181102` (needed for Service Mesh)

chrore(deps) bump luaossl from `20180708` to `20181102`

---

kong/db/strategies/postgres/connector.lua

Adds `premature` check to Postgres cleanup timer.
Fix #3975

fix(db) add premature check for postgres cleanup timer, fix #3975

---

kong/db/dao/plugins.lua
kong/db/schema/entity.lua
kong/db/schema/init.lua
kong/db/schema/typedefs.lua
kong/plugins/response-ratelimiting/schema.lua
spec/01-unit/000-new-dao/01-schema/01-schema_spec.lua
spec/01-unit/000-new-dao/01-schema/04-services_spec.lua
spec/01-unit/000-new-dao/04-dao.lua

This PR marks the `plugins.run_on` field as required, so it gets a default value after migrating from 0.14 to 0.15.
It also includes a change in the schema to make `required` work this way, taking over the role previously hold by `nullable`.
Related with https://github.com/Kong/kong-upgrade-tests/pull/12

feat/required plugins.run_on field

---

kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua

In plugin rate-limiting and response-ratelimiting, a redis:select is
called when connection is reused, even though the current configured
redis database is 0, to clear the previously selected database. This
will be problem for some use case like twemproxy where `select` is
not supported, and sending `select` call will cause the connection to
be closed.
The patch used a host+port+database based redis connection pool, so that
we always know the current connection is using correct database. The 
behaviour of redis:auth only once is not changed.
* Use database-based redis connection pool to reduce unnecessary `select` call
Related to #3293

fix(plugins) don't call redis:select when not necessary

---

kong/plugins/cors/handler.lua
spec-old-api/03-plugins/14-cors/01-access_spec.lua
spec/03-plugins/14-cors/01-access_spec.lua

Follow the mozilla guidelines for preflight request (https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) for the cors plugin implementation.
* On OPTIONS requests
* Send 200 instead of 204
* Set `Content-Length` to `0`
Fixes #4008

fix(cors) follow mozilla guidelines for preflight request

---

kong/plugins/cors/handler.lua
spec-old-api/03-plugins/14-cors/01-access_spec.lua
spec/03-plugins/14-cors/01-access_spec.lua

Closes #3832.
This pull request changes the behavior of the CORS plugin as follows:
* Forces a full string validation to avoid the issue in #3832 
* When a both valid and matched domain is processed, returns an `Access-Control-Allow-Origin` header value that equals the string sent by the client in the original `Origin` value
* Validates that the scheme, host and port also match the `Origin` value as per [RFC6454 Section 5](https://tools.ietf.org/html/rfc6454#section-5)
These changes seem reasonable to me, but happy to hear feedback.

fix(cors) properly validate flat strings

---

kong/plugins/aws-lambda/handler.lua

Strip Connection headers from AWS Lambda responses if client is using HTTP per [RFC 7540](https://tools.ietf.org/html/rfc7540#section-8.1.2.2)
Fix #2991

fix(aws-lambda) strip Connection header if client is using HTTP/2

---

kong-1.0.0rc3-0.rockspec

* Fix invalid references to functions invoked in the handler module
* Strip connections headers disallowed by HTTP/2
* Restrict the config.run_on field to first
Changelog:
https://github.com/Kong/kong-plugin-azure-functions#history

chore(deps) bump azure-functions plugin to 0.3

---

kong/db/dao/targets.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

When an upstream is created and no targets are added, `GET
/upstreams/:upstream/targets` should return an empty `data` JSON property
in the response as an array.
This change ensure an empty JSON array(`[]`) is returned and not an
empty object(`{}`).
A regression test has been added to ensure we catch this for endpoints:
- `/upstreams/:upstream/targets`
- `/upstreams/:upstream/targets/all`
Fix #4043

hotfix(db) ensure an empty JSON array is returned when no targets

---

kong/tools/utils.lua

Only return architecture and OS name, like `Darwin i386`.

chore(reports) only return arch and OS name

---

kong/pdk/request.lua
kong/plugins/oauth2/access.lua
t/01-pdk/04-request/16-get_body.t

Changes `kong.request.get_body()` to return `nil, err` on `application/json` simple types as a root (and only) content:
- strings
- numbers
- booleans
- nulls
So you can after this is merged only use this to read following JSON content:
- arrays
- objects
as a root content.
Fix #4007

fix(pdk) make kong.request.get_body() to return nil, err on simple json values

---

kong/runloop/handler.lua

This PR makes it possible for code to check if the Kong node is running as a `service-mesh` node or not with `mutual tls` connection between two Kong nodes in a same cluster using stream module.

feat(core) add ctx.is_service_mesh_request context value with tls mesh

---

kong-1.0.0rc3-0.rockspec

Bumps `luaossl` to latest. Makes #4066 work (edit: almost).

chore(deps) bump luaossl to 20181207

---

kong/runloop/handler.lua
kong/runloop/mesh.lua
kong/runloop/plugins_iterator.lua
spec/02-integration/05-proxy/03-plugins_triggering_spec.lua

This will add support for `run_on` attribute on Plugins to make them run on:
1. `all` Kong nodes regardless
2. `first` Kong node in `gateway` or `service-mesh` modes only
3. `second` Kong node in `service-mesh` mode only
This is manually tested to be working with latest (not yet released) `luaossl` and our (released) `openresty-patches`, but this does not include `busted` tests yet. If that is a blocker for `release` of a release candidate, then I will update this PR on monday.

feat(core) enable plugin.run_on support on plugins iterator

---

kong/cmd/migrations.lua
kong/cmd/utils/migrations.lua
kong/db/migrations/core/001_14_to_15.lua

Adds a `--force` flag to `kong migrations up` to allow for migrating from one release candidate to the next (since the name of the migration file is unchanged). 
A more robust solution should be in place for future rc cycles, but this might be sufficient for now. Tested locally by:
1. checking out 1.0.0rc2
2. resetting/migrating the database
3. checking out `next`
4. running `kong migrations up --force`
5. running the test suite
Verified to fail with the errors seen by users when skipping step 4 and to work with Postgres and Cassandra when including it.
See #4033, #4042, #4049.

feat(migrations) add --force flag

---

kong-1.0.0rc3-0.rockspec
kong/resty/config.lua
kong/runloop/handler.lua
kong/runloop/mesh.lua

With OpenSSL 1.1.1 setting up the `SSL_CTX*` in the certificate
phase no longer works.
This commit introduces a new kong.resty.config module which
uses the patches at https://github.com/Kong/openresty-patches/pull/31 and https://github.com/Kong/openresty-patches/pull/32

fix(mesh) set up SSL_CTX in the init phase

---

kong/resty/config.lua
kong/runloop/mesh.lua

`ffi.cdef` doesn't throw unless the type is missing, instead the `pcall` needs to be around the index of `ffi.C`
This fixes an error when openresty-patches is not applied

fix(core) move pcall to correct location

---

kong/db/strategies/postgres/init.lua

Fixes an array index issue when generating `SQL` statements with `Postgres` strategy.

fix(db) fix postgres strategy create expressions array index issue

---

kong/plugins/aws-lambda/handler.lua
kong/plugins/bot-detection/handler.lua
kong/plugins/datadog/handler.lua
kong/plugins/file-log/handler.lua
kong/plugins/http-log/handler.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/loggly/handler.lua
kong/plugins/request-size-limiting/handler.lua
kong/plugins/request-termination/handler.lua
kong/plugins/statsd/handler.lua
kong/plugins/syslog/handler.lua
kong/plugins/tcp-log/handler.lua
kong/plugins/udp-log/handler.lua

Bumps all bundled plugins to `1.0.0` as a symbolic bump for `1.0.0` release.

chore(*) bump bundled plugins to version 1.0.0 (symbolic)

---

kong/pdk/init.lua

bump(pdk) from 0.1.0 to 1.0.0

---

kong/db/strategies/cassandra/connector.lua
kong/db/strategies/connector.lua
kong/db/strategies/init.lua
kong/db/strategies/postgres/connector.lua

Calling `db:connect()` used to store the connection in as an instance
attribute in `self`, therefore in a worker singleton (`kong.db`), which
would produce `bad request` errors when used at runtime (i.e.
non-migration contexts).
This error presents itself when within the `plugins:select_by_cache_key`
special DAO method, in which the schema_state module performs a
`connect()` and subsequent operations to determine the database schema
state.
Storing the connection object in the request aware context (`ngx.ctx`)
prevents this issue. We still store the connection as an instance
attribute in non-request contexts.

fix(db) store connection in request-aware context

---

kong/api/endpoints.lua
kong/api/init.lua
spec/02-integration/04-admin_api/25-plugin-endpoints.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-method/api.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-method/handler.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-method/schema.lua

If an Admin API handler did not exit explicitly using `kong.response.exit` (or
`ngx.exit`), it would end up concatenating HTML produced by Lapis (for an
example of this behavior, remove `kong.response.exit(200)` from the `collect`
function in kong-prometheus-plugin 0.3.2).
This ensures that only the handler function executes without falling into
Lapis.
Includes a plugin fixture and a regression test.

fix(admin) avoid Lapis handler when handler doesn't exit explicitly

---

CONTRIBUTING.md

Specify the quality of PR that earns a Kong contributor shirt.
* Change wording in the patch and t-shirt sections
Fix #XXX

docs(*) specify PR quality for shirt

---

kong/db/dao/init.lua

This PR fixes a issue on `dao:update*` that resulted duplicate crud events to be sent.

fix(db) daos do not send duplicate crud event anymore

---

kong/runloop/handler.lua
spec/01-unit/018-runloop_handler_spec.lua

Upon semaphore acquisition timeout (due to another coroutine being slow to release it while performing its own router rebuild), we now fallthrough to rebuild the router in order to ensure a best effort strategy.
I considered adding a second level semaphore (e.g. releasing a few more resources for some other coroutines instead of _all_ waiting coroutines), but this behavior is close to 0.14 all the while preserving the new router mutex in most cases (as long as they don't timeout). This alleviates some of the issues observed in #4055.
Also see discussion [here](https://github.com/Kong/kong/pull/4084#discussion_r241475200) (and other references there) for context around this behavior.

feat: router mutex fallthrough

---

kong/cmd/utils/migrations.lua
kong/db/init.lua
kong/db/strategies/cassandra/connector.lua
kong/db/strategies/postgres/connector.lua

Refuse to perform a 1.0 migration if there are any contents in the "apis" table. The user needs to migrate away from APIs into Routes and Services before upgrading to Kong 1.0.
Tested using https://github.com/Kong/kong-upgrade-tests/pull/15:
```
./test.sh -b kong:0.14.1 -t kong:feat/check-apis-on-migration upgrade_paths/0.14.1_1.0.0_fails_apis
./test.sh -b kong:0.14.1 -t kong:feat/check-apis-on-migration upgrade_paths/0.14.1_1.0.0
./test.sh -d cassandra -b kong:0.14.1 -t kong:feat/check-apis-on-migration upgrade_paths/0.14.1_1.0.0_fails_apis
./test.sh -d cassandra -b kong:0.14.1 -t kong:feat/check-apis-on-migration upgrade_paths/0.14.1_1.0.0
```
(Note that to run the above tests I needed to add a temporary hack to test.sh in which it switches the currently-active OpenSSL version installed …

feat(migrations) check presence of apis before migrating

---

kong/plugins/oauth2/migrations/001_14_to_15.lua

Avoid a crash if, during a Blue/Green migration, a new credential
is inserted by the Blue cluster.

hotfix(oauth2) make Cassandra migration more resilient

---

kong-1.0.0-0.rockspec

Kong has been Apache 2.0 licensed as noted in the LICENSE file but the
rockspec license has incorrectly been recorded as MIT.

chore(rockspec) correct license to Apache 2.0

---

kong/plugins/rate-limiting/policies/init.lua
kong/plugins/response-ratelimiting/policies/init.lua

In https://github.com/Kong/kong/pull/3973 the logic of selective call redis:select is implemented for `increment` but not `usage`. This patch applies the same logic to `usage` as well.
* Use database-based redis connection pool to reduce unnecessary select call in `usage()` call.

fix(plugins) call redis:select only necessary in usage() as well

---

kong/api/init.lua
kong/api/routes/plugins.lua
kong/init.lua
kong/plugins/datadog/schema.lua
spec/02-integration/04-admin_api/04-plugins_routes_spec.lua

Fixes a number of small issues that compounded into #4136:
* `fix(api) catch handler failures and return 500` - We were getting a Lapis handler because of a failure inside the PDK. This fixes that.
* `fix(core) reset log namespace on init_worker` - Once that was fixed, we were getting a logged error with the wrong namespace.
* `fix(api) encode non-JSON-representable numbers as strings` - Once that was fixed, the error reported that it was an issue when JSON-encoding the schema. This fixed the encoding.
* `fix(datadog) correct valid sample_rate range` - Finally, that value in the datadog schema shouldn't be there in the first place; this fixes the `sample_rate` to the correct range (between 0 and 1).
For datadog sample_rate, see:
* …

fix(datadog) fix sample_rate accepted range

---

kong/conf_loader.lua
kong/templates/nginx_kong.lua
kong/templates/nginx_kong_stream.lua
spec/01-unit/002-conf_loader_spec.lua
spec/fixtures/custom_nginx.template
spec/fixtures/nginx-directives.conf

Makes it possible to inject Nginx directives also to the stream configurations with configuration or environment variables:
`KONG_NGINX_STREAM_*` (see `KONG_NGINX_HTTP`)
`KONG_NGINX_SPROXY_*` (see `KONG_NGINX_PROXY`)
E.g.
```
KONG_NGINX_SPROXY_PROXY_BIND = 127.0.0.1 transparent
```
**Some Notes:**
TLDR; using `SPROXY` prefix comes from the limitations of original design introduced prior stream routing.
I didn't enjoy using `SPROXY` but I needed some unique prefix that did not conflict with already used prefixes. I wanted to use prefix such as `STREAM_PROXY` or `STREAM_SERVER` or `PROXY_STREAM` but those would conflict with already taken `STREAM_`  and `PROXY_`  prefixes. It would make code a bit more complicated if we would like to have longest prefix match first semantics.
If I was to …

 feat(stream) nginx directive injections for stream config

---

kong/api/routes/plugins.lua
spec/02-integration/04-admin_api/04-plugins_routes_spec.lua

* Ensure that plugin schemas return sub-fields of nested records in the same
format as the toplevel `fields` entry (i.e., as an array of single-fields
objects, so that the field order can be retrieved).
* Ensure `fields` in `/plugins/schema` always returns a JSON array,
even when it is empty (as in the prometheus plugin).
This produces an incompatible output from that of 1.0.0, but I'm opening this against `master` because the one in 1.0.0 is arguably broken, so this produces the intended result.
Fixes #4137.

fix(api) fix output of records in /plugins/schema

---

kong/api/routes/plugins.lua

Prior to this patch, configuring a plugin via `POST /plugins` would send
reports with `<entity>=userdata;<entity>=userdata;` when the plugin was
not configured on a given entity (e.g. when configuring a global plugin,
or a plugin with a Route only).
We also avoid sending `enabled=true` which has very little value and
takes space in our already limited UDP packet length.

fix(reports) do not send unnecessary attributes in 'ping' message

---

.ci/setup_env.sh

Adds `--with-stream_realip_module` to OpenResty `configure` flags. Needed by: #4149.
See also:
- https://github.com/Kong/openresty-patches/pull/35
- https://github.com/Kong/homebrew-kong/pull/86

chore(ci) build nginx with stream_realip_module
