Kong/kong

README.md
Updated readme with links to relevant lua install / luarocks website.
=> Add links to lua websites

INSTALL.md, README.md
=> INSTALL.md file

kong.yml, scripts/config.lua, site/app/_includes/pages/docs.md, src/kong/dao/cassandra/factory.lua, src/kong/tools/utils.lua, src/kong/web/app.lua
Optional anonymous reports for exception and errors.
=> Send anonymous reports

kong.yml
Brings some clarity to the nginx configuration.
=> Formatting configuration

kong-0.2.0-1.rockspec, spec/integration/proxy/authentication_plugin_spec.lua, spec/integration/proxy/ratelimiting_plugin_spec.lua, spec/unit/http_client_spec.lua, spec/unit/multipart_spec.lua, src/cli/utils/utils.lua, src/plugins/keyauth/access.lua, src/tools/faker.lua, src/tools/http_client.lua, src/tools/multipart.lua
This fixes some bugs in the key authentication, especially for `multipart/data`.
I am not happy by the code quality, so I would like to refactor it a little bit.
=> fixing multipart in keyauth

spec/integration/api/api_spec.lua
How was this not noticed by travis? Something must be wrong...
=> fix: api tests. Escaping was erroring.

.travis.yml, .travis/setup_cassandra.sh, .travis/setup_lua.sh, .travis/setup_openresty.sh, Makefile, package-build.sh, versions.sh
That way we avoid incoherences between travis and our packages @thefosk
=> Unify dependencies versions for packaging and travis-ci

README.md
- Update tagline to be congruent with the one in *What is Kong?*
- Give ToC a heading and proper list type / style.
- More concise and straightforward installation.
- Reword documentation line.
- Usage restructuring, make notice about $PATH a note.
- Concise development instructions.
- Rename Makefile to Makefile Operations
=> chore(readme): Cleanup and re-organization

README.md
- Add descriptions to cure irregular spacing on mixed lists
=> chore(readme): Fix odd spacing issue under usage

kong/resolver/access.lua, spec/integration/proxy/resolver_spec.lua
=> Supporting multiple Host headers

kong-0.2.1-1.rockspec, kong/dao/cassandra/factory.lua, kong/tools/printable.lua, spec/spec_helpers.lua
- Bump the Cassandra driver
- Fix a CLI error when having an array of `hosts`
=> [feature] allow cassandra hosts with different ports. fix #185

spec/integration/cli/restart_spec.lua
=> Fixing tests

.luacheckrc, kong-0.3.0-1.rockspec, kong/cli/utils/signal.lua, kong/plugins/httplog/log.lua, kong/plugins/tcplog/log.lua, spec/integration/proxy/dns_spec.lua, spec/integration/proxy/realip_spec.lua, spec/integration/proxy/resolver_spec.lua, spec/plugins/logging_spec.lua, spec/spec_helpers.lua, spec/unit/cli/utils_spec.lua
- Disabling the HTTP test which doesn't work.
- Adding ssl.lua to the rockspec
- Spec cleanup, fixing stop not waiting for process to be killed
=> [fix] tests

database/migrations/cassandra/2015-01-12-175310_init_schema.lua
=> [fix] uppercase keyspace causing failure

kong/dao/schemas_validation.lua, spec/unit/schemas_spec.lua
=> [fix/admin api] notify which subfields are required

kong/dao/schemas/apis.lua, spec/integration/proxy/resolver_spec.lua, spec/unit/dao/entities_schemas_spec.lua
- Add `/` in the list of allowed path characters
- Added much stronger path validation and sanitization that will also
avoid duplicated path cause by trailing slashes
Fix #310
=> [fix] path now accepts arbitrary depth

distributions/.build-package-script.sh, kong-0.4.0-1.rockspec
Closes #357. Upgraded OpenSSL and OpenResty. Also fixes the rockspec by adding some missing files.
=> Closing #357

spec/integration/dao/cassandra/base_dao_spec.lua
Broken since 0060309726aed53cbaa6a525f528899fdf3a2cee
=> [fix/tests] remove consumer_id in tests for some plugins

kong/dao/schemas/apis.lua, kong/dao/schemas/consumers.lua, kong/dao/schemas/plugins_configurations.lua, kong/plugins/basicauth/daos.lua, kong/plugins/keyauth/daos.lua, kong/plugins/oauth2/daos.lua, spec/plugins/keyauth/api_spec.lua
=> Revert "Changing some plugins fields to being immutable"

README.md
Was reading through the docs and ran across these.
=> Small spelling changes in Docs

kong/constants.lua, spec/unit/constants_spec.lua
=> errors out on undefined error codes

README.md
=> [docs/license] remove license badge and add notice

README.md
=> [docs/readme] Nicer header layout

kong/plugins/hmac-auth/access.lua, spec/plugins/hmac-auth/access_spec.lua
Supports multiple headers now plus request-line
=> now additional headers can be added

spec/plugins/response-transformer/filter_spec.lua
=> [chore/specs] preperly name response-transformer specs

kong/plugins/mashape-analytics/buffer.lua, kong/plugins/mashape-analytics/handler.lua, spec/plugins/mashape-analytics/buffer_spec.lua
File cache globals for mashape-analytics handler and buffer.
=> [perf/analytics] global optimizations

kong-0.5.0-1.rockspec
=> hmac migration fix 

README.md
- fix typo
- add kong + azure article
- add Portuguese Kong video
=> fix(readme): update community resources

kong/dao/cassandra/base_dao.lua, kong/tools/responses.lua
- sort base_dao by sections (public, private)
- better responses.lua @see references to lua-nginx-module
=> [docs/ldoc] improvements to base_dao and responses modules documentation

kong/plugins/jwt/api.lua, spec/plugins/jwt/api_spec.lua
Allow updating a specific JWT credential
=> Allow PATCH method on jwt credential endpoint

kong/plugins/jwt/api.lua, spec/plugins/jwt/api_spec.lua
Allow updating of a specific jwt credential.
=> allow patch method on a specific jwt credential

kong/plugins/hmac-auth/access.lua
=> [hotfix/hmac-auth] constant digest comparision

kong/plugins/request-transformer/access.lua, kong/plugins/request-transformer/schema.lua, spec/plugins/request-transformer/access_spec.lua
PR #711 against branch next. Fixes #569
=> JSON Request Transformation

kong/plugins/oauth2/access.lua, spec/plugins/oauth2/access_spec.lua
OAuth 2.0 scopes are now properly parsed. Also fixes issue #658.
=> OAuth 2.0 scopes are now properly parsed

spec/integration/admin_api/consumers_routes_spec.lua, spec/integration/dao/cassandra/base_dao_spec.lua
This PR detects the error mentioned in #720 (but does not fix it). The test case was wrong.
=> Fixing test, and added a new test

circle.yml
different method of waiting for cassandra as suggested by circleci support
=> CI fix: waiting for cassandra

kong/plugins/datadog/handler.lua, kong/plugins/datadog/schema.lua, spec/plugins/datadog/log_spec.lua
New metric response_size added to log request size to statsd server
=> enhancement(plugin/datadog) Added response size as metric

kong.yml
Updates the documentation of `advertise`.
=> Updating cluster documentation

kong/cli/cmds/config.lua, kong/cli/services/serf.lua, kong/core/hooks.lua, kong/tools/config_defaults.lua, spec/integration/cli/cmds/start_spec.lua, spec/integration/cluster/cluster_spec.lua, spec/plugins/datadog/log_spec.lua, spec/spec_helpers.lua
=> Cluster test rewrite

kong/api/routes/plugins.lua, spec/integration/admin_api/plugins_routes_spec.lua
- fix PATCH method triggering a 500 error
- new test cases for /plugins and /plugins/:id
=> hotfix(api) fix /plugins/:id PATCH

CHANGELOG.md, kong-0.6.1-0.rockspec, kong/constants.lua
=> release: 0.6.1

kong/plugins/oauth2/access.lua, spec/plugins/oauth2/access_spec.lua
squashed #918 with proper commit message
Thanks to @PGBI for the patch
=> fix(oauth) better handling of redirect_uri

kong-0.6.1-0.rockspec, kong/api/app.lua, kong/api/routes/apis.lua, kong/api/routes/cluster.lua, kong/api/routes/kong.lua, kong/api/routes/plugins.lua, kong/core/certificate.lua, kong/core/cluster.lua, kong/core/hooks.lua, kong/core/plugins_iterator.lua, kong/core/resolver.lua, kong/kong.lua, kong/plugins/acl/daos.lua, kong/plugins/acl/handler.lua, kong/plugins/basic-auth/access.lua, kong/plugins/basic-auth/daos.lua, kong/plugins/hmac-auth/access.lua, kong/plugins/jwt/handler.lua, kong/plugins/key-auth/handler.lua, kong/plugins/oauth2/access.lua, kong/plugins/rate-limiting/handler.lua, kong/plugins/response-ratelimiting/access.lua, kong/plugins/response-ratelimiting/log.lua, kong/singletons.lua, spec/unit/core/resolver_spec.lua
=> Revert "Replace globals with `kong.singletons` module variables."

.luacheckrc, kong/api/routes/cluster.lua, kong/cli/services/base_service.lua, kong/cli/services/serf.lua, kong/core/cluster.lua, kong/core/hooks.lua, kong/kong.lua
Enhancements to the Serf implementation to improve performance.
=> Improving the performance of Serf

spec/plugins/basic-auth/access_spec.lua, spec/plugins/oauth2/access_spec.lua, spec/plugins/oauth2/hooks_spec.lua
Makes the test work with the new lint version.
=> Removes duplicate Lua table entires in tests

kong/cli/services/serf.lua, kong/core/cluster.lua, kong/core/hooks.lua
Better handle errors when Serf is unavailable during a `_members()` invocation.
=> Better handle serf members() error

kong/api/app.lua, kong/dao/schemas_validation.lua, spec/integration/admin_api/plugins_routes_spec.lua
Fixes some issues related to update:
* Closes #942.
* Closes #962.
=> Closes #942 and #962.

kong/tools/config_loader.lua, kong/tools/utils.lua, spec/integration/proxy/dns_resolver_spec.lua, spec/plugins/logging_spec.lua, spec/plugins/rate-limiting/access_spec.lua
=> Fixing a bug when loading custom plugins

kong/core/resolver.lua, kong/tools/ngx_stub.lua, spec/integration/proxy/resolver_spec.lua
=> Fixing preserve_host with request_path

spec/integration/admin_api/apis_routes_spec.lua, spec/plugins/key-auth/api_spec.lua
Verifies that #735 is fixed and cannot be replicated anymore.
=> Verifies that #735 is fixed

kong/api/routes/cluster.lua, kong/dao/dao.lua, kong/dao/schemas/nodes.lua
Fixes a bug when looking up for an entity with its primary key.
=> Fixing DAO query in cluster event handling

kong-0.7.0-0.rockspec, kong/plugins/oauth2/access.lua, spec/plugins/oauth2/access_spec.lua
=> Closes #1067

kong/plugins/mashape-analytics/buffer.lua
=> feat(galileo) increase collector timeout to 30s

kong-0.7.0-0.rockspec, kong/plugins/mashape-analytics/migrations/cassandra.lua, kong/plugins/request-transformer/migrations/cassandra.lua, kong/plugins/response-transformer/migrations/cassandra.lua, spec/plugins/jwt/jwt_parser_spec.lua
Added missing migration script for request/response transformer plugins. #1064.
=> Fix (plugins/[request/response]-transformer) Adding migration scripts

README.md
- sort tools by alphabetical order
- better tools description
- enforce an 80 chars width
=> docs(readme) sort tools + cleanup

kong-0.8.0rc2-0.rockspec, kong/constants.lua, kong/plugins/ldap-auth/access.lua, kong/plugins/ldap-auth/asn1.lua, kong/plugins/ldap-auth/handler.lua, kong/plugins/ldap-auth/ldap.lua, kong/plugins/ldap-auth/schema.lua, kong/tools/database_cache.lua, spec/plugins/ldap-auth/access_spec.lua
Adds the LDAP authentication plugin.
=> LDAP plugin

kong/constants.lua, kong/plugins/acl/handler.lua, spec/plugins/acl/access_spec.lua
=> Appends X-Consumer-Groups header when ACL is enabled

kong.yml, kong/api/crud_helpers.lua, kong/dao/dao.lua, kong/dao/migrations/cassandra.lua, kong/plugins/mashape-analytics/migrations/cassandra.lua, kong/plugins/request-transformer/migrations/cassandra.lua, kong/plugins/response-transformer/migrations/cassandra.lua, spec/integration/01-dao/03-crud_spec.lua
This fixes a bug when full-updating DAO entities.
=> Fixing DAO full-update

kong/plugins/datadog/handler.lua, kong/plugins/datadog/schema.lua, kong/plugins/datadog/statsd_logger.lua
Added two new metrics "unique_users", "request_per_user" to capture consumer details if present.
Closes #998.
=> added metrics for consumer

kong/plugins/request-transformer/access.lua
This causes a bug in the transformation plugin.
=> Replacing backend_host with upstream_host

kong/dao/migrations/postgres.lua, kong/dao/postgres_db.lua, kong/plugins/acl/migrations/postgres.lua, kong/plugins/basic-auth/migrations/postgres.lua, kong/plugins/hmac-auth/migrations/postgres.lua, kong/plugins/jwt/migrations/postgres.lua, kong/plugins/key-auth/migrations/postgres.lua, kong/plugins/oauth2/migrations/postgres.lua
=> fix(postgres): support custom (non-public) schema

kong/plugins/cors/handler.lua, spec/plugins/cors/access_spec.lua
=> Fixing CORS plugin

kong/plugins/response-transformer/body_transformer.lua, spec/plugins/response-transformer/big_response_body_spec.lua, spec/plugins/response-transformer/filter_spec.lua
=> Fixing double slash encoding in Response Transformer plugin.

kong/core/plugins_iterator.lua
=> refactor iterator to clean it up and reduce GC load

kong/dao/postgres_db.lua
=> Closing #1262

kong/plugins/oauth2/daos.lua
=> Closes #1267

kong/core/resolver.lua
=> refactor resolver string handling

kong/cmd/utils/nginx_signals.lua, kong/plugins/request-transformer/access.lua, kong/plugins/response-transformer/body_transformer.lua, kong/plugins/response-transformer/header_transformer.lua, spec/03-plugins/request-transformer/01-access_spec.lua, spec/03-plugins/response-transformer/01-header_transformer_spec.lua, spec/03-plugins/response-transformer/02-body_transformer_spec.lua
=> allows colons in the request and response transformer payloads

kong/dao/schemas/apis.lua, spec/01-unit/11-entities_schemas_spec.lua, spec/02-integration/05-proxy/01-resolver_spec.lua
=> allows url encoded request_paths

kong/api/init.lua, spec/02-integration/03-admin_api/01-kong_routes_spec.lua, spec/02-integration/03-admin_api/02-apis_routes_spec.lua, spec/02-integration/03-admin_api/03-consumers_routes_spec.lua, spec/02-integration/03-admin_api/04-plugins_routes_spec.lua
=> insert 405 handlers for all undefined http methods

kong/cmd/start.lua, kong/cmd/utils/prefix_handler.lua, kong/templates/nginx.lua, kong/templates/nginx_kong.lua, spec/01-unit/01-conf/02-prefix_handler_spec.lua, spec/02-integration/01-cmd/02-start_stop_spec.lua, spec/fixtures/custom_nginx.template
Allows to specify a custom nginx configuration template.
=> feat(cli) --nginx-conf argument for custom Nginx config template

spec/02-integration/05-proxy/01-resolver_spec.lua
=> Added a test to check the response when the URI is too long

kong/plugins/oauth2/access.lua, spec/03-plugins/oauth2/03-access_spec.lua
Better version of #1389 that closes #1363.
=> Closing #1363

kong/plugins/oauth2/schema.lua, spec/03-plugins/oauth2/03-access_spec.lua, spec/03-plugins/oauth2/04-hooks_spec.lua
Fixes some tests now that the OAuth 2.0 flow is required.
=> fix(test) oauth2

CHANGELOG.md, UPGRADE.md
=> docs(changelog) add 0.9 (unreleased) changes

kong/cmd/utils/prefix_handler.lua, kong/plugins/rate-limiting/migrations/cassandra.lua, kong/plugins/rate-limiting/migrations/postgres.lua
Fixing some 0.9.0 RC1 bugs.
* The `resty` bin file is now properly searched and its fullpath is printed into the Serf event handler file.
* Rate-limiting migration issues.
=> fix(rc1) migrations + serf event handler script

.ci/setup_env.sh
This was taken from another project that didn't need all of those.
=> fix(travis) build OpenResty with all lua-resty-* modules

kong/meta.lua, spec/01-unit/01-rockspec_meta_spec.lua
`kong.meta` is an important module holding critical details about Kong's version and soon third-party dependencies as well.
=> tests(meta) add new tests for meta module's fields

kong/cmd/health.lua, kong/cmd/quit.lua, kong/cmd/reload.lua, kong/cmd/start.lua, kong/cmd/stop.lua, kong/cmd/utils/dnsmasq_signals.lua, kong/cmd/utils/log.lua, kong/cmd/utils/nginx_signals.lua, kong/cmd/utils/prefix_handler.lua, kong/cmd/utils/serf_signals.lua, kong/serf.lua
* better consistency with capitals/non-capitals/formats/style
* prevent stop/reload/restart from double-logging when using conf_loader
twice
* reduce logging info about executables to `debug` level
=> feat(cli) improve logging messages

CHANGELOG.md, kong-0.9.0rc3-0.rockspec, kong/meta.lua
=> 0.9.0rc3 release

kong-0.9.0rc4-0.rockspec, kong/meta.lua
=> 0.9.0rc4 release

spec/03-plugins/98-rate-limiting/04-access_spec.lua, spec/03-plugins/98-response-rate-limiting/04-access_spec.lua
=> Closing clients

CHANGELOG.md, kong-0.9.0-0.rockspec, kong/meta.lua
=> release 0.9.0

spec/02-integration/05-proxy/01-resolver_spec.lua
Adding a test to try to replicate, unsuccessfully, issue #1557.
=> test(resolver) dashes in subdomain

kong/dao/dao.lua, kong/dao/factory.lua, spec/02-integration/02-dao/02-migrations_spec.lua
This completes #1502 which missed migration errors (such as unreachable
DBs, the overly famoused "connection refused" error).
=> feat(cli) prefix DB error messages with DB type

kong/dao/postgres_db.lua
* Properly logs errors when cleaning up TTLs
=> fix(postgres) properly logging TTL clean up errors

CHANGELOG.md
* Added missing fixes/additions to the CHANGELOG for 0.9.1
=> hotfix(changelog) missing v0.9.1 fixes/additions

kong/dao/schemas/apis.lua, kong/plugins/basic-auth/access.lua, kong/plugins/file-log/handler.lua, kong/plugins/http-log/handler.lua, kong/plugins/oauth2/access.lua, kong/plugins/runscope/log.lua, kong/tools/timestamp.lua, spec/01-unit/06-timestamp_spec.lua, spec/02-integration/02-dao/03-crud_spec.lua, spec/03-plugins/12-request-size-limiting/01-access_spec.lua
as per title
Fixes my urge to grab an axe and grep a hitlist from git blame
=> removed usage of `table.getn` and `string.len`

spec/03-plugins/04-cors/01-access_spec.lua
Checks that CORS properly works with 404 responses.
Created to check https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/konglayer/FMXgLOFaHcQ/DIYh0Fr_CQAJ
=> test(cors) check that it works with 404 responses

CHANGELOG.md
=> docs(changelog) add 0.9.2 changes

kong/plugins/http-log/handler.lua, kong/plugins/http-log/schema.lua
includes #1689 and adds some comment updates and exposing the conf table to the serializer (in case a different content-type is configured)
=> Fix/httplog generalized the plugin for re-use

kong/tools/database_cache.lua, spec/02-integration/04-core/02-hooks_spec.lua
* Fixes a bug that prevented global plugins from being invalidated.
Fix #1721.
=> hotfix(invalidation) invalidates global plugins

CHANGELOG.md, kong-0.9.3-0.rockspec, kong/meta.lua
=> release: 0.9.3

kong/cmd/check.lua
Sorry, last PR forgot to commit, additional to #1700  
Fix #1697
=> Inconsistencies(cli) default configuration file

kong-0.9.3-0.rockspec
=> chore(deps) updating multipart

CHANGELOG.md, kong-0.9.4-0.rockspec, kong/meta.lua
=> release(0.9.4)

spec/helpers.lua
fixes an open issue with assertion recursion, due to a single upvalue. Now properly stored in per-assertion state.
=> fix assertion recursion in test helpers

kong/tools/timestamp.lua, spec/01-unit/06-timestamp_spec.lua
updates the timestamps modules, reducing complexity and adding a millisecond precision function.
Magnitudes smaller number of table creations and table lookups, so should be faster to
=> refactor(utils) Timestamps refactored

CHANGELOG.md, bin/busted, bin/kong, kong-0.9.7-0.rockspec, kong/core/globalpatches.lua, kong/meta.lua
=> release(0.9.7)

spec/01-unit/02-conf_loader_spec.lua
=> fix (test) test failing

spec/03-plugins/01-basic-auth/02-api_spec.lua
Adds an additional test to check the uniqueness of the Basic Auth credentials.
=> test(basic-auth) check credential uniqueness

kong.conf.default
=> rewrite an odd sentence regarding clustering

kong-0.10.0rc2-0.rockspec, kong/cmd/utils/prefix_handler.lua, kong/plugins/file-log/schema.lua, kong/serf.lua, spec/02-integration/05-proxy/04-websockets_spec.lua
* Updates penlight
* Replaces the ugly `touch` commands with penlight equivalents
* Implements an error check on serf `leave` command
=> fix(cli) replace the "touch" cmds and error check for serf leave

kong/core/plugins_iterator.lua, spec/02-integration/04-core/02-hooks_spec.lua
=> hotfix(db-miss) porting #1914 fix into 0.9.x

spec/02-integration/04-core/02-hooks_spec.lua
=> fix(test) adds extra test failing on db-miss bug see also #1984

.travis.yml
Re-enables serf download in the tests.
=> hotfix(test) fixing serf download

kong/plugins/rate-limiting/policies.lua, kong/plugins/response-ratelimiting/policies.lua, spec/03-plugins/98-rate-limiting/04-access_spec.lua, spec/03-plugins/98-response-rate-limiting/04-access_spec.lua
Backport of #1843 into `master`.
=> hotfix(rate-limiting) backporting #1843 fix for fault tolerancy

CHANGELOG.md, kong-0.9.8-0.rockspec, kong/meta.lua
=> chore(release) 0.9.8

kong/plugins/jwt/daos.lua
Fixes ES256 not being enable in jwt
=> fix(plugins): expose ES256 for jwt

kong/conf_loader.lua, kong/tools/utils.lua, spec/01-unit/04-utils_spec.lua
allows only ipv4 with proper octets (0-255)
=> fix(cli): improve ipv4 validation

spec/02-integration/03-admin_api/05-cache_routes_spec.lua
The test api was inserted after Kong was started, and hence gave a 404.
=> fix(test): fix cache tests

kong/core/router.lua
Signed-off-by: Wei.ZHAO <zhaowei@qiyi.com>
=> feat(core) Cache length of CATEGORIES

spec/03-plugins/08-ldap-auth/01-access_spec.lua
Done as part of migration from old AWS account to new one.
* Updated LDAP test server endpoint
=> fix(plugin/ldap) updated LDAP test server endpoint

kong/dao/migrations/cassandra.lua
Retrieve index name from `system.schema_columns`. We cannot always rely
on the naming scheme to be respected across different setup (multiple keyspaces
with similar names) and C* versions.
=> fix(c*) retrieve index names from schema_columns

CHANGELOG.md, kong-0.10.0rc4-0.rockspec, kong/meta.lua
=> chore(rockspec) bump to 0.10.0rc4

kong/dao/db/postgres.lua, kong/dao/migrations/postgres.lua, spec/02-integration/02-dao/07-ttl_spec.lua, spec/03-plugins/12-request-size-limiting/01-access_spec.lua
Manually execute the `apis` table Postgres migration.
=> fix(migrations) manually execute apis table migration

kong-0.10.0rc4-0.rockspec
DNS resolver lib was updated to fix some Kubernetes
=> fix(core): update dns resolver dependency

spec/02-integration/05-proxy/06-upstream_timeouts_spec.lua
=> tests(proxy) fix upstream timeouts in CI

kong/meta.lua
=> chore(deps) bump Serf allowed version to 0.8.1

spec/02-integration/02-dao/02-migrations_spec.lua, spec/02-integration/02-dao/03-crud_spec.lua
Purge shm cache of the C* testing clusters when necessary.
=> tests(integration) flush C* shm cache to fix DAO tests

CHANGELOG.md, UPGRADE.md
=> docs: 0.10 upgrade notes + changelog updates

UPGRADE.md
Wording and formatting tune-ups for intro and 0.10 section of Upgrade doc.
=> fix (doc): Wording and formatting for Upgrade doc

kong/tools/database_cache.lua
=> cache(docs): adds a comment related to the use of get_or_set and locking

spec/02-integration/05-proxy/09-balancer_spec.lua
=> tests(ci): provide more time to start for background server, and collect closed sockets

CHANGELOG.md, UPGRADE.md, kong/plugins/aws-lambda/schema.lua
Pull the hotfixes into the `next` branch
=> Merge master into next

CODE_OF_CONDUCT.md
Create Code of Conduct
* Added Code of Conduct, from http://contributor-covenant.org/
=> docs(create code of conduct)

CHANGELOG.md
Also some spelling corrections
=> docs(cors) changelog for cors origins

kong/api/routes/upstreams.lua
Fixes https://github.com/Mashape/kong/issues/2305
=> hotfix(upstreams) dont require a trailing slash for active targets

kong-0.10.1-0.rockspec, kong/core/balancer.lua
=> chore(deps) update dns dependency to 0.4.0 to fix #2290

kong/dao/migrations/cassandra.lua, kong/dao/migrations/postgres.lua
=> fix(migrations) fix a typo in a field name

kong/core/balancer.lua, kong/core/handler.lua, kong/kong.lua, kong/plugins/log-serializers/basic.lua, spec/01-unit/13-log_serializer_spec.lua
previously it would only log failure data. Now it logs all attempts,
also the successful ones.
=> fix(logs) log the successful tries also

CHANGELOG.md
=> docs(changelog): spelling

kong/api/crud_helpers.lua
Extra care should have been given to a few CRUD helper methods after the
recent merge or 'master'. This fixes the behavior of a few routes in the
Admin API and takes both branches' recent changes into account.
=> fix(admin) use new find_by_id_or_field helper

CHANGELOG.md, UPGRADE.md
* mentioned in 0.10.1 changelog
* mentioned in the 0.10.x upgrade path
=> docs(*) mention 0.10.1 CORS regression

kong/plugins/request-termination/schema.lua, spec/03-plugins/27-request-termination/03-integration_spec.lua
=> fix(termination) allow plugin to be added to a consumer

CONTRIBUTING.md
+ minor edit adding a missing dot in the "support" section of this document
=> docs(contributing) add section about contributing plugins

kong/plugins/basic-auth/access.lua, kong/plugins/hmac-auth/access.lua, kong/plugins/jwt/handler.lua, kong/plugins/key-auth/handler.lua, kong/plugins/ldap-auth/access.lua, kong/plugins/oauth2/access.lua
Revert #2508, see #2515.
This should be deployed in 0.11.
=> Revert "hotfix(auth) handle nil anonymous consumers"

README.md
Added kong-java-client to list of community maintained tools
=> Added kong-java-client to list of community maintained tools

CONTRIBUTING.md
Fix logic error and some English issues in CONTRIBUTING.md.
* Fix logic mistake in Lua style example
* Some English cleanup
=> docs(contributing) some fixes

.ci/run_tests.sh, .ci/setup_env.sh, .travis.yml
Removing Serf and Dnsmasq from CI.
=> test(ci) removing serf and dnsmasq

kong/core/plugins_iterator.lua
On tests conducted on my side, this improved improve the core performance by **~25%** by avoiding to declare a closure iterator and keeping GC load and branching to a minimum.
=> perf(core) faster plugins iterator

CONTRIBUTING.md
Fixes minor typos in the CONTRIBUTING.md document.
=> docs(contributing) fix minor typos

kong/plugins/aws-lambda/schema.lua
=> feat(aws-lambda) support more regions

README.md
This GUI seems better than others which listed in README.
Konga can manage multiple Kong node easily!
=> docs(readme) add an konga UI

CHANGELOG.md, UPGRADE.md
=> docs: changelog and upgrade path updates for 0.11.0

spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
=> tests(integration) add comment clarifying old openssl error

spec/02-integration/04-admin_api/08-targets_routes_spec.lua
Fixes flaky test (ordering of inserted APIs could get mixed and cause test to fail)
=> tests(admin) fix active targets api test flakiness

README.md
test-all = unit + integration + plugins
> Makefile
```
test:
@$(TEST_CMD) spec/01-unit
test-integration:
@$(TEST_CMD) spec/02-integration
test-plugins:
@$(TEST_CMD) spec/03-plugins
test-all:
@$(TEST_CMD) spec/
```
=> docs(readme) fix test omission

kong/plugins/jwt/handler.lua, kong/plugins/jwt/schema.lua, spec/03-plugins/17-jwt/03-access_spec.lua
fixes #2643
follow up PR with the migrations: #2751
=> feat(jwt) skip authenticating preflight OPTIONS requests

CHANGELOG.md, kong-0.11.1-0.rockspec, kong/meta.lua
This PR is **not** to be merged yet, but only exists for visibility and review purposes.
getkong.org PR: https://github.com/Kong/getkong.org/pull/531
=> Release: 0.11.1

CHANGELOG.md
=> docs(changelog) add 0.10.4 changeset

spec/02-integration/05-proxy/11-error_default_type_spec.lua
The previous test suite would run with inconsistent success because the
upstream 500 error would not always trigger the NGINX error_page
directive and thus, our Kong error handling.
This new approach consistently triggers the NGINX error_page (and our
Kong error handling). Additionally, it improves the speed of this suite
by a non-negligible factor considering we only restart Kong once instead
of enforcing multiple reloads and subsequent waiting times, as well as
because of the nature of the behavior being tested (timeouts).
This should improve our inconsistent CI environments (this test suite
currently is the most common cause of failed CI builds).
=> tests(integration) more robust error_default_type testing

kong-0.11.1-0.rockspec
Bump `lua-multipart` version in rockspec.
=> chore(rockspec) bump multipart version

CHANGELOG.md
Correct contributor hbagdi's handle from hbadgi to hbagdi
=> docs(changelog) correct contributor name

CHANGELOG.md, kong-0.12.2-0.rockspec, kong/meta.lua
**Formal PR for Kong 0.12.2 - request for reviews!**
* Full list of commits since 0.12.1: https://github.com/Kong/kong/compare/0.12.1...release/0.12.2
* Docs PR: https://github.com/Kong/getkong.org/pull/599
Things to look for:
* Is the changelog complete? Typos? (TODO)
* Double checking for the absence of breaking changes in the commits
* If enough time, double checking/testing the new features/fixes
**This officially closes the merging window for 0.12.2 as of today, 2018/02/23.**
=> release: 0.12.2

CHANGELOG.md, kong-0.12.3-0.rockspec, kong/meta.lua
Diff: https://github.com/Kong/kong/compare/0.12.2...release/0.12.3
=> release: 0.12.3

kong/constants.lua
This PR fixes misplaced comment
- updated constants file
=> fix(constants) fix misplaced comment

CHANGELOG.md
Delaying the stable release as a follow-up of 0.13.0rc2
=> docs(changelog) update 0.13.0 stable target release date

README.md
=> update README with new features

kong/api/endpoints.lua
Just removes a few lines of code that were not used for anything. Something that was left there before that part of code was refactored (it used to be recursive).
=> chore(admin) remove unneeded code from endpoints.generate_endpoints

CONTRIBUTING.md
Including Kong Nation links instead of google forum
* docs(contributing) change google forum to kong nation
=> docs(contributing) change google form to kong nation

spec/02-integration/03-dao/10-cache_spec.lua
Make the regression test for #3277 less fragile by using
relative values (check that the GC always grows throughout
the test) instead of absolute values (check that the difference
between garbage collections remains within a threshold).
=> tests(dao) use relative values for #3277 regression test

kong/plugins/key-auth/handler.lua
removed the duplicate whitespace characters.
=> style(key-auth) fixed minor coding style issues

kong/dao/dao.lua
=> fix(dao) fix typo

kong-0.13.1-0.rockspec
=> chore(rockspec) update to luaossl 20180530 release

kong/cmd/utils/env.lua
Follow up fix of ac0f3f6fe3048210a68f93ee00d88f10eb77274c
=> hotfix(cli) read environment from **environ instead of printenv

spec/02-integration/05-proxy/09-balancer_spec.lua
Increase the delay and shorten the tolerance in the fail case, and restore a high timeout tolerance in the success case.
=> tests(healthchecks) improve timing for send timeout in passive tests

kong/plugins/aws-lambda/handler.lua, spec/03-plugins/23-aws-lambda/01-access_spec.lua
Fix `aws-lambda` delayed response
=> fix(aws-lambda) delayed response

t/01-pdk/08-response/11-exit.t
Fix pdk `Server` header tests on `kong.response.exit`
=> tests(pdk) fix kong.response.exit tests with rc builds

kong/pdk/ip.lua
Changed code style from implicit assignment to explicit.
=> style(pdk) explicit assignment

spec/03-plugins/17-jwt/02-api_spec.lua
Corrects the HTTP method of the test from POST to PUT.
All tests pass:
```
bin/busted spec/03-plugins/17-jwt -v
```
- Fix JWT Plugin API PUT test
=> tests(jwt) fix put test

.ci/trigger-travis.sh, .gitignore, .travis.yml
setting up travis to build nightly releases
=> feat(nightly) trigger the nightly release

spec/01-unit/010-router_spec.lua
Added cases where the incoming uri is longer than the matched uri.
The tests match current behaviour. But please note case 37, it injects an extra slash. This seems counter intuitive to me, I would have expected `/fee/bors` as the final uri.
=> refactor(test) adds testcases for (trailing) slash handling

.ci/setup_env.sh
Avoid the problem described here:
https://forum.nginx.org/read.php?2,279002
+ remove the deprecated `--with-ipv6` flag
=> chore(ci) dynamically link OpenSSL

kong/api/endpoints.lua, kong/api/routes/apis.lua, kong/api/routes/certificates.lua, kong/api/routes/consumers.lua, kong/api/routes/plugins.lua, kong/api/routes/routes.lua, kong/api/routes/services.lua, kong/api/routes/upstreams.lua, kong/db/dao/targets.lua, spec-old-api/02-integration/04-admin_api/02-apis_routes_spec.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua
- Refactoring of Endpoints
- More consistent options handling
- More consistent 404 behavior in custom entities
- More consistent collection endpoints
This was originally proposed in
#3710 
And this is one of the series of PRs that were previously implemented in that branch.
=> refactor(admin) more consistent options and 404 handling plus cleanups

CONTRIBUTING.md, README.md
Updates URLs and copy related to Kong Hub. Corrects URLs and does a little DRY.
=> Docs/hub updates to README and CONTRIBUTING

kong/db/schema/entities/certificates.lua, spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
A simple use of #3843 to see how things go....
=> feat(db) add an entity check that ensures the key matches the certificate

kong-0.14.1-0.rockspec
Changelog:
https://github.com/Kong/kong-plugin-prometheus/blob/next/CHANGELOG.md#030---20181015
From #3853
=> chore(deps) bump kong-prometheus-plugin to 0.3

kong-0.14.1-0.rockspec
* Use of new db & PDK functions
Changelog:
https://github.com/Kong/kong-plugin-azure-functions#history
=> chore: bump azure-functions plugin to 0.2

kong-0.14.1-0.rockspec
* Start using the new DB & PDK modules (compatibility with Kong >=
0.15.0)
* New schema format
Changelog:
https://github.com/Kong/kong-plugin-zipkin/blob/master/NEWS
=> chore(deps) bump zipkin plugin to 0.1

kong/db/strategies/cassandra/plugins.lua
Complex queries (even with `ALLOW FILTERING`) can cause a Java exception in Cassandra 2. This PR simplifies the query performed by the migration translation function for `plugins:select_by_cache_key` when using Cassandra 2, to only filter by a single non-null value -- either one of the ids set, or the plugin name as a fallback -- and then further filter the results in Lua.
=> hotfix(db) fix Plugins cache_key translation function for C* 2.x

UPGRADE.md
The UPGRADE.md file contains some spelling mistakes
* [Fixed Typos]
Fixed spelling mistakes improving document
=> Fixed Typos

.ci/track_failures.sh
Hello.
I modified the UUOC(useless use of cat).
what do you think?
Ref: https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat
Thanks.
* ...
Fix #XXX
=> chore(ci) fix a useless use of cat

kong/globalpatches.lua
Corrected a typo in globalpatches.lua .
=> Typo fix in globalpatches.lua

CHANGELOG.md
=> corrected minor typo

CHANGELOG.md
=> fixed typo and grammar mistakes

kong-1.0.0rc2-0.rockspec, kong/db/init.lua, kong/db/migrations/core/001_14_to_15.lua, kong/db/schema/entities/cluster_ca.lua, kong/init.lua, kong/runloop/mesh.lua, kong/tools/cluster_ca.lua, spec/01-unit/017-tools_cluster_ca_spec.lua, spec/02-integration/000-new-dao/03-db_cluster_ca_spec.lua
This pull request adds in management of the kong cluster certificate authority used for service mesh deployments.
=>  feat(db) add cluster_ca database entity

.github/ISSUE_TEMPLATE.md
Update URL in issue template
* [Update URL]
=> docs(github) Update ISSUE_TEMPLATE.md with correct url

kong/dao/migrations/cassandra.lua
Changing commit message of #4014
=> fix(migrations) cassandra drop index

kong/cmd/utils/prefix_handler.lua, kong/conf_loader.lua, kong/runloop/balancer.lua, kong/templates/nginx_kong_stream.lua, spec/01-unit/002-conf_loader_spec.lua, spec/01-unit/003-prefix_handler_spec.lua, spec/02-integration/05-proxy/00-proxy_spec.lua, spec/02-integration/05-proxy/09-balancer_spec.lua, spec/fixtures/custom_nginx.template, spec/helpers.lua, spec/kong_tests.conf
A basic test for healthchecks using the stream router, plus a fix to a bug that was uncovered when writing it.
=> Template bugfix + healthcheck test for stream router

spec/03-plugins/24-rate-limiting/04-access_spec.lua
Simple fix that makes `rate-limiting` tests work rather un-flaky (also removes the need for old dao too).
=> test(rate-limiting) fix rate-limiting access tests and remove old dao

kong/constants.lua
=> chore(reports) updating host

CHANGELOG.md, UPGRADE.md
* Clarify many entries that were obscure or incomplete.
* Distinguish regular changes from breaking changes with use of the
warning emoji.
* Highlight major additions with formatting.
* Remove internal or "hotfix" entries that are not user-facing.
* Add a few missing entries (e.g. migrations framework, new default
properties...).
* Split Admin API and Configuration changes out of Core sections.
* Fix various formatting and invalid PR links.
* Add missing TOC links.
=> docs(*) polish 1.0.0 changelog and upgrade path

kong/db/schema/init.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua
=> fix(db) floor values for integer fields on the schema

CHANGELOG.md, UPGRADE.md, kong-1.0.1-0.rockspec, kong/meta.lua
This PR supersedes #4207 and #4208
=> Release Kong 1.0.1

kong/api/endpoints.lua, kong/api/routes/cache.lua, kong/api/routes/kong.lua, kong/api/routes/snis.lua, kong/api/routes/targets.lua, kong/api/routes/upstreams.lua, kong/db/dao/certificates.lua, kong/db/dao/targets.lua, kong/plugins/acl/api.lua, kong/plugins/basic-auth/api.lua, kong/plugins/hmac-auth/api.lua, kong/plugins/jwt/api.lua, kong/plugins/key-auth/api.lua, kong/plugins/oauth2/api.lua, kong/runloop/balancer.lua
Various fixes, refactors and perf improvements that came up while working on #4132.
Commits extracted from #4189.
=> Assorted Admin API improvements

kong.conf.default
Related with https://github.com/Kong/docs.konghq.com/pull/1121
=> docs(1.0) sync default template with docs site

kong/runloop/mesh.lua
Thanks to @shashiranjan84 for catching this.
=> fix(runloop) fix a typo in Errors.code

kong/api/routes/apis.lua, spec-old-api/02-integration/04-admin_api/02-apis_routes_spec.lua
=> [0.15] fix(api) fix type inference in POST /apis/{apis}/plugins

.travis.yml
Need to explicitey define the stage order for travis-ci
Before:
After:
=> misc(ci) explicitely define the travis-ci stage order

kong-1.0.3-0.rockspec, kong/constants.lua, spec/01-unit/12-plugins_order_spec.lua
This PR adds the kubernetes sidecar injector plugin
Released here: https://github.com/Kong/kubernetes-sidecar-injector/releases/tag/v0.1.0
=> Add kubernetes sidecar injector plugin

README.md
Kong build tools nightly builds have a new location
=> doc(nightly) update docs to link to the new nightly build location

kong/pdk/client.lua, t/01-pdk/05-client/00-phase_checks.t, t/01-pdk/05-client/08-get_subsystem.t, t/01-pdk/05-client/09-get_protocol.t
Adds `kong.request.get_subsystem` and `kong.request.get_protocol`
=> feat(pdk) add get_subsystem and get_protocol functions

kong-1.0.3-0.rockspec
Updating `lua_system_constants` to latest `0.1.3`.
=> chore(deps) updating lua_system_constants to 0.1.3

kong/pdk/client.lua
Fixes a small ldoc problem in a comment. Needed to fix auto-generated docs.
=> chore(pdk) fix comments for PDK docs generation

kong.conf.default
Minor changes in kong.conf.default for improving autodocs.
Related with https://github.com/Kong/docs.konghq.com/pull/1180
=> chore (conf) comment formatting for autodoc

UPGRADE.md
As discussed with @UkiahSmith based on customer feedback, we thought some further clarifications on the migrations process from 0.14 to 1.0 would be helpful.
=> docs(upgrade) add clarifications on Blue/Green

.travis.yml
11 different release types for both releasing and nightly releases
=> chore(ci) add some release types that were missed earlier

.travis.yml
Merge after https://github.com/Kong/kong-build-tools/pull/37
=> chore(ci) when releasing include source releases

.travis.yml, CHANGELOG.md, UPGRADE.md, kong-1.1.0-0.rockspec, kong-1.1.1-0.rockspec, kong.conf.default, kong/api/endpoints.lua, kong/cmd/config.lua, kong/db/migrations/core/001_14_to_15.lua, kong/error_handlers.lua, kong/meta.lua
Merge Kong 1.1.1 into `master` so we can start working on Kong 1.2 :)
=> Merge master into next 2019-04-02

kong/cache.lua, kong/runloop/cache_prewarm.lua
This PR implements cache prewarming exhausted check:
- writes log entry and skips rest of the pre-warming in case the cache
memory is exhausted
=> feat(cache) prewarming cache exhausted check

kong/db/migrations/core/004_110_to_120.lua, kong/db/schema/entities/routes.lua, kong/runloop/handler.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua, spec/02-integration/03-db/02-db_core_entities_spec.lua, spec/02-integration/05-proxy/06-ssl_spec.lua
TODO:
- Break up commits to respect commit atomicity
=> feat: configurable https redirects

kong/init.lua, kong/runloop/plugins_iterator.lua
This PR does two performance improvements:
* It implements a "combo-based" solution for discarding plugin
combinations quickly on the plugins iterator.
* It skips plugin phases which are not different from the default Base Plugin's
In addition to this it adds several refactors:
* Merges together repeated code in the phase checker
* Merges several plugin-related structures into a single one
Extracted from #4488
Co-authored-by: Aapo Talvensaari aapo.talvensaari@gmail.com
=> perf(runloop) only run relevant phases and iterate on relevant plugin combinations

kong/runloop/handler.lua
The current implementation of the router loads everything from the
database, all the time.
Since it iterates over routes, and then it fetches the relevant
service for each route, this means that given a single service with
1000 routes, it will make 1000 requests for the database, returning
the same service.
Some notes regarding "Services changing while the router is being
rebuilt":
* This PR sacrifices some "correctness" for speed: when a service
is changed, it takes time for that change to be propagated to other
workers and kong nodes. If a service is changed it will take some
seconds before that change is made effective in the router.
* Consider that even on the current case (were no caching is used),
if the Service changes while the router iterates over route number
501, the first 500 …
=> perf(router) cache service loading in router

spec/01-unit/08-router_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/fixtures/custom_nginx.template
Fixes router slash handling integration tests spotted while doing the "waiting to be resolved": #4538.
=> tests(router) fix slash handling integration tests

kong/cache_warmup.lua, kong/init.lua, kong/runloop/handler.lua
Addresses several code review comments left after some recent PRs were merged. Some important catches there, thanks @thibaultcha for the :eyes:!
=> hotfix(core) address misc code review comments

kong/db/dao/plugins.lua, kong/init.lua, kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua, spec/01-unit/01-db/07-dao/01-plugins_spec.lua, spec/02-integration/06-invalidations/03-plugins_plan_invalidation_spec.lua
This PR contains reordenings and refactors in preparation for the async reloading work.
=> refactor(runloop) async groundwork

.ci/run_tests.sh, spec/02-integration/02-cmd/10-migrations_spec.lua
Recently the PR #4555 was manually merged, and manual changes caused some tests to fail. This PR is about to make the test suite green again.
=> tests(migrations) fix test errors on migrations test suite caused by case-changes

kong/plugins/ldap-auth/access.lua
=> style(ldap-auth) add missing error check and fix small typos in the

spec/helpers.lua
Add the same kind of handshake in `helpers.tcp_server` that we already do in `helpers.udp_server`. Hopefully, this will reduce flakiness in tests that use the `tcp_server` such as the frequent failures in the plugin tests for `tcp-log`.
=> tests(tcp) reduce flakiness using a handshake in tcp_server

kong-1.1.2-0.rockspec, kong/constants.lua, spec/01-unit/12-plugins_order_spec.lua
This branch adds kong-proxy-cache-plugin dependency. 
* Added kong-proxy-cache-plugin to bundled plugins.
=> feat(plugins) add proxy-cache plugin

kong/runloop/handler.lua
Miscellaneous cleanups on the runloop extracted originally from #4488
=> refactor(runloop) assorted cleanups

CHANGELOG.md
=> docs(changelog) add 1.2.0rc2 changes

kong-1.1.2-0.rockspec, kong/constants.lua, spec/01-unit/12-plugins_order_spec.lua
Adds [session](https://github.com/Kong/kong-plugin-session) plugin to bundled plugins:
Relevant Session Plugin PR: https://github.com/Kong/kong-plugin-session/pull/9
=> feat(plugin) add session plugin

kong-1.1.2-0.rockspec
Bumps Lapis to `1.7.0.1` (Kong fork)
I first wanted to implement this to possibly solve the issue #4672, but I tested it even with current `next` and I could not reproduce that bug even without this bump. But there is some issues lurking in Lapis, that maybe it is good idea to bump on our side too.
- Replaced the CSRF implementation, removed the key parameter and replaced with it randomly generated string stored in cookie.
- Sessions now use the lapis.encoding module to encode an decode. Session loading error messages have changed to include the error from encode_with_secret and decode_with_secret
- Remove all support for luacrypto, luaossl is required
- Add support for chaning HMAC function, add sha256 HMAC config option
- Support parsing cookies when there are multiple cookie headers
- …
=> chore(deps) bump kong-lapis from 1.6.0.1 to 1.7.0.1

kong/db/schema/init.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua
We need the schema fix from `master` in `next`.
=> Merge master into next 2019-06-10

kong/db/strategies/postgres/connector.lua
The reason is that transaction may acquire unneccessary locks, and is
also non-resilient to errors, e.g. if one table is missing `ttl` column
no cleanups will be done to other tables either.
This changes the code so that cleanups are ran separately on each table.
It might have something to do with #4601.
=> perf(db) delete expired rows without transaction with postgres

kong/db/schema/init.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua
=> fix(schema) handle conditional entity checks on false values

CHANGELOG.md, kong-1.2.1-0.rockspec, kong.conf.default, kong/meta.lua
=> Merge master into next 2019-07-01

README.md
Fixed punctuation.
* ...
Fix #XXX
Fixed punctuation.
=> docs(readme) add missing punctuation

CONTRIBUTING.md, README.md, kong/db/dao/init.lua, kong/db/strategies/cassandra/init.lua, kong/runloop/handler.lua
=> Merge master into next 2019-07-23

kong/plugins/hmac-auth/access.lua, spec/03-plugins/19-hmac-auth/03-access_spec.lua
=> fix(hmac-auth) correctly report http 1.0

spec/01-unit/01-db/01-schema/06-routes_spec.lua, spec/02-integration/04-admin_api/09-routes_routes_spec.lua
Minor changes pending from #4801.
=> tests(*) address grpc review

spec/03-plugins/09-key-auth/02-access_spec.lua
underscores while sending API keys
This has been supported in Kong, test confirms that.
=> tests(key-auth) add tests using header names containing hyphens or

kong/db/strategies/postgres/connector.lua
The postgres ttl cleanup timer used to error with:
```
[error] runtime error: ./kong/db/strategies/postgres/connector.lua:343:
attempt to perform arithmetic on local 'num_queries' (a nil value)
coroutine 0:
./kong/db/strategies/postgres/connector.lua: in function
<./kong/db/strategies/postgres/connector.lua:336>,
```
When it had issues on for example connecting to Postgres database.
This PR changes it to this:
```
[error] [lua] connector.lua:360: unable to clean expired rows from PostgreSQL database
(connection refused)
```
=> chore(db) better error messages on postgres ttl cleanup timer

Makefile
this make task was renamed and missed
=> fix(Makefile) adjust renamed make target

spec/02-integration/05-proxy/10-balancer_spec.lua
remove some dead code, left over of previous mock implementation not picked up by linter
=> refactor(tests) remove dead code

kong/runloop/handler.lua
Recently we found out that regex used with hop-by-hop headers can be a 5 to 10% of our hot path code. This PR removes the regex usage on those places.
=> perf(proxy) remove regex from hop-by-hop removal on a hot path

DEVELOPER.md
Merging the developer guide to the master branch.
=> docs(misc) Merging the developer guide to the master branch.

kong/plugins/oauth2/access.lua, spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua
Needed since #4150 was merged.
=> tests(oauth2) adjust tests to now-optional field redirect_uris

kong/db/schema/others/declarative_config.lua, spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
The uuid generator used by declarative config inadvertedly
assumed that the entities were nested.
Fixes #4954.
=> fix(declarative) correct id generation on flat relationships

kong/api/routes/config.lua, spec/02-integration/04-admin_api/15-off_spec.lua
The endpoint exports the currently running configuration for DB-less
nodes.
The configuration is returned as YAML string encoded inside a JSON
object with a `config` key.
This is chose for two reasons:
- The output of this endpoint can then be directly fed in as well,
which helps in debugging, the primary use-case for this endpoint:
```
http :8001/config -o response.json    # export
cat response.json | http :8001/config # re-import on different node
```
- It would be idea to send back client a JSON configuration in the body
but that's not possible yet as the export method only supports YAML
and adding that is outside the scope of this work.
Once JSON is supported as an output format, it can be added to this
endpoint in a non-breaking change fashion by looking up the
content-type in the …
=> feat(admin) implement GET /config for db-less

kong/runloop/plugins_iterator.lua
At the moment plugins make Kong not to work very well when database connection is not available. Even when we do pre-warming, because we don't do negative cache pre-warming. That in general results a DB call.
Previous attempt to fix this was to load all the plugins in memory, but that raised concerns of consumers and plugins applied to them. This PR changes plugin iterator to cache route and service ids. Sure there can be a lot of routes and services too, but those are the entities that we already cache quite extensively.
It allows me to:
1. start kong
2. stop postgres
3. proxy all those requests that were mentioned in #4807
Fix #4807
=> perf(proxy) cache plugins route and service ids

kong/plugins/file-log/handler.lua
Because the `log` function has no yielding calls, running it inside timer context is a waste of CPU cycles.
=> fix(file-log) remove unnecessary timer and cache hot path functions

CODE_OF_CONDUCT.md
As set out in Issue #5090 update email, the email address in the code of conduct is incorrect.
* Update support email in code of conduct
Fix #5090
=> Update code of conduct #5090

CHANGELOG.md
=> chore(changelog) fix typos

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Added comment tags to pull request template and issue template
* Added comment tags to pull request template
* Added comment tags to issue template
Added comment tags to pull request template and issue template to prevent adding this text accidentaly to issues and pull requests when using the template.
=> chore(github) comment tags to pr template & issue template

kong-1.3.0-0.rockspec
-  add `authenticated_groups` to storage
=> chore(deps) bump kong-session-plugin to 2.2.0

kong/pdk/client.lua
Update LuaDoc to correct format to fix docs auto-generator.
=> docs(pdk) update LuaDoc to correct format to fix docs auto-generator

.travis.yml
followed the travis-ci setup wizard to generate a token and encrypt it.
=> chore(ci) add slack notifications

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .travis.yml, CHANGELOG.md, CONTRIBUTING.md, UPGRADE.md, kong-1.4.0-0.rockspec, kong.conf.default, kong/cmd/utils/prefix_handler.lua, kong/conf_loader.lua, kong/init.lua, kong/meta.lua, kong/pdk/client.lua, kong/runloop/handler.lua, kong/templates/kong_defaults.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/05-proxy/04-plugins_triggering_spec.lua, spec/02-integration/05-proxy/06-ssl_spec.lua, spec/02-integration/05-proxy/20-serviceless_proxying_spec.lua, spec/02-integration/05-proxy/22-reports_spec.lua, t/01-pdk/05-client/08-get_protocol.t
=> Merge master into next 2019-10-28

Makefile, spec/01-unit/09-balancer_spec.lua, spec/01-unit/11-reports_spec.lua, spec/01-unit/14-dns_spec.lua
This PR contains two commits:
- chore(deps) update busted from 2.0.rc13 to 2.0.0 (dev dependency)
- chore(deps) update luacheck from 0.20.0 to 0.23.0 (dev dependency)
=> chore(deps) update development dependencies for busted and luacheck to lastest

.ci/setup_env.sh
`master` or tagged release while `next` for all other branches
Travis doc: https://docs.travis-ci.com/user/environment-variables/
=> chore(ci) use `master` branch of openresty-patches while building the

kong-1.4.0-0.rockspec
Changes:
-  add support for O_TRUNC
=> chore(deps) update lua_system_constants from 0.1.3 to 0.1.4

kong-1.4.0-0.rockspec
fix: delete makes the index of data incorrect (see https://github.com/Kong/lua-multipart/pull/23, thank you @jayce)
=> chore(deps) bump multipart from 0.5.5 to 0.5.6

UPGRADE.md
Corrected the typo mistake of decommission in whole document
* ...
Fix #XXX
=> UPGRADE.md

spec/02-integration/02-cmd/02-start_stop_spec.lua
This specific start / stop test would sometimes fail with 
```
send() failed (104: Connection reset by peer), context: ngx.timer
```
My thoughts are kong/nginx are "running" but not yet "ready". Adding a `kong health` check ensures that Kong is totally prepared to start processing requests and has reduced the flakiness
=> tests(integration) reduce the flakiness of the start stop test

spec/03-plugins/16-jwt/03-access_spec.lua
Adds test for a feature contributed by community member @davinwang.
=> tests(jwt) add tests for X-Credential-Identifier merged with #4993

kong/plugins/request-size-limiting/handler.lua, kong/plugins/request-size-limiting/schema.lua, spec/03-plugins/12-request-size-limiting/01-access_spec.lua
This PR cherry-picks https://github.com/Kong/kong-ee/commit/11ea5be97ceae86282544bf607bb49fbdbd00564 (not visible to public) which basically add size unit option to config.
=> feat(plugins/request-size-limiting) allow size unit (#1352)

spec/03-plugins/03-http-log/01-log_spec.lua
Some tests were failing due to timeouts on CI. Local runs did not time out, but presented some delays related to `flush_timeout`. Reducing `flush_timeout` and the number of test iterations should make tests fast enough so that the current timeout is within a safe range.
=> tests(http-log) make http-log tests faster

spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua, spec/03-plugins/02-udp-log/01-udp-log_spec.lua, spec/03-plugins/03-http-log/01-log_spec.lua, spec/03-plugins/04-file-log/01-log_spec.lua
Add test cases for grpc/grpcs on logging plugins.
- tcp-log
- udp-log
- http-log
- file-log
=> tests(grpc) add logging plugin tests

spec/03-plugins/05-syslog/01-log_spec.lua, spec/03-plugins/06-statsd/01-log_spec.lua, spec/03-plugins/07-loggly/01-log_spec.lua
Add tests for grpc on Statsd, Syslog, and Loggly.
=> tests(*) grpc logging plugins

kong/api/routes/certificates.lua, kong/db/dao/certificates.lua, spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
@hbagdi reported issue on `PUT` behavior on `/certificates` with #5309.
This PR fixes the `PUT` behavior. It also fixes several other issues
found while fixing the original issue.
Fix #5309
=> fix(admin-api) incorrect PUT behavior for /certificates

scripts/make-patch-release
New script to automate most of the release process of a patch release (x.y.(z+1)).
=> feat(scripts) make-patch-release script

kong-1.4.0-0.rockspec
bump up Prometheus plugin to 0.7
* https://github.com/Kong/kong-plugin-prometheus/blob/master/CHANGELOG.md#070---20191204
=> chore(deps) bump up prometheus plugin to 0.7

UPGRADE.md
Fixed some spelling errors in this file.
Corrected spelling of "implementaion" to "implementation" in  certain paragraphs.
=> fix(docs): UPGRADE.md - fix spelling

kong-1.4.2-0.rockspec
This PR bundles the acme plugin.
* Initial release of kong-plugin-acme.
=> feat(plugins) add the acme plugin

kong-1.4.2-0.rockspec, kong.conf.default, kong/conf_loader.lua, kong/db/dao/plugins.lua, kong/db/dao/plugins/go.lua, kong/db/schema/plugin_loader.lua, kong/init.lua, kong/runloop/plugins_iterator.lua, kong/templates/kong_defaults.lua, spec/helpers.lua, spec/kong_tests.conf
Allows Kong to use external plugins via MessagePack-RPC.  See https://github.com/Kong/go-pluginserver for the Go implementation.
=> feat(plugins) Go plugin support

UPGRADE.md, autodoc/data/admin-api.lua, kong-1.4.2-0.rockspec, kong/db/schema/others/declarative_config.lua, kong/runloop/balancer.lua, scripts/autodoc-admin-api
=> Merge master into next 2019-12-20

kong-1.4.2-0.rockspec
includes:
- fix: reduce notice-level message to debug, to reduce log noise
- feat: added 3 regions; eu-north-1, me-south-1, eu-west-3
=> chore(deps) bump kong-plugin-aws-lambda to 3.1.0

LICENSE, README.md, kong/tools/timestamp.lua, kong/tools/utils.lua, spec/helpers.lua
Update copyright notices to 2020.
=> chore(*) the year is 2020

kong/db/dao/plugins/go.lua
=> style(go) add more comment and make the Kong <-> Plugin server

kong/db/dao/plugins/go.lua
Fix issue introduced with a recent commit. I'm currently adding integration tests, which will detect such issues. For now, it's okay to merge this fix without a regression test.
=> fix(go) remove spurious assertion

CHANGELOG.md, kong-1.4.3-0.rockspec, kong/init.lua, kong/meta.lua, kong/router.lua, kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua, spec/02-integration/05-proxy/02-router_spec.lua
=> Merge master into next 2020-01-10

README.md
I don't think it is correct to advertice Service Mesh in our `readme.md` after the feature is going to be removed with 2.0.
=> docs(readme) remove service mesh

kong/plugins/acl/handler.lua, spec/03-plugins/18-acl/02-access_spec.lua
This is an alternative approach to #5277 and #5236.
The background:
`acl` plugin runs before `request-termination` plugin, and `acl` plugin only returned `403`. `403` seems like a correct status code for authenticated consumers as they are not `unauthorized or 401`. And also for anonymous consumers, if the consumer has `acl` groups configured (which I have never seen outside our test suite). But otherwise anonymous consumers should be getting `401`.
This PR tries to do almost the same as #5277 and #5236, but also tries to not touch to tests too much and thus keeping the original behavior intact (there is one test that needed to be changed).
All this work is from inspiration of Kong community, and I (@bungle) was just a tool to polish the idea a bit.
Huge thanks to @jeremyjpj0916, and …
=> feat(acl) 401 instead of 403 when no credentials found in context

kong/cmd/utils/prefix_handler.lua
Signed-off-by: bevisy <binbin36520@gmail.com>
fix(ssl_cert) incorrect calculation of certificate validity period
=> fix(ssl_cert) incorrect calculation of certificate validity period

kong/db/dao/plugins/go.lua
The Lua style of multivalue maps (used by `get_query()` and `get_headers()` functions) uses different value types to represent multiplicity of types:
- present but no value: boolean true
- one value: string
- multiple values: array of strings
In a static-type language, this results in a very verbose code.  This PR changes the representation into a more regular "map of string arrays", where the "no value" case is an empty array.
related PRs: Kong/go-pdk#19 , Kong/go-pluginserver#12
=> Multivalue maps

kong/plugins/acl/groups.lua, kong/plugins/acl/handler.lua, spec/03-plugins/18-acl/02-access_spec.lua
The PR #5440 tried to fix the issue with ACL plugin, but it didn't do it completely. As seen here:
https://github.com/Kong/kong/pull/5440#issuecomment-574720075
This is a second try to fix it so that anonymous consumers that do not have ACL groups will get `401` status code instead of `403`.
Fix #4480 (again)
=> fix(acl) second try fixing acl plugin to return 401

kong/reports.lua, spec/01-unit/11-reports_spec.lua
=> chore(*) cherry pick from next

.travis.yml, spec/02-integration/10-go_plugins/01-reports_spec.lua, spec/fixtures/custom_plugins/kong/plugins/reports-api/api.lua, spec/fixtures/go/go.mod, spec/fixtures/go/go.sum, spec/helpers.lua
=> tests(go) reports tests

kong/runloop/handler.lua
=> fix(balancer) fix check to see if response was produced by upstream

spec/03-plugins/13-cors/01-access_spec.lua
Adds tests for PR #5511 by @zytrik.
=> tests(cors) remove upstream ACAO header if no match is found

kong/plugins/basic-auth/schema.lua, kong/plugins/hmac-auth/schema.lua, kong/plugins/jwt/schema.lua, kong/plugins/key-auth/schema.lua, kong/plugins/ldap-auth/schema.lua, kong/plugins/oauth2/schema.lua, spec/03-plugins/09-key-auth/02-access_spec.lua, spec/03-plugins/10-basic-auth/03-access_spec.lua, spec/03-plugins/16-jwt/03-access_spec.lua, spec/03-plugins/19-hmac-auth/03-access_spec.lua, spec/03-plugins/20-ldap-auth/01-access_spec.lua, spec/03-plugins/25-oauth2/03-access_spec.lua
=> fix(plugins) accept consumer username in anonymous field

spec/02-integration/05-proxy/22-reports_spec.lua
Do not restart Kong in between each test.
On my machine, this file went from 26s (Pg + C*) down to 2.6s.
Hopefully, avoiding the frequent restarts might address flakiness issues with Cassandra on CI as well?
=> tests(reports) speed up reports tests

kong/db/strategies/cassandra/connector.lua, kong/db/strategies/postgres/connector.lua
=> fix(migrate_apis) fix migrate_apis error on routes.path_handling

.gitignore
=> Added .env to gitignore file !!

spec/03-plugins/09-key-auth/03-invalidations_spec.lua, spec/03-plugins/10-basic-auth/04-invalidations_spec.lua, spec/03-plugins/16-jwt/04-invalidations_spec.lua, spec/03-plugins/17-ip-restriction/02-access_spec.lua, spec/03-plugins/18-acl/02-access_spec.lua, spec/03-plugins/18-acl/03-invalidations_spec.lua, spec/03-plugins/19-hmac-auth/04-invalidations_spec.lua, spec/03-plugins/20-ldap-auth/01-access_spec.lua, spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua, spec/03-plugins/25-oauth2/04-invalidations_spec.lua
removes duplicate code and applies (an existing) test helper function
=> chore(test) apply test helper function for invalidation

kong/cmd/migrations.lua, spec/02-integration/02-cmd/10-migrations_spec.lua
also removes the prompt for a reset, if there is nothing to reset.
fixes #5605 
replaces #5606
=> feat(cli) add --force flag to bootstrap command

kong/tools/dns.lua
=> fix(dns) config parameters swapped

.gitignore, spec/config.ld, spec/helpers.lua, spec/ldoc.css, spec/readme.md
The docs itself are not included, but the base files to generate are.
The updates to the helpers are only additional doc comments, and some reordering. No functional changes.
Results are not perfect, but seem complete.
=> Adds developer docs wrt test helpers

spec/02-integration/01-helpers/01-helpers_spec.lua, spec/02-integration/05-proxy/06-ssl_spec.lua, spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua, spec/helpers.lua
Had a bad description, fixed it and added a certificate modifier.
Existing tests updated to use the new modifier
Related comment on previous PR: https://github.com/Kong/kong/pull/5643#discussion_r391672685
=> tests(helpers) fix the cn assertion

CHANGELOG.md
=> docs(changelog) add 1.5.1 changes

Jenkinsfile, Makefile
https://github.com/Kong/kong-build-tools/compare/3.1.4...4.0.1
- KBT can run PDK test suite now
- need to set the debug value explicitly when doing releases
- fix AWS daily tests failures
- fix logrotate line ending
CHANGELOG ENTRY: Fix logrotate line ending credit to WALL-E ( https://github.com/Kong/kong-build-tools/pull/243 )
=> chore(dependency) bump the KBT dependency

spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/fixtures/hosts
This was based on an old left-over AWS Lambda fixture
=> replace fixtures by test specific mocks

scripts/make-patch-release
I haven't tested this / I'm not sure how to (easily test it) outside of a release.
I copied the existing format of the previous scripts and used the instructions from https://github.com/Kong/kong-pongo/blob/master/README.md#releasing-new-kong-versions
=> chore(pongo) add a pongo step to our release script

Makefile
bumping the dependency to fix github actions per Kong/kong-build-tools#248
=> chore(dependency) bump the kong-build-tools dependency

kong-2.0.2-0.rockspec
See: https://github.com/Kong/kong-plugin-session/pull/16
=> chore(deps) bump kong session plugin from 2.2.0 to 2.3.0

spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua, spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua, spec/helpers.lua
some test related updates/cleanup
=> chore(tests) some test related updates/cleanup

kong/db/dao/targets.lua
=> fix(admin-api) properly invalidate target history at cleanup

kong-2.0.3-0.rockspec
Changelog:
https://github.com/Kong/kong-plugin-prometheus/blob/master/CHANGELOG.md#080---20200424
=> chore(deps) bump up prometheus plugin to 0.8

.luacheckrc, kong-2.0.3-0.rockspec, kong/db/dao/init.lua, kong/db/iteration.lua, kong/hooks.lua, spec/01-unit/019-hooks_spec.lua, spec/02-integration/03-db/12-dao_hooks_spec.lua
Introduce a hooks module and add hooking points to the DAO.
Hooks are named functions that are executed at specific locations
previously specified with a `run_hook` call.
=> feat(dao) hooks

kong-2.0.3-0.rockspec
See: https://leafo.net/lapis/changelog.html
=> chore(deps) bump kong-lapis from 1.7.0.1 to 1.8.1.1

kong/db/dao/plugins/go.lua
Supersedes https://github.com/Kong/kong/pull/5826.
Thanks @wopol for the contribution!
=> fix(go) reload plugin configuratin if new exists

kong-2.0.4-0.rockspec
=> chore(rockspec) add migration

kong/db/dao/plugins/go.lua, kong/runloop/plugins_iterator.lua
Both fixes were merged into next, while they should've been merged into master.
=> chore(*) cherry pick go fixes into master

kong/plugins/basic-auth/access.lua
Both of username and password are required fields in basic-auth schema.
This PR prevents fetching of credentials from the db, if the password is
not provided in authorization headers. This would help in avoiding
unnecessary calls to the db and caching of credentials.
=> chore(basic-auth) avoid fetching credentials when password not given

Makefile, kong/db/dao/init.lua, kong/db/schema/entities/targets.lua, kong/db/schema/init.lua, kong/global.lua, kong/globalpatches.lua, kong/pdk/ctx.lua, kong/pdk/init.lua, kong/pdk/log.lua, kong/plugins/basic-auth/access.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/01-unit/01-db/04-dao_spec.lua, spec/02-integration/03-db/11-db_transformations_spec.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/02-integration/04-admin_api/15-off_spec.lua, spec/02-integration/04-admin_api/18-worker-events.lua, spec/02-integration/05-proxy/22-reports_spec.lua, spec/fixtures/custom_plugins/kong/plugins/transformations/daos.lua, spec/fixtures/custom_plugins/kong/plugins/transformations/handler.lua, spec/fixtures/custom_plugins/kong/plugins/transformations/migrations/000_base_transformations.lua, spec/fixtures/custom_plugins/kong/plugins/transformations/migrations/init.lua, spec/fixtures/custom_plugins/kong/plugins/transformations/schema.lua, spec/fixtures/custom_plugins/kong/plugins/worker-events/handler.lua, spec/fixtures/custom_plugins/kong/plugins/worker-events/schema.lua, spec/helpers.lua, t/01-pdk/05-client/09-load-consumer.t, t/02-global/02-set-named-ctx.t, t/02-global/03-namespaced_log.t
=> Merge master into next 2020-05-18

Jenkinsfile, scripts/make-prerelease-release
during kong 2.1.0-alpha.1 release process I had to ninja edit some fixes to the Makefile and the release script. This PR captures those changes for future us
=> fix(prerelease) reincorporate the fixes I made locally during the prerelease

kong/db/dao/targets.lua
=> fix(dao) check if healt_info exists before using it

kong/cmd/utils/prefix_handler.lua, kong/constants.lua, kong/templates/nginx_kong.lua, kong/templates/nginx_kong_stream.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/fixtures/1.2_custom_nginx.template, spec/fixtures/custom_nginx.template
we're not using these crash reports so going to remove them at this time
=> chore(syslog) remove syslog error reporting

kong/db/dao/plugins/go.lua
Nginx module:
- kong.nginx.get_ctx
- kong.nginx.set_ctx
Ctx module:
- kong.ctx.shared.get
- kong.ctx.shared.set
=> feat(go) add ctx methods to go-pdk

spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/03-pki_spec.lua
These tests seemed to have bit-rotten a bit, so I gave them some love locally and they seem to run fast and pass ok on Travis now
=> tests(hybrid) re-enable hybrid mode tests

kong/cache.lua, kong/cmd/utils/prefix_handler.lua, kong/constants.lua, kong/db/dao/targets.lua, kong/db/declarative/init.lua, kong/db/schema/others/declarative_config.lua, kong/runloop/balancer.lua, kong/runloop/handler.lua, kong/templates/nginx_kong.lua, kong/templates/nginx_kong_stream.lua, spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua, spec/01-unit/01-db/10-declarative_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/02-integration/04-admin_api/15-off_spec.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua, spec/fixtures/1.2_custom_nginx.template, spec/fixtures/custom_nginx.template, spec/helpers.lua
=> Merge master into next 2020-06-03

.github/workflows/build_and_test.yml
Need more discussion or results: do we need to run CI against all branches or only PR's and specific branches?
=> chore(ci) run CI against all branches / PR's

scripts/make-prerelease-release
as opposed to alpha releases with a beta release we want:
- docs
- homebrew
- docker
- pongo
=> chore(ci) setup beta release capabilities

kong/db/strategies/postgres/init.lua
Just removes dead-code not needed anymore.
=> chore(db) remove dead-code from postgres strategy

CHANGELOG.md
Incorporate new changes (https://github.com/Kong/kong/pull/5994/) into 2.1.0 prerelease changelog.
=> docs(changelog) add new entries to 2.1.0 prerelease changelog

README.md
=> docs(readme): updating to reflect focus areas

kong/init.lua, kong/runloop/balancer.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/10-balancer/05-recreate-request_spec.lua
Integration test adds ~2 sec to the CI run time.
=> fix(balancer) update the Host header between balancer retries

kong/api/routes/config.lua, kong/db/declarative/init.lua, spec/02-integration/04-admin_api/15-off_spec.lua
=> fix(api) hide workspace related internal information inside

kong/db/migrations/operations/200_to_210.lua
Split from https://github.com/Kong/kong/pull/6097 on @kikito's behalf.
=> fix(migrations) reset default value for ws_id

CHANGELOG.md, kong-2.1.0rc.1-0.rockspec, kong/meta.lua, t/01-pdk/08-response/11-exit.t
=> chore(*) 2.1.0rc1

kong/db/migrations/operations/200_to_210.lua
Fixes several problems which might be visible if someone is upgrading the bot-detection plugin in postgres.
* Formatting of render as if it was fmt
* pgmoon_json.encode_json vs json_encode
* the json encode function already returns json quoted in single quotes.
* missing ::jsonb in the literal
* `SELECT * FROM 'plugins'` replaced by `SELECT * from plugins` (no quotes)
* ...
Fix #XXX
=> fix(migrations) fix fixup_plugin_config function

autodoc/data/admin-api.lua, scripts/autodoc-admin-api
According to Docs Team feedback on Docs PRs.
=> docs(autodocs) fix minor issues

CHANGELOG.md
Fixes #6151 
@jeremyjpj0916 please take a look, let me know if this is what you'd expect to find there!
=> docs(changelog) add clarification on OpenResty version bump

autodoc/data/admin-api.lua, kong.conf.default
brings over missing changes from https://github.com/Kong/docs.konghq.com/pull/2130
=> docs(*) fix typos on conf and admin-api autodocs

kong/plugins/rate-limiting/handler.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua
previously the scope of "service" policy was more about the plugin scope than the services.
=> fix(rate-limit) reduce scope of "service" policy

kong/pdk/response.lua, t/01-pdk/08-response/13-error.t
A new PDK `kong.response.error` method was [recently introduced](https://github.com/Kong/kong/pull/5562); however, said method does not handle grpc requests correctly: it forces the content-type to `application/json` and does not set proper `grpc-status` and `grpc-message` headers. This PR fixes these issues.
=> fix(pdk) kong.response.error respects grpc content-type

DEVELOPER.md
=> Typo fixed

CHANGELOG.md
=> docs(changelog) fixed a small typo

kong/conf_loader/listeners.lua, kong/constants.lua, kong/db/schema/entities/routes.lua, kong/db/schema/entities/routes_subschemas.lua, kong/db/schema/entities/services.lua, kong/reports.lua, kong/router.lua, spec/01-unit/01-db/01-schema/05-services_spec.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua, spec/02-integration/04-admin_api/09-routes_routes_spec.lua, spec/02-integration/04-admin_api/10-services_routes_spec.lua, spec/02-integration/05-proxy/26-udp_spec.lua, spec/fixtures/custom_nginx.template
This PR adds basic UDP proxying support to Kong.
=> feat(stream) UDP proxy support

kong/clustering.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
met
Otherwise the test will sometimes fail with a "attempt to
concatenate a nil value" error.
=> tests(clustering) return nil when `wait_until` condition wasn't

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, kong/init.lua
=> Merge master into next 2020-09-11

DEVELOPER.md
Update the $PATH variable after the kong-build-tools refactor.
=> docs(DEVELOPER) update the $PATH variable

kong/clustering.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
=> feat(clustering) pre-create the config cache file with 0600 permission

README.md, kong/init.lua
=> Merge master into next 2020-10-02

CODE_OF_CONDUCT.md
=> Pledge Grammar corrected

kong/db/migrations/core/005_120_to_130.lua, kong/db/migrations/core/007_140_to_150.lua, kong/db/migrations/core/008_150_to_200.lua, kong/db/migrations/core/009_200_to_210.lua, kong/db/migrations/core/010_210_to_211.lua, kong/db/migrations/helpers.lua, kong/db/migrations/operations/200_to_210.lua, kong/db/migrations/operations/210_to_211.lua, kong/db/migrations/operations/212_to_213.lua, kong/db/strategies/cassandra/connector.lua, kong/plugins/ip-restriction/migrations/001_200_to_210.lua, spec/fixtures/custom_plugins/kong/plugins/with-migrations/migrations/001_14_to_15.lua
This PR is rework of #6411, but as that went south here is another try. This PR is good to be included in possible `2.1.5` and upcoming `2.2.0`.
Fixes at least the multiple workspaces with Cassandra issue as reported by @jeremyjpj0916 on #6403.
=> fix(migrations) multiple default workspaces and wait for schema consensus fix

kong/db/migrations/core/012_213_to_220.lua
Adds proper error handling to 2.1.3 to 2.2.0 migrations. Also removes the non-needed `connect_migrations` call from Postgres. The Cassandra uses `coordinator:execute` on all the migrations.
Rest of the fixes should be merged from master when this PR is merged: #6439.
=> fix(migrations) add proper error handling to 2.1.3 to 2.2.0 migrations

kong.conf.default, kong/api/routes/clustering.lua, kong/db/schema/entities/clustering_data_planes.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/03-pki_spec.lua
Just changes the admin api endpoint `/clustering/data_planes` to a more url friendly `/clustering/data-planes`.
=> style(admin) rename /clustering/data_planes to /clustering/data-planes

kong/db/migrations/core/012_213_to_220.lua
Optimize the migrations from `2.1.0` to `2.2.0`.
I discussed this with @locao and we agreed that there was a room for optimizations, and this PR is a result of that discussion.
=> perf(migrations) optimize 2.1.0 to 2.2.0 migrations

kong/db/dao/plugins/go.lua
Go plugins run the `Log` phase under a timer, which can happen after
the request lifetime, so result of the `kong.log.serialize()` is
preloaded into a module-level table.  Two different Go plugins or two
concurrent requests on the same worker could interfere with each other.
This commit stores this request-specific information using the coroutine
of the timer itself as a key.
Fix: [FTI-1916](https://konghq.atlassian.net/browse/FTI-1916)
=> fix(go) log-preload data was using module-level scope

kong/clustering.lua
Implements a more robust websockets connection and thread management for clustering endpoint.
1. Tries to properly close the connection and notify the client
2. Tries to properly kill the started threads on reconnection
3. Adjusts so that expected events are not logged as errors
- Timeouts
- Closing of connection
4. Does not start zombie threads
Fixes an issue reported by other team.
This also contains additional commit to not cause push configs on clustering_data_planes events.
=> fix(hybrid) more robust clustering connection and thread management

kong.conf.default
These adjustments were made when regenerating the docs in the docs site. Minor wording and formatting changes.
=> docs(conf) minor adjustments to the config comments for docs

UPGRADE.md
=> docs(UPGRADE.md) add upgrade instructions for kong 2.2.0

kong-2.2.0-0.rockspec
- Include the `type` function in template environment.   Because headers may contain array elements such as duplicated headers, `type` is a useful function in these cases.
=> chore(deps) bump kong-plugin-request-transformer from 1.2.x to 1.3.x

kong-2.2.0-0.rockspec
=> chore(deps) bump zipkin to 1.2.0

.github/workflows/build_and_test.yml, UPGRADE.md, kong.conf.default, kong/db/dao/init.lua, kong/db/dao/plugins/go.lua, kong/router.lua, spec/01-unit/08-router_spec.lua, spec/02-integration/05-proxy/06-ssl_spec.lua, spec/02-integration/10-go_plugins/01-reports_spec.lua, spec/fixtures/go/go-hello.go
Merge master into next 2020-11-16
=> Merge master into next 2020-11-16

README.md
Added Note for New Contributors
* [Documentation Update]
* [Linked the respected files as hyperlinks
=> Added Note for New Contributors

kong.conf.default, kong/templates/nginx_kong.lua, spec/fixtures/custom_nginx.template
Enables access logs on cluster listener and writes logs to admin access log.
Fix #6589
=> feat(cluster) enable access log on cluster listener

kong/api/routes/kong.lua, kong/clustering.lua, kong/pdk/node.lua, kong/reports.lua, kong/tools/utils.lua, spec/01-unit/05-utils_spec.lua, t/01-pdk/12-node/00-phase_checks.t, t/01-pdk/12-node/03-get_hostname.t
In addition of adding the new function to the PDK, this PR replaces `utils.get_hostname` everywhere with the new PDK function.
=> feat(pdk) kong.node.get_hostname

CHANGELOG.md
Copy and pasted the description from the EE changelog https://docs.konghq.com/enterprise/changelog/#core
=> docs(changelog) mention the non-root way of running kong

CHANGELOG.md, Jenkinsfile, README.md, kong.conf.default, kong/cmd/reload.lua, kong/cmd/utils/nginx_signals.lua, kong/cmd/utils/prefix_handler.lua, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua, spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/02-integration/02-cmd/03-reload_spec.lua, spec/fixtures/reload.conf
=> Merge master into next 2020-12-17

kong-2.2.1-0.rockspec
=> chore(deps) bump serverless

spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/02-cmd/13-signals_spec.lua, spec/02-integration/03-db/11-postgres-ro_spec.lua, spec/02-integration/05-proxy/06-ssl_spec.lua, spec/02-integration/05-proxy/23-context_spec.lua, spec/02-integration/11-dbless/02-workers_spec.lua, spec/03-plugins/03-http-log/01-log_spec.lua, spec/03-plugins/08-datadog/01-log_spec.lua, spec/03-plugins/25-oauth2/03-access_spec.lua
we have enough wheels, let's not reinvent them...
=> chore(test) apply logfile assertions

kong/runloop/plugin_servers/init.lua
the `kong` table has some special-case magic for the `.log` subtable;
avoid cacheing to preserve this.
Fix #6630
=> fix(go): don't cache `kong.log` methods.

kong/init.lua, kong/pdk/service.lua, kong/resty/ctx.lua, kong/router.lua, kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua, kong/workspaces/init.lua
Just some small `ngx.ctx` optimizations (and one upstream local ngx.var change).
=> perf(*) small ngx.ctx usage optimizations

kong/tools/sandbox.lua, spec/01-unit/020-sandbox_spec.lua
validator function was returning an incorrect error message on execution error.
=> fix(sandbox) fix validate_function and validate

LICENSE
I was looking at the license and I noticed a commit from @hbagdi last year updating the year, so I made this quick PR to update it again.
=> chore(*) the year is 2021 (license update)

kong/plugins/rate-limiting/handler.lua
The PR #5460 tried to fix rate-limiting accuracy issues as reported with #5311. That PR has stayed open for over a year now.
There is a smaller change in that PR that we can make without a lot of work or debating, and this PR contains that only:
1. it removes extra phase handlers and context passing of data and now does everything in `access` phase (this could make it more accurate as well, compared to post-poning that to log phase)
2. it now also sets rate-limiting headers when the limits have exceeded
=> fix(rate-limiting) remove unneeded phase handlers for better accuracy

scripts/autodoc
This will work as before, it will generate files in autodoc/output (it will print an info message now)
scripts/autodoc
The following however will also try to install the generated files in the docs folder for
you:
scripts/autodoc ../docs.konghq.com 2.3.x
=> docs(autodoc) scripts/autodoc can install files in docs repo

kong-2.3.1-0.rockspec
=> chore(deps) bump luasec from 0.9 to 1.0

CHANGELOG.md, kong-2.3.2-0.rockspec, kong/cmd/migrations.lua, kong/db/schema/entities/routes.lua, kong/meta.lua, kong/router.lua, kong/runloop/handler.lua, kong/tools/uri.lua, spec/01-unit/08-router_spec.lua, spec/01-unit/18-tools_uri_spec.lua, spec/02-integration/02-cmd/10-migrations_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/02-integration/05-proxy/08-uri_encoding_spec.lua
=> Merge master into next 2021-02-10

scripts/make-patch-release
Change is compatible with GNU sed and BSD sed shipped with MacOS.
=> chore(scripts) fix sed commands

kong/pdk/client.lua, kong/pdk/request.lua, kong/pdk/service/request.lua
=> fix(pdk) ensure PDK type comments are followed correctly

README.md
=> docs(readme) mention master builds

README.md
=> docs(readme) added link for IBM Cloud deployment on README

kong/runloop/handler.lua
This issue is documented by @goober at:
https://github.com/goober/kong-websocket-bug
Fix #6691
Fix #5714
Fix #6921
=> fix(proxy) do not clear Upgrade header if response Connection header contains Upgrade

kong/constants.lua, kong/db/declarative/init.lua, kong/init.lua, kong/runloop/handler.lua
=> refactor(db) simplify cache code in kong.init

CHANGELOG.md, kong/init.lua, kong/runloop/balancer.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/10-balancer/05-recreate-request_spec.lua
=> Merge master into next 2021-03-23

kong-2.3.3-0.rockspec
=> chore(deps) bump kong-prometheus-plugin to 1.2.0

.luacheckrc, kong-2.4.0beta.2-0.rockspec, kong/tools/kong-lua-sandbox.lua, kong/tools/sandbox.lua, spec/01-unit/020-sandbox_spec.lua
This change requires https://github.com/Kong/kong-lua-sandbox/pull/1 to be merged and the steps described in that pr (tag, published rock) in order to be mergeable. Before that happens, CI will complain about not finding the luarock.
=> chore(deps) use kong's sandbox instead of kikito's

kong/plugins/file-log/handler.lua, kong/plugins/http-log/handler.lua, kong/plugins/loggly/handler.lua, kong/plugins/syslog/handler.lua, kong/plugins/tcp-log/handler.lua, kong/plugins/udp-log/handler.lua
08b5349be introduced a new feature, but did not bump the version.
=> chore(plugins) bump logging plugins

kong/pdk/client.lua
=> chore(pdk) adjust ambigious comment for kong.client.load_consumer

autodoc/admin-api/data/admin-api.lua, scripts/autodoc
- Add missing autodoc data for `/schemas/plugins/validate`
- Ensure all PDK files are individually copied
=> fix(docs) autodocs fixes

scripts/make-patch-release, scripts/make-prerelease-release
Default base branch in the docs repo changed to `main`
=> chore(scripts) update docs base branch

kong/pdk/response.lua
=> docs(pdk) document underscore transformations in kong.response.set_headers

kong.conf.default
=> docs(conf)  Use of declarative_config for data plane nodes.

kong/tools/utils.lua
=> refactor(utils) skip wrapper function

autodoc/admin-api/data/admin-api.lua
=> docs(admin-api) document Tags UTF-8 names

kong/pdk/response.lua
See https://konghq.atlassian.net/browse/DOCU-397 and @lena-larionova 's comment in https://github.com/Kong/docs.konghq.com/pull/2646#issuecomment-789123732.
=> [DOCU-397] Fix format in autogen PDK template

CHANGELOG.md
This was requested by the docs team.
=> docs(changelog) reword changelog point to make it clearer

kong/plugins/syslog/handler.lua, kong/plugins/syslog/schema.lua
Allow to configure a specific facility within the syslog plugin.
Add facilities to schema.lua and handler.lua.
NA
=> feat(syslog) add facility configuration capability

README.md
Redirect to the right OSS section of the installation page.
=> docs(README) Update the installation links

kong/tools/uri.lua
This commit tries to do several optimization on our url normalization code that is executed on our hot path.
Optimizations:
1. runs regex only when it looks like it is needed
2. does `/..`, `/.`, and `//` normalization only if needed
3. moves anonymous callback functions to module local functions
=> perf(uri) optimize uri normalization code

kong-2.4.0-0.rockspec
* Fix luaL_buffinit() can use the stack and broke buffer_meth_receive()
=> chore(deps) bump luasec from 1.0 to 1.0.1

.github/ISSUE_TEMPLATE/bug_report.md
Make Kong versions more explicitly on the bug report.
=> chore(*) tweak github bug summary

scripts/common.sh, scripts/make-patch-release
Add a new announce step to patch release script, which echoes text to be used in Kong Nation and Slack announcement.
=> chore(scripts) add announce step to release script

kong/cmd/config.lua, spec/02-integration/02-cmd/11-config_spec.lua
Add file extension metric to db_import.
=> chore(reports) add db-import report for file type

.github/workflows/perf.yml, spec/helpers/perf.lua, spec/helpers/perf/drivers/terraform.lua
Fix some typo and error handling based on recent scheduled test runs.
=> fix(perf) typo and better intermediate error handling

.github/workflows/build_and_test.yml
compression/decompression of artifacts
=> chore(actions) use `actions/cache@v2` which features faster

.github/workflows/build_and_test.yml
=> chore(actions) use `htest` for unit tests, just like the rest of the

kong/pdk/service/request.lua
=> fix(pdk) fix typo

.github/workflows/autodocs.yml, scripts/autodoc
Building autodocs requires a working Kong development environment locally. This commit adds a GitHub Actions
workflow that installs all dependencies, runs autodoc and raises a pull request against the docs repo with
any changes
It is triggered on any commit to master that touchesautodocs/** or when a workflow_dispatch event is received
* Add `.github/workflows/autodocs.yml` workflow
=> chore(autodocs): add autodoc auto-generation workflow

kong-2.4.1-0.rockspec
New minor version because 1 new minor feature was added
=> chore(deps) bump zipkin plugin

.github/workflows/build_and_test.yml, autodoc/admin-api/openapi-gen.lua, kong-admin-api.yml, scripts/common.sh, scripts/gen-admin-api-def.sh, scripts/make-patch-release, scripts/make-prerelease-release
This PR includes:
- The first version of the Kong Admin API definition generator.
- The actual Kong Admin API definition.
- Updates to the release scripts to run the definition generator and update the kong-admin-api.yml file before release.
- An update to the CI script to run the definition generator and check if it's still working.
=> docs(openapi-gen) Kong Admin API definition generator

kong/clustering/control_plane.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
This should finally fix the flakiness of sync compatibility tests.
=> fix(clustering) flakiness in tests and some upvalue override fixes

kong/clustering/control_plane.lua, kong/clustering/data_plane.lua
Move to use a inline ngx.log to preserve source code line in error log
=> fix(clustering) preserve src line in error log

kong/runloop/plugin_servers/process.lua
detects the return code 127 (command not found) to display an
appropriate error.
Also avoids "start&fail storms", it should not do more than one spawn
per second.
=> fix(external-plugins) specific "command not found" error

kong/globalpatches.lua
see https://github.com/Kong/lua-resty-worker-events/issues/41
=> fix(sleep) force time update to prevent deadlocks

kong-2.4.1-0.rockspec
=> deps(dns) bump to 6.0.2

spec/02-integration/05-proxy/14-server_tokens_spec.lua
=> fix(proxy) typo in 14-server_tokens_spec.lua

spec/02-integration/05-proxy/06-ssl_spec.lua, spec/02-integration/05-proxy/25-upstream_keepalive_spec.lua, spec/03-plugins/03-http-log/01-log_spec.lua, spec/03-plugins/25-oauth2/03-access_spec.lua, spec/helpers.lua
also adds some doc comments and fixes some typos
=> chore(test) adds a helper to clear the current error logfile

CHANGELOG.md
I updated the 2.5 changelog with my wording edits and added documentation links as well.
=> docs(changelog) wording changes and docs links

.github/ISSUE_TEMPLATE/config.yml
Adds a "[template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)" which customizes the view at: https://github.com/Kong/kong/issues/new/choose to include 2 new sections:
- "Questions" section to help route users to participate in the Kong discussion forum
- "Security Vulnerability" section to help users understand how to submit vulnerability inquiries.
=> chore(*) added template chooser

kong/db/dao/init.lua, kong/db/schema/init.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/01-unit/01-db/04-dao_spec.lua
Pulling the non-ee changes from https://github.com/Kong/kong-ee/pull/2392 to here. See that PR for an explanation of the issue and my proposed solution.
☝️ 
Fix FTI-1847
=> Decrement workspace_entity_counters on cascade deletes

kong/plugins/grpc-gateway/deco.lua
Transform the "well known type" `.google.protobuf.Timestamp` (a
secs+nanos protobuf structure) to/from JSON datetime string.
requires the `encode hooks` feature starwing/lua-protobuf#145
=> feat(grpc-gateway) encode Timestamp

kong/plugins/aws-lambda/README.md, kong/plugins/aws-lambda/v4.lua, spec/03-plugins/27-aws-lambda/99-access_spec.lua
Import remaining commits from aws-lambda master, since https://github.com/Kong/kong/pull/7464 just got merged and there were new changes.
=> chore(plugins/aws-lambda) import new aws lambda features

kong/plugins/acme/api.lua, kong/plugins/acme/client.lua, kong/plugins/acme/handler.lua, kong/plugins/acme/schema.lua
Import remaining commits from acme master, since https://github.com/Kong/kong/pull/7545 just got merged and there were new changes.
=> chore(plugins/acme) import missing commits

kong/clustering/control_plane.lua
This is largely to improve readability.
N/A
None
=> style: use string.rep instead of a hard-coded string

kong/plugins/datadog/handler.lua
Based on PR https://github.com/Kong/kong/pull/7463
=> chore(datadog) bump version from 3.0.1 to 3.1.0

SECURITY.md, kong/db/dao/init.lua, kong/db/schema/init.lua, scripts/common.sh, scripts/make-final-release, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/01-unit/01-db/04-dao_spec.lua, spec/03-plugins/06-statsd/02-schema_spec.lua, spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua, spec/helpers.lua
Cherry Pick relevant commits from `master` into `release/2.5.x`.
=> chore(releases) cherry-pick from `master` into `release/2.5.x`

spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua, spec/03-plugins/26-prometheus/02-access_spec.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua, spec/helpers.lua
This adds back a few tests marked `pending` and improves stability of some test cases.
=> tests(prometheus) attempt to fix flakiness

kong/router.lua, spec/01-unit/08-router_spec.lua
Fix [#7687](https://github.com/Kong/kong/issues/7687)
=> fix sort routes with both regex and prefix routes

kong/runloop/plugin_servers/process.lua
fix typo（pluginserger->pluginserver）
* fix typo（pluginserger->pluginserver）
=> fix typo（pluginserger->pluginserver）

kong/plugins/proxy-cache/strategies/memory.lua
=> fix(proxy-cache) invalid variable use

kong/conf_loader/init.lua
This will allow playing with it and see what breaks.
=> feat(dns) enable ipv6 as unsupported experimental feature

kong/plugins/acme/handler.lua, spec/03-plugins/29-acme/03-access_spec.lua
=> fix(plugins/acme) escape dots in wildcard domains pattern

Jenkinsfile
- use latest in daily build
- use 3.14 in finals
=> chore(build) update alpine base

.github/workflows/build_and_test.yml, kong/init.lua, kong/templates/nginx_kong.lua
Related: https://github.com/Kong/lua-kong-nginx-module/pull/19
=> perf(vars) use index to access variables

kong/templates/nginx_kong.lua
Adds a few variables to be loaded as indexed variables to boost performance.
=> perf(*) load more indexed vars

kong-2.5.0-0.rockspec, kong/api/routes/plugins.lua, kong/cmd/config.lua, kong/cmd/utils/log.lua, kong/deprecation.lua, kong/globalpatches.lua, kong/pdk/log.lua, t/01-pdk/02-log/06-deprecation.t
With 3.0 coming up, we'll probably be deprecating some elements.
See https://lunarmodules.github.io/Penlight/libraries/pl.utils.html#raise_deprecation
=> feat(pdk) add kong.log.deprecation (and kong.cmd.utils.log.deprecation)

kong/runloop/handler.lua
=> chore(handler) call ngx.http_version() only once, use localized log and exit, and localize ngx.exec

CHANGELOG.md
=> docs(CHANGELOG) changes for 2.6.0

autodoc/admin-api/data/admin-api.lua, autodoc/admin-api/generate.lua, kong-admin-api.yml
Adds documentation for `HEAD` and `OPTIONS` admin api endpoints.
Also updates the autogenerated `kong-admin-api.yml`.
=> docs(admin) add information about HEAD and OPTIONS endpoints

DEVELOPER.md
=> docs fix broken link

kong/global.lua, spec/02-integration/07-sdk/01-ctx_spec.lua, spec/02-integration/07-sdk/02-log_spec.lua, spec/02-integration/07-sdk/03-cluster_spec.lua
Found some small issues with SDK still being around while we use PDK for Plugin Development Kit
=> style(pdk) change references from SDK to PDK

kong/init.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/10-balancer/06-stream_spec.lua
It was reported by @KentAVP that on stream module the retries don't work in #8029
Fix #8029
=> fix(balancer) make stream proxy balancer retries work 

autodoc/admin-api/data/admin-api.lua
Update Admin API autodoc to add that Route is case sensitive. Task initially brought up because of user issue:
https://konghq.atlassian.net/browse/DOCU-46
@kikito
=> [DOCU-46] Admin API: add note about Route case sensitivity

spec/01-unit/21-dns-client/02-client_spec.lua
There are more tests that could benefit from this approach, but these were failing right now.
=> tests(unit) resolve SRV records tests using mock DNS

kong/runloop/plugin_servers/init.lua, spec/02-integration/10-go_plugins/01-reports_spec.lua, spec/fixtures/go/go-hello.go
=> feat(go) allow access to request headers in Log phase

kong/pdk/client.lua, kong/router.lua, kong/runloop/handler.lua
=> fix(*) use a cleaner way to detect tls_passthrough_block variable being

CHANGELOG.md
Fix the link relative to session plugin
Add the info about proxy-cache merge
=> Doc (changelog): fix bad link and add Proxy-cache plugin merged info

kong/clustering/data_plane.lua
This makes extending the functionality a bit easier.
=> style(clustering) split inflating and deflating of config cache to separate methods

autodoc/admin-api/data/admin-api.lua
Feature from https://github.com/Kong/kong/pull/6757
Full doc PR at https://github.com/Kong/docs.konghq.com/pull/3373
=> doc(admin-api) add tls_passthrough in route

kong/plugins/grpc-gateway/deco.lua, kong/plugins/grpc-web/deco.lua, kong/tools/grpc.lua, spec/01-unit/22-grpc-utils_spec.lua, spec/fixtures/grpc/direct_imports.proto, spec/fixtures/grpc/second_level_imports.proto
Recursively scan imported files for services and methods
Fix [FTI-3027]
[FTI-3027]: https://konghq.atlassian.net/browse/FTI-3027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(grpc) allow imported services

kong/tools/kong-lua-sandbox.lua
Fix https://github.com/Kong/kong/discussions/8071
=> fix(sandbox) allow os.date and table.concat in the sandbox [CT-293]

kong/db/schema/entity.lua, kong/db/schema/init.lua
Remove `goto` statements from the schema package for Lua 5.1 compatibility.
None
=> refactor(schema) remove goto statements for Lua 5.1 compat

kong/plugins/rate-limiting/policies/init.lua, kong/plugins/rate-limiting/schema.lua, spec/03-plugins/23-rate-limiting/05-integration_spec.lua
Reverts #8032
This feature needs support in different parts of Kong before being released. We are postponing its release.
=> Revert "feat(rate-limiting) add redis username support (#8032)"

spec/helpers/perf/drivers/local.lua
Summary
fix search nginx_bin in local driver's setup
Full changelog
fix for loop of nginx bin
=> fix(perf) search nginx_bin in local driver

.github/workflows/autodocs.yml
Add the ability to force an environment rebuild in the `autodocs` Action
* Add the ability to force an environment rebuild in the `autodocs` Action
=> Add ability to force autodoc environment rebuild

kong/plugins/acme/client.lua, kong/plugins/acme/schema.lua
Add rsa_key_size configuration option to the acme plugin as mentioned in https://github.com/Kong/kong/discussions/8111.
* adds the configuraiton option
* no tests were added  (cert_type option which is similar has none either)
=> feat(acme) add rsa_key_size config option to acme plugin

spec/02-integration/04-admin_api/11-reports_spec.lua, spec/02-integration/05-proxy/22-reports_spec.lua, spec/02-integration/10-go_plugins/01-reports_spec.lua
=> Fix reports tests issues

LICENSE, README.md, kong/tools/timestamp.lua, kong/tools/utils.lua, spec/helpers.lua
Update copyright years.
ref: 
- https://github.com/Kong/kong/pull/7123
- https://github.com/Kong/kong/pull/6774
**Hold this until the new year comes.** 🎄
* Update copyright years
=> chore(*) update copyright year 2022

kong/resty/ctx.lua
localize ngx.var/ngx.log/ngx.WARN to speed up
* localize ngx.var/ngx.log/ngx.WARN
=> perf(resty.ctx) localize ngx.var/ngx.log/ngx.WARN

.github/PULL_REQUEST_TEMPLATE.md
Add comments to pull request template. Should be more friendly to human. 🤔
=> chore(*) add comments to pull request template

DEVELOPER.md, README.md
Enhance Kong repo's readme/guide to be more friendly to contributors and users.
=> docs(*) improve docs for developer

DEVELOPER.md
- Fix typo
- Format code examples
=> docs(dev) fix typo and format code examples

kong/resty/ctx.lua
localize base.get_request for ctx.lua
* localize base.get_request
=> chore(*) localize get_request for ctx.lua

spec/04-perf/01-rps/04-simple_hybrid_spec.lua, spec/helpers/perf.lua, spec/helpers/perf/drivers/docker.lua, spec/helpers/perf/drivers/local.lua, spec/helpers/perf/drivers/terraform.lua
This PR adds support for performance testing Kong in hybrid mode. The support is restricted to Docker driver.
* Implemented hybrid mode support to Docker driver in the performance test framework.
* Added a spec that does performance test in hybrid mode.
=> feat(tests) adds hybrid mode support to performance test framework

kong/cache/warmup.lua
Code clean, some some optimization
* localize ngx.now/ngx.log/ngx.NOTICE
* use ngx.null in GLOBAL_QUERY_OPTS
=> chore(cache) localize ngx.* for warmup.lua

kong/cache/marshall.lua
localize cjson.encode in marshall.lua
* localize cjson.encode in marshall.lua
=> chore(cache) localize cjson.encode in marshall.lua

spec/fixtures/custom_nginx.template
Just forgot to remove one variable in:
https://github.com/Kong/kong/pull/8351
=> chore(tests) remove unnecessary var index

CHANGELOG.md
- docs(changelog) changelog for 2.7.1
- docs(changelog) add unreleased feats, fixes and big perfs so far
* ...
=> docs(changelog) include 2.7.1 and upcoming changes

kong/cmd/vault.lua, kong/db/schema/entities/vaults_beta.lua, kong/pdk/vault.lua, spec/02-integration/02-cmd/14-vault_spec.lua, spec/02-integration/04-admin_api/19-vaults_spec.lua
=> fix(vaults) some fixes and changes to vaults beta

kong/pdk/vault.lua, kong/vaults/env/init.lua
Two small fixes, check the commits.
=> fix(vaults) replace "-" with "_" when looking up config or env vars

kong-2.7.0-0.rockspec, spec/02-integration/03-db/01-db_spec.lua
See: https://github.com/leafo/pgmoon/releases/tag/v1.14.0
Fix #8259
=> chore(deps) bump pgmoon from 1.13.0 to 1.14.0

CHANGELOG.md
=> docs(changelog) add missing fix in the changelog. 
