Kong/kong

kong/init.lua

This is the seond PR that comes from the discussion of #4171.
Without this patch the Postgres strategy creates 7 non-pooled luasocket connections to database on Kong.init(). This patch reduces that to 3.
Without this patch the Cassandra strategy creates 9 non-pooled luasocket connections to database on Kong.init(). This patch reduces that to 1.
The difference is because Postgres needs to run initialization SQL to setup the connection timezone and database schema on new connections. And for Postgres `connect_migrations` is the same
as `connect` while with Cassandra it is not. It is still a tiny improvement for Postgres as well.

perf(db) improve kong startup time by reusing luasocket on kong.init

---

kong/api/routes/kong.lua
kong/db/dao/init.lua
kong/db/dao/plugins.lua
kong/db/dao/snis.lua
kong/db/dao/targets.lua
kong/init.lua
kong/plugins/acl/groups.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua

This is a first PR that comes from the discussion of #4171.
This changes full table iterations to use `1000` as a page size instead of the previous `100` (the default in admin api).
Introduces slight performance benefits.

perf(db) change page size in full iterations from 100 to 1000

---

kong/plugins/basic-auth/access.lua
kong/plugins/basic-auth/basicauth_credentials.lua
kong/plugins/basic-auth/crypto.lua
spec/03-plugins/10-basic-auth/01-crypto_spec.lua
spec/03-plugins/10-basic-auth/02-api_spec.lua

This commit simply updates the function names used to generated the SHA1 of the basic-auth credential's password to correctly identify the function's purpose and result. This lays the groundwork to be able to use symmetric encryption within Kong at large, without being confused by the legacy functionality present here.
* rename basic-auth plugins `crypto.encrypt` to `crypto.hash`
* rename basic auth plugin credential's DAO local function `encrypt_password` to `hash_password`

style(basic-auth) rename password hashing function

---

kong.conf.default
kong/db/strategies/postgres/connector.lua
kong/templates/kong_defaults.lua
spec/01-unit/04-prefix_handler_spec.lua
spec/02-integration/03-db/01-db_spec.lua

Adds support for Postgres schemas. Makes it possible to use other schemas, and not only the `public` schema in Postgres with an explicit configuration option.
Introduces a new configuration parameter:
```
pg_schema
````
The `unspecified` is the default value of the parameter.
Fix #4145

feat(db) add support for postgres schemas

---

kong/plugins/tcp-log/handler.lua

Do not add a carriage return anymore to payload
(CR is not needed and can produce an invalid JSON on receiver side)
Fix #4048

fix(tcp-log) remove trailing carriage return

---

.github/ISSUE_TEMPLATE.md

Remove the note that GitHub issues are reserved excluslvely for
bug reports, as feature requests are now accepted here as of
950fc30dd53b13699f493177874f9c0300312073.

chore(gh) remove OOD notation in GitHub issue template

---

kong-1.0.0-0.rockspec
spec/02-integration/01-helpers/01-helpers_spec.lua
spec/helpers.lua

The test helper is mainly for plugins testing, since recent changes make the test set up harder. See https://github.com/Kong/kong-plugin/pull/9
* updated `version.lua` to 1.0.1
* added `helpers.get_version()` to dynamically get the Kong version (not from meta data)

Add test helper to get Kong version, bump version.lua to 1.0.1

---

kong/constants.lua
kong/plugins/acl/groups.lua
kong/plugins/acl/handler.lua
spec/03-plugins/18-acl/01-api_spec.lua
spec/03-plugins/18-acl/02-access_spec.lua
spec/03-plugins/18-acl/03-invalidations_spec.lua
spec/fixtures/custom_plugins/kong/plugins/ctx-checker/handler.lua
spec/fixtures/custom_plugins/kong/plugins/ctx-checker/schema.lua

This PR adds support for a new `context` value:
```lua
kong.ctx.shared.authenticated_groups
```
The value of this `context` parameter should be a Lua array, e.g.:
```lua
kong.ctx.shared.authenticated_groups = { "sales", "management" }
```
And updates `ACL` plugin to support the `context` value, in addition to the consumer acl groups that it supported before this patch.
Why?
Authentication plugins that use a 3rd party (other than Kong) to store credentials can benefit from using a central `ACL` plugin to do authorization for them. And this also allows users to do authorization with multiple plugins running in `OR` configuration on a same route or service (well perhaps even globally). Those 3rd party plugins include plugins from core, from community, and plugins in Kong Enterprise, to …

feat(acl) add support for authenticated groups (for 3rd party authentication)

---

kong/db/strategies/postgres/connector.lua

This backports the fix (#4167)  when using non-public schema with Postgres from `next` to `master` without adding the new configuration parameter, so that we can apply this to `1.0.1`.

fix(db) backport postgres schema fix from next to master (only the fix)

---

kong/cmd/utils/prefix_handler.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua

To reproduce the issue, start Kong with:
```
KONG_PROXY_LISTEN=off \
KONG_ADMIN_LISTEN=off \
KONG_STREAM_LISTEN=0.0.0.0:9000 kong start --vv
```
This PR fixes the above to work.

fix(conf) kong crashes on start with only stream listener

---

kong/plugins/aws-lambda/schema.lua
kong/plugins/http-log/sender.lua

Add   "cn-north-1" and  "cn-northwest-1" to the list of allowed regions to permit AWS Lambda
functions to be invoked from the AWS China region.
@thibaultcha Thanks.

feat(aws-lambda) add AWS China region to plugin schema

---

kong/db/dao/plugins.lua
kong/db/init.lua
spec/01-unit/01-db/07-db.lua
spec/01-unit/16-runloop_handler_spec.lua
spec/fixtures/mocker.lua

The translation function for plugins:select_by_cache_key needs to poll
schema_state to decide when to stop using the "migrating" version of the
operation.
Kong checks the schema state once on startup. This commit adds a new
operation, `DB:last_schema_state` to retrieve the last value obtained
(`DB:schema_state` remains the same, re-querying the live database). The
`plugins:select_by_cache_key` translation function first checks
`last_schema_state` before performing the more expensive operation using
`schema_state`.
In the usual scenario where Kong is properly migrated before startup, the use
of `last_schema_state` will be sufficient for disabling the translation
function.
See #4164.

perf(db) reuse first call of schema_state in translation function

---

kong/cmd/migrations.lua
kong/cmd/start.lua
kong/db/dao/plugins.lua
kong/db/schema/init.lua
kong/db/schema/metaschema.lua
kong/globalpatches.lua
kong/pdk/init.lua
spec/01-unit/01-db/01-schema/02-metaschema_spec.lua
spec/01-unit/01-db/07-dao/01-plugins_spec.lua
spec/fixtures/custom_plugins/kong/plugins/dummy/schema.lua
spec/fixtures/custom_plugins/kong/plugins/invalid-schema/handler.lua
spec/fixtures/custom_plugins/kong/plugins/invalid-schema/schema.lua
spec/fixtures/custom_plugins/kong/plugins/rewriter/schema.lua
spec/helpers.lua
t/01-pdk/08-response/12-get_source.t

Introduces a "MetaSubSchema" for validating subschemas.
For Kong 1.0.x, this will only raise a warning log and not prevent plugins accepted by Kong 1.0.0 from loading.
To add the warning log, I also needed this:
The `kong` global, which offers the PDK APIs such as `kong.log`, was available from some parts of the Kong core and not from others. Because of this, we would often end up recoursing to `ngx` APIs instead of the improved `kong` ones.
This refactor loads the `kong` global for two environments where it wasn't being loaded, namely the test files and the `bin/kong` CLI.
Because the Kong core initializes a PDK instance and that loaded `resty.core` (which patches `ngx` fields) and `kong.globalpatches` also patches `ngx` fields for the CLI and tests, it was necessary to move the loading …

feat(schema) verify the validity of plugin schemas

---

kong/runloop/mesh.lua

The `http2` did not work with Kong `1.0.0`, and it was also reported here:
https://discuss.konghq.com/t/kong-http2-support/2600/3

fix(core) http2 support

---

kong/api/endpoints.lua
kong/api/routes/certificates.lua
kong/api/routes/consumers.lua
kong/api/routes/plugins.lua
kong/api/routes/upstreams.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua
spec/02-integration/04-admin_api/10-services_routes_spec.lua
spec/02-integration/05-proxy/10-balancer_spec.lua

This PR includes two bugfixes:
* invalid handling of targets, reported in #4132 
* some null values were not being returned as `null` by the Admin API
As part of the fix, a new `method` argument was added to methods of the `kong.api.endpoints` module, allowing a refactor of several endpoint handlers.
The commits of this PR were extracted from #4189.
Fixes #4132.

fix(api) fix handling of invalid targets, better handling of nulls

---

kong/db/strategies/cassandra/connector.lua
kong/init.lua

A fix for #4212 - more details to come.
EDIT: adding details below
In the init phase, lua-cassandra fallbacks to LuaSocket (since cosockets
are not supported). When we ask Kong to connect to the C* peers over
TLS, we use LuaSec. LuaSec wraps the LuaSocket TCP object (which itself
wraps the kernel socket).
LuaSocket normally returns `1` when calling `sock:close()`, but when
wrapped by LuaSec, the latter dismisses that return value, and thus,
`sslsock:close()` does _not_ return anything.
We could work around this limitation by providing an additional fix to
the pgmoon and lua-cassandra LuaSocket metatable wrappers, but this
commit presents a faster fix for the sake of efficiency, in the spirit
of the 1.0.2 release.
Note also how we changed the return value of `db_conn:close()` to `true` …

fix(db) ensure boot when using C* with client-to-node TLS

---

kong-1.0.1-0.rockspec

Changes:
* Returning a negative ttl value from the L3 callback will now make the
fetched data bypass the cache (it will still be returned by get()). This
is useful when some fetched data indicates that it is not cacheable.
* When get() returns a value from L2 (shm) during its last millisecond
of freshness, we do not erroneously cache the value in L1 (LRU)
indefinitely anymore.
* When get() returns a previously resurrected value from L2 (shm), we
now correctly set the hit_lvl return value to 4, instead of 2.
Full Changelog:
https://github.com/thibaultcha/lua-resty-mlcache/blob/master/CHANGELOG.md

chore(deps) bump lua-resty-mlcache to 2.3.0

---

kong/runloop/handler.lua

Originally done here:
https://github.com/Kong/kong/commit/40a073ea57155c5e99e717724dae86dbc0f02508#diff-1f0f137350308286de76ec59740c8eda
Bug introduced here (the next commit after ^):
https://github.com/Kong/kong/commit/ba3f4e46d122f1e134d6bff4024e9a9af8f1baeb#diff-1f0f137350308286de76ec59740c8eda
Yes, this is quite severe bug.

fix(core) pass the context table to mesh.rewrite

---

kong.conf.default

The `ssl` option no longer exists. It was added back to `kong.conf.default` in 4fa780a2, but it should be removed from both `kong.conf.default` and the website documentation.
This was detected because a `grep` performed by kong-upgrade-tests misbehaved due to this paragraph referencing `proxy_listen_ssl`.

docs(conf) remove old option that was incorrectly ressurected

---

kong/db/init.lua
kong/db/strategies/cassandra/connector.lua
kong/db/strategies/connector.lua

When bootstrapping, both `up` and `teardown` phases of each migration
execute subsequently. If the `teardown` step executed DML statements,
such statements can span all peers (due to replication factors). If the
replica peers have not yet reached consensus for their schema, they will
provoke errors and make the bootstrapping fail.
This change ensures that we wait for schema consensus when:
* before running `teardown` if `up` was just ran
* after running `teardown` if `up` was _not_ just ran (see comment as
for why)
* after running all migrations that were to be run, if executing
`run_up` only
From another perspective:
* `run_up == true`: wait for consensus at the very end (after executing
all up steps)
* `run_teardown == true`: wait for consensus after each teardown step
* `run_up == true …

fix(db) ensure we reach schema consensus while bootstrapping

---

kong/runloop/handler.lua
spec/02-integration/05-proxy/02-router_spec.lua

If Routes have `regex_priority` properties mixed between numbers and nil
(e.g. one Route was created with a default `regex_priority`, the other
was created with a purposefully NULL `regex_priority`, the comparison in
the router rebuild sorting of Routes would error out, because we are
comparing one Route's `nil` value against another Route's `number`.
Fix #4254

fix(router) ensure rebuilds when Routes have 'regex_priority = nil'

---

kong/db/migrations/core/003_100_to_110.lua

Drops legacy `upsert_ttl` function (not used anymore)

chore(db) drop un-used `upsert_ttl` postgres function

---

kong/plugins/request-transformer/access.lua
spec/03-plugins/14-request-transformer/02-access_spec.lua

Source of the problem: the plugin was getting the full set of headers from `kong.request.get_headers`, which includes the request Host value, and was setting it (after transformations) to `kong.service.request.get_headers`. Effectively, this performed the equivalent of the Route attribute's `preserve_host = true` behavior all the time.
This commit restores the input value of the `Host` header from the service request to the table prior to the transformations. It also removes special-case handling of the `Host` header that was present in the plugin, which is now handled by the PDK itself.
A change in this behavior as opposed to 0.14 is that now the
`request-transformer` plugin _is_ able to modify the value of `Host`:
* if `preserve_host` is false, you can modify it using `add`;
* if …

fix(request-transformer) handle Host header correctly

---

kong/plugins/oauth2/access.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

When using a token issued by a plugin with `global_credentials = true`
against a plugin with `global_credentials = false`, the plugin would
crash due to some indexing of nil fields.
[kong] access.lua:49 [oauth2] failed to get from node cache: callback threw an error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:580:
attempt to index field 'service' (a nil value)
Fix #4232

fix(oauth2) prevent a crash when using a global token

---

kong/db/strategies/postgres/connector.lua

Makes `preread` phase work on tests shown in #4243. But this is a work-around, as it forces `LuaSockets` on `proxy`. On the other hand, this is the current, and wrong, behavior of `lua-cassandra` as well.
This was made for `1.0.3` as it is better to have working implementation (even with `luasockets`) than a broken implementation. If `starttls` can be corrected so that tests run correctly with tests added in #4243, this can be closed.
Workaround: #4243

fix(db) workaround starttls bug by reverting pg to luasockets on preread

---

kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

Previously, a schema such as this:
```
{ type = "array",
default = {},
elements = { type = "string" },
}
```
Would be encoded in json as a `{}` instead of as a `[]` (the Lua table given for the default value would be copied, and its metatable would remain)
A similar thing would happen with sets.
This change sets the metatable to `cjson.array_mt` and also adds tests for other possible values given to the default (i.e. `cjson.empty_array`).

fix(schema) fix errors when encoding default empty arrays

---

kong/templates/nginx.lua
kong/templates/nginx_kong_stream.lua
spec/01-unit/04-prefix_handler_spec.lua
spec/fixtures/custom_nginx.template
t/01-pdk/05-client/01-get_ip.t
t/01-pdk/05-client/02-get_forwarded_ip.t
t/01-pdk/05-client/03-get_port.t
t/01-pdk/05-client/04-get_forwarded_port.t

A stream module supports real ip when using `proxy_protocol` flag on stream `listen`. This enables the `trusted ips` to work with stream module.

feat(stream) add support for stream real ip configuration

---

kong-1.0.3-0.rockspec

Bumps `lua-resty-http` to `0.13` which adds authenticated proxy support to `request_uri`.

chore(deps) bump lua-resty-http to 0.13

---

kong/api/routes/plugins.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua

Prior to this patch, `PUT` requests to plugins under their associated
resources (e.g. `/services/{service}/plugins/{plugin}`) would
systematically return `404`, instead of creating the plugin if it did
not exist. This was because the `before` Lapis hook attempts to retrieve
the plugin in the database before modifying it. Those endpoints are
preserved for backwards-compatibility purposes (being too nested to be
auto-generated), so that workaround is fine.
This patch ensures that we skip this logic with `PUT` requests, plus
makes sure that we set the `self.args.post` arguments according to the
`self.params` arguments (path segments with foreign UUIDs).
Thanks @gszr for the report.

fix(admin) proper support for `PUT /{entities}/{entity}/plugins/{plugin}`

---

.travis.yml
Makefile

kong-build-tools includes a functional test for the Kong version that's in the header `Via: "kong/x.y.z`. https://github.com/Kong/kong-build-tools/blob/master/test/test_smoke.tavern.yaml#L82
To make this test pass when building a nightly build we `sed` the `meta.lua` file so the Kong version matches. This also has the benefit that nightly builds will return the date/time stamp when one runs `Kong version` instead of the last released kong version.

chore(ci) fix nightly builds

---

kong/db/strategies/cassandra/init.lua
kong/db/strategies/init.lua
kong/db/strategies/postgres/init.lua

The implementation of a core entity consists of up to three parts:
1. the schema of the entity (`kong.db.schema.entities.my_entity`)
2. a DB-agnostic DAO module implementing custom methods for that entity or overriding standard methods in a DB-agnostic manner (`kong.db.dao.my_entity`)
3. one or more DB-specific modules implementing the database backend
for custom methods, or overriding standard methods in a DB-specific manner (`kong.db.strategies.postgres.my_entity` and    `kong.db.strategies.cassandra.my_entity`)
Instead of using a hardcoded list of customized DB-specific override modules (item 3 above) with this commit we simply attempt to load the module for every entity, and use it if it is available.
This is the backwards-compatible solution to be merged to `master`. Once this is in, …

refactor(db) de-hardcode custom strategies list

---

kong/runloop/balancer.lua

Avoid a stacktrace when the database fails to obtain the list of upstreams (as
seen in an error log provided by @hutchic): instead report a CRIT-level
message and fallback to an empty list.
```
2019/02/12 17:38:18 [crit] 36#0: *7 [lua] balancer.lua:719: init(): failed loading initial list of upstreams: failed to get from node cache: callback threw an error: /usr/local/share/lua/5.1/kong/runloop/balancer.lua:476: attempt to index local 'up' (a
boolean value)
/usr/local/share/lua/5.1/kong/runloop/balancer.lua:476: in function </usr/local/share/lua/5.1/kong/runloop/balancer.lua:472>
/usr/local/share/lua/5.1/resty/mlcache.lua:766: in function 'get'
/usr/local/share/lua/5.1/kong/cache.lua:126: in function 'get' …
```

fix(balancer) avoid crash when failing to obtain list of upstreams

---

kong.conf.default
kong/db/strategies/cassandra/connector.lua
spec/02-integration/03-db/01-db_spec.lua

Resolve contact points before instantiating cluster.  The driver does
not support hostnames in the contact points list, but we accidentally
support this feature by relying on our globalpatches.lua override of
`tcpsock:connect()`, in which we perform DNS resolution. This could lead
to mismatches between the driver policies and the peers info stored in
the shm.
This scenario is described in details here:
thibaultcha/lua-cassandra@8b9fcd9
We do not rely on `kong.dns` since the `kong` global is not always fully
instantiated in all of our components yet (notably the tests and the
CLI).

 fix(db) resolve Cassandra contact points when provided as hostnames 

---

kong/db/dao/plugins.lua
spec/02-integration/03-db/03-plugins_spec.lua

Before this change, assigning a plugin to an empty service (with no routes) would result in an “no compatible routes found in service” error. That is considered a breaking change (for things like automatic setups) and has been altered now: when a plugin is assigned to a service, and the service has no routes, then there will be no error. The error will still be raised when the service has at least one route, but none of its routes are compatible.

hotfix(db) allow plugins on empty services

---

kong/plugins/jwt/jwt_parser.lua
spec/03-plugins/16-jwt/01-jwt_parser_spec.lua

When using JOSE  (Json Object Signature and Validation),  Kong incorrectly returns:
```json
{"message":"Bad token; invalid typ"}
``` 
After some investigation (see #4217), it appears that Kong explicitly rejects any `typ` not equal to JWT. This includes `typ` JOSE.
RFC [7519 section 5.1](https://tools.ietf.org/html/rfc7519#section-5.1) states:
> ...This [`typ`] parameter is ignored by JWT implementations; any processing of this parameter is
performed by the JWT application....
Given the above statement, it appears that Kong should ignore the `typ` header. This PR does that. 
Effectively, this change resolves the original `invalid typ` and is able to properly verify a JWT with `typ` JOSE.
* ...
Fix #4217

fix(jwt) fix typ handling

---

kong/plugins/basic-auth/access.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/access.lua
spec/03-plugins/09-key-auth/02-access_spec.lua
spec/03-plugins/09-key-auth/03-invalidations_spec.lua
spec/03-plugins/10-basic-auth/03-access_spec.lua
spec/03-plugins/10-basic-auth/04-invalidations_spec.lua
spec/03-plugins/16-jwt/03-access_spec.lua
spec/03-plugins/16-jwt/04-invalidations_spec.lua
spec/03-plugins/18-acl/03-invalidations_spec.lua
spec/03-plugins/19-hmac-auth/03-access_spec.lua
spec/03-plugins/19-hmac-auth/04-invalidations_spec.lua
spec/03-plugins/20-ldap-auth/01-access_spec.lua
spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua

Fix(basic-auth, ldap-auth, key-auth, jwt, hmac-auth) status code for unauthorized requests
* Fix status code from 403 to 401 for unauthorized requests for basic-auth plugin [#3713](https://github.com/Kong/kong/issues/3713)
* Fix status code from 403 to 401 for unauthorized requests for key-auth plugin
* Fix status code from 403 to 401 for unauthorized requests for ldap-auth plugin
* Fix status code from 403 to 401 for unauthorized requests for jwt plugin
* Fix status code from 403 to 401 for unauthorized requests for hmac-auth plugin
Fix #3713

fix(basic-auth, ldap-auth, key-auth, jwt, hmac-auth) status code for unauthorized requests

---

kong/api/endpoints.lua
kong/api/init.lua
kong/db/errors.lua
kong/db/strategies/off/init.lua
spec/02-integration/04-admin_api/14-off_spec.lua

Here are the "features" and tests for reporting errors with `off` database strategy.

feat(api) restrict data manipulation operations on 'off' db with errors

---

kong/db/dao/targets.lua
kong/db/schema/entities/targets.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

This fixes two problems:
1) Target cleanup was happening in the wrong order. This was not a problem for
the target being inserted (because cleanup happened before insertion), but it
would cause the other targets of the list to be corrupted in case they had a
target history themselves.
Since cleanup happened before insertion (meaning before a weight=0 entry was
inserted upon deletion), this meant that deleting targets never truly emptied
the table -- this meant that Cassandra could not delete upstreams, because the
cascade-delete annotation was missing from the entity schema. Merely adding
`on_delete = "cascade"` to `targets.upstream` would fix the problem in #4317
illustrated by the regression test added to
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua but would not
fix …

fix(db) fix target cleanup and cascade-delete for Targets

---

.travis.yml

seems I missed an ubuntu. A successful build of a bionic release using kong-build-tools [here](https://travis-ci.com/Kong/kong-build-tools/jobs/177874840)

chore(ci) release daily builds for bionic

---

kong/init.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua

This fixes the initial loading of the declarative config file based on the `declarative_config` configuration variable.
Includes a regression test (triggering the issue running that test on `next` may be flaky (though it did trigger consistently On My Machine™️, but running the test on the fixed version should be stable — best I could get for an intermittent test).

hotfix(dbless) fix initial load of declarative config

---

kong/api/arguments.lua
spec/01-unit/01-db/03-arguments_spec.lua

Corrects the type inference of values of map types when using form-encoded inputs. In particular, this was affecting the input of configuration for response-ratelimiting.
Includes a fix to the relevant unit test.
Fixes #4344.

fix(api) fix type inference of map values using form-encoded

---

.travis.yml

We don't need to perform a local compilation of OpenResty etc in the Travis environment when making daily builds because those already happen inside `kong-build-tools`. This should shave a few minutes off from each of the daily build runs.

chore(ci) do not run setup_env.sh during daily builds deploy

---

kong/plugins/ldap-auth/asn1.lua
kong/plugins/ldap-auth/ldap.lua

Lua 5.3 comes with `string.pack` and `string.unpack` so there are libraries that try to see if they are in place, like @daurnimator's `lua-http` library. The `lua_pack` modifies standard `string`
library, and adds `pack` and `unpack` functions to it which are incompatible with Lua 5.3 versions of them. `lua-http` on the other hand thinks it is getting the 5.3 ones, and then we see things
crashing.
Another PR with removal of `lua_pack` dependency will follow.
This is based on `next` so that I can rebase #4286 on top of `next` when this is merged.

fix(*) quick fix lua_pack as it modifies standard lua string library

---

kong/db/declarative/init.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/10-balancer_spec.lua
spec/fixtures/admin_api.lua
spec/fixtures/blueprints.lua
spec/fixtures/custom_plugins/kong/plugins/fail-once-auth/handler.lua
spec/fixtures/custom_plugins/kong/plugins/fail-once-auth/schema.lua
spec/fixtures/dc_blueprints.lua
spec/helpers.lua

This PR contains a couple of fixes and a major update to the upstreams and healthcehcks test suite, enabling it to run on `database=off` mode as well.
The main fix issues `"crud"` worker-events when Upstreams and Targets are created via the declarative config endpoint, so that these events propagate and eventually generate and populate the internal balancer objects and healthcheckers. This fixes the behavior of upstreams and healthchecks using db-less mode.
The changes made to the `10-balancer_spec.lua` test suite to make it run on both database and db-less mode are described in more detail in its own commit message.

hotfix(dbless) fixes and tests for healthchecks using declarative config

---

kong/db/schema/entities/routes.lua
kong/router.lua
kong/runloop/handler.lua
spec/01-unit/01-db/01-schema/06-routes_spec.lua
spec/01-unit/08-router_spec.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua
spec/02-integration/03-db/07-tags_spec.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua
spec/02-integration/05-proxy/18-serviceless_proxying_spec.lua
spec/03-plugins/22-aws-lambda/01-access_spec.lua
spec/03-plugins/26-request-termination/02-access_spec.lua

This is first implementation of so called `allow_by_default` routing. E.g. routes that act as a transparent routes. Which means you don't need to create service entity, but instead you can use HTTP proxying or `iptables` transparent proxying rules.

feat(core) make service on routes optional (transparent proxying)

---

kong-1.0.3-0.rockspec
kong/init.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
spec/01-unit/09-balancer_spec.lua
spec/02-integration/05-proxy/10-balancer_spec.lua
spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua

Bumps the DNS client and loadbalancer lib to 3.0.2
- Fix (DNS lib + Kong): a potential issue with the healthchecks not being able to set the status of a peer. This happens when there are multiple levels of dns, eg: SRV -> A -> ip-address.
- Fix (DNS lib): the (long time) outstanding fix for the error `attempt to index local 'address' (a nil value)`

chore(deps) update dns lib to 3.0.2

---

kong/db/strategies/cassandra/init.lua

A map does not have `elements`, but `keys` and `values`.
This unfortunately does not come with a test, as no core entity has a
map field as of today.

fix(db) properly serialize maps in C* strategy

---

.travis.yml
Makefile

Utilize the git://kong-build-tools repository to run the Kong functional test suite against any branch builds that are set to build via cron

chore(ci) add functional tests to Kong CI

---

kong-1.1.0rc2-0.rockspec
kong/meta.lua

* **Transparent proxying** - the `service` attribute on Routes is now optional; a Route without an assigned Service will proxy transparently (#4286)
* Resolve hostnames in Cassandra contact points (#4378)
* Fix health checks for Targets that need two-level DNS resolution (e.g. SRV → A → IP) (#4386)
* Fix serialization of map types in the Cassandra backend (#4368)
* Fix Admin API inferencing of map types using form-encoded (#4368)
* PDK version identifier was bumped to 1.1.0
* `kong.client.get_subsystem` was moved to `kong.nginx.get_subsystem` (#4358)
* fix the behavior of the `/tags` endpoint and `?tags=` query string from the Admin API when using `database=off` (#4380)
* fix initial load of the declarative config file (#4342)
* reloading the declarative config via `/config` refreshes the …

Release: 1.1.0rc2

---

.travis.yml

Our test matrix has been showing a duplicate entry for `KONG_TEST_DATABASE=postgres TEST_SUITE=integration` at the end of
the list.
I contacted the support staff at Travis CI and this was the way [they suggested](https://github.com/ssabrii/kong/blob/master/.travis.yml) to fix the problem.

chore(ci) prevent spurious test from showing up in matrix

---

Makefile

the inclusion of `.requirements` doesn't let us specify package names when building releases. Example of this is https://bintray.com/beta/#/kong/kong-nightly/next?tab=overview where the package is always being named for what's in the `.requirements` file and not using the ENV override

chore(ci) kong next daily build naming fix

---

kong/api/routes/config.lua
kong/cmd/config.lua
kong/db/declarative/init.lua
spec/01-unit/11-reports_spec.lua
spec/02-integration/02-cmd/11-config_spec.lua
spec/02-integration/04-admin_api/11-reports_spec.lua

This PR reports certain usage of the new DB-less or declarative config feature.
* Add tests for hourly "ping" report when `database = off`
* Generate `dbless-reconfigure` event when `/config` API is used to reconfigure with tests
* Generate `config-db-import ` event when `kong config db_import` cmd is used to import config from `.yml` into database with tests
* Fix small styling issue in `/config` API endpoint

feat(reports) report anonymous usage data of dbless feature

---

kong/db/strategies/postgres/init.lua

A fix to Postgres strategy that corrects the check on foreign fields whether or not the foreign field is part of the primary key as well. This is not needed for core entities (so perhaps not that urgent), but custom entities may need it.

fix(db) is part of primary key was incorrectly checked on foreign fields

---

kong/db/dao/plugins.lua
kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua
spec/01-unit/01-db/01-schema/02-metaschema_spec.lua
spec/02-integration/03-db/03-plugins_spec.lua
spec/fixtures/custom_plugins/kong/plugins/legacy-plugin-bad/handler.lua
spec/fixtures/custom_plugins/kong/plugins/legacy-plugin-bad/schema.lua
spec/fixtures/custom_plugins/kong/plugins/legacy-plugin-good/handler.lua
spec/fixtures/custom_plugins/kong/plugins/legacy-plugin-good/schema.lua

When auto-converting a legacy schema from a plugin, we need to determine if something of type "table" is an array, map, set or record. When we failed to pin this down, we were producing an incomplete schema, which led to runtime crashes.
if we have a table type that wasn't further specified in any way, we now make it a map from strings to strings, which is the most generic type (apart from abusing "any", since we don't want dynamically-typed plugin schemas).
To prevent similar problems from happening again, this PR also adds a defensive measure: it runs the MetaSchema validator on the schemas generated by the auto-converter as well. This validation should never fail, because the best-effort legacy schema converter should either produce a valid schema or report failure in advance. However, …

fix(schema) adjustments for legacy schema auto-converter

---

kong/cmd/config.lua

Do not output the string `nil` upon a successful parse.
Thanks @hbagdi for reporting.

hotfix(cmd) fix output of `kong config parse`.

---

Makefile

The current 'make dev' reinstalls Kong and the dev dependencies.
The new 'make dev-only' only installs dev dependencies without
touching the Kong installation itself.
This enables plugin testing without Kong source code.

chore(make) adds a new Make target to install dev tools only

---

kong/db/schema/entities/services.lua
spec/01-unit/01-db/01-schema/05-services_spec.lua

Timeouts in Service objects can be currently set to 0, but the proxy
calls then return 500s as OpenResty API doesn't allow for zero or
negative timeouts:
https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#set_timeouts
`typedefs.timeout` is not currently used anywhere except for defining
timeouts in the `Service` entity.
A `0` value for a timeout is a valid, and for such a use-case, a user
can define their own type value using the Schema library.

fix(schema) change timeout to be at least 1ms

---

.ci/setup_env.sh

This should avoid having `next` or PRs based upon it to use dependencies
built for `master`.
Hopefully this will address the issues we're currently having with the
`pdk` testsuite failing due to `set_real_ip` patch for the stream
module being present in the `next` build of OpenResty and absent
in `master`.
As suggested by @dndx, we identify a set of dependencies by hashing
`.travis.yml` and `.ci/setup_env.sh`, which combined should keep track of changes in base dependency version bumps and compilation flags.

chore(ci) do not reuse incompatible Travis caches

---

kong/api/routes/consumers.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua

This issue was reported by @JoarSvensson on issue #4402.
Fix #4402

fix(api) consumers endpoint filtering by custom id

---

.travis.yml

This PR includes a name change to our bintray repository which I'll try to capture 
kong-community-edition-deb kong-deb
kong-community-edition-rpm becomes kong-rpm
kong-community-edition-alpine-tar becomes kong-alpine-tar
Todo:
After merging:
The following screenshots demo successful releases of a mock 1.0.4

chore(ci) have travis-ci handle building / releasing Kong

---

kong.conf.default

Add missing documentation in `kong.conf.default` for features introduced in Kong 1.1.

docs(conf) document database=off and declarative_config

---

kong/error_handlers.lua

This ternary operator is unnecessary and can be removed.

fix(error-handler) removing the ternary operator used by message as redundant

---

kong-1.1.1-0.rockspec
kong/cache.lua

2 commits extracted from #4457 
---
This release of mlcache introduces the new `get_bulk()` API needed by
the wildcard SNI feature.
Changelog for 2.4.0:
https://github.com/thibaultcha/lua-resty-mlcache/blob/master/CHANGELOG.md#2.4.0

chore(deps) bump mlcache to 2.4.0 and expose 'get_bulk()'

---

kong/plugins/basic-auth/basicauth_credentials.lua
spec/03-plugins/10-basic-auth/02-api_spec.lua

This PR fixes an issue when patching basic auth credentials: `PATCH consumers/:consumers/basic-auth/:basicauth_credentials`. 
Currently, if `password` is not sent in the PATCH request, nil is hashed and saved as the password. The new behavior is to ignore nil password, preserving the current password if one is not sent. 
* `_BasicauthCredentials:update` only calls `hash_password` if password is not nil
* `_BasicauthCredentials:update_by_username` only calls `hash_password` if password is not nil
* Adds tests

fix(basic-auth) ignore password if nil on basic auth credential patch

---

kong/init.lua

Maybe later it should, but in current form it gives critical errors
to error log:
```
KONG_DECLARATIVE_CONFIG=kong.yml ./bin/kong restart --vv
```
writes to error log:
```
[crit] 7691#0: *1 [lua] init.lua:533: init_worker():
error loading declarative config file:
init.lua:266: bad argument #1 to 'pairs' (table expected, got nil),
context: init_worker_by_lua*
```

fix(core) declarative config should not be parsed with db-mode on start

---

kong/db/schema/metaschema.lua

This change ensures that `one_of` will check to see if an element is of any type, rather than just a string.

feat(schema) make one_of support multiple types

---

kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

This PR enables nested record field types to merge as expected on `PATCH`. Previously any unset values within the incoming record object would reset previously set values to either a default value or null. This change allows the previously set values to be respected during a partial update by conditionally setting `read_before_write` to `true`.

fix(schema) address issue where field type "record" nested values reset on update

---

README.md

I guess it is good to have a `follow on twitter` badge along with the ones currently present within `Readme.md` :thinking: 
This is how it looks like:-
[![Twitter](https://img.shields.io/twitter/follow/thekonginc.svg?style=social&label=Follow)](https://twitter.com/intent/follow?screen_name=thekonginc)

doc(badge) Add follow on twitter badge

---

kong/cmd/utils/prefix_handler.lua
spec/02-integration/05-proxy/10-balancer_spec.lua
spec/03-plugins/22-aws-lambda/01-access_spec.lua
spec/fixtures/custom_nginx.template
spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua
spec/helpers.lua

The mocks are injected into the nginx conf and rendered with the
Kong configuration. The Lambda plugin has been converted to this
format.
Please check commit scope/type, as I wasn't sure

chore(tests) enable plugin specific nginx server/stream mocks

---

kong/runloop/mesh.lua

When using declarative config and a `cluster_ca` is not declared,
mesh mode cannot be used. This means that `mesh_alpn` is not declared.
When performing a proxy call to the SSL port with wget like this:
```
wget https://localhost:8443/ --no-check-certificate
```
we get to a state where `getssl()` returns a value but `ssl:getAlpnSelected()`
returns `nil`. We need to avoid this check when `mesh_alpn` is not set.
(Interestingly, this happens with `wget` but does not happen with `curl -k`.)
Fixes #4497.

fix(declarative) do not mis-detect mesh mode

---

kong-1.1.1-0.rockspec

This is a backwards-compatible patch-release bump to fix a Kong issue.
See https://github.com/Kong/lua-resty-healthcheck#061-04-apr-2019
Fixes #4453.

chore(deps) bump lua-resty-healthcheck to 0.6.1

---

kong/db/schema/entity.lua
spec/helpers.lua

- Override `Entity.new_subschema` in schema instance returned by `Entity.new`
- Use `Entity.new` to instantiate plugins schemas in spec helpers
These changes allow the helper `validate_plugin_config_schema` to be consistent with how plugins schemas are loaded in the plugins DAO. In particular, this fixes an issue where default values for nested records are not populated in the entity validated and returned by `validate_plugin_config_schema`.

tests(*) plugin schema helper

---

kong-1.1.1-0.rockspec
kong/plugins/rate-limiting/migrations/003_10_to_112.lua
kong/plugins/rate-limiting/migrations/init.lua

Add missing index on rate-limiting plugin metrics on route + service.
*  added index ratelimiting_metrics on (service_id, route_id, period_date, period).
Fix #4374

added index on ratelimiting_metrics. closes #4374

---

kong/db/schema/init.lua
kong/db/schema/metaschema.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

Add new schema validators:
- `mutually_required`: all declared fields must be set if any of them is
set
- `mutually_exclusive_sets`: if either of the fields declared is set, none of
the remaining can be set
- ~~Naming: I'm still not 100% happy with the names; in particular, I think
argument names in the `mutually_exclusive` validator could be better.
Suggestions very welcome~~

feat(db) add mutually_required and mutually_exclusive_sets

---

kong/db/strategies/postgres/connector.lua

This PR tries to make Postgres schema bootstrapping and resetting more robust in scenarios where the username used to connect Postgres database has limited permissions (e.g. unable to drop or create schemes), see #4483.
It also fixes issue with (Azure Postgres) username indirection, see: #4502.
Fix #4483, #4502

feat(db) pg username indirection (e.g. azure) and limited permissions support

---

kong/db/migrations/core/000_base.lua
kong/db/migrations/core/001_14_to_15.lua
kong/db/migrations/core/002_15_to_1.lua
kong/db/migrations/core/003_100_to_110.lua
kong/plugins/acl/migrations/000_base_acl.lua
kong/plugins/acl/migrations/001_14_to_15.lua
kong/plugins/basic-auth/migrations/000_base_basic_auth.lua
kong/plugins/basic-auth/migrations/001_14_to_15.lua
kong/plugins/hmac-auth/migrations/000_base_hmac_auth.lua
kong/plugins/hmac-auth/migrations/001_14_to_15.lua
kong/plugins/jwt/migrations/000_base_jwt.lua
kong/plugins/jwt/migrations/001_14_to_15.lua
kong/plugins/key-auth/migrations/000_base_key_auth.lua
kong/plugins/key-auth/migrations/001_14_to_15.lua
kong/plugins/oauth2/migrations/000_base_oauth2.lua
kong/plugins/oauth2/migrations/001_14_to_15.lua
kong/plugins/rate-limiting/migrations/001_14_to_15.lua
kong/plugins/rate-limiting/migrations/002_15_to_10.lua
kong/plugins/response-ratelimiting/migrations/001_14_to_15.lua
kong/plugins/response-ratelimiting/migrations/002_15_to_10.lua

Updates postgres migration to be more resilient to schema changes and make them (more) reentrant. This work started with #4506, but was moved to this separate PR.

refactor(migrations) make postgres migrations reentrant

---

kong/api/endpoints.lua
kong/api/init.lua
kong/db/dao/init.lua
kong/db/errors.lua
kong/db/schema/init.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua

This work was originally done by @hbagdi (thank you):
https://github.com/hbagdi/kong/commit/d627649ee3aad55d7a0c94a09e627f356ea3994e
This commit makes it possible to use names (`unique fields` or `endpoint key`) in `insert`/`update`/`upsert`/`update_by_*`/`upsert_by_*`
kong db calls and admin api calls, e.g.:
```
http :8001/routes paths=/ service.name=test -f
```
(previously you needed to use `service.id=<uuid>`)

feat(db) implement foreign entity unique / endpoint key field resolver

---

kong/conf_loader.lua
kong/init.lua
spec/01-unit/03-conf_loader_spec.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua

This is a complement to db28453.
When the `declarative_config` entry is set in `kong.conf` alongside `database=postgres` or `database=cassandra`, this caused the initialization of declarative config from DB-less mode to trigger incorrectly in DB mode, causing problems with worker initialization. This commit fixes the issue.
Includes a regression test that demonstrates the problem.
Fixes #4508. Thanks @pamiel for reporting!
Also, this PR includes two other minor fixes for things that came up while fixing this bug:
* when `admin_listener = ` (with no value) in `kong.conf` (I forgot about `off`), we were getting a crash inside Penlight, which translated to a cryptic error message to the user ("error in argument 1: got nil, expected string"). Now we get a proper usage message.
* fix check of …

fix(core) prevent declarative_config from causing problems in DB mode

---

kong/api/api_helpers.lua
kong/api/routes/kong.lua
kong/api/routes/plugins.lua
spec/02-integration/04-admin_api/02-kong_routes_spec.lua

Kong currently exposes schemas of plugin configurations at
`/plugins/schema/:plugin_name`.
This commit exposes schema of all core and custom entities in Kong at
`/schemas/:name`.

feat(api) expose schemas of db entities on the Admin API

---

kong/db/dao/plugins.lua
spec/02-integration/03-db/03-plugins_spec.lua
spec/fixtures/custom_plugins/kong/plugins/plugin-with-custom-dao/custom_dao.lua
spec/fixtures/custom_plugins/kong/plugins/plugin-with-custom-dao/daos.lua
spec/fixtures/custom_plugins/kong/plugins/plugin-with-custom-dao/handler.lua
spec/fixtures/custom_plugins/kong/plugins/plugin-with-custom-dao/schema.lua
spec/fixtures/custom_plugins/kong/plugins/plugin-with-custom-dao/strategies/cassandra/custom_dao.lua
spec/fixtures/custom_plugins/kong/plugins/plugin-with-custom-dao/strategies/postgres/custom_dao.lua

This commit introduces new functionality into the plugin_loader module to support attempting to load a strategy for custom plugin DAO implementations. This would allow plugins to define a strategy at a path like
`kong/plugins/<plugin>/db/strategies/<strategy>/<entity>.lua`
This is essentially a copypasta of the custom strategy loader found in kong.db.strategies.
* support loading custom DAO strategies for plugins

feat(dao) support loading custom DAO strategies for plugins

---

kong/plugins/request-transformer/schema.lua
spec/03-plugins/14-request-transformer/01-schema_spec.lua

Header-related configurations of request transformer are not validated. Invalid header value configurations would be accepted but the invalid headers are not properly transformed previously. This commit adds validations for header fields.
* Add request-trasnformer plugin validation
* Add related tests

feat(request-transformer) validate header values in plugin configuration

---

kong/api/routes/config.lua
kong/db/declarative/init.lua

Do not send Upstream CRUD events on `load_into_cache` when it is called during first initialization. Create a separate function `load_into_cache_with_events` which is used when refreshing the config in `/config`.
Fixes #4507.
There is no regression test due to the flaky nature of the problem.

fix(dbless) do not send Upstream CRUD events on first init

---

kong/plugins/request-transformer/access.lua
spec/03-plugins/14-request-transformer/02-access_spec.lua

ngx_http_lua_module treats all header names as lower case strings, so
when changing something from request they must always be compared this
way.
Issue reported in https://github.com/Kong/kong/issues/4504

fix(request-transformer) plugin is case insensitive for header names now

---

kong/runloop/handler.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/03-upstream_headers_spec.lua
spec/fixtures/custom_nginx.template

Removes the following request and response headers:
- `Proxy` (see: https://httpoxy.org/)
- `Proxy-Connection`
- `Proxy-Authenticate`
- `Proxy-Authorization`
- `TE`
- `Transfer-Encoding`
- `Trailer`
- `Upgrade`
Headers specified in the value of the Connection header are cleared as well.

feat(proxy) clear hop-by-hop headers

---

kong/router.lua
kong/runloop/handler.lua
spec/01-unit/08-router_spec.lua

Just a small style change on `router` code to get rid of `mocking` related parameters on public interfaces. I am fully ok, if there are objections at merging this.

style(router) remove passing of ngx and localize functions and magic tables

---

kong/globalpatches.lua

Regular tcp/udp connections would skip the additional debug info
available on dns lookup failure. Updated globalpatches to include
the additional infos.

chore(log) improve dns failure logs

---

kong/db/strategies/cassandra/connector.lua
kong/globalpatches.lua
kong/runloop/balancer.lua

Additions:
- Log the `try_list` JSON string upon DNS resolution failures in the
Cassandra connector.
Changes for consistency:
- All DNS resolution failures contain the string "DNS resolution
failed" which is something end-users can understand better than
implementation details (e.g. "`toip()` called failed"). It can also be
searched for much more easily.
- The Cassandra connector log is prefixed with the strategy name,
`[cassandra]`, as all other CLI error messages already are.
- Cosockets DNS resolution failures are prefixed with `[cosocket]`,
which is much easier to search for, and more obvious for seasoned users
or maintainers. Since the "DNS resolution failed" string is also in
the message, we consider this message insightful enough for end-users.
- The balancer's logs don't use a …

feat(*) better consistency of DNS resolution error messages

---

.travis.yml

packages build for Amazon Linux 2 are not backwards compatible with Amazon Linux 1 and our cloudformation is currently pinned to Amazon Linux 1

fix(aws) we want to build with and for Amazon Linux 1

---

kong/api/endpoints.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

Previously, a disabled endpoint like `GET /targets` would return:
```
{"message":"table: 0x487eb080table: 0x4198c950table: 0x40ea27e0"}
```
This has been updated to correctly return the body now and a regression
test has been added.

fix(api) correctly return "not found" on disabled endpoints

---

kong-1.1.2-0.rockspec

Cherry-picked from `next` to reduce GC pressure during `/config` events triggering a `cache:purge()` event.
---
This release of mlcache introduces the new `get_bulk()` API needed by
the wildcard SNI feature.
Changelog for 2.4.0:
https://github.com/thibaultcha/lua-resty-mlcache/blob/master/CHANGELOG.md#2.4.0

chore(deps) bump lua-resty-mlcache to 2.4.0

---

kong/api/routes/config.lua
spec/02-integration/04-admin_api/15-off_spec.lua

Catch the case where `/config` is POSTed with no input, and produce
a generic error message instead of dumping an internal lyaml error like
```
{
"error": "failed parsing declarative configuration file config.yml: .../.luaver/luarocks/3.0.4_5.1/share/lua/5.1/lyaml/init.lua:445: bad argument #1 to 'parser' (must provide a string argument)"
}
```
Thanks @bungle for the report!

fix(api) correct error message when /config is given no input

---

kong/db/schema/entities/routes.lua
kong/db/schema/typedefs.lua
kong/plugins/ip-restriction/schema.lua
spec/01-unit/01-db/01-schema/06-routes_spec.lua
spec/03-plugins/17-ip-restriction/01-schema_spec.lua

The validator used ipv4 only `resty.iputils` which caused errors in validating ipv4 addresses in stream routes with destinations and sources. The router itself used `resty.mediador.proxy` which does
have ipv6 support.
The `ip-restriction` plugin is still left to use `resty.iputils` partly because it is very efficient implementation (faster than mediador). We may need in future look for nice optimized way to verify ips and cidr blocks, and match cidr blocks. We also have some tools in `kong.tools.utils` which are a bit restrictive in their implementation.

feat(core) add support for stream ipv6 routes

---

kong-1.1.2-0.rockspec
kong.conf.default
kong/cache.lua
kong/cache_warmup.lua
kong/conf_loader.lua
kong/db/dao/plugins.lua
kong/init.lua
kong/templates/kong_defaults.lua
spec/01-unit/01-db/08-cache_warmup_spec.lua

Introduces a new configuration property, `db_cache_warmup_entities`, which allows the user to specify which entities should be warmed up at initialization. 
From the documentation at `kong.conf.default`:
```
#db_cache_warmup_entities = services, plugins
#
#
```
The default value is `services, plugins`: the `routes` entity does not need to be warmed up because it is cached via the in-memory router object; specifying this in this configuration property is a no-op.
Includes unit tests for the `kong.cache_warmup` module.
This is a port of work produced by @bungle and kikito in #4408, #4462, #4468, #4488. Thanks @thibaultcha for the preliminary feedback and suggestions on the property name and specifics of the behavior.
(Note that, at @thibaultcha's suggestion, this PR replaces the "cache …

feat(cache) introduce cache warmup for entities and DNS

---

kong-1.1.2-0.rockspec

Bump `pgmoon` dependency to `1.10.0`.
* fix fail to run query if it has null byte
* use luaossl for md5 before lua crypto, add better error

chore(deps) bump pgmoon to 1.10.0

---

kong-1.1.2-0.rockspec

Bump `luasec` dependency to `0.8`.
* Add support to ALPN
* Add support to TLS 1.3
* Add support to multiple certificates
* Add timeout to https module (https.TIMEOUT)
* Drop support to SSL 3.0
* Drop support to TLS 1.0 from https module
* Fix invalid reference to Lua state
* Fix memory leak when get certficate extensions

chore(deps) bump luasec to 0.8

---

kong/plugins/oauth2/migrations/001_14_to_15.lua

Fixes an issue reported at #4572, where migrations could set a 0 ttl for `oauth2_tokens` that have never expiring `0` tokens, leading to deletion of such tokens.
Fix #4572

fix(migrations) oauth2 tokens ttl was incorrectly migrated, fix #4572

---

kong-1.1.2-0.rockspec

Changes:
- Improve host still considered down error logs to include the error
causing each node to be considered as "DOWN", as well as the duration
for which it will still be considered "DOWN".
E.g.:
all hosts tried for query failed. 127.0.0.1: host still considered down.
127.0.0.2: host still considered down
Becomes:
all hosts tried for query failed. 127.0.0.1: host still considered
down for 1s (last error: timeout). 127.0.0.2: host still considered
down for 1s (last error: timeout)
Full Changelog:
https://github.com/thibaultcha/lua-cassandra/blob/master/CHANGELOG.md#140

chore(deps) bump lua-cassandra to 1.4.0

---

kong/db/dao/plugins.lua
kong/plugins/acl/handler.lua
kong/plugins/aws-lambda/handler.lua
kong/plugins/basic-auth/handler.lua
kong/plugins/bot-detection/handler.lua
kong/plugins/correlation-id/handler.lua
kong/plugins/cors/handler.lua
kong/plugins/datadog/handler.lua
kong/plugins/file-log/handler.lua
kong/plugins/hmac-auth/handler.lua
kong/plugins/http-log/handler.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/handler.lua
kong/plugins/loggly/handler.lua
kong/plugins/oauth2/handler.lua
kong/plugins/rate-limiting/handler.lua
kong/plugins/request-size-limiting/handler.lua
kong/plugins/request-termination/handler.lua
kong/plugins/request-transformer/handler.lua
kong/plugins/response-ratelimiting/handler.lua
kong/plugins/response-transformer/handler.lua
kong/plugins/statsd/handler.lua
kong/plugins/syslog/handler.lua
kong/plugins/tcp-log/handler.lua
kong/plugins/udp-log/handler.lua
kong/runloop/handler.lua
spec/01-unit/01-db/07-dao/01-plugins_spec.lua
spec/03-plugins/15-response-transformer/02-body_transformer_spec.lua

Plugins handlers have always been inheriting from the `BasePlugin`
class, which is itself inheriting from the `Object` class provided by
`kong.vendor.classic`.
This design predates even the very first public release of Kong in 2015,
and was influenced by the OOP background of its original authors.
Today, the case can be made against this design:
- At best, it makes instances with `debug` log levels extremely noisy.
- At worst, it has a non-negligible performance impact due to the
constant metatable lookups of a plugin's handlers methods and
because of the non-JITable `ngx.log` calls sitting on hot code paths.
- All in all, its only purpose was to provide a `_name` attribute which
was only used by the `BasePlugin` parent class and redundant with the
`handler.name` property injected by the …

perf(*) plugins handlers do not have to inherit from BasePlugin anymore

---

kong/plugins/log-serializers/basic.lua
spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua

The following PR logs the TLS version used by the request into the `basic` serializer for every logging plugin.

feat(plugins) log request TLS version

---

.ci/run_tests.sh
spec/02-integration/04-admin_api/02-kong_routes_spec.lua

- Simplify the test file to setup Kong only once for each strategy to
speed up tests
- Add `off` strategy for this file. Kong Ingress Controller will start
using these endpoints once 1.2 in db-less mode. The tests will ensure
that we don't run regress in future.

tests(admin) run tests for routes in dbless mode

---

kong/init.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua
spec/02-integration/06-invalidations/03-plugins_iterator_invalidation_spec.lua

This PR contains 3 refactors:
* Merges plugins_plan and plugins_iterator into a single entity
* Replaces the `repeat ... until` fake loop inside plugins_iterator by `goto`s
* Removes unnecessary metatables in plugins iterator
These refactors will be used as a base for async work

refactor(runloop) plugins_iterator refactors

---

kong/api/routes/config.lua
kong/cache.lua
kong/concurrency.lua
kong/db/declarative/init.lua
kong/global.lua
kong/init.lua
kong/templates/nginx_kong.lua
kong/templates/nginx_kong_stream.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/fixtures/custom_nginx.template

This PR allows performing DB-less updates atomically and with cache eviction control.
This is done by adding support for "double-buffering" in `kong.cache`: the cache object is able to maintain two lower-level mlcache instances internally, one being the "active page" and another being the "shadow page", writing to the shadow page, and flip between them in one go.
* we enable two cache pages when using DB-less mode
* we load the new configuration into the shadow page, and only if the entire declarative config is loaded successfully the cache pages are flipped.
* when the cache is not large enough to hold a declarative config input, the `/config` endpoint fails with HTTP 413 Request Too Large, and the previous DB-less configuration is retained
* the PR includes tests that demonstrate the …

feat(dbless) enable atomic update with eviction control

---

kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua

This fixes a hole left in 27dc712
causing a plugin iterator state to not have a `version` field, thus
forcing the plugins iterator to be rebuilt for every request.
This regression cause a single worker to experience performance drops
of over **80%** in terms of tps.
A similar regression was introduced by
06b760e in which the `version` field of
the `plugins` state was removed, forcing the plugins map to be rebuilt
for each request.
Alas, it seems like no unit test exists as of today for the current
plugins_iterator module ensuring that this property is properly set.

hotfix(plugins-iterator) fix a recent performance regression

---

kong/db/migrations/core/001_14_to_15.lua
kong/db/strategies/cassandra/connector.lua
kong/plugins/oauth2/migrations/001_14_to_15.lua
kong/plugins/oauth2/migrations/002_15_to_10.lua

This PR contains two fixes that together fix the issue: #4610.
1. It makes cassandra teardown migrations reentrant
2. It makes cassandra up migrations to ignore undefined column errors
Fix #4610

fix(migrations) make cassandra migrations reentrant and ignore undefined columns errors

---

.travis.yml

Resulting package name on bintray: `kong-master-2019-05-15.trusty.all.deb` where `master` is the branch the travis-ci cron ran against

chore(nightly) adjust nightly package naming

---

kong/api/routes/config.lua
kong/cmd/config.lua
kong/db/declarative/init.lua
kong/db/errors.lua
kong/init.lua
kong/runloop/handler.lua
spec/02-integration/02-cmd/03-reload_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/02-integration/05-proxy/02-router_spec.lua
spec/helpers.lua

Instead of opening 2 PRs (one of which would be a single hotfix commit) which would require a rebase and conflict-fix once merged, I'm pushing these combined for review. If desired, I can open `hotfix/cache-flip` as a separate PR. Each commit has its own description and can be reviewed separately (they do not undo work from previous commits).
https://github.com/Kong/kong/commit/2767d9bae41dc2c6451fd16a5e3ef72348c603b8
Thanks @bungle for the report!
This hotfix fixes two problems at once, both related to incorrect behavior flipping cache pages:
* we now propagate worker events so that all workers flip their cache pages and point to the currently-filled shm
* we avoid flipping pages at startup, to prevent dependencies with worker-event propagation order at initialization
Two regression …

hotfix(declarative) fix cache flip + feat(declarative) /cache?check_hash=1

---

kong/cmd/config.lua
kong/cmd/init.lua
kong/cmd/migrations.lua
kong/cmd/prepare.lua
kong/cmd/utils/migrations.lua
kong/db/migrations/core/000_base.lua
kong/db/strategies/postgres/connector.lua

Fixes `kong migrations up|finish -f` (see the `-f`) to not run executed, when there are no executed migrations.
There is also some assorted style fixes related to `kong` cli and `migrations`.

fix(migrations) check if there are executed migrations when using -f

---

kong-1.1.2-0.rockspec
kong/runloop/balancer.lua
spec/02-integration/05-proxy/10-balancer_spec.lua
spec/helpers.lua

Instead of disabling active healthchecks in the stream module altogether (which was done to avoid duplicate active healthchecks), what we need to do is to run the "tcp" type healthchecks in the stream module, and the other ones ("http", "https") in the http module.
For active healthchecks on stream to work, we need to bump lua-resty-healthcheck. 
This PR also adds a test for active healthchecks using stream, which also serves like a regression test for Kong/lua-resty-healthcheck#19

fix(healthchecks) fix active healthchecks in stream module

---

kong/plugins/ldap-auth/access.lua
spec/03-plugins/20-ldap-auth/01-access_spec.lua
spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua

This patch fixes STARTTLS functionality which hasn't been working because plugin starts TLS connection even for existing connections from the pool and then fails.
This patch separates connection pool for TLS connections because STARTTLS extention works on the same port as non-secure connections and two plugins configured with different settings can end up using secure connection or worse non-secure.
This patch adds additional check if TLS connection is being reused or not, that helps to prevent getting error messages from LDAP when plugins tries to STARTTLS connection even if it is already started.
This patch supplements tests with additional configuration for multiple LDAP connection strategies (non-secure, starttls).
* Add separate connection pool for secure connections
* Add additional …

fix(ldap-auth) reuse connection if starttls has been already started

---

kong/plugins/acl/handler.lua
kong/plugins/aws-lambda/handler.lua
kong/plugins/basic-auth/handler.lua
kong/plugins/bot-detection/handler.lua
kong/plugins/correlation-id/handler.lua
kong/plugins/cors/handler.lua
kong/plugins/datadog/handler.lua
kong/plugins/file-log/handler.lua
kong/plugins/hmac-auth/handler.lua
kong/plugins/http-log/handler.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/handler.lua
kong/plugins/loggly/handler.lua
kong/plugins/oauth2/handler.lua
kong/plugins/rate-limiting/handler.lua
kong/plugins/request-size-limiting/handler.lua
kong/plugins/request-termination/handler.lua
kong/plugins/request-transformer/handler.lua
kong/plugins/response-ratelimiting/handler.lua
kong/plugins/response-transformer/handler.lua
kong/plugins/statsd/handler.lua
kong/plugins/syslog/handler.lua
kong/plugins/tcp-log/handler.lua
kong/plugins/udp-log/handler.lua

Bump plugins versions to account for recent internal changes their
handlers (a29c355). Said changes removed plugins handlers dependency
on the base plugin class; there were changes in the plugins DAO
(`load_plugin_schemas`) to accommodate for the base class removal, making
it non-backwards compatible, warranting a major version bump in plugins
versions.

chore(plugins) bump version fields

---

kong/db/dao/init.lua

The `check_update` function used strategy function directly, that does not handle the default values correctly. This is usually not a problem but it becomes a problem when we add new columns to database, and then want to rely on `schema` defaults (the database could have a `null` as a value when migrated).
Solves one part of the issue reported here #4631

fix(dao) make read-before-write updates to handle default values correctly

---

kong/plugins/log-serializers/basic.lua
spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua

Adding the following entries in the `basic` log serializer:
* `request.tls.cipher`
* `request.tls.client_verify`

feat(log) adding more TLS information in basic serializer

---

kong.conf.default
kong/concurrency.lua
kong/conf_loader.lua
kong/init.lua
kong/runloop/handler.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/16-runloop_handler_spec.lua
spec/01-unit/17-concurrency_spec.lua
spec/02-integration/06-invalidations/03-plugins_iterator_invalidation_spec.lua

This is a continuation of #4627, but has been kept separate in order to make merging them separately easier.
This PR introduces the `router_consistency` config option which, if set to `eventual` completely decouples the building of the router and plugins iterator from the treatment of each request - Kong instead relies on the fact that rebuilds are triggered every second via a timer. The default remains `strict`, which matches the same level of router consistency of as that of past Kong releases.
This was extracted from #4488

perf(runloop) pure async rebuilds with config option

---

kong/api/routes/kong.lua
kong/globalpatches.lua
kong/pdk/node.lua
kong/runloop/handler.lua
kong/tools/utils.lua
spec/01-unit/05-utils_spec.lua
spec/02-integration/04-admin_api/02-kong_routes_spec.lua
t/01-pdk/12-node/00-phase_checks.t
t/01-pdk/12-node/02-get_memory_stats.t
t/Util.pm

- Move memory reporting into a standardized PDK function
- Some updates to the memory reporting result including better semantics for clients (Lua numbers instead of strings)
- Update Admin API `/status` endpoint to use aforementioned PDK function

feat(pdk) implemented 'kong.node.get_memory_stats()'

---

spec/01-unit/01-db/04-dao_spec.lua

The file was incorrectly named, so it was not picked up by Busted when traversing the folder. Also, fix the tests to match the latest changes in read-before-write for updates and auto-defaults.

tests(dao) enable and fix DAO unit tests

---

spec/helpers.lua

Instead of setting a parameter on the kong stop function, it can now
be specified as an env variable.
Variable is: KONG_TEST_DONT_CLEAN (KONG_DONT_CLEAN in tests)

feat(tests) allow to override log/prefix cleaning

---

kong/db/dao/plugins.lua

In a29c355, we removed the need for Plugins to inherit from the
BasePlugin class, but added backwards-compatibility ensuring existing
plugins can still inherit from it, and their constructor (`:new()`) is
called.
However, the Zipkin plugin deep-inherits from BasePlugin, via an
intermediate parent class (OpenTracing):
https://github.com/Kong/kong-plugin-zipkin/blob/master/kong/plugins/zipkin/handler.lua#L8
This patch ensures that such plugins have their `:new()` constructor
called as well, by hardening the "does it inherit from BasePlugin?"
check performed on their `handler` module. We do so by using
`classic.lua`'s `is()` method.

hotfix(plugins) execute ':new()' when Plugins deep-inherit from BasePlugin

---

kong/db/dao/init.lua
kong/db/schema/init.lua
kong/db/schema/metaschema.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

This PR re-introduces the `immutable` field validator to the DAO, allowing Kong to prevent certain fields from being updated. 
* **schema/init.lua** Introduced `validate_immutable_fields` schema method
* **schema/init.lua** Expanded checks in `process_auto_fields` to include searching each field for `immutable` attribute
* **dao/init.lua** Integrated new functionality into `check_update`
* **spec/01-unit/01-db/04-dao.lua** Added Unit Tests

feat(dao) re-introduce immutable field validator to DAO

---

kong/cmd/config.lua
kong/db/schema/others/declarative_config.lua
spec/02-integration/02-cmd/11-config_spec.lua

Whenever an entity was inserted via declarative config without an explicit `id` given in the YAML file, the loader auto-generated a random UUID. When using `kong config db_import`, this meant that each time one loaded a file, it would generate new entries, even though the implementation of `db_import` used `upsert`.
With this commit, when an `id` is not given but the "endpoint-key" unique identifier is given to an entity (e.g. `name` for `service`, `username` for `consumer`, etc.), this endpoint-key is used to generate a deterministic UUID v5.
This allows upserts to work as expected when using `kong config db_import`.
As discussed with @kikito, we cannot easily use `upsert_by_<unique>` here because the id's are auto-generated at a different step, so it is not easy to tell apart the id's …

fix(declarative) fix db_import upsert via deterministic v5 UUIDs

---

spec/02-integration/05-proxy/10-balancer_spec.lua
spec/fixtures/balancer_https_server.lua

Simplify the mock http server for balancer tests, and move it out-of-process. We used to run it in a thread, and to have two implementations, one based in lua-http that did both http and https, and a faster one for http-only tests. This drops the lua-http one and uses a single implementation based on luasocket and uses luasec to wrap the SSL socket when doing https tests. Since the https mode is now https-only, the https is adjusted to perform https requests exclusively (previously it used https for healthchecks only).
This was prompted by OpenSSL crashes I've been experiencing both locally and, since today, on Travis:
https://travis-ci.org/Kong/kong/jobs/539774062
```
[ RUN      ] spec/02-integration/05-proxy/10-balancer_spec.lua @ 1216: Ring-balancer #postgres #ipv4 #healthchecks …
```

tests(balancer) replace lua-http mock server with luasec

---

kong/db/dao/certificates.lua
kong/db/dao/snis.lua
kong/db/schema/entities/certificates.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua

So that we may use it to store certificates that does not have private key available (for example, CA certs)
Same issue as https://github.com/Kong/kong/pull/4599, but against `next` instead.
Docs: https://github.com/Kong/docs.konghq.com/pull/1248

feat(schema) make `key` field of `certificate` entity to be optional

---

kong.conf.default
kong/conf_loader.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/04-prefix_handler_spec.lua

On `http` you can now give new listen flags:
- `deferred`
- `bind`
- `reuseport`
On `stream` you can now give new listen flags:
- `bind`
- `reuseport`
Deferred is not supported on `stream` that's why it is not there.
Fix #4452

feat(conf) add `deferred`, `bind` and `reuseport` listen flags

---

kong/db/dao/plugins.lua
kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

What it does is that it removes fields that are not part of the `record` fields from values returned from strategies on `Schema:process_auto_fields` on `select` context (e.g. when read-before-write entities are used).
It allows removal of fields from records without needing to make a migration too.

feat(schema) support removing fields in records without migrations

---

kong-1.1.2-0.rockspec

These were bumped:
- `kong-plugin-azure-functions` to `~> 0.4`
- `kong-plugin-kubernetes-sidecar-injector` to `~> 0.2`
- `kong-plugin-serverless-functions` to `~> 0.3`
- `kong-prometheus-plugin` to `~> 0.4`
The `kong-plugin-zipkin` is still using `BasePlugin` and was not
bumped here as it uses multiple levels of inheritance.
There was no need to bump these plugins:
- `kong-proxy-cache-plugin`
- `kong-plugin-request-transformer`
Because they were moved to Kong as of `1.2.0`.

chore(deps) bump several plugins on removal of `BasePlugin` dependency

---

kong/init.lua
kong/runloop/plugins_iterator.lua

~Fixes issue with plugins_iterator not executing `init_worker` when starting Kong where the plugin was not already configured (in a database). This issue was introduced in `1.2.0rc1`.~
The PR also does some style changes and refactorings like:
1. localizing global variable access on plugins iterator
2. changed the order of `phase` and `ctx` arguments given to iterator on first call
3. loads the needed structures for iterator earlier (on iterator construction)
4. does not use `mock_ctx` anymore -> certificate passes ngx.ctx (which current version of OpenResty rewrite phase clears, but it still gives a table and future proofs that code path) and init_worker passes `nil` (as the ngx.ctx is not used for anything on init_worker with plugins iterator)
~5. finally it adds tests that check that …

refactor(runloop) change order of ctx and phase arguments, prepare plugins_iterator structures, localize globals on plugins_iterator

---

kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

This came up when trying to use `eq = false` in a `conditional` entity
checker. Includes simple a regression test.
Also adds some tests verifying the behavior of `ngx.null` as an attribute, for
completeness.

fix(schema) accepts 'false' as an attribute value

---

kong/runloop/handler.lua
spec/02-integration/05-proxy/09-websockets_spec.lua

Ensures that `Upgrade` header is not cleared with `websockets`.
Fix #4718

fix(proxy) do not clear upgrade header with websockets, fix #4718

---

kong.conf.default

Minor adjustment to the formatting, to match the Markdown format expected by the autodoc documentation generator for https://docs.konghq.com.

docs(conf) fix formatting of kong.conf.default

---

kong/db/dao/init.lua
kong/db/dao/snis.lua
kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua

1. `dao:rows_to_entities` will now properly set `array_mt` on returned entities
2. schema's `make_array` will now set `array_mt` even on non-empty arrays
3. schema's `make_set` will now set `array_mt`, it still sets `Set_mt` for non-empty arrays which the `cjson.encode` does not support, but  it works as long as the value is not turned to e.g. hash afterwards.
This is continuation of #4720.

refactor(db) replace deprecated cjson.empty_array_mt with cjson.array_mt

---

kong/db/dao/init.lua
spec/01-unit/01-db/04-dao_spec.lua

This PR corrects an issue with cache_key generation when a schema defines a composite cache_key with optional fields that are not type `foreign`. The issues occurs when calling `DAO:cache_key` with `key` parameter of type `table` containing properties with value `nil` or `null`:
Example Schema
```
local schema = {
name = "Foo",
primary_key = { "a" },
cache_key = { "b", "u" },
fields = {
{ a = { type = "number" }, },
{ b = { type = "string" }, }, -- optional cache_key component
{ u = { type = "string" }, }, -- optional cache_key component
},
}
```
nil
```
dao:cache_key({a = 1, b = "foo", u = ngx.null})
-- 'Foo:foo:userdata: NULL:::'
```
null
```
dao:cache_key({a = 1, b = "foo", u = nil})
-- 'Foo:foo:nil:::'
```
This PR converts nil/null cache_key components to an empty string, resulting in …

fix(dao) convert null/nil to empty string when generating cache_key from table

---

kong/pdk/request.lua

Instead of switching back and forth with global `cjson`, we instantiate
a new module level `cjson` and set `decode_array_with_array_mt` to true.
Thanks @kidd and @Tieske for the pointers.

refactor(pdk) use cjson.new and decode_array_with_array_mt(true)

---

bin/busted
spec/03-plugins/23-rate-limiting/04-access_spec.lua
spec/03-plugins/23-rate-limiting/05-integration_spec.lua
spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
spec/helpers.lua

Adds a KONG_SPEC_REDIS_HOST env var to make it easy to bind it in tests.
* change the hardcoded addrs for redis to a helper variable
* change bin/busted so it doesn't override `KONG_SPEC.*` env vars

test(*) add KONG_SPEC_REDIS_HOST env var

---

kong/conf_loader.lua
kong/db/strategies/cassandra/connector.lua
spec/01-unit/01-db/05-cassandra_spec.lua
spec/01-unit/03-conf_loader_spec.lua

1. fix(conf) ensure 'cassandra_local_datacenter' must be specified for all DCAware LB policies
2. fix(db) ensure C* serial consistency is local when DCAware LB policy is in use
The hard-coded setting in 2. could cause some LWT (e.g. `INSERT INTO ... IF NOT EXISTS`) to fail with unavailable exceptions when running atop of a multi-DC cluster with cross-datacenter network issues.
An error that one can observe on such issues looks like so:
could not execute insertion query: [Unavailable exception] Cannot achieve consistency level QUORUM

fixes: better handling of C* config validation and serial_consistency option

---

kong/plugins/ldap-auth/access.lua
kong/plugins/ldap-auth/schema.lua
spec/03-plugins/20-ldap-auth/02-schema_spec.lua

This PR adds LDAPS support. It is a reworking of PR #2720 by @gauauu, updating its code to a mergeable state in current Kong `next`.
This is different from the STARTTLS option. STARTTLS encrypts the existing connection and that is what is usually advised to use for securing the data. But some LDAP servers are only configured to use LDAPS on port 636. More details are available on the discussion in #2720.
Closes #2720.
Fixes #4060.
See also #1393.

feat(ldap-auth) add ldaps support

---

scripts/merge-master-into-next

This is a development tool for performing merges from the `master` branch into `next` correctly. Up to this day, these merges had to be done manually and that process was error-prone (multiple people got it wrong in different occasions, myself included).
A key problem is that the Github green button offers three options but none of them does the right thing we need (you end up either with an incorrect rebase, or with a double merge commit), therefore the branch needs to be approved in the web UI and merged from the terminal.
This script makes this process more consistent. It requires `hub` (a CLI interface to the Github API).
As a demonstration of this script, the latest merge from `master` into `next` was done entirely using this script:
* I ran `scripts/merge-master-into-next create` …

feat(scripts) introduce semi-automated merge-master-into-next script

---

CHANGELOG.md
kong-1.2.0-0.rockspec
kong-1.2.1-0.rockspec
kong/meta.lua

- Add changelog for 1.2.1
- Ensure correct plugin versions
* sidecar-injector: bump to 0.2
* request-transformer: no need to bump (major component is up-to-date, so luarocks will pick up the latest patch release available)
- Bump Kong version

Release: 1.2.1

---

kong/runloop/handler.lua

Ensures that `Upgrade` header is not cleared on `websocket`. This is the second patch after the initial patch PR #4719. It seems like some servers send back `Upgrade: WebSocket` instead of `Upgrade: websocket` which caused the proxy to clear the `Upgrade` header. This ensures that the value is compared case-insensitive.
The test is missing as it is a bit tricky to implement that as our mock websocket server always sends the `Upgrade` header back as lower case `websocket` which does not cause this issue. But the fix in itself is rather simple.
Fix #4779

fix(proxy) do not clear upgrade header (case-insensitive), fix #4779

---

kong-1.2.1-0.rockspec

Changes:
- style related updates
- small change to make migration a bit more re-entrant
- use kong pdk to read the post args for logout
- remove unused base plugin require
- bump resty session to 2.24
- bump versions on travis ci to make it work with next branch of kong

chore(deps) bump session plugin to 2.1

---

kong/api/api_helpers.lua
kong/tools/utils.lua
spec/01-unit/05-utils_spec.lua
spec/01-unit/07-api_helpers_spec.lua
spec/02-integration/01-helpers/01-helpers_spec.lua
spec/03-plugins/09-key-auth/02-access_spec.lua

This PR modifies `utils.encode_args` to recursively encode nested args. Previously, only a single level of nesting was supported. 
* Adds `recursive_encode_args` function, called from `utils.encode_args` when it encounters a table value
* Adds tests

fix(utils) recursively url encode args

---

.ci/setup_env.sh
.travis.yml
kong/pdk/init.lua
kong/pdk/service.lua
t/01-pdk/09-service/00-phase_checks.t
t/01-pdk/09-service/03-set-tls-cert-key.t

This feature allows plugins to override client certificate used while handshaking with services dynamically.

feat(pdk) implemented kong.service.request.set_cert_key()

---

kong/cmd/config.lua
kong/db/declarative/init.lua
kong/db/schema/entities/cluster_ca.lua
kong/db/schema/entities/tags.lua
kong/db/schema/metaschema.lua
spec/02-integration/02-cmd/11-config_spec.lua
spec/02-integration/03-db/08-declarative_spec.lua

feat(cmd) implement `kong config db_export` command

---

kong-1.2.1-0.rockspec
kong/cache.lua
kong/db/dao/init.lua
kong/db/declarative/init.lua
kong/runloop/handler.lua

This version has the `shm_retries` option (default 5) to fix
potential 'no memory' errors, as reported by @hbagdi .
Additionally the return values of `post`, `post_local` and `poll`
behave more Lua-ish. So we can now check on `ok` instead of on `err`

chore(deps) bump worker-events to 1.0.0

---

kong-1.2.1-0.rockspec
kong/api/routes/upstreams.lua
kong/db/dao/targets.lua
kong/runloop/balancer.lua
spec/01-unit/09-balancer_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua
spec/fixtures/balancer_https_server.lua
spec/helpers.lua

- Changes needed for lua-resty-healthcheck 1.0.0 which requires that hostnames
are used combined with IP and port to know exactly which host is being checked.
- lua-resty-healthcheck version bumped in rockspeck.

feat(balancer) healthcheck uses ip+port+hostname combo

---

kong/db/schema/others/declarative_config.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua

Endpoints that could be identical under different parents, e.g. identical targets under different upstreams, were being overwritten when using a declarative config. This PR makes auto-generated primary keys to be compound by parent's foreign keys, avoiding that issue.
Fix #4778

fix(declarative) compound key for endpoints that can be identical

---

Makefile

The $OS string is supposed to be either "linux" or "darwin".
However, the grpcurl releases named them "linux" or "osx".
Since the `$OS` var seems to be only used for this, I just changed its value on the `if` to `osx`.

fix(Makefile) fix installing grpcurl in osx

---

kong/plugins/basic-auth/daos.lua
spec/02-integration/03-db/08-declarative_spec.lua

This change makes basicauth_credentials non-exportable by db_export.
Explanation: basicauth_credentials have a built-in encryption system - the passwords are encrypted in the database.
If these are exported, they cannot be imported back to the database (they would be re-encrypted, rendering them useless).
The recommended way to import credentials for now is using plain, unencrypted passwords (which can not be obtained from the database).

fix(db_export) skip basicauth_credentials on db_export

---

kong/db/migrations/core/005_120_to_130.lua
kong/db/schema/entities/upstreams.lua
kong/runloop/balancer.lua
spec/01-unit/09-balancer_spec.lua

- `"round-robin"` is now an available balancing algorithm, with the same behavior that was found in `algorithm="consistent"` and `hash_on="none"` combination before.
- Added migrations to set new `algorithm` field values, according to existent `hash_on` values.
- Added `shorthands` to the schema to keep backward compatibility in admin API and declarative config, avoiding inconsistent settings.

fix(balancer) added round-robin to algorithms enum

---

kong/init.lua
kong/runloop/handler.lua

Errors occurring during the `init_worker` phase can be critical to Kong's
proper runtime functioning. If any such error is encountered, it is
currently logged as a `CRIT` level warning, indicating an unhealthy
node. Unfortunately, those startup logs are often ignored by users,
causing corrupted worker processes to be left untouched, which can be
catastrophic in many cases.
This change ensures that all `init_worker` errors susceptible to produce
a corrupted worker process will be logged every time such a worker were
to accept a connection/request, with an `ALERT` level warning.
Note that a better initialization design would be to update the
lua-resty-worker-events library so that it can be initialized in the
`init` phase (and its polling later started in `init_worker`).
Doing so would …

feat(core) stash init_worker error and print them during request processing

---

spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua
spec/helpers.lua

Travis CI seems to be causing up to 30 second delays when DNS fails to resolve (which is a situation we trigger deliberately in our tests, and used to be quick).
I was able to make most tests pass by increasing timeouts, but one of them proved particularly tricky and for now I just disabled it with the `#flaky` hashtag, in the interest of unblocking our ongoing work and testing for completing the 1.3.0 release cycle.

tests(*) address flakiness issues in Travis CI

---

kong/runloop/balancer.lua
spec/02-integration/02-cmd/03-reload_spec.lua

When using dbless configs caches from removed targets were still valid after a reload and were being recreated. This change invalidates upstream caches before creating new balancers, forcing them to be retrieved from DAO.
Fix #4808

fix(balancer) invalidate upstream cache before creating balancer

---

kong/db/schema/entities/routes_subschemas.lua
spec/01-unit/01-db/01-schema/06-routes_spec.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua

Fix inconsistency in error message reported by entity checker and schema
rules. gRPC doesn't accept a `methods` attribute.

hotfix(schema) grpc subschema entity checker

---

kong-1.2.1-0.rockspec

see release notes: https://github.com/Kong/lua-resty-dns-client#410-7-aug-2019
Fixes #4781

chore(deps) update dns client to 4.1.0

---

.ci/setup_env.sh
spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua

Add tests for tcp-log with gRPC client protocol.

tests(tcp-log) add tests for grpc client protocol

---

.gitignore
.travis.yml
autodoc/data/admin-api.lua
autodoc/general.lua
scripts/autodoc-admin-api

This PR merges the auto-generation of reference docs for the Admin API, which currently live in the https://github.com/kong/docs.konghq.com repository, into this repository.
It also integrates the generation in the CI run. This means that whenever a new entity, schema attribute or Admin API endpoint is added to the code base, it will have to be documented to make the tests pass.
This PR includes @dndx's recent fixes and documentation of the CA Certificates entity (superseding https://github.com/Kong/docs.konghq.com/pull/1421)  as well as new docs for new Upstreams endpoints introduced in #4752 and the `headers` attribute for Routes introduced in #4758.

docs(admin-api) verify automated reference docs

---

kong/db/schema/typedefs.lua
spec/01-unit/01-db/01-schema/03-typedefs_spec.lua

An exact match of `host` header should not be allowed in the headers
property of routes but a header with `host` as a sub-string in the key should be
allowed.
* hotfix(schema) allow 'host' substrings in headers

hotfix(schema) allow 'host' sub-string in headers

---

kong/plugins/acl/daos.lua
kong/plugins/basic-auth/basicauth_credentials.lua
kong/plugins/basic-auth/daos.lua
kong/plugins/hmac-auth/daos.lua
kong/plugins/jwt/daos.lua
kong/plugins/key-auth/daos.lua
kong/plugins/oauth2/daos.lua
spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/03-plugins/09-key-auth/01-api_spec.lua
spec/03-plugins/10-basic-auth/02-api_spec.lua
spec/03-plugins/10-basic-auth/03-access_spec.lua
spec/03-plugins/16-jwt/02-api_spec.lua
spec/03-plugins/18-acl/01-api_spec.lua
spec/03-plugins/19-hmac-auth/02-api_spec.lua
spec/03-plugins/25-oauth2/02-api_spec.lua

The issue originates from converting the old schema to new one where some fields where marked as `default=ngx.null` instead of `required=true`. This PR changes those back to required.
Fix #4875

fix(plugins) foreign fields were not always required as they should

---

kong/db/dao/plugins.lua
spec/02-integration/03-db/03-plugins_spec.lua

The plugins had an customized api that used read-before-write on upserts which is not how our definition of upsert should work.
There are many interpretation of what upsert can mean, the two most common ones are:
1. insert (post) or update (patch)
2. insert (post) or replace (put)
Our definition is the 2. where replace means that we do not retain any properties of the existing entity, except the primary key (to avoid deleting the entity prior inserting a new one).
Fix #4802

fix(dao) PUT on plugin configs behaves like PATCH (instead of replace)

---

kong/plugins/oauth2/access.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

`client_id` (from downstream client) was not validated against empty string before it was used, and that subsequently caused a DAO validation error. This fixes that.
Fix #4728

fix(oauth2) empty client_id wasn't checked, which resulted server error

---

kong/pdk/response.lua
t/01-pdk/08-response/11-exit.t

This contains more refinements to PDK's `kong.response.exit` for better gRPC support and compatibility with a current code and gRPC (a bit like best effort). Also explicitly errors on cases where explicitly outputting grpc content that we cannot encode.
* fix(pdk) remove the grpc_mode check, checking content types is enough. Also fixes warning that is logged when using this on admin api.
* fix(pdk) do not replace headers when specified with response.exit
* fix(pdk) response.exit to error when using table body with content-type.  Also logs warning when using table body that is not the common:
```
{
message = "<string>"
}
```
and then basically ignores that body for better compatibility withcurrent Kong core and plugins that are not necessarily build for grpc in mind.

 fix(pdk) response.exit to error when using table body with content-type

---

kong-1.2.1-0.rockspec

Changes:
* Add Content-Length: 0 header on POST/PUT/PATCH when the body is absent
* Add flag to enable debug logging
The `Content-Length` issue has been reported outside of the public channels.

chore(deps) bump resty-http from 0.13 to 0.15

---

kong/pdk/response.lua
spec/03-plugins/15-response-transformer/01-header_transformer_spec.lua
t/01-pdk/08-response/00-phase_checks.t

enable phase test for it. fix #4848
We take advantage of the new [ngx.resp.add_header](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/resp.md#add_header) function which is both simpler and faster.
Note on mock of `kong.response.add_header` in plugin tests. Since the purpose of that file is to test whether the transformer calls `add_header` correctly instead of testing the `add_header` API itself, this change is appropriate. The PDK test suite already ensured `add_header` will function properly.

fix(pdk) make sure `response.add_header` works in `rewrite` phase and

---

spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
spec/02-integration/05-proxy/12-error_default_type_spec.lua
spec/helpers.lua

This should eliminate the `Status expected: (number) 504 Status received: (number) 503 Body: (string) '{"message":"name resolution failed"}` failure we have been seeing recently.
Note on the selection of IP address. It is just one of the RFC 1918 address that is likely not being used. This may or may not work depends on the network environment but as far as Travis, Docker, VMWare or VirtualBox are concerned, it works well (and much better than the domain we had in there).

tests(proxy) fix flappy tests caused by instability in DNS resolving

---

kong/reports.lua
spec/02-integration/04-admin_api/11-reports_spec.lua
spec/02-integration/05-proxy/21-reports_spec.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/api.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/handler.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/schema.lua
spec/helpers.lua

Previously the anonymous reports ping only included a single counter for the requests the server did:
```
requests=100
```
With this PR, it also differentiates between types:
```
requests=100;http_reqs=10;https_reqs=0;grpc_reqs=20;grpcs_reqs=0;ws_reqs=70;wss_reqs=0
```

feat(reports) include traffic entry types

---

kong/pdk/private/phases.lua

This is a small workaround to a problem that happens when any custom
content_by_lua block attempts to use the PDK. For example, this happens when
trying to hit the `/` endpoint of the metrics server of the Prometheus plugin:
https://github.com/Kong/kong-plugin-prometheus/blob/0.4.1/kong/plugins/prometheus/serve.lua#L32
In normal operation of Kong, `kong.ctx.core.phase` is always set,
so the code path added should never be hit.
This is a regression test for kong-plugin-prometheus that demonstrates the fix:
```
diff --git a/spec/03-custom-serve_spec.lua b/spec/03-custom-serve_spec.lua
index 032e34d..c70afb0 100644
--- a/spec/03-custom-serve_spec.lua
+++ b/spec/03-custom-serve_spec.lua
@@ -67,5 +67,14 @@ describe("Plugin: prometheus (custom server)",function()
local body = …
```

fix(pdk) treat custom content blocks as the Admin API

---

kong/db/dao/targets.lua
spec/02-integration/04-admin_api/15-off_spec.lua

When adding targets if the port is empty it should default to 8000, but dbless strategy was missing this behavior.

fix(targets) add ports to targets missing them

---

Makefile

most important change is fixes around building and release from source. Entire diff is here https://github.com/Kong/kong-build-tools/compare/2.0.0...2.0.1

chore(ci) bump the kong-build-tools version

---

kong/plugins/key-auth/handler.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/13-error_handlers_spec.lua
spec/fixtures/custom_nginx.template

Previously, e.g. when doing `TRACE` request:
```
http TRACE :8000
```
Nginx terminated the request with the following headers and body:
```html
HTTP/1.1 405 Not Allowed
Connection: close
Content-Length: 163
Content-Type: text/html; charset=UTF-8
Date: Fri, 16 Aug 2019 09:19:10 GMT
Server: kong/1.2.1
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty/1.15.8.1</center>
</body>
</html>
```
With this change, the output doesn't expose OpenResty version anymore, although it is to be noted, that it still exposes `openresty`, which can be considered a bug in Nginx/OpenResty default response body templates as they don't seem to respect `server_tokens=off` that this commit adds
to our server templates.
This also affects other …

feat(*) do not expose openresty version

---

kong/init.lua

Previously on TLS/SSL requests we logged init worker errors twice, this changes it so that we will only log it once.

chore(proxy) only log init worker errors once with tls request

---

kong-1.2.1-0.rockspec

Changes:
- introduce workarounds for LuaJIT 47bit userdata

chore(deps) bump luaossl from 20190612 to 20190731

---

kong/runloop/balancer.lua

`populate_healthchecker` function was trying to set peers status with data that might be set by a worker that ran before but was not checking if said data was actually available, eventually causing lua-resty-dns-client to execute callbacks with invalid values.

fix(balancer) don't set health if target is not created yet

---

kong/db/migrations/core/005_120_to_130.lua
kong/db/schema/entities/ca_certificates.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua
spec/02-integration/04-admin_api/16-ca_certificates_routes_spec.lua

Thanks @hbagdi for pointing it out!
This is a very small change and ideally goes out in 1.3.0 to avoid any future migration pains.

feat(schema) make `ca_certificates.cert` field unique

---

kong.conf.default
kong/conf_loader.lua
kong/runloop/handler.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua

Prior this change the router and plugins where checked for changes every second (starting two timers per second on each worker). The issue #4872 reported some issues that frequent updates may cause on proxying performance and suggested we allow configuring the value. This PR adds `router_update_frequency` configuration option, which still default to that same once per second. This is mostly usable with `router_consistency=eventual`. But it will affect `strict` too (but raising this value with `strict` will make it more likely that the routers are rebuild on request time (making a timers bit useless, though it may be ok with slow traffic scenarios).
Fix #4872

feat(conf) add router_update_frequency configuration option

---

kong/db/dao/init.lua

This PR removes `options.ttl` and `options.tags` context validity checks (ie: failing a select with ttl on the options). These checks will fail, for instance, during an update of an entity, when options are being proxied from the update to a select during a `read_before_write`. 
Since there's already magic in place on the dao for checking these options depending on the context, these checks are an extra safeguard. What this proposes is to silently ignore options that do not make sense on a given context.
* Remove `options.ttl` context checks on options validation from dao
* Remove `options.tags` context checks on options validation from dao
Makes it possible to include `ttl` on compound update queries

fix(dao) remove options.ttl and options.tags context checks

---

autodoc/data/admin-api.lua
scripts/autodoc-admin-api

This PR adds the following:
1. a generic description about auto-generated endpoint
2. support for `admin_api_name` and `admin_api_nested_name` schema parameters
3. support for the fourth level of entity endpoint

docs(admin-api) document the fourth level of auto-generated admin apis

---

kong/plugins/response-transformer/body_transformer.lua
kong/plugins/response-transformer/schema.lua
spec/01-unit/01-db/01-schema/07-plugins_spec.lua
spec/03-plugins/15-response-transformer/02-body_transformer_spec.lua

Response transformer is turning every value into string, which is not something expected. This change updates response transformer to convert values into its expected type accordingly.
Fix #4880

 fix(response-transformer) allow specify type for config value

---

kong/plugins/oauth2/access.lua
kong/plugins/oauth2/daos.lua
spec/03-plugins/25-oauth2/02-api_spec.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

Allow to create client_credentials without redirect_uris field
* Update oauth2_credentials dao
* Handle issue token when redirect uris is null for `grant_type` "client_credentials"
* Add related tests
Fix #2030

feat(oauth2) make redirect_uris field optional

---

kong/constants.lua
kong/init.lua
kong/reports.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua
kong/templates/nginx_kong.lua
kong/templates/nginx_kong_stream.lua
spec/02-integration/05-proxy/21-reports_spec.lua
spec/fixtures/1.2_custom_nginx.template
spec/fixtures/custom_nginx.template
spec/fixtures/custom_plugins/kong/plugins/reports-api/handler.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/schema.lua

- Adds stream reports and makes h2 and h2c reports available
- Also makes kong.reports safe for running it with stream module
- Removes excess code from plugins iterator where "reports" plugin was added to loaded plugins (it is not used) and moved reports initialization code to runloop
Removes need to have GRPC_PROXY_MODES, e.g. "grpc" and "grpcs", and makes the mode consistent on what we have for "http" where we don't have "https", "h2" or "h2c".
Fixes issue where `kong.reports` didn't work correctly on `stream`, as pointed out in this comment: https://github.com/Kong/kong/issues/4975#issue-486338205

feat(reports) add h2, h2c, tcp, and tls reports + removal of GRPC_MODES

---

kong/init.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/14-server_tokens_spec.lua

This PR moves latency counting from `handler.lua` to `init.lua` to provide a more consistent counting of latency headers as more and more stuff has been added to `init.lua` which is not accounted in latency counting. Also proxy-latency counting now takes the balancer phase in
counting too, which was not a case before this PR.
The PR tries to make header counting resilient on errors, ngx.exec / ngx.exit, etc. too, and that's why it might look a bit strange why a lot of this counting is re-checked on later phases.
Part of this refactoring some of the code was moved from `handler.lua` to `init.lua`, most notable it didn't make sense to keep `balancer.before` and `balancer.after` anymore in `handler.lua`.
It also contains other commit:
**refactor(proxy) chronological order the functions in …

refactor(proxy) make latency header counting more robust and consistent

---

CHANGELOG.md

Fixes the article before a consonant.

docs(changelog) fix typo

---

kong/api/endpoints.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua

[Issue]
PUT method is not working as documented when creating a Service object.
[Details]
Per following document, it is supposed that users could create a Service associated to a Route object using the PUT method:
– Create Or Update Service Associated to a Specific Route
https://docs.konghq.com/1.2.x/admin-api/#create-or-update-service-associated-to-a-specific-route
However, the Admin API returns 404 when trying to perform the above operation.
[Steps to reproduce]
Create a new Route object
```
$ http POST http://sanfrancisco:36201/routes name=testrt001 paths:='["/testrt001"]'
HTTP/1.1 201 Created
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://sanfrancisco:36202
Connection: keep-alive
Content-Length: 359
Content-Type: application/json; charset=utf-8
Date: Fri, …
```

fix(admin) allow put requests to nonexistent foreign entities

---

.ci/setup_env.sh
.travis.yml
Makefile
spec/02-integration/05-proxy/02-router_spec.lua

Purpose of this cut / paste is to relocate the setup CI logic into a Make task such that it can be reused in other repositories.
Applied sensible defaults in the bash script which can be overridden by environment variables to keep backwards compatibility
Reference: https://github.com/Kong/openresty-patches/pull/55

chore(ci) add the ability to use the Kong CI setup from external repositories

---

kong/globalpatches.lua
kong/plugins/rate-limiting/policies/init.lua
spec/03-plugins/23-rate-limiting/02-policies_spec.lua

The "local" policy now sets the TTL on the counter to be equal to one period
length (e.g. if the counter is for requests in the current minute, the
TTL is set to one minute).
This supersedes #4422, bringing @cb372's contribution to a mergeable state.

feat(rate-limiting) set ttl for local policy counters

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/schema.lua
spec/03-plugins/23-rate-limiting/04-access_spec.lua

Add service-level support for the rate-limiting plugin, in addition to the existing consumer, credential and IP levels.
This supersedes #4749 to merge @wuguangkuo's contribution into the `next` branch instead of `master`

feat(rate-limiting) at service level

---

kong/db/declarative/init.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/fixtures/burst.yml

When loading declarative configs, there were excessive events being fired up, overflowing lua-resty-worker-events queue, and losing some of them. 
This change creates a new keyword for upstreams and targets, which means that all of those entities must be processed, avoiding to create one event per entity.

fix(declarative) reduce events while loading declarative configs

---

kong/db/declarative/init.lua

This borrows from JSONschema and OpenAPI. Any value can now have a `$ref` entry, eg. json:
```json
"my_key": { "$ref": "#/components/some/value" }
```
A new top level entry `components` is introduced to hold reusable objects and values.
An additional commit fixes the Lua declarative input parsing and error handling.

fix(declarative) Lua input parsing and error handling

---

kong/cluster_events/strategies/cassandra.lua

The proper name for this option is `consistency`. Specifying
`consistencies` as prior to this patch causes the pagination queries to
use the default consistency setting of `ONE`, instead of the desired
`LOCAL_ONE`.

fix(cluster_events) set LOCAL_ONE consistency in C* polling query

---

kong/pdk/client.lua
kong/pdk/private/phases.lua
kong/plugins/basic-auth/access.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/access.lua
kong/plugins/oauth2/access.lua
t/01-pdk/05-client/00-phase_checks.t
t/01-pdk/05-client/09-load-consumer.t
t/Util.pm

Anonymous consumer previously could be configured using only the `ID` of the consumer, with this change, the plugin configuration can use the `username` in addition to `ID`.
Fix https://github.com/Kong/kubernetes-ingress-controller/issues/265

feat: accept consumer username for anonymous configuration

---

kong/runloop/balancer.lua

As target history entries don't have `order` property anymore, we must compare old and new entries individually to check if they are different.
Fix #4846

fix(balancer) check if target history must be applied

---

kong/plugins/response-transformer/header_transformer.lua
kong/plugins/response-transformer/schema.lua
spec/01-unit/01-db/01-schema/07-plugins_spec.lua
spec/03-plugins/15-response-transformer/01-header_transformer_spec.lua
spec/03-plugins/15-response-transformer/03-api_spec.lua

Add support to rename response headers in response-transformer plugin
- Modify the schema of the response-transformer plugin to add
configuration related to rename headers. In addition, a function to
validate headers names through Kong method has been added.
- Modify _M.transform_headers response-transformer plugin function to
rename response headers.
- Add test for the rename response headers in response-transformer plugin.
Since request-transformer plugin support modify rename headers it is
necessary that response-tranformer plugin has it. For example, map the
value to internal header and expose public header.

feat(response-transformer) add support to rename response headers

---

kong-1.3.0-0.rockspec
spec/01-unit/12-plugins_order_spec.lua
spec/01-unit/13-plugins_version_spec.lua

Changelog:
https://github.com/Kong/kong-plugin-prometheus/blob/master/CHANGELOG.md#050---20190916
Summary:
- **Route based metrics:**  All proxy metrics now contain a tag with the name
or ID of the route.
- **New metrics releated to Kong's memory usage:**
New metrics related to Kong's shared dictionaries
and Lua VMs are now available
- Performance has been improved by avoiding unnecessary timer creation.
This will lower the impact of the plugin on Kong's overall latency.

chore(deps) bump prometheus plugin to 0.5

---

kong/constants.lua
kong/reports.lua
spec/01-unit/11-reports_spec.lua
spec/02-integration/02-cmd/11-config_spec.lua
spec/helpers.lua

Sends reports with `tcp` instead of `udp`. Also changes the port where the reports are sent from 61829 to 61830.

chore(reports) sends reports with tcp instead of udp

---

autodoc/data/admin-api.lua
kong-1.3.0-0.rockspec
kong.conf.default
kong/api/api_helpers.lua
kong/api/init.lua
kong/api/routes/health.lua
kong/api/routes/kong.lua
kong/conf_loader.lua
kong/init.lua
kong/status/init.lua
kong/templates/kong_defaults.lua
kong/templates/nginx_kong.lua
spec/01-unit/03-conf_loader_spec.lua
spec/02-integration/08-status_api/01-core_routes_spec.lua
spec/fixtures/custom_plugins/kong/plugins/admin-api-method/status_api.lua
spec/fixtures/nginx-directives.conf

Problem
-------
Kong's Admin API exposes `/status` endpoint, which is consumed by other
services in the infrastructure to monitor Kong's health.
While this has worked for Kong for a long time,
we run into following issues with the current design:
- Users want to health-check Kong and also protect Kong's Admin API at
the same time. If Kong's Admin API is protected using an auth plugin,
health-checking becomes difficult. The reason being not all
orchestration/platform tools performing health-checks support adding
arbitrary headers to health-check requests.
- Users want to expose Kong's health outside a private network but keep
the Admin API locked down.
- It is hard to perform HTTP based health-checks for a Kong node running
only the proxy interface i.e. the Admin interface is disabled.
- A …

feat: implemented a new status interface

---

Makefile

Full changes: https://github.com/Kong/kong-build-tools/compare/2.0.1...2.0.3
- ability to build arm64 packages
- bumped openresty-build-tools for older ld version compatibility (trusty, jessie, centos/rhel 6)

chore(ci) bump kong-build-tools

---

kong/db/schema/init.lua
kong/db/strategies/cassandra/init.lua
kong/db/strategies/postgres/init.lua
kong/plugins/key-auth/daos.lua
kong/plugins/key-auth/handler.lua
kong/plugins/key-auth/migrations/002_130_to_140.lua
kong/plugins/oauth2/migrations/003_130_to_140.lua
spec/03-plugins/09-key-auth/01-api_spec.lua
spec/03-plugins/09-key-auth/02-access_spec.lua

Add support for keyauth credentials expiration by using metaschema ttl. Mainly based on https://github.com/Kong/kong/pull/4239, rebased and with the approach recommended on the comments.
The downside is the impossibility to differentiate between an invalid and an expired token. 
> [ p0pr0ck5 commented on Jan 24](https://github.com/Kong/kong/pull/4239#issue-247234145)
> * Add ttl = true to keyauth credentials schema
> * Add migration for Postgres to add TTL column
> * Add API spec for added behavior
* Add dao support to return ttl on select queries for strategies
* Return entity ttl on keyauth cache callback
* Add API spec for listing ttl on keyauth admin endpoint
Fix #87

feat(key-auth) support auto-expiring keys through dao ttl

---

kong/db/migrations/core/001_14_to_15.lua
kong/db/migrations/core/005_120_to_130.lua
kong/db/strategies/cassandra/connector.lua
kong/plugins/oauth2/migrations/001_14_to_15.lua
kong/plugins/oauth2/migrations/002_15_to_10.lua
spec/02-integration/02-cmd/10-migrations_spec.lua

Whenever we add migrations we may endup with a migration that is not reentrant. This PR fixes one such case, and now adds some tests too to make it less likely to happen again.

fix(db) reentrant migrations with added tests

---

kong-1.3.0-0.rockspec
kong.conf.default
kong/conf_loader.lua
kong/db/strategies/cassandra/connector.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua

A new `cassandra_refresh_frequency` property schedules a recurring background timer calling lua-cassandra's [cluster:refresh()](https://thibaultcha.github.io/lua-cassandra/modules/resty.cassandra.cluster.html#_Cluster:refresh) method in the background. In lua-cassandra 1.5.0, this method has been refactored to be safe to call at runtime.
When `cassandra_refresh_frequency` is `0`, no topology refresh timer will be scheduled. A restart of Kong is necessary for lua-cassandra to consider new nodes (decommissioned nodes are blacklisted by the retry policy). The default value for this timer is chosen to be `60`.
No Admin API endpoint has been implemented as part of this PR for the time being. Subsequent patches welcome if a manual refresh feature turns out to be desired.
**Note:** a more …

feat(cassandra) refresh cluster topology 

---

kong/pdk/init.lua
kong/pdk/request.lua
kong/plugins/log-serializers/basic.lua
spec/01-unit/10-log_serializer_spec.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
spec/helpers.lua

This PR fixes the outstanding caveat of using logging plugins to log NGINX-produced errors. The caveat - described in e709c95 - causes some request properties (i.e. method and uri args) to be incorrectly logged.
Since e709c95, Kong executes plugins on NGINX-produced errors. However, as described in the mentioned commit's message, a caveat with the approach (note: the sanest one) is that the request method is overridden by the `error_page` directive during the internal redirect (and the uri args do not survive the redirect either).
This approach chooses to rely on the PDK to fix this limitation, and manually parses the request headers when necessary (and possible).
Fix #4025
Fix #4751

fix(log-serializer) log correct request properties on NGINX-produced errors

---

.ci/setup_env.sh
.travis.yml

DEPS_HASH on .travis.yml didn't depend on .requirements file. This PR makes .requirements part of it, and also removes `make setup-ci`, which has already been removed in `next` branch. Also makes setup_env.sh to pick deps from .requirements file (fixing the failure in https://travis-ci.org/Kong/kong/jobs/588551598#L284)
* .requirements has to be part of the DEPS_HASH to be aware of changes
on deps
* Removing `make setup-ci` step from .travis.yml and making setup_env
find the dependency versions from .requirements file.  Previous to
this, the build was tried twice (the second one failing due to not
having the variables set)

chore(ci) fix dependency hash

---

kong-1.3.0-0.rockspec

Changelog:
https://github.com/Kong/kong-plugin-prometheus/blob/master/CHANGELOG.md#060---20190929
Summary:
Metrics are now be available on the Status API

chore(deps) bump prometheus plugin to 0.6

---

spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua

Attribute `host_header` was missing in declarative config unit tests.

fix(tests) new attribute host_header in upstream entity

---

kong/db/declarative/init.lua
kong/db/schema/init.lua
kong/db/schema/others/declarative_config.lua
spec/02-integration/02-cmd/11-config_spec.lua
spec/03-plugins/10-basic-auth/05-declarative_spec.lua

Enables transformations in declarative, adds tests that tests this with basicauth_credentials.
Fixes:
#4542 (though it will not allow password in hashed form in declarative, that we need to solve later?)

feat(declarative) add support for schema:transform for declarative

---

kong/db/dao/init.lua
kong/db/declarative/init.lua
kong/db/errors.lua
kong/db/schema/metaschema.lua
kong/db/strategies/cassandra/init.lua
kong/db/strategies/off/init.lua
kong/db/strategies/postgres/init.lua
spec/01-unit/01-db/02-db-errors_spec.lua
spec/02-integration/03-db/10-db_unique_foreign_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/fixtures/custom_plugins/kong/plugins/unique-foreign/daos.lua
spec/fixtures/custom_plugins/kong/plugins/unique-foreign/handler.lua
spec/fixtures/custom_plugins/kong/plugins/unique-foreign/migrations/000_base_unique_foreign.lua
spec/fixtures/custom_plugins/kong/plugins/unique-foreign/migrations/init.lua
spec/fixtures/custom_plugins/kong/plugins/unique-foreign/schema.lua

Adds support for unique foreign key fields in `schema` like:
```lua
{ service = { type = "foreign", reference = "services", unique = true, }, },
```
Also generates all the normal `unique` `DAO` functions for `unique` foreign keys:
- `select_by_[service]`
- `update_by_[service]`
- `upsert_by_[service]`
- `delete_by_[service]` 
Where `[service]` is the foreign field with `unique=true`.
This PR also adds new error `invalid foreign key` and changes the code to use it where it should.

feat(db) support unique constraint on foreign fields

---

kong/db/dao/init.lua
kong/db/schema/init.lua
kong/db/schema/metaschema.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua
spec/01-unit/01-db/01-schema/02-metaschema_spec.lua

This is continuation of the dao transformations. This time the PR adds read transformations to DAOs, and opens a door for encryption of data at rest.

feat(db) add support for read transformations

---

CHANGELOG.md

Adding a note that the release assets on bintray are now by target architecture
`1.3.0` was released such that it was backwards compatible so that will allow automation to switch while still pinned to `1.3.0` and then upgrade to `1.4.0` with no loss of functionality

docs(changelog) document the release asset name change

---

kong/db/migrations/core/006_130_to_140.lua
kong/db/strategies/postgres/connector.lua

The original `cluster events` cleanup routine was executed within a transaction provided by a trigger when inserting new events. This removes the function and trigger (and thus transaction) and moves `cluster_events` cleanup as part of our generic cleanup routine. It should fix the issue #4986, but it is quite hard to reproduce, thus no tests where added.
Fix #4986

fix(db) cluster events deadlock as reported by #4986

---

kong/plugins/jwt/handler.lua
spec/03-plugins/16-jwt/03-access_spec.lua

Pretty straight forward, fixes jwt plugin from throwing for example:
```
{"message": "An unexpected error occurred"}
```
to
```
{"message":"Invalid 'iss' in claims"}
```
When folks decide to go a little crazy and not provide a valid value on a claim, kinda edge case but a consumer leveraging the gateway did bring it up so here I am 🍻 .
Sample testing it in my dev environment, but I included an updated unit test for good measure too. I know yall dig those 😁. 
Least I can do after the awesome conference you folks put on. More to come! I have 3-4 ideas to PR that might be cool. 
* Implemented: /kong/plugins/jwt/handler.lua checking for the empty string claims
* Updated: /spec/03-plugins/16-jwt/03-access_spec.lua to include case for the empty string claims
Fix #4976

fix(jwt) handle empty string claims

---

kong/db/strategies/cassandra/init.lua

Fixes issues with tag-filtered GETs on Cassandra-backed nodes.
* Modify table index within Cassandra tag query handling to allow passing a subset of all entities found, rather than all entities found, to the next phase.
* When dereferencing entity IDs found during a Cassandra tag query, skip entities that no longer exist.
This addresses two fatal errors that appear during admin API GET requests filtered by tags on Cassandra-backed nodes:
* Kong Enterprise filters the list of tagged entities retrieved to remove entities that are not in the correct workspace (or whose workspace cannot be determined, because the entity has been deleted). Without [this change](https://github.com/Kong/kong/commit/330129b3320ba0dd7c7975c27a1aba998ea0c741), table indices for filtered entities will have no value, …

Fix tag-filtered GET issues for Cassandra-backed nodes

---

kong.conf.default
kong/conf_loader.lua
kong/init.lua
kong/pdk/client.lua
kong/runloop/handler.lua
kong/templates/kong_defaults.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
spec/02-integration/05-proxy/06-ssl_spec.lua
spec/02-integration/05-proxy/20-serviceless_proxying_spec.lua
spec/02-integration/05-proxy/22-reports_spec.lua
t/01-pdk/05-client/08-get_protocol.t

warning when attempting to enable it
Service Mesh causes upstream HTTPS request to ignore `proxy_ssl_*`
directives due to its replacement of the Nginx `SSL_CTX` data
structure (#5112, #4955). This PR disables Service Mesh by default and
adds a test to confirm normal upstream TLS behavior. Enabling it
requires additional configuration `service_mesh = on` or environment
variable `KONG_SERVICE_MESH=on` and will cause a deprecation warning on
startup.
Service Mesh (alongside patches to OpenResty) will be completely removed
in the next major release.
Fixes #5112.
Fixes #4955.

fix(proxy) disable service mesh by default and show a deprecation

---

kong/db/strategies/cassandra/init.lua

* float doesn't exist as a schema field. Aligns C* with postgres

fix(cassandra) change float to number schema field

---

spec/01-unit/01-db/01-schema/07-plugins_spec.lua
spec/01-unit/12-plugins_order_spec.lua
spec/01-unit/13-plugins_version_spec.lua

Fix build error triggered by update of response-transformer plugin.

hotfix(tests) initialize global `kong` for PDK based plugins

---

Makefile

`.travis.yml` calls `setup-ci` which in turn calls `setup-build`. Calling `setup-build` twice when using EC2 arm build workers more often then not leads to the worker not being available when we try and build the arm asset
Chaning `build-kong` to `package-kong` is just to align the `nightly-release` make task with the `release` make task they are identical tasks in kong-build-tools repository
One can see the result of this by searching for `make setup-build` on https://travis-ci.org/Kong/kong/jobs/599203538

chore(ci) fix nightly arm builds

---

kong-1.3.0-0.rockspec
spec/01-unit/01-db/02-db-errors_spec.lua
spec/02-integration/03-db/03-plugins_spec.lua
spec/02-integration/04-admin_api/03-consumers_routes_spec.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua
spec/02-integration/04-admin_api/10-services_routes_spec.lua

- utils.quote_arg will now optionally take an array of arguments and escape them all into a single string.
- app.parse_args now accepts a 3rd parameter with a list of valid flags and aliases
- app.script_name returns the name of the current script (previously a private function)
- Documentation updates
- utils.quit: exit message is no longer required, and closes the Lua state (on 5.2+).
- utils.assert_arg and utils.assert_string: now return the validated value
- pl.compat: now exports the jit and jit52 flags
- pretty.write: now sorts the output for easier diffs #293
- utils.raise changed the global on_error-level when passing in bad arguments
- utils.writefile now checks and returns errors when writing
- compat.execute now handles the Windows exitcode -1 properly
- types.is_empty would …

chore(deps) update penlight from 1.5.4 to 1.7.0

---

Makefile

Full diff: https://github.com/Kong/kong-build-tools/compare/2.0.3...2.0.4
- use centos packages for redhat
- capable of buildling centos/redhat 8
- cache the images
Also updated the Kong make task. Recycling the `release` task as part of `nightly-release` keeps the two tasks sync'd and we'll catch `release` challenges earlier

chore(ci) bump kong-build-tools dependency

---

kong/cmd/utils/prefix_handler.lua

Remove the arbitrary `16384` limit to `worker_connections`.
This limit was set long ago and appears to be legacy cruft. There is no reason to set this cap; users should be able to rely on file limit information (as parsed by `get_ulimit()`) to define this value instead
of silently being capped here.
* remove `math.min` call around setting `infos.worker_connections` in `prefix_handler`

refactor(core) remove arbitrary limit on worker_connections

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTING.md

Existing single GitHub template for issues is planned to be deprecated in the future and Github itself recommends updating the repo to _new issue template workflow_.
The existing issue template was removed and replaced with two new templates: bug report and feature request.
* removed existing single issue template
* added issue template for bug report with proper label
* added issue template for feature request with proper label
* updated `CONTRIBUTING.md` to link to issue template chooser
N/A

chore(Github) multiple issue templates

---

.travis.yml

verified we're capable of building buster packages as part of this PR https://github.com/Kong/kong-build-tools/pull/146

chore(release) add Debian buster as a release target

---

kong/api/routes/kong.lua
spec/02-integration/04-admin_api/02-kong_routes_spec.lua

All endpoints will be listed under the "/endpoints" path of the
management API.
With auto-generated endpoints it might not always be clear what
is available. By listing the user can see what the system has
available. Especially when adding additional plugins, that might
not always be properly documented.
here's an example of the additional output:
```json
[
"/",
"/acls",
"/acls/{acls}",
"/acls/{acls}/consumer",
"/basic-auths",
"/basic-auths/{basicauth_credentials}",
"/basic-auths/{basicauth_credentials}/consumer",
"/ca_certificates",
"/ca_certificates/{ca_certificates}",
"/cache",
"/cache/{key}",
"/certificates",
"/certificates/{certificates}",
"/certificates/{certificates}/services",
"/certificates/{certificates}/services/{services}",
"/certificates/{certificates}/snis", …
```

feat(api) list available endpoints

---

kong/api/routes/kong.lua
spec/02-integration/04-admin_api/02-kong_routes_spec.lua

Every list endpoint in Kong returns back data inside a `data` property
in the JSON response.
This small change follows the (informal) API convention.
This also makes it easy to parse the response in typed languages where
one wants to provide an "Object" to decode the response into.

hotfix(api) return endpoints inside a property

---

kong/api/routes/plugins.lua
spec/02-integration/04-admin_api/04-plugins_routes_spec.lua

JSON input should be kept as is, but our customized plugin endpoint did always infer the input, even with JSON input. This PR changes the code to only infer with `application/x-www-form-urlencoded` and `multipart/form-data`.
Fix FT-1066 (reported through customer support channels).

fix(admin-api) fix plugins fill-data to not infer json input

---

spec/02-integration/04-admin_api/15-off_spec.lua

Only run multiple workers in tests that exercise concurrency.
This is a workaround for some observed concurrency issues in `/config`, in order to improve the flakiness of the test suite. The actual underlying issue has been backlogged and will be addressed separately.

tests(dbless) separate concurrency tests

---

spec/02-integration/06-invalidations/03-plugins_iterator_invalidation_spec.lua

The PR #5191 introduced a breakage in one test that was wrongly written.
This PR fixes the test so that we get `green` `master` again.

hotfix(tests) fix a test that broke when we removed json inferring from plugins

---

kong/db/schema/init.lua
spec/01-unit/01-db/04-dao_spec.lua
spec/02-integration/02-cmd/11-config_spec.lua

Fixes issue with `kong config db_export` when trying to read
entities that are ttl-enabled and whose ttl value is `null`.
Contains regression tests both at unit and integration level.
FIxes #5185.

fix(db) only returns a null ttl if nulls is given

---

kong/api/endpoints.lua
spec/02-integration/04-admin_api/17-foreign-entity_spec.lua
spec/fixtures/custom_plugins/kong/plugins/foreign-entity/daos.lua
spec/fixtures/custom_plugins/kong/plugins/foreign-entity/handler.lua
spec/fixtures/custom_plugins/kong/plugins/foreign-entity/migrations/000_base_foreign_entity.lua
spec/fixtures/custom_plugins/kong/plugins/foreign-entity/migrations/init.lua
spec/fixtures/custom_plugins/kong/plugins/foreign-entity/schema.lua

The original detection worked like this:
```
local inverse = not foreign_schema.fields[foreign_field_name] and
schema.fields[foreign_field_name]
```
This worked great, but it held an assumption that can go wrong.
Example:
Routes DAO has foreign key to servive, specified by the field with name `service`.
So `routes_schema.fields["service"]` is specified (see schema.fields[foreign_field_name]).
All good so far. But then there is another check that I would say is flaky: `not service_schema.fields["service"]`. Service schema does not obviously have field called `service` currently, but if we ever add a field to service schema with a name of `service` this assumption turns up-side-down, and we have introduced a bug.
I though if we could make this more clever, but I ended up with an explicit …

fix(admin-api) change detection of foreign entity endpoints to explicit

---

kong/plugins/datadog/handler.lua
kong/plugins/datadog/schema.lua
spec/03-plugins/08-datadog/01-log_spec.lua
spec/03-plugins/08-datadog/02-schema_spec.lua

The plugin will now report metrics with `name`, `status` and `consumer` tags for:
- upstream_latency
- kong_latency
- latency
- request_count
- request_size
- response_size
The tags `name` and `status` will have the value of the service name and http status code respectively.  The tag `consumer` is only added if the `consumer_identifier` is specified.
As a result, only 6 metrics are reported to datadog:
- kong.upstream_latency
- kong.kong_latency
- kong.latency
- kong.request.count
- kong.request.size
- kong.response.size
These tags make the following metrics redundant and are no longer reported:
-  status_count
-  status_count_per_user
-  unique_users
-  request_per_user
If you have datadog dashboards and alerts based on the old-style metrics, you need to change them to use the new tag …

feat (datadog) plugin report metrics with tags

---

kong/api/routes/cache.lua
kong/cache.lua
kong/cache_warmup.lua
kong/constants.lua
kong/db/declarative/init.lua
kong/db/strategies/off/init.lua
kong/global.lua
kong/init.lua
kong/runloop/balancer.lua
kong/runloop/certificate.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua
kong/templates/nginx_kong.lua
kong/templates/nginx_kong_stream.lua
spec/01-unit/01-db/08-cache_warmup_spec.lua
spec/01-unit/09-balancer_spec.lua
spec/01-unit/14-dns_spec.lua
spec/01-unit/16-runloop_handler_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/fixtures/custom_nginx.template

New cache `kong.core_cache` is meant for core usage, while the existing
`kong.cache` is used in, e.g., plugins.

refactor(core) client cache separation

---

autodoc/data/admin-api.lua
kong/api/routes/upstreams.lua
kong/db/dao/targets.lua
kong/db/schema/entities/upstreams.lua
kong/runloop/balancer.lua
spec/01-unit/01-db/01-schema/09-upstreams_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua

- added new field `threshold` to `healthchecks` in `upstreams` entities.
- added new query parameter `balancer_health` for the endpoint `/upstreams/:upstream_id/health`. When `balancer_health=1`, the endpoint returns the balancer health, instead of the targets' health.

feat(balancer) use lua-resty-dns-client healthThreshold attrib

---

kong-1.4.0-0.rockspec

- Add DNS-based Authentication of Named Entities (DANE) support
- Add __close() metamethod
- Fix deprecation warnings with OpenSSL 1.1
- Fix special case listing of TLS 1.3 EC curves
- Fix general_name leak in cert:extensions()
- Fix unexported 'ssl.config' table
- Replace $(LD) with $(CCLD) variable
- Remove multiple definitions of 'ssl_options' variable
- Use tag in git format: v0.9
- Fix unexported 'ssl.config' table (backported)
- Fix general_name leak in cert:extensions() (backported)

chore(deps) bump luasec from 0.8 to 0.9

---

kong-1.4.0-0.rockspec

Bump lua-resty-dns-client to 4.1.1.
Changelog:
Fix: added logging of try-list to the TCP/UDP wrappers, see PR 75.
Fix: reduce logging noise of the requery timer

chore(deps) bump lua-resty-dns-client to 4.1.1

---

kong/router.lua
kong/templates/nginx_kong.lua
spec/01-unit/08-router_spec.lua

Fix issue preventing `preserve_host` behavior from
taking effect on gRPC.
Fixes #5053, #5217.
Due to Nginx gRPC module behavior, the `Host` header is not translated to the pseudo-header `:authority`, but instead sent as `Host`.

fix(grpc) preserve_host behavior

---

spec/01-unit/08-router_spec.lua

Add regression test for an ambiguous router match case involving matching prefixes on non-matching hostnames. 2683b86c2f7680238e3fe85da224d6f077e3425d fixed this issue, but was designed to address a different issue, and did not have tests for this case.
* Add regression test to router unit tests.

Add regression test for ambiguous router matching

---

kong/cmd/config.lua

Initialize the kong global and database before running any `kong config` subcommand.
* Move initialization of `kong` global and database prior to subcommand-specific code for `kong config` CLI command.
* Remove existing `kong` global and database initialization specific to `db_export`.
The `db_import` and `parse` subcommands invoke `parse_file`, which runs entity checks. Entity checks can require database access, and the `rbac_user` Enterprise entity does currently. If the `kong` global is not present and/or `kong.db` is not initialized, `db_import` and `parse` will fail.

Create "kong" global before executing "kong config" subcommands

---

kong/runloop/balancer.lua

Remove old balancers from upstream_ids. 
The big `upstream_ids` table may cause memory leak on upstream/target events.
Memory usage of Kong
before
after
(Maybe) Fix #5203

fix(balancer): remove old balancer from upstream_ids

---

scripts/autodoc-admin-api

Generate documentation to let the user know that they can use `service.name` instead of `service.id` when referring to a foreign key, etc.
Thanks @rainest for pointing out this omission in the docs!
Companion docs.konghq.com PR with the changes applied:
https://github.com/Kong/docs.konghq.com/pull/1622

docs(autodoc) document endpoint-key-based notation for Admin API calls

---

kong/plugins/request-termination/handler.lua
spec/03-plugins/14-request-termination/02-access_spec.lua

When you apply plugin for any `route` or `service` and set response code `204` without providing a message and you try to send a request to that route it responds with status code `204` and `Content-Length: 2` which is not good and tools such as `Postman` hangs on it.
This PR propose a solution to fix this issue by checking if `conf.message` is provided if not then just don't `exit` with empty body object just set `nil` to avoid any possible issues.
* add additional check for `conf.message` before sending response back with `body` object included.

fix(request-termination) add check for content object

---

kong/plugins/oauth2/migrations/001_14_to_15.lua

This PR was originally send as #4588, but merge conflict was probably wrongly resolved, so this change got missing. Here is another try to get this in.
Fix #4572, #5242

fix(migrations) oauth2 tokens ttl was incorrectly migrated

---

kong/router.lua
spec/01-unit/08-router_spec.lua
spec/02-integration/05-proxy/02-router_spec.lua

This is a continuation of #5216. It further reverts some breaking changes introduced by #3780, involving the handling of slashes inside the router.
Related with #4469. Related with #4538.

fix(router) slashes -- take 2

---

Makefile

full diff: https://github.com/Kong/kong-build-tools/compare/2.0.5...2.0.8
- merged openresty-build-tools into kong-build-tools
- merged openresty-patches into kong-build-tools
- pinned the helm version
- updated the pinned k8s version

chore(dependency) bump kong-build-tools pinned version

---

kong/constants.lua
kong/plugins/jwt/handler.lua

The jwt credential according to its database definition, does not have username but key. The key can be used to represents the authenticated jwt_credential.
* X-Credential-Username is correctly set
X-Credential-Username is correctly set with jwt credential.key (i.e. iss - jwt issuer) which represents the authenticated jwt credential. Therefore other plugins relying on X-Credential-Username will work.
Fix #XXX

jwt credential does not have "username" but "key"

---

Jenkinsfile
Makefile

By dropping the signing key in the right place and setting the `PRIVATE_KEY_PASSPHRASE` we now have signed releases.
```
hutchic@colin-usb:~/Downloads$ rpm -K kong-2019-11-26.el6.amd64.rpm 
kong-2019-11-26.el6.amd64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#1d5f3726) 
hutchic@colin-usb:~/Downloads$ curl -o kong.key https://bintray.com/user/downloadSubjectPublicKey?username=kong
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  3173    0  3173    0     0   5873      0 --:--:-- --:--:-- --:--:--  5865
hutchic@colin-usb:~/Downloads$ rpm --import kong.
kong.key                  kong.private.gpg-key.asc  kong.rpm                  
hutchic@colin-usb:~/Downloads$ rpm --import kong.key …
```

feat(release) setup signed rpm packages on daily releases

---

kong/cache.lua
kong/cluster_events/init.lua
kong/cluster_events/strategies/cassandra.lua
kong/cluster_events/strategies/off.lua
kong/cluster_events/strategies/postgres.lua
spec/02-integration/06-invalidations/01-cluster_events_spec.lua

The current implementation of cluster events (before this PR) uses `ngx.now()` a lot when inserting and reading data from `cluster_events`. This can lead to various hard to debug issues as there can be a clock skew between the nodes.
Issues like:
1. writer being in future making the readers not to pick events
2. writer being in past making the readers skip events
3. cleanup routine may delete entries the readers have not applied
This PR changes the cluster events to use `cassandra` or `postgres` server time on `inserting` and on `selects`. There is some fall-back code to `ngx.now()` but they should almost never be used (only in cases where there is a temporary communication issue with db).
This also makes nodes, even with clock skew, more consistent.
Unfortunately it is hard to write test …

fix(cluster-events) make cluster events more robust and more consistent

---

.travis.yml
Jenkinsfile

Trusty standard support ended on April 2019 ( https://wiki.ubuntu.com/Releases ) it's time we stop building Kong trusty packages
hold until https://github.com/Kong/kong-build-tools/pull/167 is merged / released

chore(release) drop trusty as a release target

---

kong/api/routes/config.lua
kong/api/routes/plugins.lua

We have received some complains about admin api timeouts because of
anonymous reports. This PR changes the reports so that they will be
sent in a timer detached from the admin api request.
E.g. #5256.

feat(admin-api) run anonymous reports on a timer on admin api

---

kong/tools/batch_queue.lua

The exponential backoff should only be applied in case of failures to send. Starting the delay value from 1 was forcing a 1 second delay between sends (even in non-batched mode).

fix(http-log) do not impose a retry delay on successful sends

---

kong/runloop/balancer.lua

* Do not leave the `creating` flag behind when the balancer fails to create.
This includes a refactor to ensure that the mutually-exclusive section of the
balancer creation always releases the flag, so that this doesn't happen again.
* Make more explicit the fact that we carry on if the healthchecker fails, by
logging it on `create_balancer`
* Add a sanity check in the ring balancer callback to ensure balancers and
healthcheckers are in sync, as already happens in other parts of the code.
Fix #5189
Fix #5283

fix(balancer) handle errors when creating balancer properly

---

Jenkinsfile

kong-build-tools uses dashes instead of underscores consistently now

chore(ci) small Makefile command typo

---

kong/runloop/handler.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
spec/fixtures/custom_plugins/kong/plugins/invalidations/handler.lua
spec/fixtures/custom_plugins/kong/plugins/invalidations/schema.lua

A single `patch` on e.g. `service` entity may cause four cluster events fired, out of which all four are the same. This was doubled because the #5114 introduced the core cache / plugins cache split.
This PR also adds a guard on `patches`: when the entity and old entity cache keys are the same, only one invalidation event is sent.

fix(cache) same invalidation sent multiple times

---

spec/02-integration/02-cmd/11-config_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua

Increase our coverage of declarative config testing: verify that validation errors on a valid YAML are caught. This was a blind spot in our test suite (it had unit tests for the validation function, but not integration tests to ensure the function is used).

tests(declarative) verify that validation errors are caught

---

kong/db/schema/entities/services.lua
spec/02-integration/04-admin_api/10-services_routes_spec.lua

Issue #5313 opened by @granularmike1 describes a bug in admin api where patching a service with `service.url` does not cleanup existing data.
E.g.
```
http PATCH :8001/services/my-service url=http://example.test
```
Doesn't clean `service.path` if it was previously specified. This is unexpected when the `url` sugar parameter is used.
Fix #5313

fix(schema) service url should cleanup existing url components

---

kong/db/schema/entities/services.lua
spec/01-unit/01-db/01-schema/05-services_spec.lua

PR #5102 changed service entity where it added optional `port` to `service.host`. This is not actually used, and is wrong as the service also has `service.port` for that. Thus this PR returns that back to original, that is `service.host` cannot contain `port`.

fix(schema) service host cannot have port

---

kong/tools/batch_queue.lua

This avoids memory issues with an ever growing queue in Lua memory when the http-log queue handling is slower than the number of incoming requests, essentially restoring the pre-queueing behavior of http-log when queuing settings are not enabled.
Without this patch, running http-log under load (e.g. testing with `wrk`) displays an ever-increasing memory consumption, up until the Lua VM panics with an "out of memory" error. With this patch, running the same test with `wrk` shows stable memory consumption.
We still need to address the memory growth issues for when queueing is enabled and the flushing is too slow, but for now this is a useful fix to make the default settings usable.

fix(http-log) do not use a queue when queue_size is 1

---

kong-1.4.2-0.rockspec
kong/plugins/acl/api.lua
kong/plugins/acl/daos.lua
spec/03-plugins/18-acl/01-api_spec.lua

@albertored reported issue here #5280.
This PR removes `endpoint_key` from `acls` dao, as it is not `unique`,
and using non-unique endpoint keys leads to strange results.
And of course it fixes the issue reported:
```
http POST :8001/consumers username=alice
http POST :8001/consumers username=bob
http POST :8001/consumers/alice/acls group=foo
http POST :8001/consumers/bob/acls group=foo
http GET :8001/consumers/alice/acls/foo
http GET :8001/consumers/bob/acls/foo
```
All returning `200`/`201` as expected.
Fix #5280

fix(acl) get acl by group fails when more consumers share the same group

---

kong.conf.default
kong/conf_loader.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua

and allow specifying `backlog=N` options in listener flags
This enables the `reuseport` flag by default, and use a higher `backlog` to help with high traffic servers.
It should have no impact on existing use case, only that server with lots of worker now sees more evenly distributed load and connection across workers. it also reduces issue such as https://discuss.konghq.com/t/concurrent-websocket-connections/4854 from occurring.
Note on the `backlog` value. It is set to a fairly high value `16384` to help handle burst of TCP connections better. The `backlog` is by default set to unlimited on BSD systems and `511` on Linux, which is on the lower end and Kernel can easily handle more connections than that.
However, note that from the man page of `listen`:
> If the backlog argument is …

feat: enable `reuseport` option for Nginx `listen` directive by default

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/policies/init.lua
spec/03-plugins/23-rate-limiting/04-access_spec.lua

This have been previously proposed with #3451 and #2735. This PR tries only to add `Retry-After` header, so it is not as complete as #3451, but it may be easier to get these in as parts.
Thank you @grahamar and @ioggstream for all the previous efforts.
The `Retry-After` is in `seconds`. If there is more than one `Limit` configured and more than one limit has exceeded the `Retry-After` will contain the biggest number (in seconds). E.g. if minute limit is exceeded and hour limit is exceeded it probably means that `Retry-After` will tell you when the hour limit is released assuming that the minute limit will be released earlier.
The PR is also turning on most of the `unit test` suite on `rate-limiting`.

feat(rate-limiting) add support for Retry-After header on 429 response

---

kong/conf_loader.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/04-prefix_handler_spec.lua
spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua

absolute path to avoid relative path resolve issues
For user-friendless reasons. This ensures `lua_ssl_trusted_certificate` is handled similarly like other configs such as `admin_ssl_cert` which already has this check.

feat(core) check the existence of `lua_ssl_trusted_certificate` and use

---

spec/03-plugins/23-rate-limiting/04-access_spec.lua

The state of a previous run may leak into a retry because the tests don't
setup their dependencies in an isolated manner.
Given that all tests use minute counters, a quick solution is to wait for the
minute flip in between the attempt and the retry.
Local testing has demonstrated this to be effective (first-attempt failures
have resulted in successful retries, whereas without it the retries for the
test in line 755 also fail.)

tests(rate-limiting) wait for minute flip when retrying a test

---

kong-1.4.2-0.rockspec

Changelog:
https://github.com/Kong/kong-plugin-acme/blob/master/CHANGELOG.md#020---20191218
Summary:
- Breaking change: this plugin now can only configured as global plugin.
- Add support for dbless mode.
- Add `tos_accepted` to plugin config if using Let's Encrypt.
- Add `domains` to plugin config to include domains that needs certificate.

chore(deps) bump acme plugin to 0.2.x

---

kong/plugins/rate-limiting/handler.lua
spec/03-plugins/23-rate-limiting/04-access_spec.lua

This PR adds support for the following headers specified in
https://tools.ietf.org/html/draft-polli-ratelimit-headers-01:
- RateLimit-Limit
- RateLimit-Remaining
- RateLimit-Reset
For `RateLimit-Limit` this does not implement multiple windows support (I removed it for now):
https://tools.ietf.org/html/draft-polli-ratelimit-headers-01#section-6.2.4
All this work was done by @ioggstream (give him a t-shirt or two!) on
several attempts: #5330 and #3451, and btw. @ioggstream is the author
of that draft rfc, which I hope gets promoted to a proposed standard!
Great stuff! And sure we want to support it.
I (@bungle) gathered the ideas and feedback from the previous PRs
(including #2735) and tried to make all these in a state where we
can agree and merge. I have refactored the code a bit when …

feat(rate-limiting) add support for draft-rfc rate-limiting headers

---

autodoc/data/admin-api.lua
scripts/autodoc-admin-api

Our lists of accepted protocols in the `service` entity was outdated in the 1.4.x documentation.
Instead of fixing it once and risking getting this kind of thing out-of-date again, we now generate the list of accepted values in the documentation, the same way we do for presenting default values.
A [companion PR was sent to the docs repo](https://github.com/kong/docs.konghq.com/pull/1673) with the generated data.

docs(autodoc) generate lists of possible values from `one_of`

---

autodoc/data/admin-api.lua
kong/db/migrations/core/001_14_to_15.lua
kong/db/migrations/core/007_140_to_200.lua
kong/db/schema/entities/routes.lua
kong/plugins/acl/migrations/001_14_to_15.lua
kong/router.lua
spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/01-unit/08-router_spec.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua
spec/02-integration/05-proxy/02-router_spec.lua
spec/fixtures/router_path_handling_tests.lua

> This PR supersedes the previous ones on this topic, see below.
This PR introduces a new Routes attribute called `path_handling`.
It complements #5216 and #5227 by making it possible to select the behavior the router will have when combining the Service path, Route path and the request path into a single path sent to the upstream.
For now `path_handling` accepts two values:
* `"v0"` (the default from now on) makes paths in the router behave like in Kong 0.x (like they did  before #3780)
* `"v1"` makes paths behave like in Kong 1.x (like they did after #3780)
Migrations are adaptive, ensuring that when migrating routes from 0.14.1, they get `path_handling = "v0"`, and when migrating from 1.x, they get `path_handling = "v1"`. This way, routes continue working the same way after a …

feat(router) path handling algorithms, with migrations

---

kong/db/schema/others/declarative_config.lua

Entities defining a field that is a record and abstract fail to be loaded unless they define an empty fields on the record.
* `{ config = { type = "record", abstract = true } }` will try to ipairs through nil.
* `{ config = { type = "record", abstract = true, fields = {} } }` would load fine
For instance, the test schema on https://github.com/Kong/kong/blob/7b8b41508430ad4c63c5ee832c50576623c47e5d/spec/01-unit/01-db/01-schema/01-schema_spec.lua#L1039-L1067 would not work as an entity.
Not sure what would be the better place to add a test for this scenario that is not an integration test so we can hit this function. The unit test on subschemas does not go through `load_plugin_subschemas`.
Also confused about why an entity goes through `load_plugin_subschemas`.
* Default to empty fields …

fix(schema) default entities with empty fields

---

kong/db/strategies/cassandra/connector.lua

See `0.x` commit:
https://github.com/Kong/kong/commit/9beaa6258ae924a766d09bb0e9ddcf44866eb2cc
Testing this is a bit tricky, I tried that, as Cassandra Server needs to support authentication, the original didn't add test, so I guess this might just be alright to be merged.
Fix #5327

feat(migrations) better support for using already existing C* keyspaces

---

.ci/setup_env.sh

`openresty-patches` repo for build and use the new `kong-build-tools` instead

chore(ci) stop using the deprecated `openresty-build-tools` and

---

kong-1.4.2-0.rockspec
kong/reports.lua
spec/01-unit/11-reports_spec.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/api.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/handler.lua

Previously counters in anonymous reports are implemented with shm
counters. Multiple shm operations happen with request, and each
requires shm level lock across all workers. The lock overhead is
especially noticable while running Kong with large amount of cores.
To improve performance, reports now uses [lua-resty-counter](https://github.com/kong/lua-resty-counter).
It replaces per request shm operation with cheaper worker level Lua
numbers and sync to shm timely.
* use lock-free lua-resty-counter in reports

perf(reports) use lock-free lua-resty-counter in reports

---

kong/router.lua
spec/02-integration/05-proxy/02-router_spec.lua

This bug was introduced on `1.3.0` that added header based routing, and was reported in #5371.
Fix #5371

fix(router) longest path routes are no longer matched as expected

---

kong-1.4.2-0.rockspec

Some memory leak issues are identified and fixed
Changelog https://github.com/fffonion/lua-resty-openssl/blob/master/CHANGELOG.md
* bump lua-resty-openssl to 0.4.2

chore(deps) bump lua-resty-openssl to 0.4.2

---

Makefile

Signed daily releases work as follows ( https://github.com/Kong/kong/blob/0cf5bfa2c9ba7b24e52e8904981233b8adce3eac/Jenkinsfile#L199-L208 )
- run setup-kong-build-tools which clones the pinned kong-build-tools repository
- overwrite the empty private key file with one that is securely stored in Jenkins
- run nightly-release
- nightly-release in turn runs release
An unintended side effect of having the `release` step run `setup-kong-build-tools` as a prerequisite is it resets the kong-build-tools directory such that the private key file has been reset to empty

chore(ci) [skip travis] signed centos nightly releases

---

spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua
spec/02-integration/06-invalidations/03-plugins_iterator_invalidation_spec.lua
spec/03-plugins/25-oauth2/02-api_spec.lua
spec/03-plugins/25-oauth2/04-invalidations_spec.lua

Fix test flakiness issue discussed in https://github.com/Kong/kong/pull/5354 (and also make them faster)
As a bonus, speed up the Admin API tests for Certificates too: on my machine, Cassandra tests for it went from 34s to 2.8s (woohoo!)
Aaand while I was waiting for CI to run on other PRs, I sped up the OAuth2 tests too: on my machine, Cassandra tests went from 52s to 27s :+1:

tests(invalidations) use wait to reduce flakiness 

---

kong/db/declarative/init.lua

This print was left over for debugging reasons but leaks all the
sensitive credentials in logs.

fix(declarative) remove a leftover print for security reasons

---

kong/clustering.lua

DP node certificate hash
`CERT_DIGEST` will always be set, this was a leftover from the old
code which also supported unauthenticated connections.

fix(clustering) remove the unnecessary condition for checking the

---

kong/router.lua
spec/02-integration/05-proxy/02-router_spec.lua

When retrieving routes matches from the cache, header matches were being ignored.
Fix #5260
Close #5267

fix(router) do not ignore header-matched routes when retrieving matches from cache

---

kong/db/dao/plugins/go.lua

needed for go-pdk functions that return non-indexable values (i.e: numbers)

fix(go) don't try to check members of non-table results

---

kong/router.lua
spec/02-integration/05-proxy/02-router_spec.lua

Unrelated longer paths were messing with the routing priority, so they must be evaluated alone when choosing by the longest path.
Fix #5418

fix(router) split paths to properly sort for routing priority

---

kong/init.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua

There is a slight edge case reported on #5374. I originally tried to propose a fix to this on my original `async rebuilds` work, but when it was refactored, the fix was dropped out.
The issue is that our `routes:each` / `plugins:each` does actually multiple calls to db, each of which can `yield`, thus making it possible for rows to be added / deleted between different pages of data. This will in some cases make our router invalid.
My original fix used recursive rebuilding, but this new will just terminate the rebuild, which means the router / plugins iterator is not updated, and so the previous one will be used. The next async rebuild or request (non-async) will start a new try.
This is a back-port of for `master` branch:
https://github.com/Kong/kong/pull/5429
See #5374 (might be a fix)

fix(router) detect changes on router/plugins iterator while rebuilding (backported)

---

spec/helpers.lua

To expose TEST_CONF_PATH environment variable
Fix https://github.com/Kong/kong/issues/5269

test(config) expose KONG_SPEC_TEST_CONF_PATH env

---

kong-1.4.3-0.rockspec

Fixes a upstream library bug that will behave incorrectly when
certificate has not_after time later than year 2100.
* Bump lua-resty-openssl to 0.4.3
Fix #5446

chore(deps) bump lua-resty-openssl to 0.4.3

---

spec/02-integration/10-go_plugins/01-reports_spec.lua
spec/fixtures/custom_plugins/kong/plugins/reports-api/api.lua

Extend the reporter-api fixture plugin so it accepts a custom
stats port. Doing so allows tests to select a random port for
the mock stats server, reducing flakiness.
As an example, the tests for Go plugins reports are updated to
leverage this addition and select a random port for its mock
stats server.

tests(fixtures) allow custom port in reporter plugin

---

spec/01-unit/09-balancer_spec.lua

Noticed this when I saw a significant delay in these tests when running these from home, possibly due to my ISP's DNS setup.
This slows down the unit test for the balancer object and is not really the focus of the test.

tests(balancer) do not perform DNS resolution in unit tests

---

kong/router.lua
spec/02-integration/05-proxy/02-router_spec.lua

Paths must be evaluated independently when sorting for route matching.
Fix #5438

fix(router) split paths before marshalling routes

---

kong/db/schema/others/declarative_config.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua

This was reported with #5401. When I added DAO transformations, for some reason I ended up writing stupid code that just broke the whole schema validation on declarative. This commit is an
attempt to fix that. Sorry for all the pain caused.
While fixing this, I also found out that original validation didn't work correctly when you had entity validations that relied on values of foreign keys. This is now also corrected.
Fix #5401

fix(declarative) schema validation in db-less mode

---

kong-1.4.3-0.rockspec

Fixed:
- The IPC module now avoids replaying all events when spawning new workers, and
gets initialized with the latest event index instead.
[#88](https://github.com/thibaultcha/lua-resty-mlcache/pull/88)
Changelog:
https://github.com/thibaultcha/lua-resty-mlcache/blob/master/CHANGELOG.md#241

chore(deps) bump lua-resty-mlcache to 2.4.1

---

kong/runloop/handler.lua

(second try, following first attempt https://github.com/Kong/kong/pull/5478)
Trying to run Kong in Docker image with a limited amount of memory, the following error has been raised:
```
2020/01/20 21:44:18 [alert] 27#0: worker process 27129 exited on signal 9
2020/01/20 21:44:18 [error] 27142#0: init_worker_by_lua error: /usr/local/share/lua/5.1/kong/runloop/handler.lua:97: bad argument #1 to 'log' (bad log level: -1)
[C]: in function 'log'
/usr/local/share/lua/5.1/kong/runloop/handler.lua:97: in function 'update_lua_mem'
/usr/local/share/lua/5.1/kong/runloop/handler.lua:870: in function 'before'
/usr/local/share/lua/5.1/kong/init.lua:565: in function 'init_worker'
init_worker_by_lua:2: in main chunk
2020/01/20 21:44:18 [debug] 27157#0: *99929 [lua] globalpatches.lua:243: …
```

fix(core) Usage of ngx.ERROR instead of ngx.ERR when logging a out of memory

---

kong/init.lua
kong/pdk/ctx.lua

It came to my knowledge that our users have evidenced a following problem:
```
function plugin:access(conf)
kong.ctx.plugin.key = "value"
kong.ctx.shared.cfg = tostring(conf)
end
function plugin:header_filter(conf)
if not kong.ctx.plugin.key then
-- the bug!
end
local cfg2 = tostring(conf)
if kong.ctx.shared.cfg ~= cfg2 then
-- also illustrates reason for a bug!
end
end
```
Before running the plugin (before this PR) we called this:
```
kong_global.set_named_ctx(kong, "plugin", conf)
```
So the `conf` table ended up as a key in `ngx.ctx`, but there are
cases when this `conf` table may change, I believe, between say
`access` and `header_filter` phases. Possible reasons being:
1. new plugin iterator being built between the phases
2. conf table gets cache evicted, and appears again as a new …

fix(pdk) kong.ctx.plugin.* may be flaky

---

kong-2.0.0-0.rockspec

Proxy cache changelog:
- remove api related code from the plugin
- use kong pdk and localize vars
- fix https://github.com/Kong/kong-plugin-proxy-cache/pull/17
- close https://github.com/Kong/kong-plugin-proxy-cache/pull/18

chore(proxy-cache) bump plugin from 1.2 to 1.3

---

kong/init.lua

I am not sure if `go plugins` can currently implement `init_worker` phase (but perhaps they later can), and thus I decided to wrap setting of:
```
ctx.ran_go_plugin = true
```
Inside a check where we actually check that context is available in a first place.

chore(core) go reports context value setting

---

kong.conf.default

Add missing documentation for `stream_listen` `ssl` and `bind` options.

docs(conf) document ssl stream listen option

---

kong/runloop/certificate.lua
spec/01-unit/01-db/01-schema/11-snis_spec.lua
spec/02-integration/05-proxy/06-ssl_spec.lua
spec/02-integration/05-proxy/22-reports_spec.lua

The default certificate for the proxy can now be configured via Admin API using the `/certificates` endpoint. A special '*' SNI has been introduced which stands for the default certificate.
The order in which Kong serves a certificate is:
- Exact SNI match
- Search by prefix wildcard
- Search by suffix wildcard
- Look for a cert associated with the SNI `*`
- The default certificate on file-system
This is an effort in the direction to make Kong more dynamic and minimize static configuration that is put in when the process is started.

feat(runloop) dynamic default certificate

---

spec/02-integration/01-helpers/02-blueprints_spec.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
spec/02-integration/05-proxy/11-handler_spec.lua
spec/02-integration/06-invalidations/03-plugins_iterator_invalidation_spec.lua
spec/02-integration/07-sdk/01-ctx_spec.lua
spec/02-integration/07-sdk/02-log_spec.lua

Some `APIs` related code was still found on our test suite. This PR removes that. APIs were removed on Kong 1.0.

chore(tests) remove api related code

---

kong/runloop/handler.lua
spec/02-integration/05-proxy/03-upstream_headers_spec.lua

`HTTP` `Connection` header usually carries a list of `headers` meant for receiver (in this case proxy) that are not meant to be proxied further (so called hop-by-hop headers). Our gateway correctly cleans these headers, but it was a bit too aggressive.
It turns out as reported on #5465 that websockets upgrade mechanism is broken with Firefox, but works on Chrome. The difference being that Chrome sends following headers:
```http
Connection: Upgrade
Upgrade: websocket
```
while Firefox sends the following:
```http
Connection: keep-alive, Upgrade
Upgrade: websocket
```
As the `Upgrade` was listed on `Connection` header by Firefox, the Kong incorrectly removed the `Upgrade` header from the upstream headers, and thus it made the websockets upgrade to fail. Chrome had only the `Upgrade` header …

fix(proxy) hop-by-hop headers to not clear upgrade header on upgrade

---

kong-2.0.0-0.rockspec

fixes #5477 ,  issues with DNS records having `ttl=0`.
See https://github.com/Kong/lua-resty-dns-client/pull/83 for details

chore(deps) update dns client to 4.1.3

---

kong/db/dao/plugins/go.lua

Allows Go plugins to access the `kong.ctx.shared` table.

feat(go) add getter/setter for `kong.ctx.shared`

---

kong/plugins/datadog/handler.lua
kong/plugins/datadog/statsd_logger.lua
kong/plugins/file-log/handler.lua
kong/plugins/http-log/handler.lua
kong/plugins/loggly/handler.lua
kong/plugins/statsd/handler.lua
kong/plugins/statsd/statsd_logger.lua
kong/plugins/syslog/handler.lua
kong/plugins/tcp-log/handler.lua
kong/plugins/udp-log/handler.lua

Just some choring to make our log plugins use more PDK niceness (especially replaces `ngx.log` with `kong.log`). And while doing so, I changed the code to be more similar across log plugins, and updated a style to match more our current.

chore(log plugins) make log plugins use pdk especially kong.log

---

kong/plugins/ldap-auth/access.lua
kong/plugins/ldap-auth/handler.lua
spec/03-plugins/20-ldap-auth/01-access_spec.lua
spec/03-plugins/20-ldap-auth/02-invalidations_spec.lua

Currently `ldap-auth` does set virtual credential in context on authentication, but that virtual credential does not have `id` which means that rate-limiting plugin cannot rate-limit by the credential, and thus fall-backs to rate-limit by ip.
This commit adds `cache_key` as id for that virtual credential.
Currently `ldap-auth` does seem to use `username` and `password` in a `cache_key` in plain. This is potentially dangerous and may be leaked through it to different places:
- memory
- admin api
- logs
This commit fixes that by calling `sha1_bin` on that when generating a cache key. It also drops the use of `md5`.
Fix #4129

fix(ldap-auth) credential rate-limiting and hashing of cache key

---

kong/error_handlers.lua

`kong.request.get_header("<header-name>")` already always returns a string and never a `table`, and this commit removes those extra and unnecessary checks from Kong error handlers.

chore(error-handlers) no need to check type with kong.request.get_header

---

kong-2.0.0-0.rockspec
kong/plugins/oauth2/daos.lua
kong/plugins/oauth2/daos/oauth2_tokens.lua

Currently oauth2 plugins use access token in plaintext in cache keys.
This can potentially cause the token to appear in debug-level logs
and in Admin API access logs if the cache keys are manipulated
directly via the `/cache/` endpoint.
This commit hashes the cache key extending the `:cache_key` operation
of the DAO for `oauth2_tokens`.
This is hopefully a simpler alternative alternative to #5500.

fix(oauth2) hash oauth2_tokens cache key via the DAO

---

kong-2.0.0-0.rockspec
spec/02-integration/04-admin_api/16-ca_certificates_routes_spec.lua

Fixes #5446
Cherry-pick of #5448, also adding a regression test.

chore(deps) bump lua-resty-openssl to 0.4.3 (#5448)

---

kong/cmd/migrations.lua

Include lua_package_path in the package.path when running migrations.
This ensures that Kong runs migrations for plugins installed in
locations indicated by lua_package_path outside the standard Lua path.
* Update `package.path` with `lua_package_path` locations in `cmd.migrations:execute()`
This was initially discovered while working on https://github.com/Kong/charts/pull/24
The Helm chart mounts all plugin files under `/opt/kong/plugins`. While testing, we observed that plugin files were mounted correctly and that `KONG_PLUGINS` included them, but that no migrations were detected.

fix(migrations) include configured Lua path

---

kong/plugins/oauth2/access.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

Currently the OAuth2.0 plugin is not handling the passing of the empty ```Authorization``` or custom header set with the bearer <access_token> not present. 
* Modify access.lua
* Add 1 related test in 03-access_spec.lua
* ...
Fixes: #5513

fix(oauth2) handle missing token

---

spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua

This tests often returns:
```
[ RUN      ] ...06-invalidations/02-core_entities_invalidations_spec.lua @ 1281: core entities invalidations [#cassandra] Services raises correct number of invalidation events
...06-invalidations/02-core_entities_invalidations_spec.lua:1306: Expected objects to be equal.
Passed in:
(number) 2
Expected:
(number) 1
...06-invalidations/02-core_entities_invalidations_spec.lua:1306: in function <...06-invalidations/02-core_entities_invalidations_spec.lua:1281>
[  FAILED  ] ...06-invalidations/02-core_entities_invalidations_spec.lua @ 1281: core entities invalidations [#cassandra] Services raises correct number of invalidation events (453.24 ms)
[----------] 23 tests from spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua …
```

tests(invalidations) mark test as flaky

---

kong.conf.default
kong/conf_loader.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/09-balancer_spec.lua
spec/01-unit/14-dns_spec.lua
spec/01-unit/16-runloop_handler_spec.lua
spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua

This change adds the option to change upstreams asynchronously, i.e. upstreams will not be updated on every call to Admin API, but rather when a timer expires. This improves the performance when Kong is configured with a large number of upstreams and/or when upstreams are frequently changed.

feat(balancer) async change upstreams

---

COPYRIGHT
scripts/update-copyright

This new script updates the COPYRIGHT file. In order to do that:
* It attempts to download the license files for some basic dependencies (like OpenResty and LuaRocks)
* It installs all the Lua rocks for the current kong rockspec
* It then attempts to download all the license files for said rocks.
This PR also includes an update of the COPYRIGHT file done with the script.

feat(scripts) update copyright

---

kong/plugins/cors/handler.lua

This is a fix for an issue filed as a task/feature at
https://github.com/Kong/kong/issues/4886
Upon closer inspection, this behavior is closer to a bug, and probably
creates unexpected behavior for all users of the CORS plugin.
The plugin logic accounts for all cases where it shuould add an ACAO
header to enable CORS.
- If the plugin is enabled but no allowed domains are defined, ACAO: *
- If allowed domains =  *, ACAO: *
- If one or more specific domains/regexes is defined and request Origin
header matches, ACAO: <request Origin header value>
However, if (and only if) a specific list of domains is defined and the
request Origin header FAILS to match, then the upstream header is passed
through. If your upstream server returns ACAO: *, there is no way to
implement a more restrictive CORS …

Remove upstream ACAO header if no match is found

---

Jenkinsfile

- name the next and master packages with their respective branches so they don't conflict on bintray
- adjust src, alpine and amazon nightly releases so they don't land in the official release repository

chore(nightly) fix the nightly release repository and package names

---

spec/02-integration/05-proxy/19-grpc_proxy_spec.lua

Add tests for gRPC streaming responses and requests.  They do work in the sense that all content is passed as expected and in order.
The requests are buffered, so the service doesn't receive any content until the last message is sent by the client.  This could broke an application that depends on a "ping-pong" behaviour during a single RPC call.

tests(grpc) verify streaming methods

---

kong/router.lua
kong/runloop/certificate.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/06-ssl_spec.lua

The `stream_lua` per-connection doesn't exist yet during
`ssl_certificate_by_lua` phase. As a result saving the SNI into the
`ngx.ctx` object wouldn't preserve into later phases, causing SNI
routing failure.
This PR uses the `ngx.ssl.server_name` method to obtain the SNI
`server_name` instead which is guaranteed to work in the later phases.
Thanks @hbagdi for the report!

fix(proxy) fix broken SNI based routing in L4 proxy mode, closes #5501

---

Makefile

https://github.com/Kong/kong-build-tools/compare/3.0.0...3.1.0
- logrotate support
- systemd reload bug fix
- fix broken rpm builds

chore(dependency) bump the ci build dependency pin

---

kong/db/strategies/cassandra/connector.lua

fixes https://discuss.konghq.com/t/kong-pongo-hangs-with-kong-plugin/5517/9
The patch in use allows Cassaandra contactpoints to be resolved in the init phases, but did not patch the `settimeout` method. In OpenResty is uses milliseconds, but in LuaSocket it uses seconds. This ended up that the default timeout of 2000ms turned into 2000s (appr. 33 mins).
This fix will also convert the timeouts to the proper units.

fix(cassandra) use proper units for timeouts

---

Makefile

kong-build-tools bump so the release doesn't fail because of a postgres docker image change https://github.com/Kong/kong-build-tools/pull/224
Full diff https://github.com/Kong/kong-build-tools/compare/2.0.9...2.3.2
The other changes are noop and some fixes with the exception of:
- introducing systemd but that change is backwards compatible
- remove service mesh patches for 1.15.8.2

chore(dependency) bump the kong-build-tools dependency so daily tests pass

---

spec/02-integration/05-proxy/04-plugins_triggering_spec.lua

The file spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
is currently taking 20s waiting for timeouts (5s timeouts across 4 tests).
By closing the client connections right away, the tests proceeed immediately.
This shaves 20s off each run of this file (for a single database strategy).

tests(proxy) speed up plugin triggering tests

---

kong/constants.lua
spec/01-unit/12-plugins_order_spec.lua

Out-of-tree plugins bundled by default are also enabled by default. The Acme plugin was recently bundled to Kong, but not enabled by default.

fix(plugins) enable acme by default

---

kong-2.0.1-0.rockspec
kong/runloop/balancer.lua
spec/01-unit/09-balancer_spec.lua
spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua

When I post the health explicitly via the Admin API (/upstreams/U/targets/T/healthy) the health status is updating in only one worker (giving me flappy results in the Admin API response as workers become inconsistent).
I'm tracking down the problem and I found some inconsistencies: the `post_health` operation calls straight into the balancer of the worker that responded to the Admin API call to update it and then propagates health via `cluster_events` only, skipping `worker_events` altogether. At first I thought this was the problem, but as I went hunting down I found a comment in `balancer.post_health` code that says `-- Update health status and broadcast to workers`, so using `cluster_events` only _should_ have worked.
The issue then is that, when healthcheck-by-address was introduced, …

fix(healthchecks) fix propagation of posted health across workers

---

Makefile

A single change in this kong-build-tools release to fix a failing postgres test https://github.com/Kong/kong-build-tools/pull/225

chore(dependency) bump a dependency to fix postgres tests in ci

---

autodoc/data/admin-api.lua
scripts/autodoc-admin-api

Our check for missing endpoint documentation was checking for
missing _entity_ documentation only, and not to the general
files such as `kong/api/routes/kong.lua`.
This commit:
* adds the check to those files
* adds the missing documentation so that the check passes
* removes a deprecated endpoint (which is now documented in
the non-deprecated style)

docs(admin-api) check for and add documentation to missing endpoints

---

kong-2.0.0-0.rockspec

Bump lua-resty-openssl to 0.5.3.
Needed by https://github.com/Kong/lua-kong-nginx-module/pull/11
and https://github.com/Kong/kong/issues/5549
Full changelog https://github.com/fffonion/lua-resty-openssl/compare/0.4.3...0.5.3
* Bump lua-resty-openssl to 0.5.3 to support x509 store functions and lua-resty-hmac compat mode.
Fix #5549

chore(deps) bump lua-resty-openssl to 0.5.3

---

kong/api/routes/cache.lua
spec/fixtures/balancer_utils.lua

invalidation on Kong instance 2 after route update on Kong instance 1
Also make sure the `DELETE /cache/<cache_key>` invalidates both core
and user facing cache, just like `DELETE /cache`
This should make `next` run consistently green. Before it was like this: https://travis-ci.org/Kong/kong/builds/653089923?utm_source=github_status&utm_medium=notification
We are tracking the router rebuild issue in the particular test setup elsewhere, as it is not related to the balancer tests in any way.

tests(balancer) reduce the flakiness of the test suite by forcing router

---

Jenkinsfile

There's only two conditions in which Jenkins should be doing anything
Release:
- run from SCM don't run from cron
Nightly Release:
- run from timer don't run from SCM
- only run on master and next
SCM push to next / master is a noop
cron event runs build, test and nightly release stages
SCM tag runs build, test and nightly release stage also the tag doesn't attempt to re-run every 24hrs

chore(ci) make sure tags dont get built by the nightly cron

---

kong/clustering.lua

CRUD events generated by Admin API may not be propagated to other
workers correctly, causing sync delays
Note: I manually tested this locally by running 12 workers for the CP and make Admin API changes, each change now generates 12 log entry with different PIDs for each, which means all the workers received the event correctly.
```
2020/02/25 09:03:10 [debug] 5191#0: *7056 [lua] clustering.lua:309: push_config(): config pushed to 1 clients
2020/02/25 09:03:10 [debug] 5200#0: *7057 [lua] clustering.lua:309: push_config(): config pushed to 0 clients
2020/02/25 09:03:10 [debug] 5196#0: *7058 [lua] clustering.lua:309: push_config(): config pushed to 0 clients
2020/02/25 09:03:12 [debug] 5197#0: *7167 [lua] clustering.lua:309: push_config(): config pushed to 0 clients
2020/02/25 09:03:13 …
```

fix(clustering) fix an issue that when running CP with multiple workers,

---

kong/runloop/plugins_iterator.lua

When using declarative configuration, the cache object holding the plugin configs doesn't
seem to call the `load_plugin_from_db()` function.  (maybe it's preloaded some other way?)
This makes they never get the full DB key injected in the config, so the
`go.get_instance()` function falls back to using just the plugin name as the key to the
instance ID table.  Hilarity ensues.
This patch moves the injection of the `__key__` and `__seq__` fields from the
`load_plugin_from_db()` function to the outer `load_configuration()` function, so it works
on any DB strategy.
fix: https://discuss.konghq.com/t/the-go-plugin-may-not-work-right/5545

Bugfix: instances of same go-plugin on different routes get mixed.

---

.ci/setup_env.sh
.travis.yml
kong/pdk/response.lua
t/01-pdk/08-response/11-exit.t

In L4 proxy mode, some of the features in here makes little sense. Such
as the JSON encoding support and `headers` argument. Therefore they have been removed.
Also, I have been looking at the way `kong.response.exit` is used right now in Kong code, and it appears that the `5xx` errors are the most problematic for returning directly to the client as they usually contain textual error message most certainly makes no sense to L4 protocol. Therefore, for `5xx` errors we log them to the error log file before simply close the downstream connection.
Feedbacks or comments are welcomed!

feat(pdk) support `kong.response.exit` method for L4 proxy mode

---

kong-2.0.1-0.rockspec

Clean an extra error log when jwt plugin is applied on a service
which connects to https upstream.
* Bump up lua-resty-openssl to 0.4.4
Fix #5614
This commit should only goes to 2.0.x releases, if there's any. In `next` we already have used lua-resty-openssl 0.5.3 which includes this patch.

chore(deps) bump lua-resty-openssl to 0.4.4

---

.ci/run_tests.sh
.ci/setup_env.sh
.travis.yml

Use https://github.com/hishamhm/busted-htest as a default for shorter and nicer-looking test outputs in CI.

tests(*) use busted-htest for shorter color output

---

.ci/setup_env.sh
Makefile

Make sure we load the htest handler for runs via the Makefile, which is agnostic to the CI environment, instead of setup_env.sh, which is specific to Travis.

chore(ci) load htest output handler in the Makefile

---

.travis.yml
spec/03-plugins/10-basic-auth/03-access_spec.lua

The `lint` target performs additional checks on the codebase.

 chore(ci) use 'make lint' for linting instead of luacheck only 

---

kong-2.0.2-0.rockspec
kong/clustering.lua
kong/tools/utils.lua
spec/01-unit/05-utils_spec.lua

Thanks to some quick benchmark work by @fffonion, it it clear that the declarative config can be easily compressed to achieve a much smaller footprint.
According to data provided by @fffonion :
Before Gzip, 1000 Service/Route pairs resulted in a JSON that is 560KB. After Gzipping that size is reduced down to 11KB. Obviously test data has a lot of redundancies, but even for random data a size saving of ~50% can still be achieved, which makes Hybrid mode sync faster and consumes less bandwidth.
Also we bumped the maximum payload size to 4MB, with Gzip that should easily allow tens of thousands of Service/Route pairs which should be sufficient for most of the user's requirments.

perf(clustering) use Gzip when transferring and saving declarative configurations

---

kong-2.0.2-0.rockspec

- altname: RFC822 alias to email 37467fc
- bn: mathematics, bit shift and comparasion operations 87bf557
- kdf: use give id as type parameter 0e767d0
- kdf: kdf.derive in luaossl compat mode 45788b6
- kdf: add key derivation functions support d78835e

chore(deps) update lua-resty-openssl from 0.5.3 to 0.6.0

---

kong/pdk/request.lua
kong/runloop/handler.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/03-upstream_headers_spec.lua
spec/fixtures/custom_nginx.template
t/01-pdk/04-request/00-phase_checks.t
t/01-pdk/04-request/18-get_forwarded_path.t

Kong currently adds these headers to upstream request:
```
X-Forwarded-For
X-Forwarded-Port
X-Forwarded-Proto
X-Forwarded-Host
X-Real-IP
```
@erikgb mentioned that he would like to have `X-Forwarded-Prefix`
added on #5602.
This PR adds that, and additionally introduces a new PDK function:
```lua
local path = kong.request.get_forwarded_path()
```
Close #5602

feat(proxy/pdk) add support for X-Forwarded-Prefix

---

kong/api/routes/certificates.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua

If you send multiple `SNIs` as body argument AND also an `SNI` on URL matching one of the `SNIs` in body, it leads to `sni is duplicated` error.
This bug was introduced with #5321, so it affects Kong 1.5+ (including 1.5).
This PR fixes the issue and the duplicate is not reported anymore as an error (url SNI is only appended to `snis` if not already found on `snis`).
Fix #5652 (at least partly)

fix(admin) PUT on certificates could error with sni is duplicated

---

spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua

increase the `assert.near` so the test is more reliable
ran the test in a loop for ~30 minutes without a failure

test(least-connection) fix the least-connection test to be more reliable

---

kong/error_handlers.lua

Create new header tables before passing them to `kong.response.exit()`. The exit-transformer plugin can modify these tables, and the current pass by reference allows those modifications to persist for other requests on the same worker.
* Create new header tables before passing them to `kong.response.exit()` in error handler.
* Remove existing module-level header tables.
Fix an issue where modifying the `headers` variable in exit-transformer functions resulted in unrelated requests seeing the same header modification.

fix(errors) use new header tables in error handler

---

kong/cache_warmup.lua
kong/constants.lua
kong/runloop/handler.lua
spec/01-unit/01-db/08-cache_warmup_spec.lua

TLDR; Moves `consumers` and `tags` on cache warmup from `kong.core_cache` to `kong.cache`.
It was found out that our plugins in general tend to call `kong.cache:get`, and they never use `kong.core_cache:get`. This is also for historical reasons as we didn't have `core_cache` before recently. When we did the split we did put so called `core entities` into `core_cache` on cache warmup. This included things like `consumers` and `tags` too. But we didn't change the
plugins. The common case for authentication plugins was to fetch consumers from `kong.cache:get` while the warmup now warmed them up in `kong.core_cache`. Thus the entities weren't warmed up in a right cache from plugin perspective.
In #5665 it was proposed to fix this by changing `key-auth` plugin to use `core_cache`. I personally …

fix(cache-warmup) move consumers and tags from core cache to cache

---

kong/plugins/log-serializers/basic.lua
spec/01-unit/10-log_serializer_spec.lua

Replace the value of the `Authorization` header with `REDACTED` in the basic serializer.
* Updated the basic serializer to replace the value of the `Authorization` header with the string `REDACTED` if present. This still indicates whether the client sent the header while not recording the actual credential in the log system.
* Update serializer unit tests to confirm this behavior and use a more realistic header table.
As this is technically a new feature, and modifies existing existing functionality, PRing to next, though I think we could reasonably apply it to master and count it as bugfix instead depending on whether we think anyone relies on the existing behavior here (I don't think anyone should). The diff applies equally on either.
Including the actual value of `Authorization` is …

Strip Authorization value from logged headers

---

kong-2.0.2-0.rockspec

Sync up with latest release, contains:
- Enable the enterprise encryption of aws secrets.

chore(deps) update aws lambda plugin from 3.1 to 3.2

---

autodoc/data/admin-api.lua
scripts/autodoc-admin-api

This change on the autodoc for the Admin API improves legibility on the Admin API headers and tables. 
This has a sister PR in https://github.com/Kong/docs.konghq.com/pull/1851

docs: admin api headers

---

kong-2.0.2-0.rockspec
kong/db/schema/typedefs.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/ip-restriction/schema.lua
spec/03-plugins/17-ip-restriction/01-schema_spec.lua
spec/03-plugins/17-ip-restriction/02-access_spec.lua

Add IPv6 support for the ip-restriction plugin.
Looking for feedback so I can see if it would be a good idea to replace the 'lua-resty-iputils' and 'lua-resty-mediador' libraries by the 'lua-resty-ipmatcher' one.
The iputils lib is only used for typedef validations and the mediador lib is used for trusted ips on the pdk side and for sources and destinations on the router side.
- [feat(ip-restriction) add support for IPv6](https://github.com/Kong/kong/pull/5640/commits/fb76a01bfcea55e50353402204be6b2c62eebd3a)

feat(ip-restriction) add support for IPv6

---

kong/init.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua

The plugin iterator builds the list of plugins. If the first plugin errors on plugins iterator build on access phase there is a chance that the plugins iterator may not be built completely. E.g. it might be missing all the log plugins. This PR delays the response so that the plugins iterator will still be fully built.
It basically also allows plugins to do:
```lua
if err then
return error(err)
end
```
instead of:
```lua
if err then
kong.log.err(err)
return kong.response.exit(500, { message = "An unexpected error occurred" })
end
```
Or that those two are the `same`.
In separate commit I also changed the plugins to use `error(err)`, but I decided to move that to another PR: #5696.
@Tieske, isn't this what you suggested at some point?

fix(proxy) the plugins might not be fully collected on error on one plugin

---

kong/plugins/acl/handler.lua
kong/plugins/basic-auth/access.lua
kong/plugins/hmac-auth/access.lua
kong/plugins/ip-restriction/handler.lua
kong/plugins/jwt/handler.lua
kong/plugins/key-auth/handler.lua
kong/plugins/ldap-auth/access.lua
kong/plugins/oauth2/access.lua
kong/plugins/rate-limiting/handler.lua
kong/plugins/response-ratelimiting/access.lua

Makes plugins to do:
```
local ok, err = func()
if not ok then
return error(err)
end
```
instead of:
```
local ok, err = func()
if not ok then
kong.log.err(err)
return kong.response.exit(500, { message = "An unexpected error occurred" })
end
```
This PR is a continuation of #5692 (this is applied to `next` so that when #5692 is merged to master, that needs to then be merged to next, so please not merge this until then).

refactor(plugins) use error(err) instead of kong.response.exit on 500 errors

---

kong/db/dao/targets.lua
spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua

When cleaning up targets history, the last existing one could be removed and then the upstream would be empty and also removed.
Fix #5593

fix(dao/targets) don't remove the last target in history

---

Makefile

release notes here https://github.com/Kong/kong-build-tools/releases/tag/4.1.0
full diff https://github.com/Kong/kong-build-tools/compare/4.0.1...4.1.0
Notable change is "openresty-patches: add OpenResty 1.15.8.3 patches"

chore(dependency) bump the KBT dependency so we get the openresty patches

---

.ci/run_tests.sh
.ci/setup_env.sh
.github/workflows/build_and_test.yml
.travis.yml
Makefile
spec/01-unit/02-rockspec_meta_spec.lua
spec/02-integration/05-proxy/05-dns_spec.lua

This commit makes Kong able to run on GitHub Actions, but still kept the
Travis CI files around so that we could use both at the same time during
the transitional period. Eventually Travis CI support will be removed.
This PR further splits Kong core integration tests into two halves on
GitHub Actions to further reduce the run time by utilizing all the
concurrency we have access to, as the core integration tests has
consistently been the long tail of all the jobs, running 2x slower than
the second slowest job. Splitting is not done on Travis as the
concurrency limit makes doing so pointless.
Todo:

chore(ci) github actions via kbt

---

kong-2.0.2-0.rockspec
kong/plugins/oauth2/access.lua
kong/plugins/oauth2/daos.lua
kong/plugins/oauth2/migrations/004_200_to_210.lua
kong/plugins/oauth2/secret.lua
spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/03-plugins/25-oauth2/02-api_spec.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

This was originally implemented with #4866 by @janza.
After some review comments, and the introduction of DAO transformations, I decided to make changes, thus opening this new PR.
This PR adds a new `boolean` column `hash_secret` to `oauth2_credentials` that is used to determine whether or not the `client_secret` will be hashed.
The PR adds support for `pbkdf2` (and contains code for `argon2`, and `bcrypt` if we want to enable them later). The plugin will also check if the `client_secret` needs to be rehashed (on usage). One caveat. If you run this on cluster and some nodes have `argon2` and some don't, it is possible that you cannot use the credentials on those that don't. So keep your environments similar.
Close #4866, Fix #1237 (at least on OAuth2)

feat(oauth2) optionally hash client secret

---

kong-2.0.2-0.rockspec

- Change: export DNS source type on status report.
See [PR 86](https://github.com/Kong/lua-resty-dns-client/pull/86).

chore(deps) bump lua-resty-dns-client from 4.1.3 to 4.2.0

---

kong-2.0.2-0.rockspec

- Minor update
- Allow for TLS v1.2 when using LuaSec (Miles Elam)

chore(deps) bump pgmoon from 1.10.0 to 1.11.0

---

kong/runloop/balancer.lua
spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua

This was previously in #5712 
The added field will contain the report as created by the balancer, containing the balancer structure (targets, addresses, statusses, etc.).
This includes number of resolved addresses, DNS results, and record types.

feat(dns) export more data for balancer health

---

kong/runloop/balancer.lua

When there are a large number of upstreams in the database or the database is under heavy load, loading upstreams will take longer and, sometimes, unacceptably longer. This change addresses said issue by keeping the stale cache until the new data is loaded from the database. As there might be stale content with this change, this behavior only exists when worker consistency is set to eventual.

perf(balancer) load upstreams before cleaning cache

---

Makefile

full diff https://github.com/Kong/kong-build-tools/compare/4.1.0...4.2.2
notable change is openssl is migrating their asset location

chore(dependency) bump the kong-build-tools dependency

---

Jenkinsfile

in order to push daily and unofficial images to docker hub we need to login to docker
I tested these changes here: https://internal.builds.konghq.com/blue/organizations/jenkins/kong/detail/chore%2Fforce-jenkins-daily-release/13/pipeline/

chore(release) login to docker hub to push daily and unofficial tagged images

---

.ci/run_tests.sh

Pongo has the option to use Squid as a test dependency (a forward
proxy). This is used by some plugin tests, but not supported in
the Kong CI tests. Hence we need to exclude those tests.

chore(test) exclude 'squid'-tagged tests

---

kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/03-typedefs_spec.lua

Schema.define used `not value` where it should have used `value == nil`.

fix(schema) allow boolean `false` overrides with Schema.define

---

Makefile

Cherry-pick of https://github.com/Kong/kong/pull/5747
> full diff https://github.com/Kong/kong-build-tools/compare/4.2.1...4.2.2
> notable change is openssl is migrating their asset location

chore(dependency) bump the kong-build-tools dependency (#5747)

---

kong/db/schema/others/declarative_config.lua

fails schema validation
When a declarative config fails schema validation, we attempts to
re-load the config again after populating the foreign keys
(see `kong.db.schema.others.declarative_config.flatten`).
Inside `flatten` we call the `kong.db.schema.others.declarative_config.load`
function, which reloads the schema objects and insert them into
the `all_schemas` global table without first clearing it.
The result is that the `all_schemas` table will keep growing
indefinitely and eventually causes Nginx to be OOM killed.
This PR attempts to fix the issue by clearing the `all_schemas` table
every time `load` is called, which according to my test indeed prevents
the memory from leaking anymore.
closes #5732

fix(declarative) fix memory leaks when loading a declarative config that

---

kong/runloop/balancer.lua

instead of the balancers creating logs like `[balancer 1]`, a balancer create from upstream `myupstream` will now log with a prefix `[upstream:myupstream 1]` making correlating the logs a lot easier.
The default for `log_prefix` is `"balancer"` but was never set/overridden by Kong.

fix(balancer) set a proper log prefix with upstream name

---

kong/db/declarative/init.lua
spec/02-integration/02-cmd/03-reload_spec.lua

The cache must be purged before loading to prevent that removed entries are kept in the database after a reload.
Fix #5705

fix(declarative) purge cache before loading

---

kong/conf_loader.lua
kong/reports.lua
kong/templates/kong_defaults.lua
spec/01-unit/11-reports_spec.lua

Add a `kic` configuration setting for reporting purposes. This is not documented in kong.conf.default, as we don't intend for users to set it manually. It should only be set by our Kubernetes tooling.
* Add `kic` configuration, default `off`.
* Add `kic` to reporting data.
* Add tests for reporting.

feat(config) add "kic" configuration for reporting

---

kong-2.0.3-0.rockspec
spec/fixtures/hosts

NOTE: this can only be merged after updating the Lambda plugin to a newer version than 3.2.0.

Remove fixture for Lambda + bump version

---

kong-2.0.3-0.rockspec

- optimize: use `table.clear` to clear table object.
- optimize: local cache.
- change: compat mode for `table.clear` .

chore(deps) bump lua-resty-counter from 0.2.0 to 0.2.1

---

kong-2.0.3-0.rockspec

backward compatible release. Adds functions for other phases than access.
(major bump is only to indicate feature complete and start of SemVer)

chore(deps) bump serverless-functions to 1.0.0

---

kong/runloop/certificate.lua

The loop inside this function can trigger a trace restart that results
in a wrong value in the local index variable.   (#5748)
until this is fixed in LuaJIT, disabling JIT for this function
avoids the problem.

fix(cache) disable JIT mlcache:get_bulk() on ARM64

---

kong/db/declarative/init.lua
kong/init.lua
kong/templates/nginx_kong_stream.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/02-integration/05-proxy/01-proxy_spec.lua
spec/fixtures/custom_nginx.template

socket
Currently, the stream subsystem receives the declarative config from
the filesystem only. Once Kong is running, updating the declarative config
through `/config` admin API no longer propagates to the stream
subsystem. In the long term we will have shared shdict between `http`
and `stream` subsystem which solves the problem. However this PR
provides a temporary and clean solution for getting around the issue without
introducing new OpenResty patches, and can be reverted in the future
easily once situation changes.
Fixes #5656

fix(declarative) send config updates to stream subsystem via Unix domain

---

Jenkinsfile

AWS is having challenges with providing functioning ARM hardware. This change will allow other builds to continue even if the Ubuntu Xenial arm build fails

fix(release) let the release continue even if parts of it fail

---

kong/conf_loader.lua
spec/01-unit/03-conf_loader_spec.lua

`.kong_env` file
Doing so could cause failures such as ones described in #5761, where a
value of `"!abCDefGHijKL4\#1MN2OP3"` was first transformed to
`"!abCDefGHijKL4#1MN2OP3"` and written to `.kong_env`. If we apply
transformation to `"!abCDefGHijKL4#1MN2OP3"` again when loading from
`.kong_env`, then it becomes `"!abCDefGHijKL4` which results in
different value used by the CLI and worker.
fixes #5761

fix(conf_loader) do not apply additional processing when loading from

---

kong/pdk/response.lua

When flushing delayed responses, if there was a body encoding error, the request's processing continued and unexpected errors could show up. This change stops the request's processing, returning a 500 status.

fix(pdk) stop request processing on body encoding error

---

kong/runloop/balancer.lua

Issue #5455 reports Kong instances getting stuck with DNS resolution errors when using Kubernetes Ingress Controller.  In those cases, the DNS query won't work, but it should've been resolved first by the `get_balancer()` function.
Since this function can't be called at `balance` phase, if it didn't work earlier (at `access` phase), there's no other option than reporting failure.  It seems that there's some intermittent failure on reading the upstreams list, and once it returns an empty list, it's stored in the cache.
This patch avoids saving in the cache an empty upstream list, in the hope that a subsequent query will find the real content.
Fix #5455

fix(balancer) don't cache an empty upstream name dict

---

autodoc/data/admin-api.lua

most pressing issue: example of array usage on the command line

docs(admin-api) add examples using arrays

---

Makefile

cherry picking https://github.com/Kong/kong/pull/5830
patch bump of Kong build tools
[full changelog](https://github.com/Kong/kong-build-tools/compare/4.3.1...4.3.2)
notable change: Nuke the previous Kong source to avoid cache collissions https://github.com/Kong/kong-build-tools/pull/265

chore(dependency) bump the kong-build-tools dependency (#5830)

---

kong/db/declarative/init.lua
kong/init.lua

the correct config page is purged during load
The issue is only present when Kong is running with multiple workers.
Use #5789 as an example, the following events happens:
1. A new declarative config is uploaded via the Admin API
2. Kong is on cache page 2, `kong.core_cache:purge()` is called without
the shadow flag, causes the page `1` to be purged immediately
3. New config is loaded into page 1
4. Kong switches to use page 1, then page 2 is purged immediately.
The switch to use page 1 is not immediate and some
workers may keep using the now empty page 2 for a short period of time. This may cause
page 2 to be poisoned with an incorrect negative match. Which for #5789,
is the `sni:example.com` for looking up certificate matches. This
will cause `sni:example.com` to forever return `false` …

fix(declarative) fix race condition when reloading config by making sure

---

kong/cache.lua
kong/db/declarative/init.lua
spec/02-integration/11-dbless/01-respawn_spec.lua
spec/helpers.lua

When worker respawns under DB-less mode, the `core_cache` is always uses
the first cache page. If the current page in use is the second page,
then the newly spawned worker will not be getting the correct view of
the configurations, causing undefined behaviors such as unexpected 404s
in router. This commit saves the `core_cache` page information inside
`shdict` so that new workers can always find the correct page to use.
fix #5799

fix(declarative) use correct cache page when worker respawns

---

Makefile

Our `make dev` "uninstall and then reinstall" phase makes it a bit
unfriendly to certain build systems (like pongo) which prefer to use
`make dependencies` instead.
One difference between `make dev` and `make dependencies` is
that the former installs grpcurl, but not the later.
This change moves the installation of grpcurl to `make dependencies`,
so it becomes "like `make dev` but without uninstalling and reinstalling".

chore(makefile) make grpcurl part of dependencies

---

kong/db/dao/init.lua
kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua
spec/01-unit/01-db/04-dao_spec.lua
spec/02-integration/04-admin_api/18-worker-events.lua
spec/fixtures/custom_plugins/kong/plugins/worker-events/handler.lua
spec/fixtures/custom_plugins/kong/plugins/worker-events/schema.lua

I know this is controversial. But It turns out that currently with `upsert` the invalidations do not send the `old entity`, while in _most_ (I think it always should) cases with `update` it does so.
Because there is `old_entity` in `update` (which `upsert` uses too) invalidations and we do have code that relies on it and perhaps 3rd party code in plugins that relies on it, this commit changes our DAOs so that `read-before-write` is always enabled for `update` and `upsert`.
This is for correctness (even when it might mean race condition between read and write). And bugs caused by not having this commit are really hard to investigate. I know that we tried hard to avoid `read-before-write` especially with Cassandra, but we also have had to loosen that and more and more code already does …

fix(db) read-before-write always on updates and upserts

---

kong-2.0.4-0.rockspec

- Fix Kong storage adapter to use `regenerate` strategy.
- Bumps `lua-resty-session` to `3.3`.

chore(deps) bump session plugin from 2.3.0 to 2.4.0

---

.ci/setup_env.sh

This PR ensures kong-build-tools and go-pluginserver are properly cached and their pinned versions are honored. Previously to this, they were being cloned into $DOWNLOAD_ROOT, which is not cached by CI -- only $INSTALL_ROOT is.
**NOTE**: please make sure to **squash and merge, fixing commit message**.

fix(ci) properly pin and cache kong-build-tools and go-pluginserver

---

.ci/setup_env.sh

This PR ensures kong-build-tools and go-pluginserver are properly cached and their pinned versions are honored. Previously to this, they were being cloned into $DOWNLOAD_ROOT, which is not cached by CI -- only $INSTALL_ROOT is.
This is a cherry-pick from the master branch.

fix(ci) properly pin and cache kong-build-tools and go-pluginserver (#5882)

---

spec/02-integration/05-proxy/22-reports_spec.lua
spec/helpers.lua

rename 'errlog' modifier, fix a bad example and added reference
and example usage

chore(docs) update docs for helpers

---

kong-2.0.4-0.rockspec

- Change `luaossl` to `lua-resty-openssl`
- fix: do not validate region name against hardcoded list of regions
- feat: add `host` configuration to allow for custom Lambda endpoints

chore(deps) bump aws-lambda plugin to 3.4.0

---

kong/db/schema/init.lua
spec/02-integration/03-db/11-db_transformations_spec.lua
spec/fixtures/custom_plugins/kong/plugins/transformations/daos.lua
spec/fixtures/custom_plugins/kong/plugins/transformations/handler.lua
spec/fixtures/custom_plugins/kong/plugins/transformations/migrations/000_base_transformations.lua
spec/fixtures/custom_plugins/kong/plugins/transformations/migrations/init.lua
spec/fixtures/custom_plugins/kong/plugins/transformations/schema.lua

This fixes issue when trying to merge master to next. The problem is because `next` now has read-before-write on updates, but it also added oauth2 credentials transformation and related tests. One of those tests starts to fail if trying to merge master to next. The test itself is fine.
The problematic test is this:
https://github.com/Kong/kong/blob/next/spec/03-plugins/25-oauth2/02-api_spec.lua#L522-L540
```lua
it("updating client_secret requires hash_secret", function()
local res = assert(admin_client:send {
method  = "PATCH",
path    = "/consumers/bob/oauth2/" .. credential.id,
body    = {
client_secret = "test",
},
headers = {
["Content-Type"] = "application/json"
}
})
local body = assert.res_status(400, res)
local json = cjson.decode(body)
assert.same({
["@entity"] = {
"all or none of …
```

fix(schema) transformation validation is skipped when it should not

---

kong-2.0.4-0.rockspec

- uses `lua-resty-openssl` instead of `luaossl` fixes kong start issue
with `next` packages.

chore(deps) bump kong-lapis to from 1.8.1.1 to 1.8.1.2

---

kong.conf.default
kong/cmd/utils/prefix_handler.lua
spec/01-unit/04-prefix_handler_spec.lua

- Adds a test for `nginx_main_worker_rlimit_nofile=auto` and
`nginx_events_worker_connections=auto`
- Adds documentation for `nginx_main_worker_rlimit_nofile=auto` and
`nginx_events_worker_connections=auto`
- Renames some variables to avoid further confusion

chore(conf) worker_rlimit_nofile & worker_connections "auto" == max 16384

---

Makefile

Full changelog: https://github.com/Kong/kong-build-tools/compare/4.3.2...4.3.6
- add zlib as a dependency
- docker-kong compatibility adjustments
- go version pinning

chore(deps) bump the kong-build-tools dependency

---

kong/globalpatches.lua
spec/02-integration/04-admin_api/15-off_spec.lua

When Kong parses a declarative config, and when the declarative config
has a lot of entities and one of the high index entity has validation
errors, Kong may generate a JSON response message like this:
```
plugins = {
[12] = {
<schema errors>
}
}
```
Unfortunately this causes the lua-cjson library to throw the
"Cannot serialise table: excessively sparse array" error. This PR
increases the limit of cjson so that these error won't happen with small
number of configurations.
fixes #5768
For discussion:
Is this the best way to solve it? cJSON provides another mode for dealing with excessively sparse arrays which is to convert numeric indices to hash tables. See: https://www.kyne.com.au/~mark/software/lua-cjson-manual.html#encode_sparse_array. That way we would never fail to encode the JSON …

fix(globalpatches) increase the limit when encoding sparse array in Kong

---

kong/global.lua
kong/pdk/ctx.lua
kong/pdk/init.lua
kong/pdk/log.lua
t/01-pdk/05-client/09-load-consumer.t
t/02-global/02-set-named-ctx.t
t/02-global/03-namespaced_log.t

This PR replaces #5851 because it provides a more robust implementation and fixes several other issues.
* Store namespace keys in `ngx.ctx` to ensure all dynamically generated namespaces are isolated on a per-request basis.
* Introduce a new global API (which is a private API for use by core only) to explicitly delete a namespace.
A note on the benefits of this new implementation compared to #5851:
* By using a table to keep track of namespaces in `ngx.ctx`, we ensure that users of `ngx.ctx` cannot access the table namespaces, thus properly isolating it and avoiding polluting `ngx.ctx` for core and/or plugins. We can think of it as a double-pointer reference to the namespace. Each request gets a pre-allocated table for 4 namespaces (of course not limited to 4), with the assumption that …

fix(pdk) ensure 'kong.ctx.plugin' and 'kong.log' are light-threads safe

---

kong/db/schema/entities/targets.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

The loadbalancer will honour SRV provided weights, and hence it makes sense for Kong to support the same range.
The "weight" range for targets was 0-1000, as enforced by Kong. The balancer will take those, and in case of an SRV it will override the given weights with the values retrieved from the SRV record (reason: Kong trusts the DNS server).
Now since SRV records have a 2-byte weight setting (0-65535), it would pick up a weight of 65535, if given in an SRV record, despite that the target definition only allows up to 1000.
Hence it makes sense for targets to also allow 0-65535 as a range.

chore(targets) allow weight 0-65535 to match SRV records

---

kong-2.0.4-0.rockspec
kong/runloop/balancer.lua

Breaking change in lib is: if the "target" was an IP, then it will
no longer be returned as `host`, but `nil` instead.
This behaviour is now catered for on Kong side, so overall no
changes in behaviour for Kong.
Fix #5869

chore(deps) bump dns client/balancer to 5.0.1

---

kong/plugins/cors/handler.lua
spec/03-plugins/13-cors/01-access_spec.lua

Use add_header instead of set_header for Vary header as it can be used in other use cases. 
* use add_header instead of set_hedear in cors plugin 
Fix #4782

fix(cors): don't override Vary header

---

kong/db/schema/init.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua

On PR #5879 @murillopaula proposed a fix to a common but arbitrary plugin field called `config.anonymous`. The PR tried to tackle two things at the same time. It tried to infer `JSON` input (which we don't do), and it tried to fix issue where upgraded databases still contained empty strings `""` stored to `config.anonymous` (instead of `null`). This only fixes the issue for this field. It also added `legacy` flag to that field, which in my opinion the field is not, or that it is not any special to any other field that could contain empty string `""`. So I didn't think it was a good idea to start flagging fields to `legacy` one by one.
Thus I discussed this with @murillopaula and out of those discussions came one winner that we both agreed upon. The solution is to run automatic …

fix(schema) make process auto fields to remove empty strings on select

---

kong-2.0.4-0.rockspec

This PR depends on Kong/kong-plugin-zipkin#78
being merged and a new rockspec being pushed to Luarocks.
Update: the other PR is done and the Luarock is released. This PR should be good to go now.

chore/bump zipkin 1.1.0

---

kong/api/routes/config.lua
kong/clustering.lua
kong/cmd/config.lua
kong/db/dao/init.lua
kong/db/declarative/init.lua
kong/db/schema/others/declarative_config.lua
kong/plugins/basic-auth/daos.lua
kong/templates/kong_yml.lua
spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/02-integration/02-cmd/11-config_spec.lua
spec/02-integration/03-db/08-declarative_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua
spec/03-plugins/10-basic-auth/05-declarative_spec.lua

Alternative name for this PR: feat/declarative config _transform.
This change fixes #5649 (basic-auth credentials not working on hybrid mode).
It is an alternative to #5792 where the proposed fix involves adding a new pseudo-field called `encrypted_password` to the entities.
The main drawback of that approach is that it requires manually changing all the entities which have transformations. Moreover, the change seems to be nearly identical in all cases: making a pseudo-field which in effect deactivates the transformation.
On this take, we add a new parameter to the declarative config file itself. The field is called `_transform`. When this field is present and set to `false`, the transformations are not executed when exporting. If the field is not present, or if it is, but it's set to …

feat/basic auth hybrid mode (take 2)

---

kong-2.0.4-0.rockspec

- **cipher:** AEAD modes with authentication
- **pkey:** support one shot sign/verify for Ed25519 and Ed448 keys
- **pkey:** support key derivation for EC, X25519 and X448 keys
- **pkey:** output pkey to DER and JWK format
- **pkey:** load EC key from JWK format
- **pkey:** set/get_parameters for EC key
- **pkey:** load RSA key from JWK format
- **pkey:** add function to set rsa parameter
- ***:** add prefix to all error messages
- **x509:** fail soft when CRL is not set

chore(deps) bump lua-resty-openssl from 0.6.0 to 0.6.2

---

.ci/run_tests.sh

some bundled kong plugins prefix their tags with `v`

fix(ci) adjust plugin tests for some plugin naming inconsistencies

---

kong/db/declarative/init.lua
spec/01-unit/01-db/10-declarative_spec.lua

Contains a fix that converts `lyaml.null`s to `ngx.null` when parsing declarative configuration.

fix(declarative) convert lyaml.nulls to ngx.nulls

---

kong/db/schema/others/declarative_config.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua

The declarative config validation may return misleading error messages in some cases, see #5750.
The validation of declarative configuration could fail when presenting configuration that did not have ids or names or didn't have a cache key.
Here is such configuration:
```yaml
_format_version: "1.1"
services:
- name: test-service
routes:
- paths:
- /test/path
plugins:
- name: key-auth
url: https://example.com
consumers:
- username: test-user
basicauth_credentials:
- username: test-username
password: test-password
```
See #5920
Fix #5750
Fix #5920

fix(declarative) misleading errors and validation errors

---

kong/runloop/balancer.lua

This was originally added in #4873 to fix #4808, but it seems like code has evolved since, and the building of balancers have changed. Thus this invalidation code is a left-over and it causes other problems as reported on #5837.
Fix #5837

fix(balancer) remove balancer invalidation from exclusive create balancer

---

kong/api/routes/config.lua
kong/clustering.lua
kong/cmd/config.lua
kong/db/declarative/init.lua
kong/db/schema/others/declarative_config.lua
kong/init.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/02-integration/03-db/08-declarative_spec.lua
spec/03-plugins/10-basic-auth/05-declarative_spec.lua

This PR modifies some of the changes introduced by #5835.
In particular, the `flatten` function now returns two separate
tables, `entities` and `meta`, instead of a single one.
This is done in order to is simplify a future merge with Kong EE.
The `_transform` field is also removed from the reports as it isn't
needed.

refactor(db-less) change the `flatten` return types

---

spec/helpers.lua

`return` will return `nil` when what we need here is `true`

fix(wait_pid) logic error in the pid_dead spec helper

---

kong/pdk/init.lua

As commit da707f0f9 introduced a new PDK submodule, minor version needs
a bump.

chore(pdk) bump version to 1.4.0

---

kong/cache.lua
spec/02-integration/04-admin_api/15-off_spec.lua

This change makes it actually all items from the cache (not only
mark them as "expired"), so that `safe_set` used in a subsequent
declarative config load can work if the previous one failed with
"memory full" (due to a too-large configuration that returned
HTTP 413).
This fixes some flakiness previously observed in tests, where
tests would pass when running individually but fail when running
in sequence with a smaller `mem_cache_size` configuration.

fix(dbless) actually release memory when purging the cache

---

kong/runloop/handler.lua

I noticed this when looking at the logs and spotting that when `kong.db.declarative.init` purges the shadow page, of both `kong.cache` and `kong.core_cache`, the page numbers for each were not in sync.

fix(dbless) flip both kong.cache and kong.core_cache

---

kong-2.0.4-0.rockspec
kong/constants.lua
spec/01-unit/12-plugins_order_spec.lua
spec/helpers.lua

Add the [grpc-gateway plugin](https://github.com/Kong/kong-plugin-grpc-gateway) and enable grpc plugins by default (following the pattern as #5555).
* Add the grpc-gateway plugin to rockspec
* Enable grpc-web and grpc-gateway plugin by default

feat(plugins) add grpc-gateway plugin

---

kong-2.0.4-0.rockspec
kong/conf_loader/init.lua
kong/conf_loader/listeners.lua

No behavior changes.
Also removes a little bit of code duplication around the parsing of listeners.

refactor(conf) make separate module for conf_loader listeners

---

kong/db/declarative/init.lua
kong/db/iteration.lua
kong/db/schema/init.lua
kong/db/strategies/off/init.lua
spec/02-integration/02-cmd/11-config_spec.lua
spec/02-integration/03-db/08-declarative_spec.lua
spec/02-integration/04-admin_api/15-off_spec.lua

The lyaml library uses its own representation for null. We need to preserve nulls for schema correctness.
The previous value caused a failure running locally. Add some more leeway to avoid flaky tests.
Both functions need the same change to export nulls.
Both Postgres and Cassandra strategies return null on fields that have null value stored in database. The DBless stores entities directly to cache where we don't keep nulls. But it has a problem that this commit tries to fix. This commit changes off strategy to fill nulls when the entities are accessed via DAO, the nulls are then later removed (again) by DAO when it calls process_auto_fields. This extra fill nulls is added to avoid the DAO process_auto_fields to fill explicit null values with possible default values.
Fix #5834

fix(declarative) null handling

---

kong/api/routes/upstreams.lua
kong/db/dao/targets.lua
kong/db/iteration.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua

Iterator had issue that it did not pass options to when it called
`dao:row_to_entity`.
E.g. `http :8001/upstreams/upstream/targets` returned:
```
{
"data": [
{
"created_at": 1591010002.497,
"id": "06f8e88f-f874-44ab-a6bf-989e58a505ba",
"target": "127.0.0.1:8000",
"upstream": {
"id": "5f3a5828-7e09-4d80-b899-41b0111510cd"
},
"weight": 100
}
],
"next": null
}
```
Instead of:
```
{
"data": [
{
"created_at": 1591010002.497,
"id": "06f8e88f-f874-44ab-a6bf-989e58a505ba",
"tags": null,
"target": "127.0.0.1:8000",
"upstream": {
"id": "5f3a5828-7e09-4d80-b899-41b0111510cd"
},
"weight": 100
}
],
"next": null
}
```
On Admin API (see the missing `tags=null`).
Targets did not pass the options on custom dao calls, this
commit fixes that.
Targets gave `500` error on:
```
http PUT …
```

fix(dao) target dao and endpoints

---

kong/db/dao/plugins/go.lua

Fix issue with go plugins where the plugin instance is intermittently
killed.
Cherry-picked from https://github.com/Kong/kong/pull/5903.
Thanks to @primableatom and @djepoulet for the PR and help in investigating the issue.

fix(go) reload killed plugin instance

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/schema.lua
spec/03-plugins/23-rate-limiting/01-schema_spec.lua

Feature: Use a custom header value as an identifier for Rate-Limiting.  
This feature can be used when consumers cannot be inputted to Kong Consumers, e.g. Header "X-App-Version: 0.0.1" is present in every request, and the App-Versions are too dynamic to create Kong Consumers, then it is possible to use the header value of "X-App-Version" as an identifier.
* Use a custom header value as identifier for Rate-Limiting.

feat: Custom Header as identifier for Rate-Limiting

---

autodoc/data/admin-api.lua
scripts/autodoc-admin-api

This change replaces some of the autodoc-generated admin api docs so they
use `id or name` instead of just `id`.
Related with https://github.com/Kong/docs.konghq.com/pull/1874

docs(autodoc) replace some `id` with `id or name`

---

Jenkinsfile

- the worker is a more recent bionic release
- uses ec2 spot

chore(ci) switch the build worker type we're using

---

kong/pdk/log.lua
kong/plugins/datadog/schema.lua
kong/plugins/file-log/schema.lua
kong/plugins/http-log/schema.lua
kong/plugins/log-serializers/basic.lua
kong/plugins/loggly/schema.lua
kong/plugins/statsd/schema.lua
kong/plugins/syslog/schema.lua
kong/plugins/tcp-log/schema.lua
kong/plugins/udp-log/schema.lua
spec/01-unit/10-log_serializer_spec.lua
spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua

In #5995, we refactored the basic log serializer into a proper PDK function. @bungle kindly provided #5629 which allows stream subsystem to call the log serializer function as well, which this PR is heavily based upon. It allows various logging plugin to work under TCP and TLS proxy mode.

feat(pdk) log serializer can not be used in stream subsystem

---

autodoc/data/admin-api.lua

Just updates auto-generator to produce max target weight of 65535 as updated with #5871.

docs(admin) update max weight on targets to 65535

---

kong/init.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua
spec/02-integration/11-dbless/02-workers_spec.lua

This PR includes two changes:
* It handles the creation of a Plugins Iterator on the Init Worker phase on a separate step, which fails less frequently.
* It changes the `get_*_plugin_iterator` functions so they don't assume that the plugins iterator is ready. They now check that the plugins iterator is there before using it, and attempt to recreate it once per request.
The reason we don't re-attempt to create the plugins iterator many times (at startup or on each request) is because we want to avoid a scenario in which two workers "compite with each other" by continuously re-creating the plugins iterator.

fix(runloop) a more robust plugins iterator on init worker

---

Jenkinsfile

Only reason this used to work is kong-build-tools alpine had this pinned. Recently fixed that to use the variable which means this broke

chore(release) pin alpine to 3

---

kong/plugins/rate-limiting/handler.lua

New feature "rate-limiting by header" was introduced (7c449842a),
so a minor bump in said plugin is required.

chore(plugins) bump rate-limiting plugin version

---

kong-2.0.4-0.rockspec
kong/pdk/request.lua
kong/pdk/service/response.lua
t/01-pdk/04-request/16-get_body.t

Adds support for parts with same name.
Also updates PDK functions to take advantage of this new functionality.
Thanks @nikolaydubina for providing us https://github.com/Kong/lua-multipart/pull/28.

chore(deps) update multipart library from 0.5.6 to 0.5.8

---

kong/plugins/correlation-id/handler.lua
spec/03-plugins/11-correlation-id/01-access_spec.lua

Note that by moving the priority to run before the Auth plugins, it can no longer be configured on consumers. Since by the time it runs, the consumer hasn't been identified yet.

fix(correlation-id) add id on short-circuit

---

kong/db/schema/others/declarative_config.lua
spec/01-unit/01-db/10-declarative_spec.lua

knows to skip trying to validate it
Otherwise entities containing the `ttl` field will cause "unknwon field"
validation failures
fixes #6063

fix(declarative) keep the `ttl` definitions so that schema validator

---

Makefile

`grpcurl` every time
Before the change, every time `make dev` is called `grpcurl` has to be re-downloaded. This took 17 sec on my network:
```shell
time make.dev
...
real	0m17.512s
user	0m1.587s
sys	0m1.202s
```
After the change, once `grpcurl` is already present, subsequent `make dev` takes only seconds to complete:
```shell
real	0m2.804s
user	0m1.426s
sys	0m1.141s
```
since `grpcurl` does not release that frequently (and we don't need the latest version for the tests), this should be a worthy tradeoff.

chore(makefile) speed up `make dev` command by avoid downloading

---

kong/cache.lua
kong/db/declarative/init.lua
kong/db/schema/others/declarative_config.lua
kong/db/strategies/off/init.lua
kong/init.lua
kong/runloop/balancer.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua
kong/templates/kong_defaults.lua

Before this commit, it was really hard to understand how the `POST /config` worked with dbless and was it correct. While figuring out how to make this depend less on events, and be more atomic, I also found couple of issues.
Let me try to explain changes here.
**`declarative/init.lua`**:
This file had following code:
```lua
kong.core_cache:purge(SHADOW)
kong.cache:purge(SHADOW)
```
The function also had parameter to which `page` to load configuration, so this was for obvious reasons changed to:
```lua
kong.core_cache:purge(shadow) --using the function argument
kong.cache:purge(shadow) --using the function argument
```
So that `load` will always clear the page where it is loading the config to (that workers need to be able to clear their LRUs).
The `load_into_cache_with_events` also relied …

fix(declarative) make reload atomic and properly clean the needed caches

---

spec/helpers.lua

fixes docs on UDP server helper and fixes a possibel returned error that is not an error.

docs(helpers) document udp server return values

---

kong/api/arguments.lua
kong/api/routes/plugins.lua

Plugins did double inferring for arguments. First without schema and
second time with the schema. This all worked rather fine, except when
the `PATCH` call also included `name` attribute. This caused a double
inferring bug for `ngx.null`
`""` -> changed to `ngx.null` and then `ngx.null` inferred again turning
it in some cases to `{ ngx.null }`.

fix(api) issue with double inferring with plugins

---

kong/db/migrations/operations/200_to_210.lua

There's a mismatch between the way PostgreSQL migrates
composite cache keys in Postgresql which end with ':':
```
UPDATE "$(TABLE)"
SET cache_key = CONCAT(cache_key, ':',
(SELECT id FROM workspaces WHERE name = 'default'))
WHERE cache_key LIKE '%:';
```
Cassandra did the opposite, updating the cache keys which did *not*
end with ':' :
```
for _, row in ipairs(rows) do
if not row.cache_key:match(":$")
local cql = ...
```
This change was masked because of the plugins cache warmup, which
ignores the cache_key field. But it was visible if Kong was started
with cache warmup deactivated for plugins, after migrating
plugins from an older version of Kong in Cassandra.

fix(migrations) fix composite cache keys in Cassandra

---

kong-2.1.0-0.rockspec

Changelog:
* Fix issue where header matching pattern could take an indeterminate amount of time on long strings

chore(deps) bump multipart to 0.5.9

---

kong/plugins/rate-limiting/policies/init.lua

The increment function of the Redis policy first gathers which relevant
keys actually exist, and then executes all the INCRBY/EXPIRE operations.
This has a window of error between the existence check and the
(optional) EXPIRE operation.
A solution documented in the Redis documentation
(https://redis.io/commands/incr) is to use a Lua operation in the Redis
server, which operates atomically.
Fixes #5763

fix(rate-limit) perform atomic redis increments

---

kong.conf.default

Document new settings for Hybrid Mode PKI
Shamelessly copied from https://github.com/Kong/docs.konghq.com/compare/docs/hybrid-mode-pki

docs(clustering) add settings defined by Hybrid Mode PKI

---

kong/pdk/node.lua
t/01-pdk/12-node/02-get_memory_stats.t

Fix issue where memory in use as reported by the `/status`
endpoint would be treated as `bytes`, while the output of
`collectgarbage("count")` is given in kbytes.
CHANGELOG:
- Fix issue where consumed worker memory as reported by `/status` would be incorrectly reported

fix(handler) convert collectgarbage output to bytes

---

kong/init.lua
kong/runloop/plugins_iterator.lua

The plugins iterator was being built before setting the default workspace id, therefore indexing the plugins under the wrong workspace.
Fix #6160, fix #6204

fix(init) set the default workspace before using it

---

kong.conf.default

NONE is an internal value meant to refer that the value was not given, it
should not be passed explicitly (and indeed it will be interpreted as a domain
name).
Fixes #6205.

docs(conf) default for pg_ro_host is not "NONE"

---

kong/db/migrations/operations/200_to_210.lua

When running migrations with `force`, e.g.:
```
kong migrations up -f
```
OR
```
kong migrations finish -f
```
Cassandra could ran `ws_update_keys` multiple times, even on a
row that was already updated. This commit makes it not to do that
for already updated rows.
It was noted that when migrations fail without `force` and they
are ran again without `force` there is re-entrancy problem too,
that this fixes.
This was added as a quick fix for upcoming 2.1.2.

fix(migrations) make cassandra ws_update_keys re-entrant

---

kong/router.lua
kong/runloop/handler.lua
spec/01-unit/08-router_spec.lua
spec/02-integration/05-proxy/03-upstream_headers_spec.lua

Pick non-breaking parts of fix https://github.com/Kong/kong/pull/6201 into master and add a few more tests.
New behavior:
- Stripped portion of path is added as X-Forwarded-Prefix 
- Stripped portion of path is *not* added as X-Forwarded-Prefix if it is `/`
- Stripped portion of path is *not* added as X-Forwarded-Prefix if a X-Forwarded-Prefix is received from a trusted client

fix(handler) forward stripped prefix as x-forwarded-prefix

---

Makefile

In the future we should migrate alpine to match the naming convention of our other repositories until then we need this exception in our Makefile logic 😢

fix(alpine) adjust the alpine repository name when doing official releases

---

Jenkinsfile
scripts/common.sh
scripts/make-patch-release
scripts/make-prerelease-release
scripts/send-slack-message.sh
scripts/setup-ci.sh

combined common elements of `make-patch-release` and `make-prerelease-release` into `common.sh`
moved `update_docker`, `homebrew`, `vagrant`, `pongo` to be ran after the release stage successfully runs. The steps announce their success / failure in #team-core slack channel
Sample PR opened by the bot account
Sample slack notification
All secrets are stored securely in 1password and as jenkins credentials

chore(automation) automate additional steps that dont need to be human ran

---

kong/db/migrations/operations/212_to_213.lua

When testing the migrations I used some debug statements in migrations, but they slipped
through the review process, and I forgot them there. This PR just removes them.

chore(migrations) remove a left-over debug statement

---

kong/api/routes/config.lua
kong/constants.lua
kong/db/declarative/init.lua
kong/init.lua
kong/runloop/handler.lua

With this patch the same node can receive new config at `:8001/config` only one at the time, and it waits for other workers to flip before allowing a new config to be uploaded. It makes `:8001/config` endpoint essentially serializable.
There is 60 seconds timeout, so that it will not be held forever.
@hishamhm knows that I tried this on the previous atomic (#6092), but as it was not causing issues anymore with router and plugins iterator, I removed it. Further testing showed that balancer has still issues with this. So I set up the flip-serializer again.

fix(balancer) make balancer flip config atomic by waiting for workers to finish

---

spec/03-plugins/08-datadog/01-log_spec.lua
spec/03-plugins/09-key-auth/02-access_spec.lua
spec/03-plugins/10-basic-auth/03-access_spec.lua
spec/03-plugins/11-correlation-id/01-access_spec.lua
spec/03-plugins/16-jwt/03-access_spec.lua
spec/03-plugins/17-ip-restriction/02-access_spec.lua
spec/03-plugins/19-hmac-auth/03-access_spec.lua
spec/03-plugins/20-ldap-auth/01-access_spec.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

Add grpc tests for 
- datadog
- correlation-id
- ip-restriction
Also hardens assertions in auth-plugins tests.

tests(plugins) add grpc test cases

---

kong-2.1.3-0.rockspec

* Introduce configuration `pass_stripped_path`, which, if set to true, causes the plugin to pass the stripped request path (see the `strip_path` Route attribute) to the upstream gRPC service.

chore(deps) bump grpc-web plugin to 0.2

---

kong/constants.lua
kong/pdk/request.lua
kong/runloop/handler.lua
kong/templates/nginx_kong.lua
spec/02-integration/05-proxy/03-upstream_headers_spec.lua
spec/fixtures/custom_nginx.template
t/01-pdk/04-request/00-phase_checks.t
t/01-pdk/04-request/18-get_forwarded_path.t
t/01-pdk/04-request/19-get_forwarded_prefix.t

Picks breaking portions of https://github.com/Kong/kong/pull/6201 into `next`.
**feat(pdk) add request.get_forwarded_prefix**
* **Breaking change**: existing `request.get_forwarded_path` method was
modified to return the request's `X-Forwarded-Path` header (if any,
and coming from a trusted client) or the request's path, as obtained by
`request.get_path`, rather than the request's prefix path stripped by
Kong
* New method `request.get_forwarded_prefix` was introduced; it returns
the request's prefix path component, as stripped by Kong. It also checks
if a `X-Forwarded-Prefix` header comes from a trusted source and uses
the given value
**feat(handler) add x-forwarded-path header**
* If a trusted source provides a `X-Forwarded-Path` header, it's
proxied as-is
* Otherwise, Kong will set the …

feat(*) x-forwarded-path and request.get_forwarded_prefix

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/schema.lua
spec/03-plugins/23-rate-limiting/01-schema_spec.lua
spec/03-plugins/23-rate-limiting/04-access_spec.lua

This PR expands #6234 (by @fairyqb) with a couple integration tests as well as changing the way the ratelimiting is calculated (in the original PR `conf.path` was just ignored by `kong.request.get_path`).
Left my changes as separate commits for easier review, but this PR should be Squashed and Merged into a single commit when approved.
Closes #6234. Closes #6202

feat(rate-limiting) implement rate limiting by path. 

---

spec/03-plugins/14-request-termination/02-access_spec.lua
spec/03-plugins/23-rate-limiting/04-access_spec.lua
spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
spec/helpers.lua

Add grpc test cases testing basic plugin functionality:
- request-termination
- rate-limiting
- response-rate-limiting: for this plugin, only rate-limiting headers
were tested, as the tests rely on manipulating response headers, which
is not currently possible with our mock grpc service

tests(*) plugins grpc 2

---

kong/init.lua

When resetting kong shms, we should not flush kong_process_events, as other workers may rely on its contents to keep working. This shm is always full, so there's no use on flushing it anyway.
Fix #6269

fix(init) do not flush kong_process_events dict

---

.ci/run_tests.sh
.travis.yml
kong-2.1.3-0.rockspec

It removes `WARN` log entry that we have seen with Kong `2.1.x` series, and reported by @michaelhsk on #6247.

chore(deps) bump prometheus plugin to 1.0.0

---

kong/clustering.lua

Currently when CP sends new config to DP the DP will apply that config even in case it is already applying a config, and even in case when CP sends a new config (which means 2 configs queued). Only the last config is needed. This PR changes it so that DP drops the unnecessary configs that it knows are going to be replaced right after.
This commit is continuation of the work that started with #6293 that made the CP skip the configs that it knows are already going to be replaced. This just makes the same thing on DP side.
You might wonder why is that? With huge configs, it can take a lot of time for DP to apply the configuration, @cwurm told us delays like 77 seconds in this message: #6280 (comment)
That's why the CP can send multiple new configs during the time DP is applying the previous …

feat(hybrid) do not queue updates on dp nodes 

---

CHANGELOG.md

Fix omission in 2.1.0 changelog.

docs(changelog) mention mTLS support for active health checks in 2.1.0

---

kong-2.1.3-0.rockspec

- ***:** x509.* set should return true on success [2a09575](fffonion/lua-resty-openssl@2a09575)
- **x509.csr:** finish {set,add}_extension functions [d34b702](https://github.com/fffonion/lua-resty-openssl/commit/d34b702a17b4f491e2a97e971da1d6125d482066)
- **x509.extension:** add ability to convert to other data type [15a5c7f](https://github.com/fffonion/lua-resty-openssl/commit/15a5c7ff38452a7bd04919b4a7e9c9dc1dfa931d)
- ***:** support reset for hmac and digest [37ba4b0](https://github.com/fffonion/lua-resty-openssl/commit/37ba4b0f63c60898ee25cfeeeab8b5651c62296e)
- ***:** initial support for OpenSSL 3.0 [be5dc10](https://github.com/fffonion/lua-resty-openssl/commit/be5dc10c24aabb6697ecb9fe2bd75c8a11e2b2d7)
- **x509.csr:** add get_extension and get_extensions function …

chore(deps) bump resty.openssl from 0.6.2 to 0.6.5

---

kong/runloop/balancer.lua
spec/02-integration/05-proxy/18-upstream_tls_spec.lua
spec/02-integration/09-hybrid_mode/01-sync_spec.lua

`Upstream.client_certificate` instead.
This allows `client_certificate` setting used for mTLS handshaking with
the `Upstream` server to be shared easily among different Services.
However, `Service.client_certificate` will take precedence over
`Upstream.client_certificate` if both are set simultaneously.

feat(upstream) When `Service.client_certificate` is not set, use

---

kong/cmd/hybrid.lua

It was reported by @hishmamhm on #6365 that we give indication of success
even when we fail writing a certificate. This commit changes that to error
on such cases.
Fix #6365

fix(cmd) kong hybrid gen_cert errors on permissions issues

---

kong/plugins/acl/handler.lua
spec/03-plugins/18-acl/02-access_spec.lua

It was reported with #6281 that ACL plugin with `config.deny=do-not-deny-anyone`
does not work in all scenarios. I found two possible scenarios:
1. The user was authenticated but did not have consumer nor did not set authenticated groups
2. The user was not authenticated at all (no auth plugins added)
3. There was authentication but the authenticated user was anonymous and thus didn't have credential
All of this lead to `401`s.
This is more about semantics. Loosening the verification on anonymous and non-authenticated
users will make this plugin a bit more flexible, but then I can see that this might open some
security issues.
What does `nil` `authenticated_groups` mean (or empty `{}`) when using ACL plugin with `config.deny`?
1. the groups cannot be determined, deny the request
2. we …

fix(acl) deny should not deny proxying if denied group does not match

---

autodoc/admin-api/data/admin-api.lua
kong/db/migrations/core/012_213_to_220.lua
kong/db/schema/entities/routes.lua
kong/init.lua
kong/reports.lua
kong/runloop/handler.lua
kong/templates/nginx_kong.lua
spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/02-integration/03-db/02-db_core_entities_spec.lua
spec/02-integration/05-proxy/27-unbuffered_spec.lua
spec/fixtures/custom_nginx.template

By default Kong does buffer the request. This is not ideal when proxying bigger payloads with HTTP 1.1 chunked encoding.
This PR adds a new property to route entity:
```
request_buffering = <true/false>
```
By default that is `true` (which is the same as before). Users can now turn the request buffering `off` by route-by-route manner by setting `route.request_buffering=false`.
By default Kong does buffer the response. This is not ideal when upstream is sending payloads with HTTP 1.1 chunked encoding.
This PR adds a new property to route entity:
```
response_buffering = <true/false>
```
By default that is `true` (which is the same as before). Users can now turn off the response buffering on route-by-route manner by setting `route.response_buffering=false`.

feat(proxy) add route.request|response_buffering

---

kong/plugins/correlation-id/handler.lua
spec/03-plugins/11-correlation-id/01-access_spec.lua

Makes `correlation-id` plugin to check for empty header. Before this commit the empty header was forwarded as is. With this commit the empty header is replaced by a generated id. I didn't feel we need to make this a config option.
Fix #5646

feat(correlation-id) override empty correlation id with a generated one

---

kong/api/arguments.lua
kong/db/schema/entities/services.lua
kong/db/schema/entities/upstreams.lua
kong/db/schema/init.lua
kong/db/schema/metaschema.lua
kong/plugins/acl/schema.lua
kong/plugins/bot-detection/schema.lua
kong/plugins/ip-restriction/schema.lua
spec/01-unit/01-db/01-schema/01-schema_spec.lua
spec/01-unit/01-db/03-arguments_spec.lua

This is a "second shot" at the design of the shorthands feature, based on comments by @bungle, who correctly pointed out that we were missing type information.
This also fixes #6352 by making the form-encoded inference system in the Admin API aware of shorthand_fields.
The feature has been renamed from `shorthands` to `shorthand_fields` to avoid a "polymorphic" state in between the deprecated and new form.

feat(schema) typed shorthand_fields, deprecate shorthands

---

kong/plugins/key-auth/handler.lua
spec/03-plugins/09-key-auth/02-access_spec.lua

Issue #5893 pointed out that `key-auth` plugin returns `400` and "Cannot process request body" message in case the body decoding fails. This happens even in case the key is found in other places like `query` of `headers`.
Fix #5893

fix(key-auth) do not error with 400 when body cannot be decoded

---

Makefile

* Caching now uses files in a global directory instead of local
`.luacheckcache` file. Default cache directory is
`%LOCALAPPDATA%\Luacheck\Cache` on Windows,
`~/Library/Caches/Luacheck` on OS X/macOS, and
`$XDG_CACHE_HOME/luacheck` or `~/.config/luacheck` on other systems.
* Fixes for using Luacheck with Lua 5.4:
- Parse 5.4 attributes in `local` declarations (but ignores them for now)
- Luacheck itself can also run with Lua 5.4
* Fixed `randomize` missing from `busted` set of standard globals (#183).
* Added additional `table` and `thread` definitions for `ngx_lua`.
* Added additional `match` definition for `busted`.
* Upgraded Windows binary components: Lua 5.3.4 -> 5.3.5,
LuaFileSystem 1.6.3 -> 1.7.0.

chore(deps) bump luacheck (used for tests) from 0.23 to 0.24

---

kong/init.lua
kong/pdk/response.lua
kong/plugins/request-termination/handler.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/14-server_tokens_spec.lua
t/01-pdk/08-response/11-exit.t

This commit contains following things:
1. it removes `Server` header setting from `kong.response.exit`
2. admin api now sets `Server` header according to `conf.headers` on `header_filter`
3. proxy does not add `Server` header in case `Via` header contains the same value and request is short-circuited (this is for `aws-lambda`, `azure-functions` etc. plugins that kinda proxy, but do not use the proxy module, and skip balancer)
Fix #6367

fix(headers) admin api and proxy server headers adjustment

---

spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua

```
FAILED  spec/02-integration/05-proxy/10-balancer/01-ring-balancer_spec.lua:878: Ring-balancer #cassandra #healthchecks (#cluster #db) #hostname does not perform health checks when disabled (#3304)
...tegration/05-proxy/10-balancer/01-ring-balancer_spec.lua:901: iteration 1
Expected objects to be the same.
Passed in:
(number) 0
Expected:
(number) 10
...tegration/05-proxy/10-balancer/01-ring-balancer_spec.lua:901: in function <...tegration/05-proxy/10-balancer/01-ring-balancer_spec.lua:878>
```
https://internal.builds.konghq.com/blue/organizations/jenkins/kong-build-tools/detail/chore%2Fdocker-compatibility/3/pipeline#step-80-log-385

fix(balancer) mark a balancer test as being flaky

---

.ci/setup_env.sh

If it is not included in cache hash calculation, dependencies that are updated in .rockspec are leaked to other tests / builds.

chore(tests) include kong*.rockspec to cache hash calculation on travis

---

kong/clustering.lua
spec/02-integration/02-cmd/12-hybrid_spec.lua

Starting control plane with:
```
KONG_ROLE=control_plane \
KONG_CLUSTER_CERT=cluster.crt \
KONG_CLUSTER_CERT_KEY=cluster.key \
./bin/kong start -p cp
```
Then connecting data plane to it with:
```
KONG_ROLE=data_plane \
KONG_CLUSTER_CONTROL_PLANE=cp.test:8005 \
KONG_CLUSTER_CERT=cluster.crt \
KONG_CLUSTER_CERT_KEY=cluster.key \
KONG_LUA_SSL_TRUSTED_CERTIFICATE=cluster.crt \
KONG_DATABASE=off \
./bin/kong start -p dp
```
And then gracefully stopping control plane with:
```
KONG_ROLE=control_plane \
KONG_CLUSTER_CERT=cluster.crt \
KONG_CLUSTER_CERT_KEY=cluster.key \
./bin/kong quit -p cp
```
Will result (after 10 secs):
```
Timeout, Kong stopped forcefully
```
This PR is to fix that so that what happens is this instead (after around 1 sec):
```
Kong stopped (gracefully)
```

fix(hybrid) allow graceful exit of cp and dp nodes

---

kong-2.1.4-0.rockspec

- In pl.class, _init can now be inherited from grandparent (or older ancestor) classes. #289
- Fixes dir, lexer, and permute to no longer use coroutines. #344
- `pretty.debug` quickly dumps a set of values to stdout for debug purposes
- `pretty.write`: now also sorts non-string keys [#319](https://github.com/Tieske/Penlight/pull/319)
- `stringx.count` has an extra option to allow overlapping matches [#326](https://github.com/Tieske/Penlight/pull/326)
- added an extra changelog entry for `types.is_empty` on the 1.6.0 changelog, due to additional fixed behaviour not called out appropriately [#313](https://github.com/Tieske/Penlight/pull/313)
- `path.packagepath` now returns a proper error message with names tried if it fails
- Fix: `stringx.rfind` now properly works with overlapping matches …

chore(deps) bump penlight from 1.7.0 to 1.9.2

---

kong-2.1.4-0.rockspec

- feat: adding support for 'isBase64Encoded' flag in Lambda function responses
- fix: respect `skip_large_bodies` config setting even when not using
AWS API Gateway compatibility

chore(deps) bump AWS Lambda plugin to 3.5.0

---

kong.conf.default
kong/clustering.lua
kong/conf_loader/init.lua
kong/db/migrations/core/012_213_to_220.lua
kong/db/schema/entities/clustering_data_planes.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua
spec/02-integration/09-hybrid_mode/01-sync_spec.lua

cluster_data_planes table so it won't grow uncontained
Also adds new config option `conf.cluster_status_ttl`, that allows the
TTL of cluster status entries to be overwritten by user. The default TTL
is 14 days.

feat(clustering) automatically purge entries from the cluster_data_planes table so it won't grow uncontained

---

kong.conf.default
kong/cmd/utils/prefix_handler.lua
kong/conf_loader/init.lua
kong/db/strategies/cassandra/connector.lua
kong/db/strategies/postgres/connector.lua
kong/templates/nginx_kong.lua
kong/templates/nginx_kong_stream.lua
kong/tools/utils.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/04-prefix_handler_spec.lua
spec/01-unit/05-utils_spec.lua
spec/02-integration/05-proxy/27-lua-ssl-trusted-cert_spec.lua
spec/fixtures/1.2_custom_nginx.template
spec/fixtures/custom_nginx.template

This PR adds two features to the `lua_ssl_trusted_certificate` option:
* It is now a comma-separated list instead of a single item. All the paths on the list are concatenated into a single file in a fixed location (`$PREFIX/.ca_combined`).
* It accepts a special `system` value, which is expanded to the "system default". This follows a very simple heuristic to try to use the most common cert in most popular distros. `system` can be used in conjunction with other paths.
Note that this PR involves modifying Kong's template - as a result, the UPGRADE.md file should include such changes when a new version is released.

feat(conf) improved lua_ssl_trusted_certificate

---

kong/init.lua

On errors (especially 499), it's possible that some phases are skipped.
Even on those cases, Kong spent time waiting, so it should be accounted
not only on header-filter but on body-filter (unlikely!) or log phase.
Fix #6180

Always count KONG_WAITING_TIME

---

kong-2.1.4-0.rockspec
kong/db/schema/typedefs.lua

The resty.iputils lacks ipv6 support and we don't use it anymore. This change removes the last dependency to it and removes the dependency from luarocks.

chore(deps) remove resty.iputils dependency

---

kong/api/api_helpers.lua
kong/init.lua
kong/pdk/response.lua

This PR makes admin api calls to poll worker events before and after actually executing the admin api call function. It makes admin api less dependent on background timers, and makes usage of admin api more predictable.

chore(admin) poll worker events before and after the changes

---

kong/constants.lua
kong/db/init.lua
spec/01-unit/01-db/07-db_spec.lua
spec/02-integration/03-db/01-db_spec.lua

This PR adds a version check on db connector initialization. Any version lower that `MIN` will throw an error, unless it's greater or equal to `DEPRECATED`, on which case a warning is shown. 
It's a direct port of the feature that was present on old DAO (https://github.com/Kong/kong/pull/6167 and https://github.com/Kong/kong/commit/a9f5af1a53a701bd74c9ed6683390c3f1b43fc6b). Moved some of the specs to be unit tests instead of integration by mocking related data structures.

feat(db) check MIN and DEPRECATED versions on connector init

---

kong/tools/utils.lua

I believe we call these "hotfixes" since it fixes a feature introduced in the current release.

fix(utils) typo in error message

---

Jenkinsfile

This flag exists on the KONG_BUILD_TOOLS repository Jenkinsfile but I forgot to include it here

chore(ci) set the docker experimental flag so we can push manifests

---

kong/runloop/balancer.lua

Fix errors like these:
```
2020/10/01 14:09:57 [debug] 5632#0: *95 [lua] base_plugin.lua:26: access(): executing plugin "canary": access
2020/10/01 14:09:57 [error] 5632#0: *95 [kong] init.lua:266 [canary] /kong/kong/runloop/balancer.lua:1097: attempt to index local 'ctx' (a nil value), client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "canary5.com"
2020/10/01 14:09:57 [debug] 5632#0: *95 [lua] base_plugin.lua:26: access(): executing plugin "canary": access
2020/10/01 14:09:57 [error] 5632#0: *95 [kong] init.lua:266 [canary] /kong/kong/runloop/balancer.lua:1097: attempt to index local 'ctx' (a nil value), client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "canary5.com"'
```

fix(balancer) protect against nil request context data

---

kong-2.1.4-0.rockspec
kong/conf_loader/init.lua
kong/db/schema/typedefs.lua
kong/pdk/ip.lua
kong/router.lua
kong/tools/utils.lua
spec/01-unit/01-db/01-schema/06-routes_spec.lua

The resty.mediador dependency can be replaced with ipmatcher, and that's what this commit does.

chore(deps) remove resty.mediador dependency

---

Jenkinsfile

I resolved this for unofficial tagged releases, official releases but missed the unofficial master / next

chore(release) we require AWS credentials for daily ARM releases

---

Jenkinsfile

The arm build workers require randomized names so the ssh keys dont collide
The only ENV I added was `DOCKER_MACHINE_ARM64_NAME="jenkins-kong-"`cat /proc/sys/kernel/random/uuid`` the rest was a copy / paste to move some values

chore(arm) build workers

---

kong-2.1.4-0.rockspec

Full diff: https://github.com/fffonion/lua-resty-openssl/compare/0.6.5...0.6.7
Changelog: https://github.com/fffonion/lua-resty-openssl/blob/master/CHANGELOG.md

chore(*) bump lua-resty-openssl to 0.6.7

---

kong/db/migrations/helpers.lua

We have never documented this properly and we don't use it in any of the current
migrations. This was needed for pre `1.0.0` migrations.
With this deprecation, we have option to either:
1. remove it with `3.0.0`
2. if feedback demands that we need to keep it:
then remove the warning and properly document it

chore(migrations) deprecate migration helpers

---

kong/plugins/rate-limiting/daos.lua

Rate-limiting metrics is problematic on db exports / imports as reported by @jeremyjpj0916 on #6310.
There are several issues on that, but it seems like the main issue is that Cassandra schema specifies the value of ratelimiting_metrics as `COUNTER`. Also it probably does not make sense to export these anyway as agreed on that issue.
Fix #6310

fix(db) do not export ratelimiting_metrics

---

kong/meta.lua
kong/runloop/handler.lua
kong/templates/nginx_kong.lua
spec/fixtures/custom_nginx.template

With latest OpenResty based on Nginx `1.7.x` series we can now use variables in `scheme` part of `grpc_pass`, thus we can now remove some repetition from our templates.
There is one additional commit in this PR that removes support for `1.15.8.x` series of OpenResty, because after this PR, the templates won't work anymore with the earlier version.

chore(template) grpc_pass now has support for variables 

---

kong/templates/nginx_kong_stream.lua

When stream_listen is on, and  `proxy_access_log` is set `off`, Kong will generate `access_log off basic;`.
Error `nginx: [emerg] invalid parameter "basic" in /usr/local/kong/nginx-kong-stream.conf:63` occurs.

fix(template): nginx conf parse error when access_log set off in stream subsystem

---

kong/api/routes/clustering.lua
spec/02-integration/09-hybrid_mode/01-sync_spec.lua
spec/02-integration/09-hybrid_mode/03-pki_spec.lua

Adds /clustering/status back for backward compatibility with a `Deprecation` header as described in https://tools.ietf.org/html/draft-dalal-deprecation-header-03.

hotfix(admin) add /clustering/status back with deprecation header

---

kong/cmd/utils/migrations.lua

Fixes issue reported in #6105 by @jeremyjpj0916.
Before this commit:
```
$ kong migrations up
Error: [PostgreSQL error] cluster_mutex callback threw an error: kong/cmd/utils/migrations.lua:67: Database has pending migrations; run 'kong migrations finish'
[C]: in function 'error'
kong/cmd/utils/migrations.lua:67: in function <kong/cmd/utils/migrations.lua:63>
kong/db/init.lua:364: in function <kong/db/init.lua:314>
[C]: in function 'pcall'
kong/concurrency.lua:45: in function 'cluster_mutex'
kong/cmd/utils/migrations.lua:63: in function 'up'
kong/cmd/migrations.lua:177: in function 'cmd_exec'
kong/cmd/init.lua:88: in function <kong/cmd/init.lua:88>
kong/cmd/init.lua:88: in function <kong/cmd/init.lua:45>
bin/kong:9: in …
```

fix(cli) no stack trace when running migration up while having pending migrations

---

kong/api/routes/upstreams.lua
spec/02-integration/04-admin_api/08-targets_routes_spec.lua
spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua

`PATCH` requests to Kong admin API return `200` and the entity as the response body when succeeded. This change fixes the behavior for target entities to the standard, instead of returning `204`.

fix(api) use the standard status when patching targets

---

kong/clustering.lua

Does not cause push config on `dao:crud` events for daos that have `db_export=false`.
Most notable it does not push when there are dao events for `clustering_data_planes` dao.

hotfix(hybrid) do not push config changes when there is nothing new to export

---

kong/db/migrations/operations/200_to_210.lua

On issue #6403 we have tried to chase the reason for why selecting default workspace id sometimes fail. This commit tries to make it so that if we ever get workspace id, we will store it in module level variable for further migrations that might need it, and not trying to do select each time, which seems flaky according to #6403.
We labeled this as `perf` as that is one thing that it surely does, but we are not sure if it fixes the #6403, and even if it does, we still do not fully understand the root cause of it.

perf(migrations) store workspace id after first retrieval

---

kong/db/dao/plugins.lua
kong/runloop/plugins_iterator.lua

Schemas are not associative arrays, indexed by the field name,
but arrays of fields; therefore, one needs to iterate over the
top-level `fields` to check for the presence of specific fields.

fix(dao) no_{consumer,route,service} usage

---

kong.conf.default

separate properties for CP and DP purposes by headings
Assuming the sections will grow in future versions, hence adding here. In EE this is already the case, hence adding them upstream.

chore(conf) update kong.conf.default

---

README.md

Replace the building badge since we switch to the Github Action.

docs(README) update the building badge with Github Action

---

kong/db/dao/plugins/go.lua

Allows Go plugins to just use the idiomatic `log.Printf(...)`.
Any stdout/stderr output will be copied into nginx's `error.log` line by line.

feat(go) grab log from pluginserver's stderr

---

kong/db/dao/plugins/go.lua

When a Lua coroutine (thread) finds that another thread is starting an
instance, it waits until the other either succeeds or fails.  In case of
failure, the original thread fails the request, and the second one
tries again.  This retry was wrongly being stored in the old intance
info table which is removed by the failing thread, and never stored
back in the general table by the retrying thread.  This fix ensures
that on the failing case the second thread doesn't hold the old info,
but creates a new one.
Fix #6432 #6500

fix instance restarting fight.

---

kong/db/dao/plugins/go.lua
spec/02-integration/10-go_plugins/01-reports_spec.lua
spec/fixtures/go/go-hello.go

Once again, having Go log phase run in a timer means less access to
request-relative information.
This patch stores `ngx.ctx` and `kong.ctx.shared` tables, prolonging
their lifetimes until timer execution time.  Note: these _must_ be
removed before finishing the timer, or it would create a memory leak.
Fix #6426 
Replace #6430

Save context tables for the Go log phase timer.

---

kong-2.2.0-0.rockspec
kong/init.lua
kong/templates/nginx_kong_stream.lua
kong/tools/stream_api.lua
spec/02-integration/05-proxy/01-proxy_spec.lua
spec/02-integration/12-stream_api/01-stream_api_endpoint_spec.lua
spec/fixtures/custom_plugins/kong/plugins/stream-api-echo/api.lua
spec/fixtures/custom_plugins/kong/plugins/stream-api-echo/handler.lua
spec/fixtures/custom_plugins/kong/plugins/stream-api-echo/schema.lua

OpenResty http and stream modules keep Lua code in separate spaces; and for the time being, the shared dictionaries are shared only between the spaces of the same module.
This feature adds a simple RPC on top of a datagram-mode unix domain socket.  Just a call/result with a single string on each direction.
From the `api.lua` module in a plugin directory, return a table with a `_stream` field.  For example:
```lua
return {
_stream = function(data)
return "back: " .. data
end,
}
```
The handler will receive a single string in the `data` parameter, and should return a single string or `nil, err` on error.
Use `stream_api.request(<plugin name>, <data>)`  to call the handler registered by the named plugin.  On success, it will return the string returned by the handler.  On error it will return …

minimal inter-modules RPC 

---

kong/db/schema/entities/routes.lua
kong/db/schema/entities/services.lua
kong/db/schema/typedefs.lua
spec/01-unit/01-db/01-schema/05-services_spec.lua
spec/01-unit/01-db/01-schema/06-routes_spec.lua
spec/01-unit/05-utils_spec.lua
spec/02-integration/02-cmd/02-start_stop_spec.lua
spec/02-integration/04-admin_api/09-routes_routes_spec.lua
spec/02-integration/04-admin_api/10-services_routes_spec.lua

This PR adds utf-8 capabilities to the names of Routes and Services.
Some tests which assumed ASCII-only had to be modified.
Tests which check that utf-8 strings can be used in the Admin API have been added.

feat(*) utf-8 names for Routes and Services

---

spec/helpers.lua

follow up to https://github.com/Kong/kong/pull/6351#issuecomment-696800128
The 2 functions should have been combined from the start. Since these are only helpers and the additional function in #6351 hasn't yet made it into a release, I think this PR should be in `2.2` still, to keep it clean and not release a helper that gets deprecated right after.

refactor(helpers) combine 2 functions

---

kong/cmd/utils/prefix_handler.lua
kong/conf_loader/init.lua
kong/runloop/certificate.lua
kong/templates/nginx_kong.lua
kong/templates/nginx_kong_stream.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/04-prefix_handler_spec.lua
spec/fixtures/1.2_custom_nginx.template
spec/fixtures/custom_nginx.template

Previously you could just set a single value to:
- `ssl_cert` and `ssl_cert_key`
- `admin_ssl_cert` and `admin_ssl_cert_key`
- `status_ssl_cert` and `status_ssl_cert_key`
This commit makes them arrays.
Previously we only generated RSA certificate by default which didn't allow certain ciphers on default cipher suites. This commit now also generates ECDSA certificate by default. On modern and intermediate cipher suites the ECDSA certificate is set as the default fallback certificate, on old cipher suite the RSA certificate remains the default fallback certificate. When specifying the custom certificates (with a custom cipher suite), the first specified in array is considered the default fallback certificate.

feat(conf) change *ssl_cert* to arrays and autogenerate ecdsa cert

---

kong-2.2.0-0.rockspec

The update only contains a single fix, but since the version is stable it was promoted to 1.0.0.

chore(deps) bump azure-function to 1.0.0

---

UPGRADE.md

URLs to the Kong Documentations were fixed, now users will go to the desired website directly. The need for URL redirections can be avoided. 
Also sometimes these redirections take a lot of time, now that can also be avoided as the users will be taken directly to the documentation page.

Fixed URLs to Kong Documentation

---

kong/plugins/key-auth/handler.lua
kong/plugins/key-auth/schema.lua
spec/01-unit/01-db/01-schema/07-plugins_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/02-process_auto_fields_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/02-integration/03-db/03-plugins_spec.lua
spec/03-plugins/09-key-auth/02-access_spec.lua

Adds new two new plugin config fields to `key-auth` plugin:
1. `config.key_in_header=<true|false>` (default `true`)
2. `config.key_in_query=<true|false>` (default `true`)
To complement already existing config field:
`config.key_in_body=<true|false>` (default `false`)

feat(key-auth) add config.key_in_header and config.key_in_query

---

kong/db/schema/entities/routes.lua
kong/db/schema/typedefs.lua
kong/plugins/http-log/handler.lua
kong/plugins/http-log/schema.lua
spec/01-unit/01-db/01-schema/03-typedefs_spec.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/03-plugins/03-http-log/01-log_spec.lua
spec/03-plugins/03-http-log/02-schema_spec.lua

Adds an option to provide a custom header, and value to add to the log request. Typically required for Splunk for example.

feat(http-log) add custom header for authorization

---

autodoc/admin-api/data/admin-api.lua
kong/db/migrations/core/013_220_to_230.lua
kong/db/schema/entities/certificates.lua
kong/runloop/certificate.lua
spec/02-integration/04-admin_api/06-certificates_routes_spec.lua
spec/02-integration/05-proxy/06-ssl_spec.lua
spec/fixtures/ssl.lua

The PR #6509 added support for static configuration to be able to set multiple certificates and keys with:
- `ssl_cert` and `ssl_cert_key`
- `admin_ssl_cert` and `admin_ssl_cert_key`
- `status_ssl_cert` and `status_ssl_cert_key`
But it didn't yet allow `certificates entity` to contain multiple certificates. This PR changes `certificates entity` to contain two new fields:
- `cert_alt`
- `key_alt`
Where you can configure alternative certificate and the matching key, this way you can use `cert` and `key` to store ECDSA certificate and `cert_alt` and `cert_key` to store RSA certificate.

feat(db) certificates to have cert_alt and key_alt fields

---

kong/clustering.lua
kong/db/migrations/core/013_220_to_230.lua
kong/db/schema/entities/clustering_data_planes.lua
kong/db/schema/typedefs.lua
spec/01-unit/01-db/01-schema/03-typedefs_spec.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
spec/02-integration/09-hybrid_mode/01-sync_spec.lua
spec/fixtures/custom_plugins/kong/plugins/cache/schema.lua
spec/fixtures/custom_plugins/kong/plugins/error-generator-last/handler.lua
spec/fixtures/custom_plugins/kong/plugins/error-generator-last/schema.lua
spec/fixtures/custom_plugins/kong/plugins/error-generator/schema.lua
spec/fixtures/custom_plugins/kong/plugins/error-handler-log/schema.lua
spec/helpers.lua
spec/kong_tests.conf

Previously, Hybrid mode did not have any capabilities for checking the
version compatibility between CP and DP (aside from the
`_format_version` field in the declarative config generated) and this
will cause some operational safety issues when people are running a
cluster of diverse Kong versions as Kong CP may be pushing out configs
DP could not understand without knowing.
After this commit, DP node will start reporting their Kong version
running to the CP. CP will then store this information onto the
database in the new `version` field of the `/clustering/data-planes`
Admin API endpoint.
DPs will also report the installed plugins and their version upon
connecting to the CP.
CP uses the Kong version and plugin information reported by DP to make
decision on whether new config should be …

feat(clustering) version checks between CP and DP

---

kong-2.2.1-0.rockspec

- Don't skip YAML entries from mixed key Lua tables.
- `luke` really propagates `LDFLAGS` to module compilation commands.

chore(deps) bump lyaml from 6.2.5 to 6.2.7

---

kong-2.2.1-0.rockspec

- `get()` callback functions are now optional. Without a callback, `get()` now still performs on-cpu L1/L2 lookups (no yielding). This allows implementing new cache lookup patterns guaranteed to be on-cpu for a more constant, smoother latency tail end (e.g. values are refreshed in background timers with `set()`). Thanks Hamish Forbes and Corina Purcarea for proposing this feature and participating in its development! [#96](https://github.com/thibaultcha/lua-resty-mlcache/pull/96)
- Improve `update()` robustness to worker crashes. Now, the library behind  `cache:update()` is much more robust to re-spawned workers when initialized in  the `init_by_lua` phase. [#97](https://github.com/thibaultcha/lua-resty-mlcache/pull/97)
- Document the `peek()` method `stale` argument which was not …

chore(deps) bump resty.mlcache from 2.4.1 to 2.5.0

---

Jenkinsfile

Centos 6 is EOL as of Nov 30 - https://endoflife.software/operating-systems/linux/centos

chore(build) remove centos6 from build matrix

---

kong/db/init.lua
kong/db/schema/others/migrations.lua
spec/01-unit/01-db/01-schema/10-migrations_spec.lua
spec/fixtures/custom_plugins/kong/plugins/with-migrations/migrations/000_base_with_migrations.lua
spec/fixtures/custom_plugins/kong/plugins/with-migrations/migrations/001_14_to_15.lua

The initial assumption behind only allowing strings of SQL and CQL on the "up" side of migrations was that the operations on this phase needed to be safe, fast and reentrant.
Unfortunately CQL is much more limited than Pg's SQL. So what's trivial to do in Pg is impossible to do in Cassandra. So we arrive to a point where trivial and safe operations get delayed to the `teardown` phase, simply because they need a more complete language than CQL to be done.
This change adds a new `up_f` method to which accepts a Lua function with a connector, effectively allowing the use of Lua inside Cassandra migrations' "up" phase. While adding the same features in Postgres would not be difficult, we think that SQL is powerful enough to do most "safe" things we need (perhaps with some trivial string …

feat(migrations) allow up_f field in Cassandra migrations

---

kong.conf.default
kong/conf_loader/init.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua
spec/01-unit/04-prefix_handler_spec.lua

If we install and run Kong with everything default, whenever Kong tries to write something to the Kong prefix, things will break and we will get a permission denied error. This applies to:
- DP nodes trying to write the config.json.gz file to the Kong prefix
- go pluginserver trying to write the go.lua file write to the Kong prefix
- Lua plugins trying to write files to the Kong prefix
And other cases. This is because, by default, the Kong prefix is owned by `root`. When we do a `apt-get install` or `yum install`, the `/usr/local/kong/` prefix (default) is owned by `root` by default. After that, if we do a `kong start` without changing our operating system's `$USER`, the nginx master process will be run as `root` and the nginx workers processes will be run as `nobody`. It means that if we …

fix(conf) default nginx_user to kong, not nobody

---

README.md

Updated README.md by updating the links under Development section as it was no more working.
The links that were changed were of 
[CONTRIBUTING.md] , [DEVELOPER.md ] , [CODE_OF_CONDUCT.md] and [COPYRIGHT] as no of them were working!
All of them redirected to same page with just "#".
So i updated them with working one.
* Link updated for [CONTRIBUTING.md] , [DEVELOPER.md ] , [CODE_OF_CONDUCT.md] and [COPYRIGHT] as no of them were working.
Fix [CONTRIBUTING.md] , [DEVELOPER.md ] , [CODE_OF_CONDUCT.md] , [COPYRIGHT] links in readme.md

Updated Development Section in README.md

---

kong/api/routes/clustering.lua

`/clustering/status` endpoint
Since we have announced the deprecation of the `/clustering/status` endpoint,
we should not make new database fields available from it. This
encourages people to switch over, but also because we no longer provide any
documentation update to the old endpoint.

fix(clustering) do not include the new fields in the deprecated

---

kong/cmd/reload.lua
kong/cmd/utils/nginx_signals.lua
kong/cmd/utils/prefix_handler.lua
spec/02-integration/02-cmd/03-reload_spec.lua
spec/fixtures/reload.conf

Originally this issue seemed to be fixed in:
https://github.com/Kong/kong/commit/1b4780345002d77513e1342d35c17867d45df1e7
But that only fixed it to work with environment variables. This PR now fixes the `kong reload -c <config>` to work too.
On my machine (and I have seen this elsewhere too) sometimes a corrupted `.kong_env` gets generated. This is most probably because of usage of `ffi.C.write`. It is hard to reproduce, but it requires multiple reloads and passing `-c` (confs).
I changed the code to use plain Lua, which seemed to mitigate the issue fully.

fix(cmd) usage of ffi.C.write and -c flag on reload

---

kong/clustering.lua
kong/constants.lua
kong/db/migrations/core/013_220_to_230.lua
kong/db/schema/entities/clustering_data_planes.lua
spec/01-unit/01-db/01-schema/13-cluster_status_spec.lua
spec/02-integration/09-hybrid_mode/01-sync_spec.lua

status of CP-DP sync and reasons for failing the compatibility check
Now the `/clustering/data-planes` endpoint includes a new field - `sync_status`. Which will contain values that represents if sync is allowed between CP and DP and if not, the reason for the failure.

feat(clustering) add more fields on Control Plane API that returns the

---

kong/pdk/log.lua
t/01-pdk/02-log/05-set_serialize_value.t

Log-type plugins (like file_log, or http_log) use the kong.log.serialize() function to "extract" a table representing the current status of Kong. That table is used in the logs.
This change introduces a new function which allows customizing the table returned by kong.log.serialize(). This can be used by plugins to customize the output of a logging plugin without having to "monkey-patch" it.
Related with #5968

feat(pdk) kong.log.set_serialize_value

---

kong/runloop/plugin_servers/process.lua
kong/templates/kong_defaults.lua

The multi-pluginserver feature (AKA external-plugins, #6600 ) requires a new configuration style to allow the user to define how to run several pluginserver processes.  This patch provides backwards compatibility by detecting the old settings (`go_plugins_dir` and `go_pluginserver_exe`) and reading as if the equivalent "new style" was written.
It also restores compatibility with the old go-pluginserver (v0.5.0) which didn't have the `-dump-all-plugins` feature.  Instead it asks for each configured plugin.

handle old config styles

---

kong/plugins/request-size-limiting/handler.lua
kong/plugins/request-size-limiting/schema.lua
spec/03-plugins/12-request-size-limiting/01-access_spec.lua
spec/helpers.lua

Adds an option to the "request-size-limit" plugin to require the "content-length" header. If this is set it will prevent the plugin from trying to read the full body, which actually is behaviour counter to what the plugin is supposed to do. So this new option provides better protection.

feat(request-size) option to require content-length header

---

kong/api/routes/config.lua
kong/api/routes/kong.lua
kong/cache/init.lua
kong/cmd/reload.lua
kong/constants.lua
kong/db/declarative/init.lua
kong/global.lua
kong/globalpatches.lua
kong/init.lua
kong/runloop/handler.lua
spec/02-integration/02-cmd/03-reload_spec.lua
spec/02-integration/11-dbless/01-respawn_spec.lua

The `reset_kong_shm` logic was reworked after finding out multiple issues with it. One of such issue was reported here: #6464
And there are instructions how to reproduce it. We found further issues when doing parallel reloads, uploads of new configs and crashing workers at the same time.
This also removes flushing of non-paged shared dictionaries as that is problematic with reloads, as there can be old and new workers at the same time. It also prevents the usage of `:8001/config` during the reload.
There are some commits before this final fix for the issues that were found during fixing the main issue or along the way (I will make another PR for other issues that I also found during this work).
Fix #6464

fix(cli) reset kong shm rework on reload

---

kong/runloop/plugin_servers/mp_rpc.lua

the `msg_id` field in every packet helps associate call and return packets.  Each call increments a counter, but the result should be local during the call/return cycle to avoid interference from concurrent HTTP requests.

fix(ext-plugin): msg_id scope per-connection, not per-pluginserver

---

kong/cmd/migrations.lua
kong/cmd/start.lua
spec/02-integration/05-proxy/27-lua-ssl-trusted-cert_spec.lua

The commit 1e6afa171272a12a1577c7f7e172a5a0cac4ca30 introduced a
regression for a case where we want to enable verification of database
certificates when doing SSL handshake connections. For example, if we
wanted to specify `pg_ssl = on` and `pg_ssl_verify = on` to enable
verification of the postgres certificate, the following error would be
thrown:
```
Error:
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:220: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: error loading CA locations (No such file or directory)
[C]: in function 'assert'
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:220: in function 'cmd_exec'
/usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:96> …
```

fix(conf) prepare prefix to combine trusted certs

---

kong/plugins/response-transformer/handler.lua
kong/plugins/response-transformer/schema.lua
spec/03-plugins/15-response-transformer/03-api_spec.lua

It was reported by @rmlodzikowski-nokia on issue #6707 that you can configure `response-transformer` with settings that
can lead for runtime error. There were two possible fixes:
1. handle `nulls` on runtime
2. do not allow `nulls` in config
For this PR I picked the `2.` as I think it is better to make arrays `required` rather than adding `null` handling code in
code. The arrays default to empty array `{}`, so `required` here does not mean that you need to actively give a value,
it just means that you cannot actively give `null`.
Similar PR will be opened on `request-transformer`.
Fix #6707

fix(response-transformer) do not allow nulls in arrays

---

kong-2.2.1-0.rockspec
kong.conf.default
kong/conf_loader/init.lua
kong/templates/kong_defaults.lua
kong/tools/sandbox.lua
spec/01-unit/020-sandbox_spec.lua

Some Kong functionality (present and future) and plugins uses arbitrary lua code, which provides the most definitive way of extending usage. This comes with its own security problems:
* Not all users will use this feature
* Every kong part and plugin loads arbitrary lua differently
* On unsecured kong deploys, opens up a security door depending on what environment context is allowed to the lua code.
Point is, there's no silver bullet to accept or disable this functionality, and it will depend on what every kong user wants or expects from their installation.
This PR proposes:
* Adding `sandbox.lua` as a dependency https://github.com/kikito/sandbox.lua/pull/2 (currently embedded on this PR with some modifications) to run these on a restricted sandbox. We can add that as a requirement on the …

feat(kong) add sandbox and sandbox_helpers

---

kong/db/schema/others/declarative_config.lua

It was reported on #6547 that each time a new configuration is loaded to Kong the memory is leaked. On the issue thread there are information of the where the leak starts and where the actual leak happens.
See: https://github.com/Kong/kong/issues/6547#issuecomment-754609973
and: https://github.com/Kong/kong/issues/6547#issuecomment-754869338
This PR changes the code so that we only (lazy) load the `full schema` that is needed for `full validation` only once and then we store that into partial schema. This means that we are not constantly re-creating the fullschema that seems to be cached differently inside `schema.lua` on each invocation as it uses tables as cache keys and the load seem to make new tables for fields each time we call `Declarative.load`.
I am not 100% sure does it remove …

fix(declarative) lazy load full schema for validation and store it in partial schema

---

kong/init.lua
spec/02-integration/05-proxy/24-buffered_spec.lua

In #6726 @danielki33 reported that on upstream connection errors with buffered proxying we return `500` instead of `501` and that runtime error was logged. This PR fixes that.
Fix #6726

fix(proxy) return 502 on connectivity errors with buffered proxying

---

spec/fixtures/https_server.lua
spec/fixtures/mock_webserver_tpl.lua

The new HTTPS mock server based on Nginx was not being properly configured for IPv6 addresses.

fix(fixtures) listen for ipv6 in mock webserver

---

kong-2.3.0-0.rockspec

This update is required for the latest version of OpenResty: A compatibility change with how a number is converted from a pattern has caused a issue with how queries with an affected row count return.
- Lua pattern to number compatibility fix (John Regan @jprjr)
- Support for Lua 5.1 through 5.4 (John Regan @jprjr)
- Fix bug where SSL version was not being passed when using LuaSec (Murillo Paula @murillopaula)
- Default to TLS v1.2 when using LuaSec
- Luabitop is no longer automatically installed as a default dependency (for Lua version compatibility)
- Migrate test suite from Travis to GitHub actions. Test suite now uses docker to spawn test postgres servers

chore(deps) bump pgmoon to 1.12.0

---

kong-2.3.0-0.rockspec

@RyouZhang reported with #6739 that Kong starts to spin CPUs 100% with `2.3.0` when healthchecks are enabled. @murillopaula confirmed it and gave additional information and we could reproduce it easily.
We identified an issue in lua-resty-dns-client 5.2.1 together with @Tieske and @locao, fixed it.
This PR bumps the Kong dependency to the fixed version of the library.
Fix #6739

chore(deps) bump lua-resty-dns-client to 5.2.1

---

scripts/make-prerelease-release

scripts/make-prerelease-release  accepts `-rc.X` versions and no special treatment of rc.1 (maybe there was some "almost final" steps?)

accept RC prereleases

---

kong-2.3.0-0.rockspec

- **aux/nginx:** only show warning message when function is being called [9964a6d](https://github.com/fffonion/lua-resty-openssl/commit/9964a6d29aded1c0d06c1a8700ee313e08506c2f)
- **openssl:** not load ssl modules by default [390ad79](https://github.com/fffonion/lua-resty-openssl/commit/390ad79c413ec779ff7a1ad2b86ff0fe389c085d)
- **ssl:** add function to free the verify callback function [62dc81a](https://github.com/fffonion/lua-resty-openssl/commit/62dc81a4c7be1c745e7e3ab728f3e060c981f446)
- **pkcs12:** allow to define algorithm to encrypt key and cert [b9678ce](https://github.com/fffonion/lua-resty-openssl/commit/b9678ce4ee4a233fb0bd8ed61d41c6d45a6fbb9d)
- **pkcs12:** check on cert and key mismatch [5953cc2](https://github.com/fffonion/lua-resty-openssl/commit/5953cc281cff06027f3b2bba234 …

chore(deps) bump lua-resty-openssl to 0.6.11

---

Jenkinsfile

`tag pattern` is not working in the context of `when` / `allOf`

chore(ci) fix jenkins conditional stage failure

---

kong/api/endpoints.lua
kong/db/dao/init.lua
kong/db/schema/typedefs.lua
spec/02-integration/03-db/07-tags_spec.lua
spec/02-integration/04-admin_api/14-tags_spec.lua

This change expands the range of accepted characters in tags from a limited set of ASCII characters to almost all utf-8 sequences.
Exceptions:
* ',' and '/' are reserved for filtering tags with "and" and "or" and are not allowed in tags
* Non-printable ASCII (like the space character, ' ') is not allowed
Attempting to tag an entity with an invalid utf-8 sequence will raise an error.
Closes #5451

feat(tags) allow utf-8 in tags

---

kong/pdk/cluster.lua

autodoc tool to not generate the corresponding documentation for it

fix(pdk) fix incorrect module name for `kong.pdk.cluster`, which caused

---

kong/runloop/handler.lua

Sets cache values:
- `"router:version"`
- `"plugins_iterator:version"`
to `init` for a fresh workers.

fix(cache) always set router and plugin iterator versions to "init" even on reloads

---

Makefile

* Add. Support Lua 5.4
* Add. thread:interrupt() method
* Fix. Handling error without string message
- Support multiple elliptic curves under OpenSSL 1.1.1+
- Improve support for Lua 5.4 (not longer require bit library to be installed)
- Ignore delayed RST_STREAM frames in HTTP 2

chore(deps) bump dev/testing deps to latest

---

kong/cmd/migrations.lua
spec/02-integration/02-cmd/10-migrations_spec.lua

to override the default prefix
In https://github.com/Kong/kong/pull/6650 we decided to create the combined cert under the prefix directory. However, we forgot to add the `-p` or `--prefix` option support which means when user runs `kong migrations` command as non-privileged user, the following error will be shown with no way to get around (unless run as `root`):
```
prefix directory /usr/local/kong not found, trying to create it
Error: Permission denied
```

fix(cmd) `kong migrations` should accept the `-p` or `--prefix` option

---

kong.conf.default

address some outdated information regarding `client_ssl_*`

docs(conf) add description for alternate certificate support of Kong and

---

kong/init.lua
kong/runloop/handler.lua

This commit changes the code to check not run certain initialization on certain modes:
1. do not build router on control planes
1. do not execute cache warmup on control planes
2. do not start plugin servers on control planes
3. do not initialize balancer on control planes (also disables healthchecks)
4. do not start async router rebuild timer on control planes
5. do not start async plugin iterator rebuild timer on control planes
6. do not subscribe on events with dbless

fix(*) do not run non-needed code on roles that don't need them

---

kong/plugins/hmac-auth/access.lua
kong/plugins/hmac-auth/handler.lua
spec/03-plugins/19-hmac-auth/03-access_spec.lua

It was reported as part of the issue #6804 that `hmac-auth` plugin has a bug in one if statement. This commit fixes that.
It didn't cause any security issues as it was catched later on, but still it is good to fix this.

fix(hmac-auth) fix issue with validation if-statement

---

kong.conf.default

@juumixx reported on #6823 about a left-over note in our configuration docs. This commit removes the note.
Fix #6823

fix(docs) remove note on ssl on stream_listen

---

kong/api/routes/kong.lua
kong/globalpatches.lua
spec/02-integration/02-cmd/03-reload_spec.lua
spec/02-integration/04-admin_api/02-kong_routes_spec.lua
spec/02-integration/11-dbless/01-respawn_spec.lua

- Removes `prng_seeds` from shared dictionaries
- Removes `prng_seeds` from local variable
- Removes `prng_seeds` from `:8001/`
- Adds `pids` to `:8001/`

fix(admin) do not send prng_seeds but instead send pids

---

kong-2.3.2-0.rockspec

chore(rockspec) bump lua-resty-healthcheck to 1.4.1

---

kong/init.lua
kong/runloop/balancer.lua

There seems to be a bug where we didn't pass `ctx` always to `balancer.execute`, this should fix it.

fix(balancer) pass ctx to balancer.execute

---

kong/api/api_helpers.lua
kong/api/routes/config.lua
kong/db/declarative/init.lua
spec/02-integration/04-admin_api/15-off_spec.lua

This PR adds a way to load declarative config as an inline YAML file.
Previously it was possible only as a YAML string inside the the `config` JSON payload. Now JSON and YAML have parity of ways to being loaded.
In addition to that fix, the reading algorithm has been changed so that JSON is always tried first, then YAML, then Lua (when enabled).
This fixes a previous problem in which the YAML parser was used erroneously to parse JSON configs.
This last fix is what made us make those slight changes in the tests. Things like trailing commas were accepted by the YAML parser but are not valid JSON.

fix(admin-api) declarative config json/yaml loading

---

kong-2.3.2-0.rockspec

- ***:** support BoringSSL [9c4e5dc](https://github.com/fffonion/lua-resty-openssl/commit/9c4e5dccefb7fa2e08c489e2922ea05e043e28f2)
- **bn:** add generate_prime [2cc77a4](https://github.com/fffonion/lua-resty-openssl/commit/2cc77a4513dad2f4d684535d1230484e8e91bfbd)
- **openssl:** add function to list supported cipher and digest algorithms [5bdc2a4](https://github.com/fffonion/lua-resty-openssl/commit/5bdc2a406c974f471331636de670915df9386f82)
- **openssl:** add function to get and set fips mode [f6de183](https://github.com/fffonion/lua-resty-openssl/commit/f6de183b19e57616ded39e73518acd198c730056)
- **csr:** count extension count in openssl 3.0 [5af0f4b](https://github.com/fffonion/lua-resty-openssl/commit/5af0f4b02edd0fb8c461a1e08b04eb4eb781f744)
- **csr:** BREAKING: remove …

chore(deps) bump resty-openssl from 0.6.11 to 0.7.0

---

kong-2.3.2-0.rockspec

This bumps the lua-cassandra dep. The new lua-cassandra changes [1]
impact the selection of SSL/TLS protocol chosen during the handshake
negotiation. Prior, the version was hardcoded to 'tlsv1'. Now, the
client will select the highest version available out of the following
allowable values: 'tlsv1_1', 'tlsv1_2', 'tlsv1_3'.
This fixes https://konghq.atlassian.net/browse/FTI-2249
[1] - https://github.com/thibaultcha/lua-cassandra/commit/d742d5ca844a23da487b8f33e67559ff369e62a9
Signed-off-by: Jeremy J. Miller <jeremy.miller@konghq.com>

chore(deps) bump lua-cassandra to 1.5.1 (FTI-2249)

---

Makefile

Golang binaries can give false positives to `make lint` because they
might include a `#o` pattern.

chore(makefile) lint: ignore binary files

---

kong/init.lua
kong/pdk/log.lua
spec/fixtures/custom_plugins/kong/plugins/ctx-tests/handler.lua

`kong.log.serialize()` did its own calculation of Kong proxy latency that didn't account all the latencies (e.g. SSL).

fix(pdk) kong.log.serialize to use KONG_PROXY_LATENCY

---

kong/init.lua
kong/plugins/base_plugin.lua
kong/runloop/handler.lua
kong/runloop/plugins_iterator.lua
spec/02-integration/05-proxy/28-stream_plugins_triggering_spec.lua
spec/fixtures/custom_plugins/kong/plugins/logger-last/handler.lua
spec/fixtures/custom_plugins/kong/plugins/logger/handler.lua
spec/fixtures/custom_plugins/kong/plugins/logger/schema.lua

For historical purposes (service mesh era) the stream module ssl phase was implemented differently. As we have dropped service mesh and moved to a more standard Nginx, we can re-enable the ssl_certificate phase on plugins in `stream` module. This commit does that.

 feat(proxy) enable ssl_certificate phase on plugins with stream module

---

kong/init.lua

This was already added to other `stash_ref` calls, so here is the last place.

perf(proxy) pass ctx to stash_ref

---

kong/router.lua
spec/fixtures/router_path_handling_tests.lua

The PR #6821 by @dndx implemented path normalization, but there is another case with path stripping where
the uri postfix is not sanitized correctly for a better security. This commit fixes that.

fix(router) sanitize path postfix

---

kong/runloop/balancer.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua
spec/02-integration/05-proxy/10-balancer/05-stress.lua
spec/fixtures/balancer_utils.lua
spec/fixtures/mock_webserver_tpl.lua
spec/helpers.lua

When using eventual worker consistency, instead of trying to synchronize
all workers using a shared dictionary, share the events, and let each
worker deal with its updates.
This PR also fixes several IPv6 issues in balancer tests.

fix(balancer) use a FIFO for eventual consistency updates

---

kong.conf.default

Fixing formatting so that autodoc scripts render the parameters correctly. 
At the moment, all three sandbox parameters render as one: https://docs.konghq.com/gateway-oss/2.3.x/configuration/#untrusted_lua
Improving descriptions for `untrusted_lua` and `untrusted_lua_sandbox_requires` based on input from Luis. 
Note, there is a link to https://github.com/kikito/sandbox.lua/blob/master/sandbox.lua for the full allowed/disallowed list, as I didn't want to duplicate all of that and have an doc update dependency. I think that's fine?
N/A
N/A

fix(conf) Fix formatting for sandbox properties

---

.ci/run_tests.sh

The kong-prometheus-plugin test suite was disabled as it is flaky right now.

chore(ci) disable kong-prometheus-plugin test suite

---

scripts/make-patch-release

This is no longer needed; current sed usage is compatible
with both GNU sed and BSD sed (as found in MacOS).

chore(scripts) do not check for gnu sed

---

kong/init.lua
spec/02-integration/05-proxy/09-websockets_spec.lua

We cannot really do buffered responses with e.g. websocket connection upgrades. This commit disables the response buffering on connection upgrades.

fix(proxy) disable buffered responses on connection upgrades

---

kong/db/migrations/state.lua
spec/02-integration/03-db/06-migrations_state_spec.lua

The `pairs` iteration over `plugin_names` makes running migrations inconsistent - the order in which the subsystems are loaded changes randomly.
This PR stops the random order by sorting the subsystems alphabetically, so at least the order in which migrations are executed is constant.
Sorting things this way is better than having no order at all, but the ideal solution would be sorting plugins topologically (so a plugin having entities depending on another plugin will be loaded later).

fix(migrations) sort subsystems alphabetically

---

kong/cache/warmup.lua
spec/01-unit/01-db/08-cache_warmup_spec.lua

When an upstream name is used as a service hosts entry, it should not be warmed-up, as it's not a real DNS entry.

perf(warmup) do not warmup upstream names

---

kong-2.3.3-0.rockspec

- Support lazy loading route actions from route name to module name #710
- Add UTF8 helper module, lapis.utf8, for identifying single UTF8 chars and whitespace (lpeg patterns that can be used for trimming and sanitization)
- Add cascade option to postgres drop index schema function
- Remove unused mimetypes dependency
- If yield_error or assert_error are not captured by a outer coroutine then a hard error will happen
- Request\add_params does not need a name
- When searching for OpenResty installation, also accept a binary named openresty (for openresty install on mac with brew)
- pgmoon connection error messages are prefixed with “postgres” to make them easier to identify
- remove excess ; characters in generated SQL for some postgres schema functions
- Postgres create index schema …

chore(deps) bump kong-lapis from 1.8.1.2 to 1.8.3.1

---

kong/db/strategies/cassandra/init.lua
spec/02-integration/04-admin_api/14-tags_spec.lua

This is consistent with what the PostgreSQL strategy and our docs.
Fixes #6779

fix(db) ignore tags in Cassandra when filtering by multiple entities

---

kong/runloop/plugin_servers/process.lua

and not start plugin server in unsupported stream subsystem
The current mode of `spawn` will left the plugin server alive after Kong exits. This PR prefix command
with `exec` so that `sh` is replaced by the actual process.
This can be alternatively done by providing a table to `ngx_pipe.spawn`, which may be more ideal (but is
also harder to do right since we will then need to seperate argument by spaces).
Also the plugin server is now not started in stream subsystem as ngx.pipe seems not supported in stream
subsystem.
* Use exec on the spawned plugin server
* Don't start plugin server in unsupported stream subsystem
See also https://github.com/openresty/lua-nginx-module/issues/1855

fix(external_plugins) exec on the spawned plugin server

---

kong/plugins/oauth2/access.lua
kong/plugins/oauth2/handler.lua
spec/03-plugins/25-oauth2/03-access_spec.lua

@jeremyjpj0916, sorry I tried to push to your PR https://github.com/Kong/kong/pull/6337, but I just don't seem to handle `git` too well. And that got closed. I reopened it here with some small changes.
Fixes: https://github.com/Kong/kong/issues/6311
^^ Full discussion and examples over here. My changes fix 2 scenarios I can see Kong not responding as I would expect to an end user. 1 was type error fix(by validating a scenario where bad user input yields a boolean reference not a string), other requires thinking about it a little deeper to return the right response to clients. 
* Add better handling in ```get_redirect_uris``` when fields are not present ```client_id``` ends up being a boolean parameter. Potentially fixes could have been done alternatively in the ```retrieve_parameters``` …

fix(oauth2) handle more client invalid token generation cases

---

kong/db/schema/entities/targets.lua
kong/db/schema/entities/upstreams.lua
spec/01-unit/01-db/01-schema/08-targets_spec.lua
spec/01-unit/01-db/01-schema/09-upstreams_spec.lua
spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua

I screwed, sorry @WALL-E, I tried to rebase your original: https://github.com/Kong/kong/pull/6400, but then mistakenly pushes next branch to your next branch, while I was meaning to push the rebased one. Then it closed the PR and I could not push anymore to your branch, Thus here it is again. If this goes green I think we can merge it. Thank you @WALL-E  and sorry for inconvenience.

fix(schema) more descriptive error logs when type is invalid

---

.ci/run_tests.sh

The kong-prometheus-plugin test suite was disabled as it is flaky right
now.

chore(ci) disable kong-prometheus-plugin test suite (#6896)

---

kong/plugins/rate-limiting/schema.lua
kong/plugins/response-ratelimiting/schema.lua
spec/03-plugins/23-rate-limiting/03-api_spec.lua

Some plugins have default options that don't work well with `dbless` or `hybrid` deployments mostly because the database is not available on gateway nodes. This PR adjusts defaults and validation rules on those plugins.

feat(plugins) role based defaults

---

kong-2.3.3-0.rockspec

Zipkin 1.3.0 is totally backwards compatible with 1.2.0 but brings fixes
and new features.
Before this change can be merged,
* https://github.com/Kong/kong-plugin-zipkin/pull/107 needs to be approved and merged,
* A new tag of the plugin needs to be published in the zipkin repo
* A new version of the zipkin plugin needs to be published in Luarocks
* ...
Fix #XXX

chore(deps) bump Zipkin to 1.3.0

---

kong/db/declarative/init.lua
kong/db/schema/others/declarative_config.lua
kong/db/schema/topological_sort.lua
kong/db/strategies/postgres/connector.lua
kong/tools/utils.lua
spec/01-unit/01-db/01-schema/12-topological_sort_spec.lua
spec/01-unit/01-db/06-postgres_spec.lua
spec/01-unit/05-utils_spec.lua

This fix to the topological sort function introduces these changes:
* The main algorithm has been abstracted away into utils. It can now topologically sort anything, not just schemas.
* When sorting schemas, core entities will be considered before plugin entities - this avoid problems when plugin entities use core entities but don't explicitly depend on them.
* It will try to sort schemas alphabetically when possible
* The end result will still be topologically sorted, but now it will be constant.
We use topological sorting in two places:
* The PostgreSQL connector uses it to sort table names (it replaces a custom toposort implementation)
* Declarative Config uses it to sort entities for loading
Note that the previous "special treatment of workspaces" is now part of the "prioritize core …

fix(db) topological sort prioritizes core

---

CHANGELOG.md

As 2.2.2 was a backport release, changes in the release branch did not make it to master. Thus, changelog entries for 2.2.2 are missing in master.

docs(changelog) add 2.2.2 entries

---

kong/db/schema/typedefs.lua
kong/plugins/file-log/handler.lua
kong/plugins/file-log/schema.lua
kong/plugins/http-log/handler.lua
kong/plugins/http-log/schema.lua
kong/plugins/loggly/handler.lua
kong/plugins/loggly/schema.lua
kong/plugins/syslog/handler.lua
kong/plugins/syslog/schema.lua
kong/plugins/tcp-log/handler.lua
kong/plugins/tcp-log/schema.lua
kong/plugins/udp-log/handler.lua
kong/plugins/udp-log/schema.lua
spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua
spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua
spec/03-plugins/02-udp-log/01-udp-log_spec.lua
spec/03-plugins/03-http-log/01-log_spec.lua
spec/03-plugins/03-http-log/02-schema_spec.lua
spec/03-plugins/04-file-log/01-log_spec.lua
spec/03-plugins/04-file-log/02-schema_spec.lua
spec/03-plugins/05-syslog/01-log_spec.lua
spec/03-plugins/07-loggly/01-log_spec.lua
spec/kong_tests.conf

Add capability to set new log fields, or unset existing fields, by
executing custom Lua code in the Log phase.
This feature uses the new PDK method `kong.log.set_serialize_value`,
as well as the new sandbox capability, both introduced in Kong 2.3.
Currently supported logging plugins:
* file-log
* Loggly
* Syslog
* tcp-log
* udp-log
* http-log
Not included in:
* Datadog
*  Statsd

feat(plugins) add log by lua capability

---

kong/clustering.lua
spec/02-integration/09-hybrid_mode/01-sync_spec.lua
spec/fixtures/custom_plugins/kong/plugins/dummy/handler.lua
spec/helpers.lua

Hybrid mode version check is now changed into a relaxed form:
- DP is allowed to connect to CP that has at most two minor versions ahead
- Version check in plugins is same as Kong itself
- DP is allowed to have superset list of plugins to CP
- DP is not allowed to connect if major version mismatch, or it's newer than CP, or it misses plugins from CP.
* Implement relaxed version compatibility check in hybrid mode allowing DP to lag two minor versions behind
Fix #XXX

feat(clustering) relax version compatibility check to allow DP lagging 2 minor versions behind

---

kong-2.4.0beta.2-0.rockspec

- ***:** redefine callback functions to a style FFI will not overflow [f91202c](https://github.com/fffonion/lua-resty-openssl/commit/f91202c57b826d935d831ec452d2b90fc33277fa)
- **altname:** return unsupported as value in not implemented types [ef5e1ed](https://github.com/fffonion/lua-resty-openssl/commit/ef5e1eda9eaea1fd4c8d7d65e438275fed10cdc6)
- **auxiliary/nginx:** typo in error message [4bd22d8](https://github.com/fffonion/lua-resty-openssl/commit/4bd22d81419ed160af1dcea16f42fd284f8f2ad5

chore(deps) bump lua-resty-openssl from 0.7.0 to 0.7.2

---

kong/pdk/table.lua

Most likely the culprit is the missing `@function` tag
@lena-larionova @tlblessing fyi. Created PR here since docs are rendered from this file.

docs(pdk) fix kong.table.merge ldoc comment

---

kong/runloop/plugin_servers/process.lua

On Kong reload or other graceful shutdown of the nginx workers, the
pluginservers were not closed, making the worker linger until explicitly
killed.
Now the log capture loop exits when the worker is exiting, allowing the
pluginserver to be killed when the pipe object is GC'ed
Fix #6904
Fix #6948

fix(external-plugins) close pluginserver when exiting worker

---

kong/runloop/plugin_servers/process.lua

two related issues:
- the new config style is detected by the `pluginserver_names` setting,
but the default is an empty table, thus it's never falsy, and the old
configuration style is never attempted
- the pluginserver names serve to tie the other configuration fields,
but those fieldnames are lowercased, so the pluginserver names must be
lowered too.
Fix #6840

fix(go) - go-pluginserve config

---

kong/runloop/plugin_servers/pb_rpc.lua

seems most (all?) Linux variants use `/usr/include` for protobuf
"standard" files, but Homebrew uses `/usr/local/opt/protobuf/include`

fix(external-plugins) - add macos include path

---

kong/plugins/rate-limiting/handler.lua
kong/plugins/rate-limiting/policies/cluster.lua
kong/plugins/response-ratelimiting/handler.lua
kong/plugins/response-ratelimiting/policies/cluster.lua

Postgres parameters were not properly escaped with the following plugins:
- `rate-limiting`
- `response-ratelimiting`
This PR fixes that.

fix(plugins) properly escape postgres sql parameters

---

kong/pdk/service/request.lua
t/01-pdk/06-service-request/04-set_path.t

unreserved list of RFC 3986 when calling `kong.service.request.set_path()`
to avoid proxy failures later

fix(PDK) auto-escape characters that are not in the reserved and

---

kong/db/schema/entities/routes.lua
kong/router.lua
spec/01-unit/08-router_spec.lua

regex detection first, then depending on the type of path use URI
normalization or regex normalization
Regex normalization is similar to URI normalization, except:
1. It does not merge slashes
2. If after percent decoding the character becomes a PCRE meta
character, then it will be escaped

fix(router) properly normalize paths inside Route object by running

---

kong/pluginsocket.proto

fix(go)  ports are ints, not strings

---

kong-2.4.0beta.2-0.rockspec
kong/runloop/plugin_servers/pb_rpc.lua

- Add missing lua-protobuf to rockspec
- Refactor `parsefile`, so it looks in common development and production locations

refactor(*) go pb rpc

---

kong.conf.default
kong/conf_loader/init.lua
kong/templates/kong_defaults.lua
spec/01-unit/03-conf_loader_spec.lua

protocols < 1.2 in cosocket and bumping the pgmoon dependency to the
latest which includes the LuaSec TLS 1.2 support. fixes #6645
Postgres >= 12 requires TLS >= 1.2 to connect. Since TLS < 1.2 has known
vulnerabilities, we will disable older versions of support in OpenResty
cosocket by default, but leave the option for users to re-enable them
if so desire.
Tested locally with latest Postgres 13 with TLS enforced and both migrations as well as proxy features works well after the change.

fix(postgres) support connecting to Postgres >= 12 by disabling SSL/TLS < 1.2

---

kong-2.3.3-0.rockspec
scripts/update-copyright

Also a repo is now available, allowing to remove the special
case from the copyright-collecting script
Info here: https://github.com/lunarmodules/luasyslog#201-released-24-mar-2021

deps(luasyslog) bump to 2.0.1 fixing a potential memory issue

---

kong/runloop/balancer.lua

There may be cases where an upstream is not yet loaded on `init` and
`init_worker` phases (for example, failure on reading the upstreams
list in the `init()` function) and because of that, after these init
phases, we will just always return a `503` to the client with the error
`"name resolution failed"` since the dns-client lib will return a
`"dns server error: 3 name error"` to Kong. So we can't assume the
upstream doesn't exist just because we are past the init phases.
This applies to both the `strict` and `eventual` balancer worker
consistencies.
This is complementing https://github.com/Kong/kong/pull/7002
Fix #6812

fix(balancer) don't assume upstreams don't exist after init phases

---

.github/stale.yml

Added probot-stale app: after a period of inactivity, a label will be applied to mark an issue as stale, and optionally post a comment to notify contributors

chore(ci) add github probot-stale app config

---

kong/clustering.lua

@hutchic reported in #6935 that:
> When the control plane looses it's database connection it's currently unable to send updates to new data planes.
This PR is about to make control plane more resilient on database failures on such case.
Fix #6935

feat(clustering) resilient initial config on control plane database failures

---

kong/cmd/migrations.lua
kong/cmd/utils/prefix_handler.lua

The nginx configuration files are usually rewritten from configuration
and template on each restart/reload.  This also happens on `migration`
commands, as part of the configuration loading.  This can be
undesirable, especially when using a custom templace, since these
commands don't admit a `--nginx-conf` argument, so they always use the
default template, reverting customization.
Given that these commands don't restart/reload the nginx process,
there's no benefit in writing the config files.  This patch skips the
writing (and verifying) steps on those commands.
Fix #6917

fix(cli) don't overwrite config files on migration commands

---

UPGRADE.md
autodoc/upgrading/generate.lua
scripts/autodoc

This PR introduces a new autodoc tool which produces updating.md, a smaller version of UPGRADE.md used in docs.konghq.com.
The PR also modifies our 2.3.0 UPGRADE.md instructions so that they match the modifications in the updating.md made by the docs team, although there are some differences (some formatting had to be sacrificed in order for the doc to work in both the docs page and as as standalone markdown file)
We still need to create the installation instructions for 2.4.0, that will come in a separate PR, using this one as a base.

docs(autodoc) autodoc tool for splitting upgrade.md doc

---

kong/clustering.lua

@hutchic reported in #6935 that:
> When the control plane looses it's database connection it's currently unable to send
> updates to new data planes.
This PR is about to make control plane more resilient on database failures on
such case.
Fix #6935

feat(clustering) resilient initial config on control plane database failures (#6938)

---

kong.conf.default
kong/conf_loader/init.lua
kong/templates/kong_defaults.lua
kong/templates/nginx_kong_stream.lua
spec/01-unit/04-prefix_handler_spec.lua

This change fixes the stream template configuration to allow custom access logs formats. To differente the HTTP proxy from the stream access logs I added the `PROXY_STREAM_ACCESS_LOG` keeping the current default.
When using kong with TCP I can't use a custom log format. Since `PROXY_ACCESS_LOG` is used in the `nginx_kong_stream.lua` and `nginx_kong.lua` templates, I thought it would be nice to follow the same interpolation pattern in both places.
In my use case I have both TCP streams and HTTP request configured in Kong. 
When I try to customize my http access log with the example env vars:
```
NGINX_HTTP_LOG_FORMAT: custom 'any format'
PROXY_ACCESS_LOG: /dev/stdout custom
```
I get the following error because the rendered template is invalid `/dev/stdout custom basic`:
```
Error: could …
```

fix(template) standardize access_log template config

---

kong/runloop/handler.lua
spec/02-integration/05-proxy/07-upstream_timeouts_spec.lua

The balancer tries states are saved when retrying. The last retry is never saved, as there are no more retries. This change saves the failure state so it can be correctly logged.
Fix #6820

fix(handler) save failed try status to log it

---

kong/plugins/hmac-auth/access.lua
spec/03-plugins/19-hmac-auth/03-access_spec.lua

which is introduced in later versions of the "Signing HTTP Messages"
RFC. closes #3789
Previously the Kong implementation of the RFC included a signing
parameter "request-line" which contains the HTTP request method and
request URI plus the HTTP version number. This is not part of the RFC
draft, and has created issue such as #3789 where changing the HTTP
request version by intermediary proxy caused the signature validation to
fail.
In general, including the HTTP protocol version inside the signature
makes little sense, as the protocol does not identify the resource that
is being accessed, and can be changed by clients/proxies which still
preserving the original semantics of the request.
This PR adopts the "@request-target" field as described inside …

feat(hmac-auth) add support for the "@request-target" field support

---

kong/pdk/private/phases.lua
kong/pdk/response.lua
kong/runloop/plugin_servers/init.lua
kong/runloop/plugin_servers/mp_rpc.lua
kong/runloop/plugin_servers/pb_rpc.lua

The `kong.response.get_XXX()` functions require data from the response
object, which is no longer accessible in the "post-log" timer used to
call Log handlers in external plugins.
This patch allows those functions to work by adding the required data to
the set saved at the start of the "real" log phase.
Fix Kong/go-pdk#61

fix(external-plugins)  response.getXXX() functions from log phase

---

kong-2.4.0-0.rockspec

This PR needs Kong/kong-plugin-prometheus#125 to
be approved and merged, the new tag for prometheus created, and a new
rockspec pushed, before it can be merged.

chore(deps) bump prometheus plugin to 1.2.1

---

README.md

Fix some minor grammatical errors.
* Hyphenate a word
* Add oxford commas (best practice)
* Fix plurality ("suites" implies plurality so the "tests" is superfluous)

docs(readme) Fix Grammatical Errors

---

kong/db/dao/targets.lua
spec/02-integration/02-cmd/11-config_spec.lua

Since Kong version 2.2.0, target entities behave as any other entity, but their `upsert` function was not prepared for that.

fix(dao) upsert existent targets

---

kong/tools/stream_api.lua
spec/02-integration/12-stream_api/01-stream_api_endpoint_spec.lua
spec/fixtures/custom_nginx.template

- the config template used for tests was missing the inter-module RPC
socket
- to reuse the data-gathering function on both HTTP and Stream modules,
the RPC message should support array of strings, just like `ngx.print()`.
- prefix errors with the intent.  "connection closed" is far too
ambiguous.

fix(core): RPC - test config template, array of strings, better errors

---

Makefile

Now uses binary package again.

chore(deps) bump grpcurl version to 1.8.0

---

kong-2.4.0-0.rockspec

Fixes some small dependency version pinning issues.

fix(deps) pin dependencies for lua-protobuf and remove patch pinning from prometheus-plugin

---

kong/templates/nginx_kong_stream.lua

`kong.pdk.node` iterrates through ngx.shared magic table to
get list of shdict metrics, implement the __pairs metamethod so
it's happy.
* fix(template) fix iterrator in stream shdict
See also https://github.com/Kong/kong-plugin-prometheus/pull/118

fix(template) fix iterator in stream shdict

---

kong/runloop/balancer.lua

here the `i` variable is an index to a copy of the event queue, but
then it's used to remove the event from the original queue.  As soon as
one item is removed, the indexes don't match and the wrong event is
removed.
this patch works on the first event and then removes the first item on
each iteration.
If an event results in an error, the loop is aborted and it's not
removed from the queue, just as previously.  If the error is
persistent, no other event is processed.  Consider moving failed events
to the tail of the queue.

fix(balancer) remove the correct upstream event from queue

---

Makefile

As soon as we want to upgrade `grpcurl` this will need to not be hardcoded
* fix(build) Do not hardcode grpcurl version when downloading
N/A

fix(build) Do not hardcode grpcurl version when downloading

---

kong/plugins/hmac-auth/handler.lua
kong/plugins/syslog/handler.lua

These plugins should have been bumped in the listed PRs but were missed.
hmac-auth:
https://github.com/Kong/kong/pull/7037
New feature, minor version bump
syslog:
https://github.com/Kong/kong/pull/6081
New feature, minor version bump
* Bumped hmac-auth plugin to 2.3.0
* Bumped syslog plugin to 2.2.0
N/A

fix(core) Bumping some plugins that got missed

---

kong/init.lua
kong/runloop/handler.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua

@dsteinkopf reported on #7054 that when executing a plugins iterator with two subsequent tls keepalive request, the wrong plugin is executed. We found out that we do pass context in ssl phase to plugin iterator and that indeed creates a connection wide structures in that context, which are then shared between different keepalive requests, and thus a wrong plugin might be executed.
This commit changes it so that we do not pass context to plugin iterator with `certificate` phase and thus it won't store data in it.
Huge thanks for @dsteinkopf for reporting this!
Fix #7054

fix(proxy) the context got shared between different tls keepalive requests

---

kong/init.lua
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua
spec/fixtures/custom_plugins/kong/plugins/init-worker-lua-error/handler.lua
spec/fixtures/custom_plugins/kong/plugins/init-worker-lua-error/schema.lua

Previously when a plugin's "init_worker" handler fails, the rest of the
`init_worker` task are no longer executed. Although this is not
something that should happen in normal situation, there are certain
custom plugins that are not written correctly and failed "init_worker"
causes things like Hybrid mode to break because it's `init_worker` code
no longer executes.
This PR allows the Kong node to finish the rest of the initialization
even in case of plugin's "init_worker" handler error. It should improve
the situation because Kong core's initialization generally does not
depend on the outcome of a particular plugin's "init_worker" handler, and
this improves the stability of the product slightly.
Because failed "init_worker" handler is still considered a serious
event, we use the …

fix(plugin_iterator) guard against Lua error that happens inside plugin's "init_worker" handler

---

kong/templates/nginx_kong.lua

Eg. Accessing kong using the "TRACE" method returns a standard nginx error page.
This is because nginx returns a status code of 405.
Adds 405 to the error page settings of nginx config and returns the kong error page.

fix(conf) Added status code 405 to nginx config

---

kong/clustering.lua

@murillopaula let us know about hybrid mode behavior that caused constant flips of data plane configuration even when no change was actively made with admin api.
It turned out that our `clustering` module subscribes to `invalidations`, and on each `invalidations` event it starts to push configs to data planes connected to it. With further look it was also found that the `clustering` module will by itself generate `invalidations` events when it updates the `clustering_data_planes` table about the information of the data plane that connected to it (e.g. last seen status). This caused constant `invalidations` happen across the control plane cluster and then in turn caused constant sending of config and config flips on data planes.
The solution was to make check for handling the `dao:crud` …

fix(clustering) constant cache flips on dp because of invalidations event

---

kong-2.4.0-0.rockspec

- deprecate: `permute.iter`, renamed to `permute.order_iter` (removal later)
[#360](https://github.com/lunarmodules/Penlight/pull/360)
- deprecate: `permute.table`, renamed to `permute.order_table` (removal later)
[#360](https://github.com/lunarmodules/Penlight/pull/360)
- deprecate: `Date` module (removal later)
[#367](https://github.com/lunarmodules/Penlight/pull/367)
- feat: `permute.list_iter` to iterate over different sets of values
[#360](https://github.com/lunarmodules/Penlight/pull/360)
- feat: `permute.list_table` generate table with different sets of values
[#360](https://github.com/lunarmodules/Penlight/pull/360)
- feat: Lua 5.4 'warn' compatibility function
[#366](https://github.com/lunarmodules/Penlight/pull/366)
- feat: deprecation functionality `utils.raise_deprecation` …

chore(deps) bump penlight from 1.9.2 to 1.10.0

---

kong/runloop/handler.lua
spec/01-unit/16-runloop_handler_spec.lua

Previously, the CP could still do health checks upon CRUD upstreams and targets events. The following logs would be shown on the CPs:
```
2021/04/22 13:00:31 [warn] 99#0: *5924 [lua] balancer.lua:259: callback(): [healthchecks] balancer 5349c4d4-0deb-4528-80e1-59bbfe176452:testUps6066_01 reported health status changed to UNHEALTHY, context: ngx.timer
```
This will disable health checks and balancers completely on CPs by not creating worker/cluster events on them.

fix(*) skip upstreams/targets events on control planes

---

kong/db/strategies/off/init.lua
spec/02-integration/03-db/14-dao_spec.lua

`select_by_cache_key` looks up an entity in db or cache with its cache_key. In `off` strategy,
the function delegates to `select_by_key` which ultimately calls `kong.core_cache:get`.
Since `off` strategy already uses the cache_key to populate declarative config into cache,
it's sufficient to use the provided `field` directly into `select_by_key`.
* correct key for select_by_cache_key in off strategy
Fix #XXX

fix(db) correct key for select_by_cache_key in off strategy

---

kong/db/dao/plugins/go.lua
kong/runloop/plugin_servers/mp_rpc.lua
kong/runloop/plugin_servers/pb_rpc.lua

When an instance_id of a plugin external changes, the plugin instance pretended to be reseted and retried in the bridge event loop again.
This was failing and none was being retried, making the call to the plugin did not happen; it was due to a typo in the comparisson.
This has been identified and tested with heavy traffic when the kong balancer is refreshed and reload into memoy cache; it was not failing with low traffic.
Fix https://github.com/Kong/kong/issues/7148

fix(external-plugins): use lowercase for comparing string in error condition

---

kong/tools/kong-lua-sandbox.lua
spec/01-unit/020-sandbox_spec.lua

Reasoning: the idea behind limiting access to string.rep was
disallowing a single operation from allocating too much memory.
Given that in LuaJIT there are no debug hooks, it is trivial to
implement a loop which allocates a lot of memory on every single
iteration.
Plus, given that the `string` table was global and obtainable via any
sandboxed string, its sandboxing provoked issues on the global state.
This change accepts string.rep in sandboxed environments as a practical
compromise.
Fixes #7062
Fixes #7133

fix(sandbox) allow string.rep in sandboxed environments

---

.ci/run_tests.sh
.ci/setup_env_github.sh
.github/workflows/build_and_test.yml
spec/02-integration/02-cmd/10-migrations_spec.lua
spec/02-integration/03-db/07-tags_spec.lua
spec/02-integration/03-db/09-query-semaphore_spec.lua
spec/02-integration/05-proxy/25-upstream_keepalive_spec.lua
spec/02-integration/10-go_plugins/01-reports_spec.lua

Couple of test cases needs to be fixed in order to run correctly. This is because KBT spawns all the dependencies when running even in cases those dependencies are not needed. For example, even in C* and DB-less test mode, Postgres servers are still started. In Actions we only spawns the external dependencies needed for each test scenario, thus exposing those issues.

chore(actions) remove use of KBT based build and caching for CI runs

---

kong/db/migrations/state.lua

When a custom plugin is loaded that is not located in the Kong tree
the user manually sets the Lua-path to locate the plugin. In that
case the assumption that the 'init' files will be found might be
wrong.
Fixes #6867
Fixes #7340

fix(migrations) don't assume '/?/init.lua' in the path

---

.ci/run_tests.sh
.github/workflows/build_and_test.yml

docs generation tests
If docs repo is not found, the `autodoc` tool still runs generation, except skips `cp`ing the output files to the `docs.konghq.com` directory.

chore(ci) remove docs.konghq.com checkout since it is not needed for

---

spec/02-integration/05-proxy/04-plugins_triggering_spec.lua

outputs
The file-log plugin writes log lines asynchronously, but the current
implementation of test code incorrectly assumes the first line it
encounters from the log file always corresponds to the previous request.
This is not 100% true because log lines for other test cases may not
have been flushed yet. This will cause test failures like:
```
FAILED  spec/02-integration/05-proxy/04-plugins_triggering_spec.lua:440: Plugins triggering [#off] short-circuited requests responses.send stops plugin but runloop continues
spec/02-integration/05-proxy/04-plugins_triggering_spec.lua:471: Expected objects to be equal.
Passed in:
(nil)
Expected:
(string) '1d39b630-dd75-456d-8885-0a42c652cc0d'
```
See: https://github.com/Kong/kong/runs/2691542275 for an example of flaky run caused by this issue.
To …

tests(plugins_triggering_spec) reduce flakiness when reading file-log

---

autodoc/admin-api/data/admin-api.lua

The links on the [Admin API 2.4.x page](https://docs.konghq.com/gateway-oss/2.4.x/admin-api/) were broken. I checked [another page](https://github.com/Kong/docs.konghq.com/edit/main/app/gateway-oss/2.4.x/network.md) to see how the product URL was built and then copied the same format.
I also removed link references that are not used on this page (validated by searching for `[clustering]` etc in the source)
* Fix links on Admin API page

Fix relative links in admin-api.lua

---

kong/db/schema/others/declarative_config.lua
spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua

fix(dc) exclude cases where "plugins" are used not as plugins
