kong.conf.default, kong/router.lua, kong/templates/kong_defaults.lua
TODO:
- come up with DoS exploits that would be stopped by this limit
- apply similar limits to other user-input regexes
=> fix(router) limit path regex to a lower backtracking limit

kong-2.4.1-0.rockspec
Changelog from upstream:
- Fix exporter to attach subsystem label to memory stats
[#118](https://github.com/Kong/kong-plugin-prometheus/pull/118)
- Expose dataplane status on control plane, new metrics `data_plane_last_seen`,
`data_plane_config_hash` and `data_plane_version_compatible` are added.
[#98](https://github.com/Kong/kong-plugin-prometheus/pull/98)
=> chore(deps) bump prometheus plugin to 1.3.0

kong.conf.default, kong/init.lua, kong/templates/kong_defaults.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/helpers.lua
Exploring the idea of passing declarative config as a string, rather than mounting in a file.
* add new env var
* add condition to parse as string rather than file
* add error handling
https://github.com/Kong/kong/discussions/7344
```
docker run \
-e KONG_DATABASE=off \
-p 8000:8000 \
-v $HOME/git/kong/kong/db/declarative/init.lua:/usr/local/share/lua/5.1/kong/db/declarative/init.lua \
-e KONG_DECLARATIVE_CONFIG='{"_format_version":"1.1","services":[{"host":"mockbin.com","port":443,"protocol":"https","routes":[{"paths":["/"]}]}],"plugins":[{"name":"rate-limiting","config":{"policy":"local","limit_by":"ip","minute":3}}]}' \
kong:latest
```
```
http -b :8000/status/200
http -b :8000/status/200
http -b :8000/status/200
http -b :8000/status/200
```
should see "message": "API rate limit …
=> feat(dc) implement KONG_DECLARATIVE_CONFIG_STRING

kong/plugins/ldap-auth/schema.lua, spec/03-plugins/20-ldap-auth/02-schema_spec.lua
LDAP Authentication [documentation](https://docs.konghq.com/hub/kong-inc/ldap-auth/#parameters) indicates a default value for the LDAP port as `389`. This corrects the default value for the `config.ldap_port` and aligns default values with those listed in the plugin documentation.
* fix(schema) add default value for LDAP port
=> fix(schema) add default value for LDAP port

kong-2.4.1-0.rockspec, kong/plugins/grpc-gateway/CHANGELOG.md, kong/plugins/grpc-gateway/README.md, kong/plugins/grpc-gateway/deco.lua, kong/plugins/grpc-gateway/handler.lua, kong/plugins/grpc-gateway/kong-plugin-grpc-gateway-0.1.3-1.rockspec, kong/plugins/grpc-gateway/schema.lua, spec/03-plugins/28-grpc-gateway/01-proxy_spec.lua, spec/fixtures/grpc/helloworld.proto
As a result of an effort to improve external plugins maintainership, we are importing currently-bundled plugins into Kong's main tree. The grpc-gateway plugin used to live in [1].
Additionally to importing plugin contents, this PR also preserves the Git history. History was amended to correct commit scopes - including `grpc-gateway` in commit messages scope.
*Note*: this also fixes the current failure observed in `master` tests.
[1] https://github.com/Kong/kong-plugin-grpc-gateway
=> chore(plugins) import grpc gateway

kong/plugins/syslog/handler.lua, kong/plugins/syslog/schema.lua
The default value is now populated at runtime for compatibiliy.
This commit can be reverted in 2.7 (2 version started from 2.5) or 3.0 whichever comes eariler.
=> fix(syslog) ensure new facility field is compatible with older versions in hybrid mode

spec/helpers.lua
Same approach used by the admin_client helper:
https://github.com/Kong/kong/blob/2.4.1/spec/helpers.lua#L835-L845
=> tests(helpers) add forced_port to proxy_client

kong/status/init.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/02-integration/08-status_api/01-core_routes_spec.lua, spec/02-integration/08-status_api/02-targets_routes_spec.lua
on Data Plane
This PR exposes following endpoint to status API:
- GET /upstreams/{upstream}/targets/
- GET /upstreams/{upstream}/health/
- GET /upstreams/{upstream}/targets/all/"
- GET /upstreams/{upstream}/targets/{target}
=> feat(status_api) expose upstream healthchecks endpoint on status API

spec/02-integration/10-go_plugins/01-reports_spec.lua, spec/fixtures/mock_upstream.lua
Needed with: https://github.com/Kong/kong-build-tools/pull/401
The testing branch is here (currently is has issues with grpc-plugin tests):
https://github.com/Kong/kong/pull/7465
=> fix(tests) add server header on mock upstream responses

autodoc/admin-api/data/admin-api.lua
Update protocols and name definitions
Update protocols definition to clarify the following use cases:
* only the `HTTPS` protocol is allowed, and user sends `HTTP` request
* only the `HTTP` protocol is allowed, and user sends `HTTPS` request
Clarify that single protocol allowed should be sent as a string and not an array. 
Note that all accepted protocols are listed in the Route Object section. 
Specify that all name values must be unique. 
Fix DOCU-707
=> docs(admin-api) Update protocols and name definitions

kong/db/schema/init.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua
This PR was made for the bringing forward compatibilty in DataPlane in hybrid mode.
When a new field is added in ControlPlane but the value is null (usually means it's unset), DP will ignore such
field from schema validation.
Only DataPlane will receive this behaviour. Extra fields from admin API and declarative config are still returning
errors.
=> fix(hybrid) ignore fileds that values are null

autodoc/admin-api/data/admin-api.lua
This PR addresses issue [586](https://github.com/Kong/docs.konghq.com/issues/586).
* add note that `host` is case sensitive
Edit: add note that `hosts` is also case sensitive
Fix DOCU-1562
=> [DOCU-1562] add note about host as case sensitive

kong/clustering/control_plane.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
This PR fixes a regression from
9cdd34ed4ee8f6fd8cab560ac09173950076355b,
where patch versions on DP are ignored no matter it's newer or older.
This preserves the same behaviour before
9cdd34ed4ee8f6fd8cab560ac09173950076355b.
* ...
Fix #XXX
=> fix(clustering) ignore patch version mismatch

kong/db/strategies/cassandra/connector.lua
ALTER statements for existing columns cause migration/bootstrap errors when initializing Kong. This commit ensures that ALTER statement errors are safely ignored for standard migrations and re-entrant migration operations when using Apache Cassandra 4.0.
GitHub Actions were also updated to test against 4.0-rc1.
* fix(db) Apache Cassandra 4.0 compatibility
=> fix(db) Apache Cassandra 4.0 compatibility

kong/clustering/control_plane.lua, kong/clustering/data_plane.lua
There are two cases that may cause updating the sync status on database:
1. PING frame received by control plane from dataplane
2. New config send to dataplane from control plane
As these are ran in two threads and as the postgres upsert statement is asynchronous non-blocking query, the order which we send the queries is not always the order which they appear in postgres.
This PR makes our test suite less flaky on the race condition by grabbing the initial configuration compatibility before starting the read/write threads.
There is also a small change that makes `last-seen` only updated when receiving `PING` frame from data plane. This is more in line of what we had before.
Changed data plane log messages to contain information about control plane. This also adds couple of new log …
=> fix(clustering) fix race condition causing flakiness on sync status of data plane

kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/init.lua, spec/01-unit/19-hybrid/02-clustering_spec.lua
Previously data plane hash calculation was flaky and with recent OpenResty changes it become
even flakier. This PR tries to calculate data plane config hash in a more reliable way by
sorting the data and then calculating the hash out of it.
=> fix(clustering) more reliable way to calculate data plane config hash

spec/helpers.lua
because it used to use `ngx.time()` which only has second
precision, a time-out specified as 1 second could actually be
only 0.001, if that 1ms would cross the second boundary
=> fix(test) reduce test flakyness by actually waiting

kong/runloop/handler.lua, spec/02-integration/05-proxy/03-upstream_headers_spec.lua
Clear proxy authorization header only when it is part of original request headers.
Removes it also when the plugin specifies it with exactly same value as in original
request headers.
=> fix(proxy) removal of proxy-authorization header

kong/init.lua, spec/02-integration/05-proxy/24-buffered_spec.lua
According to docs, `ngx.location.capture` returns `res.truncated ==
true` on error cases, but it seems HEAD requests might cause it too.  In
those cases don't force an error response.
Fixes #7059
=> Handle HEAD requests in buffered mode.

Jenkinsfile
Release 3.14 (15-6-2021, see https://alpinelinux.org/releases/ ) has issues that break `make` (see https://github.com/alpinelinux/docker-alpine/issues/146 ) and hence cause Pongo image builds to fail.
NOTE: it was set to `latest` which was good to catch issues early (this issue proves the approach worked), so we'll have to revisit upon newer Alpine releases whether we can go back to the `latest` tag.
=> fix(ci) pin Alpine release to 3.13

autodoc/admin-api/data/admin-api.lua, autodoc/admin-api/generate.lua, scripts/autodoc
Before this PR, autodoc generated two separate (but similar) files for the admin api:
* `admin-api.md` for the "db" Admin API
* `db-less-admin-api.md` for db-less
After this PR,
* only `admin-api.md` will remain
* It will have two new top sections describing db-less & declarative config
* methods that are not compatible with db-less will be marked as such with a warn blue box
---
**Note for reviewers**: I have moved this back to "please review" despite @javierguerragiraldez 's approval because feedback from the docs team resulted in two new changes which were added after his review:
* We now mark both db and db-less methods with badges, with a custom syntax
* We patched the PDK navigation in one way and the Admin API navigation in a totally different way. This second way required an extra …
=> docs(autodoc) collapse declarative_admin_api.md into admin_api.md

kong/runloop/balancer.lua
Ensures that existing healthchecks are stopped when processing CRUD events on targets. 
* Ensure `stop_healthchecker` is called for existing balancer prior to `create_balancer`. Follows pattern from `do_upstream_event`
**Notes**:
- Haven't added tests for this. Figured I would try copy the existing test from `do_upstream_event` but it doesn't look like this is tested at present? (Was looking at https://github.com/Kong/kong/blob/2.4.1/spec/01-unit/09-balancer_spec.lua so perhaps Iäm in the wrong place?)
- Opened PR against `master`. But it seems like the branching strategy in this repo has changed somewhat since I last submitted a PR. Feel free to let me know if you want this rebased to a (release?) branch.
Fix #7406 
Fix #7407
=> fix(balancer) ensure existing healthchecker is stopped when processing target event

CHANGELOG.md
=> docs(changelog) don't call 2.5.x an RC release any more

kong/cmd/utils/prefix_handler.lua
This enables code like this in the templates:
```
some_directive $(os.getenv("SOME_ENV_VAR"));
```
Fixes: #6546
=> feat(template) allow os.getenv in the template renderer

spec/helpers.lua
fixes the issue reported here: https://github.com/Kong/kong-plugin/pull/16#issuecomment-881673138
=> chore(test) helper db-export should honor test config

kong/runloop/balancer/balancers.lua
Backport of #7408, balancer code has been rewritten after that PR was merged.
=> fix(balancers) stop health check when recreating balancer

kong/db/schema/init.lua
I modified the internal constraints object to be a Hash instead of an
Array. `ipairs` ignores non-numeric keys so in order to iterate it
correctly we need to use `pairs`. I was already doing this for
non-workspace entities but missed doing it for the workspace special
case in `.get_constraints()`.
Original PR: https://github.com/Kong/kong/pull/7560
=> fix(schema) iterate _cache[...].constraints with pairs

kong/clustering/data_plane.lua
Ensure data plane config thread is terminated gracefully, preventing it from getting into a semi-deadlocked state.
It'd be pretty tough to make this testable, so I hope it's okay without any additional tests added. I haven't run the test suite locally so :crossed_fingers: that it passes the automated tests here.
Fix #7567
=> fix(clustering) ensure data plane config thread is terminated gracefully

kong-2.5.0-0.rockspec
- add reserved_name/reserved_range to enum
- update embeded descriptor.pb file in protoc.lua to latest version
- add hooks for message encoding
- add proto3 optional support (use proto3_optional or experimental_allow_proto3_optional flags to protoc.lua)
- bugfix
=> chore(deps) bump lua-protobuf from 0.3.2 to 0.3.3

.github/workflows/perf.yml, spec/04-perf/01-rps/01-simple_spec.lua, spec/04-perf/01-rps/02-balancer_spec.lua, spec/04-perf/01-rps/03-plugin_iterator_spec.lua, spec/04-perf/02-flamegraph/01-simple_spec.lua, spec/04-perf/02-flamegraph/03-plugin_iterator_spec.lua, spec/helpers/perf.lua, spec/helpers/perf/drivers/docker.lua, spec/helpers/perf/drivers/local.lua, spec/helpers/perf/drivers/terraform.lua, spec/helpers/perf/git.lua, spec/helpers/perf/utils.lua
This PR adds balancer and plugin iterator based tests. In order to setup those tests,
we also add features to start upstream with multiple ports and expose admin API.
- allow to start upstream with multiple ports …
- add function to write current test case's descriptor
- allow to expose admin port and test on pre releases
- add balancer, plugin iterator tests
- fix quote path in redirection and fix git repo test function
- remove wait in tests, adjust stapxx args for longer duration
=> perf(*) new tests cases and fixes

kong-2.5.0-0.rockspec
- ***:** popup errors from lower functions [a19e9c8](https://github.com/fffonion/lua-resty-acme/commit/a19e9c8af9179a81815c653d176aa0bfc27e532b)
- **autossl:** pass storage config to acme client ([#43](https://github.com/fffonion/lua-resty-acme/issues/43)) [ef1e541](https://github.com/fffonion/lua-resty-acme/commit/ef1e54112d1bdda187812a0e6c96d8b134fd4d04)
- **autossl:** add challenge_start_delay [df4ba0b](https://github.com/fffonion/lua-resty-acme/commit/df4ba0b71a1f92b87d7f9f203475bc7115c56b9a)
- **autossl:** check if domain is whitelisted before cert renewal ([#35](https://github.com/fffonion/lua-resty-acme/issues/35)) [942c007](https://github.com/fffonion/lua-resty-acme/commit/942c007711ba1a0f04b8f30f81443a46ae0ed412)
- **client:** add challenge_start_callback …
=> chore(deps) bump lua-resty-acme from ~> 0.6 to == 0.7.1

kong-2.5.0-0.rockspec
- **extension:** fallback to ASN1_STRING_print in extension:text where X509V3_EXT_print is not available [f0268f5](https://github.com/fffonion/lua-resty-acme/commit/f0268f55b124eb4ff65b472899e241af850f9d35)
=> chore(deps) bump lua-resty-openssl from 0.7.3 to 0.7.4

kong/clustering/control_plane.lua
Duplicated CP plugin version information is being appended to a log message when the CP and DP major versions differ. The CP plugin version is already part of `msg`.
```
18:44:01 [warn] 2997#0: *26 [lua] control_plane.lua:247: check_version_compatibility(): [clustering] data plane acl plugin version 3.0.1 is different to control plane plugin version 3.0.13.0.1 [id: e5ecbe97-b04a-464f-8667-ba82edea4953, host: d9d9a0877271, ip: 127.0.0.1, version: 2.4.1.1-dev-enterprise-edition], client: 127.0.0.1, server: kong_cluster_listener, request: "GET /v1/outlet?node_id=e5ecbe97-b04a-464f-8667-ba82edea4953&node_hostname=d9d9a0877271&node_version=2.4.1.1-dev-enterprise-edition HTTP/1.1", host: "127.0.0.1:9005"
18:44:01 [warn] 2997#0: *26 [lua] control_plane.lua:247: check_version_compatibility(): …
```
=> chore(log) remove duplicate CP plugin version output in log

kong/db/strategies/postgres/connector.lua
All operations that qualify as a non-critical "read" operation are correctly hitting the postgres read-only replica. With the exception of the call to the `schema_meta` table.
* Add the `read` operation keyword to route the query to a potential read-only replica
=> perf(postgres): meta_schema is a read-only operation

.luacheckrc, kong/db/schema/entities/workspaces.lua, spec/01-unit/01-db/01-schema/15-workspaces_spec.lua
You can create a workspace named "plugins" or "services" and nothing in the schema stops a user from doing that.  After which, Kong allows some further API interactions (POST /plugins/services is apparently valid although I couldn't find documentation on it so it may "look" like a valid workspace from within e.g. Manager but POST /plugins/consumers doesn't work (Method not allowed). It's rather hard to find the root cause for random looking issues that occur when using reserved workspace names.
* Added workspace schema validation function
* Added tests
=> fix(workspace): do not allow reserved names

kong-2.5.0-0.rockspec
Fixes IPv6 using same prefix for same mask length: https://github.com/api7/lua-resty-ipmatcher/issues/18
* Change lua-resty-ipmatcher version from 0.6 to 0.6.1
=> Bump lua-resty-ipmatcher to 0.6.1

spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua, spec/helpers.lua
replaces previous hack of "make some IO sometime after".
=> fix(tests) force yield (via `sleep(0)`) after semaphore:post()

kong/runloop/handler.lua, spec/02-integration/05-proxy/03-upstream_headers_spec.lua
It was reported by @ly123-liu on #7722 that Kong removes `Proxy-Authentication` header from upstream
request.
RFC2612 (https://datatracker.ietf.org/doc/html/rfc2616#section-13.5.1) specifies them as a hop-by-hop
headers that should be removed. But it did not consider use case of having multiple proxies, so RFC7235
corrected the wording https://datatracker.ietf.org/doc/html/rfc7235#section-4.4.
> A proxy MAY relay the credentials from the client request to the next proxy if that is
> the mechanism by which the proxies cooperatively authenticate a given request.
Fix #7722
=> fix(proxy) keep proxy-authentication request header and proxy-authenticate response header

kong/runloop/plugin_servers/init.lua, kong/runloop/plugin_servers/process.lua
The external plugins rewrite of #6600 regressed CLI bug first reported
in #6437 and fixed in #6596.
Fix #7583
=> update module's `local kong` var

kong-2.5.0-0.rockspec, spec/02-integration/05-proxy/24-buffered_spec.lua
Changes:
- fix: `stringx.strip` behaved badly with string lengths > 200
- fix: `path.currentdir` now takes no arguments and calls `lfs.currentdir` without argument
- feat: `utils.raise_deprecation` now has an option to NOT include a stack-trace
See changelog: https://github.com/lunarmodules/Penlight/blob/master/CHANGELOG.md#1110-2021-08-18
=> chore(deps) bump Penlight to 1.11.0

kong/tools/uri.lua
Runs ngx.re.gsub only when ngx.re.find finds that there is something to escape.
In many cases there will not be anything to escape.
=> perf(uri) escape only when needed

kong/api/routes/upstreams.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua
@flrgh reported on issue #7699 that our admin api return 404 for GET requests with target endpoint
when the target.weight is 0.
Fix #7699
=> fix(admin) GET /upstreams/:upstreams/targets/:target returns 404 when target weight is 0

kong/pdk/response.lua, t/01-pdk/08-response/13-error.t
@wi1dcard reported on issue #7746 that certain accept headers may cause Kong to runtime error. I found an issue in kong.response.error function, and fixed it.
Fix #7746
=> fix(pdk) malformed accept header can cause unexpected HTTP 500

kong-2.5.0-0.rockspec
* Fix handle SSL_send SYSCALL error without errno
* Fix off by one in cert:validat(notafter)
* Fix meth_get_{sinagure => signature}_name function name
* Fix update the Lua state reference on the selected SSL context after SNI
* Fix ignore SSL_OP_BIT(n) macro and update option.c
=> chore(deps) bump luasec from 1.0.1 to 1.0.2

autodoc/admin-api/data/admin-api.lua, autodoc/cli/data.lua
Updating links to point to `/gateway-oss/` instead of just `/`. 
This directory changed a few releases ago, so these pages now live here: https://docs.konghq.com/gateway-oss/
N/A, internal doc changes only.
N/A
=> docs(autodoc) Update links in autodocs

kong/pdk/service/request.lua, kong/runloop/balancer/init.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/19-grpc_proxy_spec.lua
Ensure the `:authority` pseudo-header is set on balancer retry upstream requests.
Depends on:
- https://github.com/Kong/kong-build-tools/pull/403
- https://github.com/Kong/lua-kong-nginx-module/pull/18
=> fix(balancer) set :authority on balancer retries

CHANGELOG.md, kong/db/schema/init.lua, kong/db/schema/metaschema.lua, kong/plugins/aws-lambda/handler.lua, kong/plugins/aws-lambda/schema.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/03-plugins/27-aws-lambda/02-schema_spec.lua, spec/03-plugins/27-aws-lambda/99-access_spec.lua
Allows auto-detection of region using either `AWS_REGION` or `AWS_DEFAULT_REGION` environment variables.
This PR also has another commit:
The `only_one_of` validator marks at least one field required, this new `mutually_exclusive` entity validator allows none to be configured.
Partly resolves issue #7697
=> feat(aws-lambda) add support for detecting AWS region from environment variable

kong/plugins/request-termination/handler.lua
echo option and trigger were added in https://github.com/Kong/kong/pull/6744, but that didn't bump the version
ping @mikefero this might cause compatibility issues
=> fix(request-termination) bump version

scripts/changelog-helper.lua
The following command:
```
./scripts/changelog-helper.lua 2.5.0 master $GITHUB_TOKEN
```
Currently (Aug 31st) generates the following output:
```
Getting comparison commits
Getting PRs associated to commits in main comparison
#7785. #7765.. #7777. #7767. #7774. #7723. #7632. #7748. #7756. #7725. #7759. #7750. #7757. #7758. #7695. #7742. #6744. #7738. #7736..... #7727. #7731. #7589. #7719..... #7724. #7704. #7703. #7606.. #7380. #7666. !b0fe5611adc1cb34822dae460ed68be5582c9a33... #7454. #7516. #7598. #7661. #7657. #7659. #7658.. #7547...... #7656. #7607. #7568. #7604. #7642.... #7637.. #7545.. #7464. #7617. #7538. #7578.. #7549. #7586. #7560.. !4088d4b4fab04de7eb0891ed84d1d424ac058431 #7605. #7558..... #7502. #7569. #6872...
Categorizing PRs
Finding non-konger authors
jiachinzhao:✅ liov:✅ …
```
=> chore(scripts) implement scripts/changelog-helper.lua

kong/api/api_helpers.lua, spec/02-integration/04-admin_api/02-kong_routes_spec.lua
@rainest reported our strange support for `HEAD` requests on #7554.
This commit fixes the mentioned issue and adds support for `HEAD`
requests for all admin api endpoints.
Fix #7554
=> feat(admin) add support for HEAD calls (GET without body)

scripts/make-final-release, scripts/make-patch-release
This will allow us to deprecate internal checklists and
only use the script. Implements https://github.com/Kong/core-team/blob/master/adr/2021-07-29-deprecate-release-checklists.md.
=> chore(scripts) add reminder steps

kong/runloop/balancer/upstreams.lua, kong/runloop/handler.lua
The workspace id received in the request was being dismissed when posting balancer CRUD events. When workers used these posted events they had to fallback to the default workspace.
* When an upstream event is received from the DAO `handler.lua` now gets the workspace id from the request and adds it to the upstream entity that will be used in the worker and cluster events. Before this change, when an worker or cluster event was treated, the workspace id was lost and the balancer used the default workspace id as a fallback.
* No tests were added as Kong API Gateway does not use custom workspaces.
=> fix(handler) use request workspace to post balancer events

kong/pdk/response.lua, t/01-pdk/08-response/11-exit.t
It was reported by @albertforweb on issue #7816 that our PDK's `kong.response.exit` overrides content-length header even when it was explicitly given. This commit fixes the issue.
Fix #7816
=> fix(pdk) kong.response.exit cannot use customized "Content-Length" header

kong/plugins/prometheus/exporter.lua, spec/03-plugins/26-prometheus/06-hybrid-mode_metrics.lua
A new metrics `data_plane_cluster_cert_expiry_timestamp` is added to expose the Data Plane's `cluster_cert`
expiry timestamp.
* expose DP cert expiry timestamp
=> feat(plugins/prometheus) expose DP cert expiry timestamp

kong/init.lua, kong/router.lua, kong/runloop/balancer/init.lua, kong/runloop/handler.lua, spec/01-unit/16-runloop_handler_spec.lua, spec/04-perf/01-rps/01-simple_spec.lua, spec/04-perf/01-rps/02-balancer_spec.lua, spec/04-perf/01-rps/03-plugin_iterator_spec.lua, spec/04-perf/02-flamegraph/01-simple_spec.lua, spec/04-perf/02-flamegraph/03-plugin_iterator_spec.lua
of uncommon branches
Other work like reducing var.http_HEADER and upstream var will be done in seperate PR.
Partly from #7426 #7421
=> perf(*) reduce unnecessary read on ngx.var and avoid caching outside

kong/api/api_helpers.lua, kong/init.lua, spec/02-integration/04-admin_api/02-kong_routes_spec.lua, spec/02-integration/04-admin_api/09-routes_routes_spec.lua
Previously Admin API always replied the same on all OPTIONS requests:
```lua
header["Access-Control-Allow-Methods"] = "GET, HEAD, PUT, PATCH, POST, DELETE"
header["Access-Control-Allow-Headers"] = "Content-Type"
return ngx.exit(204)
```
This commit changes that OPTIONS request only replies to routes that our Admin API has. Non-existing routes will get `404`.
It also adds `Allow` header to responses, and both `Allow` and  `Access-Control-Allow-Methods` now contain only the methods that the specific API supports.
=> feat(admin) add better support for OPTIONS requests

kong/runloop/handler.lua
Trying to get rid of tab_resize and perhaps the new_key too:
=> perf(balancer) optimize for less table resize

CHANGELOG.md, kong-2.5.1-0.rockspec, kong/meta.lua
Just adds couple of commits from 2.5.1 to master. Replaces #7869.
=> chore(*) add commits from 2.5.1 to master

scripts/changelog-helper.lua
The script was using:
* `commit.commit.author.date`, which was when the commit was **written**
It should have been using this instead:
* `commit.commit.committer.date`, which is the last time the commit was
modified/merged.
As a result of this change, the script now does not ignore some commits
that were previously discarded (they where originally written before the
appropriate period, but were merged inside the period)
=> chore(scripts) fix date used in changelog helper script

kong/clustering/compat/removed_fields.lua, spec/01-unit/19-hybrid/03-fields-removal_spec.lua
Fix version compatibility with older dataplanes connected newer control plane containing schema changes for `aws-lambda`, `grpc-web`, and `request-termination`
**Note**: `aws-lambda` and `grpc-web` minor (or patch) versions still need to be bumped as their are new features which were incorporated during the importing of the plugins into the repo.
- aws-lambda comparison from previous Kong Gateway (OSS) 2.5.1 release; https://github.com/Kong/kong-plugin-aws-lambda/compare/3.5.4...master
- grpc-web comparison from previous Kong Gateway (OSS) 2.5.1 release; https://github.com/Kong/kong-plugin-grpc-web/compare/v0.2.0...master
* fix(clustering) add unknown fields for removal with older dataplanes
=> fix(clustering) add unknown fields for removal with older dataplanes

kong/runloop/balancer/balancers.lua, kong/runloop/balancer/least_connections.lua, kong/runloop/balancer/round_robin.lua, kong/runloop/balancer/targets.lua, spec/01-unit/09-balancer/01-generic_spec.lua, spec/01-unit/09-balancer/02-least_connections_spec.lua, spec/01-unit/09-balancer/03-consistent_hashing_spec.lua, spec/01-unit/09-balancer/04-round_robin_spec.lua, spec/helpers/dns.lua
Main differences come from the fact that the new balancer is not a general-purpose library, and doesn't present a large and defensive API to manage its internal structures. Instead, it now depends on the working of Kong's data entities.
Kinds of tests we're no longer interested in and has been removed:
* Accept/reject a wide variety of call styles to create balancer and add targets to it:  these are helper functions to emulate database operations, no need to make them robust and generally useful.
* Garbage collecting a handle releases it: handles are simple Lua tables, they are expected to be properly released and not just dropped. Integration tests ensure that.
* Accept a handle instead of an address: feature removed.
* Detailed errors for 'address not found' on many methods: most of …
=> tests(balancer) port remaining balancer tests from lua-resty-dns-client.

kong/plugins/grpc-gateway/CHANGELOG.md, kong/plugins/grpc-gateway/handler.lua
This is a cherry-pick from the 2.6.x branch into master.
=> chore(grpc-gateway) bump the plugin version

kong-2.6.0-0.rockspec
- ***:** use a standarlized log interface [0ff01bd](https://github.com/fffonion/lua-resty-acme/commit/0ff01bd2ab39ff3973106946644223d1740a31b8)
- **autossl:** release update_lock after cert is created to allow multiple type of certs for same domain to be created within short time [e315070](https://github.com/fffonion/lua-resty-acme/commit/e315070834a6c5b516110d61bb12bb9052f896a8)
- **autossl:** increase cert lock time ([#47](https://github.com/fffonion/lua-resty-acme/issues/47)) [efb0602](https://github.com/fffonion/lua-resty-acme/commit/efb0602ab286f93f25d6f98d9ec26521970f743b)
- **tls-alpn-01:** set version 3 in certificate generated ([#49](https://github.com/fffonion/lua-resty-acme/issues/49)) [887cad8](https://github.com/fffonion/lua-resty-acme/commit/887cad8b2ee02748c863f85e8f8afdec3c …
=> chore(deps) bump resty.acme from 0.7.1 to 0.7.2

kong-2.6.0-0.rockspec
- ***:** rename some EVP_ API to use get in openssl3.0 [8fbdb39](https://github.com/fffonion/lua-resty-openssl/commit/8fbdb396d0a4988a24ff2e0404c1866a416d9cff)
- **aux/nginx:** add 1.19.9 [eb73691](https://github.com/fffonion/lua-resty-openssl/commit/eb73691c058c9d55a1b57405f889f5bc3ecd0420)
=> chore(deps) bump resty.openssl from 0.7.4 to 0.7.5

kong/pdk/response.lua, kong/plugins/proxy-cache/handler.lua, kong/plugins/response-transformer/handler.lua, t/01-pdk/08-response/00-phase_checks.t, t/01-pdk/08-response/09-set_raw_body.t, t/01-pdk/08-response/14-get_raw_body.t
Adds two new PDK functions that currently only work on `body_filter` phase:
1. kong.response.get_raw_body
2. kong.response.set_raw_body
The `body_filter` phase may be called for each chunk. Sometimes plugins need the full body. If all plugins try to buffer the response, it leads to multiple buffers and even buggy situations. Thus, `kong.response.get_raw_body` was added.
The `kong.response.set_raw_body` as a better way to do:
```
ngx.arg[1] = "hello"
ngx.arg[2] = true
```
in `body_filter` phase. It also clears the `buffer` if one was created by' `kong.response.get_raw_body`.
This also updates two core plugins to use those new functions.
=> feat(pdk) add kong.response.get_raw_body and kong.response.set_raw_body

kong/runloop/balancer/upstreams.lua, spec/01-unit/09-balancer_spec.lua
Balancer modules have an `init()` method that also gets called on
configuration reload.  This is an opportunity to clear any local cache
that should reflect the database.
Fix #7859
=> fix(balancer) reset local caches on init

kong/runloop/plugins_iterator.lua
We don't need to iterate over the plugins on `certificate` or `rewrite` phases if there are no global plugins configured.
(the perf test is broken, until it is fixed or 2.7 is released, but I don't think we should wait for it)
=> perf(plugin-iterator) return zero iterator when no global plugins specified

.ci/run_tests.sh, .github/workflows/build_and_test.yml, spec/01-unit/08-router_spec.lua, spec/01-unit/21-dns-client/01-utils_spec.lua, spec/01-unit/21-dns-client/02-client_spec.lua, spec/02-integration/05-proxy/19-grpc_proxy_spec.lua
This causes massive slowdown when `resolv.conf` contains `search`
directive as the client may need timeout 10 times searching local domain
before trying the correct domain name:
```
10:26:40.740170 IP (tos 0x0, ttl 64, id 1379, offset 0, flags [DF], proto UDP (17), length 79)
192.168.40.133.37051 > 192.168.40.2.domain: [bad udp cksum 0xd224 -> 0x0e86!] 27482+ SRV? www.thijsschreijer.nl.localdomain. (51)
10:26:42.742989 IP (tos 0x0, ttl 64, id 2060, offset 0, flags [DF], proto UDP (17), length 79)
192.168.40.133.37051 > 192.168.40.2.domain: [bad udp cksum 0xd224 -> 0x0e86!] 27482+ SRV? www.thijsschreijer.nl.localdomain. (51)
10:26:44.746401 IP (tos 0x0, ttl 64, id 3213, offset 0, flags [DF], proto UDP (17), length 79)
192.168.40.133.37051 > 192.168.40.2.domain: [bad udp cksum 0xd224 -> …
```
=> tests(dns-client) do not search local domain when resolving

.github/workflows/perf.yml
While the root cause for such ephermal timeout in executing
commands still needs investigation, adding a timeout to avoid the
whole job being killed by Github will stop the bleeding
=> tests(perf) add a timeout for Running Test step

kong/constants.lua, kong/db/schema/entities/routes.lua, kong/db/schema/entities/routes_subschemas.lua, kong/init.lua, kong/pdk/client.lua, kong/router.lua, kong/runloop/handler.lua, kong/templates/nginx_kong_stream.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/03-db/02-db_core_entities_spec.lua, spec/02-integration/04-admin_api/09-routes_routes_spec.lua, spec/02-integration/04-admin_api/10-services_routes_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/fixtures/custom_nginx.template
Adds the ability in route TLS traffic based on SNI without terminating the connection.
To let Kong does normal TLS termination
```
kong.conf:
stream_listen=0.0.0.0:9000 ssl
kong.yaml
routes:
- protocol: tls
snis: something
tls_passthrough: false #default
```
To let Kong does TLS passthrough
```
kong.conf:
stream_listen=0.0.0.0:9000 ssl
kong.yaml
routes:
- protocol: tls
snis: something
tls_passthrough: true
```
* feat(router) allow TLS passthrough in stream router
Fix #5902 #6694
TODO:
=> feat(router) allow TLS passthrough in stream router

kong-2.6.0-0.rockspec, kong/constants.lua, kong/plugins/azure-functions/handler.lua, kong/plugins/azure-functions/kong-plugin-azure-functions-1.0.1-1.rockspec, kong/plugins/azure-functions/schema.lua, spec/03-plugins/35-azure-functions/01-access_spec.lua
As a result of an effort to improve external plugins maintainership, we are importing currently-bundled plugins into Kong's main tree. The azure-functions plugin used to live in [1].
Additionally to importing plugin contents, this PR also preserves the Git history. History was amended to correct commit scopes - including azure-functions in commit messages scope.
[1] https://github.com/Kong/kong-plugin-azure-functions
=> chore(*) import azure functions

autodoc/upgrading/generate.lua
* Update title in front matter
* Add OSS badge to front matter
We are single-sourcing the Gateway docs and have two upgrade guides, one for OSS and one for Enterprise. We need to differentiate them better, so this meta data will do that.
=> docs(autodoc) change upgrade autodoc front matter

scripts/autodoc
We are single-sourcing the Gateway OSS and Enterprise documentation, so we updated the script in order to reflect the new single Gateway version. 
We removed the configuration file. A more complete version of the configuration properties is generated from docs.konghq.com/autodoc-conf-ee in the repo Kong/docs.konghq.com, which uses the `kong.conf.default` file in the `kong-ee` repo. The output includes both OSS and Enterprise properties.
Preview PR, pull down fork for testing autodocs: https://github.com/Kong/docs.konghq.com/pull/3110
=> docs(autodoc) update script for Gateway single source [DOCU-1908]

autodoc/admin-api/data/admin-api.lua
Updating the route path handling algorithms table in the Admin API doc based on feedback from a field engineer working with customers. The updated table has a more complete matrix and fixes some broken markdown.
Parallel to docs repo PR: https://github.com/Kong/docs.konghq.com/pull/3353
N/A
From original PR submitter: Was walking through the logic with a client and found it slightly confusing, and also noticed the table broken in the official docs. Tested this using a kong instance and setting up a service and route and calling the proxy api to test each combination in the table. Have also shared this with the client (new table) and they are happier that it makes more sense and values match what they have seen too.
=> docs(admin API) Update path handling table

kong.conf.default, kong/conf_loader/init.lua
compliant ciphers
Turning this option on doesn't make Kong FIPS complaint, it needs Kong
to be linked with a FIPS complaint OpenSSL.
=> feat(conf) add a new cipehrsuites `fips` that includes only FIPS

kong.conf.default, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua, kong/tools/dns.lua
Add dns_cache_size configuration parameter to support maximum number of records for in-memory DNS client cache
* Add configuration parameter draft
=> feat(conf) add dns_cache_size configuration parameter support

kong/plugins/rate-limiting/policies/init.lua, kong/plugins/rate-limiting/schema.lua, spec/03-plugins/23-rate-limiting/05-integration_spec.lua
Adds support for configuring an username for the redis connection.
- Adds the optional property redis_username used for connecting to redis. This allows to make use of redis ACL features supported with Redis 6.0
=> feat(rate-limiting) add redis username support

CHANGELOG.md, kong/conf_loader/init.lua
Cassandra deprecation message when starting/restarting/reloading kong.
This appears on screen as well as in the logs.
- Cassandra support is deprecated with 2.7 and will be fully removed with 4.0.
TODO:
=> docs(c*): add cassandra deprecation message

kong/tools/utils.lua
Use Lua 5.1 compatible `xpcall` invocation. 
This helps run a subset of Kong's functionality within a Lua 5.1-only compatible VM.
None
=> refactor(utils) use Lua 5.1 compatible xpcall

DEVELOPER.md
The current "Master Builds" link reference doesn't exist, and the link is broken. This replaces that with the nightly build Docker Hub page.
=> fix(doc) add nightly link

kong/db/schema/metaschema.lua, kong/plugins/acme/schema.lua, kong/plugins/aws-lambda/schema.lua, kong/plugins/azure-functions/schema.lua, kong/plugins/basic-auth/daos.lua, kong/plugins/http-log/schema.lua, kong/plugins/loggly/schema.lua, kong/plugins/oauth2/daos.lua, kong/plugins/oauth2/schema.lua, kong/plugins/session/schema.lua
This PR marks several key fields as encrypted in several plugins.
Field encryption at rest is a Kong-EE-exclusive feature, this is here for easy upwards merges.
=> chore(plugins-ee) enable encryption of some fields if keyring enabled (EE feature)

kong-2.6.0-0.rockspec
* DEL character is properly escaped in strings
=> chore(deps) bump inspect from 3.1.1 to 3.1.2

kong-2.6.0-0.rockspec
- **jwk:** fix typo of secp521r1 [81d2a64](https://github.com/fffonion/lua-resty-openssl/commit/81d2a646bde7a66ab87e127eace0d40aa714be58)
=> chore(deps) bump resty.openssl to from 0.8.1 to 0.8.2

CHANGELOG.md, kong/db/declarative/init.lua, kong/db/schema/others/declarative_config.lua, kong/router.lua, kong/tools/utils.lua
Previously, when a large DB-less config is processed by Kong, Kong will
be CPU bound when parsing/validating the config and rebuilding the router.
This could cause undesirable proxy latency behavior during reloads.
This PR introduces periodic yielding points so that reload tasks no
longer hogs the CPU until reload completely finishes. Request processing
will be able to continue even while DB-less reload and router rebuild is
happening.
CT-321
=> perf(dbless) improve proxy long tail latency for DB-less reload [CT-321]

kong/runloop/balancer/init.lua, spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua
When the field set to be used for hashing is not found, the balancer will use an empty string to avoid that the selected balancing algorithm tries to hash a nil value.
=> fix(balancer) avoid using nil hash-value

kong/db/schema/init.lua, kong/db/schema/metaschema.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/01-unit/01-db/01-schema/02-metaschema_spec.lua
- fix(schemas) add transformations support to subschemas
- fix(schemas) add shorthand_fields support to subschemas
The transformations and shorthand fields could not be applied to subschemas. This PR will make them available in subschemas too.
=> fix(schemas) add transformations and shorthand_fields support to subschemas

autodoc/admin-api/data/admin-api.lua
Add the `enabled` boolean param to Admin API.
Closes [DOCU-2074](https://konghq.atlassian.net/browse/DOCU-2074) and [TDX-1675](https://konghq.atlassian.net/browse/TDX-1675)
=> [DOCU-2074] Add enabled param to Admin API

spec/helpers/perf.lua
A minor comment mistake in perf.lua
typofix in spec.helpers.perf.lua
function start_stapxx
=> doc: a minor typofix for spec.helpers.perf

kong/resty/dns/client.lua
`ssl_cert` and `ssl_session_fetch` can both yield, but were missing from
the supported list. Without this, a client running in one of these
phases may fail to resolve unexpectedly.
https://github.com/Kong/lua-resty-dns-client/commit/e723618cd268b42ff51d36a5b3a1bec6e1b431f3
This fix connection issues with the kong ee mtls-auth plugin.
=> Fix dns client semaphose phases

scripts/autodoc
Updating the output filename for the generated upgrade guide.
The filename had to be changed since we need two separate pages for Enterprise and open-source gateway upgrades. This is the new page location: https://docs.konghq.com/gateway/2.6.x/install-and-run/upgrade-oss/
N/A
Guide was being generated into the wrong file.
=> autodocs(upgrade) Update filename for upgrade guide on docs site

spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua
With 50 threads testing the least-connections algorithm this test was flaky, sometimes the number of parallel requests were not enough.
=> tests(least-connections) increase test precision

spec/helpers/perf.lua, spec/helpers/perf/drivers/local.lua, spec/helpers/perf/drivers/terraform.lua, spec/helpers/perf/utils.lua
Add options for generate flame graph in perf.lua,
So we can use options like '--inverted --color aqua'.
It also has some code clean and typofix.
* add param opts in  generate_flamegraph()
* change flamegraph cmd string in generate_flamegraph()
* some code clean
* minor typofix
=> feature: add perf flame graph opts for local/terraform

kong/pdk/service/request.lua, spec/helpers/perf/utils.lua
Optimize pdk request.lua with string.byte,
It will avoid  lj_str_new temp string overhead
* add local string_byte = string.byte
* change request.set_path, replace string.sub to string.byte
=> optimize(pdk) use string.byte to avoid lj_str_new overhead

kong/clustering/compat/removed_fields.lua, kong/plugins/rate-limiting/handler.lua, spec/01-unit/19-hybrid/03-fields-removal_spec.lua
Add new rate-limiting fields to the list of excluded fields for older DPs compatibility.
=> chore(rate-limiting) bump plugin version

CHANGELOG.md
=> docs(changelog) grpc allows services from imported `.proto`s

kong/runloop/certificate.lua
This was originally fixed because of:
https://github.com/Kong/kong/issues/5748
It is fixed as seen here:
https://github.com/LuaJIT/LuaJIT/issues/579#issuecomment-623803502
=> chore(certificate) remove a temporary arm64 workaround

kong/db/schema/entities/tags.lua
Yes, `tags` schema is kinda abstract, but it was a bit confusing for me to see a field with `type=string` and then having `elements` too. This commit just changes the schema to a bit less confusing.
=> chore(entities) adjust tags schema

kong/pdk/private/phases.lua
PHASES.n means lshift times, but now it equals to 13, it is 0x2000，
but the max phases admin_api is 0x10000000,
so the function get_phases_names can not get the right name.
I change the PHASES.n to 30, then we can support the all phases bits.
* change PHASES.n to 30, means 2^30 = 0x40000000
=> fix(pdk) get_phases_names wrong lshift

Makefile
This fixes the deeper underlying problem related to https://github.com/Kong/kong-pongo/pull/241 .
In those cases the `make dev` overall failed because LuaRocks failed, but it was not signaled. Hence docker assumes the image to be valid and even caches the results of the docker commands. Despite them being faulty.
=> fix(make-dev) bail out if rock installation fails

kong-2.7.0-0.rockspec
Changelog:
<a name="0.8.4"></a>
- **x509.\*:** use SHA256 as default sign digest in BoringSSL [355681a](https://github.com/fffonion/lua-resty-openssl/commit/355681a33d88d85de0faae3e8eb6685e0e3b9f34)
- **pkey:** add pkey:get_default_digest_type [0572e57](https://github.com/fffonion/lua-resty-openssl/commit/0572e57e0ab418f2dd749dbc5042b0c680e346a7)
<a name="0.8.3"></a>
- **hmac:** include evp.md headers [125ea05](https://github.com/fffonion/lua-resty-openssl/commit/125ea059da6b1effef7a187c434ebd6022dc3b82)
=> chore(deps) bump resty.openssl from 0.8.2 to 0.8.4

kong/pdk/service/request.lua
Summary
Optimize pdk request.lua with string.byte,
It will avoid lj_str_new temp string overhead
Same as PR #8168
Full changelog
change set_body_handlers[CONTENT_TYPE_FORM_DATA], replace string.sub to string.byte
=> perf(pdk) another string.byte to avoid lj_str_new overhead

kong/clustering/data_plane.lua, kong/cmd/utils/prefix_handler.lua, kong/plugins/file-log/handler.lua, kong/tools/utils.lua
Changes `ffi.cdef` for:
```
int open(const char * filename, int flags, int mode);
```
to correct one:
```
int open(const char * filename, int flags, ...);
```
The previous (wrong) declaration causes issues with macOS with M1.
There will be other related PRs on other repositories for better M1 support for Kong.
See also:
https://github.com/Kong/kong-build-tools/pull/427
https://github.com/Kong/lua-kong-nginx-module/pull/21
=> fix(ffi) make corrections on ffi declarations for macOS+M1

kong/runloop/handler.lua
As before's PR, it is a minor improvement about string.byte.
But I think it is in a hot code path, may  reduce many lj_str_new overhead.
* use string.byte to check the last char of uri
=> perf(runloop) use string.byte in access.after to check is_args

kong/templates/nginx_kong_stream.lua
In version 2.6 0, unable to transparently transmit SNI when proxy TLS service
In this modification, you can customize the transparent dynamic TLS SNI name. If you need to customize it, you can configure it in the plug-in. The default name is the same as the original one,using kong_ upstream
=> Support TLS SNI custom dynamic configuration

kong/conf_loader/init.lua
Print error message when failed to load config file.
Output err msg can be useful when debugging problems related to file config.
* Print error message when failed to load config file
ref: https://github.com/Kong/kong/issues/8230
=> chore(init): print err when loading config file err

DEVELOPER.md
Updating the dependency versions in our `DEVELOPER.md`. This also properly compiles on M1 Mac.
=> docs: updating source compilation versions

kong/router.lua
Openresty has a more efficient ffi function ngx.ssl.server_name() ,
it has the same result as var.ssl_server_name,
so I think we can use it both in stream and http subsystem.
* use ngx.ssl.server_name() to get the value of  var.ssl_server_name
=> perf(router) use ngx.ssl.server_name() instead of var.ssl_server_name

kong/runloop/balancer/targets.lua
As `ngx.timer.every` was used, if resolving an address took longer than 1 sec, another resolving callback would be called, instead of waiting until the first one finish. With this change, a new timer will be scheduled only after the previous one has executed.
=> fix(targets) reschedule resolve timer after resolving

.github/dependabot.yml
Add GitHub dependabot to keep GitHub Actions dependencies up-to-date.
see: [Enabling Dependabot version updates for actions](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot)
=> chore(ci) add dependabot to keep actions up-to-date

kong/runloop/handler.lua
localize ngx.time for better performance
* localize ngx.time in update_lua_mem
=> perf(runloop) optimize the call of ngx.time in log phase

.github/workflows/perf.yml, spec/04-perf/01-rps/01-simple_spec.lua, spec/04-perf/01-rps/02-balancer_spec.lua, spec/04-perf/01-rps/03-plugin_iterator_spec.lua, spec/04-perf/02-flamegraph/01-simple_spec.lua, spec/04-perf/02-flamegraph/03-plugin_iterator_spec.lua, spec/04-perf/99-teardown/01-teardown_spec.lua, spec/fixtures/perf/terraform/equinix-metal/main.tf, spec/fixtures/perf/terraform/equinix-metal/metal.tf, spec/fixtures/perf/terraform/equinix-metal/output.tf, spec/fixtures/perf/terraform/equinix-metal/variables.tf
As the rebranding of packet, its terraform provider also moved to different name:
```
19:21:51.730  [debug] [terraform] => The remote registry returned warnings for
19:21:51.730  [debug] [terraform] => registry.terraform.io/packethost/packet:
19:21:51.730  [debug] [terraform] => - For users on Terraform 0.13 or greater, this provider has moved to
19:21:51.731  [debug] [terraform] => equinix/metal. Please update your source in required_providers.
```
This PR cleans up the places where old names are used and point to the new provider.
=> chore(perf) rename packet to metal and bump terraform version

kong/api/routes/upstreams.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua
/upstreams/<upstream>/targets/all endpoint
/upstreams/<upstream>/targets/all endpoint returns an incorrect `next` field where the url is
`/upstreams/<upstream>/targets` but `offset` is the one used in `/all` endpoint. When user use the
returned URL, Kong throws an error since the `offset` format is different in `/upstreams/<upstream>/targets`
versus `/upstreams/<upstream>/targets/all`.
This PR duplicates the `endpoints.get_collection_endpoint` function to generate a correct `next` field in response.
* fix(admin-api) correctly return next field for /upstreams/<upstream>/targets/all endpoint
Fix #8243
=> fix(admin-api) correctly return next field for

Makefile
Download grpcurl arm64 version when the machine is aarch64.
Failed to exec `make bin/grpcul` on Mac M1 Docker container (ubuntu image, `uname -m`: aarch64).
See: https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64
AArch64 and ARM64 refer to the same thing.
* Download grpcurl arm64 version when the machine is aarch64.
=> fix(makefile) grpcurl compatible with aarch64

kong/runloop/plugin_servers/pb_rpc.lua
Specifically, a Headers struct is a map of string to list of strings.
Each value has to be unwrapped as a structpb_list.
Fix: Kong/go-pdk#83 
Fix: #8211
=> fix(extplugin) recursively unwrap Protobuf struct

spec/helpers/perf/drivers/local.lua
When generate flame graph in local drive,
The `cat` cmd will dump the svg into logger but not stdout,
so we should check the cmd, if it is cat then use an empty opts.
* add a flag is_cat_cmd
* check flag to determine opts
=> tests(flamegraph) fix generate flamegraph in local driver

kong/clustering/init.lua, kong/cmd/utils/prefix_handler.lua, spec/01-unit/04-prefix_handler_spec.lua
There were some spots in `kong.clustering` that assumed `pl_file.read()` would throw an error on failure, causing it to throw cryptic errors when we can't read a file:
```
[error] 2050#0: init_by_lua error: /usr/local/openresty/lualib/ngx/ssl.lua:378: attempt to get length of local 'pem' (a nil value)
/usr/local/openresty/lualib/ngx/ssl.lua:378: in function 'parse_pem_priv_key'
/usr/local/share/lua/5.1/kong/clustering/init.lua:130: in function 'new'
/usr/local/share/lua/5.1/kong/init.lua:613: in function 'init'
init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/openresty/lualib/ngx/ssl.lua:378: attempt to get length of local 'pem' (a nil value)
```
I have wrapped these in `assert()` so that Kong will throw a more meaningful error in this case.
I …
=> fix(*) catch file read failures

kong-2.7.0-0.rockspec
Changelog: https://github.com/lunarmodules/Penlight/blob/master/CHANGELOG.md#1120-2022-jan-10
- deprecate: module `pl.text` the contents have moved to `pl.stringx` (removal later) [#407](https://github.com/lunarmodules/Penlight/pull/407)
- deprecate: module `pl.xml`, please switch to a more specialized library (removal later) [#409](https://github.com/lunarmodules/Penlight/pull/409)
- feat: `utils.npairs` added. An iterator with a range that honours the `n` field [#387](https://github.com/lunarmodules/Penlight/pull/387)
- fix: `xml.maptags` would hang if it encountered text-nodes [#396](https://github.com/lunarmodules/Penlight/pull/396)
- fix: `text.dedent` didn't handle declining indents nor empty lines [#402](https://github.com/lunarmodules/Penlight/pull/402)
- fix: `dir.getfiles`, …
=> deps(penlight) Bump to 1.12

spec/04-perf/01-rps/01-simple_spec.lua, spec/04-perf/01-rps/02-balancer_spec.lua, spec/04-perf/01-rps/03-plugin_iterator_spec.lua
Sometime we want to shorter or longer time for perf test,
the original load duration is fixed to 30s in code,
now we can use env to adjust this value
* check env PERF_TEST_LOAD_DURATION in perf test
=> tests(perf) add env to adjust perf test load duration

kong/runloop/handler.lua
It looks like there is no other reference of ngx.null,
so the localization of ngx.null is useless,
just like we did to ngx.config.prefix.
Please do a double check for handler.lua.
* remove localization of ngx.null
* use ngx.null in GLOBAL_QUERY_OPTS
=> style(runloop) remove local ngx.null reference

kong/runloop/plugin_servers/pb_rpc.lua
ConsumerSpec and AuthenticateArgs type defined in proto need unwrapping, otherwise
`client.load_consumer()` and `client.authentication()` will not work with external plugin via pb-rpc protocol.
* Add type unwrap functions for ConsumerSpec and AuthenticateArgs
Fix #8279
=> fix(extplugin) add type unwrap functions

spec/helpers/perf/drivers/local.lua
In perf local dirver, if there is no dir '/tmp/perf-test-nginx',
the 'mkdir /tmp/perf-test-nginx/logs' will failed,
then the perf test will failed.
pl.path.mkdir can not create dir recursively, 
so we have to create it by our self.
* add pl_path.mkdir(nginx_prefix)
=> fix(tests) add pl_path.mkdir(nginx_prefix)

kong/router.lua, spec/02-integration/05-proxy/06-ssl_spec.lua
When a route has an SNI attribute containing an FQDN ending in a dot, the trailing dot was being used to match routes. But according to [RFC-3546](https://datatracker.ietf.org/doc/html/rfc3546#section-3.1), this trailing dot is not part of the hostname, thus must not be used for matching.
This change updates the route marshaling function to not include the trailing dot in this case.
* Remove trailing dot from SNIs in route marshaling function.
* Added test for specific case.
Fix #7550
CT-236
=> fix(router) remove last dot in FQDNs

kong/plugins/rate-limiting/policies/init.lua, kong/plugins/rate-limiting/schema.lua, spec/03-plugins/23-rate-limiting/05-integration_spec.lua
Re-adding `username` support for Redis connections; @27ascii contribution.
On top of reverting the removal of the `username` support, this PR fixes an issue with Redis increment eval query, adds Redis server version checking for the ACL tests added and adds a minimum supported Redis version; logs error if below minimum.
see https://github.com/Kong/kong/pull/8032 for original PR by @27ascii. 
* Adds the optional property redis_username used for connecting to redis. This allows to make use of redis ACL features supported with Redis 6.0
* fix(plugin) correct Redis increment eval for ACL queries
=> chore(revert) re-add Redis username support

kong/plugins/response-ratelimiting/policies/init.lua, kong/plugins/response-ratelimiting/schema.lua, spec/03-plugins/24-response-rate-limiting/05-integration_spec.lua
This PR adds ACL configurations by adding `redis_username` configuration to the response ratelimiting plugin. This syncs with the feature added for the ratelimiting plugin by @27ascii; see https://github.com/Kong/kong/pull/8213 for re-addition into `master` branch.
This PR also refactors the Redis connection logic to be shared via a function (removes copy-pasta).
* Adds the optional property redis_username used for connecting to redis. This allows to make use of redis ACL features supported with Redis 6.0
https://konghq.atlassian.net/browse/FT-2189
=> feat(plugin) add ACL configuration for response ratelimiting [FT-2189]

kong/db/strategies/cassandra/connector.lua
The Cassandra connector should use the write consistency setting
(`cassandra_write_consistency`) from the Kong configuration file for
recording the migration status.
* Fixed defect in Cassandra connector where it didn't use the configuration file consistency.
=> Fix C* connector record migration consistency level

scripts/common.sh, scripts/make-final-release, scripts/make-patch-release, scripts/make-prerelease-release
- chore(scripts) add instructions to some steps
- refactor(scripts) extract check_requirements to common.sh
- chore(scripts) make-prererelease-release works without flags
- chore(scripts) pass all global arguments to `usage` function in release scripts
- refactor(scripts) move duplicated release steps to common.js
* ...
Fix #XXX
=> (chore) document and refactor release scripts

kong/clustering/init.lua, spec/01-unit/19-hybrid/02-clustering_spec.lua
With large configurations the hash calculation can take a lot of time and memory. This PR optimizes the performance of configuration hash calculation. The time is cut to about half of what it used to be and the peak memory usage has also gone down.
This does not produce exactly same hash on certain input as it did before (as I optimized array case and did other change).
Before this PR:
Calculating hash done in 13.43399977684 secs
Maximum resident set size (kbytes): 6081520
After this PR:
Calculating hash done in 4.1620001792908 secs
Maximum resident set size (kbytes): 2720864
Tests were done with 395M kong.json file that was decoded to lua table. The memory usage without hash calculation is:
Maximum resident set size (kbytes): 2163472
Performance boost:
13,43399977684 - 4,1620001792908 = …
=> perf(clustering) improve hash calculation performance

autodoc/admin-api/data/admin-api.lua
Broken links in the docs.
* Fix links in `autodocs/admin-api`
Related to https://github.com/Kong/docs.konghq.com/pull/3549
=>  Fix broken links to DB-less and Declarative config on Admin API

kong-2.7.0-0.rockspec
- Fix 138 issue of chunked cookies are not expired when session shrinks,   thanks @alexdowad.
- Fix 134 where regenerate strategy destroyed previous session when calling   `session:regenerate`, it should just `ttl` the old session, thanks @hoebelix
- 3.9 introduced an issue where calling session:regenerate with flush=true, didn't really flush if the session strategy was `regenerate`.
- AES GCM mode support was added to AES cipher.   This is recommended, but for backward compatibility it was not set as default.  It will be changed in 4.0 release.
- Redis ACL authentication is now available.
- Add `session_redis_username`
- Add `session_redis_password`
- Deprecate `session_redis_auth`; use `session_redis_password`
- Optimize Redis and Memcache storage adapters to not connect to database …
=> chore(deps) bump resty.session from 3.8 to 3.10

kong/cache/warmup.lua, kong/db/dao/init.lua, kong/db/declarative/init.lua, kong/db/schema/init.lua, kong/db/schema/metaschema.lua, kong/db/schema/topological_sort.lua, kong/runloop/balancer/upstreams.lua, kong/runloop/handler.lua
This set of performance improvements contains mainly schema and dao related enhancements:
- uses max page size when iterating over tables on initialization, rebuilds and warmups
- localize variable access in dao/schema modules
- optimizes very hot process auto fields function
- replaces ipairs with for i, #array loops
See the individual commits.
In my tests these patches together with #8010 will improve dbless reloads. E.g. router rebuild used to take something like 7 seconds per worker with my 50 MB YAML-test configuration. With these two PRs I get that to around 3-4 seconds.
=> perf(dao/schema) no ipairs, max page size, skip deep clone, localize vars

kong/router.lua, spec/01-unit/08-router_spec.lua
When I view the code in router.lua, 
I find the logic of MATCH_SUBRULES.HAS_WILDCARD_HOST_PORT may be a mistake.
if we have many hosts, the value of has_port may disappear in the next loop.
Please check the logic flow to confirm I am right or wrong.
* add a new var has_wildcard_host_port
* use has_wildcard_host_port to determine subrules.
=> fix(router) may be a bug in has_wildcard_host_port check

kong/resty/dns/client.lua
dns.client.lua use many string.sub to manipulate string,
We can use string.byte to optimize check first/last char,
It is better than string.sub.
* use string.byte instead of string.sub
=> chore(*) use string.byte to optimize dns client.lua

kong/router.lua, kong/runloop/handler.lua, spec/01-unit/08-router_spec.lua
This PR contains the following performance optimizations to Kong Router (both build time and proxy time optimizations):
- detecting the capturing groups removed (not needed)
- remove use of table.insert and ipairs + refactorings:
1. removes the usage of `ipairs` and `table.insert` and uses counters stored in key `[0]` to keep track of number of elements in arrays
2. adds booleans to skip certain logic when not needed
3. refactors repetitive code to functions (particularly with sources and destinations)
- compiles the regex used to detect if the path is plain
- enables route caching for header based routes
- add negative caching for non-matches
- pass caches to router that enables flushing of caches:
1. previously on each router rebuild, we created a new caches (`resty.lru`), which in turn …
=> perf(router) multiple performance optimizations

spec/01-unit/14-dns_spec.lua
There is a implicit call of dns.client.init in 
setup_it_block() => balancer.init() =>  targets.init(),
so the dns.client.init in before_each will be overwrited and can not work.
To solve this, we should move dns.client.init into setup_it_block(),
then dns.client can use proprer init configration.
* move dns.client.init into setup_it_block()
=> tests(dns) fix dns resolve in 14-dns_spec.lua

.github/labeler.yml, .github/workflows/label.yml
[actions/labeler](https://github.com/actions/labeler) is an action for automatically labeling pull requests.
See https://github.com/actions/labeler#usage
Edit `.github/labeler.yml` file to add/delete labels or paths.
```yaml
repo:
- '*'
@domain/core:
- package/core/*
- package/core/**/*
test:
- src/**/*.spec.js
source:
- any: ['src/**/*', '!src/docs/*']
frontend:
- any: ['src/**/*.js']
all: ['!src/main.js']
```
=> chore(*) add Github Action labeler

CHANGELOG.md
A place where new PR for 2.8 can target their Changelog entry to.
=> docs(changelog) add 2.8 changelog section

kong/resty/dns/client.lua, spec/01-unit/21-dns-client/02-client_spec.lua
if `/etc/resolv.conf` has some special value, like `search .`
then in function `search_iter()`, we will get wrong domain `qname..` ,
It is not a valid dns and will cause error.
So we should check the `search` table,
if there is only one char '.', we replace it with '',
then we can get the right dns name 'qname.'
* check options.search, replace single '.' to ''
=> fix(dns) check options.search array for dot domain

.github/workflows/label.yml
The labeler github action is currently failing on PRs [like this one](https://github.com/Kong/kong/pull/8287) that originate from a fork rather than an internal branch:
> Error: HttpError: Resource not accessible by integration
> Error: Resource not accessible by integration
[link](https://github.com/Kong/kong/runs/4903066028)
I believe it's related to [this super long issue](https://github.com/actions/labeler/issues/12)
The generally-accepted solution seems to be using `pull_request_target` as the event trigger instead of `pull_request`, and the github actions [event trigger docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) also seem to imply that it's the proper event trigger for this use case:
> This event runs in the context of …
=> chore(ci) run the labeler on pull_request_target

.github/workflows/autodocs.yml
The docs repo has a new CI check to help categorise PRs. This PR automatically adds the `review:autodocs` label to any PR raised in the docs repo
* Use the `review:autodocs` label on generated PRs
=> Add review:autodoc to generated docs PR

kong/cache/init.lua
Check whether `opts` is table is a good idea,
but it seems to be a little late after checking `opts.shm_name`,
So I moved the code to the begin of the function.
* check opts in the begin of function.
=> chore(cache) optimize cache init new

.github/workflows/label.yml
See #8322 for more details.
Adding `pull_request_target` was not enough to fix the permission issue. This PR is a workaround, probably the ideal solution is the suggested in [this comment](https://github.com/actions/labeler/issues/12#issuecomment-1019246202).
=> chore(ci) run the labeler only on pull_request_target

kong/templates/nginx_kong.lua, spec/fixtures/custom_nginx.template
As lua-kong-nginx-module says(https://github.com/Kong/lua-kong-nginx-module#lua_kong_load_var_index): 
Note that variables defined by set directive are always indexed by default and does not need to be defined here again.
We need not to add `var_index` for these var defined by `set`.
* remove unnecessary var index(ctx_ref/kong_proxy_mode/...)
=> chore(templates) remove unnecessary var index

autodoc/admin-api/data/admin-api.lua, autodoc/cli/data.lua, autodoc/cli/generate.lua, scripts/autodoc
For the Admin API doc:
* Set the correct output file for the Admin API doc in the docs.konghq.com repo. The file path is [`admin-api/index.md`](https://github.com/Kong/docs.konghq.com/blob/main/app/gateway/2.7.x/admin-api/index.md), not `admin-api.md`
* Update links to new structure, as the `gateway-oss` URL is now just `gateway`
For the CLI doc:
* Removing `Back to Top` links from the `generate.lua` file for the CLI doc. As with the PDK, they're redundant: 
* The docs site has a scroll to top button built in, and a right-side nav to scroll to any header on the page.
* Removing leading `Introduction` header, as this is also redundant
* Update link to new structure, as the `gateway-oss` URL is now just `gateway`
Tested by generating the docs via the script, everything displayed as …
=> docs(autodoc) Update links and output files for Admin API and CLI docs

CHANGELOG.md, kong-2.7.0-0.rockspec
Bump lua-resty-openssl to 0.8.5.
https://github.com/fffonion/lua-resty-openssl/blob/master/CHANGELOG.md
=> chore(deps) bump lua-resty-openssl to 0.8.5

kong/plugins/prometheus/handler.lua, kong/plugins/prometheus/kong-prometheus-plugin-1.5.0-1.rockspec
We have some changes going into the [EE plugin](https://github.com/Kong/kong-ee/pull/2835) that necessitate a minor version bump. This is essentially just a noop version increment in order to keep the plugin version in-step with EE. It's kind of unfortunate and awkward, but it's (IMO) better than having two different versions to reconcile later on.
=> chore(prometheus) increment plugin version

kong/reports.lua
Openresty will support mtls with `sslhandshake` soon,
we need not to use own special `tlshandshake`,
and in this case, it only uses normal ssl feature,
we can change to `sslhandshake` safely.
see:
https://github.com/openresty/lua-nginx-module/pull/1602
https://github.com/openresty/lua-resty-core/pull/278
* use sock:sslhandshake instead of sock:tlshandshake
=> chore(*) use sock:sslhandshake instead of sock:tlshandshake

CHANGELOG.md, kong/router.lua, spec/01-unit/08-router_spec.lua
Add header regex matching method for routing decision. Based on this issue created before
https://github.com/Kong/kong/issues/5666
For avoiding behavior changes, only header with 1 value and prefixed with `~*` is checked against `re_find`
Unit test added as
```
-- 15. headers (regex)
{
service = service,
route = {
headersRegex = true,
headers = {
user_agent = {
"~*windows|linux|os\\s+x\\s*[\\d\\._]+|solaris|bsd",
},
},
},
},
```
Fix https://github.com/Kong/kong/issues/5666
=> feat(router) add header regex matching method

spec/02-integration/11-dbless/01-respawn_spec.lua
This test case was flaky because it relied on proxying a real request out to `example.com`. Using the mock upstream instead will make the test more reliable.
=> tests(dbless) use mock upstream

CHANGELOG.md, kong-2.7.0-0.rockspec, kong/constants.lua, kong/runloop/balancer/balancers.lua, kong/runloop/balancer/healthcheckers.lua, kong/runloop/balancer/upstreams.lua, kong/runloop/handler.lua, spec/01-unit/09-balancer/03-consistent_hashing_spec.lua, spec/01-unit/09-balancer/04-round_robin_spec.lua, spec/01-unit/09-balancer_spec.lua, spec/02-integration/04-admin_api/15-off_spec.lua, spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua, spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua
Now targets don't lose their health status when the upstream is updated, e.g. when a new config is pushed to data planes.
* When the health checker for a target is stopped now the function `delayed_clear()` is called, instead of `clear()`. This change keeps the target's health status in lua-resty-healthcheck's shared dictionary for 5 minutes before actually purging it. If the target is added again by a new upstream with the same name, the health status is kept.
FTI-2623
=> feat(balancer) keep target health state on config updates

kong/runloop/balancer/balancers.lua
This is a debug level message that confused some users being wrongfully ranked.
FTI-3172
=> fix(balancer) debug messages must use DEBUG level

kong/runloop/plugin_servers/init.lua
Skip preloading headers in stream subsystem.
Note this PR doesn't try to guard from user actively call `kong.request.get_header{,s}`,
which will result into an error, but rather let the log phase proceed in stream subsystem
* skip preloading headers in stream subsystem
=> fix(plugin_server) skip preloading headers in stream subsystem

autodoc/admin-api/generate.lua
In the Admin API documentation, change `Not available in DB-less mode.` to `This API is not available in DB-less mode.`
PR in the Docs repo: https://github.com/Kong/docs.konghq.com/pull/3653
=> Update Admin API note

autodoc/admin-api/data/admin-api.lua, autodoc/admin-api/generate.lua
Remove wording in Admin API docs Target Object that says targets cannot be modified or deleted.
Corresponds to: https://github.com/Kong/docs.konghq.com/pull/3663
Addresses: [DOCU-2140](https://konghq.atlassian.net/browse/DOCU-2140)
=> [DOCU-2140] Update Admin API Target Object 

kong/pluginsocket.proto, kong/runloop/plugin_servers/pb_rpc.lua
the response can be: content (as bytes), filepath of buffered data, or
error string.
Fix: Kong/go-pdk#85
Requires: Kong/go-pdk#91
=> fix(go-pdk) request.GetRawBody when buffered

kong/db/schema/init.lua, spec/02-integration/13-vaults/01-vault_spec.lua, spec/helpers.lua, spec/kong_tests.conf
When auto-dereferencing secrets fail, we have two options:
1. keep the value (which means the value is actually a reference such as: `{vault://env/cert-1/key}`
2. set value to `nil`
In both cases the error is also logged.
Original implementation followed 1. but this commit changes it to 2.
Reason being that reference strings can leak to secrets, which they are not meant to.
For example session plugin has secret. If you set secret to `{vault://env/session-secret}` and the dereferencing fails, the secret becomes `{vault://env/session-secret}`. This can lead to potential leak of secret on a system that does not resolve secrets correctly. Or at least it is not good idea that references can become secrets. This commit changes it so that on failure (we log the warning) and also set the value to …
=> fix(db) when auto-dereferencing fails set value to nil

CHANGELOG.md, kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/constants.lua, kong/db/declarative/init.lua, spec/02-integration/04-admin_api/02-kong_routes_spec.lua, spec/02-integration/08-status_api/01-core_routes_spec.lua
This change adds back the `configuration_hash` entry to the `/status` endpoint when using dbless mode/node is a dataplane and no configuration has been loaded.
See #8214 for reference.
* `configuration_hash` returns `"00000000000000000000000000000000"` when no configuration has been loaded.
* Tests updated.
FT-2358
=> fix(declarative) initialize hash for empty config

kong/pdk/vault.lua
This fixes the vault to fill default values for configuration based on a config field schema in case the field is required and has a default value, when there is no configuration for the field already.
=> fix(pdk) fill default values with vault config required fields

kong/plugins/cors/handler.lua, spec/03-plugins/13-cors/01-access_spec.lua
The CORS plugin currently always sets a `Vary: Origin` header on
responses.
`Vary: Origin` should not be sent together with `Access-Control-Allow-Origin: *` since the response won't vary by the `Origin` request header.
Unnecessarily sending the `Vary: Origin` header can cause issues with intermediate caches and cause them to either create identical cache copies for each origin or cause them to outright refuse caching the result.
This fixes behavior by no longer sending a `Vary: Origin` header when
`Access-Control-Allow-Origin: *` and credentials is disabled.
* don't send vary: origin header when access-control-allow-origin header is *
* update tests to match behavior of not sending vary: origin header when access-control-allow-origin header is *
=> fix(cors) don't send vary header with * origin

kong/plugins/oauth2/access.lua, spec/03-plugins/25-oauth2/03-access_spec.lua
It was reported that when Kong OAuth 2.0 plugin is configured together with some other authentication plugin with `conf.anonymous` (logical OR), the OAuth 2.0 plugin does not clear `X-Authenticated-UserId` and `X-Authenticated-Scope` headers that it normally only sets on successful authentication (aka when plugin runs).
This can lead to potential issue on upstream if upstream rely on these headers and trust that they came from OAuth 2.0 plugin. This change makes OAuth 2.0 plugin to clear such headers in logical OR scenario.
It is to be noted that Kong itself worked as expected, it is just about the expectations that upstream service may have made. It is probably harmless to remove these headers when OAuth 2.0 plugin is configured in logical OR.
=> fix(oauth2) clear authenticated oauth2 headers with multi-auth

kong/plugins/datadog/schema.lua
I found out that datadog schema specifies default for metrics in two levels. Once in config field level and second in metrics level. The config field level causes validation errors in schema loading but those errors are ignored by our loader for some reason. Still I think this is a bug and the default should not be there twice.
=> fix(datadog) default value for metrics specified twice

kong/runloop/plugin_servers/process.lua
The properties `go_pluginserver_exe` and `go_pluginserver` are
deprecated in favor of new multi-pluginservers implementation.
Compatibility code will remain in place until 3.0, when it will be
removed.
=> chore(deprecation) add deprecation warning

kong/plugins/rate-limiting/handler.lua, kong/plugins/response-ratelimiting/handler.lua
Bumping for the new redis_username field.
=> Bump plugin versions of rate-limiting and response-ratelimiting (2.8.x)

kong/plugins/prometheus/exporter.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua
This adds gauges to track ngx.timer.running_count() and ngx.timer.pending_count() as requested by @rishabh-gupta2.
Fix #7670
=> feat(prometheus) add nginx timer metrics

CHANGELOG.md
This PR adds a deprecation notice for the external go-pluginserver.
=> docs(changelog) add deprecation of go-pluginserver

kong/plugins/acme/handler.lua, kong/plugins/cors/handler.lua, kong/plugins/datadog/handler.lua, kong/plugins/oauth2/handler.lua, kong/plugins/prometheus/handler.lua
Several plugins should be bumped because we made changes to them.
On Kong 3.0.0 we will change this so the bundled plugin versions
coincide with Kong version
Bumped because of new features:
* ACME #8114
* Prometheus #8387
Bumped because of new fixes:
* CORS #8401
* oauth2 #8422
* Datadog #8315
=> chore(plugins) bump some plugin versions due to changes

kong/router.lua
It seems that methods_t / snis_t does not use function append(),
so the [0] is useless.
* remove [0] in methods_t/snis_t
=> chore(router) remove [0] in methods_t/snis_t

kong/plugins/zipkin/tracing_headers.lua, spec/03-plugins/34-zipkin/tracing_headers_spec.lua, spec/03-plugins/34-zipkin/zipkin_no_endpoint_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua
With the latest [spec](https://www.jaegertracing.io/docs/1.29/client-libraries/#tracespan-identity) of `uber-trace-id`, parent_id is not mandatory. Because of this zipkin plugin validation is failing if the parent_id is sent as `0` and it is recreating the header with new `trace_id`. This results in not propagating the downstream context to upstream services.
=> fix(zipkin): jaeger header validation

kong/runloop/handler.lua
There are some localized var like `operation` `target` `upstream`,
but these localized var are not used wisely.
I don't know the reason, please check the code or give me an explain.
* use localized var in place of original var
=> chore(runloop) use localized var in worker events handler

autodoc/admin-api/data/admin-api.lua
Added description for the field `configuration_hash` in the `/status` endpoint.
#8214 
#8425
=> docs(admin-api) field configuration_hash in /status

autodoc/admin-api/data/admin-api.lua
Remove Admin API **Delete Service Associated to a Specific Route** endpoint.
Accompanying PR for https://github.com/Kong/docs.konghq.com/pull/3740
=> [DOCU-348] Admin API: rm DEL service for route

kong/db/declarative/init.lua
fix(admin) 500 response when post /config API busy
When admin API /config is busy loading new config and another upload requested, server response with 500, and message like: failed to broadcast reconfigure event: recursive.
This is caused by `worker_event`'s implementation of detection of recursive. We solve this by rejecting upload requests when busy(429 instead of 500)
Fix FT-2472
=> fix(admin) 500 response when post /config API busy

.github/labeler.yml, DEVELOPER.md
The labeler does not add some labels correctly, such as I create a PR to change the `DEVELOPER.md`, the labeler should add the label named 'corex/docs', but it is not now.
Example: #8518
=> Chore(labeler) does not add some labels correctly

kong/db/schema/init.lua, kong/plugins/response-ratelimiting/access.lua, spec/03-plugins/24-response-rate-limiting/01-schema_spec.lua
If `config.limits.{limit_name}.*` is `null`, this plugin will raise a HTTP 500 error.
* If `config.limits.{limit_name}.*` is `null`,  skip it.
* Add a related test in `spec/03-plugins/24-response-rate-limiting/01-schema_spec.lua`.
Fix #8314
=> fix(schema-validator) does not convert the `null` in the declarative configuration to `nil`

DEVELOPER.md
The chapter doesn't address patches that should be applied to OpenResty and other dependencies, and the link it contains is outdated(which redirects to kong/kong's git repo).
Fix FT-2487
=> docs(*) update source install instructions

kong/clustering/control_plane.lua
We should use `ngx.ERROR` in `ngx.exit()`, not `ngx.ERR` which is used in `ngx.log`
* use ngx.exit(ngx.ERROR)
=> fix(clustering) use ngx.exit(ngx.ERROR)

UPGRADE.md
Remove backticks from Upgrade page headers to create more styling consistency.
Related to: https://github.com/Kong/docs.konghq.com/pull/3756
=> [DOCU-1996] Rm code backticks from upgrade headers

CHANGELOG.md, kong-2.8.0-0.rockspec
- **obj:** clean up stale error occured from OBJ_txt2* [219a2f0](https://github.com/fffonion/lua-resty-openssl/commit/219a2f0cace8480800394d6e88b188138f2650a1)
- **pkey:** clear_error in passphrase type mismatch [8577422](https://github.com/fffonion/lua-resty-openssl/commit/857742273629d4e801a2d862644213fe5fdbf02a)
- **x509.\*:** move clear_error to last when loading [369eea1](https://github.com/fffonion/lua-resty-openssl/commit/369eea1e4a1a185055296e07f272a3e470442916)
- **openssl:** add function to list SSL ciphers [9861af1](https://github.com/fffonion/lua-resty-openssl/commit/9861af1a074f74f529e341049ada29cbf7d57a48)
- **ssl:** refine various handshake controlling functions [30bf41e](https://github.com/fffonion/lua-resty-openssl/commit/30bf41e958775f60afff1976fe731978c816dd25)
=> chore(deps) bump resty.openssl from 0.8.5 to 0.8.6

kong/pdk/service.lua
The text was limiting to IP addresses, but hostnames can also be set (as well as Upstream names).
=> docs(pdk) hostnames are allowed in kong.service.*

kong/plugins/prometheus/prometheus.lua
Prometheus metric with boolean label (false) is ignored due to this check
=> fix(prometheus): fix for boolean label handling

kong/plugins/pre-function/_handler.lua, kong/plugins/pre-function/_schema.lua, spec/03-plugins/33-serverless-functions/01-schema_spec.lua, spec/03-plugins/33-serverless-functions/02-access_spec.lua, spec/03-plugins/33-serverless-functions/03-dbless_spec.lua, spec/03-plugins/36-request-transformer/02-access_spec.lua
remove `config.functions` from serverless plugin schema
migrations for replace `conifig.functions` with `config.access` might needed.
FT-2557
=> fix(serverless) remove `config.functions` from schema

kong/plugins/hmac-auth/access.lua, spec/03-plugins/19-hmac-auth/03-access_spec.lua
Remove deprecated signatures from hmac-auth plugin
FT-2557
=> fix(hmac-auth) remove deprecated signatures

kong/templates/nginx_kong.lua, spec/fixtures/custom_nginx.template
In `lua-kong-module` we add a new param `default` for directive `lua_kong_load_var_index`,
It will add many commonly used var index by default.
With this param, the nginx template can be simplified greatly.
Please see:
https://github.com/Kong/lua-kong-nginx-module/pull/34
https://github.com/Kong/lua-kong-nginx-module/pull/35
* use `lua_kong_load_var_index default`
* remove other `lua_kong_load_var_index`
=> style(templates) use var_index default

kong-2.8.0-0.rockspec, spec/helpers.lua, spec/helpers/ssl.lua
Replace the SSL wrapper in spec.helpers.tcp_server to based on an FFI implementation, and choosed in
precedence of `luasec`. `luasec` doesn't compile happily with BoringSSL and there's too much work to
make it compatible, as BoringSSL has fairly freewill API choice that spans across multiple versions of OpenSSL.
However, both implementation has stable interface to SSL_*. This PR allows us to spin up a SSL server based on
luasocket without luasec.
*  use FFI based SSL server in tests
=> tests(helpers) use FFI based SSL server in tests

CHANGELOG.md, kong/plugins/acme/schema.lua
Acme auth_method schema will gain default = "token", one_of = { "token", "kubernetes" }
FT-2557
=> chore(acme) auth_method default value

kong/cmd/utils/env.lua, kong/vaults/env/init.lua
ffi.C.environ's address can change during realloc, this patch
avoid globalize it to prevent pointing to wrong memory address
cc @aboudreault
=> fix(env) localize environ pointer and early return on nil

kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/db/declarative/init.lua, kong/runloop/handler.lua, spec/01-unit/19-hybrid/02-clustering_spec.lua
Implements conditional rebuilding of `router`, `plugins iterator` and `balancer` on data planes. This means that DPs will not rebuild router if there were no changes in routes or services. Similarly, the plugins iterator will not be rebuild if there were no changes to plugins, and finally balancer in not reinitialized if there are no changes to upstreams or targets.
=> perf(clustering) conditional rebuilding of router, plugins iterator and balancer on dp

CHANGELOG.md, kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua
Router and plugin iterator rebuild timers were scheduled using `ngx.timer.every`. If the rebuild processes took longer than `worker_state_update_frequency` to execute, they would start again while the previous one was still running.
* Change `ngx.timer.every` calls to `ngx.timer.at`.
* Previously returned error `"plugins iterator was changed while rebuilding it"` is now logged as an info message.
* No tests were added, the behavior is the same as before.
There were multiple reports of `"plugins iterator was changed while rebuilding it"` logged as error.
Fix #8525 
FTI-3239
=> fix(runloop) reschedule rebuild timers after running them

kong/db/dao/init.lua, spec/01-unit/01-db/04-dao_spec.lua
This makes the `cache_key` function more robust. For example this code may be quite common:
```lua
local route = kong.db.routes:select_by_name("my-route")
-- {
--   id = ...,
--   name = "my-route",
--   ...
--   service = {
--     id = ...
--   }
-- }
local cache_key = kong.db.services:cache_key(route.service)
```
Now if `service` schema has `cache_key = { "name" }` (it does not, but just as an example) you can see that the `local cache_key` will then be same for all the `services` (no matter if they are pointing to different service by id), as the `route.service` is not expanded by default, and it only contains the primary key, in this case `id`.
The change in this commit is that it will now actually fallback to `primary_key = { "id" }` in case it cannot find anything by the …
=> fix(db) make dao:cache_key to fallback to primary_key if nothing from cache_key was found

CHANGELOG.md, kong/templates/nginx_kong.lua, spec/fixtures/custom_nginx.template
This `server {}` block previously had no `error_log` directive, so it was inheriting the `proxy_error_log` settings from the `http {}` scope. Logging to the same place as `admin_error_log` is more sensible. We might want to consider introducing a new `cluster_error_log` config option at some point to give users more flexibility (using `admin_error_log` as a fallback), but to me this seems fine for now.
=> fix(core) use admin_error_log for cluster listener

CHANGELOG.md, kong-2.8.0-0.rockspec
- **x509.crl:** add functions to find and inspect revoked list in CRL [37c1661](https://github.com/fffonion/lua-resty-openssl/commit/37c1661fbebebad3b804f602f631e4ba65b80e07)
=> chore(deps) bump resty.openssl from 0.8.6 to 0.8.7

CHANGELOG.md, kong-2.8.0-0.rockspec
* A minimal performance test was introduced. Several refactors were introduced, which seem to make inspect.lua faster now.
* inspect.lua was rewritten using Teal
=> chore(deps) bump inspect from 3.1.2 to 3.1.3

Makefile
Bumps `luacheck` development dependency from 0.25.0 to 0.26.0.
* Add "unused hint" flag — @javierguerragiraldez
Function arguments that start with a single underscore get an "unused hint".
Leaving them unused doesn't result in a warning.
Using them, on the other hand, is a new warning (№ 214).
* Add hook to enable Luacheck for use in pre-commit — @mblayman
* Warn on error-prone and unnecessary negations — @arichard4
Two new warnings (№ 581 and 582) flag error-prone operator orders.
* Add Dockerfile implementation — @MartinBroers
A 6.34MB containerized image with everything needed to run the linter.
Build your own or pull prebuilt images from GHRC.
* Setup repository for use *as* a GitHub Action — @alerque
Lint your repositories using GitHub Action workflows with just a single `uses:` …
=> chore(deps) bump luacheck from 0.25.0 to 0.26.0

CHANGELOG.md, kong-2.8.0-0.rockspec
Bump lua-resty-healthcheck to 1.5.1
FTI-3262
=> chore(rockspec) bump lua-resty-healthcheck 1.5.1

CHANGELOG.md
Do not reigister unnecessary event handlers on Hybrid mode Control Plane nodes
=> docs(CHANGELOG) add change log entry for #8452

CHANGELOG.md, kong/api/routes/upstreams.lua, spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/02-integration/04-admin_api/15-off_spec.lua, spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua, spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua, spec/fixtures/admin_api.lua, spec/fixtures/balancer_utils.lua
Kong has used the [POST](https://www.ietf.org/rfc/rfc2616.html#section-9.5) method to insert and update targets since always, but [RFC-2616](https://www.ietf.org/rfc/rfc2616.html) defines that the [PUT](https://www.ietf.org/rfc/rfc2616.html#section-9.6) method is the one appropriate one for this action.
This is a breaking change planned for the next major version.
* Changed method in Admin API.
* Updated tests and test helper functions.
FT-2544
=> fix(api) targets upserts using PUT HTTP method

autodoc/admin-api/data/admin-api.lua
Document missing feature for Kong 2.8.x
* Document regex header matching, implemented in #6079
=> docs(api) document header regex in autodocs admin api

autodoc/admin-api/data/admin-api.lua
in config hash returned by `/status`
=> docs(admin-api) clarify what `"00000000000000000000000000000000"` means

CHANGELOG.md, kong/plugins/proxy-cache/handler.lua
`proxy_cache_hit` contains the response data to be shared with the logging plugins. Originally it was added to the generic Nginx request's ctx, then later it was changed to use Kong's ctx but the previous one was kept as a backward compatibility. For the next major version this compatibility will be removed.
* Removed `proxy_cache_hit` backward compatibility.
FT-2559
=> chore(proxy-cache) do not copy response data to request's ctx

CHANGELOG.md, kong/runloop/balancer/targets.lua
If the target event received is not creating a new target, the DNS record renewal for said record must be stopped. If it's not, Kong will keep resolving every removed/updated target it ever known.
* When a target event different from `"create"` is received, remove the hostname from the heap containing the hostnames that must be resolved.
* As the heap is not exposed outside of `targets.lua`, no tests were added.
FTI-2927
=> fix(balancer) stop DNS renewal on target event

kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/db/declarative/init.lua, kong/runloop/handler.lua, spec/01-unit/19-hybrid/02-clustering_spec.lua
backport of #8519 
Implements conditional rebuilding of `router`, `plugins iterator` and `balancer` on
data planes. This means that DPs will not rebuild router if there were no changes in
routes or services. Similarly, the plugins iterator will not be rebuild if there were
no changes to plugins, and finally balancer in not reinitialized if there are no
changes to upstreams or targets.
=> perf(clustering) conditional rebuilding of router, plugins iterator and balancer on dp (2.8)

Jenkinsfile
=> chore(build) Don't build debian jessie since this is failing

CHANGELOG.md, kong/runloop/plugin_servers/mp_rpc.lua, spec/01-unit/25-msgpack_rpc_spec.lua
=> fix(pdk): msgpack rpc functions handles binary

kong/templates/nginx_kong_stream.lua, kong/tools/stream_api.lua, spec/02-integration/12-stream_api/01-stream_api_endpoint_spec.lua, spec/fixtures/custom_nginx.template, spec/fixtures/custom_plugins/kong/plugins/stream-api-echo/api.lua
This re-implements the stream API with TCP instead of UDP in order to allow for larger response payloads without having to handle chunking/fragmenting things ourselves.
Performance-wise, keep-alive is used to cut down on per-request connection overhead, and the message payload is sent raw instead of being packed/unpacked on either side. I've done some unscientific testing locally with a single-threaded client and an API that simply echoes back the input payload. With a payload size of 8000 (the max of the current implementation) I am getting ~7-8k rps with the current implementation and ~8-9k rps with this new implementation. Things will obviously degrade from there with larger payload sizes, though I don't think I've raised the limit so high as to necessitate further optimizations (let …
=> feat(stream_api): use TCP instead of UDP

spec/fixtures/https_server.lua
Penlight functions that were in the `pl_text` module in previous releases are now in `pl_stringx`. This uses the correct module and avoids the display of warning messages.
=> tests(fixtures) use functions from pl_stringx

kong.conf.default, kong/cmd/utils/nginx_signals.lua, kong/templates/kong_defaults.lua, spec/02-integration/02-cmd/15-utils_spec.lua
I maintain several different installations of OpenResty (both vanilla and Kong-flavored) on my machine for dev/testing of different projects.
The first time I went to run the Kong test suite locally, I spent a half hour or so scratching my head and cursing the sky over this error:
```
nginx: [emerg] unknown directive "lua_kong_load_var_index" in /home/flrgh/git/kong/kong/servroot/nginx.conf:69
nginx: configuration file /home/flrgh/git/kong/kong/servroot/nginx.conf test failed
```
_But I prepended the correct NGINX bin dir to my PATH already--why doesn't it work?!_
As I would soon discover, Kong searches some common OpenResty system/default paths _before_ consulting PATH, making it impossible to use a non-standard OpenResty installation for running the Kong cli, busted, etc. if system …
=> feat(conf) allow user-specified OpenResty install path

scripts/make-patch-release
`scripts/make_patch_release` wanted to use the old `master/next` model, in which all changes were merged back to `master`.
In our new branching model, patch releases (`2.7.1` branch off from minor branches (`release/2.7.x`). That's what "$base" points to.
This PR also includes some minor changes to the script to appease shellcheck, on a separate commit
- chore(scripts) update make_patch_release to new branching model
- chore(scripts) make shellcheck happy about make-patch-release
=> chore(scripts) update make_patch_release to new branching model

scripts/common.sh
This function was removed by mistake on a script refactor (#8078).
It was cherry-picked back into the master branch (#8495) but not to the
release/2.8.x branch. It is not needed for kong to work, but it might be
needed in order to do the post-release steps of a hypothetical 2.8.2
release.
=> chore(scripts) add missing update_docker function in release/2.8.x

kong.conf.default, kong/conf_loader/init.lua, spec/01-unit/03-conf_loader_spec.lua
When `system` was opt-in, it made sense to "fail noisily" if the current
system didn't have certs in any of the usual places and the user had
opted in to system.
Now that we look for them by default, the noisy behavior is incorrect,
because it makes kong unable to start in places with no system certs.
Instead, the abstence of default certificates gets *noted* in the logs,
but Kong can continue without them.
Related with #8602
=> hotfix(conf) make lua_ssl_trusted_certificate fail softly on launch

CHANGELOG.md, kong/runloop/plugin_servers/pb_rpc.lua
Fix issue where the Go plugin instance would not get updated after
a plugin server restart.
Fixes #8293
=> fix(plugins) ensure go plugins on protobuf restart instance

.github/workflows/build_and_test.yml
Let's use our kong/grpcbin image in CI until we get an official PR merged on the moul/grpcbin repo.
https://hub.docker.com/r/kong/grpcbin/tags
=> ci(*) use kong/grpcbin instead of moul/grpcbin for arm64 support

kong-2.8.1-0.rockspec
Luarocks upload was failing when trying to download the rock from
Github, which was failing with "The unauthenticated git protocol
on port 9418 is no longer supported". More information here:
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
We're replacing git with https, which is one of the fixes recommended on
that guide.
=> chore(rockspec) replace git protocol by https

CODEOWNERS
This adds the `CODEOWNERS` file to the repository. This is the first step in configuring approval permissions. Once this file is merge into the repo, I can enable the branch protection settings for CODEOWNERS. 
* ...
=> chore(*): add a CODEOWNERS file to the repo

kong/plugins/ldap-auth/asn1.lua
Small fix for #8663 
The bug won't affect the existing functionality in the CE version.
=> fix(ldap-auth) free internal pointer after covert to lua string

.github/labeler.yml
Any PR includes a changelog will add a “core/docs” label which is unnecessary, this PR added an extra label 'changelog' to detect changelog file changes.
=> chore(ci) changelog label

CHANGELOG.md, kong/runloop/balancer/targets.lua
Due to a missing check on DNS resolve timer callback, messages like this were logged when issuing a `kong reload` command:
```
2022/04/19 20:44:45 [crit] 80722#0: *17 [lua] targets.lua:248: could not reschedule DNS resolver timer: process exiting, context: ngx.timer
```
* Added check for [`premature`](https://github.com/openresty/lua-nginx-module#ngxtimerat) schedules and ignored those calls instead of trying to schedule and throwing an error.
=> fix(balancer) do not reschedule resolve timer when reloading

kong/db/declarative/init.lua
Adds support for atomic exports of declarative configs with Postgres.
=> feat(clustering) atomic exports of declarative configs with postgres

CHANGELOG.md, kong/pdk/response.lua, t/01-pdk/08-response/05-set_header.t, t/01-pdk/08-response/08-set_headers.t, t/01-pdk/08-response/11-exit.t
Users should not set the Tranfer-Encoding header and it is also not supported by OpenResty.
Fix #8083
Fix CT-312
=> fix(pdk) ignore user set Tranfer-Encoding

spec/02-integration/09-hybrid_mode/03-pki_spec.lua
The first test in this group is flaky, and is delaying development in other areas.
Marking the whole group as flaky since the other test depends on the
first one, as a stopgap solution until we find a better way to do this.
=> tests(hybrid) mark test as flaky

kong/clustering/control_plane.lua, kong/clustering/wrpc_control_plane.lua
We are already wrapping some calls to
`export_deflated_reconfigure_payload()` inside a pcall in the
`control_plane.lua` file. This change is doing a pcall in all the
remaining calls to `export_deflated_reconfigure_payload()` in this file
to avoid the CP crash whenever we find errors during initialization of
modules for example.
=> fix(cp) do a pcall for all calls to export_deflated_reconfigure_payload

Jenkinsfile
Some recent PR's have broken our ability to package / run Kong.
This PR uses our packaging / release tooling to do a single test run.
=> test(packaging): do a quick validation that Kong can viably be packaged

Jenkinsfile
I accidentally committed a hard coded absolute path. I removed / fixed it to be relative
=> chore(ci): fix the test packaging

CHANGELOG.md, kong-2.8.0-0.rockspec
- **ctx:** use global ctx where request is unavailable [e3590cf](https://github.com/fffonion/lua-resty-openssl/commit/e3590cfcbeb6f0d5f110c3c4e1b6cdc63b88e001)
- **x509.extension:** correct X509V3_CTX size for OpenSSL 3.0 [0946c59](https://github.com/fffonion/lua-resty-openssl/commit/0946c5937fa9fa4bb41a70267a67fcc87307b6a6)
- **x509.extension:** add X509V3_set_issuer_pkey in OpenSSL 3.0 [dbd3f74](https://github.com/fffonion/lua-resty-openssl/commit/dbd3f7418a665ae797e6ffc71ba1d7f0660c95f0)
- **x509.store:** add set_purpose and verify_method parameter [b7500fe](https://github.com/fffonion/lua-resty-openssl/commit/b7500fe7212c26070363afeab4a8acfe44c3cfc8)
=> chore(deps) bump resty.openssl from 0.8.7 to 0.8.8

CHANGELOG.md, kong-2.8.0-0.rockspec
* Fix missing DANE flag
* Remove unused parameter in https.lua
=> chore(deps) bump luasec from 1.0.2 to 1.1.0

Makefile
- Exempt special builtin \_ENV from 214 warning
- In case of no home environment, default to caching in CWD 
- Add multi-thread support to container
- Tweak warning message for 214 to be more explicit
=> chore(deps) bump luacheck (dev dep) from 0.26.0 to 0.26.1

CHANGELOG.md, kong-2.8.0-0.rockspec
* Fix: avoid breaking active health checks when adding or removing targets.
=> chore(deps) bump resty.healthcheck from 1.5.0 to 1.5.1

kong-2.8.0-0.rockspec, kong/cmd/reload.lua, kong/cmd/utils/nginx_signals.lua, kong/cmd/utils/prefix_handler.lua, kong/cmd/utils/process_secrets.lua, kong/conf_loader/init.lua, kong/db/schema/entities/vaults_beta.lua, kong/pdk/vault.lua, spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/02-cmd/03-reload_spec.lua, spec/02-integration/13-vaults/01-vault_spec.lua, spec/02-integration/13-vaults/03-mock_spec.lua, spec/fixtures/custom_vaults/kong/vaults/mock/init.lua, spec/fixtures/custom_vaults/kong/vaults/mock/schema.lua, spec/helpers.lua, spec/kong_tests.conf
This PR comes with a few more fixes to Vault on how it handles process secrets.
Kong escapes e.g. `"#"` with `"\#"`, and these need to be removed before passing them to vault functions as otherwise reference like:
```
{vault://env/pg-passwordhttps://github.com/Kong/kong/issues/1}
```
Doesn't work as it gets past as:
```
{vault://env/pg-password\#1}
```
This fixes that.
Kong's initialization parses Kong configuration twice:
1. first the config is parsed in timer context by kong start (cli)
2. then the config is parsed again in init context when kong server is started
Many Vault implementations will require the availability of `ngx.socket.tcp` to be able to fetch secrets. Unfortunately the `ngx.socket.tcp` is not available on init or init worker phases, but it works on timer context. …
=> fix(conf) vault inferring and no request found

kong/api/routes/health.lua, kong/pdk/nginx.lua, kong/plugins/prometheus/exporter.lua, kong/templates/nginx_kong.lua, spec/03-plugins/26-prometheus/05-metrics_spec.lua, spec/fixtures/custom_nginx.template, spec/fixtures/prometheus/metrics.conf, t/01-pdk/10-nginx/00-phase_checks.t, t/01-pdk/10-nginx/02-get_statistics.t
:8444/status does not support HTTP/2 due to
"ngx.location.capture". Now use LuaJIT ffi to retrieve Nginx status
data.
The "/nginx_status" location block is left in nginx-kong.conf as other
components may depend on it.
=> fix(admin) support HTTP/2 when requesting /status

.github/workflows/build_and_test.yml, scripts/validate-rockspec
Not sure if something like this exists already (or how useful it is), but here's a quick n' dirty validation script:
1. Ensures that only one rockspec file exists
2. Runs `luarocks lint` on the rockspec file
3. Validates that all modules in the rockspec file are present on disk
4. Validates that all files in kong have a corresponding entry in the rockspec file
```
$ ./scripts/validate-rockspec
Found rockspec file to validate: kong-2.8.0-0.rockspec
Linting...
Checking modules...
OK!
```
```
$ ./scripts/validate-rockspec
Failure: No rockspec file found
```
```
$ ./scripts/validate-rockspec
Failure: Multiple rockspec files found: kong-2.8.0-0.rockspec kong-2.8.0-1.rockspec
```
```
$ ./scripts/validate-rockspec
Found rockspec file to validate: kong-2.8.0-0.rockspec
Linting...
Error: Failed …
```
=> tests(rockspec) add a script to validate rockspec file

Jenkinsfile
adjust commit based releases to return a calver on `kong version` command and to push a calver'd docker tag per https://github.com/Kong/kong-madr/pull/37
=> chore(ci): adjust how we version our nightlies

kong/plugins/aws-lambda/handler.lua, spec/03-plugins/27-aws-lambda/99-access_spec.lua
Hi, I would like to add some compatibility to Kong's `aws-lambda` plugin so that it can receive string type status code when working in the proxy integration mode.
When AWS Lambda function is working as a proxy integration, the `statusCode` returned by lambda function will become the HTTP status code returned by API gateway.
Currently, we only accept number type `statusCode`,
https://github.com/Kong/kong/blob/23f50ea1cd3e6985713ea29c81bc4d50f86f2d6e/kong/plugins/aws-lambda/handler.lua#L75
After some tests I found that AWS API gateway works fine if the type of `statusCode` is either number or string. And if the `statusCode` is an invalid HTTP status code, such as `600`(smaller than 100 or larger than 599) or `200a`(containing non-numeric characters), it will throw an "internal server …
=> feat(plugin/aws-lambda)accept string type statusCode as return when working in proxy integration mode

kong/db/strategies/off/init.lua
DBless doesn't naturally yield (not with `shared dict`, nor with `lmdb`). This may cause latency spikes when iterating over bigger lists, e.g. `kong.db.routes:each()`. This commit adds some yields so that iterating doesn't fully block the worker from doing other work too, so this is about cooperative multitasking.
=> perf(db) yield on dbless daos

kong/db/schema/init.lua, kong/db/strategies/off/init.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua
It is inefficient to create deep copies of tables when e.g. looping through database rows (and with records in them we recursively deep copy them). In my testing with uploading some 64k routes with dbless (which calls process auto fields twice), this can cut the time looping the data by 1/4th. It also generates much less garbage.
I searched our code bases where we use "select" context, and could not find anything that might break because of this.
=> perf(schema) no deep copy on select on process auto fields

CHANGELOG.md
This reflects the documentation side of the work to deprecate Debian 8 detailed in [ENGEN-450](https://konghq.atlassian.net/browse/ENGEN-450).
The deprecation of Debian 8 (by which I mean we stop making Debian 8-based packages and container) is targetting Kong Gateway(s) 3.0.
So the intent with this PR is that these changelog messages trickle down to kong-ee as well. If that assumption is false and I need to say, open a sister PR there, please let me know.
> - Deprecate/stop producing Debian 8 "Jessie" containers and packages (EOLed June 2020)
[Kong/kong-build-tools #448](https://github.com/Kong/kong-build-tools/pull/448)
[Kong/kong-distributions #766](https://github.com/Kong/kong-distributions/pull/766)
=> [ENGEN-450] chore(changelog) debian 8 deprecation notice

.github/workflows/build_and_test.yml, spec/02-integration/05-proxy/02-router_spec.lua, spec/02-integration/05-proxy/19-grpc_proxy_spec.lua, spec/02-integration/05-proxy/21-grpc_plugins_triggering_spec.lua, spec/02-integration/05-proxy/22-reports_spec.lua, spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua, spec/03-plugins/02-udp-log/01-udp-log_spec.lua, spec/03-plugins/03-http-log/01-log_spec.lua, spec/03-plugins/04-file-log/01-log_spec.lua, spec/03-plugins/05-syslog/01-log_spec.lua, spec/03-plugins/06-statsd/01-log_spec.lua, spec/03-plugins/07-loggly/01-log_spec.lua, spec/03-plugins/08-datadog/01-log_spec.lua, spec/03-plugins/09-key-auth/02-access_spec.lua, spec/03-plugins/10-basic-auth/03-access_spec.lua, spec/03-plugins/11-correlation-id/01-access_spec.lua, spec/03-plugins/14-request-termination/02-access_spec.lua, spec/03-plugins/16-jwt/03-access_spec.lua, spec/03-plugins/17-ip-restriction/02-access_spec.lua, spec/03-plugins/19-hmac-auth/03-access_spec.lua, spec/03-plugins/20-ldap-auth/01-access_spec.lua, spec/03-plugins/21-bot-detection/01-access_spec.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua, spec/03-plugins/24-response-rate-limiting/04-access_spec.lua, spec/03-plugins/25-oauth2/03-access_spec.lua, spec/03-plugins/26-prometheus/02-access_spec.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua, spec/03-plugins/32-grpc-web/01-proxy_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua, spec/helpers.lua
Now, the `host` and `port` of the `grpcbin` used for testing are fixed in the code and not easy to change. These parameters should be allowed to be changed via environment variables.
This PR introduces three environment variables to improve it:
* `KONG_SPEC_TEST_GRPCBIN_HOST`
* `KONG_SPEC_TEST_GRPCBIN_PORT`
* `KONG_SPEC_TEST_GRPCBIN_SSL_PORT`
=> tests(*) make the `host` and `port` of `grpcbin` configurable

kong/pdk/request.lua, t/01-pdk/04-request/13-get_header.t
Applying suggestions from OpenResty contributors. We use `ngx.var.http_*` to get the header.
Notice that the behavior changes. Now `request.get_header` does not have a limit of header number.
Fix FT-2780
=> perf(pdk) faster request.get_header

kong/runloop/balancer/init.lua
When a target was added using only its hostname, it was not possible to update its health status using only the hostname, i.e. omitting the IP. This change fixes that issue.
This problem was identified while fixing a different issue. The tests don't fail because their current behavior is removing a healthy target and adding it again as unhealthy. The test is already fixed in a different branch (fix/target_creation_method).
* Check if the ip received is actually an ip before trying to set the health status.
=> fix(balancer) set target status using hostname

CHANGELOG.md, kong/api/routes/kong.lua
instead of a list of plugin names with values `true` it will now report the plugin versions:
```json
"plugins": {
"available_on_server": {
"acl": "3.0.1",
"acme": "0.4.0",
"aws-lambda": "3.6.3",
"azure-functions": "1.0.1",
"basic-auth": "2.2.0",
"bot-detection": "2.0.0",
"correlation-id": "2.0.2",
"cors": "2.1.1",
"datadog": "3.1.1",
"file-log": "2.1.0",
"grpc-gateway": "0.2.0",
"grpc-web": "0.3.0",
"hmac-auth": "2.4.0",
"http-log": "2.1.1",
"ip-restriction": "2.0.0",
"jwt": "2.2.0",
"key-auth": "2.4.0",
"ldap-auth": "2.2.0",
"loggly": "2.1.0",
"oauth2": "2.1.2",
"post-function": "2.1.0",
"pre-function": "2.1.0",
"prometheus": "1.6.0",
"proxy-cache": "1.3.2",
"rate-limiting": "2.4.0",
"request-size-limiting": "2.0.0",
"request-termination": "2.1.0",
"request-transformer": "1.3.3", …
```
=> feat(api) report plugin versions on server

kong/clustering/wrpc_data_plane.lua
yield
`update_config` can yield, so we need to cache fields in `self`, otherwise it might got updated (on L89) before we read it (on L208), and causes L202 become false next time, thus prevent next ConfigSync being executed. This probably become more visiable as we introduce more `yield` from #8800.
*  localize config_version to avoid race condition from yield
=> fix(clustering) localize config_version to avoid race condition from

kong/api/routes/kong.lua
besides exposing the version, the priority of a plugin is also a property that quite often is unclear to users, so dynamically getting it from the system will help answering those questions.
I didn't include it in the original PR (#8810 ), because of the upcoming dynamic priorities. But after a chat with @jschmid1 it turns out that the hard-coded priorities will remain the default, so still makes sense to expose those as well.
Also; removed the `true` placeholder, which doesn't make sense anymore now that the metadata is an object
=> feat(api) add plugin priority to metadata

CHANGELOG.md, kong/api/routes/upstreams.lua, spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua, spec/02-integration/05-proxy/10-balancer/02-least-connections_spec.lua, spec/fixtures/admin_api.lua, spec/fixtures/balancer_utils.lua
In Kong 2.x series it was possible to update targets using `POST` method. When fixing this behavior, the path `/upstreams/{upstream}/targets` was mistakenly changed to also use `PUT` method, instead of only blocking adding duplicated targets. This PR changes it.
* Removed support to `PUT` in `/upstreams/{upstream}/targets`
* Refuse to update targets using `POST`.
* Tests updated.
* ~~Cherry-picked #8797, in order to the tests to pass.~~ Needed sister PR already merged.
FT-2874
DECK-64
=> fix(api): use POST to add targets to specific upstream

CHANGELOG.md, kong-2.8.0-0.rockspec
> Released on: 2022/05/20
- Improve DC-aware LB policies robustness. [#147](https://github.com/thibaultcha/lua-cassandra/pull/147)
- Ensure request-aware + DC-aware LB policy prioritizes local peers over remote ones.
=> chore(deps) bump resty.cassandra from 1.5.1 to 1.5.2

kong/clustering/data_plane.lua, kong/clustering/utils.lua, kong/clustering/wrpc_data_plane.lua
The functions `encode_config` and `decode_config` are unnecessary and make people confused,
This PR directly uses `deflate_gzip` and `inflate_gzip`, and hides the gzip details in the `utils` module.
* Remove encode_config` and `decode_config`  in data_plane
* Use `deflate_gzip` and `inflate_gzip` in `utils`
=> chore(cluster) remove decode/encode_config in data_plane

spec/02-integration/09-hybrid_mode/03-pki_spec.lua
wRPC should be stable now. Removing the flaky flag from the test.
=> chore(clustering)  remove wRPC flaky flag

kong/runloop/balancer/init.lua, kong/runloop/balancer/upstreams.lua, spec/02-integration/04-admin_api/15-off_spec.lua
When Kong is using `worker_consistency = eventual`, a timer is used to update the internal balancer state on every `worker_state_update_frequency` seconds. Instead of using the same timer for all changes, the said timer was being started again on every balancer update, the previous ones were kept running, piling up the number of timers.
* Fixed timer start in `runloop/balancer`.
* Added a regression test.
FTI-3274
=> fix(balancer) start only needed upstream update timers

kong/runloop/balancer/upstreams.lua, spec/02-integration/04-admin_api/15-off_spec.lua
When the balancer state timer is running, it updates the flag that avoids it to be started again on every run. This PR adds the same behavior to scheduling the update timer, instead of waiting for the first run. This change avoids that an upstream that is updated more than once before the eventual consistency timer run for the first time, schedule it again.
This PR completes the fix introduced in #8694. 
* Set running flag to `true`.
* No tests were added, they were already failing.
=> fix(upstreams) mark the update timer as scheduled

CHANGELOG.md, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/clustering/utils.lua, kong/clustering/wrpc_data_plane.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/11-dbless/03-config_persistence.lua
The data plane configuration is now persisted on disk with the LMDB database. At startup,
the node automatically reload the latest version of the configuration. The config cache mechanism is not useful
anymore.
Do not merge, depends on: https://github.com/Kong/kong/pull/8670
=> Remove config cache

kong/cluster_events/strategies/postgres.lua, kong/db/dao/init.lua, kong/db/schema/init.lua, kong/db/strategies/cassandra/init.lua, kong/db/strategies/cassandra/tags.lua, kong/db/strategies/postgres/init.lua, kong/pdk/table.lua, kong/router.lua, kong/tools/utils.lua, kong/tools/wrpc.lua
OpenResty only supports LuaJIT these days and things like `require "table.new"` and friends can be considered to be there. This commit just removes the fallback Lua functions usually associated with them. So basically cleans our code on that.
=> chore(*) do not maintain fallbacks to luajit table goodies

CHANGELOG.md, kong/pdk/request.lua, t/01-pdk/04-request/00-phase_checks.t, t/01-pdk/04-request/20-get_raw_path.t
This changes the behavior of `kong.request.get_path()` such that it performs path normalization on the value before returning it to the caller. The new PDK function `kong.request.get_raw_path()` performs no normalization and contains a notice about its potential security pitfalls when used unwisely.
**Note:** there has been much discussion on the underlying implementation/methodology of our normalization strategy (see #8140). This pull request does not attempt to resolve that discussion and only focuses on the PDK interface. The assumption here is that the implementation of `kong.tools.uri.normalize` can be updated/finalized at a later date if we wish (though some test cases and LuaDoc annotations may need to be updated depending on what changes are made).
=> feat(pdk) normalize kong.request.get_path

README.md
Replace all "Konnect” to “Konnect Cloud”
Make all links to Konnect Cloud have utm tracking parameters https://konnect.konghq.com/register/?utm_medium=Referral&utm_source=Github&utm_campaig[…]y&utm_content=konnect-promo-in-gateway&utm_term=get-started
* ...
=> Replace Konnect w/Konnect Cloud, add UTM params

kong-2.8.0-0.rockspec, kong/clustering/control_plane.lua, kong/clustering/wrpc_control_plane.lua, kong/clustering/wrpc_data_plane.lua, kong/plugins/grpc-gateway/deco.lua, kong/plugins/grpc-web/deco.lua, kong/tools/grpc.lua, kong/tools/wrpc/init.lua, kong/tools/wrpc/proto.lua, spec/01-unit/22-grpc-utils_spec.lua
The origin implementation of proto file searching is hacking with `searchpath`, and that implementation would fail to deal with `include` in a proto file that should be found outside the containing folder of that file.
What this PR does:
1. Extract proto related code into a separate module, and styling;
2. Rewrite implementation of annotation parsing;
3. Rewrite implementation of proto file searching.
=> refactor(wrpc) Refactor wRPC proto file process

kong/plugins/oauth2/daos.lua, kong/plugins/session/daos.lua
Authorization codes in general are short-lived, and exporting them is not needed.
Sessions are short-lived and not needed for exporting. It can be especially bad with enterprise if this exports sessions used for manager/developer portal to data planes.
These also make little sense on hybrid.
=> chore(oauth2/session) do not db export authorization codes or sessions

spec/02-integration/07-sdk/03-cluster_spec.lua
The first part of UUID is not 11 but 8 hex digits. and it's because the incorrect argument of `ngx.say`.
=> tests(clustering) incorrect pattern and change to print

kong/db/dao/init.lua
Hi, this PR aims to fix the bug that will cause an unexpected 404 error on creating/updating configs with invalid options.
A simple way to reproduce:
1.  Store the example config and sync the config using decK, as you can see the TTL of the consumer key is an invalid value which will not pass the [`validate_options_value` func
](https://github.com/Kong/kong/blob/fcb7275fe30ab7f4f7510cdc3ab6e90a783a868e/kong/db/dao/init.lua#L205)
```
_format_version: "1.1"
consumers:
- keyauth_credentials:
- key: test
ttl: 100000001
username: test@gmail.com
services:
- connect_timeout: 60000
host: httpbin.org
name: test1
path: /anything
plugins:
- config:
anonymous: null
hide_credentials: false
key_in_body: false
key_in_header: true
key_in_query: true
key_names:
- apikey
run_on_preflight: true
enabled: …
```
=> fix(dao) check_upsert func return value on invalid options

kong/plugins/prometheus/exporter.lua, kong/plugins/prometheus/handler.lua, spec/03-plugins/26-prometheus/02-access_spec.lua, spec/03-plugins/26-prometheus/03-custom-serve_spec.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua, spec/03-plugins/26-prometheus/05-metrics_spec.lua
Rework and Upgrade Prometheus Plugins Metrics and Labels.
These Prometheus plugin will be the first class citizen for metrics collection in Kong 3.0 and beyond. This patch attempts to lay foundation for a good set of base metrics+labels, that can also be expanded upon in later releases
* Latency has been split into 4 different metrics: `kong_latency_ms`, `upstream_latency_ms` and `request_latency_ms` (http) /`tcp_session_duration_ms` (stream). Buckets details below.
* Separate out Kong Latency Bucket values and Upstream Latency Bucket values. 
* Kong Latency and Upstream Latency can operate at orders of magnitudes different. Separate out these buckets to reduce memory overhead.
* `consumer_status` removed.
* `request_count` and `consumer_status` have been merged into just …
=> feat(plugin) Adjust Prometheus to be the reference Impl for metrics

CHANGELOG.md, kong/db/migrations/core/016_280_to_300.lua, kong/db/schema/entities/upstreams.lua, kong/runloop/balancer/init.lua, spec/01-unit/01-db/01-schema/09-upstreams_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua, spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua, spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua, spec/fixtures/balancer_utils.lua
This adds `path`, `uri_capture`, and `query_arg` as hash sources for upstreams.
There are some code simplicity vs performance vs absolute correctness tradeoffs to consider here:
* `path` sources its value from `$uri`, which is normalized according to NGINX rules and _not_ `kong.tools.uri.normalize($request_uri)`. The balancer hash is not directly exposed via any public API and is much less sensitive to compatibility issues than other areas of the codebase (i.e. `kong.router`), so I think it's okay to not be 100% consistent here.
* `query_arg` uses `ngx.req.get_uri_args`, which is semi-expensive as it creates a new table (similar to `hash_on_header` now). A feature of an upcoming OpenResty release allows optimizing away the table creation …
=> feat(balancer) add path, uri_capture, and query as hash sources

CHANGELOG.md, kong/pdk/log.lua, kong/pdk/request.lua, t/01-pdk/02-log/00-phase_checks.t, t/01-pdk/04-request/00-phase_checks.t, t/01-pdk/04-request/20-get_start_time.t
This adds `kong.request.get_start_time` as a PDK function. Before this change the business logic for computing this value was contained in `kong.log.serialize()`, so the only stable-ish API for fetching start time was `kong.log.serialize().started_at` (kind of wasteful/inelegant). Therefore this seems like a worthwhile inclusion to the PDK.
* Add `kong.request.get_start_time` PDK function.
* Update `kong.log.serialize` to use `kong.request.get_start_time`
=> feat(pdk) add kong.request.get_start_time()

kong/runloop/plugin_servers/pb_rpc.lua
Wrong commit message.
fix #8734
=> fix(core) PDK crash when return array

kong/api/routes/config.lua, kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/db/declarative/init.lua, kong/db/schema/init.lua, kong/db/schema/others/declarative_config.lua, kong/db/strategies/off/init.lua, kong/tools/utils.lua
Adds yielding to some hot paths that otherwise may cause latency spikes with huge Kong configurations. The special focus was to make CP/DP config changes less blocking.
=> perf(*) make some heavily used code paths more cooperative by yielding

CHANGELOG.md, kong/api/routes/kong.lua, kong/db/dao/plugins.lua, kong/plugins/pre-function/handler.lua, spec/02-integration/03-db/03-plugins_spec.lua, spec/fixtures/custom_plugins/kong/plugins/api-override/handler.lua, spec/fixtures/custom_plugins/kong/plugins/ctx-tests-response/handler.lua, spec/fixtures/custom_plugins/kong/plugins/ctx-tests/handler.lua, spec/fixtures/custom_plugins/kong/plugins/enable-buffering-response/handler.lua, spec/fixtures/custom_plugins/kong/plugins/enable-buffering/handler.lua, spec/fixtures/custom_plugins/kong/plugins/error-generator-last/handler.lua, spec/fixtures/custom_plugins/kong/plugins/error-generator/handler.lua, spec/fixtures/custom_plugins/kong/plugins/error-handler-log/handler.lua, spec/fixtures/custom_plugins/kong/plugins/foreign-entity/handler.lua, spec/fixtures/custom_plugins/kong/plugins/init-worker-lua-error/handler.lua, spec/fixtures/custom_plugins/kong/plugins/invalidations/handler.lua, spec/fixtures/custom_plugins/kong/plugins/reports-api/handler.lua, spec/fixtures/custom_plugins/kong/plugins/short-circuit/handler.lua, spec/fixtures/custom_plugins/kong/plugins/stream-api-echo/handler.lua, spec/fixtures/custom_plugins/kong/plugins/tcp-trace-exporter/handler.lua, spec/fixtures/custom_plugins/kong/plugins/transformations/handler.lua, spec/fixtures/custom_plugins/kong/plugins/unique-foreign/handler.lua
Adds stricter checks on plugins when loading. Priority must be a valid integer (not `inf` nor `NaN`), and the version must be parseble as `x.y.z`.
This means the `pre-functions` plugin now has a `PRIORITY = 1000000`, which previously was `+inf`.
**review**: best reviewed without whitespace changes
=> Validate plugin PRIORITY and VERSION fields upon loading

kong/resty/dns/client.lua
`lua-resty-dns` defaults this to `false`. Setting it to true allows to catch additional data into the DNS cache. And hence prevent more lookup queries.
=> perf(dns) default addition_section to true

kong-2.8.0-0.rockspec, kong/plugins/aws-lambda/handler.lua, kong/plugins/aws-lambda/iam-sts-credentials.lua, kong/plugins/aws-lambda/schema.lua, spec/03-plugins/27-aws-lambda/07-iam-sts-credentials_spec.lua
This PR adds support for assuming role based on EC2/ECS metadata credentials.
Currently, the aws-lambda plugin does not support cross-account invoking. To achieve that we need to add support for assuming roles based on EC2/ECS metadata credentials. After fetching the metadata credentials,  it'll make an additional request to AWS's STS service to ask to assume role.
Codes in the `iam-sts-credentials.lua` originated from an [old PR](https://github.com/Kong/kong-plugin-aws-lambda/pull/42), I re-arranged it and picked up part of the function that I need.
Note that this is a short term plan to support FTI-3291 as it does not modify much of the code. Hoping to catch the last train of Version 3.0. In the long term perspective, I think all the codes related to fetching AWS credentials should be …
=> feat(aws-lambda) add support for assume role based on metadata credentials

kong/db/declarative/init.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
This PR fix for a new DP get zero size config while service with plugin-enabled route is disabled.
The primary reason for this is CP does not totally filtering the exported config so when running in hybrid mode, DPs are sent disabled services and the routes/plugins associated with them. 
FTI-4009 FTI-4040
=> fix(clustering) do not export plugins on a route attached to a disabled service

.github/labeler.yml, .github/workflows/build_and_test.yml, CHANGELOG.md, kong-2.8.0-0.rockspec, kong/constants.lua, kong/include/opentelemetry/proto/collector/trace/v1/trace_service.proto, kong/include/opentelemetry/proto/common/v1/common.proto, kong/include/opentelemetry/proto/resource/v1/resource.proto, kong/include/opentelemetry/proto/trace/v1/trace.proto, kong/pdk/tracing.lua, kong/plugins/opentelemetry/handler.lua, kong/plugins/opentelemetry/otlp.lua, kong/plugins/opentelemetry/proto.lua, kong/plugins/opentelemetry/schema.lua, kong/tools/utils.lua, kong/tracing/instrumentation.lua, kong/tracing/propagation.lua, spec/01-unit/12-plugins_order_spec.lua, spec/03-plugins/37-opentelemetry/01-otlp_spec.lua, spec/03-plugins/37-opentelemetry/02-schema_spec.lua, spec/03-plugins/37-opentelemetry/03-propagation_spec.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua, spec/03-plugins/37-opentelemetry/05-otelcol_spec.lua, spec/fixtures/opentelemetry/otelcol.yaml, spec/helpers.lua
Add the OpenTelemetry plugin which pushes the build-in instrumentation to the backend server through the [OTLP/HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp) protocol with Protobuf content type.
_Note: merge using rebase strategy._
FT-2588
=> feat(plugins) opentelemetry plugin

kong/tools/utils.lua
It turned out that Kong Enterprise edition requires a tracing framework that requires `kong.tools.utils` before running the `global patches`. This means that things like `ngx.IS_CLI` is not set during `require` time and then the module gets cached. This then makes some of the unit type tests not to pass on enterprise edition CI.
There are several ways to fix this. E.g. not to require `tracing` before running global patches or just doing something like this on test setup that were failing:
```
require("kong.tools.utils").yield = function() end
```
Or setting the `ngx.IS_CLI` even before running global patches...
Here is a solution that just makes detection of `IS_CLI` to happen on yield call-time.
=> tests(*) change kong.tools.utils.yield to check IS_CLI on call time

CHANGELOG.md, kong-2.8.0-0.rockspec
- Add support for Postgres extended query protocol (using text transport)   See https://github.com/leafo/pgmoon#extended-and-simple-query-protocols
- Add support for pgmoon_serialize metamethod on objects to allow objects   to describe how they can be serialized   See https://github.com/leafo/pgmoon#custom-type-serializer
- Implement pgmoon_serialize for the included PostgresArray type
- Add the set_type_deserializer method for easier configuration of deserialization (the undocumented set_type_oid method is deprecated. See https://github.com/leafo/pgmoon#custom-type-deserializer
- The query method can now take additional arguments to cause the query to be sent using the extended query protocol with parameters from the arguments
- Array deserialization is now aware of the NULL value and …
=> chore(deps) bump pgmoon from 1.14.0 to 1.15.0

spec/01-unit/09-balancer/03-consistent_hashing_spec.lua, spec/01-unit/09-balancer/04-round_robin_spec.lua
Round-robin and consistent-hashing algorithms tests were creating new balancers with fixed number of slots (`10`) instead of using the number set in the test case.
* Fixed helper function that sets the default values for new test balancers.
=> tests(balancer) fix the slot number for new balancers

kong/plugins/aws-lambda/handler.lua
This PR is trying to separate AWS credential cache keys which are used by different aws-lambda plugins, by adding a plugin identifier in the mlcache key name.
Users might want to enable multiple aws-lambda plugins, targeting at different IAM roles and different lambda functions. Under this situation credential cache must be separated to avoid mutual overwrite
* Adding `conf.aws_assume_role_arn` as plugin identifier to the credential cache key name
No issue reference for now.
=> feat(aws-lambda) separate aws credential cache in aws-lambda plugin by plugin identifier in config

CHANGELOG.md, kong-2.8.0-0.rockspec, kong/api/routes/kong.lua, kong/globalpatches.lua, kong/init.lua, kong/runloop/plugin_servers/init.lua, spec/01-unit/01-db/08-cache_warmup_spec.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/02-cmd/08-quit_spec.lua, spec/02-integration/03-db/09-query-semaphore_spec.lua, spec/02-integration/04-admin_api/20-timers_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/02-integration/09-hybrid_mode/05-ocsp_spec.lua, spec/02-integration/10-go_plugins/01-reports_spec.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua, spec/fixtures/mocks/lua-resty-dns/resty/dns/resolver.lua, spec/helpers.lua
Integrating https://github.com/Kong/lua-resty-timer-ng into Kong-CE.
* fix(plugin_servers) bypass timer library
* feat(AdminAPI) add `/timer` route
* chore(rockspec) add `resty.timerng` as dependency
* tests(unit/db/cache_warmup) fix
* tests(integration/cmd/quit) fix
* tests(integration/hybrid_mode/ocsp) fix
* tests(plugin/rate-limiting/access) fix
* tests(integration/db/query-semaphore) fix
* tests(integration/admin/timers) add tests for `http://kong_admin/timers`
* tests(integration/cmd/start_stop) fix
* tests(integration/proxy/router) fix
* docs(CHANGELOG) update
```json
{
"flamegraph": {
"running": "@./kong/runloop/balancer/targets.lua:248:Lua() 0\n@./kong/plugins/prometheus/handler.lua:15:Lua();@./kong/plugins/prometheus/exporter.lua:153:init_worker();@./kong/plugins/prometheus/promet …
```
=> feat(timerng) integrate the `lua-resty-timer-ng`

kong/init.lua, kong/runloop/plugin_servers/init.lua, kong/templates/nginx_kong.lua
When we exit or reload kong, plugin servers are quitting because they encounter errors in the socket(closing). This behavior is not proper. We close with SIGTERM when possible.
Hopefully, this can be a fix to #8531
=> fix(language) plugin server graceful shutdown

kong/db/declarative/marshaller.lua, spec/fixtures/dump_lmdb_key.lua
Replaces `cjson` based serializer with LuaJIT `string.buffer` serializer.
=> perf(declarative) use luajit serializer for lmdb

kong/vaults/env/init.lua
There is a potential risk that if `init` is invoked a lot, a *table overflow* error will occur. Can be verified very simply by: 
```
$ resty -e 'local ffi = require "ffi" while true do ffi.cdef[[void exit(int status);]] end'
ERROR: table overflow
(command line -e):1: in function 'inline_gen'
init_worker_by_lua:44: in function <init_worker_by_lua:43>
init_worker_by_lua:52: in function <init_worker_by_lua:50>
```
It's wrong to call `ffi.cdef()` repeatedly for the same things. Always call it on the top-level scope of module files. 
* fix luajit table overflow error when using `ffi.cdef`
=> fix(env) luajit table overflow error when using ffi.cdef

kong/db/dao/plugins.lua, kong/tools/utils.lua
When plugin priorities collide we cannot guarantee a deterministic result from the sorting function. There are a couple of plugins that traditionally have colliding priorities like their EE counterparts. To ensure determinism this commit adds a collision detection that falls back to a plugin name based sorting. Also the function moved to the `kong.tools.utils` module to test it in
isolation.
_note that this is a backwards port from ee_
=> fix(dao): plugin priority collision handling

spec/03-plugins/09-key-auth/01-api_spec.lua
The `key-auth` credential `id` is incorrectly set to `consumer.id`.
Fix #_[FTI-4091]_
[FTI-4091]: https://konghq.atlassian.net/browse/FTI-4091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests(key-auth) change json.consumer.id to json.id

CHANGELOG.md, kong/api/endpoints.lua, kong/api/init.lua, kong/db/schema/init.lua, kong/db/schema/metaschema.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/01-unit/01-db/01-schema/02-metaschema_spec.lua, spec/helpers.lua
Removes `legacy = true` support from `schemas` and from `schema fields`.
=> chore(db) remove schema legacy attributes

CHANGELOG.md, kong/runloop/certificate.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/18-upstream_tls_spec.lua
When updating client certificate, the certificate in core_cache should be invalidation, and the corresponding cache item for the new certificate should be used. Currently this logic doesn't work.
The logic for invalidating a certificate in core_cache doesn't work when a update event occurs.
change the logic how to get cache_key for certificate in core_cache and add a test
=> fix(dao) invalidate client certificate cache when updating

kong-2.8.0-0.rockspec
* [feat(stats) add field is_running to `timer:stats().timers.<timer_name>](https://github.com/Kong/lua-resty-timer-ng/commit/af977e31413f6387a30cc25ea327939d6a4c1f48)
* [fix(*) reduce log amount](https://github.com/Kong/lua-resty-timer-ng/commit/7e15ffa3783b9baa0ca77e4573b5e45b0c6a3176)
=> chore(deps) bump `lua-resty-timer-ng` from 0.1.0 to 0.2.0

CHANGELOG.md, kong/plugins/zipkin/handler.lua
include connect time in balancer span
=> fix(zipkin) include connect time in balancer span

CHANGELOG.md, kong/plugins/acme/handler.lua, kong/plugins/basic-auth/handler.lua, kong/plugins/hmac-auth/handler.lua, kong/plugins/jwt/handler.lua, kong/plugins/key-auth/handler.lua, kong/plugins/ldap-auth/handler.lua, kong/plugins/oauth2/handler.lua, kong/plugins/rate-limiting/handler.lua
Some static priorities of Kong's plugins collide or are bunched up. This commit will keep the relative priority in which these plugins are executed but loosens the priority numbers.
- A couple of plugins that received new priority values.
This is important for those who run custom plugins as it may affect the sequence your plugins are executed.
Note that this does not change the order of execution for plugins in a standard kong installation.
List of plugins and their old and new priority value:
- `acme` changed from 1007 to 1705
- `basic-auth` changed from 1001 to 1100
- `hmac-auth` changed from 1000 to 1030
- `jwt` changed from 1005 to 1450
- `key-auth` changed from 1003 to 1250
- `ldap-auth` changed from 1002 to 1200
- `oauth2` changed from 1004 to 1400
- `rate-limiting` changed from …
=> fix(plugins): change static priorities

.github/labeler.yml
Fix autodoc path, add `autodoc` label
=> chore(labler) fix autodoc path

kong/pdk/vault.lua
Originally process secrets was meant only to be used on CLI where the cache may not be available (e.g. when parsing `kong.conf`), but we decided later that process secrets could also be used on runtime for config secrets.
This commit implements similar caching that is currently enabled on config cache function to process secrets function.
This also contains two other commits that are just some cleanups and something  that I need for rotation implementation.
=> feat(pdk) add caching to process secrets function 

scripts/autodoc
Fix autodoc output, it will throw error code 1 when autodoc generation failed.
related: https://github.com/Kong/kong/pull/8984
=> tests(autodoc) return exit code 1 when autodoc generation failed

CHANGELOG.md, kong/api/routes/config.lua, kong/cmd/config.lua, kong/db/declarative/init.lua
For a while we accepted .lua declarative configurations via command-line only, but not on the admin API.
BREAKING CHANGE: Dropped support for loading declarative configuration in .lua format using the command-line tool
* ...
=> feat(cmd)! remove support for declarative config in Lua format

kong/plugins/rate-limiting/policies/cluster.lua, kong/plugins/response-ratelimiting/policies/cluster.lua, kong/tools/timestamp.lua
This PR aims to fix a disordered behaviour caused by `pairs` which will eventually cause a Postgres DEADLOCK problem.
Currently, SQL transaction that does an increase on rate limit metrics over all spans of the timestamp table is concatenated over a `pairs` code block. The code will iterate through the timestamp table(which is defined as below):
https://github.com/Kong/kong/blob/a02542d6dfb96073c4ef6ab5f86b350b756ae2fa/kong/tools/timestamp.lua#L45-L68
The `pairs` function **does not guarantee the order of the iteration process**, thus the generated SQL might be **disordered**.
In a classic clustering mode(not the DP/CP mode, just multiple Kong instances sharing one database), the SQL may look like this(logs get truncated but as you can see, the `day` insert SQL is in front of the `second` …
=> fix(plugin) pairs disorder when iterate over timestamp table

autodoc/admin-api/data/admin-api.lua, kong/api/routes/kong.lua, kong/globalpatches.lua, kong/init.lua, kong/runloop/handler.lua, spec/01-unit/01-db/08-cache_warmup_spec.lua, spec/01-unit/16-runloop_handler_spec.lua, spec/02-integration/03-db/09-query-semaphore_spec.lua, spec/02-integration/04-admin_api/20-timers_spec.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua, spec/helpers.lua
* style(runloop) use every timer instead of at timer to rebuild router and plugin iterator
* feat(AdminAPI) add the worker info to the response of `/timers`
* tests(helpers) extend function `wait_timer`
=> fix(admin) add the worker info to the response of `/timers`

spec/helpers/perf.lua, spec/helpers/perf/drivers/docker.lua, spec/helpers/perf/drivers/local.lua, spec/helpers/perf/drivers/terraform.lua
This bug didn't affect previous Github action runs, where we test two git based versions.
=> perf(*) tests(perf) correctly preserve kong source code when using daily image

CHANGELOG.md
add `lua-resty-events` in changelog.
* changelog: Additions.Core
=> docs(changelog) add lua-resty-events in changelog

kong/db/schema/init.lua
Fix issue internally reported as FT-3076 where schema process auto-fields function could lead to an attempt to index local 'refs' (a nil value) error.
=> fix(schema) process auto-fields attempt to index local 'refs' (a nil value)

CHANGELOG.md, kong-2.8.0-0.rockspec
[0.8.10] - 2022-06-28
Commit https://github.com/fffonion/lua-resty-openssl/commit/d54b5d61bc14813121f4a6bda2e1d7eab215094a
* __x509.init__ add `get_signature_digest_name` to return short name of digest algorithm.
* __x509.csr__ add `get_signature_digest_name` to return short name of digest algorithm.
* __x509.crl__ add `get_signature_digest_name` to return short name of digest algorithm.
* __objects__ add `find_sigid_algs` to transforms signature `nid` to digest `nid`.
* Fix _[FTI-3334](https://konghq.atlassian.net/browse/FTI-3334)_
=> chore(deps) bump resty.openssl from 0.8.8 to 0.8.10

CHANGELOG.md, kong-2.8.1-0.rockspec, kong/meta.lua
Steps required after the release of 2.8.1:
- Bumping Rockspec and Meta versions
- Changing rockspec protocol from git to http (see sister PR #8672 which modifies the `release/2.8.x` rockspec)
- Manual update of the changelog to include 2.8.1 changes.
=> chore(release) 2.8.1 post-release

kong/runloop/handler.lua
It does not make sense to use cache with dbless where the data is already in memory, especially because the route rebuild process can use a lookup table.
It also consumes a lot of memory to have service in:
1. lmdb (in memory)
2. shared dictionary (in memory)
3. worker local memory
So this commit removes the unneccessary use of cache here.
Reading shdict also causes locking.
=> perf(handler) do not use cache with dbless when looking up service for route

kong/init.lua
We have removed deprecated `nginx_upstream_keepalive` setting in: #8794. At this point Kong is expected to be built with `enable_keepalive` patch. This commit removes unnecessary warning and check.
=> chore(balancer) remove warning about keep-alive patch, which is required

CHANGELOG.md, kong/runloop/handler.lua
`ngx.ctx.balancer_address` was removed, please use `ngx.ctx.balancer_data` instead.
=> chore(balancer) remove deprecated ngx.ctx.balancer_address

Jenkinsfile
Add a stable tag for easily pull latest tags from scripts. It seems we don't build multi-arch images for ubuntu20.04, so the original image has the `amd64` prefix compared to alpine one.
* add a stable tag for easily pull latest tags from scripts.
=> chore(ci) add constant label for "latest" nightly build image

kong/globalpatches.lua
Kong Enterprise invoked `ngx.sleep` in `init` phase in some scenarios(e.g. keyring failed). But the current patch for `ngx.sleep` doesn't support fallback to blocking sleep in `init` phase.
* fix(globalpatches) fallback to alternative_sleep at init phase
NO issue related
=> fix(globalpatches) fallback to alternative_sleep at init phase

kong/clustering/init.lua, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua
This should be considered a non-user configuration, and we also should avoid using it if possible.
And this feature is intentionally not documented.
Fix FT-3077
=> feat(clustering) switch to use old protocol

kong/plugins/acme/handler.lua, spec/03-plugins/29-acme/03-access_spec.lua
Update `domains_matcher` only when ACME's config is updated.
=> perf(plugins) cache domains_matcher for ACME

kong/plugins/aws-lambda/aws-serializer.lua, spec/03-plugins/27-aws-lambda/05-aws-serializer_spec.lua
when `aws-lambda` plugin `awsgateway_compatible` configuration set to `true` and  `request-transformer` replace uri configuration enabled, `kong` use request_uri to find serializer path args, this action doesn't respect  `request-transformer` configuration parameters
change aws-lambda plugin serializer path arg from request_uri to upstream_uri
Fix #8608
=> fix(aws-lambda) change path from request_uri to upstream_uri

kong/runloop/handler.lua
It's control_:airplane:, not control_:window:
=> fix(runloop) fix typo in configuration role check

kong/init.lua, kong/pdk/response.lua, spec/02-integration/05-proxy/28-stream_plugins_triggering_spec.lua, spec/fixtures/custom_plugins/kong/plugins/short-circuit/handler.lua
Implements delayed responses with stream module that is used to short-circuit streams.
=> feat(proxy) implement delayed response with stream module

CHANGELOG.md, kong/db/migrations/core/016_280_to_300.lua, kong/router.lua, spec/01-unit/08-router_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua
It's not a very reliable and sound way to support percent-encoding in regex. We choose to tell users that we have a normalized (standard) form to match with so there's no ambiguity.
https://github.com/Kong/kong/pull/8140#issuecomment-1168371378
fix CT-344
=> fix(core) stop percent decoding regex path

CHANGELOG.md, kong/db/migrations/core/016_280_to_300.lua, kong/db/schema/typedefs.lua, kong/router.lua, spec/01-unit/01-db/01-schema/05-services_spec.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua, spec/01-unit/01-db/01-schema/09-upstreams_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua, spec/01-unit/08-router_spec.lua, spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua, spec/02-integration/04-admin_api/10-services_routes_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/03-plugins/36-request-transformer/02-access_spec.lua, spec/fixtures/balancer_utils.lua
Another solution for #9022.
fix CT-344
We need to remember to add migration, and also "back migration" for EE.
**PLEASE MERGE AFTER: #9024**
=> feat(core) explict flag for regex route.path

CHANGELOG.md, kong/db/strategies/postgres/connector.lua, kong/pdk/vault.lua, spec/01-unit/23-vaults_spec.lua
This PR contains three commits on top of #8966 (which is now merged):
1. feat(pdk) add kong.vault.try helper function for secret rotation: Adds experimental (for now) kong.vault.try function that can be used to implement automatic secret rotation.
2. feat(db) add automatic secret rotation of postgres username and password: Adds automatic secret rotation of postgres username and password.
3. feat(pdk) add rate-limiting to kong.vault.try function
=> feat(pdk/db) kong.vault.try function and automatic secret rotation of postgres credentials

kong/clustering/config_helper.lua, spec/01-unit/19-hybrid/02-clustering_spec.lua
Improve calculate hash performance by utilizing string buffer and tablepool.
=> perf(clustering) improve calculate hash performance by utilizing string buffer and tablepool

kong/plugins/opentelemetry/schema.lua
Make sure opentelemetry plugin is the global scope.
FT-3096
=> fix(otel) allow only global scope

kong/clustering/control_plane.lua, kong/clustering/init.lua, kong/clustering/wrpc_control_plane.lua
This reduces double event handling and event publishing on clustering.
On further PRs we can reduce double exporting, json decoding, calculate hashing etc. that are common between wrpc control plane and json control plane, but here I just fixed the double event handling.
=> fix(clustering) do not register events multiple times

spec/02-integration/03-db/11-postgres-ro_spec.lua
This test is flaky because we may send the request before the router takes effect.
We need to wait not only for log emitting but also for the router update to take effect.
=> fix(tests) more requests to wait for router update

kong/plugins/acme/handler.lua
Currently the FTI-3300 has not landed and we're using the previous implementation, monitoring the use of it using debug logs. But we're not able to have the granularity of failed domains registration. With this log we would be able to have more insights.
Note: suggesting changing `whitelist` to `allowlist` too.
* Add host in the debug log for non allowed domain
Following https://github.com/Kong/kong/pull/9047
=> feat(acme): debug log details

kong/plugins/prometheus/exporter.lua
* fix(prometheus) data_plane_version_compatible metric of inexistent data plan had been held in shared dict
FTI-4157
=> fix(prometheus) data_plane_version_compatible metric of inexistent data plan had been hold in shared dict

kong/tools/wrpc/init.lua, kong/tools/wrpc/threads.lua
We miss handling of message sending error (over WebSocket), and the future times out when an error happens.
This problem is found when I tried to send a payload larger than `payload_limit`.
=> fix(wrpc) error handling when sending message

kong/clustering/wrpc_data_plane.lua, kong/tools/wrpc/init.lua
It may leak when an error happens, and we recreate the wRPC connection. The previous one is not closed (instead, the WebSocket connection is closed. Probably a typo.)
=> fix(clustering) potential leaking for DP wRPC

t/01-pdk/02-log/01-sanity.t, t/Util.pm
This is mainly to fix some EE test issues where there is a race condition when JIT and NGINX are writing in the same error log file. The refactor is simply to allow more flexibility and enable the JIT logs only when needed.
Example of failure: https://github.com/Kong/kong-ee/runs/7387011751?check_suite_focus=true#step:10:52
=> tests(*) refactor t/Util.pm to provide more config flexibility

kong/cmd/migrations.lua
It says `[Y/n]`, but doesn't take Y as the default choice.
=> fix(cmd) confusing prompt

scripts/autodoc
the autodoc CI test is passing when it should not be ( https://github.com/Kong/kong/runs/6726254426?check_suite_focus=true#step:7:15 ).
This PR makes it fail "correctly" aka if the autodoc fails CI will fail as intended
I'll leave the exercise to other to make the documentation fixes required to pass this PR.
=> fix(ci): autodoc was passing when it should not have been

kong/plugins/aws-lambda/aws-serializer.lua, spec/03-plugins/27-aws-lambda/06-request-util_spec.lua
fix plugin `aws-lambda` 500 error in serviceless route and config enable awsgateway_compatible
* fix plugin `aws-lambda` 500 in serviceless route and config enable awsgateway_compatible
* add serviceless `db.route` spec to cover this case
=> fix(aws-lambda) fix 500 error in serviceless route

kong/db/schema/entities/routes.lua, kong/db/schema/typedefs.lua, spec/01-unit/01-db/01-schema/05-services_spec.lua, spec/01-unit/01-db/01-schema/09-upstreams_spec.lua, spec/02-integration/04-admin_api/07-upstreams_routes_spec.lua, spec/02-integration/04-admin_api/10-services_routes_spec.lua
This scheme change was not done right and causes a lot of tests to fail.
And, `typedef.path` is also used in places like service.
=> fix(*) router now has different path scheme

kong.conf.default, kong/conf_loader/init.lua, spec/02-integration/14-tracing/01-instrumentations_spec.lua
Add `request` type to tracing instrumentation.
This allows only to create the top-level span.
=> fix(tracing) add `request` type to only create request-level span

kong/router/atc_compat.lua, kong/templates/kong_defaults.lua
This code is copied from the traditional router, we just keep the same logic/behavior as old router. 
Maybe we will change it in the future.
=> chore(atc_router) add LRU cache support just like the traditional router

kong/router/atc_compat.lua, kong/templates/kong_defaults.lua, spec/fixtures/balancer_utils.lua
* enable `traditional_compatible` in kong_defaults.lua
* replace regex `?<` to `?P<` to work with Rust regex
* sort `route.paths`, move regex uri to the front
* use `table.new` to pre-allocate table object
=> fix(templates) use `atc_compatiable` as default for `router_flavor`

kong/db/declarative/init.lua, kong/db/schema/others/declarative_config.lua, spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua
* fix(vaults) load vault subschema in `off` strategy
=> fix(vaults) load vault subschema in `off` strategy

kong/plugins/prometheus/exporter.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua
This emits the missing initialized stat `node_info` which outputs the node_id and the current kong gateway version for prometheus to scrape using the info pattern.
Adds this extra metric in the `/metrics` Prometheus endpoint
```
kong_node_info{node_id="c0ba8250-7a6e-44dc-b146-b9ca9a22e47b",version="3.0.0"} 1
```
=> fix(promtheus-plugin): emit missing node_info guage stat

kong/clustering/wrpc_control_plane.lua, kong/clustering/wrpc_data_plane.lua, kong/include/wrpc/wrpc.proto, kong/tools/wrpc/future.lua, kong/tools/wrpc/init.lua, kong/tools/wrpc/message.lua, kong/tools/wrpc/proto.lua, kong/tools/wrpc/threads.lua, spec/01-unit/19-hybrid/05-wrpc/future_spec.lua, spec/01-unit/19-hybrid/05-wrpc/proto_spec.lua, spec/01-unit/19-hybrid/05-wrpc/queue_spec.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/07-wrpc_spec.lua, spec/03-plugins/37-opentelemetry/01-otlp_spec.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua, spec/fixtures/mocks/lua-resty-websocket/resty/websocket/peer.lua, spec/fixtures/wrpc/test.proto, spec/helpers.lua
1. CP crashes if DP report meta data with empty plugin list
2. the client is inserted to the list before it reported "basic info", therefore it's possible for an incompatible client to receive config pushs.
3. If no error happens, and no ping is sent yet, update_sync_status is not called and thus we cannot query that DP
4. CP does not return result of compatibility check ReportMetadata
5. Unnessary argument when dp creates connection(refactory leftover)
FT-3030
=> fix(clustering) wRPC bugs fix

CHANGELOG.md, kong-3.0.0-0.rockspec
Bump lua-resty-healthcheck to latest 1.6.x release. This is needed to use any lua-resty-events 0.1.x release.
* [lua-resty-healthcheck 1.6.1](https://github.com/Kong/lua-resty-healthcheck/tree/1.6.1#161-25-jul-2022)
=> chore(rockspec) bump lua-resty-healthcheck to 1.6.1

CHANGELOG.md, kong-3.0.0-0.rockspec
- **client:** skip checking eab_handler if eab_kid and eab_hmac_key is set ([#71](https://github.com/fffonion/lua-resty-acme/issues/71)) [6004738](https://github.com/fffonion/lua-resty-acme/commit/6004738222718c678d612afb61a0a428ee25fdb4)
- **storage:** add Vault namespace ([#63](https://github.com/fffonion/lua-resty-acme/issues/63)) [e241933](https://github.com/fffonion/lua-resty-acme/commit/e24193396af96900f3436dc55c5b0be98bc2ccca)
=> chore(deps) bump resty.acme from 0.8.0 to 0.8.1

CHANGELOG.md, kong-3.0.0-0.rockspec
- fix: `warn` unquoted argument
[#439](https://github.com/lunarmodules/Penlight/pull/439)
- fix: `xml.parse` returned nonsense when given a file name
[#431](https://github.com/lunarmodules/Penlight/pull/431)
- feat: `app.require_here` now follows symlink'd main modules to their directory
[#423](https://github.com/lunarmodules/Penlight/pull/423)
- fix: `pretty.write` invalid order function for sorting
[#430](https://github.com/lunarmodules/Penlight/pull/430)
- fix: `compat.warn` raised write guard warning in OpenResty
[#414](https://github.com/lunarmodules/Penlight/pull/414)
- feat: `utils.enum` now accepts hash tables, to enable better error handling
[#413](https://github.com/lunarmodules/Penlight/pull/413)
- feat: `utils.kpairs` new iterator over all non-integer keys …
=> chore(deps) bump penlight from 1.12.0 to 1.13.1

kong/db/schema/metaschema.lua, kong/db/strategies/cassandra/init.lua, kong/db/strategies/postgres/init.lua, spec/01-unit/01-db/01-schema/02-metaschema_spec.lua, spec/02-integration/03-db/07-tags_spec.lua
Allows to define table_name field in a schema. Before the table name was deduced from the entity name.
* Add `table_name` schema field
=> feat(db): disconnect table_name from entity name

CHANGELOG.md, kong/conf_loader/init.lua
We added the feature and warning on 8 Sep 2021 (see #7819), and we have not heard reports on it (perhaps because it was not turned on by default). Thus I removed the warning of the feature being experimental, and now it is considered a fully supported one (though I didn't enable it yet by default).
=> chore(conf) remove warning on experimental `AAAA` in `dns_order` configuration

kong/db/migrations/core/016_280_to_300.lua, kong/db/schema/entities/vaults.lua, spec/05-migration/db/migrations/core/016_280_to_300_spec.lua
Use "sm_vaults" instead of "vaults" for the SM vaults table in 3.0.
Rework the migration and its test accordingly.  This change enables
blue/green upgrades.
To support upgrades of installations running 2.8.1.3 as well as
earlier 2.8.x versions, the migration test supports both the
`/vaults-beta` and `/vaults` prefix to retrieve SM vaults during
testing.
Fix FT-3182
=> chore(db) Change vaults table name, rework 2.8->3.0 migration + test

kong/router/atc.lua
use `ipairs` to init schema, simplify the code.
=> refactor(atc-router) use ipairs to init schema

kong/cmd/vault.lua
- Adds support for `-c` and `--conf` options to `kong vault` commands.
- Adds support for `-p` and `--prefix` options to `kong vault` commands.
=> fix(cli) add support for `-c`/`--conf` and `-p`/`--prefix` options to `kong vault` commands

CHANGELOG.md, kong.conf.default, kong/conf_loader/listeners.lua, spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua
- feat(conf) add ipv6only=on|off to listen options
- feat(conf) add so_keepalive=on|off|[keepidle]:[keepintvl]:[keepcnt] to listen options
Fix #9169
=> feat(conf) add ipv6only and so_keepalive options to listen options

kong/api/endpoints.lua, kong/db/dao/init.lua, kong/db/schema/typedefs.lua, spec/02-integration/03-db/07-tags_spec.lua, spec/02-integration/04-admin_api/14-tags_spec.lua
This change updates Kong so that space characters can be used in tag
names.  The tags related tests have been updated to use tag names with
spaces.
=> feat(core) allow spaces to be used in tag names FT-2680

kong/router/atc_compat.lua
Reuse ffi.new uint64 to avoid overhead
=> refactor(atc-router) reuse ffi_new uint64

kong/router/init.lua
`atc_compat.new` should use `cache` and `cache_neg`.
See #9096
=> fix(atc-router) router is not inited properly

kong/include/kong/services/negotiation/v1/negotiation.proto
Should we also change the id of the service? This service is more fundamental than config.
=> fix(clustering) fix rpc id of negotiation

kong/db/schema/init.lua, spec/02-integration/13-vaults/01-vault_spec.lua
If you call `schema:process_auto_fields` multiple times with `select` context, it turned out that it removes the existing `$refs` and then you would loose the references. This commnit fixes it so that `$refs` are kept on the fields that are `referenceable`.
=> fix(db) keep the $refs for the existing fields when process auto fields is called

kong/router/atc_compat.lua
use `table.new` and reuse table object when we calculate headers cache key
=> refactor(router/atc) optimize get_headers_key

kong/db/declarative/init.lua, kong/db/strategies/off/init.lua, spec/01-unit/01-db/10-declarative_spec.lua, spec/02-integration/04-admin_api/15-off_spec.lua
LMDB has a (compile-time) max key length limitation of 511. It's easy to exceed this limit when generating unique field indexes in dbless, since they use the [potentially unbounded] field value as part of the key.
With this update, we use a sha1 checksum of the field value instead of just the raw value itself in order to limit the key length.
There is definitely a non-zero performance cost to this, but I don't see any way around that. And we can't easily get much cheaper than sha1.
=> fix(db) use a checksum to limit unique key length

kong/runloop/plugin_servers/init.lua
- fix(runloop) typo fix for kong.log.err
=> fix(runloop) typo fix for kong.log.err

kong/router/atc.lua, kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
* Strip default port in http.host, then pass it to atc-router, 
so atc-router can match host with default port.
* Add a `net.port` and split host:port
* Enable some test cases.
=> fix(router) atc-router ignores default port

kong/db/strategies/postgres/init.lua
When a field uses the foreign key as the primary key, it uses the name of that item instead of its field name for page_next, thus failing to find the value of the field.
fix FTI-4253
=> fix(db) failed to query 2nd page for fields use foreign keys as the primary key

kong/runloop/handler.lua, spec/03-plugins/33-serverless-functions/02-access_spec.lua
It was reported by @joshkping in #9246 that your handler may runtime crash in certain cases. This started to happen after this commit was merged: https://github.com/Kong/kong/commit/44d24a216cfa17926d0c0b2781587d1200bf35e7
It looks like this affects a lot of versions:
- 2.8.1
- 2.8.0
- 2.7.2
- 2.7.1
- 2.7.0
- 2.6.1
- 2.6.0
Fix #9246
=> fix(handler) reverted logic to old one in var.upstream_uri concatenation logic

CHANGELOG.md, kong.conf.default, kong/cmd/utils/prefix_handler.lua, spec/01-unit/04-prefix_handler_spec.lua
Adds lower bound of 1024 to:
- `nginx_events_worker_connections=auto`
- `nginx_main_worker_rlimit_nofile=auto`
=> chore(conf) lower bound to worker_connections and worker_rlimit_nofile

kong/plugins/prometheus/grafana/kong-official.json
- update metric and label names for the Prometheus-plugin grafana dashboard.
- updated queries
=> fix(prometheus-grafana-dashboard): Update the dashboard to use 3.0.0 metric names

kong/db/dao/init.lua, spec/01-unit/01-db/04-dao_spec.lua, spec/03-plugins/25-oauth2/04-invalidations_spec.lua
In a scenario where `consumer` entities were deleted, the
`oauth2_tokens` entities didn't have their caches invalidated. This is
because the `find_cascade_delete_entities` function was only finding
entities up to a maximum of two levels. So in this case where
`consumer` is referenced by `oauth2_credentials` and
`oauth2_credentials` is referenced by `oauth2_tokens` (consumer ->
oauth2_credentials -> oauth2_tokens), only the `consumer` and
`oauth2_credentials` had their cache invalidated, the `oauth2_tokens`
caches had their cache still valid after a /consumers DELETE operation. The
`find_cascade_delete_entities` function of the DAO module needs to be
recursive because of this issue. So this PR is doing that, plus it's
adding unit tests along with integration tests for the `oauth2` plugin. …
=> fix(dao) add recursion over entities that need to be cascade-deleted

kong/global.lua
increase events queue len to 1024*50, it may reduce the probability of queue overflow.
See FT-3214.
=> chore(*) increase events queue len to 1024*50

kong/tracing/propagation.lua, spec/01-unit/26-tracing/02-propagation_spec.lua
When `tracestate` header is multi valued ( it is allowed by the spec ) zipkin plugin was failing with error ```bad argument #1 to 'match' (string expected, got table)```
* [zipkin] handling multi value tracestate header correctly
=> fix(tracing) handling tracestate header correctly

kong/tracing/instrumentation.lua
Balancer span creation was using the incorrect param name for span kind.
* [tracing] fixed balancer span kind
=> fix(tracing) balancer span_kind fix

kong/clustering/init.lua, kong/clustering/wrpc_control_plane.lua, kong/init.lua, kong/tools/wrpc/threads.lua, spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua
DP errors in the log when CP exits because CP does not close the connection properly:
```
2022/08/11 11:33:32 [notice] 18802#0: *11 [lua] threads.lua:80: step(): [wRPC] WebSocket frame: failed to receive the first 2 bytes: closed, context: ngx.timer
2022/08/11 11:33:32 [error] 18802#0: *7 [lua] init.lua:252: error while receiving frame from peer: failed to receive the first 2 bytes: closed, context: ngx.timer
2022/08/11 11:33:32 [error] 18802#0: *5 [lua] init.lua:252: error while receiving frame from peer: failed to receive the first 2 by
```
Fix FT-3204
=> fix(clustering) DP errors when CP exits

.github/workflows/upgrade-tests.yml
Previously, upgrades were tested with PostgreSQL twice due to copy&paste error.
=> chore(test) Actually test upgrade path with cassandra

CHANGELOG.md, kong-3.0.0-0.rockspec, kong/cache/marshall.lua
lua-resty-mlcache 2.6.0 add support for new api `string.buffer` in OpenResty 1.21.4.1
=> deps(*) bump lua-resty-mlcache to 2.6.0

kong-3.0.0-0.rockspec
@jeremyjpj0916 reported on #9282 about a problem in our `2.8.1` `.rock` file in luarocks:
https://luarocks.org/manifests/kong/kong-2.8.1-0.src.rock
That has now been fixed. I used:
```
source = {
url = "git+https://github.com/Kong/kong.git",
tag = "2.8.1"
}
```
To upload and generate a new `.rock` file.
Here I will fix the url in our `master` branch to also contain `git+https` and
the `.git` at the end. This should be right according to:
https://github.com/luarocks/luarocks/wiki/Rockspec-format#build-rules
And Github proposed URLs when cloning:
https://github.com/Kong/kong.git
=> chore(rockspec) use git+https as a luarocks url

kong/plugins/http-log/migrations/001_280_to_300.lua
In Kong <=2.8, the `http-log` plugin supports providing multiple header values in the array, and will automatically concatenate them (delimited by `, `) when sent over the wire to the defined HTTP log endpoint.
Prior to these code changes, if someone has `{"some-header": ["test1", "test2"]}` set as the headers on their plugin config, when migrating from 2.8 to 3.0, it’d re-write the headers config to `{"some-header": "test1"}`. These code changes allow to retain the same behavior as prior versions.
Given the example headers config above, the headers sent by the gateway in a manual integration test are below:
```
Content-Length: 1556
User-Agent: lua-resty-http/0.16.1 (Lua) ngx_lua/10020
Content-Type: application/json
some-header: test1, test2
```
The DB migration was manually tested from …
=> fix(http-log) properly migrate headers when multiple values are provided

kong/pdk/log.lua, spec/01-unit/10-log_serializer_spec.lua
Ensure the log parameter `upstream_uri` contains any query args that are sent with the upstream request. 
When there is a cache hit in the `proxy-cache` plugin, the flow is interrupted without executing [access/after() in the runloop](https://github.com/Kong/kong/blob/442df3e2860b85498d8f9ba41c22f6c7d111a2ee/kong/runloop/handler.lua#L1444-L1448) so the value of `upstream_uri` in the logs becomes inconsistent when the `proxy-cache` plugin is enabled.
=> fix(log-serializer) ensure upstream_uri includes query args

kong/db/dao/init.lua, kong/db/strategies/cassandra/init.lua, spec/01-unit/01-db/04-dao_spec.lua
> This pull request cherry-picks https://github.com/Kong/kong-ee/pull/3622
This PR fixes the issue that DAO delete hooks were triggered when no rows were affected.
The issue currently affects Kong Enterprise and Kong Manager. When concurrent delete requests are initiated on the same entity, the counter in the workspace meta will potentially be decremented multiple times and become a negative number.
FT-3072
=> fix(db) skip delete hooks if no rows were affected

kong/vaults/env/init.lua
Follows the same logic that we now have on plugins, e.g. see:
https://github.com/Kong/kong/blob/master/kong/plugins/acl/handler.lua#L44
=> chore(vaults) set env vault version to kong version

spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/fixtures/custom_nginx.template
This updates the `custom_nginx.template` (commonly used in our integration tests) with the `legacy_hybrid_protocol` gate, bringing it into parity with the production template:
https://github.com/Kong/kong/blob/9af18e1b02c1740e5a541198cd48af719cb5cee8/kong/templates/nginx_kong.lua#L442-L448
See #9145
=> tests(clustering) add missing wrpc handler gate

CHANGELOG.md, kong/cmd/start.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua
This change set makes Kong more likely to recover from an unclean shutdown.
It also includes a bugfix for `kong start` wherein the `.kong_env` file could be rewritten (among other things) if Kong is already running.
When Nginx suffers an unclean shutdown (HW issue, OS issue, `SIGKILL`, etc), it may fail to clean up any listening unix sockets from the filesystem. The presence of these will cause Kong to fail to start back up again:
> [emerg] 2127#0: bind() to unix:/usr/local/kong/worker_events.sock failed (98: Address in use)
Kong will search for any existing unix sockets within the prefix directory and remove them before attempting to start nginx. If Kong/nginx is already running, no action is taken.
The search for dangling sockets is performed only in the top-level prefix directory (no …
=> feat(cmd) clean dangling unix sockets on startup

kong/router/atc_compat.lua, kong/router/init.lua, kong/router/traditional.lua, kong/router/utils.lua, kong/runloop/handler.lua
Implements dynamic router LRU cache size based on number of routes.
- By default we initialize positive router LRU cache of 5000 items.
- If there is more than 5000 routes we reinitialize cache to closest 5000, e.g. if there is 5001 routes, we re-initialize cache to 10000 items and keep the size 10000 until number of routes reaches either over 10000 or less than 5001.
- The maximum size of cache is limited to 100000 items.
This should improve our routing performance with high number of routes when routes are found in cache. This will increase memory usage though, but it is expected for users to have beefier systems when number of routes is high (again we limit this to 100000). If previous LRU of 5000 items took around 5 MB, the dynamic is expected to take 100 MB at most (per worker).
=> perf(router) dynamic router lru cache size based on number of routes

kong/clustering/init.lua, kong/clustering/wrpc_control_plane.lua, kong/init.lua, kong/tools/wrpc/threads.lua, spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua
This reverts commit a51d298d920f8e662f923524128dc69599b62224.
For errors were thrown when CP exits.
We need to rework this later then.
=> Revert "fix(clustering) DP errors when CP exits"

autodoc/admin-api/data/admin-api.lua, kong/db/schema/entities/routes.lua, spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua, spec/01-unit/01-db/01-schema/11-declarative_config/04-on-the-fly-migration_spec.lua, spec/02-integration/03-db/02-db_core_entities_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua
This PR ~~denies~~ users from setting `path_handling=v1` when the Kong gateway is running with `router_flavor=traditional_compatible`, as the `path_handling` feature is stepping into deprecation and path_handling v0 will be the default behaviour when composing upstream_uri.
Discussed with the team and decide to only print deprecation log in the current version.
* Add custom entity check function to deny setting `path_handling=v1` when `router_flavor` is `traditional_compatible`
=> chore(router) deprecate setting path handling v1 when router_flavor is traditional_compatible

kong/api/routes/kong.lua
This doesn't actually change anything about this field in Kong OSS,
but in EE the `_VERSION` field includes `-enterprise-edition`. We don't
want to include the edition information as part of our kong version
information on the '/' endpoint because that is machine parseable.
=> chore(api) Unify the version we return on the '/' endpoint

Jenkinsfile
use alpine for the unofficial `kong/kong:latest`. In the future we should use debian-slim but need arm64 builds for debian first
=> chore(ci): set alpine as the docker hub latest floating tag

autodoc/admin-api/data/admin-api.lua
According to this PR commit [fix(api) upsert of targets now require the PUT HTTP method](https://github.com/Kong/kong/pull/8596)
Change set targets healthy/unhealthy endpoints the POST HTTP method to the PUT HTTP method
FT-2544
=> fix(auto-doc) change targets healthy/unhealthy endpoints http method `POST` to `PUT`

Makefile
- [**breaking**] Follow semver guidelines, next release will be v1.x.y
- Overhaul docker container to run on Lua 5.4
- Store cached luacheck values per-version in case of changes
- Set_default_std for ldoc
- Add builtin std option for Ldoc globals
- Add builtin std option for the Playdate SDK
- Refactor rockspec to dodge luarocks 3.1.3 bug
- Fix caching the ffi.typeof function on luajit — @Tieske
- Fix 'metatype' as a patched method on luajit — @Tieske
- Report pending without function argument — @Tieske
- Cache all outputter functions, use io.write not print — @Tieske
- Exit when CLI specified helper fails — @Tieske
- Restore globals set to nil in insulate block — @Henkoglobin
- Change rockspec URL to git+https — @Frenzie
- Fix error in gtest and utfhandlers if color was set — @Tieske
- …
=> chore(deps) bump dev dependency of luacheck and busted

kong/router/atc_compat.lua
Optimize `traditional_compatible` and `expressions` router to not read headers in case there are no routes with header matching rules.
=> perf(router) if header matching is not used, don't read headers

spec/02-integration/04-admin_api/08-targets_routes_spec.lua
Fix these two tests:
* flips the target status from UNHEALTHY to HEALTHY
* flips the target status from HEALTHY to UNHEALTHY
https://github.com/Kong/kong/blob/5946d86d9ad268fe17c1ffd862715de87e198c96/.ci/run_tests.sh#L38-L45
I have ran an [action](https://github.com/Kong/kong/actions/runs/2934175655) to repeat these tests 200 times, and it is green, I think we can merge this PR.
_FT-3284_
=> tests(intergration/admin_api/targets_routes) fix flaky tests

kong/db/dao/targets.lua, kong/runloop/balancer/healthcheckers.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua
Target with weight 0 will not be added into the healthcheck list,
and the default Health status of targets is HEALTHY. For such
targets, Admin API call /upstreams/<upstream>/health reports Health
status as HEALTHY while the healthcheck is not performed for them.
The appropriate status is HEALTHCHECK_OFF.
Fix for Admin API call to provide response with "HEALTHCHECK_OFF"
for targets with weight 0.
=> fix(dao) response "HEALTHCHECK_OFF" for targets with weight 0

CHANGELOG.md, kong/plugins/rate-limiting/schema.lua, kong/plugins/response-ratelimiting/schema.lua, spec/03-plugins/23-rate-limiting/03-api_spec.lua, spec/03-plugins/24-response-rate-limiting/03-api_spec.lua
This will only affect new plugin configuration, so no cp/dp compat fix is required. docs PR to be done when merged.
=> RateLimiting/ResponseRateLimiting: change the default policy to local (FT-3295)

spec/03-plugins/06-statsd/01-log_spec.lua
The `shdict_usage` metric will be returned when Kong has just started, and also every minute, so we should test it when Kong has just started.
_FT-3301_
=> tests(plugins/statsd/log) fix some flaky tests about `shdict_usage` metric

kong/cmd/utils/prefix_handler.lua, kong/conf_loader/init.lua, spec/01-unit/03-conf_loader_spec.lua
* move creation of certificate and key files in a separate block
* write certs and keys files for the remaining values: cluster_* and client_*
* update configuration with generated path for cluster_* and client_*
=> feat(conf) add support for remaining variables

kong/router/atc_compat.lua, kong/tools/utils.lua, spec/01-unit/08-router_spec.lua
The assignment of `old_route` is wrong, it should happen before `old_routes[route_id] = route`.
And in the previous code, the rebuild is actually a complete build, not an incremental build.
=> fix(router) old_route has wrong assignment order

.github/workflows/build_and_test.yml
This change is desired because it eliminates the need for builds/unit tests to pass on PRs that exclusively include only markdown file changes.
Hopefully, this will reduce the time it takes for markdown-only PRs to get approved and merged.
This is a sister PR to https://github.com/Kong/kong-ee/pull/3692
* [Implement changes to skip builds/unit tests for markdown file PRs]
=> chore(gha): don't unit test .md file changes

spec/01-unit/08-router_spec.lua
Adds missing tests to perf pr that was recently merged, see: #9327.
This tests that `ngx.reg.get_headers` is called only when there are routes with header matching rules.
=> tests(router) add test for header optimization pr #9327

spec/02-integration/09-hybrid_mode/01-sync_spec.lua
It could fail if run separately without previous tests initializing the variable.
=> fix(test) hybrid sync test

kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
Adjust some test cases to fit flavor `traditional_compatible` and `expressions`.
Changes:
* remove unnecessary expression/priority in test
* due to `YIELD_ITERATIONS` is `1000` now, change test loop to `2000`
* add more test cases
=> tests(router) add more test cases for incremental build

kong/plugins/acme/client.lua, kong/plugins/acme/handler.lua
When having several certs, when it fails to update there is no way to know which one is failing.
* adding log entry
=> feat(acme): add host on certificate update log

kong/plugins/acme/handler.lua, kong/plugins/acme/schema.lua, spec/03-plugins/29-acme/03-access_spec.lua
Add `enable_ipv4_common_name` option to allow or deny ipv4 common names certificates. On `certificate` or `access` if the option is disabled the request is rejected, so the ACME challenge is not triggered.
This has been done on a custom plugin in Konnect to fix some gateway listening with wildcard host.
* Add `enable_ipv4_common_name` in schema
* Add check_domains logic
* Add ip v4 access challenge test
cc @fffonion
=> feat(acme): add enable_ipv4_common_name option

CONTRIBUTING.md
Kong's commit message format was similar to [conventional-commits](https://github.com/Kong/kong/pull/new/conventional-commits), but deviated in not requiring a colon after the type and optional scope.  As other repositories in the Kong organization have adopted conventional-commits and external tools begin to rely on the format, we're switching `Kong/kong` to this format as well.
=> docs: embrace conventional-commits

kong/db/migrations/core/016_280_to_300.lua
The migration steps should happen in the up phase, not the teardown phase.
Notice this PR needs cooperation from 2.8.x.x.
fix FT-3293
=> fix(db) blue/green migration for route regex path

SECURITY.md
The link to the documentation was broken, so I fixed it.
* Updated broken link
Benjamin Bertow benjamin.bertow@mercedes-benz.com, Mercedes-Benz Tech Innovation GmbH.
https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md
=> docs fix link to docs for reporting vulnerability

kong/conf_loader/init.lua, spec/01-unit/03-conf_loader_spec.lua
Add support for base64(and base64url)-encoded *_cert and *_cert_key properties.
=> feat(conf): support base64 encoded *_cert and *_cert_key

kong/runloop/plugin_servers/mp_rpc.lua, kong/runloop/plugin_servers/pb_rpc.lua
This is a fix for https://github.com/Kong/kong/issues/9301 / FT-3319: when a request made the plugin fail, the creation of a new instance was not handling a failed connection properly.
Upon failure to connect to the socket, it was possible to end up in a state where the instance existed without an instance id,
causing an infinite loop and high CPU utilization.
=> fix(external-plugins): handle failing instance creation

kong/plugins/request-transformer/access.lua
fix issue introduced by [#9186](https://github.com/Kong/kong/pull/9186)
FTI-4205
=> fix(request-transformer) properly catch errors of cjson.encode as we changed to cjson.safe now

kong-3.0.0-0.rockspec, kong/db/declarative/migrations/init.lua, kong/db/declarative/migrations/route_path.lua, kong/db/migrations/core/016_280_to_300.lua, kong/db/migrations/migrate_path_280_300.lua, kong/router/atc_compat.lua, kong/router/traditional.lua, spec/01-unit/08-router_spec.lua
We should make it consistent with regex paths, so we do not normalize user input paths.
This PR also includes migration.
Remember to add downgrade support for this to EE.
=> fix(router) prefix match no longer normalize input

kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
The traditional router would use the `a` (anchor) flag when evaluating input to ensure regex paths only match from the start of the string.
Given the route path `/prefix/[0-9]+` (<=2.8) or `~/prefix/[0-9]+` (>=3.0):
| request | match |
|------------|---------|
|`GET /prefix/123`       | yes |
|`GET /extra/prefix/123` | no |
This updates the traditional_compatible router to replicate the same behavior. The underlying atc router library does not support regex flags, so we accomplish this by prepending the regex with `^`.
=> fix(router) anchor regex paths in traditional_compatible mode

kong/init.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/02-router_spec.lua
fixes FT-3328
Previously, when worker respawns, the `router:version` and `plugins_iterator:version` keys in the cache is incorrectly set to `init`, this causes the newly spawned worker to not rebuild the router/iterator and always use the router/iterator from when master process was created.
=> fix(runloop) do not reset `*:version` to `init` when worker respawns,

kong/runloop/handler.lua, spec/03-plugins/10-basic-auth/03-access_spec.lua
As Kong auth plugins support `conifg.anonymous` to be configured as the username of consumer, once a consumer has been cached with the username as part of the cache key, this consumer cache won't be invalidated by the default cache invalidation event handler after the consumer has been deleted.
Considers of the conifg.anonymous exists in several auth plugins, so I added a common event handler to invalidate the extra cache rather than in each plugin.
FTI-4287
=> fix(auth-plugins): auth plugins cache inconsistency while anonymous was configured as username

kong/plugins/statsd/log.lua, kong/plugins/statsd/schema.lua, spec/03-plugins/06-statsd/01-log_spec.lua
1. `hostname_in_prefix` in shdict metrics have an error formate `kong.node.dd38ef0eed4d.node.dd38ef0eed4d.shdict.kong_core_db_cache.free_space:133341184|g`
2. `request_size` and `response_size` using counter is best
* `request_size` and `response_size` using counter type and change test
*  change shdict formate in `hostname_in_prefix`
=> fix (statsd) fix hostname_in_prefix flag bug and request_size/respons type bug

kong.conf.default
typofix, flavor should be `expressions`
=> fix(conf) typo fix, flavor should be `expressions`

scripts/make-release, scripts/release-lib.sh
Cherry-pick of #9406 for 3.0
* This fixes a couple small issues with the release script which were detected on a test run today in preparation for the 3.0 release
Our current release process requires the release script to be up-to-date on the branch that is going to be released (the script can't release a different branch).
The change doesn't affect Kong's functionality in any way, the modified script is only executed when cutting the release.
Exception approved by myself (Enrique Garcia).
=> chore(release) bump kong-release-tools version requirement (#9323)

scripts/make-release, scripts/release-lib.sh
By giving it proper semantic commit messages.
Previously: https://github.com/Kong/homebrew-kong/commit/ca40b01ee8f4cbca8ff70e5d000035ceb94e6984
We've been known to use https://semantic-release.gitbook.io in a couple places for automation. This PR updates the commit messages for some of the commits it generates to conform to that (the addition of `:`).
=> chore(scripts): make make-release release better

kong/router.lua, spec/01-unit/08-router_spec.lua
This PR is to support blue/green migration from 2.8.x to 3.0.x.
This PR needs https://github.com/Kong/kong/pull/9334 to cooperate.
Fix FT-3293
=> fix(core) support route migration

CHANGELOG.md, kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
=> fix(router): check empty route field

CHANGELOG.md, kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
=> fix(router/atc): properly handle empty fields on the `Route` object

CHANGELOG.md, kong/plugins/aws-lambda/handler.lua, kong/plugins/aws-lambda/iam-ecs-credentials.lua, spec/03-plugins/27-aws-lambda/04-iam-ecs-credentials_spec.lua
This PR fixes a bug that the aws-lambda plugin failed to get environment variables in ECS which leads to unable to fetch ECS task role credentials.
This bug is introduced since #8900, in which the moment of the step `require "kong.plugins.aws-lambda.iam-ecs-credentials"` is changed from happening in package load(init phase) to only in function call(access phase). Since in the Nginx process environment, only those environment variables exposed through the `env` Nginx config directory can be fetched by `os.getenv` in Lua code(with an exception that env vars can all be fetched in the init phase, and most of the Kong code that using `os.getenv` relies on this). So after #8900, fetching ECS environment variables will fail.
Sorry for bringing this bug in, and this also shows that a full …
=> fix(aws-lambda): fetch ecs environment variable failure caused by the phase change

autodoc/admin-api/data/admin-api.lua
Adds links to the atc router docs. 
Fixes an issue requested in #docs
=> docs(api): update router documentation to include atc-router docs links

bin/busted
6c9814db1 added Penlight to the top of bin/busted, which triggers a warning because it depends on lfs, which sets a global var:
> writing a global Lua variable ('lfs') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
=> fix(busted) silence gobal var warnings from OpenResty

kong/init.lua, kong/runloop/handler.lua, spec/02-integration/05-proxy/02-router_spec.lua
@Benny-Git reported on #9090 about issue of stale data picked up for router in case the worker was restarted.
Some insights:
There are several ways to restart workers:
1. you reload them with e.g. kong reload or similar nginx signal
2. worker crashes
3. worker is killed
On case 1 the `init` phase will be re-executed, on 2 and 3 it will not.
This commit ensures that the router is rebuild on init worker if it is not current (by default all workers are spawned from master process LuaJIT VM and that is not reintialized on cases 2 and 3).
FT-3432
=> fix(*): do not use stale router data if workers are respawned

kong/cmd/prepare.lua, kong/cmd/utils/prefix_handler.lua, spec/02-integration/02-cmd/09-prepare_spec.lua
Kong Docker image for example starts Kong by running `kong prepare` and then executes `nginx -c ... -p ...` as seen in:
https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh
This causes issues with Kong secret management references. By default, Kong passes secrets to nginx using environment variable when using `kong start`, but here the `nginx` is started directly without calling `kong start` and thus the secrets are not available for Kong init. This commit fixes that.
=> fix(cmd): kong prepare to write out .kong_process_secrets

kong/init.lua, kong/runloop/handler.lua
=> fix(*): do not use stale router data if workers are respawned 

CHANGELOG.md, kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua
=> fix(router/atc): check expression building error

CHANGELOG.md, kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua
Under `traditional_compatiable` mode and in rare cases, there is a possibility that ATC generated from the `Route` object contains invalid regexes. When this happens, we need to properly detect the error and report it in the log.
See PR #9480.
=> fix(router/atc): properly handle expressions building error

Jenkinsfile
Trigger per-commit releases to our unofficial docker repository `kong/kong` for past releases.
This will result in for example a commit to `next/2.4.2` making the docker images
```
GITCOMMITSHA # equivalent to 2.4.2-debian
kong/kong:2.4.2 # equivalent to 2.4.2-debian
kong/kong:2.4.2-alpine # the only multi-arch
kong/kong:2.4.2-amazonlinux
kong/kong:2.4.2-debian
kong/kong:2.4.2-ubuntu
=> chore(release): setup per-commit releases for past releases

kong/globalpatches.lua, kong/tools/utils.lua
In `globalpatches.lua` we re-implement `ngx.sleep`, 
which will check nginx phase then call `socket.sleep` or original `ngx.sleep`.
But in function `yield`, we already have phase check logic
and don't need blocking sleep.
In this case, the re-implemented `ngx.sleep` introduces unnecessary cost,
we should call original `ngx.sleep`.
This PR add a new global function `_G.native_ngx_sleep` like `_G.native_timer_at`,
and use `_G.native_ngx_sleep`  in `yield`.
=> chore(tools): use native ngx.sleep in yield

kong/api/arguments.lua, spec/02-integration/04-admin_api/21-truncated_arguments_spec.lua
Admin API will quietly truncate the request post arguments if reach the limit(100), which might cause data inconsistency issues.
1. Increase max_uri_args and max_post_args to 1000
2. Return 400 while reach the maximum argument number
[FTI-4407]
[FTI-4407]: https://konghq.atlassian.net/browse/FTI-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(admin): fix potentially truncate arguments

kong/plugins/proxy-cache/cache_key.lua, kong/plugins/proxy-cache/handler.lua, kong/tools/utils.lua, spec/03-plugins/31-proxy-cache/02-access_spec.lua, spec/03-plugins/31-proxy-cache/03-api_spec.lua
Replace md5 hashing algorithm with sha256 on the proxy-cache plugin
Add utils functions for sha256 hashing
[FT-2418](https://konghq.atlassian.net/browse/FT-2418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
=> feat(hash): replace md5 with sha256 on proxy-cache plugin

kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua
Originally the `reconfigure` event was `atomic` and it was not yielding. But this caused huge spikes in latencies when new configurations where applied.
We started to add yielding in different places that happen in `reconfigure` event. It may now lead to nasty things like: new router, and old plugins iterator gets used etc. (router from new configuration and plugin iterator from old configuration).
I needed to refactor the handler so that it could at least support more atomic flip of `router` and `plugins iterator`. The balancer is still problematic as it is shared global state and a new balancer cannot currently be build behind the scenes cooperatively, and then flip it atomically together with router and plugins iterator. I asked @locao to research if that could be doable. I leave that …
=> refactor(handler): trying to make reconfigure more atomic

CHANGELOG.md, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/clustering/utils.lua, kong/clustering/wrpc_data_plane.lua, kong/globalpatches.lua, kong/init.lua
Data plane's connection to control plane is moved to a privileged worker process, including:
- maintaining websocket (wrpc) connection and data transfer
- decompression of received data
- json decoding of the received data
- validation and flattening of received data
- inserting data to lmdb
(so that these won't affect latencies / rps on proxy workers)
=> perf(clustering): use privileged worker for control plane connection

Jenkinsfile
We changed the pulp admin api domain. Recreating the previous one is going to require some additional effort. For the purposes of the 2.8.2 release this should get us over the finish line
=> fix(url): adjust the pulp admin api links

CHANGELOG.md, kong/cmd/init.lua
With timer-ng, the CLI has become slow to terminate as nginx attempts to wait for all pending timers to stop before exiting:
```
$ time kong roar >/dev/null
real    0m1.033s
user    0m0.024s
sys     0m0.016s
```
This commit explicitly shuts down the timer-ng instance so that the CLI can quickly exit:
```
$ time kong roar >/dev/null
real    0m0.132s
user    0m0.027s
sys     0m0.013s
```
* explicitly stop timer-ng instance on completion of CLI commands
=> fix(cli): shut down timers at the end of execution

kong/router/atc.lua
Since function `yield` needs to check `phase` to decide sleep or return,
It will cause many unnecessary `get_phase` calls in a busy loop.
This PR get the nginx phase before loop begin and pass it to `yield`.
=> style(router/atc): pass `phase` param to `yield`

kong/router/compat.lua, spec/01-unit/08-router_spec.lua
Fields in route (paths/hosts) may be `nil` or `ngx.null`, so we use `is_empty_field` to check them more carefully.
=> style(router/atc): check fields with `is_empty_field` when we calc priority

kong/router/compat.lua
Generate regex path string in one line, this may reduce temporary string in Lua land.
=> style(router/atc): reduce temporary string in regex path checking 

kong/router/atc.lua, kong/router/compat.lua, kong/router/expressions.lua
Define constant `LOGICAL_AND` `LOGICAL_OR` in `atc.lua`,
then use them in other Lua modules.
=> style(router/atc): define constant LOGICAL_AND/OR

kong/router/atc.lua
Cache host-port split results to speed up router building and matching.
This logic is a mimic of traditional flavor router.
=> chore(router/atc): cache split host port results

kong/init.lua, kong/runloop/plugin_servers/init.lua
Due to PR #9342 #9546 #9547, 
We should do some code clean to fit these changes.
* use `get_saved()` in  `kong.nginx.req_start_time`
* check `ngx.config.subsystem == "http"` in module scope
* remove 'log.notice' when `worker_id() ~= 0`
* remove check of worker id in `init.lua`, because plugin server did the same thing.
* if it is http subsystem then we localize `ngx.req.get_headers` `ngx.resp.get_headers`
* if it is stream subsystem then `req_get_headers` will do nothing
=> style(plugin_server): small code clean for plugin server 

CHANGELOG.md, kong/plugins/aws-lambda/aws-serializer.lua, spec/03-plugins/27-aws-lambda/05-aws-serializer_spec.lua
This PR adds a new field `requestContext` into the lambda input data when the aws-lambda plugin is working in `awsgateway_compatible` mode.
The `requestContext` is part of the input data in lambda proxy integration, according to [this AWS document page](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format), and it contains many fields containing request related information on AWS API Gateway. 
The aws-lambda plugin in Kong provides an AWS API Gateway compatible mode that can generate an input data similar with 
[the example provided in this doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format), …
=> feat(aws-lambda): add requestContext field into aws-gateway-compatible input

kong/clustering/data_plane.lua, kong/clustering/wrpc_data_plane.lua, kong/tools/utils.lua, spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua
Translate the log to a more user-friendly form, and lower the log level.
Also correcting some of the log formats.
Fix FT-3204
=> fix(clustering): DP friendly msg when CP offline

kong/reports.lua, kong/router/atc.lua, kong/router/init.lua, kong/router/traditional.lua, kong/router/utils.lua, spec/02-integration/05-proxy/22-reports_spec.lua, spec/kong_tests.conf
Collect statistics of configured routers and runtime usage:
1. How many routes are configured;
2. How many paths are configured for routes;
3. How many headers are configured for routes;
4. The used router flavor;
5. How many routes are configured for different kinds of protocols;
6. How many routes are configured with different path handling;
7. How many regex paths matched
Configured route statistics are collected every time the router is rebuilt. The statistics are sent along with the ping.
Fix FT-3217
=> feat(report): route statistic

kong/cmd/prepare.lua, kong/cmd/utils/prefix_handler.lua, spec/02-integration/02-cmd/09-prepare_spec.lua
Kong Docker image for example starts Kong by running `kong prepare` and then executes `nginx -c ... -p ...` as seen in:
https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh
This causes issues with Kong secret management references. By default, Kong passes secrets to nginx using environment variable when using `kong start`, but here the `nginx` is started directly without calling `kong start` and thus the secrets are not available for Kong init. This commit fixes that.
=> fix(cmd): kong prepare to write out .kong_process_secrets (#9478)

kong/error_handlers.lua
Use number index to simplify error message processing.
* use number index instead of string index
* add function `get_body` and cache other messages.
=> refactor(error_handlers):simplify error handlers

CHANGELOG.md, kong-3.1.0-0.rockspec
- **x509.\*:** fix set_extension will fail when a extension with same NID is not exist yet ([#75](https://github.com/fffonion/lua-resty-openssl/issues/75)) [b2f57b8](https://github.com/fffonion/lua-resty-openssl/commit/b2f57b860509a371ab1df71bbbc9e176e5a4d004)
- **x509.altname:** support set and get IP addresses ([#74](https://github.com/fffonion/lua-resty-openssl/issues/74)) [363c80d](https://github.com/fffonion/lua-resty-openssl/commit/363c80d1f2c7ba29dce268e213a9a16c9eae2953)
- **x509.store:** add set_flags ([#77](https://github.com/fffonion/lua-resty-openssl/issues/77)) [8f3f16a](https://github.com/fffonion/lua-resty-openssl/commit/8f3f16a2b6d6c0f680c781f20a9e84a631da9aa5)
- **\*:** reuse cdata to improve performance [fc9cecd](https://github.com/fffonion/lua-resty-openssl/commit/fc9cec …
=> chore(deps): bump lua-resty-openssl from 0.8.10 to 0.8.13

kong/plugins/request-transformer/access.lua, spec/03-plugins/36-request-transformer/02-access_spec.lua
backport FTI-4205
[The original PR](https://github.com/Kong/kong/pull/9186)
=> fix(request-transformer): preserves empty json arrays after decoding and re-encoding

kong/plugins/http-log/schema.lua, spec/03-plugins/03-http-log/02-schema_spec.lua
[The original PR](https://github.com/Kong/kong/pull/9257)
fix(http-log): internal error during validating the schema if `http_endpoint` contains userinfo but `headers` is empty
The missing field will be filled with an appropriate default value
in function `handle_missing_field`. When no explicit defualt value
is set and the field isn't nilable and required, then its default
value will be ngx.null, which is a lightuserdata with the point NULL.
FTI-4173
=> fix(http-log): internal error during validating the schema if http_endpoint contains userinfo but headers is empty (backport FTI-4173)

CHANGELOG.md, kong/cmd/start.lua, kong/global.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua
This fixes an issue with how Kong initializes resty.events. The code was
previously using `ngx.config.prefix()` to determine the listening socket
path to provide to the resty.events module. This causes breakage when
NGINX is started with a relative path prefix:
> failed to instantiate 'kong.worker_events' module: failed to disable listening: unix:my-prefix/worker_events.sock
Instead of using `ngx.config.prefix()`, Kong will now prefer
`kong.configuration.prefix` when available, as it is already normalized
to an absolute path. If `kong.configuration.prefix` is not defined, the
result of `ngx.config.prefix()` will be used after resolving it to an
absolute path.
Also contains an unrelated fix in `kong/cmd/start.lua`.
* prefer `kong.configuration.prefix` to `ngx.config.prefix()`
* convert …
=> fix(core): ensure absolute path is used for event sock

CHANGELOG.md, kong/tracing/propagation.lua, spec/01-unit/26-tracing/02-propagation_spec.lua
cherry-pick of #9280
Co-authored-by: Mayo <mayocream39@yahoo.co.jp>
Co-authored-by: Wangchong Zhou <fffonion@gmail.com>
=> fix(plugins/zipkin): correctly parse `ot` baggage headers

CHANGELOG.md, kong/plugins/request-transformer/access.lua, spec/03-plugins/36-request-transformer/02-access_spec.lua
This PR fixes a bug in the `request-transformer` plugin, where the rename header cannot override an already existing header steadily.
If a header `A-header` already exists with a value `A-value` in the request, and the `request-transformer` plugin is configured to rename `B-header`(with a value `B-value`) to `A-header`(with different format, like all chars are capitalized), then the upstream request will contain an `A-header` with possibly `A-value` or `B-value`. This unpredictable behaviour may caused by `pairs` function disorder behaviour(Again!).
The code flow is as follows:
A `header` table is fetched by `ngx.req.get_headers` and used later for storing upstream request headers
https://github.com/Kong/kong/blob/c33d745793b454ab27d9681562fadbccbc454a1b/kong/plugins/request-transformer/ac …
=> fix(request-transformer): unpredictable overriding result from rename header to existing header caused by pairs disorder

CHANGELOG.md, kong-3.1.0-0.rockspec
- **x509.crl:** fix metamethods when revoked is empty ([#79](https://github.com/fffonion/lua-resty-openssl/issues/79)) [e65adc7](https://github.com/fffonion/lua-resty-openssl/commit/e65adc7f132628c97e4db69cb5c4b13ff9cf0abf)
=> chore(deps): bump lua-resty-openssl from 0.8.13 to 0.8.14

kong/plugins/aws-lambda/handler.lua, spec/03-plugins/27-aws-lambda/99-access_spec.lua, spec/fixtures/aws-lambda.lua
This PR changes the behaviour of extracting lambda response in the AWS-Lambda plugin. There will be 3 situations that are considered valid for the field `isBase64Encode`: true, false or not defined. Values that are not booleans or not nil are considered invalid and the plugin will return a 502 response.
Note that if a lambda response contains `"isBase64Encode": null`, then the value(turned into userdata `cjson.null` in Lua) will also be considered invalid.
* Fix the behaviour of extracting lambda response that the value of isBase64Encode can only accept true, false or not defined.
* Add related tests
Fix [FTI-4420]
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format
[FTI-4420]: …
=> fix(aws-lambda): accept only true|false|nil for isBase64Encode

CHANGELOG.md, kong/include/kong/pluginsocket.proto, kong/runloop/plugin_servers/pb_rpc.lua
=> fix(pdk): response.exit accept bytes

kong/init.lua, kong/runloop/plugin_servers/init.lua, kong/runloop/plugin_servers/mp_rpc.lua, kong/runloop/plugin_servers/pb_rpc.lua, kong/runloop/plugin_servers/process.lua, spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
We start plugin servers asynchronously while requests try to send RPC calls to the server. When the sock file is not deleted, the server may start a bit slower and the requests hit before it listen to the newly created sock file.
fix FTI-4282
=> fix(pluginserver): error if req come before ready

CHANGELOG.md, kong-3.1.0-0.rockspec
- luke no longer crashes in std.normalize require loops occasionally in Lua 5.4.
- lyaml emitter no longer leaks at least six bytes for every map, sequence and scalar emitted.
=> chore(deps): bump lyaml from 6.2.7 to 6.2.8

.github/workflows/build_and_test.yml
Now, CI don't check the `#o` or `#only` tag in busted tests, this PR fixed it.
_FT-3502_
=> chore(Github Action) fix job `lint-doc-and-unit-tests`

kong/plugins/rate-limiting/handler.lua, kong/plugins/rate-limiting/schema.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua
Error code and error message are hardcoded for rate-limiting plugin.
This allow to set them via configuration
https://stackoverflow.com/questions/72557894/how-can-i-replace-kong-error-to-a-custom-text
=> feat(rate-limting) allow to set error code and error message

CHANGELOG.md, kong/clustering/control_plane.lua, kong/clustering/wrpc_control_plane.lua
1. When new DP connects, it first pushes config, then adds the DP to client lists;
1. When the client list is empty, `push_config_loop` skips handling of the new config signal, expect the config to be sent by logic no.1
This causes races when a new config comes in while the first DP is receiving its first config, and the config will be skipped as the list is empty. The new config won't be seen by that DP or any new DPs.
We fix that by re-posting the semaphore, so no config will be missed.
Co-authored-by: @flrgh for his diagnosis(don't forget to add this to the commit message)
fix FT-3496
=> fix(clustering): race cond for new DP and new cfg

CHANGELOG.md, kong/error_handlers.lua, spec/02-integration/05-proxy/13-error_handlers_spec.lua, spec/fixtures/custom_nginx.template
When nginx blocks request with trace method from client, it hits the default error message in kong which is "The upstream server responded with 405", it is a little ambiguous. Actually the request doesn't reach upstream. 
Define  a detail message "Method not allowed" for 405 status code.
=> chore(error_handlers): define response message for trace method 405 error status code

.github/workflows/label-check.yml
Add CI to prevent merging when `do-not-merge` or `do not merge` labels exist.
related: https://github.com/Kong/koko/pull/170
=> chore(ci): fail on do-not-merge label

kong/clustering/data_plane.lua
s/err/err_msg/
This matches the behavior of the wRPC data plane code:
https://github.com/Kong/kong/blob/1a110469bd2513e69a15ca2161816c24354ce273/kong/clustering/wrpc_data_plane.lua#L226-L233
=> fix(clustering): log the correct error message var

kong/plugins/opentelemetry/handler.lua, spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
According to the original design, the default propagation header type should be `w3c`, described in https://docs.konghq.com/hub/kong-inc/opentelemetry/#propagation.
> The plugin detects the propagation format from the headers and will use the appropriate format to propagate the span context. If no appropriate format is found, the plugin will fail back to the default format, which is w3c.
The previous implementation didn't specify the default header type successfully, it was failback to the `b3` default.
=> fix(opentelemetry): set default propagation type to w3c

kong/pdk/tracing.lua, kong/plugins/opentelemetry/handler.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua, spec/03-plugins/37-opentelemetry/05-otelcol_spec.lua
Fix an issue where OpenTelemetry spans are randomly stripped and not sent to the backend.
=> fix(otel): use `BatchQueue` to avoid worker-level table data race

spec/02-integration/01-helpers/01-helpers_spec.lua, spec/02-integration/02-cmd/03-reload_spec.lua, spec/02-integration/02-cmd/06-restart_spec.lua, spec/02-integration/02-cmd/12-hybrid_spec.lua, spec/helpers.lua
The main goal I started out with was to make the test in `spec/02-integration/02-cmd/12-hybrid_spec.lua` less flaky. Waiting until a file exists and is non-empty is a common enough task that I made a helper function for it.
```lua
helpers.wait_for_file_contents(fname, timeout) end
```
I have put this function into use in a few tests.
Along the way I discovered that `helpers.wait_until` was using `ngx.time()` and therefore lacks some precision when being used with timeout of <= 1, so I swapped that out for `ngx.now()`.
=> tests(helpers): add file waiter

spec/02-integration/01-helpers/01-helpers_spec.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua, spec/helpers.lua
This takes the re-open logic I used in #8925 and moves it into the helper http client so it can be reused elsewhere.
While there are a lot of tests in kong that could benefit from this behavior, there's not really a huge benefit to updating existing, non-flaky tests that simply create a new http client for each test case, so for now I haven't changed any test cases aside from the obvious prometheus one.
=> tests(helpers): add a reopen option to proxy http clients

kong/db/schema/entities/routes.lua, kong/router/atc.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua
When we did code clean for atc-router(#9331), we removed function `get_schema()` unwisely,
which is used in DB schema entity checking.
See [`schema/entities/routes.lua`](https://github.com/Kong/kong/blob/e7b6963f8c01c11232828d2709de08743708bf56/kong/db/schema/entities/routes.lua#L50).
=> fix(router/atc): exports atc.schema for entities checking

kong/plugins/request-termination/schema.lua, spec/03-plugins/14-request-termination/01-schema_spec.lua
`status_code` should not be allowed to be set to null, otherwise a 500 error will be returned.
* Do not allow set `status_code` as null
FTI-4291
=> fix(request-termination): status_code cannot be set as null

spec/README.md
There is a typo into the spec README, 
https://github.com/Kong/gojira/issues/51
=> doc(spec): Fix the variable according to `helpers.redis_host`

kong/plugins/oauth2/access.lua, spec/03-plugins/25-oauth2/03-access_spec.lua
PKCE enforcement can be applied to both `public`  and `confidential` clients as per the implementation of [`requires_pkce`](https://github.com/Kong/kong/blob/2c1d24223b95136ece01892a55bc25c626b2eb14/kong/plugins/oauth2/access.lua#L247-L260). Currently the error returns to calling applications will always specify that `code_challenge is required for **public** clients` (even if the calling client is a `confidential` client). This PR ensures that the error message correctly reflects the client type.
* Use `client.client_type` when building "code challenge required" error message to ensure that the error message correctly reflects the calling client's type
* Updated existing test for confidential client to reflect the updated error message.
=> fix(oauth2): specify correct client type in `code_challenge` error msg

spec/02-integration/04-admin_api/09-routes_routes_spec.lua, spec/02-integration/05-proxy/07-upstream_timeouts_spec.lua, spec/03-plugins/27-aws-lambda/99-access_spec.lua, spec/03-plugins/30-session/01-access_spec.lua, spec/03-plugins/30-session/02-kong_storage_adapter_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua, spec/03-plugins/35-azure-functions/01-access_spec.lua, t/03-dns-client/02-timer-usage.t
Some of these don't actually try to make requests out to `httpbin.org`, but hopefully it saves future us some work to have them not show up in `git grep`.
=> tests(*): remove httpbin.org from integration tests

spec/fixtures/balancer_utils.lua
This is an attempt to (maybe) address a mysterious test failure:
https://github.com/Kong/kong/runs/6729326547?check_suite_focus=true
```
./spec/fixtures/balancer_utils.lua:333: Error 400: {"code":2,"message":"schema violation (host: required field missing)","fields":{"host":"required field missing"},"name":"schema violation"}
./spec/fixtures/blueprints.lua:21: in function 'insert'
./spec/fixtures/balancer_utils.lua:333: in function 'add_api'
...tion/05-proxy/10-balancer/03-consistent-hashing_spec.lua:207: in function 'test_with_uri'
...tion/05-proxy/10-balancer/03-consistent-hashing_spec.lua:393: in function <...tion/05-proxy/10-balancer/03-consistent-hashing_spec.lua:388>
```
This code uses blueprints to create a service object, via the `url` shorthand. The value of …
=> tests(fixtures): fortify service creation

CHANGELOG.md, kong/plugins/azure-functions/schema.lua, kong/plugins/grpc-gateway/schema.lua, kong/plugins/grpc-web/schema.lua, kong/plugins/pre-function/_schema.lua, kong/plugins/prometheus/schema.lua, kong/plugins/proxy-cache/schema.lua, kong/plugins/request-transformer/schema.lua, kong/plugins/session/schema.lua, kong/plugins/zipkin/schema.lua
All plugin entities are expected to have a `protocols` schema field, but some plugin schemas are missing it. From a functional point of view, this doesn't have any impact, since the `protocols` field is still injected in the overall schema. But when plugin schemas are retrieved via the Admin API using the `/schemas/plugins/<name>` endpoint, then the "original" schema is returned. For example:
```
$ http :8001/schemas/plugins/prometheus
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 354
Content-Type: application/json; charset=utf-8
Date: Tue, 11 Oct 2022 06:42:47 GMT
Server: kong/3.0.0
X-Kong-Admin-Latency: 6
{
"fields": [
{
"config": {
"fields": [
{
"per_consumer": {
"default": false,
"type": "boolean"
}
},
{
"status_code_metrics": {
"default": …
```
=> fix: add missing protocols field to plugins

CHANGELOG.md, kong.conf.default, kong/router/traditional.lua, kong/templates/kong_defaults.lua
When a user sets too many regex routes and `lua_regex_cache_max_entries` is set too low (or kept at default 1024), a performance issue might occur due to regex trashing. 
OpenResty [claims](https://github.com/openresty/lua-nginx-module/blob/master/README.markdown#lua_regex_cache_max_entries) that it will emit a warning when the limit has been exceeded, but it doesn't.
Fix FTI-4455
=> perf(router): increase `lua_regex_cache_max_entries` and show warning if too small

CHANGELOG.md, kong/plugins/opentelemetry/handler.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
When trace context is propagated in w3c format header, the parent_id is not set on the root span and not reported to the collector. I could not come up with a way to cover it in the tests.
* Fix `parent_id` reporting in traces propagating through w3c headers
Fix #9627
=> fix(opentelemetry): fix parent_id reporting from w3c header

CHANGELOG.md, kong-3.1.0-0.rockspec
- **pkey:** check private key existence before doing sign ([#83](https://github.com/fffonion/lua-resty-openssl/issues/83)) [eefcd2a](https://github.com/fffonion/lua-resty-openssl/commit/eefcd2a80b240f44be0bdadd1c2ccc28612004c0)
=> chore(deps) bump resty.openssl from 0.8.14 to 0.8.15

kong/plugins/statsd/schema.lua, spec/03-plugins/06-statsd/02-schema_spec.lua
remove stated metric must type limitation
* remove the constraint to disallow user configure different metrics types, to align with the previous statsd plugin behaviour
#9659 
FT-3518
=> fix(statsd) remove must type limitation

Jenkinsfile
The nature of building / packaging Kong requires retrieving dependencies that we won't always have cached. With that in mind add some retry logic to try and force builds to succeed when there's general internet flakiness
=> chore(ci): add some retry logic to parts of our CI

spec/helpers.lua
This sets the `reopen` flag for the admin client in `spec.helpers`, meaning all `GET`, `HEAD`, `OPTIONS`, and `TRACE` requests with the admin client will be retried with a new connection when there is a TCP level error. This should make our tests a little more resilient to transient problems that can occur in CI.
Requests are only retried once per connection, so there is no risk of getting stuck in a loop if something is actually down.
Integration tests for this functionality were added in #8932; all this PR does is turn it on by default.
=> tests(helpers): retry all safe admin client requests

Jenkinsfile
We've been testing Jammy for [~2 weeks](https://github.com/Kong/kong-build-tools/pull/567). Let's start officially releasing Jammy packages
=> feat(release): release official Ubuntu 22.04 (Jammy) packages

.github/workflows/perf.yml, spec/fixtures/perf/terraform/bring-your-own/main.tf, spec/fixtures/perf/terraform/bring-your-own/output.tf, spec/fixtures/perf/terraform/bring-your-own/ssh.tf, spec/fixtures/perf/terraform/bring-your-own/variables.tf, spec/helpers/perf.lua, spec/helpers/perf/drivers/terraform.lua
This PR moves the perf test in CI off equinix and to a pre-provisioned provider.
=> tests(perf): add "bring-your-own" provider

.github/workflows/build_and_test.yml, .github/workflows/perf.yml, .github/workflows/upgrade-tests.yml
Cancel previous runs if new commits are pushed to the PR, but run for each commit on master.
Ensure only one perf test run at a time, as we move to shared machines.
=> chore(tests) add concurrency control

.github/workflows/autodocs.yml
The labelers are intentionally left on `ubuntu-latest` as they are very simple workflows that should be able to run on any version of OS.
`ubuntu-latest` is currently still pointing at `ubuntu-20.04`, change `autodoc` jobs to make it consistent.
=> chore(autodocs): use `ubuntu-22.04` for autodoc as well

CODEOWNERS
CODEOWNERS file was originally added in
Kong/kong#8691.
The rationale at the time was to make sure all PRs are approved and merged only after maintainers have reviewed the change. Since then, we have come a long way.
PRs now are merged only after a moderator
on the team has taken a look at the PR and only moderators have permission to perform a merge.
This commit removes the CODEOWNERS file. My rationale is that the number of Kong maintainers is large and every change to every PR results in a notification to all members. This results in a very signal-to-noise ratio and a lot of members deal with a very high notification volume. My hypothesis here is that lowering the notification volume will help most members and they can deal with a smaller set of PRs on a daily basis.
A select few …
=> chore(ci): remove CODEOWNERS file

kong/router/compat.lua, spec/01-unit/08-router_spec.lua
We already transform '\\' to '\\\\' in regex path with function `atc.escape_str()`,
now we add more test cases to make sure it works well.
See FTI-4444.
=> tests(router/atc): escape '\' in regex path properly

.github/workflows/perf.yml
Past 2 test runs were killed by timeout (for example https://github.com/Kong/kong/actions/runs/3426004985).
Bump it up and test if it will solve the issue.
=> tests(perf): bump max test run duration from 2h to 3h

spec/02-integration/01-helpers/01-helpers_spec.lua, spec/helpers.lua
The old implementation of clean_logfile() exec()-ed out to /bin/sh with redirection to truncate the file. This yields an annoying error message if the file does not exist and cannot be created because its parent directory also doesn't exist:
> sh: 1: cannot create /home/runner/work/kong-ee/kong-ee/servroot/logs/error.log: Directory nonexistent
This implementation tries to be a little smarter. It uses `io.open()` instead of `os.execute()` and will throw an error for any errors except ENOENT.
When adding integration tests for this I noticed that the Kong instance that was running within the test suite was interfering with things a bit, so I moved all of the tests that _don't_ require a running Kong instance to a separate `describe(...)` block.
=> tests(helpers): use io.open to truncate file

spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/01-unit/09-balancer/01-generic_spec.lua, spec/01-unit/09-balancer/02-least_connections_spec.lua, spec/01-unit/09-balancer/03-consistent_hashing_spec.lua, spec/01-unit/09-balancer/04-round_robin_spec.lua, spec/01-unit/14-dns_spec.lua, spec/01-unit/21-dns-client/01-utils_spec.lua, spec/01-unit/21-dns-client/02-client_spec.lua, spec/01-unit/21-dns-client/03-client_cache_spec.lua, spec/fixtures/headers.conf, spec/fixtures/invalid.conf, spec/fixtures/to-strip.conf, spec/kong_tests.conf
=> chore(tests): remove hardcoded dns resolver in tests

kong-2.8.3-0.rockspec
The lua-resty-healthcheck feature used to keep the health status when an existent target is updated was raising more events than needed. The issue was fixed in the healthcheck module and bumped here.
* lua-resty-healthcheck bump.
* Same behavior as before, no new tests.
FTI-4353
=> chore(rockspec): bump lua-resty-healthcheck to 1.5.3

kong/db/declarative/init.lua
Define constant `IS_HTTP_SUBSYSTEM` and `STREAM_CONFIG_SOCK`,
and move them into `do ... end` block
=> style(db/declarative): use constant wisely

kong/cmd/utils/prefix_handler.lua
`log.warn()` is not `ngx.log`, we should use `string.format` style, not string concat or array style.
=> fix(cmd): use correct format to log message

kong/clustering/utils.lua, kong/clustering/wrpc_control_plane.lua, spec/01-unit/19-hybrid/03-fields-removal_spec.lua, spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
~_This depends upon #9740 and will be tough to review until it's merged._~
The goal of these changes is to take the cluster compatibility functionality from the legacy control plane code and wire it into the wRPC control plane.
In the interest of time/ease of review, there is very little refactoring here. As such, the code is not very elegant. The changes themselves are pretty minimal though, and to be honest I think most everything in `kong.clustering.*` could use a follow-up refactor for cleanliness and ease of maintenance with EE in the next release or two.
Tests for this are pretty minimal as the `update_compatible_payload` functionality is nothing new and has been fairly well-tested via the legacy cluster protocol. If any issues are discovered, bugfix/additional tests can be …
=> feat(clustering): add config compat transformations to wRPC

kong/db/schema/typedefs.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua
Example:
```json
{
"paths": ["/%c3%A4"]
}
```
```json
{
"fields": {
"paths": [
"not normalized path. Suggest: '/ä'"
]
},
"code": 2,
"name": "schema violation",
"message": "schema violation (paths.1: not normalized path. Suggest: '/ä')"
}
```
fix FT-3359
=> fix(core): prefix path must be normalized

kong-3.1.0-0.rockspec
The lua-resty-healthcheck feature used to keep the health status when an existent target is updated was raising more events than needed. The issue was fixed in the healthcheck module and bumped here.
* lua-resty-healthcheck bump.
* Same behavior as before, no new tests.
FTI-4353
=> chore(rockspec): bump lua-resty-healthcheck to 1.6.2

CHANGELOG.md, kong/plugins/http-log/handler.lua, spec/03-plugins/03-http-log/03-queue_spec.lua
Fix an issue where queue id serialization does not include `queue_size` and `flush_timeout`.
Fix #9272
=> fix(http-log): queue id serialization

kong/api/routes/debug.lua, kong/init.lua, kong/runloop/handler.lua, kong/templates/nginx_kong.lua, spec/fixtures/custom_nginx.template
Use `kong` shm instead of its own dedicated `kong_log_level`.
=> fix(api): various minor fixes and optimizations for dynamic log levels

kong/pdk/private/node.lua, spec/02-integration/09-hybrid_mode/09-node-id-persistence_spec.lua
- Uses `kong.cmd.utils.log` instead of `ngx.log` as the latter is unavailable in cmd context.
- Fixes the existing node id file with an invalid uuid won't be rewritten after Kong start.
- Enables the `pending` test
=> fix(clustering): override node id while it contains an invalid uuid

.github/workflows/package.yml
required for the release branches so
```
GITHUB_REF=release/3.0.x
```
becomes the docker tag
```
3.0.x
```
and not
```
release/3.0.x
```
Additionally if we successfully package, and test the package don't mark the build a failed because of a storage problem (for now)
Tested on my fork to verify the result:
=> fix(ci): make sure docker tag is valid

spec/03-plugins/23-rate-limiting/04-access_spec.lua, spec/helpers.lua
**BLOCKS https://github.com/Kong/kong/pull/9538**
The tests of the rate-limiting plugin have many flaky factors, and it is hard to debug. Moreover, the structure of these test cases needs some improve, so I refactor it.
_FT-3543_
=> tests(rate-limiting): refactor tests

CHANGELOG.md, kong/pdk/vault.lua
Fix issue #9839
* check nginx phase
* if it is `init` or `init_worker`, set `wait_ok` to `false`
Fix #_[9839]_
=> fix(pdk/vault): do not call sema:wait in init phase

CHANGELOG.md, kong/clustering/utils.lua, kong/init.lua
Because of increased memory usage, despite the benefits with large configurations on hybrid mode data plane latency, we decided to remove the use of privileged worker for data plane to control plane connection.
This commit removes the use of privileged worker.
Backport of #9860.
=> revert(clustering): use privileged worker for control plane connection

kong/cache/init.lua, kong/db/strategies/postgres/init.lua, kong/pdk/cluster.lua, kong/plugins/key-auth/handler.lua, spec/03-plugins/09-key-auth/02-access_spec.lua
The postgres DAO return 0 when key ttl falls between `[0, 1)`, which would make the key never expires in L1/L2 cache.
This fix will check if the returned ttl is 0. If it is, then make it `nil`.
<https://konghq.atlassian.net/browse/FTI-4066>
- [ y ] The Pull Request has tests
Fix [FTI-4066](https://konghq.atlassian.net/browse/FTI-4066)
=> fix(key-auth) expire keys in L1/L2 caches when ttl is in [0, 1)

kong/plugins/zipkin/handler.lua, kong/plugins/zipkin/reporter.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua
The Zipkin plugin error log prefix was lost in the timers.
Reimplement #8770
=> chore(zipkin): add log namespace in timers

CHANGELOG.md, kong/plugins/zipkin/handler.lua, spec/03-plugins/34-zipkin/zipkin_no_endpoint_spec.lua
The global Zipkin plugin always executes in the rewrite phase whenever a route/service-specific plugin enables, since the router only executes after the `rewrite` phase.
This cause an issue where route/service-specific plugin inherits the context written by the global plugin in the `access` phase.
According to [plugin precedence](https://docs.konghq.com/gateway/latest/admin-api/#precedence), a plugin will always be run once and only once per request, and route/service-specific plugins have higher priority than global plugins.
This PR moves the logic inside the `rewrite` phase handler to the `log` phase, and it sets the span annotation lazily with no side-effects.
Fix #9812
=> fix(zipkin): global plugin always executes in rewrite phase

Jenkinsfile
Backport e557e96bd9d623fc625fda99fcd8051be501419b from #9883.
=> [Backport release/3.1.x] fix(ci): auth

CHANGELOG.md
* Fix link / section for 3.1.0
* Add 3.0.1 entries that were only merged to `release/3.0.x`
=> docs(*) fix changelog link, add 3.0.1

kong-3.1.0-0.rockspec
<a name="0.10.1"></a>
- **zerossl:** concatenate response body as string instead of table ([#98](https://github.com/fffonion/lua-resty-acme/issues/98)) [986b1db](https://github.com/fffonion/lua-resty-acme/commit/986b1dbde6c7cc8261d10d5e8c65942e72eb9a32)
<a name="0.10.0"></a>
- **autossl:** expose function to get cert from LRU cache ([#96](https://github.com/fffonion/lua-resty-acme/issues/96)) [6135d0e](https://github.com/fffonion/lua-resty-acme/commit/6135d0e3ccc31f58193af1f49ec6fcdd9f45d6da)
- **autossl:** better cache handling in blocking mode [40f5d2d](https://github.com/fffonion/lua-resty-acme/commit/40f5d2d679a684eab81ccb4fcd1282a4255d8c37)
- **autossl:** fix behavior change in non blocking mode [aa484cc](https://github.com/fffonion/lua-resty-acme/commit/aa484ccc0ecd7ee1db4162c46feb96 …
=> chore(deps): bump lua-resty-acme from 0.9.0 to 0.10.1

CHANGELOG.md, kong/plugins/zipkin/handler.lua, kong/plugins/zipkin/schema.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua
Add support to set durations as span tags.
Fix #8126
Reimplement #8264
FTI-4507
=> feat(zipkin): add support for labeling phase duration as tags

kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
name is provided. fixes KAG-209
=> fix(router): add better error handling for ATC router when invalid field

kong.conf.default, kong/conf_loader/init.lua, spec/01-unit/03-conf_loader_spec.lua, spec/02-integration/08-status_api/01-core_routes_spec.lua
Previously, only support HTTP/1.1 TLS
- [ y ] The Pull Request has tests
* [Support HTTP2]
Fix #_[FTI-4582]_
[FTI-4582]: https://konghq.atlassian.net/browse/FTI-4582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(status_listen) support HTTP/2

.github/workflows/package.yml
Due to the dangers inherent to automatic processing of PRs, GitHub’s standard pull_request workflow trigger by default prevents write permissions and secrets access to the target repository.
Removed login step to Docker Hub.
=> chore(ci): fix packaging running on forks

CHANGELOG.md, kong/db/strategies/postgres/init.lua
Add back `FLOOR` so that `ttl` is returned as integer instead of float.
PR <https://github.com/Kong/kong/pull/9801> remove `FLOOR` part to reflect the real `ttl` value, but may return a `float` value instead of `int`, which would break some downstream clients as depicted in issue <https://github.com/Kong/kong/issues/9944>.
This PR add back `FLOOR` as in the `handler.lua`, we have double-check on `cred.ttl == 0`. So it is **safe** to add back.
Also check [FTI-4066].
Fix #_[9944]_
[FTI-4066]: https://konghq.atlassian.net/browse/FTI-4066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(db): add back `FLOOR` so ttl returns integer instead of float

kong/runloop/handler.lua
In reconfigure event handler, we use `current_router_hash` and others
to compare with new hashes, but they are function local vars.
It is not a common used pattern.
This PR puts these hash vars into `do block` scope and did some style cleaning,
Now the code is more readable and maintainable.
* move `current_router_hash` `current_plugins_hash` `current_balancer_hash` to `do block` level
* move logic into function `reconfigure_handler()`
* use `get_now_ms()` to calculate delta time
* remove unnecessary `is_exiting()`
* change the hash's default value to `0`, so we can compare them with `nil` directly
* style fix
=> refactor(core/runloop): code clean for reconfigure event processing

kong/plugins/aws-lambda/handler.lua, kong/plugins/aws-lambda/iam-ec2-credentials.lua, kong/plugins/aws-lambda/schema.lua, spec/03-plugins/27-aws-lambda/03-iam-ec2-credentials_spec.lua
This supersedes https://github.com/Kong/kong/pull/8382 by Ivan Savcic <isavcic@gmail.com> to fix tests.
Fixes FTI-4536 FTI-1889 
Relates to CSRE-663
=> Support IMDSv1 and IMDSv2

kong/runloop/balancer/upstreams.lua, spec/02-integration/06-invalidations/04-balancer_cache_correctness_spec.lua
The upstreams module's load_upstreams_dict_into_memory returned
non-cacheable value when upstreams table is empty, causing empty
table reload in request context after 10s negative TTL's expiration.
See https://github.com/Kong/kong/issues/8970#issue-1273886114.
To fix this, empty table may be considered a valid value to cache.
* [Fix empty upstreams table reload every 10s]
Fix #8970
=> fix(balancer) fix upstreams reload every 10s

kong/runloop/handler.lua
In the vast majority cases, this change has no effect, except when the host of balancer is exactly equal to "upstream_host" and `preserve_host` is `false`.
This was introduced by https://github.com/Kong/kong/pull/9494
=> fix(runloop): `set_host_header` pass the wrong upstream_host

kong/runloop/handler.lua
The original PR: https://github.com/Kong/kong/pull/9996
In the vast majority cases, this change has no effect, except when the host of balancer is exactly equal to "upstream_host" and `preserve_host` is `false`.
=> cherry-pick fix(runloop): `set_host_header` pass the wrong upstream_host (#9996)

autodoc/admin-api/data/admin-api.lua
This PR fixes an article mistake in the key set description docs.
=> docs(admin-api): fix a typo in key set description

autodoc/admin-api/data/admin-api.lua
Correct JSON response data of autodoc example.
=> docs(autodoc): correct example response data

CHANGELOG.md, kong/db/declarative/import.lua, kong/init.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/04-admin_api/02-kong_routes_spec.lua
Ensure the `hash` field is correctly configured when the declarative configuration is loaded.
=> fix(declarative-config): set hash when config is loaded

autodoc/admin-api/data/admin-api.lua
None of the debug routes are db-less compatible, but the "DB-LESS COMPATIBLE" green text still shows up next to each route: https://docs.konghq.com/gateway/latest/admin-api/#debug-routes
=> docs(admin-api): add db-less mode restrictions for the debug routes

.github/workflows/release.yml
Only enable the GitHub Actions cache for OpenResty when the trigger event is `pull_request`, otherwise Kong Manager artifact will always be cached since the `nightly` tag is used and never updated in the `.requirements` file.
=> build(release): cache only for pull_request

CHANGELOG.md, kong/plugins/jwt/handler.lua, spec/03-plugins/16-jwt/03-access_spec.lua
Deny requests that have different tokens in the jwt token search locations.
[FTI-4580]
[FTI-4580]: https://konghq.atlassian.net/browse/FTI-4580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(jwt): deny requests that have different tokens in the jwt token search locations.

CHANGELOG.md, kong/templates/nginx_kong.lua, spec/02-integration/05-proxy/03-upstream_headers_spec.lua, spec/fixtures/custom_nginx.template
Currently, Kong adds `charset=UTF-8` to `Content-Type` header of response if the content-type is one of `charset_types` and contains no charset.
Kong doesn't know the charset of upstream response and can't assume it is UTF-8. Also we shouldn't change the response unless explicitly required e.g. by the response transformer plugin.
FTI-4551
[FTI-4551]: https://konghq.atlassian.net/browse/FTI-4551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(templates): not add default charset when upstream response doesn't contain it

kong/init.lua
`current_try` is a small table, which has four fields:
* `balancer_start`
* `balancer_latency`
* `ip`
* `port`
But if the balancer retries, it will have another two fields: `state` and `code`.
In this PR I create a table with 4 fields, should we change it to 6？
=> style(core/balancer): use `table.new` to pre-create try table

kong/init.lua
* return more information in `has_declarative_config()`
* simplify `parse_declarative_config()`
* change default format version to `3.0`
=> style(core/init): optimize parse declarative config

CHANGELOG.md, kong/conf_loader/init.lua, kong/plugins/datadog/handler.lua, kong/plugins/http-log/handler.lua, kong/plugins/opentelemetry/handler.lua, kong/plugins/statsd/log.lua, kong/tools/batch_queue.lua, spec/01-unit/27-batch_queue_spec.lua
Backported from master.
This commit implements an upper limit on the number of batches that may be waiting on a queue for processing.  Once the limit has been reached, the oldest batch is dropped from the queue and an error message is logged.  The maximum number of batches that can be waiting on a queue is configured through the max_queued_batches parameter of the queue, which defaults to 100 and can be globally overriden with the max_queued_batches parameter in kong.conf
KAG-303
[KAG-303]: https://konghq.atlassian.net/browse/KAG-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(*): prevent queues from growing without bounds (#10046)

.github/workflows/release.yml
Skip login to Docker Hub in GitHub Actions if the author has no access to GitHub Token.
Follow-up PR for https://github.com/Kong/kong/pull/10029.
Fix failing CI: https://github.com/Kong/kong/actions/runs/3835570305/jobs/6528976375
=> chore(release): skip login to docker if no access to github token

kong.conf.default, kong/templates/kong_defaults.lua
Backport of #10070 
Add missing documentation entry in kong.conf.default
KAG-303
=> docs(*): document new max_queued_batches parameter

CHANGELOG.md, kong/plugins/datadog/handler.lua, spec/03-plugins/08-datadog/01-log_spec.lua
fix(plugins/datadog): The log function in datadog is called in batch queue when a batch is scheduled to be processed, and batch queue relys on the return value of the process it holds. The return value of log function in datadog always return nil, this makes batch queue consider the result of processing is failed. In this pr, a return value is added to fix this bug.
FTI-4645
[FTI-4645]: https://konghq.atlassian.net/browse/FTI-4645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(plugins/datadog):  add return value for log function in batch queue

kong/tools/utils.lua
Code clean,  move localized vars into `do end` block
=> style(tools/utils): move localized vars into `do end` block

.github/workflows/build_and_test.yml, CODEOWNERS, kong.conf.default, kong/templates/kong_defaults.lua
- Pin KBT version correctly with `.requirements`
- Revert https://github.com/Kong/kong/commit/58294b45e33ed2490b284870ad9c4b7036255bb1 as it does not intend to be cherry-picked into `3.0.x` branch
- Cherrypick https://github.com/Kong/kong/commit/fae7caa131f3922a6e1425461c0458f9cd319f67
=> chore(ci): pin kbt version (3.0.x branch)

CHANGELOG.md, kong/tracing/instrumentation.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
=> fix(opentelemetry): http.uri should be full path

CHANGELOG.md, kong-3.1.1-0.rockspec, kong/clustering/compat/init.lua, kong/clustering/compat/version.lua, kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/clustering/wrpc_control_plane.lua, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua, kong/templates/nginx_kong.lua, spec/01-unit/19-hybrid/03-compat_spec.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua, spec/02-integration/09-hybrid_mode/03-pki_spec.lua, spec/02-integration/09-hybrid_mode/05-ocsp_spec.lua, spec/02-integration/09-hybrid_mode/08-lazy_export.lua, spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua, spec/fixtures/custom_nginx.template, spec/helpers.lua
Try to restore WebSocket protocol and keep wRPC protocol.
Revert PR #9740, update to PR #9823  #9769 , #9616 #9671 #9774.
This is the cherry-pick of #9921, and didn't remove wRPC protocol.
See KAG-371.
Related PRs: #8926 #8357
* revert PR #9740
* update `control_plane.lua` with new `compat.*`
* change `compat.update_compatible_payload` to fit json+gzip
* add config item `wrpc_hybrid_protocol ` only for test
[KAG-371]: https://konghq.atlassian.net/browse/KAG-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(clustering): restore json websocket protocol (#9921)

CHANGELOG.md
Add changelog for #9925, which appears in 3.1.x but not in master.
=> doc(changelog): bump atc-router to 1.0.2

CHANGELOG.md
Restore the PR link of #9921, which was removed by mistake (#10068).
=> doc(changelog): restore pr link of #9921

CHANGELOG.md, kong/db/schema/entities/routes.lua, kong/db/schema/init.lua, kong/db/schema/metaschema.lua, kong/router/compat.lua, spec/01-unit/01-db/01-schema/01-schema_spec.lua, spec/01-unit/01-db/01-schema/06-routes_spec.lua, spec/01-unit/08-router_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua
=> fix(db): use ATC router for route validation when `router_flavor = traditional_compatible`

autodoc/admin-api/data/admin-api.lua
Reverting changes made in https://github.com/Kong/kong/pull/9990. 
`true` means supported in db-less mode. The original PR got the settings backwards, setting `true` when it should be `false`. 
The `GET` endpoint _is_ true, but this is already covered by the rule on line 2698.
Bug reported to the docs team on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1672965868058589
- ~[ ] The Pull Request has tests~ - Not applicable
- ~[ ] There's an entry in the CHANGELOG~ - Not applicable
N/A
N/A
=> docs(autodocs) Fix db-less badges on log level PUT endpoints

CHANGELOG.md, kong/db/migrations/validate_path_280_300.lua
In c* wrap function we should return `true` if all checks are OK.
See #10092 , KAG-329
=> fix(db/migration): validate c* return correct value 

CHANGELOG.md, kong/plugins/opentelemetry/handler.lua, kong/plugins/opentelemetry/schema.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
=> feat(tracing): route/service scoping

CHANGELOG.md, kong.conf.default, kong/templates/kong_defaults.lua, kong/templates/nginx_kong.lua, spec/02-integration/05-proxy/03-upstream_headers_spec.lua, spec/fixtures/1.2_custom_nginx.template, spec/fixtures/custom_nginx.template
`charset` directive that was previously hard coded in template with a value of `UTF-8` was removed completely with this PR:
https://github.com/Kong/kong/pull/9905
Previous discussion from 3 years ago pointed that this is breaking change (not a fix): https://github.com/Kong/kong/pull/5045
So here is another fix to make the directive still default to `UTF-8`. which is a quite fine default, but allow users to configure it. E.g.:
```
KONG_NGINX_HTTP_CHARSET=off kong start
```
=> fix(template) keep UTF-8 as default for charset directive but make it configurable

kong/runloop/certificate.lua
* localize some functions
* change `new_tab(1, 0)` to `new_tab(0, 1)` in `fetch_ca_certificates`
=> style(core/runloop):  style clean for certificate.lua

CHANGELOG.md, kong/plugins/datadog/handler.lua, kong/plugins/opentelemetry/handler.lua, kong/plugins/statsd/log.lua, spec/03-plugins/06-statsd/01-log_spec.lua, spec/03-plugins/08-datadog/01-log_spec.lua
Cherry-pick the batch queue return value fix to 3.1.x branch.
PRs that have been cherry-picked:
- #10044 
- #10052
=> chore(plugins): cherry pick batch queue return value fix to 3.1.x

kong/router/compat.lua, kong/router/expressions.lua, kong/router/traditional.lua
It will print error logs when users configured the gateway with atc routers and change the flavor to traditional(\_compatible) or verse visa.
Fix FT-3253
=> fix(router): emit error for route flavor misconfig

CHANGELOG.md
move upstream TLS changelog to feature
=> docs(changelog): move upstream tls changelog to feature

Makefile, bin/kong-health, spec/02-integration/02-cmd/07-health_spec.lua
This resty script checks if the Nginx master process needed by Kong is running. It provides the same functionality as `kong health`, but does not start a second Nginx for that. 
* New resty script.
* Adapted current `kong health` tests.
* To do: obsolete `kong health`.
FTI-4452
=> feat(cmd): stand-alone script to check kong health

Makefile
- Add builtin rule set for SILE globals — @alerque
- Implement support for compound operators — @a2 & @arichard4
- Correct circular reference detection visavis OpSet — @arichard4
- Remove unnecessary symbol from Playdate std — @DidierMalenfant
=> chore(deps) bump dev dependency of luacheck from 1.0.0 to 1.1.0

kong/router/atc.lua
In atc-router 1.04, we can pass the routes count param to `new()` function.
See https://github.com/Kong/atc-router/pull/9
=> chore(router/atc): pass routes count to `router.new()`

DEVELOPER.md
pcre is buit by ourselves, so user are not required to install pcre
=> doc(developer): remove pcre requirements from developer doc

CHANGELOG.md, kong/runloop/handler.lua, spec/02-integration/05-proxy/15-upstream-status-header_spec.lua, spec/fixtures/custom_plugins/kong/plugins/response-phase/handler.lua, spec/fixtures/custom_plugins/kong/plugins/response-phase/schema.lua
This causes some of the header handlings to be skipped.
Full changelog:
`runloop.lua`: moving the header phase before and after handlers and changing the way to get status in before handler
`init.lua`: adjust the ordering of handlers and set status (send headers).
Fix #10031
=> fix(core): response phase skips header.before

kong-3.2.0-0.rockspec, kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/init.lua, kong/clustering/tls.lua, kong/clustering/utils.lua, kong/conf_loader/init.lua, spec/02-integration/09-hybrid_mode/03-pki_spec.lua, spec/helpers.lua
This is a backport of refactoring that was performed in [Kong/kong-ee#4375](https://github.com/Kong/kong-ee/pull/4375). I am aware it's far from ideal to merge code in EE first and backport it into OSS, but the refactor was required in order to merge some bugfix code for an EE-specific clustering feature, so here we are. In any case, keep all of this in mind when reviewing, as I'm sure the context will help.
This moves most all of the code that handles certificates for clustering into a new, discrete module: kong.clustering.tls.
- The control_plane and utils modules no longer handle certificate validation--this is done at the root level via the `kong.clustering:validate_client_cert()` function.
- In order to untangle all the tightly-coupled code, call signatures for several functions were …
=> refactor(clustering): reorganize cert validation code

CHANGELOG.md, kong/plugins/opentelemetry/otlp.lua, kong/runloop/handler.lua, kong/tracing/instrumentation.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
According to the opentracing spec, the `http.status_code` attribute is:
> Conditionally Required: If and only if one was received/sent.
Also, the `http.flavor` attribute is supposed to be a string, not a double.
Ref: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md
This change sets `http.status_code` on the root span once it is available (at the beginning of the `header_filter` phase) and also modifies the `http.flavor` attribute type so they both follow the spec.
- <del>[ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE</del>
* Fix(tracing) add http.status_code attribute to root span, if available
FTI-4644 / KAG-463
=> fix(tracing) add http.status_code, fix http.flavor

.github/ISSUE_TEMPLATE/bug_report.yaml
Allow the "steps to reproduce" section to be formatted and previewed as Markdown like the other sections. It's currently not clear how it will be formatted when you're writing an issue. Everything gets put inside a single code fence and I frequently find that I need to reformat it after first submitting an issue.
I don't think that any of these were applicable. I've ticked them to indicate that they aren't "outstanding":
N/A
N/A
=> style(bug_report): Allow reproduce formatting

kong.conf.default
Add missing lmdb configuration options to kong.conf.default
Fix #10109
=> chore(*): lmdb config options in kong.conf.default

kong.conf.default, kong/conf_loader/init.lua, kong/globalpatches.lua, kong/templates/kong_defaults.lua, kong/tracing/instrumentation.lua, spec/02-integration/14-tracing/01-instrumentations_spec.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua, spec/03-plugins/37-opentelemetry/05-otelcol_spec.lua
=> chore(tracing): add alias to global config

CHANGELOG.md, kong/db/schema/entities/keys.lua, kong/db/schema/typedefs.lua, spec/02-integration/04-admin_api/21-admin-api-keys_spec.lua
Improve error message for invalid jwk entries
* Improve error message for invalid jwk entries
=> fix: informative error message for invalid jwk

build/dockerfiles/entrypoint.sh
On some older kernels (below 4.2), executing `ln -sf /dev/stdout /tmp/access.log` multiple times will only work the first time. This is because those kernels have a bug that misleads `openat()` to recognize `/dev/stdout` as a directory, leading to `ln` does not able to overwrite the existing files.
This can lead to that once the container is started, it will continue to fail when restarting afterward due to the docker entrypoint does not execute properly.
Kernel `3.10`:
```
$ uname -a
Linux KONG 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ 
$ docker run -it --privileged ubuntu:22.04 bash
root@03d0dfc6bb90:/# 
root@03d0dfc6bb90:/# ln -s /dev/stdout /tmp/access.log
root@03d0dfc6bb90:/# ln -s /dev/stdout /tmp/access.log
ln: failed to create …
```
=> fix(build/docker): add -n option to avoid ln failing to overwrite the existing symbolic link file

CHANGELOG.md, kong-3.2.0-0.rockspec, kong/clustering/compat/init.lua, kong/clustering/compat/removed_fields.lua, kong/plugins/session/access.lua, kong/plugins/session/daos.lua, kong/plugins/session/handler.lua, kong/plugins/session/header_filter.lua, kong/plugins/session/schema.lua, kong/plugins/session/session.lua, kong/plugins/session/storage/kong.lua, spec/03-plugins/30-session/01-access_spec.lua, spec/03-plugins/30-session/02-kong_storage_adapter_spec.lua
Bumps resty.session session from 3.10 to 4.0.0.
This is huge change as the session library was basically rewritten. The session plugin was modified accordingly.
And the clustering compatibility was added.
=> chore(deps) bump resty.session from 3.10 to 4.0.0

kong.conf.default, kong/conf_loader/init.lua, spec/01-unit/03-conf_loader_spec.lua
These properties were not properly handled in #10122
ref KAG-446
=> fix(conf_loader): deprecate and alias otel properties

build/openresty/patches/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch
See: KAG-474
Core code:
```
upool = lua_newuserdata(L, size); /* pools upool */
items = (ngx_http_lua_balancer_keepalive_item_t *) (&upool->free + 1);
ngx_http_lua_assert((void *) items == ngx_align_ptr(items, NGX_ALIGNMENT));
```
`items` points to the memory that allocated by LuaJIT (lua_newuserdata),
so it may not fit the Nginx's alignment requirement.
=> fix(core): disable C assert in upstream keepalive patch

CHANGELOG.md, kong-3.2.0-0.rockspec
- fix(session): clear_request cookie to check remember_meta correctly before using it
- feat(opm): add more dependencies in requires
- feat(opm): add right version number requirements
- docs(readme): add remark on dependencies on installation section
=> chore(deps): bump resty.session from 4.0.0 to 4.0.1

.github/workflows/build_and_test.yml
This adds broader file inclusion since we now bundle patches in the `build` directory
=> fix(ci): include build directory as build key

build/openresty/patches/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch
=> fix(patches): disable unneeded pointer alignment assertion in dynamic upstream keepalive patch (#10212)

CHANGELOG.md
=> docs(changelog): add missing PR link for #9904

BUILD.bazel, bin/busted
This patch remove watch of dangeling local files so that bazel memory usage can remain small.
This patch also makes `bin/busted` be able to run with `resty-cli` with args. Consider this
```
/path/to/resty -I lualib_path --nginx nginx_path bin/busted x
```
the current logic will be broken because arg will be
```
{
[-5] = "/path/to/resty",
[0] = "bin/busted",
[1] = "x",
}
```
In this patch, `$0` (resty-cli path) is not read from `arg[-1]` but using `/usr/bin/env resty` instead.
* [fix(busted): allow busted to be called with resty with extra args](https://github.com/Kong/kong/commit/973f2674efe6424b1a9628fe46944dcd3a49776c)
* [chore(build): reduce memory usage by removing unused filegroup](https://github.com/Kong/kong/commit/25bf4ecf6bfddcd115c16d432c7565abfd11f76e)
=> fix(*): reduce bazel memory usage on messy local state and fix bin/busted

CHANGELOG.md, kong.conf.default, kong/conf_loader/init.lua, kong/plugins/datadog/handler.lua, kong/plugins/http-log/handler.lua, kong/plugins/opentelemetry/handler.lua, kong/plugins/statsd/log.lua, kong/templates/kong_defaults.lua, kong/tools/batch_queue.lua, spec/01-unit/27-batch_queue_spec.lua
This commit implements an upper limit on the number of batches that may be waiting on a queue for processing.  Once the limit has been reached, the oldest batch is dropped from the queue and an error message is logged.  The maximum number of batches that can be waiting on a queue is configured through the max_queued_batches parameter of the queue, which defaults to 100 and can be globally overriden with the max_queued_batches parameter in kong.conf
A more complete rewrite of the queuing system is in the works but will not make it into 3.2.
KAG-303
This reverts commit 218cc0a81500986b0b94e6b4e350302326097018 and fffb4e8626ba9ec99194cd3d9f9cd15e19c72c61
=> fix(*): prevent queues from growing without bounds

CHANGELOG.md, kong.conf.default, kong/conf_loader/init.lua, kong/plugins/datadog/handler.lua, kong/plugins/http-log/handler.lua, kong/plugins/opentelemetry/handler.lua, kong/plugins/statsd/log.lua, kong/templates/kong_defaults.lua, kong/tools/batch_queue.lua, spec/01-unit/27-batch_queue_spec.lua
Backport 94a31c6471f5a52e22968e88f522135213233324 from #10247.
=> [Backport release/3.2.x] fix(*): prevent queues from growing without bounds

kong.conf.default, kong/conf_loader/init.lua, spec/01-unit/03-conf_loader_spec.lua
Backport ef25a10e78f0db517c3df0326c35f53f63d2ad99 from #10220.
=> [Backport release/3.2.x] fix(conf_loader): deprecate and alias otel properties

CHANGELOG.md
* move #9603 from fixes to the additions section
* move #9904 to the first part of the changed section
=> docs(changelog): move some entries to the right place

CHANGELOG.md
In PR #10230，we bumped resty.session to 4.0.1.
=> docs(changelog): resty.session now is 4.0.1

CHANGELOG.md, kong-3.2.0-0.rockspec
Backport 3828b1f79c5c7aa5b353bc80e3798a15a9888101 from #10265.
=> [Backport release/3.2.x] chore(deps): bump resty.timerng from 0.2.0 to 0.2.3

kong/pdk/log.lua
* Line 607, `options or {}` is redundant
* Line 283 `not sys_log_level` is true forever, removed.
* The two `serialize` functions have got many same codes. Extracted them to `prepare_serialize` function
=> refactor(pdk/log): removal and extraction of redundant code

kong.conf.default, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua, kong/tools/batch_queue.lua
- Make the default for the maximum number of batches queued in a plugin queue large to accommodate large installations.  
- Remove the global kong.conf parameter that allows the maximum number of batches to be set
- Add an undocumented, last-resort environment variable KONG_MAX_QUEUED_BATCHES that can be used to override the global default.
We don't want to expose a global configuration option for the queue limit to prevent us from having to support it in the future.  The queue system will be completely reworked in 3.2, hence this band-aid is only there as a bridge.
EE PR: https://github.com/Kong/kong-ee/pull/4541
KAG-303
=> Increase maximum queue size and remove global configuration parameter

DEVELOPER.md
When building Kong from source, if we choose to build atc-router, then we need the rust dependency.
=> docs(DEVELOPER): add rust dependencies for build atc-router

kong.conf.default, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua, kong/tools/batch_queue.lua
Backport 989b23e4af138162cf1109c6b5f37d79084a5bc1 from #10271.
=> [Backport release/3.2.x] Increase maximum queue size and remove global configuration parameter

.github/workflows/release.yml
This change ultimately resolves a build failure when bazel goes to build openresty on RHEL-7/CentOS-7:
```
checking for zlib library ... not found
./configure: error: the HTTP gzip module requires the zlib library.
You can either disable the module by using --without-http_gzip_module
option, or install the zlib library into the system, or build the zlib library
statically from the source with nginx by using --with-zlib=<path> option.
ERROR: failed to run command: sh ./configure --prefix=/github/home/.cache/bazel/_bazel_root/9817ab78a41c88bbf8d96f8d6b963143/execroot/kong/bazel-out/k8-fastbuild/bin/external/openresty/openresty.build_tmpdir/openresty/nginx \...
```
The hope is that this change will be merged to release/3.2.x, then next/3.2.x.x in EE.
=> fix(gha): ensure zlib installed for centos/rhel-7

CHANGELOG.md
=> docs(changelog): fix otle PR link 

kong/clustering/data_plane.lua, kong/clustering/init.lua
In DP's `init_worker()` we start two zero-delayed timers, it is unnecessary.
* simplify `ngx.timer.at` calls
* simplify check of `is_dp_worker_process`
=> refactor(clustering): simplify dp init_worker logic

.github/matrix-commitly.yml, .github/matrix-full.yml, .github/workflows/release.yml
1. Remove unwanted dependency of container scanning on releasing packages
2. Maintain a separate matrix for the vulnerabilities scan
=> fix(cd): remove container scan dependency

kong/cmd/utils/prefix_handler.lua
Some log lines are missing the "%s" formatter.
FTI-4801
=> fix(cmd): log format errors

CHANGELOG.md, kong-3.2.0-0.rockspec
- fix(*): hkdf is not approved by FIPS, use PBKDF2 instead on FIPS-mode
=> chore(deps) bump resty.session from 4.0.1 to 4.0.2

CHANGELOG.md, kong-3.2.0-0.rockspec
- fix(*): hkdf is not approved by FIPS, use PBKDF2 instead on FIPS-mode
=> chore(deps) bump resty.session from 4.0.1 to 4.0.2 (#10308)

CHANGELOG.md
Add a note to highlight the new default value of the parameter: `idling_timeout`
(cherry pick of https://github.com/Kong/kong/pull/10312)
~The Pull Request has tests~
~There's an entry in the CHANGELOG~
~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com~
FTI-4827
=> chore(changelog): session breaking changes

CHANGELOG.md
(cherry picked from commit ee74ed9532e372898f8473598d2ab17f960e9d79)
There's an additional entry in here for #9904 that is also missing from the 3.2 release branch.
=> docs(changelog): add entry for renamed kong.conf properties (#10310)

spec/fixtures/custom_nginx.template, spec/helpers.lua
This is just a test fixture. So, tests for data plane can make use of `mock_upstream`.
1. `control_plane` still uses port `15555/15556`.
2. `data_plane` uses a designated *new* port `16665/16666`. So, in `data_plane`, we set up mock upstream. 
For example, the RLA tests current we have to use `httpbin.org`, which makes tests flaky. Check <https://github.com/Kong/kong-ee/blob/master/plugins-ee/rate-limiting-advanced/spec/03-access_spec.lua#L1894>.
FTI-4782
=> chore(*): extend fixture `mock_upstream` to data plane (FTI-4782)

kong/cmd/utils/prefix_handler.lua
Log line isn't correctly formatted.
FTI-4801
=> fix(cmd): log format error

.github/workflows/release.yml
This PR pivots the docker hub re-tagging portions of the release github action to utilize `regctl image copy` instead of plain ole' `docker pull`.
The `docker pull` approach lacked support for multi-architecture builds, result in only `amd64` image tags being added to unofficial/official repos.
Sister PR to: https://github.com/Kong/kong-ee/pull/4624
=> fix(gha): use regctl for (multiarch) image copy

CHANGELOG.md, kong-3.2.0-0.rockspec
Fixes Redis (non-cluster/sentinel) authentication.
=> chore(deps) bump resty.session to 4.0.3

CHANGELOG.md, kong-3.2.0-0.rockspec
Fixes Redis (non-cluster/sentinel) authentication.
=> chore(deps): bump resty.session from 4.0.2 to 4.0.3(back-port)

CHANGELOG.md, kong/clustering/compat/removed_fields.lua
For 3.2, we added `aws_imds_protocol_version` for `aws_lambda` plugin, and `aws_imds_protocol_version` for `zipkin` plugin, but we did not add corresponding `removed_fields` entries.
The Pull Request has tests -- N/A, we removed tests to `removed_fileds` as it does not mean much but causes flakiness.
There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com -- N/A, it's a bug fix
Fix KAG-725
=> fix(plugin): compat issue for config sync

CHANGELOG.md, kong/clustering/compat/removed_fields.lua
Backport 2a23672d9e9e1083f219123e7318d838e180bbc7 from #10346.
=> [Backport release/3.2.x] fix(plugin): compat issue for config sync

CHANGELOG.md, kong/clustering/compat/init.lua, spec/01-unit/19-hybrid/03-compat_spec.lua
for older DPs, session "renamed" fields were just copied, this fixes it by removing the old field from the configuration
[KAG-738](https://konghq.atlassian.net/browse/KAG-738)
[KAG-738]: https://konghq.atlassian.net/browse/KAG-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(clustering): session renamed fields

kong/plugins/key-auth/handler.lua, spec/03-plugins/09-key-auth/02-access_spec.lua
Currently the key-auth plugin returns HTTP 500 (Internal Server Error) status code if the api key includes non-ascii symbols. This is not appropriate .This updates the key-auth plugin to send HTTP 401 (Unauthorized) status code on such cases.
* return 401 when the api key includes non-ascii symbols
* add a new test case in key-auth plugin
Fix #5627
Currently the key-auth plugin returns HTTP 500 (Internal Server Error) status code if the api key includes non-ascii symbols. This is not appropriate .This updates the key-auth plugin to send HTTP 401 (Unauthorized) status code on such cases.
Fix #5627
=> fix(key-auth): return unauthorized if api key includes symbols that are not allowed

.github/labeler.yml
This commit updates the CI configuration to add the "schema-change-noteworthy" label for every PR that touches any schema.lua file. This helps communicate schema changes in Kong to downstream projects like Konnect, decK, KIC, Kong Manager track each and every schema change and adapt accordingly.
=> chore(ci) add schema-change-noteworthy label for any schema.lua file change

CHANGELOG.md, kong/plugins/opentelemetry/handler.lua, kong/plugins/opentelemetry/otlp.lua, spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
We represent trace spans with a universal format for all kinds of mainstream tracers and translate them to different formats when propagating headers and exporting traces. However, OTEL misses the handling of trace ID length.
N/A There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
Fix KAG-652
=> fix(plugin): OTEL exporting with translate

CHANGELOG.md, kong/db/declarative/init.lua, kong/db/declarative/migrations/route_path.lua, spec/01-unit/01-db/01-schema/11-declarative_config/04-on-the-fly-migration_spec.lua, spec/02-integration/02-cmd/11-config_spec.lua
We choose to only handle nesting in top-level services.
N/A There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
Fix KAG-638
=> fix(db/migration): do migration before validation

kong-3.2.1-0.rockspec, kong/meta.lua
Backport f24fbd8288f5bde0962d9c36fa827d9a9d19160a from #10345.
=> feat(meta): bump to 3.2.1

.github/workflows/release.yml
Performing this comparison actually turns a "true" string into a false. We already check for a string when consuming this environment variable so there is no need to perform it here.
Without this change, releasing packages causes them to only end up in the internal channels.
=> chore(release): Boolean variables are passed as strings by Github Actions

.github/workflows/release.yml
Backport 999f5bea44aa3092b61541a40adf1be81c6490b9 from #10343.
=> [Backport release/3.2.x] chore(release): Boolean variables are passed as strings by Github Actions

build/repositories.bzl
`uname -m` on my intel mac laptop is detected in bazel as `x86_64` and not `amd64`.
```bash
$ uname -m
x86_64
$ sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
```
mirror of: https://github.com/Kong/kong-ee/pull/4402
=> fix(bazel): fix intel detection

.github/workflows/release.yml
This needed to have been ported from EE -> CE (which we don't have a formal process for).
In EE, it's a fix that got applied along my arm64 Amazon Linux work.
CE also needs this fix.
Without this fix, arm64 package files are erroneously uploaded with "amd64" in the filename-- sometimes overwriting previously uploaded (legitimate amd64) packages.
=> fix(gha): Set Package Architecture when Uploading to Pulp

.github/workflows/release.yml
* fix(gha): set package arch for upload
* Update .github/workflows/release.yml
Co-authored-by: Tyler Ball <2481463+tyler-ball@users.noreply.github.com>
---------
Co-authored-by: Tyler Ball <2481463+tyler-ball@users.noreply.github.com>
(cherry picked from commit 35c4b7a22d266262e4165fa9869a73c21202c677)
Manual backport of https://github.com/Kong/kong/pull/10339
=> fix(gha): Set Package Architecture when Uploading to Pulp (#10339)

kong/plugins/key-auth/handler.lua, spec/03-plugins/09-key-auth/02-access_spec.lua
This reverts commit d10101955bc554e9e453d5968392babbdf1bf4f9 (#10171).
The fix is too restrictive on the key syntax due to a misunderstanding on my end.  Before reimplementing, we need a reproduction case that demonstrates the problem, as we may need to fix the issue at another level.
https://konghq.atlassian.net/browse/KAG-721
=> Revert "fix(key-auth): return unauthorized if api key includes non-ascii symbols (#10171)"

build/kong_bindings.bzl
Cherry-picking EE fix for adding rpm signing related env var into repository rule environ list
Fix KAG-744
=> fix(build): add rpm signing related env var into repository rule environ list (#4647)

kong/cmd/utils/kill.lua, spec/02-integration/02-cmd/12-hybrid_spec.lua
This PR fixes the following flaky test:
```
__________
FAILED  spec/02-integration/02-cmd/12-hybrid_spec.lua:141: kong hybrid with #cassandra backend quits gracefully
spec/02-integration/02-cmd/12-hybrid_spec.lua:150: Expected objects to be equal.
Passed in:
(string) 'cat: /home/runner/work/kong/kong/servroot2/pids/nginx.pid: No such file or directory
'
Expected:
(string) ''
spec/02-integration/02-cmd/12-hybrid_spec.lua:150: in function <spec/02-integration/02-cmd/12-hybrid_spec.lua:141>
```
If the inner command substitution failed with a "file not found", the
error would be reported, even though the outer command has a
redirection. This happens because the substitution is evaluated first,
and the outer redirection does not apply to it. This fixes a flakiness
in the …
=> tests(helpers) fix flaky hybrid mode test

kong/clustering/compat/removed_fields.lua, kong/plugins/acme/client.lua, kong/plugins/acme/schema.lua, spec/03-plugins/29-acme/01-client_spec.lua, spec/03-plugins/29-acme/04-schema_spec.lua
There is currently no way to configure an existing private key to be used for the acme plugin. If the account does not have a key in storage, then a new one is created. This is a problem when external account binding credentials have already been associated with a key elsewhere (e.g. cert-manager or cert-bot). Some issuers like ZeroSSL allow for EAB credentials to be reused and multiple accounts can be created with different private keys. Others like GCP Public CA only allow for EAB credentials to be associated with one key so when the plugin tries to create a new account with a new key it fails.
The current workaround for this has been to manually insert the key in storage so a new key is not created.
This PR exposes `account_key` and will use that if the account was not found in storage …
=> feat(acme): make account_key configurable

.github/labeler.yml
This patch updates the labeler configuration to track schema changes for Enterprise code as part of the public open-source code.
=> chore(ci) track enterprise schema changes

kong/runloop/balancer/balancers.lua, kong/runloop/balancer/targets.lua, kong/runloop/balancer/upstreams.lua
The target's global cache was caching more data than it should: it kept data retrieved from the database and DNS name resolution, which has its own cache.
As a result, when config reloads were done, some processes were skipped (such as setting the upstream as healthy) because the load-balancer never identified the data as new if it was the same as cached (highly probable with DNS name resolution).
This change makes the target cache local to the worker. 
* Make the target cache local to the worker.
* This PR has no tests. This is a race condition, almost impossible to automate. 
FTI-3172
Fix #8517
Fix #10020
=> fix(balancer) use local target cache

CHANGELOG.md
`Dependencies` should be the last one.
=> docs(changelog): move `dependencies` section to the correct place

CHANGELOG.md, kong/db/strategies/postgres/connector.lua
PR #10389 and #10331 pursued different ways to improve our situation with cleanup timers.
This PR makes it so that it only happens on nodes that have admin listeners. Fairly simple but may already cover the majority of problem space.
=> chore(db): only enable posgres cleanup timer on nodes that have admin listeners

.github/workflows/label-check.yml
With this patch, CI will notify a Kong Inc internal slack channel on every PR that performs a schema change.
=> chore(ci) notify slack on PRs performing schema changes

.github/workflows/label-check.yml, .github/workflows/label-schema.yml
It seems that if the do not merge label job is skipped then the second job doesn't run either:
https://github.com/Kong/kong/actions/runs/4307151445/jobs/7511859202
This change splits the job into two and narrows down the events on which these jobs are triggered since the only meaninful input are the labels on the PR.
<!--- Why is this change required? What problem does it solve? --
=> chore: split schema change job

.github/workflows/release.yml
rustup/cargo are not exposed to PATH since bazel manages its own rust toolchain.
Fixes failures at https://github.com/Kong/kong/actions/runs/4309201395
=> fix(cd): remove detection of unused tools

build/repositories.bzl
Backport 50e8ba2df5c6134407fef034b4b170316cf239ab from #10322.
=> [Backport release/3.2.x] fix(bazel): fix intel detection

CHANGELOG.md, kong-3.2.1-0.rockspec, kong/plugins/grpc-gateway/deco.lua, kong/runloop/plugin_servers/pb_rpc.lua, kong/tools/grpc.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
Bump `lua-protobuf` from `0.3.3` to `0.4.2`.
It has been confirmed that the `lua-protobuf` under version 0.4.2 causes the Segmentation fault(core dump) while used with `lpeg`. The issue was found in another PR(https://github.com/Kong/kong/pull/10055).
Here is the proof in the core dump file on GitHub action runner.
<details>
<summary>Backtrace from the core dump</summary>
```
gdb /home/runner/work/kong/kong/bazel-bin/build/kong-dev/openresty/nginx/sbin/nginx /tmp/cores/core.nginx.30260
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1                                                                                                                                                                                                                  │····
Copyright (C) 2022 Free Software Foundation, Inc. …
```
=> chore(deps): bump lua-protobuf to 0.4.2

kong.conf.default, kong/conf_loader/init.lua, kong/templates/kong_defaults.lua, kong/templates/nginx.lua, spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/03-plugins/38-proxy-wasm/02-filters_spec.lua, spec/fixtures/custom_nginx.template
Load WASM filters from configured path.
- load wasm filters from configured path.
- do not expect individual files.
- added new directive to template.
KAG-500
=> feat(conf_loader): load all WASM filters from conf path

kong-3.2.1-0.rockspec
* fix(logs): fix too many NOTICE logs when creating a timer by @ADD-SP in https://github.com/Kong/lua-resty-timer-ng/pull/13
**Full Changelog**: https://github.com/Kong/lua-resty-timer-ng/compare/0.2.3...0.2.4
=> chore(rockspec): bump `lua-resty-timer-ng` from 0.2.3 to 0.2.4

CHANGELOG.md, kong.conf.default, kong/conf_loader/init.lua, kong/error_handlers.lua, kong/pdk/response.lua, kong/templates/kong_defaults.lua, kong/tools/utils.lua, spec/02-integration/05-proxy/12-error_default_type_spec.lua, spec/fixtures/error_templates/error_template.html, spec/fixtures/error_templates/error_template.json, spec/fixtures/error_templates/error_template.plain, spec/fixtures/error_templates/error_template.xml, t/01-pdk/08-response/13-error.t
Allow customizing error templates via kong.configuration parameters
Fix #7093
[KAG-723](https://konghq.atlassian.net/browse/KAG-723)
[KAG-751]
[KAG-751]: https://konghq.atlassian.net/browse/KAG-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KAG-723]: https://konghq.atlassian.net/browse/KAG-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(proxy): error templates customization

CHANGELOG.md, kong/db/strategies/postgres/connector.lua, spec/02-integration/03-db/20-ttl-cleanup_spec.lua
The PR #10405 changed cleanup to only happen on nodes that have Admin API listeners.
This PR makes deletion to happen in maximum of 50,000 row batches.
Inspired from #10331 and #10389.
=> feat(db): batch cleanup expired rows from postgres

build/cross_deps/zlib/repositories.bzl
This PR will mean that when the current version of zlib gets moved into the site's "fossils" repo, we won't have a broken build.
=> fix(bazel): add alt url for older zlib releases

.github/workflows/label-check.yml
This is a bad practice which could cause merge conflicts and is against our backport policy.
Tested and works:
=> chore(actions): do not allow "backport master" labels

.editorconfig, bin/busted, bin/kong, bin/kong-health
This adds vim [modelines](https://vim.fandom.com/wiki/Modeline_magic) to our lua scripts in bin/ to identify their filetypes and set the proper indentation settings.
I wish this could be done without cluttering up files with comment strings, but .editorconfig does not have any notion of "treat this file as $filetype." I have updated .editorconfig with the proper settings for these files, however.
=> chore(development): add vim modelines to bin/*

.github/workflows/label-check.yml, .github/workflows/label-schema.yml
It seems that Github Actions is not running these jobs even once even though the PRs are labelled at least once. This patch runs these jobs on other related PR activity.
=> chore: run label based jobs on other events

CHANGELOG.md, build/openresty/patches/lua-resty-core-0.1.23_02-dyn_upstream_keepalive.patch, build/openresty/patches/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch, spec/02-integration/05-proxy/25-upstream_keepalive_spec.lua
See issue #9582,
Related PR: https://github.com/Kong/kong-build-tools/pull/619
Ticket: KAG-294
* add lua-rest-core and ngx-lua patch in `build/openresty/patches`
* check debug log to verify keepalive
* add reusing connection test case
* add crc32 collision test case
Fix #_[9582]_
=> fix(core): dyn upstream keepalive
