Kong/kong

spec/02-integration/13-vaults/01-vault_spec.lua, spec/02-integration/13-vaults/02-env_vault_spec.lua
* add separate tests for env vault
* add tests to verify that we do not leak confidential information via the admin api
=> tests(vaults): add env vault tests

autodoc/admin-api/data/admin-api.lua, autodoc/admin-api/generate.lua, autodoc/admin-api/openapi-gen.lua
Adds "autogen" docs to vault_beta entity.
=> docs(admin) add docs for vault_beta entity

kong/db/schema/init.lua
See the code, it is obvious bug.
=> hotfix(schema) fix dereferencing array and set values

kong/clustering/control_plane.lua
localize string.sub in checking timeout err
* localize string.sub
=> chore(cluster) localize string.sub

CHANGELOG.md
Signed-off-by: Andrew Kew <andrewkew@gmail.com>
Spelling mistake in changelog
* Spelling mistake in changelog
=> docs(changelog) fix typo on contributor name

CHANGELOG.md
Add missing fix entry in for #8142
Related: 
- #8499
FT-2454
=> docs(changelog) add missing entry for #8142

CHANGELOG.md
Add the missing fix entry for #8141
Cherry-pick it to the 2.7 branch when approved.
FT-2454
=> docs(changelog) add missing fix entry for #8141

CHANGELOG.md
Sync up 2.7.0 changelog with master branch.
=> docs(changelog) sync up 2.7.0 changelog with master branch

CHANGELOG.md
=> docs(changelog) add entry for #8161

CHANGELOG.md
Update changelog.
cherry-pick
- https://github.com/Kong/kong/pull/8504/commits/0d973e2a79c513e37c3113d3a5d052576aa43ef4
- #8509
=> docs(changelog) sync up-to-date

autodoc/admin-api/generate.lua
Related with https://github.com/Kong/docs.konghq.com/pull/3684
=> docs(autodocs) fix admin api autodoc error when endpoint is set to false

.devcontainer/Dockerfile
=> chore(devcontainer) bump docker image version

CHANGELOG.md
Add content about [#8483](https://github.com/Kong/kong/pull/8483) .
* update file `CHANGLOG.md`
=> docs(CHANGELOG.md) add content about #8483

.github/labeler.yml
Fix serverless functions labeler.
=> chore(labeler) fix serverless-functions

kong/plugins/acl/schema.lua, kong/plugins/bot-detection/schema.lua, kong/plugins/ip-restriction/schema.lua
Remove deprecated blacklists / whitelist etc. config fields from bot-detection, ip-restriction and ACL
FT-2557
=> fix(*) remove blacklist/whitelist from schema

kong/plugins/aws-lambda/handler.lua, kong/plugins/aws-lambda/schema.lua
Aws-lambda will drop the proxy_scheme property
FT-2557
=> fix(aws-lambda) remove proxy_schema field

CHANGELOG.md
Add changelog entry for
- #8558
=> docs(changelog) add entry for #8558

kong/runloop/handler.lua
This has started to show up in flamegraphs, so I decided to optimize it out.
=> perf(proxy) reduce calls to csv function in common cases

kong/plugins/jwt/handler.lua
This [commit](https://github.com/andreleoni/kong/commit/31eb7f75860bae6387cd148312eb0059d4772daa#diff-491e6842b51ea5e9e8c9fdf51ea3b9826c92abb0104f4574d33e769c01f8d23eR28) removed the first method argument, so, the comment was not adjusted.
This request only remove a not usefull comment.
=> style(jwt-plugin) remove unusefull comment

.github/workflows/build_and_test.yml, kong/db/init.lua, kong/plugins/oauth2/access.lua, spec/01-unit/09-balancer/02-least_connections_spec.lua, spec/fixtures/balancer_utils.lua
=> chore(*) fix linter

CHANGELOG.md
=> fix(doc) duplicate and incorrect level title

kong/plugins/ldap-auth/asn1.lua, kong/plugins/ldap-auth/ldap.lua
Replace asn1 parser/decoder with openssl ffi based functions.
FT-2621
=> refactor(ldap-auth) openssl ffi based asn1 parser/decoder

Jenkinsfile
related: [5044d44](https://github.com/Kong/kong-ee/pull/3093/commits/5044d44191bf97ea5b99001e07d86138843a12a2)
The Jenkins release logic currently in PR for kong-ee is much cleaner. Let's use it here as well
=> chore(release): cleanup the Jenkins release logic

kong/tools/grpc.lua
Small optimization for grpc.lua
* localize some functions
* localize date.epoch()
=> chore(tools) small optimization for grpc

kong/clustering/control_plane.lua
=> chore(clustering) log `push_config` duration

CHANGELOG.md
Not sure which section this belongs in. It's kind of a fix and kind of a generic change.
=> docs(changelog) add entry for stream API rewrite

kong/plugins/http-log/handler.lua
change was in https://github.com/Kong/kong/pull/6992
=> chore(httplog) bump version for breaking change

scripts/validate-rockspec
1. Add `luacheck` linting to catch small problems that `luarocks lint` doesn't care about
2. Roll-up errors in `check_modules()` instead of failing early
=> tests(rockspec) improve validation script

kong/api/routes/kong.lua
fixes issues created by https://github.com/Kong/kong/pull/8821
=> fix(api) metadata represent infinity and non-numbers

spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
=> tests(healthchecks) fix flaky 401 test

kong/clustering/control_plane.lua, kong/clustering/data_plane.lua, kong/clustering/utils.lua, kong/clustering/version_negotiation/init.lua, kong/tools/grpc.lua
=> chore(cluster) code clean

spec/03-plugins/09-key-auth/02-access_spec.lua
=> tests(plugin/key-auth) fix a flaky test

CHANGELOG.md
=> docs(changelog) correct the config cache deprecation docs

Jenkinsfile, Makefile
Most of this cruft is old bintray related logic. Remove it by stealing some improvements that are a part of https://github.com/Kong/kong-ee/pull/3093
=> fix(release): remove bintray release logic

.github/labeler.yml
=> chore(labeler) add `core/tracing`

spec/03-plugins/37-opentelemetry/04-exporter_spec.lua, spec/helpers.lua
=> tests(otel) add timeout for http server

kong/clustering/wrpc_control_plane.lua, kong/clustering/wrpc_data_plane.lua, kong/include/kong/services/config/v1/config.proto, kong/tools/wrpc/future.lua, kong/tools/wrpc/message.lua
Fix FT-2965
Please merge this after: https://github.com/Kong/kong/pull/8883
=> refactor(wrpc) simplify config sync

spec/03-plugins/26-prometheus/04-status_api_spec.lua
I've had this test suite fail in CI before when the http client's keepalive connection gets closed:
```
ERROR spec/03-plugins/26-prometheus/04-status_api_spec.lua:389: Plugin: prometheus (access via status API) remove metrics from deleted upstreams
spec/03-plugins/26-prometheus/04-status_api_spec.lua:398: spec/03-plugins/26-prometheus/04-status_api_spec.lua:399: closed
./spec/helpers.lua:1369: in function 'wait_until'
spec/03-plugins/26-prometheus/04-status_api_spec.lua:398: in function <spec/03-plugins/26-prometheus/04-status_api_spec.lua:389>
```
This change attempts to make the tests more reliable by re-opening the connection when this condition is encountered.
=> tests(prometheus) retry GET /metrics on closed conn

kong/cache/init.lua
The `LMDB` removed the need for cache pages. This commit removes pages support from the cache.
=> chore(cache) remove pages and flip

kong/runloop/handler.lua
Something went wrong with `lmdb` merge, and it seems like we now stop health checkers even when the balancer is not being re-build.
The other issue was that when `flip_config` was renamed to `reconfigure`, not everything was renamed accordingly to this name change, this fixes that too.
=> fix(handler) do not stop health checkers on reconfigure if not needed

DEVELOPER.md
=> docs(*) clean up developer.md

kong/db/declarative/init.lua, kong/init.lua
The reconfigure event needs to pass hashes and not only the default workspace. This broke when PR #8519 was merged and then `LMDB` PR #8224 got merged after it (and I think merge conflicts were not correctly resolved).
=> fix(clustering) conditional rebuilding broke stream reconfigure

spec/02-integration/03-db/09-query-semaphore_spec.lua, spec/02-integration/03-db/11-postgres-ro_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/03-plugins/23-rate-limiting/04-access_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua, spec/helpers.lua
* tests(*) remove function `wait_timers_*` and add function `wait_timer` to `spec/helpers.lua`
* tests(*) fix `spec/02-integration/03-db/09-query-semaphore_spec.lua`
* tests(*) fix `spec/03-plugins/23-rate-limiting/04-access_spec.lua`
* tests(*) fix `spec/03-plugins/34-zipkin/zipkin_spec.lua`
* tests(*) fix `spec/02-integration/05-proxy/02-router_spec.lua`
* tests(*) fix `spec/02-integration/03-db/11-postgres-ro_spec.lua`
=> tests(*) fix some flaky tests

kong/plugins/opentelemetry/handler.lua, kong/plugins/opentelemetry/schema.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua
replace array type header values with single string value,
align with http-log plugin, ref: https://github.com/Kong/kong/pull/6992
=> fix(otel) set headers with single value, not array

autodoc/admin-api/data/admin-api.lua
add missing endpoint for autudoc
=> fix(docs) add missing endpoint for autodoc

.github/workflows/perf.yml, spec/04-perf/01-rps/01-simple_spec.lua, spec/04-perf/01-rps/02-balancer_spec.lua, spec/04-perf/01-rps/03-plugin_iterator_spec.lua, spec/04-perf/01-rps/04-simple_hybrid_spec.lua, spec/04-perf/02-flamegraph/01-simple_spec.lua, spec/04-perf/02-flamegraph/03-plugin_iterator_spec.lua, spec/04-perf/99-teardown/01-teardown_spec.lua, spec/helpers/perf.lua, spec/helpers/perf/charts.lua, spec/helpers/perf/drivers/docker.lua, spec/helpers/perf/drivers/local.lua, spec/helpers/perf/drivers/terraform.lua, spec/helpers/perf/utils.lua
Also cherry-picked some commits from EE.
=> tests(perf) add option to use daily image for docker and terraform

spec/01-unit/09-balancer/04-round_robin_spec.lua
remove duplicated tests
duplicated: 
1: https://github.com/Kong/kong/blob/9c71b29d586503d91db1e12edab9ece7c5f555f7/spec/01-unit/09-balancer/04-round_robin_spec.lua#L496-L524
2: https://github.com/Kong/kong/blob/9c71b29d586503d91db1e12edab9ece7c5f555f7/spec/01-unit/09-balancer/04-round_robin_spec.lua#L525-L553
=> tests(balancer) remove duplicated tests

CHANGELOG.md
Add changes of wRPC to change logs.
=> chore(docs) add wrpc to change logs

kong/pdk/tracing.lua, kong/tracing/instrumentation.lua
Localize functions and cache the ngx.ctx calls in tracing/instrumentation.
=> perf(tracing) localize functions and cache the ngx.ctx calls

kong/clustering/init.lua, kong/init.lua, kong/templates/nginx_kong.lua
and emit a warning
Fix FT-3077
=> feat(clustering) switch turn off wRPC also from CP

kong/templates/nginx_kong.lua
Fix the bug found here: https://github.com/Kong/kong/pull/9071#discussion_r917566279
=> fix(clustering) fail to listen to wrpc port

spec/helpers.lua
=> tests(helpers) fix function `wait_timer`

kong/db/migrations/core/016_280_to_300.lua
Addressing problem found here: https://github.com/Kong/kong/pull/9081#pullrequestreview-1035469413
=> fix(core) migration null handling of C*

Jenkinsfile
Continuation of https://github.com/Kong/kong/pull/9098
[My test build](https://internal.builds.konghq.com/blue/organizations/jenkins/kong/detail/fix%2Fmaster-builds/5/pipeline/31)
=> fix(release): be more explicit about building and pushing the master branch builds

spec/helpers.lua
add comments for new options in `http_serrver`
ref: https://github.com/Kong/kong/commit/69be3765d66d3d6ed1f2c2b4b5edd75231cbcb97#diff-5ef8552b54a226fa973a6c33644d117aba05c008e8e60efcc8508629eed713afR1202
=> tests(spec/helpers) add comments for new options in `http_serrver`

Jenkinsfile
alpine image is pushing successfully but Ubuntu is not -- regardless let's login just to be certain
test run visible [here](https://internal.builds.konghq.com/blue/organizations/jenkins/kong/detail/fix%2Fci-dockerhub/1/pipeline)
=> fix(ci): docker hub refs: #FT-3141

kong/globalpatches.lua
=> style(*) simplify code for timer initialization

kong/pdk/request.lua
There is a localized `ngx.var` but we did not use it wisely,
so I cleaned some code.
* use localized `ngx.var`
* use localized `ngx.req`
=> chore(pdk) localize ngx.var/ngx.req

kong/router/traditional.lua
Sync up with atc router changes. See #9096.
=> chore(router) small code clean

kong/plugins/prometheus/handler.lua, kong/plugins/prometheus/schema.lua, spec/03-plugins/26-prometheus/02-access_spec.lua, spec/03-plugins/26-prometheus/03-custom-serve_spec.lua, spec/03-plugins/26-prometheus/04-status_api_spec.lua, spec/03-plugins/26-prometheus/05-metrics_spec.lua
- fix(plugins/prometheus) fix typo of latency
=> fix(plugins/prometheus) fix typo of `latency`

kong/clustering/wrpc_control_plane.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/03-plugins/37-opentelemetry/01-otlp_spec.lua, spec/03-plugins/37-opentelemetry/04-exporter_spec.lua, spec/helpers.lua
=> tests(clustering) error handling for DP plugins diff

spec/helpers.lua
=> docs(helpers) add docs for function `wait_timer`

.github/workflows/upgrade-tests.yml, .gitignore, .luacheckrc, CHANGELOG.md, DEVELOPER.md, kong/cmd/migrations.lua, kong/db/migrations/core/016_280_to_300.lua, kong/db/schema/others/migrations.lua, kong/plugins/pre-function/migrations/_001_280_to_300.lua, scripts/test-upgrade-path.sh, spec/01-unit/01-db/01-schema/10-migrations_spec.lua, spec/05-migration/db/migrations/core/016_280_to_300_spec.lua, spec/05-migration/plugins/acme/migrations/001_280_to_300_spec.lua, spec/05-migration/plugins/http-log/migrations/001_280_to_300_spec.lua, spec/05-migration/plugins/post-function/migrations/001_280_to_300_spec.lua, spec/05-migration/plugins/pre-function/migrations/001_280_to_300_spec.lua, spec/helpers.lua, spec/upgrade_helpers.lua
This PR adds a new mechanism to test migrations.  Documentation has been added to DEVELOPER.md.
=> Upgrade tests

CHANGELOG.md
We missed atc-router in the changelog, now we add it.
=> doc(changelog)add atc-router in changelog

spec/04-perf/01-rps/06-core_entities_crud_spec.lua, spec/fixtures/perf/terraform/aws-ec2/main.tf, spec/fixtures/perf/terraform/aws-ec2/variables.tf, spec/helpers/perf.lua, spec/helpers/perf/drivers/docker.lua, spec/helpers/perf/drivers/terraform.lua, spec/helpers/perf/git.lua
* [test(perf) drop explict aws provider variable, user can set credential](https://github.com/Kong/kong/commit/669fc02536cb9e87a4a687eb495e40410d96039d) 
through AWS_* environment variables for more flexible setup
* [tests(perf) fix CRUD test](https://github.com/Kong/kong/commit/2d1e2824cd9dbea880adbbf9bf41648d7eb6a85a)
* [tests(perf) fix docker driver with daily image](https://github.com/Kong/kong/commit/70965ea94806c056aa9ab5de941ece7909b3f35c)
* [tests(perf) skip nginx version check on spec.helpers load](https://github.com/Kong/kong/commit/0b66547a71f18d1ab2f7db12503f018871a99f22)
* [tests(perf) fix version mapping](https://github.com/Kong/kong/commit/4ccf84247917abe9654121b95acb05d6bd925020)
=> perf(*) fix(*) perf test framework fixes cherry-picked from EE

CHANGELOG.md
We missed asw-lambda plugin the changelog, now we add it.
=> doc(changelog)add aws-lambda in changelog 

CHANGELOG.md
* remove redundant changelog
* add missing changelog
=> docs(changelog) remove redundant and add missing changelog

kong/runloop/balancer/targets.lua
Do not log critical error when balancer dns resolving timer rescheduling fails because of process is shutting down. (<-- very proper english, thank you).
=> chore(balancer) do not log critical error on timer rescheduling on shutdown

kong/router/atc_compat.lua
Inspired by #9036, I introduced `tablepool` in atc router.
I think it may be some help for performance.
* use `tablepool` to reduce small table object usage
=> refactor(router) use tablepool to improve router

kong/db/schema/init.lua, spec/02-integration/04-admin_api/04-plugins_routes_spec.lua
It was reported by @zhangxuri198 on #9224 that our Admin API gives `unexpected error` on certain input. This commit fixes the issue.
Fix #9224
=> fix(db) schema:merge_values to check type of value, fix #9224

CHANGELOG.md, kong/plugins/zipkin/handler.lua
=> fix(zipkin) fix incorrect header start calculation

kong-3.0.0-0.rockspec, kong/router/atc_compat.lua, kong/router/init.lua, kong/router/traditional.lua, kong/router/utils.lua
Remove redundant code in `atc_compat.lua` and `traditional.lua`.
=> refactor(router) code clean with utils.lua

CHANGELOG.md
addendum to https://github.com/Kong/kong/pull/9182
=> chore: add table_name feature changelog

CHANGELOG.md
addendum to https://github.com/Kong/kong/pull/8957
=> chore: add stanza for #8957

kong/tools/utils.lua
=> chore(tools) code clean for utils.lua

CHANGELOG.md
Add missing changelog for:
- https://github.com/Kong/kong/pull/8255
- https://github.com/Kong/kong/pull/8663
- https://github.com/Kong/kong/pull/8914
- https://github.com/Kong/kong/pull/8574
Please merge with Rebase.
=> docs(changelog) add missing entries

kong/router/atc_compat.lua
* use constant bit flags
* localize vars
=> chore(router/atc) use constant priority bit

CHANGELOG.md, scripts/changelog-helper.lua
Updates to the 3.0 changelog (FTI-3121)
=> docs(changelog) update changelog for 3.0

kong/router/atc_compat.lua
Add yielding in build atc-router
=> perf(router/atc)yield in build router

.gitignore, scripts/test-upgrade-path.sh
Was previously logging to files, but that was not very helpful.
=> chore(upgrade-tests) log to stdout instead of files to benefit CI

kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
unit test for router expression
=> test(router/expression) unit test for router expression

autodoc/admin-api/data/admin-api.lua, kong/api/routes/upstreams.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua
Remove healthy APIs in hybrid mode.
Fix FT-2953
=> fix(endpoints) disable healthcheck `PUT` apis in hybrid mode

kong/router/atc_compat.lua, spec/01-unit/08-router_spec.lua
=> fix(router) atc compat escaping

kong/router/atc_compat.lua
=> style(router) typofix remove_existing

.github/workflows/build_and_test.yml, spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua, spec/fixtures/mock_webserver_tpl.lua, spec/helpers.lua
=> tests(intergration/proxy/balancer/healthchecks) fix some flaky tests

kong/router/atc_compat.lua
=> style(router/expression) small code clean

spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua
https://github.com/Kong/kong/blob/b033e3cdd134a392c4dcffc2b5b044e219f1479f/.ci/run_tests.sh#L44-L115
I started [an action](https://github.com/Kong/kong/actions/runs/2931839104) to run these tests about 70 times, once [it](https://github.com/Kong/kong/actions/runs/2931839104) is green, we can merge this PR.
_FT-3282_
=> tests(integration/proxy/balancer/consistent-hashing) fix some flaky tests

spec/01-unit/08-router_spec.lua
add fields expression/priority only for flavor expressions
=> tests(router) optimize unit test for router

spec/02-integration/04-admin_api/08-targets_routes_spec.lua
Fix test case "returns HEALTHCHECK_OFF for target with weight 0" in spec/02-integration/04-admin_api/08-targets_routes_spec.lua
Add a short time waiting for the config to be taken effect.
=> fix test failure

CHANGELOG.md
* update changelog about path handling deprecation
=> docs(changelog) update changelog about path handling deprecation

spec/02-integration/04-admin_api/08-targets_routes_spec.lua
=> tests(integration/admin_api/targets_routes) fix a flaky test

kong/clustering/control_plane.lua, kong/clustering/wrpc_control_plane.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/06-lagacy_switch_spec.lua, spec/02-integration/09-hybrid_mode/08-lazy_export.lua
Based on https://github.com/Kong/kong/pull/9362, and inspirations from https://github.com/Kong/kong/pull/9368 with wRPC related bugs fixed.
=> perf(clustering) on-demand export of declarative config for Hybrid mode protocols

kong/clustering/control_plane.lua, kong/clustering/wrpc_control_plane.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/06-lagacy_switch_spec.lua, spec/02-integration/09-hybrid_mode/08-lazy_export.lua
=> Cherrypick #9368 to `release/3.0.x.`

kong/router/atc_compat.lua, kong/tools/utils.lua, spec/01-unit/08-router_spec.lua
=> Cherry pick/ fix old route order #9346

kong/db/migrations/core/016_280_to_300.lua
Cherry-picking https://github.com/Kong/kong/pull/9334
=> Cherry pick/route bg mig

CHANGELOG.md
changelog entry for https://github.com/Kong/kong/pull/9384
=> docs(changelog): changelog entry for #9384

kong-3.0.0-0.rockspec, kong/db/declarative/migrations/init.lua, kong/db/declarative/migrations/route_path.lua, kong/db/migrations/core/016_280_to_300.lua, kong/db/migrations/migrate_path_280_300.lua, kong/router/atc_compat.lua, kong/router/traditional.lua, spec/01-unit/08-router_spec.lua
Cherry pick of https://github.com/Kong/kong/pull/9389 for 3.0.0 release
=> fix(router) prefix match no longer normalize input (#9389)

kong.conf.default
=> docs(kong.conf) add `router_flavor` documentation (#9386)

kong.conf.default
=> fix(conf): typo fix, flavor should be expressions (#9411)

CHANGELOG.md, kong/plugins/prometheus/grafana/kong-official.json
1. update prometheus changelog to explain the new flag
2. update prometheus grafana json panel
=> docs(upgrade) change prometheus changelog and update prometheus dashboard

kong/db/declarative/init.lua, kong/db/declarative/migrations/init.lua, kong/db/declarative/migrations/route_path.lua, spec/01-unit/01-db/01-schema/11-declarative_config/04-on-the-fly-migration_spec.lua, spec/02-integration/02-cmd/11-config_spec.lua, spec/02-integration/04-admin_api/11-reports_spec.lua
when you put a route nested in service it fails to migrate on the fly.
=> fix(declarative) migration failed on nested route

kong/db/declarative/init.lua, kong/db/declarative/migrations/init.lua, kong/db/declarative/migrations/route_path.lua, spec/01-unit/01-db/01-schema/11-declarative_config/04-on-the-fly-migration_spec.lua, spec/02-integration/02-cmd/11-config_spec.lua, spec/02-integration/04-admin_api/11-reports_spec.lua
when you put a route nested in service it fails to migrate on the fly
This is a cherry-pick of #9412
=> fix(declartive): migration failed on nested route

CHANGELOG.md, kong/plugins/prometheus/grafana/kong-official.json
This is the cherry-pick of #9410
=> docs(changelog) change prometheus changelog and update prometheus dashboard

UPGRADE.md
cherry-pick of https://github.com/Kong/kong/pull/9404 for 3.0.0 release
=> docs(upgrade) instructions for 3.0 

kong/tools/utils.lua
* Do not use division in `yield`.
* move `ngx.sleep`/ `ngx.get_phase`
=> refactor(tools): optimize `utils.yield` for better performance

CHANGELOG.md
Cherry-pick CHANGELOG.md changes from `release/3.0.x`
=> docs(changelog) add 3.0.0 changes

CHANGELOG.md, kong/init.lua, spec/02-integration/14-tracing/01-instrumentations_spec.lua, spec/fixtures/custom_plugins/kong/plugins/tcp-trace-exporter/handler.lua
=> fix(instrumentation) plugin_header_filter instrumentation was not in correct place

CHANGELOG.md
little typo in the changelog
* ...
=> fix: CHANGELOG

kong/router.lua, kong/runloop/handler.lua
=> perf(router): dynamic router lru cache size based on number of routes

CHANGELOG.md, kong/include/wrpc/wrpc.proto, kong/tools/wrpc/future.lua, spec/01-unit/19-hybrid/05-wrpc/future_spec.lua
=> style(wrpc): typo fix recieve -> receive

.ci/run_tests.sh, .github/workflows/build_and_test.yml, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/02-cmd/12-hybrid_spec.lua, spec/02-integration/02-cmd/13-signals_spec.lua, spec/02-integration/04-admin_api/08-targets_routes_spec.lua, spec/02-integration/06-invalidations/02-core_entities_invalidations_spec.lua, spec/03-plugins/01-tcp-log/01-tcp-log_spec.lua, spec/03-plugins/02-udp-log/01-udp-log_spec.lua, spec/03-plugins/05-syslog/01-log_spec.lua, spec/fixtures/balancer_utils.lua, spec/helpers.lua
_FT-3340, FT-3341, FT-3342, FT-3343, FT-3344, FT-3346, FT-3347, FT-3348_
=> tests: fix some flaky tests

CHANGELOG.md
Summary:
Add missing document for #9510
=> docs(CHANGELOG): add missing document for #9510

CHANGELOG.md, kong/api/arguments.lua, spec/02-integration/04-admin_api/21-truncated_arguments_spec.lua
This is a backport of https://github.com/Kong/kong/pull/9510 to the 2.8 release branch
=>  fix(admin): increase max uri and post arguments to 1000 (backport 2.8)

kong/init.lua, kong/runloop/plugins_iterator.lua
- perf(plugins-iterator): cache global plugins for faster execution
- perf(plugins-iterator): replace iterators with iterator getters
=> perf(plugins-iterator): cache globals and replace iterators with iterator getters

kong/runloop/plugin_servers/init.lua
I found that lots of code of plugins did not localize global apis, 
so I did a try, Does it make sense?
* localize some API like `pairs` `type`
* introduce a function `get_saved()` to reduce duplicated code.
=> style(plugin_servers): some localization of functions

kong/runloop/plugin_servers/init.lua
=> fix(PDK): req.start_time for PDK log phase

kong/router/compat.lua
Add the same logic in compat router: last dot in FQDNs must not be used for routing
=> chore(router/atc): remove last dot in sni

CHANGELOG.md, kong/include/kong/pluginsocket.proto, kong/pdk/request.lua, kong/runloop/plugin_servers/init.lua, t/01-pdk/04-request/00-phase_checks.t, t/01-pdk/04-request/21-get_uri_captures.t
=> feat(pdk): add request.get_uri_captures

CHANGELOG.md, kong/runloop/plugin_servers/init.lua
Minor code style fixes.
* Remove duplicated code in #9512
* changelog style fixes (break long line)
* changelog entry for #9173
=> style(*): style fix for plugin server and changelog

spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua
=> tests(integration/proxy/balancer/consistent-hashing): mark as a flaky test group

kong/conf_loader/init.lua, kong/tools/utils.lua
`try_decode_base64` moved to utils (reflects change from: https://github.com/Kong/kong-ee/pull/3872)
=> chore(utils): reflecting changes in ee utils

kong/db/declarative/init.lua
Do some clean work when I am doing code review.
* localize `cjson.*`
* move `exiting()` to their own `do end` block.
* use `get_phase()` to optimize `yield` call
* in `load_into_cache`, localize some var like `is_foreign` `item_fname`
* use `utils.sha256_hex` to replace `resty.sha256`
=> style(db/declarative): small code clean

CHANGELOG.md
=> doc(changelog): fix PR link for #9583

.github/workflows/upgrade-tests.yml, spec/05-migration/db/migrations/core/017_300_to_310_spec.lua
add 3.1 migrations spec
add 3.1 migrations spec for #9430 
chery-pick #9487
=> tests(migrations): add 3.1 migrations spec

kong/clustering/control_plane.lua, kong/clustering/wrpc_control_plane.lua, kong/db/declarative/migrations/route_path.lua, kong/db/migrations/migrate_path_280_300.lua
Small code clean.
* localize some apis
* change array `REGEX_META_CHARACTERS`
* optimize function `percent_decode`
=> style(db): declarative migration clean

kong/router/atc.lua, kong/router/init.lua, kong/router/traditional.lua, kong/router/utils.lua
Small code clean and optimization for phonehome_statistics
* remove unnecessary `_M.phonehome_statistics`
* add `utils.route_match_stat` to simplify code
* change protocol count logic (do not use for loop)
* code alignments
=> style(router): code clean and optimization for phonehome_statistics

CHANGELOG.md
These extra changelog entries snuck in when merging #9594
=> docs(changelog): remove incorrect entries

kong/api/api_helpers.lua, kong/api/endpoints.lua
=> style(api): api code clean

spec/fixtures/https_server.lua
Fix https://github.com/Kong/kong/actions/runs/3334462656/jobs/5517448732
_FT-3508_
=> tests(https_server): retry if failed to start Nginx

CHANGELOG.md
The original feature pull request was a fork, so it was easier to just do this in a separate PR.
=> docs(changelog): add entry for #8930

.github/ISSUE_TEMPLATE/bug_report.yaml
This will fix some grammatical issues potentially making the wording more easier to read.
* This changes wording in the bug_report.yaml file as some grammar is not correct.
=> (Grammar Changes) Update bug_report.yaml

CHANGELOG.md
=> docs(changelog): add entry for #9457

CHANGELOG.md
=> docs(changelog): add entry for #9504

spec/02-integration/09-hybrid_mode/02-start_stop_spec.lua
=> tests(clustering): turn off vitals in stop/start errlog test

CHANGELOG.md
Typo fix for #9463, and move to `Fixes` section.
=> docs(changelog): typofix for #9463

kong/plugins/opentelemetry/handler.lua
Optimize the logic of function `get_cached_headers()`
=> style(plugins/otel): code clean for get_cached_headers()

.devcontainer/Dockerfile
=> chore(devcontainer) bump to 3.0.0

.devcontainer/Dockerfile
Fixed missing yaml-dev dependency in devcontainer
* Add yaml-dev dependency 
Fix #9692
=> Fixed #9692 missing yaml-dev dependency in devcontainer

.devcontainer/Dockerfile
=> chore(devcontainer): use correct tag and move off alpine

kong/db/dao/key_sets.lua, kong/db/dao/keys.lua, kong/db/schema/entities/key_sets.lua, spec/02-integration/03-db/18-keys_spec.lua
* remove cache_key from key-sets
* change cache_key construction of keys
cherry-picked from https://github.com/Kong/kong-ee/pull/4040
=> fix(core): fix cache_key issues

CHANGELOG.md
=> doc(changelog): add an entry for PR 9778

kong/tools/wrpc/init.lua
=> fix(clustering): wrpc also set ws connect timeout

CHANGELOG.md
Add missing changelog for #9521.
* Add missing changelog for #9521
Fix nothing.
=> docs(changelog): add changelog for #9521

kong-3.1.0-0.rockspec
=> chore(deps): bump pgmoon to 1.16.0

Makefile
kong-build-tools makes a best guess at the KONG_SOURCE_LOCATION. To avoid building incorrect source let's be explicit cc @gruceo
=> fix(Make): explicitely set the KONG_SOURCE_LOCATION environment variable

.github/workflows/package.yml
Backport 89ac217b4d6dc0fbecb11909ca50e8d7443c9e05 from #9829.
=> [Backport release/2.8.x] fix(ci): make sure docker tag is valid

kong/db/declarative/init.lua
Small code clean for declarative.
=> style(db/declarative): small code clean for declarative

kong/plugins/prometheus/api.lua, kong/plugins/prometheus/exporter.lua, kong/plugins/prometheus/prometheus.lua
cherry-picking 2 commits that optimize the performance.
=> cherrypick(prometheus): performance optimization

CHANGELOG.md
=> docs(core): changelog for path validation change

Jenkinsfile
Backport e557e96bd9d623fc625fda99fcd8051be501419b from #9883.
=> fix(ci): authentication changes

Jenkinsfile
Backport e557e96bd9d623fc625fda99fcd8051be501419b from #9883.
=> [Backport release/3.0.x] fix(ci): auth

.github/labeler.yml
=> chore(ci): add bazel labels

.github/labeler.yml
Try to fix github actions labeler.
The labeler seems to be running with master branch code.
=> chore(ci): fix labeler

.github/workflows/build_and_test.yml, .github/workflows/package.yml, .github/workflows/perf.yml, .github/workflows/upgrade-tests.yml, build/README.md, scripts/build-kong.sh
Backport bazel changes from EE to CE.
=> backport(*): EE -> CE bazel changes

.github/workflows/build_and_test.yml, .github/workflows/package.yml, .github/workflows/perf.yml
GitHub Actions includes Bazelisk by default as of actions/runner-images#490
=> chore(ci): remove bazelisk

kong/init.lua
Remove repeated code with some small functions, let the code more readable.
Introduce new functions:
* is_data_plane 
* is_control_plane 
* is_dbless
=> style(init): introduce role/mode check functions

kong/pdk/service.lua
=> style(pdk):localize some vars

.github/workflows/package.yml
=> chore(ci): replace kbt with bazel build

build/README.md
=> doc(build): Update README.md

build/README.md
Add Bash/Zsh command and supporting Mac FAQ
=> docs(ci): add Bash/Zsh command and supporting Mac FAQ

kong/plugins/basic-auth/access.lua, kong/plugins/basic-auth/crypto.lua
Code clean and small optimization.
* add `oj` opts for `re.gmatch`
* simplify `salt_password()`
* localize some vars
=> refactor(plugins/basic-auth): code clean and optimization

README.md
Takeover https://github.com/Kong/kong/pull/9818
=> docs(README): fix markdown order list manner

kong/plugins/aws-lambda/iam-ec2-credentials.lua
Fix a confusing typo in a comment
=> fix(plugin): Fix typo in comment

kong/plugins/aws-lambda/iam-ec2-credentials.lua
=> style(plugin): adjust whitespace

CHANGELOG.md
https://konghq.atlassian.net/browse/FTI-4536
=> docs(changelog): add CHANGELOG entry for AWS Lambda IMDSv2 support

kong/plugins/prometheus/api.lua, kong/plugins/prometheus/exporter.lua, kong/plugins/prometheus/prometheus.lua, spec/03-plugins/26-prometheus/06-hybrid-mode_metrics_spec.lua, spec/03-plugins/26-prometheus/07-optional_fields_spec.lua
=> feat(prometheus): skip fields in shm (high cost) when no instance configured

kong/router/atc.lua
Simplify CACHED_SCHEMA init code and other code clean.
=> style(router/atc): simplify atc code

kong/plugins/ip-restriction/handler.lua, spec/03-plugins/17-ip-restriction/02-access_spec.lua
add lrucache for ipmatcher
* lrucache
* more test cases for `PATCH` method
* add a 300 seconds ttl for cache
=> perf(plugins/ip-restriction): add lrucache for ipmatcher

kong/plugins/response-transformer/body_transformer.lua, kong/plugins/response-transformer/handler.lua, kong/plugins/response-transformer/header_transformer.lua, spec/03-plugins/15-response-transformer/01-header_transformer_spec.lua, spec/03-plugins/15-response-transformer/02-body_transformer_spec.lua
Code clean and small optimization.
* localize some functions
* use function `json_value` to simplify logic
* remove `is_json_body` in body_transformer
* move `is_json_body` test cases into header_transformer
=> refactor(plugins/response-transformer): code clean

.github/workflows/release.yml
Fix failing nightly build: https://github.com/Kong/kong/actions/runs/3790682227
=> build(release): fix rpm build

.github/workflows/build_and_test.yml, .github/workflows/release.yml
Fix failing https://github.com/Kong/kong/actions/runs/3791470802/jobs/6446931340
=> build(release): fix permissions

spec/03-plugins/26-prometheus/07-optional_fields_spec.lua
The test is trying to access a stream port.
=> fix(test): prometheus test incorrect mock

kong/plugins/key-auth/handler.lua
Small code clean and improvements.
=> style(plugins/key-auth): code clean

.github/workflows/release.yml
Fix errors like https://github.com/Kong/kong/actions/runs/3800357104
=> chore(cd): skip empty matrix

kong/plugins/acme/api.lua, kong/plugins/acme/client.lua, kong/plugins/acme/handler.lua
localize more vars, fix a typo in `deserialize_certkey()`
=> style(plugins/acme):localize more vars

kong/init.lua
localize some vars in `balancer()`
=> style(core/balancer): localize vars in balancer()

kong/pdk/response.lua
* localize `cjson.encode`
* function `get_http_message` to generate message
* constant `is_http_subsystem`
=> style(pdk): optimize error message and other code clean

kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua
The original PR https://github.com/Kong/kong/pull/9494
FTI-4369
=> [Backport]refactor(handler): trying to make reconfigure more atomic

kong/clustering/compat/init.lua, spec/01-unit/19-hybrid/03-compat_spec.lua
cherry-pick #9972 
[FTI-4617]
[FTI-4617]: https://konghq.atlassian.net/browse/FTI-4617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(clustering): `upstream.use_srv_name` should be removed for DPs older than `3.1.0` (#9972)

kong.conf.default, kong/templates/kong_defaults.lua
Add missing documentation entry in kong.conf.default
KAG-303
=> docs(*): document new max_queued_batches parameter

spec/01-unit/16-runloop_handler_spec.lua
This is a fix PR for #9970, I did not use mock correctly.
=> fix(test): mock test for runloop events

CHANGELOG.md, kong/constants.lua, kong/db/dao/init.lua, kong/db/schema/typedefs.lua, kong/plugins/oauth2/schema.lua, spec/03-plugins/25-oauth2/01-schema_spec.lua
fix FTI-3250
[FTI-3250]: https://konghq.atlassian.net/browse/FTI-3250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(oauth2): validation on ttl

kong/concurrency.lua
=> style(core): refactor concurrency code with some localization

.gitignore
Summary:
Add vscode related ignored folders
=> chore(git): add vscode related ignored folders

build/BUILD.bazel, build/luarocks/BUILD.luarocks.bazel
=> fix(build): fix macOS compatibility without coreutils and genrule missing xcode env vars

build/package/nfpm.yaml
Add new script from #9808 into package
=> chore(build): package kong-health script

bin/kong-health
=> fix(cli) use proper command name for health

CHANGELOG.md
Add missing change log for PR #10143.
=> docs(changelog): add changelog entry for atc-router 1.04

autodoc/admin-api/data/admin-api.lua
Following up PR for https://github.com/Kong/docs.konghq.com/pull/4888#issuecomment-1371483488
=> fix(admin-api): update plugin.protocols document

CHANGELOG.md
Remove a duplicated change log entry, which already appears in the Fixes section.
=> docs(changelog): remove duplicated entry

kong.conf.default
=> docs(conf): link Securing the Admin API from admin_listen

kong.conf.default
=> docs(kong.conf.default): typo fix for  LMDB config options

CHANGELOG.md
Add missing change log entry for #9787 .
=> docs(changelog): add changelog for #9787

.github/workflows/build_and_test.yml
revert and fix https://github.com/Kong/kong/pull/10232
=> fix(ci): include build directory as build key

CHANGELOG.md
=> docs(changelog): add missing PR link for #9904

.github/workflows/release.yml
A fix I already applied to EE: https://github.com/Kong/kong-ee/blob/master/.github/workflows/release.yml#L349-L366
Needed in CE to **actually** build arm64 images.
=> fix(gha): align docker platform output name

kong/pdk/log.lua
Inspired by PR #10259, remove some redundant code.
* wrap `tonumber` to `to_decimal`
* style lint
=> refactor(pdk/log): wrap function `to_decimal`

.github/workflows/release.yml
=> fix(gha): ensure zlib installed for centos/rhel-7

.github/workflows/build_and_test.yml, spec/helpers.lua
Adds a test to prevent issues like: https://github.com/Kong/kong-pongo/issues/383
=> chore(ci): add test to check test-helper doc generation

CHANGELOG.md
This adds a changelog entry for #10122.
=> docs(changelog): add entry for renamed kong.conf properties

README.md
=> docs: change inc year

.github/workflows/release.yml
Cherry-pick of https://github.com/Kong/kong/pull/10335.
=> fix(actions): use `regctl` for (multiarch) image copy (#10335)

CHANGELOG.md, kong/plugins/opentelemetry/handler.lua, kong/plugins/opentelemetry/otlp.lua, spec/03-plugins/37-opentelemetry/03-propagation_spec.lua
Backport 6fa55b38152ce6510248b6bb549af0ef852bdabe from #10332.
=> [Backport release/3.2.x] fix(plugin): OTEL exporting with translate

build/kong_bindings.bzl
Cherry-pick https://github.com/Kong/kong/pull/10376 into `release/3.2.x`
=> fix(build): cherry-pick adding rpm signing related env var into repository rule environ list (#4647) (#10376)

build/repositories.bzl
=> fix(build): fix intel detection with elif

CHANGELOG.md, kong/db/declarative/init.lua, kong/db/declarative/migrations/route_path.lua, spec/01-unit/01-db/01-schema/11-declarative_config/04-on-the-fly-migration_spec.lua, spec/02-integration/02-cmd/11-config_spec.lua
Backport 2f82cedaa248275a9e61e869331409b38d24d8d9 from #10348.
=> [Backport release/3.2.x] fix(db/migration): do migration before validation

kong/init.lua, kong/runloop/handler.lua, spec/02-integration/02-cmd/03-reload_spec.lua, spec/02-integration/05-proxy/02-router_spec.lua, spec/helpers.lua
🍒 Cherry pick:
- https://github.com/Kong/kong/pull/9396
- https://github.com/Kong/kong/pull/9485
Please do not use squash commit merge, keep the original commits for better tracking purposes.
Fix FTI-4696
=> [Backport release/2.8.x] cherrypick PRs of workers respawned 

CHANGELOG.md
=> docs(changelog) update changelog for 3.2.1

build/openresty/BUILD.openresty.bazel, build/openresty/patches/nginx-cross-endianness-fix.patch
=> fix(build): add the missing endianness cross build patch

kong.conf.default
Related to #10374 - better documentation for the error template fields
~The Pull Request has tests~
~There's an entry in the CHANGELOG~
~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
=> docs(conf): improved error_template fields documentation

kong/plugins/proxy-cache/handler.lua, spec/03-plugins/31-proxy-cache/02-access_spec.lua, spec/03-plugins/31-proxy-cache/03-api_spec.lua, spec/03-plugins/31-proxy-cache/04-invalidations_spec.lua
This reverts commit 14513553586ce8fc29072340c57b22f1c249a562 as it caused master to turn red.
=> Revert "Feat/proxy cache debug (#7829)"

CHANGELOG.md
It seems some merged PR mixed up the changelog, here is a small clean.
=> docs(changlog): fix unreleased changelog

CHANGELOG.md
Changelog entry for #10449
~The Pull Request has tests~
~There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
=> chore(*): changelog for #10449

spec/02-integration/03-db/15-connection_pool_spec.lua
Resolve flakiness in the Postgres connection pool test
KAG-864
=> tests(connection_pool): remove some flakiness

.github/workflows/build_and_test.yml, DEVELOPER.md, Makefile, build/BUILD.bazel, build/README.md
=> feat(*): update docs and Makefile to use Bazel build system

.github/stale.yml
This reverts commit aec5653167c53e9ccd811390fa2043a82f50a7a9.
More discussion is required on this.
=> Revert "Summary: chore(*): reconfigure automatic closing of issues and PRs (#10469)"

Makefile
Fix https://github.com/Kong/kong-plugin/actions/runs/4421446482/jobs/7752253030#step:4:1610
=> chore(makefile): split dependency and preserve install-legacy in Makefile

CHANGELOG.md
=> docs(changelog): small typo fix for #10468

Makefile
=> fix(makefile): remove extra @ symbols

.github/labeler.yml, .github/workflows/build_and_test.yml, scripts/check-labeler.pl
Make sure that we have automatic labelling set up for all plugins.
KAG-932
=> chore(ci): check labeler configuration for completeness

Makefile
* fix(luajit): ensure that ffi loaded libs will not get GC'ed
* Add Indonesian language support
* Allow helpers to extend busted
=> chore(deps) bump busted from 2.1.1 to 2.1.2

spec/02-integration/05-proxy/10-balancer/03-consistent-hashing_spec.lua, spec/fixtures/balancer_utils.lua
Fixing health check flaky test
KAG-836
=> tests(healthcheck): fix passive healthcheck flaky test

DEVELOPER.md, build/templates/venv.fish, build/templates/venv.sh, scripts/dependency_services/docker-compose-test-services.yml, scripts/dependency_services/up.fish, scripts/dependency_services/up.sh
pretty demo:
[![asciicast](https://asciinema.org/a/EbHlR6FuCLSzhHi6iTCRMuUiy.svg)](https://asciinema.org/a/EbHlR6FuCLSzhHi6iTCRMuUiy)
=> chore(dev): add a reference docker-compose file to bring up services

kong-2.8.3-0.rockspec, spec/02-integration/03-db/01-db_spec.lua
See https://github.com/leafo/pgmoon/releases
Fix https://github.com/Kong/kong-ee/pull/4435
=> chore(deps) bump pgmoon from 1.13.0 to 1.16.0

kong/pdk/vault.lua
Fallback to stale value on vault errors.
=> feat(vault): allow stale value returned from vault in case of an error

kong/plugins/azure-functions/handler.lua
It is questionable to have these type of micro-level config caches, and they are becoming a problem as we are starting to implement secret rotation.
KAG-1033
=> refactor(azure-functions): remove config cache

.github/matrix-commitly.yml, .github/matrix-full.yml, .github/workflows/release.yml, scripts/explain_manifest/fixtures/ubuntu-18.04-amd64.txt
Ubuntu 18.04 runner will go EOL. See actions/runner-images#6002
KAG-724
=> chore(cd): build ubuntu 18.04 inside docker instead of host OS

CHANGELOG.md, kong/db/schema/init.lua, kong/plugins/datadog/schema.lua, spec/03-plugins/08-datadog/01-log_spec.lua
* Allow referenceable fields to be parsed as string/number/boolean
* Make Datadog host/port referenceable
Fix FTI-4910
=> feat(plugin): datadog host/port referenceable

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, .github/workflows/build_and_test.yml, Makefile, kong/runloop/handler.lua, spec/02-integration/05-proxy/27-unbuffered_spec.lua
=> Revert "Fix request buffering for HTTP/2.0"

Makefile
Master is currently red because of #10595 (was green when merged), this is an attempt to fix it.
=> fix(ci): fix makefile to include CURL_INCDIR

.github/workflows/autodocs.yml, .github/workflows/perf.yml, .github/workflows/release.yml, DEVELOPER.md
Master is currently red because of #10595 (was green when merged), this is a second attempt to fix it.
=> fix(ci): fix ci to install curl headers files

CHANGELOG.md
add missing PR link for #10417
=> docs(changelog): add missing PR link for #10417

kong/plugins/opentelemetry/handler.lua
It is questionable to have these type of micro-level config caches, and they are becoming a problem as we are starting to implement secret rotation.
KAG-1034
=> refactor(opentelemetry): remove headers config cache

scripts/backoff.sh
#10606 was too eager deleting scripts, here is one that is needed.
=> chore(*): re-instantiate script that is in use

spec/03-plugins/29-acme/05-redis_storage_spec.lua
[KAG-615](https://konghq.atlassian.net/browse/KAG-615)
[KAG-615]: https://konghq.atlassian.net/browse/KAG-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(acme): add test to ensure that the namespace parameter takes effect

.bazelrc, scripts/explain_manifest/fixtures/alpine-amd64.txt, scripts/explain_manifest/fixtures/el7-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-18.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt, scripts/explain_manifest/main.py, scripts/explain_manifest/requirements.txt
This cherry-picks the following PRs:
https://github.com/Kong/kong/pull/10568
https://github.com/Kong/kong/pull/10579
Please rebase merge to keep the commits accordingly.
FTI-4918
KAG-1036
=> [cherry-pick release/3.2.x] add back debug symbol and related test to release/3.2.x

.bazelrc, DEVELOPER.md, Makefile, build/kong_bindings.bzl, build/openresty/BUILD.openresty.bazel
* correct bazelisk arch on Apple Silicon
* use macOS native command to detect processor count
* improve incremental build for openresty
* add sanity check and docs for macOS Xcode installation
=> fix(build): misc fixes for macos 

.github/workflows/release-fail-bot.yml
=> refactor(ci): use new webhook api

.github/workflows/release-fail-bot.yml
Fix KAG-1315
Add branch name.
Consistent with Kong/kong-ee#5172
=> chore(ci): add branch name in“Package & Release” notification message

kong/tools/queue.lua
Also discussed with Hans offline, the `update_time` call is not needed for these use cases and are therefore removed.
=> style(queue): localize hot path variables and minor style fixes

.github/matrix-commitly.yml, .github/matrix-full.yml, .github/workflows/release.yml, scripts/explain_manifest/config.py, scripts/explain_manifest/expect.py, scripts/explain_manifest/explain.py, scripts/explain_manifest/fixtures/alpine-amd64.txt, scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt, scripts/explain_manifest/fixtures/el7-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-18.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-22.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt, scripts/explain_manifest/main.py, scripts/explain_manifest/requirements.txt, scripts/explain_manifest/suites.py
Add a imperative test framework to verify artifacts. Move some tests that too strict to test in the manifest file into the newly written test suites.
- TODO:
* feat(build): add imperative test suite
KAG-979
=> feat(build): add imperative test suite

build/README.md
It is a minor style fix for #10645.
=> docs(build): minor style fix

autodoc/admin-api/data/admin-api.lua
Adds note that fields are referenceable.
=> docs(admin): keys.jwk and keys.pem.private_key/public_key are referenceable

spec/03-plugins/29-acme/05-redis_storage_spec.lua
wait until admin API takes effect
=> test(acme): fix acme flaky test

spec/01-unit/27-queue_spec.lua
Add a couple of tests that check whether queues still work when the system time is being changed forwards and backwards.
=> tests(core): verify that queues work after time adjustments

CHANGELOG.md
=> docs(changelog): move some entries to the correct place

.github/workflows/build.yml, .github/workflows/build_and_coverage.yml, .github/workflows/build_and_test.yml, t/01-pdk/02-log/01-sanity.t, t/Util.pm, t/pdk.luacov
Requires: https://github.com/Kong/kong/pull/10754
add coverage for pdk tests
[KAG-1324](https://konghq.atlassian.net/browse/KAG-1324)
[KAG-1324]: https://konghq.atlassian.net/browse/KAG-1324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests(pdk): add coverage

CHANGELOG.md
Remove a mistake entry introduced by #10615
=> docs(changelog): fix some mistakes 

.bazelrc, build/BUILD.bazel, build/kong_bindings.bzl, build/openresty/BUILD.openresty.bazel, build/openresty/openssl/BUILD.openssl.bazel, build/openresty/patches/LuaJIT-2.1-20220411_03_pass_cc_env.patch
This may help control the environment being sanitized for macOS.
=> fix(build): remove PATH from env var and hardcode `ar` for macOS

.github/workflows/upgrade-tests.yml, spec/05-migration/plugins/oauth2/migrations/007_320_to_330_spec.lua
=> fix(tests): upgrade tests

.github/workflows/upgrade-tests.yml
Also add an EE path to avoid an unnecessary delta with the EE project.
=> chore(ci): fix paths in upgrade tests

.github/workflows/upgrade-tests.yml, spec/05-migration/plugins/oauth2/migrations/007_320_to_330_spec.lua
Cherry-pick https://github.com/Kong/kong/pull/10811 and https://github.com/Kong/kong/pull/10813.
=>  [backport release/3.3.x] fix(upgrade-tests): add oauth2 upgrade test 

spec/02-integration/01-helpers/01-helpers_spec.lua
This updates the test for this helper util to use `assert.near()` with 25% leeway and adds `ngx.update_time()` calls when calculating duration in order to get a more accurate result.
FTI-5036
=> tests(helpers): make wait_for_file_contents less flaky

kong/router/compat.lua
This PR is a small style clean for #10615.
=> style(router/compat): small style clean

CHANGELOG.md
This PR should be a Fix, not an Addition.
=> docs(changelog): move ngx_lua patch entry to correct Fix section

scripts/dependency_services/common.sh, scripts/dependency_services/up.fish, scripts/dependency_services/up.sh
Use var `$DOCKER_COMPOSE` to invoke `docker-compose` or `docker compose`.
KAG-1496
=> fix(scripts): use docker-compose wisely

CHANGELOG.md, kong-3.4.0-0.rockspec, kong/api/routes/kong.lua
Check: https://leafo.net/lapis/changelog.html
=> chore(deps): bump kong-lapis from 1.8.3.1 to 1.14.0.2

.bazelrc
=> chore(build): keep debuginfo for non-release build as well

CHANGELOG.md
Removed unrelated PR and added a shout-out to the community author.
=> docs(CHANGELOG.md) update #10723 entry

CHANGELOG.md
Move PR #10836's entry to the correct `Fix` section (instead of `Addition`).
=> docs(changelog): move #10836's entry to the correct Fix section

spec/02-integration/03-db/15-connection_pool_spec.lua, spec/fixtures/custom_plugins/kong/plugins/slow-query/api.lua
cherry-pick of https://github.com/Kong/kong/pull/10698
KAG-1623
=> [backport to release/3.2.x] tests(connection-pool): address flakiness (#10698)

spec/02-integration/01-helpers/01-helpers_spec.lua
This updates the test to use assert.near() with 25% leeway and adds ngx.update_time() calls when calculating duration in order to get a more accurate result.
(cherry picked from commit f20d961232127190d923b3a97e4c288eb198a2b6)
=> tests(helpers): make wait_for_file_contents less flaky (#10815)

CHANGELOG.md
I think this PR should be a "fix", not a "breaking changes".
=> docs(changelog): move #10656 to fixes section

CHANGELOG.md, kong/db/errors.lua, spec/02-integration/04-admin_api/15-off_spec.lua
This is a bugfix backport of #10896.
=> fix(dbless): handle unexpected types when flattening errors

CHANGELOG.md
I notice that recently we had many incorrect change log entries, which were put into improper place.
We should write the entry more carefully.
=> docs(changelog): move #10896 to fixes-core

spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
Add an assertion to help diagnose test flakiness.
=> fix(tests): add assertion to help diagnose flakiness

build/templates/venv.fish
=> fix(venv): correct fish syntax for fish < 3.6

CHANGELOG.md
=> docs(changelog): add thanks for community in #10559

.github/workflows/release.yml
Fix issues in step summary generation (incorrectly quoted backtick characters).
=> chore(ci): fix step summary

kong/clustering/tls.lua
Small typo fix and code clean.
=> style(clustering): code clean for tls logic

scripts/explain_manifest/config.py, scripts/explain_manifest/expect.py, scripts/explain_manifest/explain.py, scripts/explain_manifest/suites.py
fix(explain_manifest): backport fixes from EE
=> fix(explain_manifest): backport fixes from EE

kong/clustering/data_plane.lua
Simplify the code, and reduce the usage of loop.
=> refactor(clustering): clean the code of write_thread

kong/tools/mime_type.lua, spec/01-unit/26-mime-type_spec.lua
Cleanup some of the unused code
=> chore(mime_type): cleanup unused code

.github/workflows/build.yml, .github/workflows/perf.yml, .github/workflows/release.yml
Save 💵 .
https://github.com/Kong/kong-ee/pull/5702
=> chore(gha): set build temporary artifact retation period to 3 days

spec/helpers.lua
=> tests(cmd): fix flakiness in cmd start/stop

build/kong_bindings.bzl
=> Fix spelling in `build/kong_bindings.bzl`

kong/clustering/data_plane.lua
This is a follow up of #11021.
=> style(clustering): remove `else` by `goto continue` in read_thread

.github/workflows/release.yml, scripts/release-kong.sh
Discrete details in: https://github.com/Kong/kong-ee/pull/5863
Fix #_[KAG-1627]_
[KAG-1627]: https://konghq.atlassian.net/browse/KAG-1627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KAG-1627] Feat: Incorporate Cloudsmith

spec/01-unit/28-plugins-iterator/01-compound_key_spec.lua, spec/01-unit/28-plugins-iterator/02-lookup_cfg_spec.lua
Remove ee license introduced in #11105.
=> tests(plugin): remove ee license

CHANGELOG.md
#11150 should be in "Changed", not "Fixes".
=> docs(changelog): move entry to correct section

kong-3.4.0-0.rockspec, kong/runloop/handler.lua, kong/runloop/log_level.lua
Move log level logic into isolated module, easy to maintain.
=> refactor(runloop): move log level logic into isolated module

.devcontainer/Dockerfile, .github/workflows/autodocs.yml, .github/workflows/build.yml, .github/workflows/perf.yml, .github/workflows/release.yml, DEVELOPER.md, Makefile, spec/02-integration/05-proxy/27-unbuffered_spec.lua
This reverts commit fa2c37192382582a8b2946e90564f509dd979b29 (#10599).
KAG-1105
=> fix(tests): revive http 2.0 tests

.devcontainer/Dockerfile, .github/workflows/autodocs.yml, .github/workflows/build.yml, .github/workflows/perf.yml, .github/workflows/release.yml, DEVELOPER.md, Makefile, spec/02-integration/05-proxy/27-unbuffered_spec.lua
Previous failure is still there, revert to analyze log file.
KAG-1105
=> Revert "Revert "fix(ci): remove Lua cURL and CI modifications because of it (#10599)" (#11167)"

kong/plugins/rate-limiting/policies/init.lua
Adds support for secret rotation for redis credentials in response-ratelimiting plugin.
=> feat(rate-limiting): add support for secret rotation with redis connection

build/dockerfiles/apk.Dockerfile, build/dockerfiles/deb.Dockerfile, build/dockerfiles/rpm.Dockerfile
Upgrade docker base image.
* upgrade docker base image (rpm, apk, and deb)
Fix #FTI-5195
=> chore(dev): upgrade docker base image

build/tests/01-base.sh
=> chore(tests): fix smoke test

.github/matrix-commitly.yml, .github/matrix-full.yml, .github/workflows/release.yml, BUILD.bazel, scripts/explain_manifest/config.py, scripts/explain_manifest/fixtures/el9-amd64.txt
Add rhel 9 matrix
kong/kong-ee#5877
[KAG-1969](https://konghq.atlassian.net/browse/KAG-1969)
[KAG-1969]: https://konghq.atlassian.net/browse/KAG-1969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(cd): add rhel-9 matrix

CHANGELOG.md
=> docs(changelog): add entry for PR #10245

CHANGELOG.md
Prepare `3.3.1` release changelog.
* Format `3.3.1` release changelog entries.
Fix #FTI-5156
=> docs(*): format 3.3.1 release changelog entries

spec/02-integration/04-admin_api/17-foreign-entity_spec.lua, spec/fixtures/custom_plugins/kong/plugins/foreign-entity/api.lua, spec/fixtures/custom_plugins/kong/plugins/foreign-entity/daos.lua
Demonstrate issue reported in https://github.com/Kong/kong/pull/8977 is no longer reproducible.
=> tests(integration): add cache invalidation test case

.github/actions/build-wasm-test-filters/action.yml, build/openresty/BUILD.openresty.bazel, kong/runloop/wasm.lua, spec/02-integration/20-wasm/04-proxy-wasm_spec.lua, spec/fixtures/proxy_wasm_filters/tests/src/test_http.rs
~For this to work, it needs https://github.com/Kong/ngx_wasm_module/pull/349 to be merged first.~ The ngx_wasm_module change was merged, so CI should be happy on this one!
=> feat(wasm) set kong.route_id and kong.service_id properties

CHANGELOG.md, kong-3.4.0-0.rockspec
Uses tags/commits from https://github.com/Kong/pgmoon/pull/30.
KAG-1936
=> chore(deps): bump kong-pgmoon from 1.16.1 to 1.16.2

kong/db/schema/others/declarative_config.lua, spec/02-integration/04-admin_api/15-off_spec.lua
No tests here because I don't think we currently have workspace tests in the OSS dbless test suite.
=> fix(dbless): make uniqueness checks workspace-aware

scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt, scripts/explain_manifest/fixtures/amazonlinux-2023-amd64.txt, scripts/explain_manifest/fixtures/debian-10-amd64.txt, scripts/explain_manifest/fixtures/debian-11-amd64.txt, scripts/explain_manifest/fixtures/el7-amd64.txt, scripts/explain_manifest/fixtures/el8-amd64.txt, scripts/explain_manifest/fixtures/el9-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt, scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
This fixes a couple items that were overlooked recently.
=> chore(ci): update build manifests

kong/runloop/wasm.lua
`resty.wasm` -> `resty.wasmx`.
Sibling of https://github.com/Kong/ngx_wasm_module/pull/359
=> chore(wasm): update ffi binding module name

kong-3.5.0-0.rockspec, kong/meta.lua, scripts/release-lib.sh
- chore(scripts) restore release-lib.sh
- release: 3.5.0
=> chore(release): bump version to 3.5.0 as part of the 3.4 Feature Freeze

.github/workflows/build.yml, .github/workflows/release.yml, bin/kong, kong/constants.lua, kong/db/schema/init.lua, kong/pdk/vault.lua, kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua, kong/templates/nginx_kong.lua, kong/templates/nginx_kong_stream.lua, spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/02-integration/02-cmd/02-start_stop_spec.lua, spec/02-integration/02-cmd/14-vault_spec.lua, spec/02-integration/13-vaults/02-env_vault_spec.lua, spec/fixtures/1.2_custom_nginx.template, spec/fixtures/custom_nginx.template, spec/fixtures/custom_plugins/kong/plugins/dummy/handler.lua, spec/fixtures/custom_plugins/kong/plugins/dummy/schema.lua, spec/fixtures/custom_vaults/kong/vaults/test/init.lua, spec/fixtures/default_nginx.template
cherry-pick of https://github.com/Kong/kong/pull/11286
=> [Backport release/3.4.x] fix(vaults): refactor vault pdk and vault ttl code

.github/actions/build-cache-key/action.yml, .github/workflows/build.yml, .github/workflows/build_and_test.yml, .github/workflows/perf.yml, .github/workflows/release.yml
This is a backport of https://github.com/Kong/kong/pull/11299
=> chore(ci): re-use cache key from build workflow (#11299)

.github/workflows/perf.yml
Ensure that perf suites are properly chosen.
=> fix(gha): ensure proper perf suites inputs

kong/runloop/plugins_iterator.lua
This PR is a simplified version of #11164, only some small localizations.
=> style(runloop): localize some functions

spec/02-integration/05-proxy/10-balancer/01-healthchecks_spec.lua
It can not easily to address in EE repo, So I have tag this to #flaky
KAG-1938
=> test(healthcheck): tag healthcheck passive test to flaky

kong/router/atc.lua
* remove the usage of `ipairs`
KAG-2148
=> style(router): remove `ipairs` and optimize router select

build/openresty/openssl/openssl_repositories.bzl
=> fix(build): update the openssl alternate download url

CONTRIBUTING.md, DEVELOPER.md, README.md
=> docs(*): fix broken links

CONTRIBUTING.md
See: https://github.com/Kong/kong/pull/11273#issuecomment-1670920688
=> docs(CONTRIBUTING): perfer `ipairs` to `for` loop

kong/router/atc.lua
This reverts commit 073d2fd54c8049f87a60680a2ee4c3a7ca88b21a.
See: https://github.com/Kong/kong/pull/11273#issuecomment-1670920688
=> Revert "style(router): remove `ipairs` and optimize router select (#11273）

.github/workflows/build_and_test.yml
Outputting kernel message on test failed, which is good for debugging segfault.
- [N/A] There's an entry in the CHANGELOG
=> chore: output kernal message on test failed

kong-3.4.1-0.rockspec, kong/meta.lua
=> chore(version): bump versions to 3.4.1

build/README.md
Adds informations for specific cases that might happen on some environments.
=> docs: improve developer doc

kong/router/atc.lua
=> style(router): move some http only functions

kong/router/atc.lua
=> style(router): simplify logic of  getting http params

scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt, scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt, scripts/explain_manifest/fixtures/debian-10-amd64.txt, scripts/explain_manifest/fixtures/debian-11-amd64.txt, scripts/explain_manifest/fixtures/el7-amd64.txt, scripts/explain_manifest/fixtures/el8-amd64.txt, scripts/explain_manifest/fixtures/el9-arm64.txt, scripts/explain_manifest/fixtures/ubuntu-20.04-amd64.txt
sample of failure: https://github.com/Kong/kong/actions/runs/5993979999
=> fix(manifest): correct manifest after recent refactor

spec/02-integration/06-invalidations/01-cluster_events_spec.lua
update time for time sensitive tests
=> chore(test): time flakiness

kong/router/compat.lua
=> style(router): minor code style clean

kong-3.5.0-0.rockspec, kong/admin_gui/init.lua, kong/admin_gui/utils.lua, kong/conf_loader/init.lua, kong/init.lua, kong/templates/kong_defaults.lua, spec/01-unit/03-conf_loader_spec.lua, spec/01-unit/04-prefix_handler_spec.lua, spec/01-unit/29-admin_gui/01-admin_gui_spec.lua, spec/01-unit/29-admin_gui/02-admin_gui_template_spec.lua, spec/02-integration/17-admin_gui/01-admin-gui-path_spec.lua, spec/02-integration/17-admin_gui/03-reports_spec.lua, spec/helpers.lua
Some changes to the admin GUI implementation in the CE gateway, makes the CE -> EE merge more easily.
Most of the changes are re-position the code blocks, coupling them with the EE code and making git 3-way merger happy, some tests were also refactored
This fix KAG-2245
The coupled PR in the EE repo https://github.com/Kong/kong-ee/pull/6199 has been merged
=> chore(admin-gui): Admin GUI CE/EE unification

.github/workflows/release-and-tests-fail-bot.yml
=> chore(CI): fix incorrect logical operator of the alter bot

kong/db/declarative/import.lua
=> style(db/declarative): small clean for `load_into_cache()`

CHANGELOG/unreleased/kong/luajit_ldp_stp_fusion.yaml
=> docs(changelog): fix changelog entry for #11537

.github/workflows/autodocs.yml, .github/workflows/build.yml, .github/workflows/build_and_test.yml, .github/workflows/buildifier.yml, .github/workflows/perf.yml, .github/workflows/release.yml, .github/workflows/upgrade-tests.yml
Revert #11543 as it causes build failure on some distros https://github.com/Kong/kong/actions/runs/6255442074
=> Revert "chore(deps): bump actions/checkout from 3 to 4"

.github/workflows/label-community-pr.yml
Remove label from PRs that created by organization members.
[KAG-2562](https://konghq.atlassian.net/browse/KAG-2562)
[KAG-2562]: https://konghq.atlassian.net/browse/KAG-2562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ci): automatically label community PRs with author/community

changelog/unreleased/kong/11480.yml, changelog/unreleased/kong/luajit_ldp_stp_fusion.yml
=> chore(changelog): use new style for changelog files

kong/plugins/pre-function/_schema.lua
Adds a description to the prefunction plugin schema.
=> add description field for pre-function plugin

changelog/changelog-template.yaml
=> chore(changelog): make the template more useful

kong-3.4.3-0.rockspec, kong/meta.lua
=> release: 3.4.3

kong/clustering/utils.lua
CE counterpart to https://github.com/Kong/kong-ee/pull/6892
=> fix(clustering): check for role->data_plane

t/05-mlcache/15-renew.t
=> chore(tests): mark one mlcache renew test as flaky

changelog/unreleased/kong/fix-tcp-log-sslhandshake.yml
=> chore(doc): correct changelog grammar

kong-3.6.0-0.rockspec, kong/tools/sha256.lua, kong/tools/utils.lua
separate sha256 functions from tools.utils
=> refactor(tools): separate sha256 functions from tools.utils

changelog/3.5.0/3.5.0.md
Update 3.5.0 changelog for rc3.
=> docs(changelog): update 3.5.0 changelog

kong-3.6.0-0.rockspec, kong/tools/utils.lua, kong/tools/uuid.lua
Separate uuid functions from the big tools.utils module.
=> refactor(tools): separate uuid functions from tools.utils

spec/03-plugins/35-azure-functions/01-access_spec.lua
Backport https://github.com/Kong/kong/pull/11879
FTI-5523
KAG-2912
=> [cherry release/3.4.x] tests(azure-functions): remove usage of mockbin in `azure-functions` tests (#11879)

kong/tools/string.lua, kong/tools/utils.lua
separate string functions from tools.utils
=> refactor(tools): separate string functions from tools.utils

changelog/unreleased/kong/validate_private_key.yml, kong/db/dao/keys.lua, kong/db/schema/typedefs.lua, kong/plugins/acme/client.lua, spec/01-unit/01-db/01-schema/03-typedefs_spec.lua, spec/02-integration/03-db/18-keys_spec.lua
Sister PR https://github.com/Kong/kong-ee/pull/7125
Fix [KAG-390](https://konghq.atlassian.net/browse/KAG-390)
[KAG-390]: https://konghq.atlassian.net/browse/KAG-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(keys): validate public and private key

COPYRIGHT
=> docs(COPYRIGHT): update copyright for 3.5.0

kong-3.6.0-0.rockspec, kong/tools/time.lua, kong/tools/utils.lua
=> refactor(tools): separate time functions from tools.utils

changelog/unreleased/kong/router-report-yield.yml
Adds missing changelog requested here:
https://github.com/Kong/kong/pull/12008#issuecomment-1809618955
=> docs(changelog): cooperatively yield when building statistics of routes

.github/workflows/build_and_test.yml, build/openresty/BUILD.openresty.bazel, kong/plugins/zipkin/README.md, scripts/dependency_services/docker-compose-test-services.yml, spec/01-unit/01-db/01-schema/11-declarative_config/03-flatten_spec.lua, spec/02-integration/02-cmd/10-migrations_spec.lua, spec/02-integration/03-db/15-connection_pool_spec.lua, spec/03-plugins/34-zipkin/zipkin_spec.lua, t/05-mlcache/03-peek.t
cherry-picked from https://github.com/Kong/kong-ee/pull/6358
[KAG-2455](https://konghq.atlassian.net/browse/KAG-2455)
[KAG-2455]: https://konghq.atlassian.net/browse/KAG-2455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests(*): misc robustness improvements cherry-picked from ARM64 tests

kong/tools/ip.lua
=> style(tools): small style fixes for ip module

kong/tools/http.lua, kong/tools/string.lua
=> style(tools): optimize string operations in http module

changelog/unreleased/kong/bump-lua-messagepack-0.5.4.yml, kong-3.6.0-0.rockspec
- improve speed (map)
~- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE~
=> chore(deps): bump lua-messagepack from 0.5.3 to 0.5.4

kong/plugins/datadog/handler.lua
`tools.string.replace_dashes` has better performance.
=> perf(plugins/datadog): use tools.string.replace_dashes

changelog/unreleased/kong/respect-custom-proxy_access_log.yml, kong/cmd/utils/prefix_handler.lua, kong/templates/nginx_kong.lua, spec/01-unit/04-prefix_handler_spec.lua
Backport https://github.com/Kong/kong/pull/12073
=> fix(core): respect custom proxy_access_log (#12073)

spec/helpers.lua
sister PR https://github.com/Kong/kong-ee/pull/7404
In companion with https://github.com/Kong/kong-pongo/pull/474.
KAG-5588
=> chore(helpers): ignore mount points for helpers.clean_prefix

spec/03-plugins/17-ip-restriction/02-access_spec.lua
(cherry picked from commit 2adad05525868d948a16b3ce5953a9846787720f)
=> [backport -> release/3.5.x] tests(plugins): refactor tests to address flakiness

kong/pdk/plugin.lua
=> docs(pdk): fix documentation of kong.plugin.get_id

changelog/unreleased/kong/bump-lua-resty-healthcheck-3.0.1.yml, kong-3.6.0-0.rockspec
bump lua-resty-healthcheck to 3.0.1
https://github.com/Kong/lua-resty-healthcheck/pull/146
FTI-5478
=> chore(deps): bump lua-resty-healthcheck to 3.0.1

DEVELOPER.md
I have fixed the typo error. Please review and merge it.
=> docs(DEVELOPER):fix typo

.github/workflows/release.yml
Fix https://github.com/Kong/kong/actions/runs/7383137417/job/20083881705?pr=12272
=> fix(cd): revert actions versions to work under RHEL 7

kong/conf_loader/listeners.lua
* use `kong.conf_loader.constants`
* use `tools.ip`
=> style(conf_loader): simplify the code of listener parse

kong/conf_loader/listeners.lua
Reverts Kong/kong#12355
See: https://github.com/Kong/kong-ee/pull/7844
=> Revert "style(conf_loader): simplify the code of listener parse"

kong/router/atc.lua, kong/router/fields.lua
=> perf(router): lazy generate field visit functions

changelog/unreleased/kong/support_http_path_segments_field.yml
=> docs(changelog): add description of `http.path.segments.len`

changelog/unreleased/expressions_not_operator.yml
[KAG-3605]
[KAG-3605]: https://konghq.atlassian.net/browse/KAG-3605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(changelog): add changelog entry for "not" operator support in ATC

.github/workflows/backport.yml, .github/workflows/cherry-picks.yml
add the description of the original pull request to backported/cherry-picked PRs
Fix https://konghq.atlassian.net/browse/KAG-3457
=> chore: add original description to backported/cherry-picked PRs

build/openresty/patches/ngx_lua-0.10.26_01-dyn_upstream_keepalive.patch
Just fixes some line numbers in patch.
=> chore(patches): make dynamic upstream keepalive patch apply cleanly

LICENSE, README.md
=> Update copyright date to 2024

changelog/unreleased/kong/add-ai-proxy-telemetry.yml, kong/api/routes/plugins.lua
Adds telemetry for AI/LLM "model" and "provider" usage.
Internal request.
=> feat(ai-proxy): add telemetry for ai-proxy

kong-3.7.0-0.rockspec, kong/meta.lua
=> chore(release): bump version to 3.7 as part of the Feature Freeze

kong/llm/drivers/shared.lua, kong/plugins/ai-proxy/handler.lua, kong/plugins/ai-response-transformer/handler.lua, spec/03-plugins/38-ai-proxy/08-encoding_integration_spec.lua
The package/library for (de-)compressing GZIP has moved in the latest master commit.
This PR fixes `ai-proxy` and `ai-response-transformer` plugins to support the new package name, as well as adding a test to prevent this in future.
Internal issue.
=> fix(ai-proxy): gzip decompression library has moved

COPYRIGHT
Update licenses/copyright file
=> 3.6 copyright

changelog/Makefile, changelog/README.md, changelog/create_pr, changelog/verify-prs
Cherry-pick https://github.com/Kong/kong-ee/pull/7997
FTI-5723
Verified by: https://github.com/Kong/kong/pull/12612
=> chore(release): add changelog automation and verification

changelog/Makefile
Cherry-pick https://github.com/Kong/kong-ee/pull/8323. Verified by https://github.com/Kong/kong/pull/12630.
FTI-5723
=> chore(release): minor improvement to changelog PR automation

changelog/Makefile
Backport https://github.com/Kong/kong/pull/12628
[FTI-5723](https://konghq.atlassian.net/browse/FTI-5723)
[FTI-5723]: https://konghq.atlassian.net/browse/FTI-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [backport -> release/3.5.x] chore(release): minor improvement to changelog PR automation

changelog/Makefile
Backport https://github.com/Kong/kong/pull/12628
[FTI-5723](https://konghq.atlassian.net/browse/FTI-5723)
[FTI-5723]: https://konghq.atlassian.net/browse/FTI-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [backport -> release/3.4.x] chore(release): minor improvement to changelog PR automation

changelog/Makefile
Backport https://github.com/Kong/kong/pull/12628
[FTI-5723](https://konghq.atlassian.net/browse/FTI-5723)
[FTI-5723]: https://konghq.atlassian.net/browse/FTI-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [backport -> release/3.3.x] chore(release): minor improvement to changelog PR automation

changelog/Makefile
Backport https://github.com/Kong/kong/pull/12628
[FTI-5723](https://konghq.atlassian.net/browse/FTI-5723)
[FTI-5723]: https://konghq.atlassian.net/browse/FTI-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [backport -> release/2.8.x] chore(release): minor improvement to changelog PR automation

.github/workflows/release.yml
Reverts Kong/kong#12090
The token is now fixed by @curiositycasualty .
=> Revert "hotfix(cd): skip comment on commit step"

CHANGELOG/unreleased/kong/udp-socket-recycle.yml, build/openresty/patches/lua-resty-dns-0.22_01-destory_resolver.patch, kong/resty/dns/client.lua, spec/02-integration/05-proxy/05-dns_spec.lua
cherry pick from https://github.com/Kong/kong/pull/10691
FTI-5803
=> [backport-2.8.x] fix(dns): fix the UDP socket leaking issue

CONTRIBUTING.md
We now offer digital badges to contributors!
=> docs(readme): remove mentions to contributor t-shirt

CHANGELOG.md, kong/conf_loader/constants.lua, kong/db/schema/init.lua, kong/db/schema/json.lua, spec/02-integration/04-admin_api/14-tags_spec.lua, spec/02-integration/09-hybrid_mode/10-forward-proxy_spec.lua
=> remove repetitive words

changelog/unreleased/kong/log-serializer-receive-latency.yml
https://github.com/Kong/kong-ee/pull/8528
[KAG-3798](https://konghq.atlassian.net/browse/KAG-3798)
[KAG-3798]: https://konghq.atlassian.net/browse/KAG-3798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(changelog): set log serializer changelog entry scope to "PDK"

kong/tools/system.lua
=> style(tools/system): fix typos in error message

README.md
Updating the definition of Kong to highlight the new AI capabilities in addition to APIM.
=> doc(README): updating the definition of Kong with the new AI capabilities

kong/tools/dns.lua
=> style(tools/dns): improve code style for readability

spec/02-integration/01-helpers/03-http_mock_spec.lua
=> tests(http_mock): assert eventually-consistent file condition

changelog/unreleased/kong/feat-jwt-es512.yml
Typo in the Change log file, Addded instead of Added. 
=> fix: typo in feat-jwt-es512.yml change log

DEVELOPER.md
Adding text to DEVELOPER.md for running EmmyLua debugger with VSCode
=> Emmy lua debugger vscode

spec/03-plugins/25-oauth2/04-invalidations_spec.lua
Test flakiness
Cherrypicking for a PR from EE
=> fix(tests): oauth2 flakiness

.github/workflows/changelog-requirement.yml
=> chore(deps): bump tj-actions/changed-files to 44.0.0

.github/workflows/release.yml
Reverts Kong/kong#12747
KAG-4382
=> Revert "chore(deps): bump bazelbuild/setup-bazelisk from 2.0.0 to 3.0.0"

kong.conf.default
=> docs(kong.conf.default): update the description of router_flavor

changelog/unreleased/kong/feat-emmy-debugger.yml, kong/tools/emmy_debugger.lua
=> fix(emmy-lua-debugger): add support status warning for feature

scripts/explain_manifest/suites.py
=> fix(cd): add tests to ensure wasm filters are in place

kong/admin_gui/utils.lua
minor style clean, add a `break` to finish loop ASAP.
=> style(admin_gui): code style minor clean

kong/router/fields.lua
Small code clean, no any new feature or change.
=> style(router/atc): move http vars into proper scope

COPYRIGHT
Updated copyright file in order to prepare for the 3.7 release
=> docs(copyright): update copyright file

COPYRIGHT
This is a forward-port of https://github.com/Kong/kong/pull/13091 to the master branch
=> docs(copyright): update copyright

spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
=> tests(integration): 09-config-compat_spec accessing undefined variable utils

changelog/unreleased/kong/feat-dont-allow-priority-with-others.yml, changelog/unreleased/kong/fix-route-set-priority-with-others.yml
Change type from 'feature' to 'bugfix'.
KAG-4411
=> docs(changelog): fix change log entry of #13021

DEVELOPER.md
=> docs(DEVELOPER.md): fix typo

kong/templates/nginx_kong.lua
ngx.location.capture was what Kong meant to put here.
=> style(templates): fix comment typo

changelog/unreleased/kong/fix-ai-proxy-shared-state.yml, kong-3.7.1-0.rockspec, kong/llm/init.lua, kong/llm/schemas/init.lua, kong/plugins/ai-proxy/handler.lua, kong/plugins/ai-request-transformer/handler.lua, kong/plugins/ai-response-transformer/handler.lua, spec/03-plugins/39-ai-request-transformer/01-transformer_spec.lua, spec/03-plugins/40-ai-response-transformer/01-transformer_spec.lua, spec/03-plugins/40-ai-response-transformer/02-integration_spec.lua
=> Backport #13028 to release/3.7.x

t/01-pdk/02-log/00-phase_checks.t, t/01-pdk/02-log/05-set_serialize_value.t, t/01-pdk/04-request/21-get_uri_captures.t, t/01-pdk/08-response/05-set_header.t, t/01-pdk/08-response/11-exit.t, t/01-pdk/08-response/13-error.t, t/01-pdk/10-nginx/02-get_statistics.t, t/01-pdk/15-tracing/01-context.t, t/03-dns-client/02-timer-usage.t, t/04-patch/01-ngx-buf-double-free.t, t/04-patch/02-ngx-read-body-block.t
Just reindex Test::Nginx tests with `reindex` found at: https://github.com/openresty/openresty-devel-utils/blob/master/reindex
KAG-4683
=> style(tests): reindex Test::Nginx tests

.github/workflows/add-pongo-release.yml
feat(ci): automatically add release version to Pongo
Cherry-pick of https://github.com/Kong/kong-ee/pull/9521.
Fix #_[FTI-6032]_
[FTI-6032]: https://konghq.atlassian.net/browse/FTI-6032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ci): automatically add release version to Pongo

kong/cache/warmup.lua
=> fix(core) correct noisy acl warmup

kong/runloop/balancer/latency.lua
=> chore(balancer/latency): update variable name

changelog/unreleased/kong/yield-in-gzip.yml
=> docs(changelog): typofix for #13338

kong/runloop/plugin_servers/pb_rpc.lua
Handle pluginserver socket timeout.
=> fix(pluginserver): handle socket timeout

spec/01-unit/31-simdjson/02-yield_spec.lua
Add more test cases for #13421.
=> tests(core): add test cases for simdjson yielding

kong/llm/proxy/handler.lua
Fix [KAG-5067](https://konghq.atlassian.net/browse/KAG-5067)
[KAG-5067]: https://konghq.atlassian.net/browse/KAG-5067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(llm): remove duplicate snippet after rebase

changelog/unreleased/kong/ai-proxy-model-header.yml, kong/clustering/compat/removed_fields.lua, kong/llm/proxy/handler.lua, kong/plugins/ai-proxy/schema.lua, spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua, spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua, spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua, spec/03-plugins/38-ai-proxy/04-cohere_integration_spec.lua, spec/03-plugins/38-ai-proxy/05-azure_integration_spec.lua, spec/03-plugins/38-ai-proxy/06-mistral_integration_spec.lua
=> feat(ai-proxy): add option to return model name in response header

changelog/unreleased/kong/bump-lua-protobuf.yml, kong-3.8.0-0.rockspec
- fix(lpb_tointegerx): filter out illegal formats, such as, #a, #-aaa...
KAG-5094
=> chore(deps): bump lua-protobuf to 0.5.2

kong/llm/schemas/init.lua, spec/03-plugins/38-ai-proxy/02-openai_integration_spec.lua, spec/03-plugins/38-ai-proxy/03-anthropic_integration_spec.lua, spec/03-plugins/38-ai-proxy/04-cohere_integration_spec.lua, spec/03-plugins/38-ai-proxy/05-azure_integration_spec.lua, spec/03-plugins/38-ai-proxy/06-mistral_integration_spec.lua, spec/03-plugins/38-ai-proxy/07-llama2_integration_spec.lua
=> chore(llm): change llm.auth.allow_override option default value to false

spec/helpers.lua
=> tests(helper): reduce the count of local variables in top level

kong/clustering/compat/removed_fields.lua, spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
Fixes [KAG-5232](https://konghq.atlassian.net/browse/KAG-5232)
KAG-5232
[KAG-5232]: https://konghq.atlassian.net/browse/KAG-5232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ai-transformers): fix compat with LT 3.8.0

COPYRIGHT
Update 3.8.0 copyright.
KAG-5216
=> docs(copyright): update 3.8.0 copyright

build/toolchain/managed_toolchain.bzl, build/toolchain/repositories.bzl, scripts/explain_manifest/fixtures/amazonlinux-2-amd64.txt, scripts/explain_manifest/fixtures/amazonlinux-2023-arm64.txt, scripts/explain_manifest/fixtures/el9-arm64.txt, scripts/explain_manifest/fixtures/ubuntu-22.04-arm64.txt
=> chore(bazel): bump crosstool-ng-actions from 0.7.0 to 0.8.0

kong-3.8.1-0.rockspec, kong/meta.lua
Bump the version numbers as part of the post-3.8.0 release
=> release: 3.8.1

CHANGELOG.md
Assemble 3.8.0 changelog into CHANGELOG.md.
KAG-5216
=> docs(changelog): assemble 3.8.0 changelog into CHANGELOG.md

CHANGELOG.md
assemble 3.7.1 and 3.8.0 changelogs into CHANGELOG.md.
KAG-5216
=> Assemble 3.7.1 and 3.8.0 changelogs into CHANGELOG.md

build/BUILD.bazel, build/openresty/BUILD.openresty.bazel
[KAG-4445](https://konghq.atlassian.net/browse/KAG-4445)
cherrypicked from https://github.com/Kong/kong-ee/pull/10226
[KAG-4445]: https://konghq.atlassian.net/browse/KAG-4445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(build): use a more reliable way to replace websocket library

kong/constants.lua, kong/db/dao/workspaces.lua, kong/db/schema/others/declarative_config.lua, spec/internal/db.lua
=> default ws_id if not exists in lmdb

changelog/unreleased/kong/fix-ai-proxy-multi-modal-azure.yml, kong/llm/drivers/shared.lua
=> fix(llm): allow multi-modal requests in azure

.github/workflows/release.yml
=> chore(ci): add docker image to the workflow summary

kong/clustering/services/sync/rpc.lua
=> fix(clustring): inc sync add ws

kong/api/routes/debug.lua
=> feat(api): remove endpoint of dynamic log level

kong/global.lua
=> fix(clustering): disable privileged events when inc sync

spec/02-integration/19-incrmental_sync/01-sync_spec.lua
KAG-5729
KAG-5736
KAG-5755
KAG-5770
KAG-5757
=> tests(clustering/rpc): add test cases for inc sync

spec/03-plugins/09-key-auth/04-hybrid_mode_spec.lua
=> tests(clustering): enable incremental sync in key-auth

spec/02-integration/09-hybrid_mode/09-node-id-persistence_spec.lua
=> tests(clustering): enable incremental sync in node-id-persistence_spec

spec/02-integration/07-sdk/03-cluster_spec.lua, spec/02-integration/09-hybrid_mode/03-pki_spec.lua, spec/02-integration/09-hybrid_mode/04-cp_cluster_sync_spec.lua, spec/02-integration/09-hybrid_mode/05-ocsp_spec.lua, spec/02-integration/09-hybrid_mode/08-lazy_export_spec.lua, spec/02-integration/09-hybrid_mode/13-deprecations_spec.lua
The feature is not a part of 3.9 release. Temporarily disable the tests.
KAG-5876
=> tests(sync): temporarily disable incremental sync tests

kong/llm/plugin/base.lua
no changelog needed as it's for unreleased changes.
unit test for the framework including this case will come in later PR.
=> fix(llm): only send gzip header when response is from upstream

changelog/unreleased/kong/feat-add-huggingface-llm-driver.yml, kong-3.9.0-0.rockspec, kong/llm/drivers/huggingface.lua, kong/llm/drivers/shared.lua, kong/llm/schemas/init.lua, spec/03-plugins/38-ai-proxy/10-huggingface_integration_spec.lua, spec/fixtures/ai-proxy/huggingface/llm-v1-chat/requests/good.json, spec/fixtures/ai-proxy/huggingface/llm-v1-chat/responses/bad_request.json, spec/fixtures/ai-proxy/huggingface/llm-v1-chat/responses/bad_response_model_load.json, spec/fixtures/ai-proxy/huggingface/llm-v1-chat/responses/bad_response_timeout.json, spec/fixtures/ai-proxy/huggingface/llm-v1-chat/responses/good.json, spec/fixtures/ai-proxy/huggingface/llm-v1-chat/responses/unauthorized.json, spec/fixtures/ai-proxy/huggingface/llm-v1-completions/requests/good.json, spec/fixtures/ai-proxy/huggingface/llm-v1-completions/responses/bad_request.json, spec/fixtures/ai-proxy/huggingface/llm-v1-completions/responses/good.json, spec/fixtures/ai-proxy/huggingface/llm-v1-completions/responses/unauthorized.json
=> Feat(ai huggingface)

CHANGELOG.md
Adds the 3.8.1 entries to the CHANGELOG
=> docs(changelog): Update changelog for 3.8.1

kong/clustering/rpc/manager.lua
=> fix(clustering/rpc): remove header x_kong_node_id

spec/02-integration/07-sdk/03-cluster_spec.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua, spec/02-integration/09-hybrid_mode/03-pki_spec.lua, spec/02-integration/09-hybrid_mode/04-cp_cluster_sync_spec.lua, spec/02-integration/09-hybrid_mode/05-ocsp_spec.lua, spec/02-integration/09-hybrid_mode/08-lazy_export_spec.lua, spec/02-integration/09-hybrid_mode/13-deprecations_spec.lua
KAG-5918
KAG-5876
See: #13906 #13876
=> tests(clustering): enable incremental sync in hybrid mode

.github/workflows/release.yml
=> chore(cd): run CD in ubuntu-24.04

kong/clustering/rpc/concentrator.lua, kong/clustering/rpc/future.lua, kong/clustering/rpc/json_rpc_v2.lua, kong/clustering/rpc/manager.lua, kong/clustering/rpc/socket.lua
=> refactor(clustering/rpc): constant for json rpc version

COPYRIGHT
=> docs(COPYRIGHT): update copyright for 3.9.0

CHANGELOG.md
Consolidate the 3.9.0 changelog entries into the central place CHANGELOG.md file.
=> docs(changelog): add 3.9.0 changelog entries

CHANGELOG.md, changelog/3.9.0/3.9.0.md
=> docs(changelog): update 3.9.0 changelog (#14016)

README.md
Adds some useful references to Konnect in the getting started to offer an easier solution for some users.
=> Add useful references to Konnect during getting started

kong/clustering/rpc/manager.lua, kong/clustering/services/sync/rpc.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
=> feat(clustering/rpc): add dp labels support

kong/clustering/rpc/manager.lua, kong/clustering/services/sync/rpc.lua, spec/02-integration/09-hybrid_mode/01-sync_spec.lua
KAG-6084
This PR follows #14046.
=> feat(clustering/rpc): add support for cert details

kong/pdk/vault.lua
KAG-6036
It is a follow up of #14025
=> style(pdk): rename some variables

kong/clustering/services/sync/rpc.lua
=> fix(clustering/rpc): check deltas if it is nil

.github/workflows/backport-v2.yml, .github/workflows/cherry-picks-v2.yml, .github/workflows/labeler-v2.yml
=> fix(workflow): rename workflows

kong/clustering/services/sync/rpc.lua
=> fix(clustering/rpc): sync if versions arent equal

spec/02-integration/09-hybrid_mode/11-status_spec.lua
KAG-5994 KAG-5894
This PR will revert the changes of #14035
=> tests(clustering): simplify hybrid status tests

spec/03-plugins/11-correlation-id/02-schema_spec.lua
Reverts Kong/kong#14142
It causes flaky.
=> Revert "tests(clustering): enable rpc sync on test"

kong/dns/client.lua
Cherry-picks changes to the new dns client that bring advanced tracing support in EE.
(cherry picked from commit 39d381b0a9523ffb2fda2cdea315f1ee47a801bf)
KAG-6277
=> [cherry-pick kong-ee#11258 ] chore(*): new dns client consistency with EE

spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
=> tests(clustering/rpc): enable rpc sync for config compat

changelog/unreleased/kong/bump-kong-nginx-module.yml, changelog/unreleased/kong/bump-lua-resty-simdjson.yml, changelog/unreleased/kong/bump-snappy-library.yml
Adds some changelogs.
KAG-6382
=> chore(changelog): add some entries to changelog

kong/clustering/rpc/manager.lua
=> fix(clustering/rpc): small typo fix for metacall

kong/clustering/services/sync/validate.lua
This PR will make the code clean to reduce the conflict of CE and EE.
KAG-6109
See: https://github.com/Kong/kong-ee/commit/1a7e91644a2ffcfbd8c4dafb49fa59a5c6be34ed
=> refactor(clustering/rpc): clean for validate_deltas()

spec/03-plugins/09-key-auth/01-api_spec.lua, spec/03-plugins/09-key-auth/02-access_spec.lua, spec/03-plugins/09-key-auth/03-invalidations_spec.lua, spec/03-plugins/10-basic-auth/02-api_spec.lua, spec/03-plugins/10-basic-auth/03-access_spec.lua, spec/03-plugins/10-basic-auth/04-invalidations_spec.lua, spec/03-plugins/10-basic-auth/05-declarative_spec.lua, spec/03-plugins/13-cors/01-access_spec.lua, spec/03-plugins/18-acl/01-api_spec.lua, spec/hybrid.lua
Manually cherry-pick from https://github.com/Kong/kong-ee/pull/11467
Fix KAG-6446
=> [cherry-pick -> master] tests(clustering/sync): add hybrid mode test for most used plugins

kong/resty/dns/client.lua, kong/timing/init.lua
Cherry-pick EE changes: https://github.com/Kong/kong-ee/pull/10989
=> [cherry-pick -> master] perf(core): small performance patches to timing and dns client

kong/clustering/services/sync/hooks.lua
=> refactor(clustering/rpc): remove CP's duplicated sync event

kong/init.lua, kong/runloop/handler.lua, kong/runloop/plugins_iterator.lua
Cherry-picks two commits from EE:
https://github.com/Kong/kong-ee/pull/11845
https://github.com/Kong/kong-ee/pull/11855
=> [cherry-pick -> master] iterator performance improvements

kong-3.10.0-0.rockspec, kong/db/strategies/off/plugins.lua, kong/db/strategies/off/services.lua, spec/01-unit/01-db/13-off/01-select-by-ca-certificate_spec.lua
Cherry-picked from https://github.com/Kong/kong-ee/pull/12072
- [ N/A] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
_[KAG-6787]_
[KAG-6787]: https://konghq.atlassian.net/browse/KAG-6787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(db): add missing func select_by_ca_certificate for off strategy

changelog/unreleased/kong/fix-jwt-www-authenticate-header-delimiter.yml, kong/plugins/jwt/handler.lua
=> style(plugin/jwt): correct code style for #14437

.github/workflows/license-notice-check.yml, kong/plugins/ai-prompt-decorator/filters/decorate-prompt.lua, kong/plugins/ai-prompt-guard/filters/guard-prompt.lua, kong/plugins/ai-prompt-template/filters/render-prompt-template.lua, kong/plugins/ai-request-transformer/filters/transform-request.lua, kong/plugins/ai-response-transformer/filters/transform-response.lua, kong/runloop/upstream_retry.lua, kong/tools/sandbox/environment/handler.lua, kong/tools/sandbox/environment/init.lua, kong/tools/sandbox/environment/lua.lua, kong/tools/sandbox/environment/schema.lua, kong/tools/sandbox/init.lua, kong/tools/sandbox/kong.lua, kong/tools/sandbox/require/handler.lua, kong/tools/sandbox/require/init.lua, kong/tools/sandbox/require/lua.lua, kong/tools/sandbox/require/schema.lua, spec/01-unit/01-db/11-declarative_lmdb_spec.lua, spec/03-plugins/03-http-log/05-old-plugin-compatibility_spec.lua, spec/03-plugins/25-oauth2/05-kdf_spec.lua, spec/fixtures/custom_plugins/kong/plugins/preserve-nulls/handler.lua, spec/fixtures/custom_plugins/kong/plugins/preserve-nulls/schema.lua
=> chore(*): remove enterprise license notice

spec/02-integration/18-hybrid_rpc/04-concentrator_spec.lua, spec/fixtures/custom_plugins/kong/plugins/rpc-concentrator-test/handler.lua, spec/fixtures/custom_plugins/kong/plugins/rpc-concentrator-test/schema.lua
=> tests(clustering/rpc): add test cases for rpc concentrator

COPYRIGHT
Update copyright for 3.9.1
KAG-7109
=> docs(COPYRIGHT): update copyright for 3.9.1

changelog/unreleased/kong/add_ai_gemini_boto_support.yml, changelog/unreleased/kong/fix-ai-azure-incorrect-path-overriding.yml, changelog/unreleased/kong/fix_ai-logger-error-handling.yml, changelog/unreleased/kong/fix_ai-plugins-templating.yml, changelog/unreleased/kong/fix_ai-streaming-function-calls.yml, changelog/unreleased/kong/fix_ai_proxy_config_issue.yml
address review comments in #14582
KAG-7109
=> docs(changelog): reword changelog entries based on the review comments

CHANGELOG.md
=> docs(changelog): consolidate 3.9.1 changelog into CHANGELOG.md

CHANGELOG.md
Consolidate 3.9.1 changelog into CHANGELOG.md.
KAG-7109
=> docs(changelog): consolidate 3.9.1 changelog into CHANGELOG.md (#14596)

COPYRIGHT, LICENSE, README.md
=> docs: bump new year

README.md
=> doc(readme): Fix Twitter Follow badge link
